import type { CatalogKey } from "./en.ts";

/** بلوچی — AI-drafted, founder-reviewed copy (plan D4). */
export const bal: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو چہے؟",
  "nav.features": "خصوصیتان",
  "nav.howItWorks": "چوں کار بیت",
  "nav.vision": "ماہی وژن",
  "nav.signIn": "داخل بیت",
  "nav.getEarlyAccess": "اولین رسایی بگیرت",
  "nav.openMenu": "مینیو گُش کن",
  "nav.closeMenu": "مینیو بند کن",
  "common.languageSwitcherLabel": "زبان بدیل کنیت",
  "notFound.title": "صفحه نه پیدہ بوتگنت",
  "notFound.body": "ای صفحه کہ تئی تلاش کنیت اے ما وجود انت یا منتقل بوتگانت.",
  "notFound.backHome": "گراں اگروپیو ئی سر",
  "common.builtForPakistan": "پاکستان ئے خاطر رچ کورتہ",
  "common.productOfAplinode": "اپلینوڈ ئی مہصول",
  "home.hero.eyebrow": "مصنوعی ذہانت ئان رچ کورتہ فارمی پوہگی ئی پلیٹ فارم",
  "home.hero.titleLead": "شعورین کاشتکاری ئے خاطر",
  "home.hero.titleAccent": "پوہگی",
  "home.hero.subtitle": "یک پلیٹ فارم کہ اے آئی مشورہ گر، سیٹلائٹ مانیٹرنگ، بازار ئی قیمت ئان اے تئی فارم ئی ریکارڈ ئان یک جاگاہ ئا جمع کنت — ڈیٹا ئا روشن فیصلہ ئان ئا بدلنت، تئی خودی زبان ئے تہا.",
  "home.hero.ctaSecondary": "چم ببین اے چوں کار بیت",
  "home.hero.imageAlt": "کاشتکار کھیت ئے تہا ٹیبلٹ ئا اگروپیو کارمنت کنوچی",
  "home.hero.readingCrop": "فصل ئی تندرسی",
  "home.hero.readingWeather": "ہوا ئی حال",
  "home.hero.readingSoil": "مٹی ئی نمے",
  "home.hero.noteExcellent": "بوڑ انت",
  "home.hero.noteClearSky": "پاکی اسمان",
  "home.hero.noteOptimal": "جوڑ انت",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم ئی توانائی ئان",
  "home.ticker.cropDoctor": "اے آئی فصل ئی ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "بازار ئی قیمت ئانی پوہگی",
  "home.ticker.weatherAdvisories": "ہوا ئے جوندا مشورہ ئان",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ئی ریکارڈ ئان",
  "home.ticker.advisoryLanguages": "7 زبان ئان ئے تہا مشورہ",
  "home.ticker.pestAlerts": "کیڑا ئانی خطرے ئی خبر",
  "home.ticker.offlineSms": "آف لائن + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری ئی فیصلہ ئان اندازہ ئی کھیل نہ بنت",
  "home.problem.subtitle": "سماں پاکستان ئے تہا کاشتکاران رواج، محلئی مشورہ ئان اے پچہ کورتہ معلومات ئان بوڑ خطرناک فیصلہ ئان کننت۔ نقصان فصل چنیگ ئے وتی پدا بیت۔",
  "home.problem.item1Title": "نامیقین وقت",
  "home.problem.item1Body": "آب، کودہ، دوا، توی، چنیگ — اہم وخت ئان ہمچوش اندازہ ئان پہ پہ کنگ بنت، کہ فصل ئا کم کنت اے خرچ ئا ضائع کنت۔",
  "home.problem.item2Title": "ورتہ فارم ئی ریکارڈ",
  "home.problem.item2Body": "سال ئانی پوہگی یادداشت اے پچہ کورتہ کتاب ئان ئے تہا منت۔ پروش سال ئے کہ کار ئے کنگ بوت، اے سال ئے آموختن ئے مشکل انت۔",
  "home.problem.item3Title": "پچہ کورتہ مشورہ ئان",
  "home.problem.item3Body": "ہمسائہ ئان، دکانداران اے ویڈیو ئان گشت ئان جواب ئے دنت — لیکن کماچ کاشتکار ئی فصل، مٹی، ہوا اے محل ئے جوندا انت۔",
  "home.problem.kicker": "اندازہ ئی قیمت فصل چنیگ ئے وتی پدا بیت",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تئی فارم ئی پوہگی،",
  "home.solution.titleB": "یک جاگاہ ئے تہا",
  "home.solution.subtitle": "سماں سال ئے خاطر یک پوہگی ئی پلیٹ فارم — مشورہ، ریکارڈ، ہوا اے بازار تئی زمین ئی ڈیٹا ئان کار ئا کننت، عام مشورہ ئان ئان نہ。",
  "home.solution.card1Title": "چہ کار کنگ",
  "home.solution.card1Body": "آب، کودہ، کیڑا ئی مار اے چنیگ ئے وخت ئے خاطر خودی مشورہ ئان — تئی فصل اے حالات ئے جوندا۔",
  "home.solution.card1Answer": "ای کھیت، ای ہفتہ ئے خاطر روشن مشورہ۔",
  "home.solution.card2Title": "چیرو کار کنگ",
  "home.solution.card2Body": "ہوا ئی رہنمائی بتگنت کار چیرو کنگ بیت، کہ غلط وخت اے اچاتک حالات تئی فصل ئا نہ کنت۔",
  "home.solution.card2Answer": "وخت رستین ہوا اے فصل ئی وڈتگ ئے جوندا۔",
  "home.solution.card3Title": "چہ کار بوتگنت",
  "home.solution.card3Body": "ہر کار — آب، ان پٹ، مرضی، خرچ، چنیگ — ترتیب داتہ ریکارڈ ئے تہا محفوظ کنگ بنت کہ ہر سال ئا زیات شعورین کنت۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ دستیاب۔",
  "home.features.eyebrow": "پلیٹ فارم ئی دنہ",
  "home.features.titleA": "بوڑتہ انجن ئان،",
  "home.features.titleB": "یک پوہگین پلیٹ فارم",
  "home.features.subtitle": "تئی خودی لفظ ئان ئے تہا اولین سوال ئان سمما سال ئی ریکارڈ ئان ئا — ہر توانائی بلئی ئا قوت دنت۔",
  "home.features.advisorModule": "ماڈیول 01 · مشورہ گر",
  "home.features.advisorTitle": "اے آئی کاشتکاری ئی مشورہ گر",
  "home.features.advisorTopics": "آب · کودہ · کیڑا اے مرضی · چنیگ",
  "home.features.advisorBadge": "رومن بلوچی",
  "home.features.advisorMockAria": "زیڑین پتر ئانی گندم ئے بابت اگروپیو مشورہ گر ئے نا نمونہ گفتگو",
  "home.features.advisorUserMsg": "منی گندم ئی پتر زیڑ بیتانت — چہ کنم؟",
  "home.features.advisorReplyTitle": "زیڑین پتر — دو عام دلیل ئان:",
  "home.features.advisorReplyCause1": "آب ئی کمی",
  "home.features.advisorReplyCause1Rest": "— سردین وخت ئان ئے تہا، سوچارے 9 بجے ئے پہ آب دنت۔",
  "home.features.advisorReplyCause2": "نائٹروجن ئی کمی",
  "home.features.advisorReplyCause2Rest": "— بوڑتہ پتر ئان اول ئا چک انت؛ لوٹ انت تہ یوریا دنت۔",
  "home.features.advisorReplyFooter": "اگر پتر ئانی تہئا زیڑین لیر ئان نظر انت، عکس روانہ کنت — man مرض ئی تشخیص کنم۔",
  "home.features.advisorInputPlaceholder": "تئی سوال لکھ یا بگو…",
  "home.features.advisorFooter": "تئی فصل ئے بابت چی بیت گشت — روچمرہ سوال ئان خوش آمدید۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ئی ریکارڈ",
  "home.features.recordsDesc": "ہر کار ترتیب ئا درج — کہ مشورہ تئی خودی زمین ئان آموکت۔",
  "home.features.record1Activity": "آب",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتر ئی سکین",
  "home.features.record3Detail": "چی مرض نہ بوت",
  "home.features.recordsCropTag": "گندم · ربیع سال",
  "home.features.languageModule": "ماڈیول 03 · زبان",
  "home.features.languageTitle": "تئی زبان، تئی لفظ",
  "home.features.languageDesc": "چی سوچیت اے چت گوش یا لکھ — تکنیکی انگریز ئے لوٹ ننت۔",
  "home.features.weatherModule": "ماڈیول 04 · ہوا",
  "home.features.weatherTitle": "ہوا ئاناگ رہنمائی",
  "home.features.weatherDesc": "مشورہ تئی سرا پہنگ بوتگئی پہ رستین حالات ئان چک بیت — جنگ ئے پہروا سپرے کرت تہ سارا کودہ وہہ ویلیت۔",
  "home.features.weatherMockAria": "پنج روچ ئی پیش بینی کہ پنجشمبر ئا سپرے ئی بند ئا نمایاں بیت",
  "home.features.dayMon": "دوشنبہ",
  "home.features.dayTue": "سہ‌شنبہ",
  "home.features.dayWed": "چارشنبہ",
  "home.features.dayThu": "پنجشنبہ",
  "home.features.dayFri": "آدینه",
  "home.features.holdSpray": "سپرے بند کن",
  "home.features.weatherLegend": "محلئی ہوا ئی پیش بینی ئان مشورہ ئی روچ نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودہگ بیت — سمہ توانائی ئان ببین",
  "home.journey.eyebrow": "اے چوں کار بیت",
  "home.journey.title": "یک سوال سال ئا پہ کورت",
  "home.journey.subtitle": "تئی اولین سوال ئان مکمل، پوہگین فارم ئی تاریخ ئا سادہ راہ۔",
  "home.journey.step1Title": "تئی فارم شامل کن",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل ئے خاطر محل، فصل اے بنیادی تفصیل ئان لکھ۔",
  "home.journey.step2Title": "اے آئی ئان بپرس",
  "home.journey.step2Body": "تئی سوال اے زبان ئے تہا لکھ یا بگو کہ تئی خودی تہا بوڑ آرام ئا اتی۔",
  "home.journey.step3Title": "رہنمائی بگیر",
  "home.journey.step3Body": "تئی فصل، ہوا، محل اے فارم ئی تاریخ ئے جوندا مشورہ بگیر۔",
  "home.journey.step4Title": "کار درج کن",
  "home.journey.step4Body": "تھورین ٹیپ ئان ئے تہا آب، کودہ، دوا یا مرض درج کن۔",
  "home.journey.step5Title": "تاریخ ئا رچ کن",
  "home.journey.step5Body": "ہر ریکارڈ آتکہ مشورہ ئان ئا زیات پوہگین اے جوڑا کنت۔",
  "home.journey.step6Title": "چستگیری جاری دار",
  "home.journey.step6Body": "سمما سال ئے اندا ریکارڈ ئان ببین اے رفت ئا چم دارات۔",
  "home.matrix.eyebrow": "سمہ توانائی ئان",
  "home.matrix.title": "لوڑٹین ئان حیران کن ئان ئا",
  "home.matrix.subtitle": "ہر خاصیت فصل ئا پہ دار بیت، خرچ ئا کم کنت یا آمدنی ئا ودہگ بیت۔ اے ئا تقویم ئے ونش — ہر درجہ پرچین ئے سر رچ کورتہ۔",
  "home.matrix.capabilitiesLabel": "توانائی ئان",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی سطح",
  "home.matrix.t1f1Title": "اے آئی فصل ئی مرض ئی پہچانک",
  "home.matrix.t1f1Body": "متاثرہ پتر ئی عکس اپلوڈ کن اے فوری تشخیص، شدت اے دوا ئی مشورہ بگیر۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت ئی چستگیری",
  "home.matrix.t1f2Body": "تئی کھیت ئی حد ئا نشان کن اے واجہ سینٹینل-2 عکس ئان ئان این ڈی وی آئی ئاناگ فصل ئی تندرسی ببین۔",
  "home.matrix.t1f3Title": "پوہگین ہوا ئی مشورہ",
  "home.matrix.t1f3Body": "محلئی ہوا ئی پیش بینی تئی فصل اے وڈتگ ئے مرحلہ ئے جوندا ملے روزانہ کار ئی مشورہ بیت۔",
  "home.matrix.t1f4Title": "بازار ئی قیمت ٹریکر اے پیش بینی",
  "home.matrix.t1f4Body": "نیڑاگ بازار ئی قیمت ئان اے آئی میلان ئان ئے جوندا ببین، کہ رستین وخت ئے تہا فروش کنیت۔",
  "home.matrix.tier2Name": "امتیازی خاصیت ئان",
  "home.matrix.tier2Badge": "نمایاں",
  "home.matrix.t2f1Title": "محلئی زبان ئانی آواز ئی چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی ئے وانگوں بگو یا لکھ — جواب اے زبان ئے تہا بشنو کہ تئی خودی بہتر سمگیت۔",
  "home.matrix.t2f2Title": "سرحکومتی اسکیم ئی جوڑاک",
  "home.matrix.t2f2Body": "تئی تفصیل ئان لکھ اے ہر اہل اسکیم ئا پہ کن — دستاویز ئان اے درخواست ئی لنک ئان ئے جوندا۔",
  "home.matrix.t2f3Title": "فصل ئی سفارش ئی انجن",
  "home.matrix.t2f3Body": "ای سال ئے تہا تئی مٹی، ہوا، بازار ئی لوٹ اے بجٹ ئے جوندا بوڑ منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم ئی نفع/نقصان ئی حسابگر",
  "home.matrix.t2f4Body": "اٹکلین اے رستین خرچ ئان، حاصل، آمدنی اے نفع — بریک ایون اے آر او آئی ئے جوندا۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم اے ماہر ئی رابطہ",
  "home.matrix.t2f5Body": "سوال ئان شی کن، عکس ئان شریک کن، ہمدرہ کاشتکار ئان اے تصدیق کورتہ ماہر ئان ئان جواب بگیر۔",
  "home.matrix.tier3Name": "حیران کن ئان",
  "home.matrix.tier3Badge": "سمہ ئان ئے پہروا",
  "home.matrix.t3f1Title": "سیٹلائٹ ئی تبدیلی ئی پہچانک",
  "home.matrix.t3f1Body": "سلائیڈر ئے جوندا وخت ئے نا سیٹلائٹ عکس ئان موازنہ کن — وڈتگ، نقصان یا قبضہ ٹریک کن۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا ئی خطرے ئی پیش بینی",
  "home.matrix.t3f2Body": "ہوا، فصل ئی مرحلہ اے تاریخ ئی بنیاد ئا احتمالی حملہ ئے پہروا اولین خبرداری۔",
  "home.matrix.t3f3Title": "آواز ئی فون کال موڈ",
  "home.matrix.t3f3Body": "واجہ نمبر ئا کال کن، سوال بگو، تئی زبان ئے تہا مشورہ بشنو — سمارٹ فون ئے لوٹ ننت۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ ئی اندازہ",
  "home.matrix.t3f4Body": "پائیدار طریقہ ئان درج کن اے رضاکارانہ بازار ئان ئان کاربن کریڈٹ ئی اندازہ بگیر۔",
  "home.matrix.t3f5Title": "آف لائن پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت ئے تہا آف لائن کار بیت، کنکشن ئے نا سنک بیت، کمزور نیٹ ئے تہا ایس ایم ایس خبر دنت۔",
  "home.vision.eyebrow": "دیدگاہ",
  "home.vision.titleA": "پاکستان ئی خاطر رچ کورتگ.",
  "home.vision.titleB": "دنیا ئی خاطر تیار.",
  "home.vision.pkTitle": "اول پاکستان ئی روش",
  "home.vision.pkBody": "اولین نسخہ پاکستان ئی کھیت ئان ئی خاطر ڈیزائن بوتگیت: محلئی فصل ئان، محلئی زبان ئان، رستین کاشت ئی روش ئان اے رستین کھیت ئی حالات۔",
  "home.vision.pkPoint1": "محلئی فصل اے اقلیم ئی پوہگ",
  "home.vision.pkPoint2": "اردو، پنجابی، پښتو، سندی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "رستین کاشتکار ئانی رائے ئانا بہتر بوتگیت",
  "home.vision.worldTitle": "جہانی وسعت ئی دیدگاہ",
  "home.vision.worldBody": "جوڑ ئے خاطر رچ بوتگ۔ چہ پلیٹ فارم پختہ بیت نئین ملکت ئا، زبان ئانا، فصل ئانا اے اقلیم ئانا ئا کش بیت — نوکین سر ئانا رچ کورت ئے تہا۔",
  "home.vision.worldPoint1": "ہر ملک ئی زرعی پوہگ",
  "home.vision.worldPoint2": "وداگ زبان ئان اے محلئی فصل ئان",
  "home.vision.worldPoint3": "ڈونگین ڈیٹا ئی جوڑ ئان اے تجزیہ ئان",
  "home.users.title1": "انفرادی کاشتکار ئان",
  "home.users.desc1": "چھوٹ اے منزلگین فارم ئان کہ رستین مشورہ اے ہر کار ئی ترتیب ئانا ریکارڈ لوٹ انت۔",
  "home.users.title2": "تجارتی فارم ئان",
  "home.users.desc2": "زرعی سودا ئان کہ ترتیب ئانا معلومات، فیصلہ ئی مدد اے ٹیم ئی ریکارڈ ئان لوٹ انت۔",
  "home.users.title3": "ایکو سسٹم ئی شرکا",
  "home.users.desc3": "ان پٹ ئی دینکان، کوآپریٹو، بیمہ اے وسیع ئی خدمت ئان کہ وخت ئے نا پلیٹ فارم ئے نا گونڈ بنت۔",
  "home.users.tagline": "اول کاشتکار ئان ئی خاطر ڈیزائن بوتگ — ایکو سسٹم ئے نا وڈاگ",
  "home.cta.eyebrow": "اولین رسے",
  "home.cta.title": "تئی فارم ئا پلیٹ فارم ئا بہ",
  "home.cta.subtitle": "اگروپیو ئے نا بہترین فیصلہ کن کاشتکار ئانا گونڈ بشو — پاکستان ئانا اول، جہان ئے تہا ودہگ۔",
  "home.cta.success": "تئو لسٹ ئے تہا اتی۔ چہ تئی محل کھول بیت مان ئان گون ئے ربط گننت۔",
  "home.cta.emailLabel": "ای میل ئی پتہ",
  "home.cta.fineprint": "اسپم ننت۔ ہر وخت ئے تہا ان سبسکرائب کن۔",
  "home.footer.tagline": "اے آئی ئاناگ فارم ئی پوہگ ئی پلیٹ فارم. مشورہ، سیٹلائٹ ئی چستگیری، بازار ئی قیمت ئان اے ریکارڈ ئان — مٹک اے سگنل، گونڈ ئا۔",
  "home.footer.pagesHeading": "ورق ئان",
  "home.footer.pagesNavLabel": "فوٹر ئی ورق ئان",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی ئی اصول",
  "home.footer.terms": "خدمت ئی شرط ئان",
  "home.footer.cookies": "کوکی ئی اصول",
  "home.footer.disclaimer": "اعلامیہ",
  "home.footer.contactHeading": "ربط ئی کن",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو. سمہ حق ئان محفوظ انت۔",
  "home.footer.motto": "پاکستان ئی خاطر رچ · دنیا ئی خاطر تیار",
};
