import type { CatalogKey } from "./en.ts";

/** بلوچی — AI-drafted, founder-reviewed copy (plan D4). */
export const bal: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو چہے؟",
  "nav.features": "خصوصیتان",
  "nav.howItWorks": "چوں کار بیت",
  "nav.vision": "ماہی وژن",
  "nav.signIn": "داخل بیت",
  "nav.getEarlyAccess": "اولین رسایی بگیرت",
  "nav.openMenu": "مینیو گُش کن",
  "nav.closeMenu": "مینیو بند کن",
  "common.languageSwitcherLabel": "زبان بدیل کنیت",
  "notFound.title": "صفحه نه پیدہ بوتگنت",
  "notFound.body": "ای صفحه کہ تئی تلاش کنیت اے ما وجود انت یا منتقل بوتگانت.",
  "notFound.backHome": "گراں اگروپیو ئی سر",
  "common.builtForPakistan": "پاکستان ئے خاطر رچ کورتہ",
  "common.productOfAplinode": "اپلینوڈ ئی مہصول",
  "home.hero.eyebrow": "مصنوعی ذہانت ئان رچ کورتہ فارمی پوہگی ئی پلیٹ فارم",
  "home.hero.titleLead": "شعورین کاشتکاری ئے خاطر",
  "home.hero.titleAccent": "پوہگی",
  "home.hero.subtitle": "یک پلیٹ فارم کہ اے آئی مشورہ گر، سیٹلائٹ مانیٹرنگ، بازار ئی قیمت ئان اے تئی فارم ئی ریکارڈ ئان یک جاگاہ ئا جمع کنت — ڈیٹا ئا روشن فیصلہ ئان ئا بدلنت، تئی خودی زبان ئے تہا.",
  "home.hero.ctaSecondary": "چم ببین اے چوں کار بیت",
  "home.hero.imageAlt": "کاشتکار کھیت ئے تہا ٹیبلٹ ئا اگروپیو کارمنت کنوچی",
  "home.hero.readingCrop": "فصل ئی تندرسی",
  "home.hero.readingWeather": "ہوا ئی حال",
  "home.hero.readingSoil": "مٹی ئی نمے",
  "home.hero.noteExcellent": "بوڑ انت",
  "home.hero.noteClearSky": "پاکی اسمان",
  "home.hero.noteOptimal": "جوڑ انت",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم ئی توانائی ئان",
  "home.ticker.cropDoctor": "اے آئی فصل ئی ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "بازار ئی قیمت ئانی پوہگی",
  "home.ticker.weatherAdvisories": "ہوا ئے جوندا مشورہ ئان",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ئی ریکارڈ ئان",
  "home.ticker.advisoryLanguages": "7 زبان ئان ئے تہا مشورہ",
  "home.ticker.pestAlerts": "کیڑا ئانی خطرے ئی خبر",
  "home.ticker.offlineSms": "آف لائن + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری ئی فیصلہ ئان اندازہ ئی کھیل نہ بنت",
  "home.problem.subtitle": "سماں پاکستان ئے تہا کاشتکاران رواج، محلئی مشورہ ئان اے پچہ کورتہ معلومات ئان بوڑ خطرناک فیصلہ ئان کننت۔ نقصان فصل چنیگ ئے وتی پدا بیت۔",
  "home.problem.item1Title": "نامیقین وقت",
  "home.problem.item1Body": "آب، کودہ، دوا، توی، چنیگ — اہم وخت ئان ہمچوش اندازہ ئان پہ پہ کنگ بنت، کہ فصل ئا کم کنت اے خرچ ئا ضائع کنت۔",
  "home.problem.item2Title": "ورتہ فارم ئی ریکارڈ",
  "home.problem.item2Body": "سال ئانی پوہگی یادداشت اے پچہ کورتہ کتاب ئان ئے تہا منت۔ پروش سال ئے کہ کار ئے کنگ بوت، اے سال ئے آموختن ئے مشکل انت۔",
  "home.problem.item3Title": "پچہ کورتہ مشورہ ئان",
  "home.problem.item3Body": "ہمسائہ ئان، دکانداران اے ویڈیو ئان گشت ئان جواب ئے دنت — لیکن کماچ کاشتکار ئی فصل، مٹی، ہوا اے محل ئے جوندا انت۔",
  "home.problem.kicker": "اندازہ ئی قیمت فصل چنیگ ئے وتی پدا بیت",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تئی فارم ئی پوہگی،",
  "home.solution.titleB": "یک جاگاہ ئے تہا",
  "home.solution.subtitle": "سماں سال ئے خاطر یک پوہگی ئی پلیٹ فارم — مشورہ، ریکارڈ، ہوا اے بازار تئی زمین ئی ڈیٹا ئان کار ئا کننت، عام مشورہ ئان ئان نہ。",
  "home.solution.card1Title": "چہ کار کنگ",
  "home.solution.card1Body": "آب، کودہ، کیڑا ئی مار اے چنیگ ئے وخت ئے خاطر خودی مشورہ ئان — تئی فصل اے حالات ئے جوندا۔",
  "home.solution.card1Answer": "ای کھیت، ای ہفتہ ئے خاطر روشن مشورہ۔",
  "home.solution.card2Title": "چیرو کار کنگ",
  "home.solution.card2Body": "ہوا ئی رہنمائی بتگنت کار چیرو کنگ بیت، کہ غلط وخت اے اچاتک حالات تئی فصل ئا نہ کنت۔",
  "home.solution.card2Answer": "وخت رستین ہوا اے فصل ئی وڈتگ ئے جوندا۔",
  "home.solution.card3Title": "چہ کار بوتگنت",
  "home.solution.card3Body": "ہر کار — آب، ان پٹ، مرضی، خرچ، چنیگ — ترتیب داتہ ریکارڈ ئے تہا محفوظ کنگ بنت کہ ہر سال ئا زیات شعورین کنت۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ دستیاب۔",
};
