import type { CatalogKey } from "./en.ts";

/** بلوچی — AI-drafted, founder-reviewed copy (plan D4). */
export const bal: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو چہے؟",
  "nav.features": "خصوصیتان",
  "nav.howItWorks": "چوں کار بیت",
  "nav.vision": "ماہی وژن",
  "nav.signIn": "داخل بیت",
  "nav.getEarlyAccess": "اولین رسایی بگیرت",
  "nav.openMenu": "مینیو گُش کن",
  "nav.closeMenu": "مینیو بند کن",
  "common.languageSwitcherLabel": "زبان بدیل کنیت",
  "notFound.title": "صفحه نه پیدہ بوتگنت",
  "notFound.body": "ای صفحه کہ تئی تلاش کنیت اے ما وجود انت یا منتقل بوتگانت.",
  "notFound.backHome": "گراں اگروپیو ئی سر",
  "common.builtForPakistan": "پاکستان ئے خاطر رچ کورتہ",
  "common.productOfAplinode": "اپلینوڈ ئی مہصول",
  "home.hero.eyebrow": "مصنوعی ذہانت ئان رچ کورتہ فارمی پوہگی ئی پلیٹ فارم",
  "home.hero.titleLead": "شعورین کاشتکاری ئے خاطر",
  "home.hero.titleAccent": "پوہگی",
  "home.hero.subtitle": "یک پلیٹ فارم کہ اے آئی مشورہ گر، سیٹلائٹ مانیٹرنگ، بازار ئی قیمت ئان اے تئی فارم ئی ریکارڈ ئان یک جاگاہ ئا جمع کنت — ڈیٹا ئا روشن فیصلہ ئان ئا بدلنت، تئی خودی زبان ئے تہا.",
  "home.hero.ctaSecondary": "چم ببین اے چوں کار بیت",
  "home.hero.imageAlt": "کاشتکار کھیت ئے تہا ٹیبلٹ ئا اگروپیو کارمنت کنوچی",
  "home.hero.readingCrop": "فصل ئی تندرسی",
  "home.hero.readingWeather": "ہوا ئی حال",
  "home.hero.readingSoil": "مٹی ئی نمے",
  "home.hero.noteExcellent": "بوڑ انت",
  "home.hero.noteClearSky": "پاکی اسمان",
  "home.hero.noteOptimal": "جوڑ انت",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم ئی توانائی ئان",
  "home.ticker.cropDoctor": "اے آئی فصل ئی ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "بازار ئی قیمت ئانی پوہگی",
  "home.ticker.weatherAdvisories": "ہوا ئے جوندا مشورہ ئان",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ئی ریکارڈ ئان",
  "home.ticker.advisoryLanguages": "7 زبان ئان ئے تہا مشورہ",
  "home.ticker.pestAlerts": "کیڑا ئانی خطرے ئی خبر",
  "home.ticker.offlineSms": "آف لائن + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری ئی فیصلہ ئان اندازہ ئی کھیل نہ بنت",
  "home.problem.subtitle": "سماں پاکستان ئے تہا کاشتکاران رواج، محلئی مشورہ ئان اے پچہ کورتہ معلومات ئان بوڑ خطرناک فیصلہ ئان کننت۔ نقصان فصل چنیگ ئے وتی پدا بیت۔",
  "home.problem.item1Title": "نامیقین وقت",
  "home.problem.item1Body": "آب، کودہ، دوا، توی، چنیگ — اہم وخت ئان ہمچوش اندازہ ئان پہ پہ کنگ بنت، کہ فصل ئا کم کنت اے خرچ ئا ضائع کنت۔",
  "home.problem.item2Title": "ورتہ فارم ئی ریکارڈ",
  "home.problem.item2Body": "سال ئانی پوہگی یادداشت اے پچہ کورتہ کتاب ئان ئے تہا منت۔ پروش سال ئے کہ کار ئے کنگ بوت، اے سال ئے آموختن ئے مشکل انت۔",
  "home.problem.item3Title": "پچہ کورتہ مشورہ ئان",
  "home.problem.item3Body": "ہمسائہ ئان، دکانداران اے ویڈیو ئان گشت ئان جواب ئے دنت — لیکن کماچ کاشتکار ئی فصل، مٹی، ہوا اے محل ئے جوندا انت۔",
  "home.problem.kicker": "اندازہ ئی قیمت فصل چنیگ ئے وتی پدا بیت",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تئی فارم ئی پوہگی،",
  "home.solution.titleB": "یک جاگاہ ئے تہا",
  "home.solution.subtitle": "سماں سال ئے خاطر یک پوہگی ئی پلیٹ فارم — مشورہ، ریکارڈ، ہوا اے بازار تئی زمین ئی ڈیٹا ئان کار ئا کننت، عام مشورہ ئان ئان نہ。",
  "home.solution.card1Title": "چہ کار کنگ",
  "home.solution.card1Body": "آب، کودہ، کیڑا ئی مار اے چنیگ ئے وخت ئے خاطر خودی مشورہ ئان — تئی فصل اے حالات ئے جوندا۔",
  "home.solution.card1Answer": "ای کھیت، ای ہفتہ ئے خاطر روشن مشورہ۔",
  "home.solution.card2Title": "چیرو کار کنگ",
  "home.solution.card2Body": "ہوا ئی رہنمائی بتگنت کار چیرو کنگ بیت، کہ غلط وخت اے اچاتک حالات تئی فصل ئا نہ کنت۔",
  "home.solution.card2Answer": "وخت رستین ہوا اے فصل ئی وڈتگ ئے جوندا۔",
  "home.solution.card3Title": "چہ کار بوتگنت",
  "home.solution.card3Body": "ہر کار — آب، ان پٹ، مرضی، خرچ، چنیگ — ترتیب داتہ ریکارڈ ئے تہا محفوظ کنگ بنت کہ ہر سال ئا زیات شعورین کنت۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ دستیاب۔",
  "home.features.eyebrow": "پلیٹ فارم ئی دنہ",
  "home.features.titleA": "بوڑتہ انجن ئان،",
  "home.features.titleB": "یک پوہگین پلیٹ فارم",
  "home.features.subtitle": "تئی خودی لفظ ئان ئے تہا اولین سوال ئان سمما سال ئی ریکارڈ ئان ئا — ہر توانائی بلئی ئا قوت دنت۔",
  "home.features.advisorModule": "ماڈیول 01 · مشورہ گر",
  "home.features.advisorTitle": "اے آئی کاشتکاری ئی مشورہ گر",
  "home.features.advisorTopics": "آب · کودہ · کیڑا اے مرضی · چنیگ",
  "home.features.advisorBadge": "رومن بلوچی",
  "home.features.advisorMockAria": "زیڑین پتر ئانی گندم ئے بابت اگروپیو مشورہ گر ئے نا نمونہ گفتگو",
  "home.features.advisorUserMsg": "منی گندم ئی پتر زیڑ بیتانت — چہ کنم؟",
  "home.features.advisorReplyTitle": "زیڑین پتر — دو عام دلیل ئان:",
  "home.features.advisorReplyCause1": "آب ئی کمی",
  "home.features.advisorReplyCause1Rest": "— سردین وخت ئان ئے تہا، سوچارے 9 بجے ئے پہ آب دنت۔",
  "home.features.advisorReplyCause2": "نائٹروجن ئی کمی",
  "home.features.advisorReplyCause2Rest": "— بوڑتہ پتر ئان اول ئا چک انت؛ لوٹ انت تہ یوریا دنت۔",
  "home.features.advisorReplyFooter": "اگر پتر ئانی تہئا زیڑین لیر ئان نظر انت، عکس روانہ کنت — man مرض ئی تشخیص کنم۔",
  "home.features.advisorInputPlaceholder": "تئی سوال لکھ یا بگو…",
  "home.features.advisorFooter": "تئی فصل ئے بابت چی بیت گشت — روچمرہ سوال ئان خوش آمدید۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ئی ریکارڈ",
  "home.features.recordsDesc": "ہر کار ترتیب ئا درج — کہ مشورہ تئی خودی زمین ئان آموکت۔",
  "home.features.record1Activity": "آب",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتر ئی سکین",
  "home.features.record3Detail": "چی مرض نہ بوت",
  "home.features.recordsCropTag": "گندم · ربیع سال",
  "home.features.languageModule": "ماڈیول 03 · زبان",
  "home.features.languageTitle": "تئی زبان، تئی لفظ",
  "home.features.languageDesc": "چی سوچیت اے چت گوش یا لکھ — تکنیکی انگریز ئے لوٹ ننت۔",
  "home.features.weatherModule": "ماڈیول 04 · ہوا",
  "home.features.weatherTitle": "ہوا ئاناگ رہنمائی",
  "home.features.weatherDesc": "مشورہ تئی سرا پہنگ بوتگئی پہ رستین حالات ئان چک بیت — جنگ ئے پہروا سپرے کرت تہ سارا کودہ وہہ ویلیت۔",
  "home.features.weatherMockAria": "پنج روچ ئی پیش بینی کہ پنجشمبر ئا سپرے ئی بند ئا نمایاں بیت",
  "home.features.dayMon": "دوشنبہ",
  "home.features.dayTue": "سہ‌شنبہ",
  "home.features.dayWed": "چارشنبہ",
  "home.features.dayThu": "پنجشنبہ",
  "home.features.dayFri": "آدینه",
  "home.features.holdSpray": "سپرے بند کن",
  "home.features.weatherLegend": "محلئی ہوا ئی پیش بینی ئان مشورہ ئی روچ نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودہگ بیت — سمہ توانائی ئان ببین",
  "home.journey.eyebrow": "اے چوں کار بیت",
  "home.journey.title": "یک سوال سال ئا پہ کورت",
  "home.journey.subtitle": "تئی اولین سوال ئان مکمل، پوہگین فارم ئی تاریخ ئا سادہ راہ۔",
  "home.journey.step1Title": "تئی فارم شامل کن",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل ئے خاطر محل، فصل اے بنیادی تفصیل ئان لکھ۔",
  "home.journey.step2Title": "اے آئی ئان بپرس",
  "home.journey.step2Body": "تئی سوال اے زبان ئے تہا لکھ یا بگو کہ تئی خودی تہا بوڑ آرام ئا اتی۔",
  "home.journey.step3Title": "رہنمائی بگیر",
  "home.journey.step3Body": "تئی فصل، ہوا، محل اے فارم ئی تاریخ ئے جوندا مشورہ بگیر۔",
  "home.journey.step4Title": "کار درج کن",
  "home.journey.step4Body": "تھورین ٹیپ ئان ئے تہا آب، کودہ، دوا یا مرض درج کن۔",
  "home.journey.step5Title": "تاریخ ئا رچ کن",
  "home.journey.step5Body": "ہر ریکارڈ آتکہ مشورہ ئان ئا زیات پوہگین اے جوڑا کنت۔",
  "home.journey.step6Title": "چستگیری جاری دار",
  "home.journey.step6Body": "سمما سال ئے اندا ریکارڈ ئان ببین اے رفت ئا چم دارات۔",
  "home.matrix.eyebrow": "سمہ توانائی ئان",
  "home.matrix.title": "لوڑٹین ئان حیران کن ئان ئا",
  "home.matrix.subtitle": "ہر خاصیت فصل ئا پہ دار بیت، خرچ ئا کم کنت یا آمدنی ئا ودہگ بیت۔ اے ئا تقویم ئے ونش — ہر درجہ پرچین ئے سر رچ کورتہ۔",
  "home.matrix.capabilitiesLabel": "توانائی ئان",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی سطح",
  "home.matrix.t1f1Title": "اے آئی فصل ئی مرض ئی پہچانک",
  "home.matrix.t1f1Body": "متاثرہ پتر ئی عکس اپلوڈ کن اے فوری تشخیص، شدت اے دوا ئی مشورہ بگیر۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت ئی چستگیری",
  "home.matrix.t1f2Body": "تئی کھیت ئی حد ئا نشان کن اے واجہ سینٹینل-2 عکس ئان ئان این ڈی وی آئی ئاناگ فصل ئی تندرسی ببین۔",
  "home.matrix.t1f3Title": "پوہگین ہوا ئی مشورہ",
  "home.matrix.t1f3Body": "محلئی ہوا ئی پیش بینی تئی فصل اے وڈتگ ئے مرحلہ ئے جوندا ملے روزانہ کار ئی مشورہ بیت۔",
  "home.matrix.t1f4Title": "بازار ئی قیمت ٹریکر اے پیش بینی",
  "home.matrix.t1f4Body": "نیڑاگ بازار ئی قیمت ئان اے آئی میلان ئان ئے جوندا ببین، کہ رستین وخت ئے تہا فروش کنیت۔",
  "home.matrix.tier2Name": "امتیازی خاصیت ئان",
  "home.matrix.tier2Badge": "نمایاں",
  "home.matrix.t2f1Title": "محلئی زبان ئانی آواز ئی چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی ئے وانگوں بگو یا لکھ — جواب اے زبان ئے تہا بشنو کہ تئی خودی بہتر سمگیت۔",
  "home.matrix.t2f2Title": "سرحکومتی اسکیم ئی جوڑاک",
  "home.matrix.t2f2Body": "تئی تفصیل ئان لکھ اے ہر اہل اسکیم ئا پہ کن — دستاویز ئان اے درخواست ئی لنک ئان ئے جوندا۔",
  "home.matrix.t2f3Title": "فصل ئی سفارش ئی انجن",
  "home.matrix.t2f3Body": "ای سال ئے تہا تئی مٹی، ہوا، بازار ئی لوٹ اے بجٹ ئے جوندا بوڑ منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم ئی نفع/نقصان ئی حسابگر",
  "home.matrix.t2f4Body": "اٹکلین اے رستین خرچ ئان، حاصل، آمدنی اے نفع — بریک ایون اے آر او آئی ئے جوندا۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم اے ماہر ئی رابطہ",
  "home.matrix.t2f5Body": "سوال ئان شی کن، عکس ئان شریک کن، ہمدرہ کاشتکار ئان اے تصدیق کورتہ ماہر ئان ئان جواب بگیر۔",
  "home.matrix.tier3Name": "حیران کن ئان",
  "home.matrix.tier3Badge": "سمہ ئان ئے پہروا",
  "home.matrix.t3f1Title": "سیٹلائٹ ئی تبدیلی ئی پہچانک",
  "home.matrix.t3f1Body": "سلائیڈر ئے جوندا وخت ئے نا سیٹلائٹ عکس ئان موازنہ کن — وڈتگ، نقصان یا قبضہ ٹریک کن۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا ئی خطرے ئی پیش بینی",
  "home.matrix.t3f2Body": "ہوا، فصل ئی مرحلہ اے تاریخ ئی بنیاد ئا احتمالی حملہ ئے پہروا اولین خبرداری۔",
  "home.matrix.t3f3Title": "آواز ئی فون کال موڈ",
  "home.matrix.t3f3Body": "واجہ نمبر ئا کال کن، سوال بگو، تئی زبان ئے تہا مشورہ بشنو — سمارٹ فون ئے لوٹ ننت۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ ئی اندازہ",
  "home.matrix.t3f4Body": "پائیدار طریقہ ئان درج کن اے رضاکارانہ بازار ئان ئان کاربن کریڈٹ ئی اندازہ بگیر۔",
  "home.matrix.t3f5Title": "آف لائن پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت ئے تہا آف لائن کار بیت، کنکشن ئے نا سنک بیت، کمزور نیٹ ئے تہا ایس ایم ایس خبر دنت۔",
  "home.vision.eyebrow": "دیدگاہ",
  "home.vision.titleA": "پاکستان ئی خاطر رچ کورتگ.",
  "home.vision.titleB": "دنیا ئی خاطر تیار.",
  "home.vision.pkTitle": "اول پاکستان ئی روش",
  "home.vision.pkBody": "اولین نسخہ پاکستان ئی کھیت ئان ئی خاطر ڈیزائن بوتگیت: محلئی فصل ئان، محلئی زبان ئان، رستین کاشت ئی روش ئان اے رستین کھیت ئی حالات۔",
  "home.vision.pkPoint1": "محلئی فصل اے اقلیم ئی پوہگ",
  "home.vision.pkPoint2": "اردو، پنجابی، پښتو، سندی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "رستین کاشتکار ئانی رائے ئانا بہتر بوتگیت",
  "home.vision.worldTitle": "جہانی وسعت ئی دیدگاہ",
  "home.vision.worldBody": "جوڑ ئے خاطر رچ بوتگ۔ چہ پلیٹ فارم پختہ بیت نئین ملکت ئا، زبان ئانا، فصل ئانا اے اقلیم ئانا ئا کش بیت — نوکین سر ئانا رچ کورت ئے تہا۔",
  "home.vision.worldPoint1": "ہر ملک ئی زرعی پوہگ",
  "home.vision.worldPoint2": "وداگ زبان ئان اے محلئی فصل ئان",
  "home.vision.worldPoint3": "ڈونگین ڈیٹا ئی جوڑ ئان اے تجزیہ ئان",
  "home.users.title1": "انفرادی کاشتکار ئان",
  "home.users.desc1": "چھوٹ اے منزلگین فارم ئان کہ رستین مشورہ اے ہر کار ئی ترتیب ئانا ریکارڈ لوٹ انت۔",
  "home.users.title2": "تجارتی فارم ئان",
  "home.users.desc2": "زرعی سودا ئان کہ ترتیب ئانا معلومات، فیصلہ ئی مدد اے ٹیم ئی ریکارڈ ئان لوٹ انت۔",
  "home.users.title3": "ایکو سسٹم ئی شرکا",
  "home.users.desc3": "ان پٹ ئی دینکان، کوآپریٹو، بیمہ اے وسیع ئی خدمت ئان کہ وخت ئے نا پلیٹ فارم ئے نا گونڈ بنت۔",
  "home.users.tagline": "اول کاشتکار ئان ئی خاطر ڈیزائن بوتگ — ایکو سسٹم ئے نا وڈاگ",
  "home.cta.eyebrow": "اولین رسے",
  "home.cta.title": "تئی فارم ئا پلیٹ فارم ئا بہ",
  "home.cta.subtitle": "اگروپیو ئے نا بہترین فیصلہ کن کاشتکار ئانا گونڈ بشو — پاکستان ئانا اول، جہان ئے تہا ودہگ۔",
  "home.cta.success": "تئو لسٹ ئے تہا اتی۔ چہ تئی محل کھول بیت مان ئان گون ئے ربط گننت۔",
  "home.cta.emailLabel": "ای میل ئی پتہ",
  "home.cta.fineprint": "اسپم ننت۔ ہر وخت ئے تہا ان سبسکرائب کن۔",
  "home.footer.tagline": "اے آئی ئاناگ فارم ئی پوہگ ئی پلیٹ فارم. مشورہ، سیٹلائٹ ئی چستگیری، بازار ئی قیمت ئان اے ریکارڈ ئان — مٹک اے سگنل، گونڈ ئا۔",
  "home.footer.pagesHeading": "ورق ئان",
  "home.footer.pagesNavLabel": "فوٹر ئی ورق ئان",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی ئی اصول",
  "home.footer.terms": "خدمت ئی شرط ئان",
  "home.footer.cookies": "کوکی ئی اصول",
  "home.footer.disclaimer": "اعلامیہ",
  "home.footer.contactHeading": "ربط ئی کن",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو. سمہ حق ئان محفوظ انت۔",
  "home.footer.motto": "پاکستان ئی خاطر رچ · دنیا ئی خاطر تیار",
  "hiw.meta.title": "ای چونت کار کنت — اگروپیو",
  "hiw.meta.description":
    "ئک منٹ ئی فارم پروفائل ئانا اولین مسلسل بہتر بیتک فصل ئی چکر ئے تہا: ببین اگروپیو سوال ئانا، کار ئانا تے ریکارڈ ئانا چونت ذاتی کاشت ئی لہر ئے تہا بدل کنت.",
  "hiw.hero.eyebrow": "ای چونت کار کنت",
  "hiw.hero.titleA": "شش گوں مرحل ئان۔",
  "hiw.hero.titleLead": "ئک",
  "hiw.hero.titleAccent": "وداگ پوهگین سیزن۔",
  "hiw.hero.subtitle":
    "اگروپیو ہمے جیڑا کار کنت جیڑا کاشت پہلے ئانا چھوتگ — تئو بوئے، پوسی، کار کنے تے ریکارڈ کنے۔ فرق رچ ئے تہا اے کہ نوک ئے تہا هر مرحل اگوانگ ئے سک کنت.",
  "hiw.hero.browseFeatures": "خصوصیت ئان ببین",
  "hiw.route.navLabel": "اگروپیو ئی فصل ئی چکر ئی شش گوں مرحل ئان",
  "hiw.route.stepLabel": "مرحل {n}: {stop}",
  "hiw.route.stop1": "فارم ئا رچ",
  "hiw.route.stop2": "پوس",
  "hiw.route.stop3": "مشورہ",
  "hiw.route.stop4": "کار کن",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "ئک واری سیٹ اپ کن",
  "hiw.setup.title": "تئی فارم زندگین پروفائل بیت",
  "hiw.setup.body":
    "چار خانگ ئان، ئک منٹ ئانا کم — ضلع، فصل، بوئی ئی تاریخ تے زمین ئی وسعت۔ ہمے سار فارم ئے۔ ہمدہ پہ ئے نا هر جواب پوهانت کہ کوئے تے چہ کن حالات ئانا اگیت.",
  "hiw.setup.point1": "فصل ئا بدل یا ہر وخت فارم ئانا زیات کن",
  "hiw.setup.point2": "ٹھیکیدار ئان تے ڈیلر ئان ئی خاطر چہ فارم ئان",
  "hiw.setup.point3": "ہچ ٹیکنیکل ئی گل پوست بیت — مٹک ئی رپورٹ ئی لوڑ نیست",
  "hiw.setup.mockHeading": "نوکین فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل ئا رچ",
  "hiw.setup.mockFootnote": "ئک منٹ ئانا کم وخت گنت",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم کہ ئے تہا ضلع، فصل، بوئی ئی تاریخ تے زمین ئی وسعت پُر انت",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گانم · ربیع",
  "hiw.setup.rowSowing": "بوئی ئی تاریخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "۱۲ ایکڑ",
  "hiw.ask.eyebrow": "چہ دل ئا گشت پوس",
  "hiw.ask.titleA": "ئک سوال ئا گنت۔",
  "hiw.ask.titleB": "تئی سار فارم ئا جواب دیت۔",
  "hiw.ask.body":
    "ئک ئی سوال وڈا فارم ئانا وڈا معنا داریت۔ پس جواب ئی پہ اگروپیو سوال ئا تئی فارم ئی بارہ پوهگین ہر گل ئے نا ملائنت.",
  "hiw.ask.pipelineLabel":
    "کاشتکار ئی سوال ئا فصل، ضلع، موسم تے تاریخ ئی حال ئے نا جور بیت تاں ذاتی جواب رچ بیت",
  "hiw.ask.question": "نوک ئا آب داتگ سم یا تھوڑا انتظار؟",
  "hiw.ask.checkedAgainst": "ہمے شے ئان ئے نا ملائنت",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گانم · خوشک ئان درآتگنت",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "۲۶° • خشکین ہفتہ",
  "hiw.ask.chipHistory": "تاریخ",
  "hiw.ask.chipValHistory": "یوریا ۹ روچ دمگاہ",
  "hiw.ask.answer":
    "دو روچ ئا دم ئا گن — بارش ئی احتمال انت، تے یوریا ئے پہ زمین تر انت. جمعہ ئے تہا نزامگ کافی ئے.",
  "hiw.ask.answerMeta": "ذاتی جواب • گانم، یوریا ئے پہ ۹ روچ ئا پدا",
  "hiw.ask.footnote": "لیک، وات یا کال کن — جواب ہر صورت ئے تہا تئی فارم ئی خودی ئے",
  "hiw.engine.eyebrow": "جواب ئی پشت ئا",
  "hiw.engine.title": "چار جانچ ئان ہمدہ پہ کہ تئو ئک لائن ئا بینت",
  "hiw.engine.body":
    "مشورہ سرچ ئی نتیجہ ئے نیست۔ ای چار دریچگ ئانا گذر کنت تاں چہ تئے تہا رسگ ئے ہمے کھیت ئی خاطر، ہمے ہفتہ ئی خاطر محفوظ ہو.",
  "hiw.engine.check1Title": "پوهگ ئا جمع کنگ",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم تے فصل ئی مرحل لیجک ئی لمحہ ئے نا جور بیت.",
  "hiw.engine.check2Title": "ملائ ئی جانچ",
  "hiw.engine.check2Desc":
    "مشورہ موسم ئی پیش ئے نا آزمایش بیت — بارش ئے تہا بیکار بیتگ سپرے انجن ئانا ندراجیت.",
  "hiw.engine.check3Title": "ذاتی کنگ",
  "hiw.engine.check3Desc":
    "تئی کھیت ئی تاریخ جواب ئا بدل کنت — ہمیشہ فصل، وڈا مٹک، وڈا مشورہ.",
  "hiw.engine.check4Title": "رساندگ",
  "hiw.engine.check4Desc":
    "پہ تئی زبان ئے نا صاف قدم ئان ئی جیز آت — اسکرین ئا، واز ئے تہا یا فون ئی ربط ئا.",
  "hiw.engine.safetyStrong": "اگر ہچ غیر محفوظ ئے درۆچنت،",
  "hiw.engine.safetyRest":
    "پس اگروپیو انتظار ئی گشت — دیر ئے تہا رسگین جواب ضائع بوتگ سپرے یا بربادوتگ فصل ئے بہتر ئے.",
  "hiw.record.recorderHeading": "کار ئا درج کن",
  "hiw.record.syncBadge": "خودکار سنک روش",
  "hiw.record.actionIrrigation": "آب داتگ",
  "hiw.record.actionFertiliser": "کاد",
  "hiw.record.actionPesticide": "کیڑہ مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرج",
  "hiw.record.actionHarvest": "فصل ئا گنڈگ",
  "hiw.record.row1Time": "امروز • بونگ ئا 6:40",
  "hiw.record.row1Label": "آب داتگ درج بوت",
  "hiw.record.row1Detail": "نہر ئی موڑ • ۴۰ منٹ • پلاٹ B",
  "hiw.record.row2Time": "دیرو",
  "hiw.record.row2Label": "کاد درج بوتگ",
  "hiw.record.row2Detail": "DAP ۲۰ کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج رچ دو ٹیپ — آف لائن ئا ئے کار کنت",
  "hiw.record.mockLabel":
    "کار ئی ریکارڈر کہ ئے تہا فوری ایکشن چپ ئان تے نوکین درج بوتگ اندراج ئان انت",
  "hiw.record.eyebrow": "چیچی کار کنے، ریکارڈ کنگ ئا روان ئے",
  "hiw.record.titleA": "نوک ئے تہا دو ٹیپ،",
  "hiw.record.titleB": "سار سیزن بہتر جواب ئان",
  "hiw.record.body":
    "ریکارڈنگ کھیت ئی خاطر رچ بوتگ — گوڑ بٹن ئان، کم خانگ ئان، ٹائپنگ ئی لوڑ نیست. هر اندراج فارم ئی یادگار ئا شریک بیت، پس مشورہ ئے فصل ئے نا تک ئا گنت.",
  "hiw.record.point1": "آب، کاد ئان، بیماری ئان، خرج ئان، فصل — سار ئک ٹائم لائن ئا",
  "hiw.record.point2": "پور آف لائن ئا کار کنت؛ سگنل ئی آتگ ئے نا خودکار سنک بیت",
  "hiw.record.point3": "بینک ئان، خریدار ئان یا بیمہ ئی خاطر سیزن ئی خلاصہ تیار",
  "hiw.loop.eyebrow": "فصل ئی چکر",
  "hiw.loop.titleA": "ای فصل ئا گنڈگ ئا تمام بیت۔",
  "hiw.loop.titleB": "ہمدہ ئانا آغاز بیت۔",
  "hiw.loop.body":
    "پوس، کار کن، ریکارڈ کن — ول ول۔ چکر ئی هر چر اگروپیو تئی مٹک ئی بارہ نوکین گل سکھانت، پس اگواں فصل پچھمگا ئانا آگہ ئے نا آغاز بیت.",
  "hiw.loop.benefit1Title": "مشورہ سرمایہ جمع کنت",
  "hiw.loop.benefit1Desc":
    "پچھمگ فصل ئی بیماری ئان، انداز ئان تے تاریخ ئان ہم فصل ئی اولین جواب ئا رچ کنت.",
  "hiw.loop.benefit2Title": "ہچ ولانا بیت",
  "hiw.loop.benefit2Desc":
    "مشاورت پوهانت کہ چی دمگا سپرے یا کاد بوتیگ — دووار انداز ئی خطرہ نیست.",
  "hiw.loop.benefit3Title": "ہر فصل دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرض ئان، خریدار ئان، بیمہ یا اگوائی فصل ئی فیصلہ ئی خاطر تیار ماندگ.",
    "hiw.loop.stepLearn": "سکھ",
  "hiw.loop.stepImprove": "بہتر کن",
"hiw.loop.diagramLabel": "گول چکر خاکہ: پوس، کار کن، ریکارڈ کن، سکھ، بہتر کن",
  "hiw.loop.centerSeason": "فصل",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر فصل، پچھمگا ئانا بہتر",
  "feat.meta.title": "خصوصیات — اگروپیو",
  "feat.meta.description": "اگروپیو ءِ هر خصوصیت ببین: اے آی زرین ڈاکٹر، سیٹلائٹ NDVI چارواشی، منڈ ءِ قیمت ءِ پیش بینی، محلی زبانان ءِ آوازی مشورہ، آن لائن پدے رسئی و SMS خبرداری، و بازین گون.",
  "feat.hero.eyebrow": "خصوصیات",
  "feat.hero.titleLead": "شما ءِ موسم ءِ هر",
  "feat.hero.titleAccent": "لوڑت کامل",
  "feat.hero.subtitle": "چاردہ خصوصیات یکجا کار کننت — برگان سکین کننت، فضا ءَ کہت ءَ ناظر انت، منڈ ءَ واننت و شما ءِ زبانا حبر دنت۔ ببین هر یک شما ءِ فارم ئے گون چی کار کنت۔",
  "feat.hero.ctaPrimary": "اولین دسترسی بگیر ات",
  "feat.hero.ctaSecondary": "چو کار کنت ببین ات",
  "feat.hero.builtFor": "پاکستان ئے راد بنز بوته",
  "feat.hero.productOf": "Aplinode ءِ پیداوار",
  "feat.hero.tile1Label": "برگ سکین",
  "feat.hero.tile1Value": "94% تند",
  "feat.hero.tile2Label": "منڈ ءِ گندم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کہت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کرمک ءِ خطر",
  "feat.hero.tile4Value": "کم · 7 روچ",
  "feat.hero.voiceReady": "آوازی مشورہ تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "SMS خبرداری · آن لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — اسپری بند کن ات",
  "feat.intel.eyebrow": "زرع ءِ دانش",
  "feat.intel.heading": "مسائل زیان ءَ پیسر ببین ات",
  "feat.intel.sub": "بیماری، کرمک، ہوا و زرع ءِ انتخاب — چار فیصلہ کہ زرع ٹھہر کننت، هر یک خود ءِ انجن گون۔",
  "feat.intel.included": "شمول انت",
  "feat.intel.doctorCode": "F·01 · دید",
  "feat.intel.doctorTitle": "اے آی زرع ءِ ڈاکٹر",
  "feat.intel.doctorDesc": "متاثر برگ ءِ تصویر بگر ات و چند ثانیہ ءَ بیماری ءِ نام، شدت و درمان ءِ منصوبہ گیر ات۔",
  "feat.intel.doctorMock": "برگ سکین ءِ نتیجہ کہ زرد زنگ بلند یقین گون تشخیص کورت",
  "feat.intel.diseaseName": "زرد زنگ",
  "feat.intel.matchScore": "94% مماثلت",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "میانہ",
  "feat.intel.pestCode": "F·02 · پیش بینی",
  "feat.intel.pestTitle": "کرمکان ءِ حملہ ءِ خبرداری",
  "feat.intel.pestDesc": "ہوا و زرع ءِ مرحلہ خطر ماڈل ئے تغذیہ کنت کہ حملہ ءَ یک روچ پیسر خبردار کنت۔",
  "feat.intel.pestMock": "ہفت روچ ءِ کرمک خطر چارٹ کہ ششمی روچ بالا ئے روت",
  "feat.intel.pestAlert": "شنبہ · ٹڈی دل ءِ خطر 74% — نوک گندم مہفوظ کن ات",
  "feat.intel.weatherCode": "F·03 · ہوا",
  "feat.intel.weatherTitle": "ہوا ءِ مطابق مشورہ",
  "feat.intel.weatherDesc": "محلی پیش بینیان شما ءِ زرع و ودھ ءِ مرحلہ گون جوڑ انت — مشورہ روشن رہنمائی ئے آت، خام ڈیٹا نہ۔",
  "feat.intel.weatherMock": "نمونہ ہوا مشورہ کہ بارش ءَ پیسر آبپاشی ءَ تاخیر ءِ حکم دنت",
  "feat.intel.delayIrrigation": "امروز آب ءِ دییم ءَ تاخیر کن ات",
  "feat.intel.rainNote": "شام 3 ئے بارش ءِ امکان — اول اسمان کہت ءَ آبپاش کنت۔",
  "feat.intel.waterSaved": "آب ءِ سپما",
  "feat.intel.cropCode": "F·04 · منصوبہ",
  "feat.intel.cropTitle": "زرع ءِ سفارش",
  "feat.intel.cropDesc": "مٹی، ہوا، طلب و شما ءِ بودجہ یکجا جانچن بنت — آہے بکار ات کہ اے موسما منفعہ دنت۔",
  "feat.intel.cropMock": "درجہ بندی شر زرع سفارشان کہ گندم سر ءَ",
  "feat.intel.crop1": "گندم",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "نخود",
  "feat.field.eyebrow": "کہت و منڈ ءِ دانش",
  "feat.field.headingA": "شما ءِ زمین فضا ءَ ناپ بیت۔",
  "feat.field.headingB": "شما ءِ زرع ڈیٹا گون پرکھ بیت۔",
  "feat.field.sub": "هر ایکڑ ئے سیٹلائٹ ءِ نظارہ و قریبی ہر منڈ ءِ جائزہ — تاکہ ودھ و فروش دوئی صحیح وقت ءَ بنت۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کہت چارواشی",
  "feat.field.ndviDesc": "خپ ءِ حد یک واری نشان کن ات؛ ہر روشن سیٹلائٹ گذر ءَ صحت ءِ زون اپ ڈیٹ بنت — کمزور حصہ چم ءَ پیسر ظاہر بنت۔",
  "feat.field.ndviMock": "کہت ءِ صحت گرڈ کہ تیر شین قوی زرع ءِ ودھ دیکت",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈ",
  "feat.field.priceTitle": "منڈ ءِ قیمت ءِ پیش بینی",
  "feat.field.priceDesc": "قریبی منڈان ءِ موجودہ ریٹ و رجحان ءِ پیش بینی — آہے وفروش ات کہ گراف اہے، خریدار کہ اہے نہ۔",
  "feat.field.priceMock": "گندم ءِ قیمت رجحان ہشت ہفتہ ءَ بلندی ئے، روک ءَ ماندن ءِ سفارش گون",
  "feat.field.wheatTrend": "گندم · 8 ہفتہ",
  "feat.field.holdStock": "↑ 12% — مال ماند ات",
  "feat.field.financeCode": "F·07 · مالیات",
  "feat.field.financeTitle": "منفعہ نقصان ءِ تعقیب",
  "feat.field.financeDesc": "هر روپی ءِ آمدنی رفت، پورا موسم — منڈ یا بانک ءَ شون ءَ پیسر بریک ایون و ROI تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ کہ ان پٹ، مزوری، آبپاشی و آمدنی لریت",
  "feat.field.rowInputs": "ان پٹ",
  "feat.field.rowLabour": "مزوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (تخمینی)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "ہرکس ئے رسئی",
  "feat.voice.headingA": "اسمارٹ فون نہ انت؟",
  "feat.voice.headingB": "انگریزی نہ؟ باز ہم شمول۔",
  "feat.voice.sub": "بہترین مشورہ بی فائدہ انت اگر کسان ئے رسے نہ۔ ہر خصوصیت تلیفونی کال ئے جواب دنت، آواز شنوت و سیگنل ءِ پدے علاقہ ءَ ہم کار کنت۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "خپ ءِ سوال بہ گو ات",
  "feat.voice.speakMock": "رومن بلوچی ءَ مشورہ گون آوازی گفتگو",
  "feat.voice.chatUser": "من ءِ زرع ءِ برگان ءَ داغ انت",
  "feat.voice.chatAdvisor": "داغان ءِ تصویر رہ دیم دے ات — مان اکنوں تشخیص کنان۔",
  "feat.voice.inputPlaceholder": "گون آواز پرسی…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کن ات",
  "feat.voice.callMock": "اگروپیو آوازی مددگار گون ٹول فری کال ءِ نقل",
  "feat.voice.greetingLine": "اگروپیو ءَ شما ءِ مہربانی",
  "feat.voice.heardLine": "آواز شنوگ بوت — جواب تیار",
  "feat.voice.callEnded": "کال تمام · خلاصہ محفوظ",
  "feat.voice.anyPhone": "هر تلیفون ءَ · انٹرنیٹ ءِ لوڑت نہ",
  "feat.voice.offlineCode": "F·10 · آن لائن + SMS",
  "feat.voice.offlineTitle": "سیگنل ءِ پدے علاقہ ہم نہ روکنت",
  "feat.voice.offlineDesc": "مشورہ، ریکارڈ و کیلکولیٹر بے سیگنل کار کننت؛ نیٹ ورک ءِ گشت ءَ سنب سنک بنت و اہم خبرداری SMS ءَ آنت۔",
  "feat.voice.networkStatus": "نیٹ ءِ حالت",
  "feat.voice.offlineQueued": "آن لائن · 3 ریکارڈ صف ءَ",
  "feat.voice.smsStamp": "SMS · 07:42",
  "feat.voice.smsMsg": "موسم ءِ خبرداری: بارش شام 3 ئے — اسپری ءِ وقت بدل ات۔",
  "feat.manage.eyebrow": "چارواشی و ودھ",
  "feat.manage.headingA": "مشورہ شروع انت۔",
  "feat.manage.headingB": "باقین سنب ریکارڈ ءَ روت۔",
  "feat.manage.sub": "تاریخچہ، سبسڈی، پاییداری و کسمان ءِ کمیونٹی — خاموش خصوصیات کہ ہر موسم جمع بنت۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈ",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی ءَ زرع ءِ کپ ئے، سنب یک ٹائم لائن ءَ کہ مشورہ جواب ءَ پیسر واننت۔",
  "feat.manage.timelineMock": "اگست ءِ فارم ءِ سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "نہر ءِ باری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریہ دیگ بوتیت",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "برگ سکین",
  "feat.manage.tl3Detail": "تند · کس بیماری نہ",
  "feat.manage.schemeCode": "F·12 · اسکیم",
  "feat.manage.schemeTitle": "سبسڈی و اسکیم ءِ جستجو",
  "feat.manage.schemeDesc": "حکومتی پیسہ کہ شما اول ءَ اہل ات — پدا کنگ، سمجھ دنگ و یک ٹیپ درخواست ئے جوڑ بوتیت۔",
  "feat.manage.checklistMock": "اہلیت ءِ چیک لسٹ کہ چار ءَ سہ شرط مکمل انت",
  "feat.manage.check1": "زمین ءِ تصدیق بوتیت",
  "feat.manage.check2": "زرع ءِ موسم مطابقت لرت",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بانکی اکاؤنٹ جوڑ بوتیت",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پاییداری",
  "feat.manage.carbonTitle": "شین طریقہ ءِ انعام",
  "feat.manage.carbonDesc": "حیاتیاتی و کم ہل ءِ طریقہ ثبت کن ات؛ سیٹلائٹ شین احاطہ تصدیق کنت و کاربن کریڈٹ ءِ قیمت ءِ تخمینہ لیت۔",
  "feat.manage.carbonMock": "کاربن ءِ خلاصہ کہ قبضہ بوتیگ ٹن و سالانہ تخمینی قیمت لریت",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ ءِ قیمت / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کسمان ءِ فورم + ماہر",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کن ات، آہے کسمان ءَ جواب گیر ات کہ خود سامنا کورتانت — تصدیق بوتیگ ماہر درست حل نشان کنانت۔",
  "feat.manage.threadMock": "کمیونٹی بحث کہ ماہر ءِ تصدیق بوتیگ جواب لریت",
  "feat.manage.threadQuestion": "کپاس ءَ سپی مچ ءِ بہترین درمان؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر ءِ تصدیق بوتیگ جواب",
  "feat.manage.threadAnswer": "نیم ءِ تل ءِ اسپرے، شام ءَ — دو واری، 5 روچ ءِ وقفہ گون۔",
  "vp.meta.title": "دید — اگروپیو",
  "vp.meta.description": "اگروپیو ءِ دید: هر کس ءِ جیب ءَ دانا زرعی راهنمایی — اول پاکستان، پنج یقین، سہ افق و اہے وعدہ کہ گیش سر نہ کننت۔",
  "vp.hero.eyebrow": "اما ءِ دید",
  "vp.hero.titleLead": "یک باوردار مددگار",
  "vp.hero.titleAccent": "ہر کس ءِ جیب ءَ.",
  "vp.hero.sub": "دانا مشورہ ءِ بھروسہ دولت، علم یا زبان ءَ نباید ببیت۔ اگروپیو ءِ واسطہ اے انت تا کہ ہر کس — ہر تلیفون ءَ، ہر دہ ءَ — اوتیرا باورا زرع کنت لیک یک ماہر ءِ برابر۔",
  "vp.hero.tagStart": "اول ات جاہے کہ لوڑ بازنت",
  "vp.hero.tagThen": "پدا جہانا گیرگ",
  "vp.hero.ctaLink": "ببین ات اما چہ جوڑ کورتانت",
  "vp.beliefs.eyebrow": "اما ءِ یقین",
  "vp.beliefs.heading": "پنج یقین ہر فیصلہ ءَ رخ دنت",
  "vp.beliefs.b1Title": "ودھگ",
  "vp.beliefs.b1Desc": "زندہ زرع، تند زمین، خوشحال کسان۔",
  "vp.beliefs.b2Title": "دانایی",
  "vp.beliefs.b2Desc": "محلی ہوا، تاریخچہ و زرع ءِ ساینس ءَ بیہ اے آی۔",
  "vp.beliefs.b3Title": "رسی",
  "vp.beliefs.b3Desc": "مشورہ ہر کس ءِ خودی زبان ءَ و خودی حال ءَ۔",
  "vp.beliefs.b4Title": "بھروسہ",
  "vp.beliefs.b4Desc": "عملی، وخت ءِ مشورہ کہ روزگار مہفوظ کنت۔",
  "vp.beliefs.b5Title": "آینده",
  "vp.beliefs.b5Desc": "دود ءِ درناوی کنگ ئے ودھیتگ ٹیکنالوجی۔",
  "vp.horizons.eyebrow": "پیسر ءِ راہ",
  "vp.horizons.heading": "سہ افق، یک لاس",
  "vp.horizons.h1Tag": "افق 01",
  "vp.horizons.h1Phase": "اکنوں",
  "vp.horizons.h1Status": "فارمان ءَ",
  "vp.horizons.h1Body": "اول پاکستان۔ بنیادی مشورہ دینک، ڈیجیٹل فارم ریکارڈ، ہوا ءِ مطابق مشورہ و شش محلی زبان — بلے ہر شی ءَ پیسر رے کسمان ءِ مشورہ ءَ گون پک بوتیت۔",
  "vp.horizons.h1P1": "بنیادی مشورہ + ریکارڈ",
  "vp.horizons.h1P2": "شش زبان",
  "vp.horizons.h1P3": "رے کسمان ءَ بہتری",
  "vp.horizons.h2Tag": "افق 02",
  "vp.horizons.h2Phase": "پیسر",
  "vp.horizons.h2Status": "ودھ بوتگ",
  "vp.horizons.h2Body": "خودی ءَ گہری و پراخی — پاکستان ءَ بزان زرع و سیمہ، زرعی ڈیٹا ءِ منبع ءِ نا گون کاپی جوڑ، و اہے تجزیہ کہ ہر سفارش ءَ ہور شخصی کنت۔",
  "vp.horizons.h2P1": "بزان زرع و سیمہ",
  "vp.horizons.h2P2": "ڈیٹا ءِ جوڑ",
  "vp.horizons.h2P3": "بلند تجزیہ",
  "vp.horizons.h3Tag": "افق 03",
  "vp.horizons.h3Phase": "پدا",
  "vp.horizons.h3Status": "جہانا",
  "vp.horizons.h3Body": "پلیٹ فارم نوکین ملکت، اقلیمان، زرع ءِ نا، زبان ءِ نا و دود ءِ نا گون ڈھل انت — جہانا ءَ ڈھلہگ ئے زرعی دانش، صفر ءَ شروع کنگ ئے بے۔",
  "vp.horizons.h3P1": "نوکین ملکت",
  "vp.horizons.h3P2": "نوکین زبان و اقلیم",
  "vp.horizons.h3P3": "جہانا ءِ پلیٹ فارم",
  "vp.outcomes.eyebrow": "بریگی ءِ شکل",
  "vp.outcomes.heading": "چار نتیجہ کہ اما خودی ءَ پرچ کننت",
  "vp.outcomes.sub": "دید ایپ ئے نہ انت — فارم ءَ بدلہگ انت۔ ہر شی اہے چار نتیجہ ءِ سامبرا روت۔",
  "vp.outcomes.o1Title": "بہترین فیصلہ",
  "vp.outcomes.o1Desc": "ہر انتخاب — آب، ان پٹ، وخت — عادت ءَ پیسر ڈیٹا ءَ۔",
  "vp.outcomes.o2Title": "بزان تولید",
  "vp.outcomes.o2Desc": "تند زرع، وخت ءَ ان پٹ، و چوٹیا کپ بوتیگ فصل۔",
  "vp.outcomes.o3Title": "کم بچگ ئے زیان",
  "vp.outcomes.o3Desc": "بیماری، کرمک و ہوا وخت ءَ گیرگ بوتنت — زرع ءِ زیان ءَ پیسر۔",
  "vp.outcomes.o4Title": "فارم کاروبار ءِ ونگا",
  "vp.outcomes.o4Desc": "ترتیب ءَ ریکارڈ و موسم ءِ دانش کہ بانک و خریدگار مننت۔",
  "vp.principles.eyebrow": "سمجھوتہ نہ انت",
  "vp.principles.heading": "اہے وعدہ کہ اما گون بنزنت",
  "vp.principles.sub": "دید جزئیات ءَ ناکام بیت۔ اہے وعدہ ہر خصوصیت، ہر صفحہ، ہر ریلیز ءَ لاگو انت — اکنوں ءَ۔",
  "vp.principles.c1Title": "کس ءِ فائدہ اول",
  "vp.principles.c1Desc": "ہر خصوصیت فارم ءِ لوڑ ءَ شروع بیت — ٹیکنالوجی ءَ گیش نہ۔",
  "vp.principles.c2Title": "زبان اول",
  "vp.principles.c2Desc": "ہر پردہ و ہر جواب کس ءِ خودی زبانا رسیت۔",
  "vp.principles.c3Title": "لمر ءَ وانگ ئے بوتگ",
  "vp.principles.c3Desc": "بلند کنٹراسٹ ماسپشت ءِ لمر ءِ واسطہ، صرف آفیس ءِ واسطہ نہ۔",
  "vp.principles.c4Title": "سادہ گال",
  "vp.principles.c4Desc": "اوتیرا سادہ کہ یک ہمسایہ بلے ئے سمجھ دیت۔",
  "vp.principles.c5Title": "اول تلیفون",
  "vp.principles.c5Desc": "موبائل اول، گوڑگ ٹچ نشان — اکنوں زرع ئے تلیفون ءَ انت۔",
  "vp.principles.c6Title": "ڈیزائین ءَ طبعی",
  "vp.principles.c6Desc": "ہلکت و بند وبست کہ طبعی لریت — ودھ، گیش ماشینری نہ۔",
  "vp.principles.motto": "خاک و سگنل — یکجا روت",
  "wy.meta.title": "اگروپیو چرا — اے آئی ئی فارم ذہنت",
  "wy.meta.description": "زراعت ئی فیصلان اٹکل ئی سرا نه دیانت بیت۔ ببین اگروپیو چونی اے آئی مشیر، فارم ئی ریکارڈ، موسم ئی آگاهی ئی رهنمائی اے مقامی زبانان یک پاکستان اول پلیٹ فارم ئی سرا جمع کنت۔",
  "wy.hero.eyebrow": "اگروپیو چرا",
  "wy.hero.titleLead": "وتہ مٹت ملێنت",
  "wy.hero.titleAccent": "سگنل ئی گؤن",
  "wy.hero.sub": "زراعت ئی فیصلان اٹکلاناں نه دیانت بیت۔ اگروپیو یک پلیٹ فارم ئی تہا اے آئی مشیر، تئی فارم ئی ریکارڈ، موسم ئی آگاهی ئی رهنمائی اے تئی وت ئی زبان دانت — تاکے هر فیصلہ تئی زمین ئی راسٹین حقیقت ئی سرا بیت۔",
  "wy.hero.ctaPrimary": "زوتر رسائی بگرئت",
  "wy.hero.ctaSecondary": "پلیٹ فارم ئے ببین",
  "wy.hero.tagStart": "پاکستان ئی بۆ جوڑ بوتگن",
  "wy.hero.tagThen": "Aplinode ئی پیداوار",
  "wy.hero.svgLabel": "زارعے ئی سرا لہرتگن خم دار لینکان",
  "wy.origin.eyebrow": "ما اے چرا جوڑ کت",
  "wy.origin.heading": "بزرگ فیصلان صرف اٹکل ئی سرا نه بیت",
  "wy.origin.sub": "اگروپیو یک سادہ مشاہدے ئے پہ شروع بوت: کشتکار ئی موسم چند فیصلان ئے گؤن ٹک بیت، اے هر فیصلہ راسٹین ذہنت ئی حق‌دار انت۔",
  "wy.origin.g1Title": "وقت ئی اٹکل",
  "wy.origin.g1Desc": "آب ڈاگ، کاد، بجی کشت، درکام — موسم ئی فیصلہ کنگ ئی لمحان ہنچؤ عادت اے امید ئے چگ بیت۔",
  "wy.origin.g2Title": "تاریخ مچ بیت",
  "wy.origin.g2Desc": "کئ سپرے بوتگنت، کئ زارعے ئے آب داتگنت، پہرؤن سال کیم مرض گندگنت — ہچ لکھگ نہ بیت، پس آئی ئی چی زانتکاری نہ بیت۔",
  "wy.origin.g3Title": "مشوران پراکنتا",
  "wy.origin.g3Desc": "ہمسایگان، دکانداران اے ویڈیوان ہر یک جواب دننت — لیکن کس ئی دستا تئی کشت، تئی مٹت یا اے ہفتگ ئی ہوا ئی راسٹین زانت نہ انت۔",
  "wy.origin.banner": "اٹکل ئی بہا درکام ئی روچ ئے ادا بیت",
  "wy.diff.eyebrow": "چی ئے اے دگار کنت",
  "wy.diff.heading1": "صرف یک دگار مشور ئی ایپ نه انت۔",
  "wy.diff.heading2": "فارم ذہنت ئی پلیٹ فارم انت۔",
  "wy.diff.sub": "بیشتر آلات صرف سوالان ئی جواب دننت۔ اگروپیو تئی فارم ئے سچنت — اے تئی لکھتگ کاران ئی گؤن زیات کارآمد بیت۔",
  "wy.diff.personalTitle": "شخصی، عام ئے نہ",
  "wy.diff.personalDesc": "تجویزان تئی کشت، تئی مقام ئے، اچی موسم ئے اے تئی فارم ئی وت ئی تاریخ ئے جوڑ بیت — کس وخت یک نسخہ ہموڑی بۆ نہ۔",
  "wy.diff.chip1": "تئی کشت",
  "wy.diff.chip2": "تئی ضلع",
  "wy.diff.chip3": "اے ہفتگ ئی موسم",
  "wy.diff.chip4": "تئی گزرتگ موسم",
  "wy.diff.langTitle": "تئی زبان ئے گپ شپ کنت",
  "wy.diff.langDesc": "چونی تئی راسٹین گپ ئے کنت، اون ئے پرس اے سم ئے بگر — مشکل انگریزی ئی ضرورت نہ انت۔",
  "wy.diff.memoryTitle": "ہر فارم ئی یادداشت",
  "wy.diff.memoryDesc": "آب ڈاگ، ان پٹ، مرض، خرچ، درکام — هر کار منظم ریکارڈ ئی تہا محفوظ، تاکے هر موسم پہرؤنی ئے بہتر شروع کنت۔",
  "wy.diff.weatherTitle": "بنیادی ئے موسم ئی آگاه",
  "wy.diff.weatherDesc": "رهنمائی تئی گہہ رسیدگ ئی پہ راسٹین حالتان ئے وانگ بیت — تاکے بارش ئے چند ساعت ئی پہ سپرے ئی تجویز نہ داتگ بیت۔",
  "wy.diff.platformTitle": "یک پلیٹ فارم، پور موسم",
  "wy.diff.platformDesc": "مشیر، ریکارڈان، موسم ئی رهنمائی اے مشورت ئے گؤن ہمکار بیت — جدا ایپان اے کتابان ئی تہا پراک نہ بیت۔",
  "wy.diff.pakTitle": "پاکستان اول",
  "wy.diff.pakDesc": "مقامی کشتان، علاقائی طریقان اے زارعے ئی راسٹین حالتان اولین روچ ئے ڈیزائن ئی تہا انت — پہ ئے شمل بوتگ فکر ئی طور ئے نہ۔",
  "wy.diff.pakBadge": "ایتھے شروع بوت",
  "wy.life.eyebrow": "مشیر کامان ئی تہا رهنمائی کنت",
  "wy.life.heading": "کشت ئی دور ئی هر فیصلے بۆ رهنمائی",
  "wy.life.sub": "یک مشیر پور کشت ئی دور ئی تہا ہمراہ انت — موسم ئی منصوبہ بندی ئے تا گھر ئے کشت ئی رساندگ ئے۔",
  "wy.life.s1Title": "آب ڈاگ ئی وقت",
  "wy.life.s1Desc": "زانت بہ کئ آب ڈاگ بیت — اے کئ منتظر بیت۔",
  "wy.life.s2Title": "کشت ئی منصوبہ بندی",
  "wy.life.s2Desc": "تئی زمین ئے موافق کشتان اے بجی کشت ئی وقتان ئے منتخب کن۔",
  "wy.life.s3Title": "کاد اے کرمکش دوا ئی رهنمائی",
  "wy.life.s3Desc": "راسٹ ان پٹ، راسٹ مقدار ئی تہا، راسٹ وقت ئی سرا۔",
  "wy.life.s4Title": "کرمک اے مرض ئی مدد",
  "wy.life.s4Desc": "مسلان ئے ژند بجانی اے پھیلگ ئی پہ اقدام کن۔",
  "wy.life.s5Title": "درکام ئی وقت",
  "wy.life.s5Desc": "اون لمحے ئے درکام کن کہ پیداوار اے معیار ئے حفاظت کنت۔",
  "wy.life.s6Title": "موسم ئی آگاه تجویزان",
  "wy.life.s6Desc": "هر تجویز اول ئے امروز ئی حالتان ئے وانگ بیت۔",
  "wy.life.s7Title": "روزانہ سوالان",
  "wy.life.s7Desc": "تئی کشت ئی بارے ئی تہا ہرچی پرس، موسم ئی ہر روچ ئے۔",
  "wy.value.eyebrow": "وعدہ",
  "wy.value.heading1": "چی کنگ۔ کئ کنگ۔",
  "wy.value.heading2": "اے چی بوتگنت۔",
  "wy.value.sub": "اگروپیو ئی هر سهولت اے سیاھ جوابان ئی ئے یک ئی خدمت کنت — اون ئے فیصلان ئی موسم اعتماد ئی موسم بیت۔",
  "wy.value.p1Heading": "چی کنگ",
  "wy.value.p1Desc": "تئی کشت اے حالتان ئے موافق روشن، خاص تجویزان — عام اشاران نہ۔",
  "wy.value.p2Heading": "کئ کنگ",
  "wy.value.p2Desc": "راسٹین موسم اے ود ئی مرحلے ئے موافق وقت، تاکے راسٹ اقدام راسٹ لمحے ئے بیت۔",
  "wy.value.p3Heading": "چی بوتگنت",
  "wy.value.p3Desc": "هر کار ئی منظم تاریخ — ہمیشہ دستیاب، ہمیشہ بہتر مشورے ئی بنیاد۔",
  "wy.who.eyebrow": "کمان ئی بۆ انت",
  "wy.who.heading": "کشتکار ئے شروع اے پہ ئے",
  "wy.who.a1Title": "انفرادی کشتکار",
  "wy.who.a1Desc": "هر فیصلے ئی تہا عملی، شخصی رهنمائی — اے ہر بوتگ کار ئی منظم ریکارڈ۔",
  "wy.who.a2Title": "تجارتی فارمان اے زراعتی کاروبار",
  "wy.who.a2Desc": "ٹیمان، زارعان اے موسمان ئی تہا منظم فارم معلومات اے بروسہ ئی قابل فیصلہ سازی ئی مدد۔",
  "wy.who.a3Title": "ایکو سسٹم ئی شریک",
  "wy.who.a3Desc": "ان پٹ دنکان، کوآپریٹوان، بیمہ شرکتان اے زراعتی توسعی خدمات — چونی چونی پلیٹ فارم ودھ بیت۔",
  "wy.who.strip": "فارم ئی گرد ماحول ئی گؤن ودھتگ",
};
