/**
 * English source of truth. Every user-visible string on translated surfaces
 * gets a key here; the other seven catalog files must mirror it (enforced by
 * catalog coverage tests and the DB sync script).
 */

export const en = {
  "nav.whyAgropioo": "Why Agropioo",
  "nav.features": "Features",
  "nav.howItWorks": "How it works",
  "nav.vision": "Vision",
  "nav.signIn": "Sign in",
  "nav.getEarlyAccess": "Get early access",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "common.languageSwitcherLabel": "Change language",
  "notFound.title": "Page not found",
  "notFound.body": "The page you are looking for does not exist or may have moved.",
  "notFound.backHome": "Back to Agropioo home",
  "common.builtForPakistan": "Built for Pakistan",
  "common.productOfAplinode": "A product of Aplinode",
  "home.hero.eyebrow": "AI-powered farm intelligence platform",
  "home.hero.titleLead": "Intelligence For",
  "home.hero.titleAccent": "Smarter Farming",
  "home.hero.subtitle": "One platform that unites an AI advisor, satellite monitoring, market prices, and your farm's records — turning data into clear decisions, in the language you speak.",
  "home.hero.ctaSecondary": "See how it works",
  "home.hero.imageAlt": "Farmer using Agropioo on a tablet in the field",
  "home.hero.readingCrop": "Crop health",
  "home.hero.readingWeather": "Weather",
  "home.hero.readingSoil": "Soil moisture",
  "home.hero.noteExcellent": "Excellent",
  "home.hero.noteClearSky": "Clear sky",
  "home.hero.noteOptimal": "Optimal",
  "home.ticker.ariaLabel": "Agropioo platform capabilities",
  "home.ticker.cropDoctor": "AI crop doctor",
  "home.ticker.satelliteNdvi": "Satellite NDVI monitoring",
  "home.ticker.mandiPrices": "Mandi price intelligence",
  "home.ticker.weatherAdvisories": "Weather-aware advisories",
  "home.ticker.farmRecords": "Digital farm records",
  "home.ticker.advisoryLanguages": "Advisory in 7 languages",
  "home.ticker.pestAlerts": "Pest outbreak alerts",
  "home.ticker.offlineSms": "Offline-first + SMS",
  "home.problem.eyebrow": "The problem",
  "home.problem.title": "Farming decisions shouldn't be a guessing game",
  "home.problem.subtitle": "Across Pakistan, farmers make high-stakes choices with tradition, local advice, and scattered information. The cost is paid at harvest.",
  "home.problem.item1Title": "Uncertain timing",
  "home.problem.item1Body": "Irrigation, fertiliser, pesticide, planting, harvest — critical moments are still guessed, costing yield and wasted inputs.",
  "home.problem.item2Title": "Lost farm history",
  "home.problem.item2Body": "Seasons of knowledge live in memory or scattered notebooks. What worked last year is impossible to learn from this year.",
  "home.problem.item3Title": "Fragmented advice",
  "home.problem.item3Body": "Neighbours, vendors, and videos all offer answers — few match the farmer's crop, soil, weather, or location.",
  "home.problem.kicker": "The cost of guessing is paid at harvest",
  "home.solution.eyebrow": "The solution",
  "home.solution.titleA": "Your farm's intelligence,",
  "home.solution.titleB": "in one place",
  "home.solution.subtitle": "One intelligence platform for the whole season — advisory, records, weather, and markets working from your land's data, not generic advice.",
  "home.solution.card1Title": "What to do",
  "home.solution.card1Body": "Personalised recommendations for irrigation, fertiliser, pest control, and harvest timing — based on your crop and conditions.",
  "home.solution.card1Answer": "Clear, specific advice for this field, this week.",
  "home.solution.card2Title": "When to do it",
  "home.solution.card2Body": "Weather-aware guidance tells you the right moment to act, so bad timing and sudden conditions stop costing you yield.",
  "home.solution.card2Answer": "Timing tuned to real weather and growth stage.",
  "home.solution.card3Title": "What has been done",
  "home.solution.card3Body": "Every activity — irrigation, inputs, disease, expenses, harvest — kept as a structured record that makes each season smarter.",
  "home.solution.card3Answer": "A complete history, always within reach.",
  "home.features.eyebrow": "Inside the platform",
  "home.features.titleA": "Multiple engines,",
  "home.features.titleB": "one intelligence platform",
  "home.features.subtitle": "From a single question in your own words to a season-long record — each capability feeds the next.",
  "home.features.advisorModule": "Module 01 · Advisor",
  "home.features.advisorTitle": "AI agriculture advisor",
  "home.features.advisorTopics": "Irrigation · fertiliser · pest & disease · harvest",
  "home.features.advisorBadge": "Roman Urdu",
  "home.features.advisorMockAria": "Example conversation with the Agropioo advisor about yellowing wheat leaves",
  "home.features.advisorUserMsg": "Meri gandum ki pattiyan peeli ho rahi hain — kya karoon?",
  "home.features.advisorReplyTitle": "Peeli pattiyan — do common causes:",
  "home.features.advisorReplyCause1": "Water stress",
  "home.features.advisorReplyCause1Rest": "— irrigate in the cool hours, before 9 AM.",
  "home.features.advisorReplyCause2": "Nitrogen shortage",
  "home.features.advisorReplyCause2Rest": "— check the oldest leaves first; feed urea if needed.",
  "home.features.advisorReplyFooter": "Agar pattiyon ke neeche peeli dhariyan nazar aayein, photo bhejein — main bimari ki tashkhees kar dunga.",
  "home.features.advisorInputPlaceholder": "Apna sawal likhein ya bolein…",
  "home.features.advisorFooter": "Ask anything about your crop — everyday questions welcome.",
  "home.features.recordsModule": "Module 02 · Records",
  "home.features.recordsTitle": "Digital farm record",
  "home.features.recordsDesc": "Every activity logged and structured — so advice learns from your own land.",
  "home.features.record1Activity": "Irrigation",
  "home.features.record1Detail": "Canal · 40 min",
  "home.features.record2Activity": "Urea 46% N",
  "home.features.record2Detail": "25 kg / acre",
  "home.features.record3Activity": "Leaf scan",
  "home.features.record3Detail": "No disease found",
  "home.features.recordsCropTag": "Wheat · Rabi season",
  "home.features.languageModule": "Module 03 · Language",
  "home.features.languageTitle": "Your language, your words",
  "home.features.languageDesc": "Speak or type the way you think — no technical English required.",
  "home.features.weatherModule": "Module 04 · Weather",
  "home.features.weatherTitle": "Weather-aware guidance",
  "home.features.weatherDesc": "Advice checks real conditions before it reaches you — spray before rain and you have washed your inputs away.",
  "home.features.weatherMockAria": "Five-day forecast strip highlighting Thursday as a no-spray advisory day",
  "home.features.dayMon": "Mon",
  "home.features.dayTue": "Tue",
  "home.features.dayWed": "Wed",
  "home.features.dayThu": "Thu",
  "home.features.dayFri": "Fri",
  "home.features.holdSpray": "Hold spray",
  "home.features.weatherLegend": "Advisory day flagged from hyperlocal forecast",
  "home.features.moreLink": "The platform keeps growing — see the full capability stack",
  "home.journey.eyebrow": "How it works",
  "home.journey.title": "One question starts the season",
  "home.journey.subtitle": "A simple path from your first question to a complete, intelligent farm history.",
  "home.journey.step1Title": "Add your farm",
  "home.journey.step1Body": "Enter your location, crop, and basic details to create a digital farm profile.",
  "home.journey.step2Title": "Ask the AI",
  "home.journey.step2Body": "Type or speak your question in the language you are most comfortable with.",
  "home.journey.step3Title": "Get guidance",
  "home.journey.step3Body": "Receive advice grounded in your crop, weather, location, and farm history.",
  "home.journey.step4Title": "Record activity",
  "home.journey.step4Body": "Log irrigation, fertiliser, pesticide, or disease with a few taps.",
  "home.journey.step5Title": "Build history",
  "home.journey.step5Body": "Every record makes future recommendations smarter and more relevant.",
  "home.journey.step6Title": "Keep monitoring",
  "home.journey.step6Body": "Review records and track progress through the whole season.",
  "home.matrix.eyebrow": "Full capability stack",
  "home.matrix.title": "From must-haves to marvels",
  "home.matrix.subtitle": "Every feature protects crops, cuts costs, or grows income. Read it like an almanac — each tier builds on the last.",
  "home.matrix.capabilitiesLabel": "capabilities",
  "home.matrix.tier1Name": "Must-Have",
  "home.matrix.tier1Badge": "Baseline",
  "home.matrix.t1f1Title": "AI crop disease detection",
  "home.matrix.t1f1Body": "Upload a photo of an affected leaf and get instant disease diagnosis, severity, and treatment recommendations.",
  "home.matrix.t1f2Title": "Satellite field monitoring",
  "home.matrix.t1f2Body": "Mark your field boundary and view NDVI-based crop health zones from free Sentinel-2 imagery.",
  "home.matrix.t1f3Title": "Smart weather advisory",
  "home.matrix.t1f3Body": "Hyperlocal forecasts combined with your crop and growth stage become daily, actionable advice.",
  "home.matrix.t1f4Title": "Mandi price tracker & predictor",
  "home.matrix.t1f4Body": "Track nearby market prices with AI trend predictions, so you sell at the right time.",
  "home.matrix.tier2Name": "Differentiators",
  "home.matrix.tier2Badge": "Stand out",
  "home.matrix.t2f1Title": "Regional language voice chatbot",
  "home.matrix.t2f1Body": "Speak or type in Urdu, Punjabi, Saraiki, and more — hear answers in the language you understand best.",
  "home.matrix.t2f2Title": "Government scheme matcher",
  "home.matrix.t2f2Body": "Enter your profile and discover every scheme you qualify for, with documents and apply links.",
  "home.matrix.t2f3Title": "Crop recommendation engine",
  "home.matrix.t2f3Body": "The most profitable crop for your soil, weather, market demand, and budget this season.",
  "home.matrix.t2f4Title": "Farm profit / loss calculator",
  "home.matrix.t2f4Body": "Expected and actual costs, yield, revenue, and profit — with break-even and ROI insights.",
  "home.matrix.t2f5Title": "Community forum + expert connect",
  "home.matrix.t2f5Body": "Post questions, share photos, get answers from fellow farmers and verified agriculture experts.",
  "home.matrix.tier3Name": "Wow Factor",
  "home.matrix.tier3Badge": "Ahead of the field",
  "home.matrix.t3f1Title": "Satellite change detection",
  "home.matrix.t3f1Body": "Compare satellite images over time with a slider to track growth, damage, or encroachment.",
  "home.matrix.t3f2Title": "AI pest outbreak prediction",
  "home.matrix.t3f2Body": "Early warnings ahead of likely pest attacks, based on weather, crop stage, and history.",
  "home.matrix.t3f3Title": "Voice-first phone call mode",
  "home.matrix.t3f3Body": "Dial a toll-free number, speak your question, hear advice in your language — no smartphone needed.",
  "home.matrix.t3f4Title": "Carbon credit estimator",
  "home.matrix.t3f4Body": "Log sustainable practices and estimate carbon credits from voluntary markets.",
  "home.matrix.t3f5Title": "Offline-first PWA + SMS alerts",
  "home.matrix.t3f5Body": "Works offline in the field, syncs when connected, alerts via SMS when data is spotty.",
} as const;

export type CatalogKey = keyof typeof en;
