/**
 * English source of truth. Every user-visible string on translated surfaces
 * gets a key here; the other seven catalog files must mirror it (enforced by
 * catalog coverage tests and the DB sync script).
 */

export const en = {
  "nav.whyAgropioo": "Why Agropioo",
  "nav.features": "Features",
  "nav.howItWorks": "How it works",
  "nav.vision": "Vision",
  "nav.signIn": "Sign in",
  "nav.getEarlyAccess": "Get early access",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "common.languageSwitcherLabel": "Change language",
  "notFound.title": "Page not found",
  "notFound.body": "The page you are looking for does not exist or may have moved.",
  "notFound.backHome": "Back to Agropioo home",
  "common.builtForPakistan": "Built for Pakistan",
  "common.productOfAplinode": "A product of Aplinode",
  "home.hero.eyebrow": "AI-powered farm intelligence platform",
  "home.hero.titleLead": "Intelligence For",
  "home.hero.titleAccent": "Smarter Farming",
  "home.hero.subtitle": "One platform that unites an AI advisor, satellite monitoring, market prices, and your farm's records — turning data into clear decisions, in the language you speak.",
  "home.hero.ctaSecondary": "See how it works",
  "home.hero.imageAlt": "Farmer using Agropioo on a tablet in the field",
  "home.hero.readingCrop": "Crop health",
  "home.hero.readingWeather": "Weather",
  "home.hero.readingSoil": "Soil moisture",
  "home.hero.noteExcellent": "Excellent",
  "home.hero.noteClearSky": "Clear sky",
  "home.hero.noteOptimal": "Optimal",
  "home.ticker.ariaLabel": "Agropioo platform capabilities",
  "home.ticker.cropDoctor": "AI crop doctor",
  "home.ticker.satelliteNdvi": "Satellite NDVI monitoring",
  "home.ticker.mandiPrices": "Mandi price intelligence",
  "home.ticker.weatherAdvisories": "Weather-aware advisories",
  "home.ticker.farmRecords": "Digital farm records",
  "home.ticker.advisoryLanguages": "Advisory in 7 languages",
  "home.ticker.pestAlerts": "Pest outbreak alerts",
  "home.ticker.offlineSms": "Offline-first + SMS",
  "home.problem.eyebrow": "The problem",
  "home.problem.title": "Farming decisions shouldn't be a guessing game",
  "home.problem.subtitle": "Across Pakistan, farmers make high-stakes choices with tradition, local advice, and scattered information. The cost is paid at harvest.",
  "home.problem.item1Title": "Uncertain timing",
  "home.problem.item1Body": "Irrigation, fertiliser, pesticide, planting, harvest — critical moments are still guessed, costing yield and wasted inputs.",
  "home.problem.item2Title": "Lost farm history",
  "home.problem.item2Body": "Seasons of knowledge live in memory or scattered notebooks. What worked last year is impossible to learn from this year.",
  "home.problem.item3Title": "Fragmented advice",
  "home.problem.item3Body": "Neighbours, vendors, and videos all offer answers — few match the farmer's crop, soil, weather, or location.",
  "home.problem.kicker": "The cost of guessing is paid at harvest",
  "home.solution.eyebrow": "The solution",
  "home.solution.titleA": "Your farm's intelligence,",
  "home.solution.titleB": "in one place",
  "home.solution.subtitle": "One intelligence platform for the whole season — advisory, records, weather, and markets working from your land's data, not generic advice.",
  "home.solution.card1Title": "What to do",
  "home.solution.card1Body": "Personalised recommendations for irrigation, fertiliser, pest control, and harvest timing — based on your crop and conditions.",
  "home.solution.card1Answer": "Clear, specific advice for this field, this week.",
  "home.solution.card2Title": "When to do it",
  "home.solution.card2Body": "Weather-aware guidance tells you the right moment to act, so bad timing and sudden conditions stop costing you yield.",
  "home.solution.card2Answer": "Timing tuned to real weather and growth stage.",
  "home.solution.card3Title": "What has been done",
  "home.solution.card3Body": "Every activity — irrigation, inputs, disease, expenses, harvest — kept as a structured record that makes each season smarter.",
  "home.solution.card3Answer": "A complete history, always within reach.",
  "home.features.eyebrow": "Inside the platform",
  "home.features.titleA": "Multiple engines,",
  "home.features.titleB": "one intelligence platform",
  "home.features.subtitle": "From a single question in your own words to a season-long record — each capability feeds the next.",
  "home.features.advisorModule": "Module 01 · Advisor",
  "home.features.advisorTitle": "AI agriculture advisor",
  "home.features.advisorTopics": "Irrigation · fertiliser · pest & disease · harvest",
  "home.features.advisorBadge": "Roman Urdu",
  "home.features.advisorMockAria": "Example conversation with the Agropioo advisor about yellowing wheat leaves",
  "home.features.advisorUserMsg": "Meri gandum ki pattiyan peeli ho rahi hain — kya karoon?",
  "home.features.advisorReplyTitle": "Peeli pattiyan — do common causes:",
  "home.features.advisorReplyCause1": "Water stress",
  "home.features.advisorReplyCause1Rest": "— irrigate in the cool hours, before 9 AM.",
  "home.features.advisorReplyCause2": "Nitrogen shortage",
  "home.features.advisorReplyCause2Rest": "— check the oldest leaves first; feed urea if needed.",
  "home.features.advisorReplyFooter": "Agar pattiyon ke neeche peeli dhariyan nazar aayein, photo bhejein — main bimari ki tashkhees kar dunga.",
  "home.features.advisorInputPlaceholder": "Apna sawal likhein ya bolein…",
  "home.features.advisorFooter": "Ask anything about your crop — everyday questions welcome.",
  "home.features.recordsModule": "Module 02 · Records",
  "home.features.recordsTitle": "Digital farm record",
  "home.features.recordsDesc": "Every activity logged and structured — so advice learns from your own land.",
  "home.features.record1Activity": "Irrigation",
  "home.features.record1Detail": "Canal · 40 min",
  "home.features.record2Activity": "Urea 46% N",
  "home.features.record2Detail": "25 kg / acre",
  "home.features.record3Activity": "Leaf scan",
  "home.features.record3Detail": "No disease found",
  "home.features.recordsCropTag": "Wheat · Rabi season",
  "home.features.languageModule": "Module 03 · Language",
  "home.features.languageTitle": "Your language, your words",
  "home.features.languageDesc": "Speak or type the way you think — no technical English required.",
  "home.features.weatherModule": "Module 04 · Weather",
  "home.features.weatherTitle": "Weather-aware guidance",
  "home.features.weatherDesc": "Advice checks real conditions before it reaches you — spray before rain and you have washed your inputs away.",
  "home.features.weatherMockAria": "Five-day forecast strip highlighting Thursday as a no-spray advisory day",
  "home.features.dayMon": "Mon",
  "home.features.dayTue": "Tue",
  "home.features.dayWed": "Wed",
  "home.features.dayThu": "Thu",
  "home.features.dayFri": "Fri",
  "home.features.holdSpray": "Hold spray",
  "home.features.weatherLegend": "Advisory day flagged from hyperlocal forecast",
  "home.features.moreLink": "The platform keeps growing — see the full capability stack",
  "home.journey.eyebrow": "How it works",
  "home.journey.title": "One question starts the season",
  "home.journey.subtitle": "A simple path from your first question to a complete, intelligent farm history.",
  "home.journey.step1Title": "Add your farm",
  "home.journey.step1Body": "Enter your location, crop, and basic details to create a digital farm profile.",
  "home.journey.step2Title": "Ask the AI",
  "home.journey.step2Body": "Type or speak your question in the language you are most comfortable with.",
  "home.journey.step3Title": "Get guidance",
  "home.journey.step3Body": "Receive advice grounded in your crop, weather, location, and farm history.",
  "home.journey.step4Title": "Record activity",
  "home.journey.step4Body": "Log irrigation, fertiliser, pesticide, or disease with a few taps.",
  "home.journey.step5Title": "Build history",
  "home.journey.step5Body": "Every record makes future recommendations smarter and more relevant.",
  "home.journey.step6Title": "Keep monitoring",
  "home.journey.step6Body": "Review records and track progress through the whole season.",
  "home.matrix.eyebrow": "Full capability stack",
  "home.matrix.title": "From must-haves to marvels",
  "home.matrix.subtitle": "Every feature protects crops, cuts costs, or grows income. Read it like an almanac — each tier builds on the last.",
  "home.matrix.capabilitiesLabel": "capabilities",
  "home.matrix.tier1Name": "Must-Have",
  "home.matrix.tier1Badge": "Baseline",
  "home.matrix.t1f1Title": "AI crop disease detection",
  "home.matrix.t1f1Body": "Upload a photo of an affected leaf and get instant disease diagnosis, severity, and treatment recommendations.",
  "home.matrix.t1f2Title": "Satellite field monitoring",
  "home.matrix.t1f2Body": "Mark your field boundary and view NDVI-based crop health zones from free Sentinel-2 imagery.",
  "home.matrix.t1f3Title": "Smart weather advisory",
  "home.matrix.t1f3Body": "Hyperlocal forecasts combined with your crop and growth stage become daily, actionable advice.",
  "home.matrix.t1f4Title": "Mandi price tracker & predictor",
  "home.matrix.t1f4Body": "Track nearby market prices with AI trend predictions, so you sell at the right time.",
  "home.matrix.tier2Name": "Differentiators",
  "home.matrix.tier2Badge": "Stand out",
  "home.matrix.t2f1Title": "Regional language voice chatbot",
  "home.matrix.t2f1Body": "Speak or type in Urdu, Punjabi, Saraiki, and more — hear answers in the language you understand best.",
  "home.matrix.t2f2Title": "Government scheme matcher",
  "home.matrix.t2f2Body": "Enter your profile and discover every scheme you qualify for, with documents and apply links.",
  "home.matrix.t2f3Title": "Crop recommendation engine",
  "home.matrix.t2f3Body": "The most profitable crop for your soil, weather, market demand, and budget this season.",
  "home.matrix.t2f4Title": "Farm profit / loss calculator",
  "home.matrix.t2f4Body": "Expected and actual costs, yield, revenue, and profit — with break-even and ROI insights.",
  "home.matrix.t2f5Title": "Community forum + expert connect",
  "home.matrix.t2f5Body": "Post questions, share photos, get answers from fellow farmers and verified agriculture experts.",
  "home.matrix.tier3Name": "Wow Factor",
  "home.matrix.tier3Badge": "Ahead of the field",
  "home.matrix.t3f1Title": "Satellite change detection",
  "home.matrix.t3f1Body": "Compare satellite images over time with a slider to track growth, damage, or encroachment.",
  "home.matrix.t3f2Title": "AI pest outbreak prediction",
  "home.matrix.t3f2Body": "Early warnings ahead of likely pest attacks, based on weather, crop stage, and history.",
  "home.matrix.t3f3Title": "Voice-first phone call mode",
  "home.matrix.t3f3Body": "Dial a toll-free number, speak your question, hear advice in your language — no smartphone needed.",
  "home.matrix.t3f4Title": "Carbon credit estimator",
  "home.matrix.t3f4Body": "Log sustainable practices and estimate carbon credits from voluntary markets.",
  "home.matrix.t3f5Title": "Offline-first PWA + SMS alerts",
  "home.matrix.t3f5Body": "Works offline in the field, syncs when connected, alerts via SMS when data is spotty.",
  "home.vision.eyebrow": "The vision",
  "home.vision.titleA": "Built for Pakistan.",
  "home.vision.titleB": "Ready for the world.",
  "home.vision.pkTitle": "Pakistan-first approach",
  "home.vision.pkBody": "Version one is designed for Pakistan's fields: local crops, regional languages, real farming practices, real field conditions.",
  "home.vision.pkPoint1": "Local crop and climate knowledge",
  "home.vision.pkPoint2": "Urdu, Punjabi, Pashto, Sindhi, Saraiki, Balochi, Hindko",
  "home.vision.pkPoint3": "Refined through real farmer feedback",
  "home.vision.worldTitle": "Global expansion vision",
  "home.vision.worldBody": "Built to adapt. As the platform matures it scales to new countries, languages, crops, and climates — without rebuilding from scratch.",
  "home.vision.worldPoint1": "Country-specific agricultural knowledge",
  "home.vision.worldPoint2": "Additional languages and local crops",
  "home.vision.worldPoint3": "Deeper data integrations and analytics",
  "home.users.title1": "Individual farmers",
  "home.users.desc1": "Small and mid-size farms that need practical guidance and an organised record of every activity.",
  "home.users.title2": "Commercial farms",
  "home.users.desc2": "Agricultural businesses that need structured information, decision support, and team-wide records.",
  "home.users.title3": "Ecosystem partners",
  "home.users.desc3": "Input suppliers, cooperatives, insurers, and extension services joining the platform over time.",
  "home.users.tagline": "Designed for farmers first — growing with the ecosystem",
  "home.cta.eyebrow": "Early access",
  "home.cta.title": "Bring your farm onto the platform",
  "home.cta.subtitle": "Join the farmers making better decisions with Agropioo — starting in Pakistan, growing worldwide.",
  "home.cta.success": "You're on the list. We'll be in touch when your region opens.",
  "home.cta.emailLabel": "Email address",
  "home.cta.fineprint": "No spam. Unsubscribe anytime.",
  "home.footer.tagline": "The AI-powered farm intelligence platform. Advisory, satellite monitoring, market prices, and records — soil and signal, together.",
  "home.footer.pagesHeading": "Pages",
  "home.footer.pagesNavLabel": "Footer pages",
  "home.footer.legalHeading": "Legal",
  "home.footer.legalNavLabel": "Legal",
  "home.footer.privacy": "Privacy Policy",
  "home.footer.terms": "Terms of Service",
  "home.footer.cookies": "Cookie Policy",
  "home.footer.disclaimer": "Disclaimer",
  "home.footer.contactHeading": "Get in touch",
  "home.footer.country": "Pakistan",
  "home.footer.copyright": "© {year} Agropioo. All rights reserved.",
  "home.footer.motto": "Built for Pakistan · Ready for the world",
  "hiw.meta.title": "How it works — Agropioo",
  "hiw.meta.description":
    "From a one-minute farm profile to a season loop that keeps improving: see how Agropioo turns questions, activity, and records into personalised farming guidance.",
  "hiw.hero.eyebrow": "How it works",
  "hiw.hero.titleA": "Six small steps.",
  "hiw.hero.titleLead": "One",
  "hiw.hero.titleAccent": "smarter season.",
  "hiw.hero.subtitle":
    "Agropioo works the way farming already works — you plant, ask, act, and record. The only difference is that now every step teaches the next one.",
  "hiw.hero.browseFeatures": "Browse features",
  "hiw.route.navLabel": "The six steps of the Agropioo season loop",
  "hiw.route.stepLabel": "Step {n}: {stop}",
  "hiw.route.stop1": "Add farm",
  "hiw.route.stop2": "Ask",
  "hiw.route.stop3": "Guidance",
  "hiw.route.stop4": "Act",
  "hiw.route.stop5": "Record",
  "hiw.route.stop6": "Better advice",
  "hiw.setup.eyebrow": "Set up once",
  "hiw.setup.title": "Your farm becomes a living profile",
  "hiw.setup.body":
    "Four fields, under a minute — district, crop, sowing date, and land size. That is the whole form. From here on, every answer knows where it is growing and what it is growing in.",
  "hiw.setup.point1": "Change crop or add fields anytime",
  "hiw.setup.point2": "Multiple farms for contractors and dealers",
  "hiw.setup.point3": "Nothing technical asked — no soil reports needed",
  "hiw.setup.mockHeading": "New farm profile",
  "hiw.setup.mockButton": "Create farm profile",
  "hiw.setup.mockFootnote": "Takes less than a minute",
  "hiw.setup.mockLabel":
    "Farm profile form with district, crop, sowing date and land size filled in",
  "hiw.setup.rowDistrict": "District",
  "hiw.setup.valDistrict": "Multan",
  "hiw.setup.rowCrop": "Crop",
  "hiw.setup.valCrop": "Wheat · Rabi",
  "hiw.setup.rowSowing": "Sowing date",
  "hiw.setup.valSowing": "20 Nov",
  "hiw.setup.rowLand": "Land",
  "hiw.setup.valLand": "12 acres",
  "hiw.ask.eyebrow": "Ask anything",
  "hiw.ask.titleA": "One question in.",
  "hiw.ask.titleB": "Your whole farm answers.",
  "hiw.ask.body":
    "The same question means different things on different farms. So before replying, Agropioo reads the question against everything it already knows about yours.",
  "hiw.ask.pipelineLabel":
    "A farmer question is combined with crop, district, weather and history context to produce a personalised answer",
  "hiw.ask.question": "Ab pani dena chahiye ya thora intezar?",
  "hiw.ask.checkedAgainst": "Checked against",
  "hiw.ask.chipCrop": "Crop",
  "hiw.ask.chipValCrop": "Wheat · tillering",
  "hiw.ask.chipDistrict": "District",
  "hiw.ask.chipValDistrict": "Multan",
  "hiw.ask.chipWeather": "Weather",
  "hiw.ask.chipValWeather": "26°C · dry week",
  "hiw.ask.chipHistory": "History",
  "hiw.ask.chipValHistory": "Urea 9 days ago",
  "hiw.ask.answer":
    "Do din rukein — barish ka chance hai, aur urea ke baad zameen abhi geeli hai. Jumma tak check karna kaafi hai.",
  "hiw.ask.answerMeta": "Personalised · wheat, day 9 after urea",
  "hiw.ask.footnote": "Type it, speak it, or call it in — the answer stays personal",
  "hiw.engine.eyebrow": "Behind the answer",
  "hiw.engine.title": "Four checks before you see one line",
  "hiw.engine.body":
    "Guidance is not a search result. It passes through four gates so what reaches you is safe for this field, this week.",
  "hiw.engine.check1Title": "Gather",
  "hiw.engine.check1Desc":
    "Farm profile, live weather, and crop stage are pulled together the moment you hit send.",
  "hiw.engine.check2Title": "Cross-check",
  "hiw.engine.check2Desc":
    "Advice is tested against the forecast — a spray that rain would waste never leaves the engine.",
  "hiw.engine.check3Title": "Personalise",
  "hiw.engine.check3Desc":
    "Your field history tilts the answer — same crop, different soil, different advice.",
  "hiw.engine.check4Title": "Deliver",
  "hiw.engine.check4Desc":
    "Out it comes as clear steps in your language — on screen, by voice, or over a phone call.",
  "hiw.engine.safetyStrong": "If something looks unsafe,",
  "hiw.engine.safetyRest":
    "Agropioo says wait — a delayed answer beats a wasted spray or a damaged crop.",
  "hiw.record.recorderHeading": "Log an activity",
  "hiw.record.syncBadge": "Auto-sync on",
  "hiw.record.actionIrrigation": "Irrigation",
  "hiw.record.actionFertiliser": "Fertiliser",
  "hiw.record.actionPesticide": "Pesticide",
  "hiw.record.actionDisease": "Disease",
  "hiw.record.actionExpense": "Expense",
  "hiw.record.actionHarvest": "Harvest",
  "hiw.record.row1Time": "Today · 6:40 AM",
  "hiw.record.row1Label": "Irrigation logged",
  "hiw.record.row1Detail": "Canal turn · 40 min · plot B",
  "hiw.record.row2Time": "Yesterday",
  "hiw.record.row2Label": "Fertiliser logged",
  "hiw.record.row2Detail": "DAP 20 kg / acre",
  "hiw.record.offlineNote": "→ Two taps per entry — offline bhi chalta hai",
  "hiw.record.mockLabel":
    "Activity recorder with quick action chips and recently logged rows",
  "hiw.record.eyebrow": "Record as you go",
  "hiw.record.titleA": "Two taps now,",
  "hiw.record.titleB": "smarter answers all season",
  "hiw.record.body":
    "Recording is built for the field — big buttons, few fields, no typing required. Each entry becomes part of the farm's memory, so advice keeps sharpening while the crop keeps growing.",
  "hiw.record.point1": "Irrigation, inputs, disease, expenses, harvest — one timeline",
  "hiw.record.point2": "Works fully offline; syncs when signal returns",
  "hiw.record.point3": "Season summary ready for banks, buyers, or insurance",
  "hiw.loop.eyebrow": "The season loop",
  "hiw.loop.titleA": "It doesn't end at harvest.",
  "hiw.loop.titleB": "It starts there.",
  "hiw.loop.body":
    "Ask, act, record — repeat. Each turn of the loop feeds what the platform knows about your land, so the next season begins ahead of the last one.",
  "hiw.loop.benefit1Title": "Advice compounds",
  "hiw.loop.benefit1Desc": "Last season's disease, doses, and dates shape this season's first answer.",
  "hiw.loop.benefit2Title": "Nothing gets repeated",
  "hiw.loop.benefit2Desc":
    "The advisor knows what was already sprayed or fed — no double dosing.",
  "hiw.loop.benefit3Title": "Every season documented",
  "hiw.loop.benefit3Desc":
    "A clean history stays ready for loans, buyers, insurance, or the next crop decision.",
    "hiw.loop.stepLearn": "Learn",
  "hiw.loop.stepImprove": "Improve",
"hiw.loop.diagramLabel": "Circular loop diagram: ask, act, record, learn, improve",
  "hiw.loop.centerSeason": "SEASON",
  "hiw.loop.centerLoop": "LOOP",
  "hiw.loop.caption": "Har season, pichle se behtar",
  "feat.meta.title": "Features — Agropioo",
  "feat.meta.description": "Explore every Agropioo capability: AI crop doctor, satellite NDVI monitoring, mandi price prediction, voice advisory in local languages, offline access with SMS alerts, and more.",
  "feat.hero.eyebrow": "Features",
  "feat.hero.titleLead": "Everything your",
  "feat.hero.titleAccent": "season asks for",
  "feat.hero.subtitle": "Fourteen capabilities working as one — scanning leaves, watching fields from orbit, reading the mandi, and speaking your language. Explore what each one does for your farm.",
  "feat.hero.ctaPrimary": "Get early access",
  "feat.hero.ctaSecondary": "See how it works",
  "feat.hero.builtFor": "Built for Pakistan",
  "feat.hero.productOf": "A product of Aplinode",
  "feat.hero.tile1Label": "Leaf scan",
  "feat.hero.tile1Value": "94% ok",
  "feat.hero.tile2Label": "Mandi wheat",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI field",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "Pest risk",
  "feat.hero.tile4Value": "Low · 7d",
  "feat.hero.voiceReady": "Voice advisory ready",
  "feat.hero.voiceLangs": "Urdu · پنجابی · Saraiki",
  "feat.hero.liveBadge": "Live",
  "feat.hero.smsLabel": "SMS alert · offline mode",
  "feat.hero.smsMsg": "Barish 3 PM — spray rokein",
  "feat.intel.eyebrow": "Crop intelligence",
  "feat.intel.heading": "See problems before they cost you",
  "feat.intel.sub": "Disease, pests, weather, and crop choice — the four decisions that decide a harvest, each backed by its own engine.",
  "feat.intel.included": "Included",
  "feat.intel.doctorCode": "F·01 · Vision",
  "feat.intel.doctorTitle": "AI crop doctor",
  "feat.intel.doctorDesc": "Photograph an affected leaf and receive the disease name, severity level, and a treatment plan in seconds.",
  "feat.intel.doctorMock": "Leaf scan result showing yellow rust detected with high confidence",
  "feat.intel.diseaseName": "Yellow rust",
  "feat.intel.matchScore": "94% match",
  "feat.intel.severityLabel": "Severity",
  "feat.intel.severityValue": "Moderate",
  "feat.intel.pestCode": "F·02 · Forecast",
  "feat.intel.pestTitle": "Pest outbreak alerts",
  "feat.intel.pestDesc": "Weather and crop stage feed a risk model that warns days before conditions favour an attack.",
  "feat.intel.pestMock": "Seven day pest risk bars rising to high on day six",
  "feat.intel.pestAlert": "Saturday · locust risk 74% — cover young wheat",
  "feat.intel.weatherCode": "F·03 · Weather",
  "feat.intel.weatherTitle": "Weather-aware advisories",
  "feat.intel.weatherDesc": "Hyperlocal forecasts meet your crop and growth stage — advice arrives as a clear instruction, not raw data.",
  "feat.intel.weatherMock": "Example weather advisory advising delayed irrigation before rain",
  "feat.intel.delayIrrigation": "Delay irrigation today",
  "feat.intel.rainNote": "Rain expected around 3 PM — let the sky water your field first.",
  "feat.intel.waterSaved": "Water saved",
  "feat.intel.cropCode": "F·04 · Planning",
  "feat.intel.cropTitle": "Crop recommendation",
  "feat.intel.cropDesc": "Soil, weather, demand, and your budget are scored together — plant what pays this season.",
  "feat.intel.cropMock": "Ranked crop recommendations with wheat first",
  "feat.intel.crop1": "Wheat",
  "feat.intel.crop2": "Mustard",
  "feat.intel.crop3": "Gram",
  "feat.field.eyebrow": "Field & market intelligence",
  "feat.field.headingA": "Your land measured from orbit.",
  "feat.field.headingB": "Your crop priced by data.",
  "feat.field.sub": "Satellite eyes on every acre and a read on every nearby mandi — so growth and selling both happen at the right moment.",
  "feat.field.ndviCode": "F·05 · Satellite",
  "feat.field.ndviTitle": "NDVI field monitoring",
  "feat.field.ndviDesc": "Mark your boundary once; health zones update with every clear satellite pass — weak patches surface before the eye catches them.",
  "feat.field.ndviMock": "Field health grid where darker green means stronger crop growth",
  "feat.field.weakZone": "Weak zone · row 2",
  "feat.field.priceCode": "F·06 · Market",
  "feat.field.priceTitle": "Mandi price predictor",
  "feat.field.priceDesc": "Live rates from nearby markets plus a trend forecast — sell when the curve says so, not when the buyer does.",
  "feat.field.priceMock": "Wheat price trend rising over eight weeks with a hold recommendation",
  "feat.field.wheatTrend": "Wheat · 8 weeks",
  "feat.field.holdStock": "↑ 12% — hold stock",
  "feat.field.financeCode": "F·07 · Finance",
  "feat.field.financeTitle": "Profit & loss tracker",
  "feat.field.financeDesc": "Every rupee in and out, season-long — with break-even and ROI ready before you step into the mandi or the bank.",
  "feat.field.ledgerMock": "Season cost ledger showing inputs labour irrigation and revenue",
  "feat.field.rowInputs": "Inputs",
  "feat.field.rowLabour": "Labour",
  "feat.field.rowIrrigation": "Irrigation",
  "feat.field.rowRevenue": "Revenue (est.)",
  "feat.field.netMargin": "Net margin",
  "feat.voice.eyebrow": "Access for everyone",
  "feat.voice.headingA": "No smartphone?",
  "feat.voice.headingB": "No English? Still in.",
  "feat.voice.sub": "The best advice is useless if it never reaches the farmer. Every capability answers a phone call, hears a voice, and survives a dead zone.",
  "feat.voice.speakCode": "F·08 · Voice",
  "feat.voice.speakTitle": "Speak your question",
  "feat.voice.speakMock": "Voice conversation with the advisor in Roman Urdu",
  "feat.voice.chatUser": "Meri fasal ke patton par dhabbe hain",
  "feat.voice.chatAdvisor": "Dhabbon ki photo bhejein — main abhi tashkhees karta hoon.",
  "feat.voice.inputPlaceholder": "Bol kar poochein…",
  "feat.voice.callCode": "F·09 · Call",
  "feat.voice.callTitle": "Dial a toll-free number",
  "feat.voice.callMock": "Toll free call transcript with the Agropioo voice assistant",
  "feat.voice.greetingLine": "Agropioo mein aapka swagat hai",
  "feat.voice.heardLine": "Awaaz samajh li — jawab tayar hai",
  "feat.voice.callEnded": "Call ended · summary saved",
  "feat.voice.anyPhone": "Works on any phone · no internet",
  "feat.voice.offlineCode": "F·10 · Offline + SMS",
  "feat.voice.offlineTitle": "Dead zones don't stop it",
  "feat.voice.offlineDesc": "Advisories, records, and calculators keep working without a signal; everything syncs when the network returns, and critical alerts arrive by SMS.",
  "feat.voice.networkStatus": "Network status",
  "feat.voice.offlineQueued": "Offline · queued 3 records",
  "feat.voice.smsStamp": "SMS · 07:42",
  "feat.voice.smsMsg": "Mosam alert: barish sham 3 baje — spray waqt badal lein.",
  "feat.manage.eyebrow": "Manage & grow",
  "feat.manage.headingA": "Advice is the start.",
  "feat.manage.headingB": "The rest runs on records.",
  "feat.manage.sub": "History, subsidies, sustainability, and a community of farmers — the quiet features that compound every season.",
  "feat.manage.diaryCode": "F·11 · Records",
  "feat.manage.diaryTitle": "Digital farm diary",
  "feat.manage.diaryDesc": "Irrigation to harvest, everything lands on one timeline the advisor reads before answering.",
  "feat.manage.timelineMock": "Farm activity timeline for August",
  "feat.manage.tl1Date": "12 Aug",
  "feat.manage.tl1Label": "Irrigation",
  "feat.manage.tl1Detail": "Canal turn · 40 min",
  "feat.manage.tl2Date": "09 Aug",
  "feat.manage.tl2Label": "Urea applied",
  "feat.manage.tl2Detail": "25 kg / acre",
  "feat.manage.tl3Date": "02 Aug",
  "feat.manage.tl3Label": "Leaf scan",
  "feat.manage.tl3Detail": "Cleared · no disease",
  "feat.manage.schemeCode": "F·12 · Schemes",
  "feat.manage.schemeTitle": "Subsidy & scheme finder",
  "feat.manage.schemeDesc": "Government money you already qualify for — matched, explained, and linked for one-tap application.",
  "feat.manage.checklistMock": "Eligibility checklist with three of four requirements complete",
  "feat.manage.check1": "Land holding verified",
  "feat.manage.check2": "Crop season matches",
  "feat.manage.check3": "CNIC registered",
  "feat.manage.check4": "Bank account linked",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% ready",
  "feat.manage.carbonCode": "F·13 · Sustainability",
  "feat.manage.carbonTitle": "Green practice rewards",
  "feat.manage.carbonDesc": "Log organic and low-tillage practices; satellite green cover verifies them and carbon credit value gets estimated.",
  "feat.manage.carbonMock": "Carbon summary showing tonnes captured and estimated yearly value",
  "feat.manage.co2Label": "CO₂ captured",
  "feat.manage.creditLabel": "Credit value / yr",
  "feat.manage.forumCode": "F·14 · Community",
  "feat.manage.forumTitle": "Farmer forum + experts",
  "feat.manage.forumDesc": "Post a problem, get answers from farmers who faced it — verified agronomists mark the right fix.",
  "feat.manage.threadMock": "Community thread with an expert verified answer",
  "feat.manage.threadQuestion": "Cotton mein safed machhar ka best ilaaj?",
  "feat.manage.threadMeta": "Multan · 12 replies · 34 upvotes",
  "feat.manage.expertBadge": "Expert verified answer",
  "feat.manage.threadAnswer": "Neem oil spray, shaam ko — do baar, 5 din ke gap par.",
  "vp.meta.title": "Vision — Agropioo",
  "vp.meta.description": "Agropioo's vision: intelligent agricultural guidance in every farmer's pocket — starting with Pakistan, built on five beliefs, three horizons, and promises that never bend.",
  "vp.hero.eyebrow": "Our vision",
  "vp.hero.titleLead": "A trusted advisor in",
  "vp.hero.titleAccent": "every farmer's pocket.",
  "vp.hero.sub": "Intelligent guidance should not depend on wealth, literacy, or language. Agropioo exists so that any farmer — on any phone, in any village — farms with the same confidence as an expert standing beside them.",
  "vp.hero.tagStart": "Start where the need is greatest",
  "vp.hero.tagThen": "Then earn the world",
  "vp.hero.ctaLink": "See what we built",
  "vp.beliefs.eyebrow": "What we believe",
  "vp.beliefs.heading": "Five beliefs shape every decision",
  "vp.beliefs.b1Title": "Growth",
  "vp.beliefs.b1Desc": "Living crops, healthy land, prosperous farmers.",
  "vp.beliefs.b2Title": "Intelligence",
  "vp.beliefs.b2Desc": "AI grounded in local weather, history, and crop science.",
  "vp.beliefs.b3Title": "Accessibility",
  "vp.beliefs.b3Desc": "Guidance in the farmer's own language and context.",
  "vp.beliefs.b4Title": "Trust",
  "vp.beliefs.b4Desc": "Practical, timely advice that protects livelihoods.",
  "vp.beliefs.b5Title": "Future",
  "vp.beliefs.b5Desc": "Scalable technology that respects tradition.",
  "vp.horizons.eyebrow": "The road ahead",
  "vp.horizons.heading": "Three horizons, one direction",
  "vp.horizons.h1Tag": "Horizon 01",
  "vp.horizons.h1Phase": "Now",
  "vp.horizons.h1Status": "In the fields",
  "vp.horizons.h1Body": "Pakistan first. The core advisor, digital farm records, weather-aware guidance, and six regional languages — refined through real farmer feedback before anything else.",
  "vp.horizons.h1P1": "Core advisor + records",
  "vp.horizons.h1P2": "Six languages",
  "vp.horizons.h1P3": "Real-farmer refinement",
  "vp.horizons.h2Tag": "Horizon 02",
  "vp.horizons.h2Phase": "Next",
  "vp.horizons.h2Status": "Broadening",
  "vp.horizons.h2Body": "Deeper and wider at home — more crops and regions across Pakistan, richer integrations with agricultural data sources, and analytics that personalise every recommendation further.",
  "vp.horizons.h2P1": "More crops & regions",
  "vp.horizons.h2P2": "Data integrations",
  "vp.horizons.h2P3": "Advanced analytics",
  "vp.horizons.h3Tag": "Horizon 03",
  "vp.horizons.h3Phase": "Later",
  "vp.horizons.h3Status": "Global",
  "vp.horizons.h3Body": "The platform adapts to new countries, climates, crops, languages, and practices — a globally adaptable agricultural intelligence built without starting from scratch.",
  "vp.horizons.h3P1": "New countries",
  "vp.horizons.h3P2": "New languages & climates",
  "vp.horizons.h3P3": "Global platform",
  "vp.outcomes.eyebrow": "What success looks like",
  "vp.outcomes.heading": "Four outcomes we hold ourselves to",
  "vp.outcomes.sub": "The vision is not the app — it is what changes on the farm. Everything ships against these four results.",
  "vp.outcomes.o1Title": "Better decisions",
  "vp.outcomes.o1Desc": "Every choice — water, input, timing — backed by data instead of habit.",
  "vp.outcomes.o2Title": "Higher productivity",
  "vp.outcomes.o2Desc": "Healthy crops, well-timed inputs, and harvests picked at their peak.",
  "vp.outcomes.o3Title": "Fewer avoidable losses",
  "vp.outcomes.o3Desc": "Disease, pests, and weather caught early — before they take the yield.",
  "vp.outcomes.o4Title": "Farms run like businesses",
  "vp.outcomes.o4Desc": "Structured records and season intelligence that banks and buyers respect.",
  "vp.principles.eyebrow": "Non-negotiables",
  "vp.principles.heading": "Promises we build by",
  "vp.principles.sub": "Vision fails in the details. These commitments apply to every feature, every page, every release — starting today.",
  "vp.principles.c1Title": "Farmer benefit leads",
  "vp.principles.c1Desc": "Every feature starts from the field's need — never from the technology.",
  "vp.principles.c2Title": "Language first",
  "vp.principles.c2Desc": "Every screen and every answer arrives in the farmer's own language.",
  "vp.principles.c3Title": "Sunlight readable",
  "vp.principles.c3Desc": "High contrast designed for the midday sun, not just the office.",
  "vp.principles.c4Title": "Plain words",
  "vp.principles.c4Desc": "Simple enough that one neighbour can explain it to another.",
  "vp.principles.c5Title": "Phones before everything",
  "vp.principles.c5Desc": "Mobile-first, big touch targets — farming lives on phones now.",
  "vp.principles.c6Title": "Natural by design",
  "vp.principles.c6Desc": "Motion and layout that feel organic — growth, never machinery.",
  "vp.principles.motto": "Soil and signal — growing together",
} as const;

export type CatalogKey = keyof typeof en;
