/**
 * English source of truth. Every user-visible string on translated surfaces
 * gets a key here; the other seven catalog files must mirror it (enforced by
 * catalog coverage tests and the DB sync script).
 */

export const en = {
  "nav.whyAgropioo": "Why Agropioo",
  "nav.features": "Features",
  "nav.howItWorks": "How it works",
  "nav.vision": "Vision",
  "nav.signIn": "Sign in",
  "nav.getEarlyAccess": "Get early access",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "common.languageSwitcherLabel": "Change language",
  "notFound.title": "Page not found",
  "notFound.body": "The page you are looking for does not exist or may have moved.",
  "notFound.backHome": "Back to Agropioo home",
  "common.builtForPakistan": "Built for Pakistan",
  "common.productOfAplinode": "A product of Aplinode",
  "home.hero.eyebrow": "AI-powered farm intelligence platform",
  "home.hero.titleLead": "Intelligence For",
  "home.hero.titleAccent": "Smarter Farming",
  "home.hero.subtitle": "One platform that unites an AI advisor, satellite monitoring, market prices, and your farm's records — turning data into clear decisions, in the language you speak.",
  "home.hero.ctaSecondary": "See how it works",
  "home.hero.imageAlt": "Farmer using Agropioo on a tablet in the field",
  "home.hero.readingCrop": "Crop health",
  "home.hero.readingWeather": "Weather",
  "home.hero.readingSoil": "Soil moisture",
  "home.hero.noteExcellent": "Excellent",
  "home.hero.noteClearSky": "Clear sky",
  "home.hero.noteOptimal": "Optimal",
  "home.ticker.ariaLabel": "Agropioo platform capabilities",
  "home.ticker.cropDoctor": "AI crop doctor",
  "home.ticker.satelliteNdvi": "Satellite NDVI monitoring",
  "home.ticker.mandiPrices": "Mandi price intelligence",
  "home.ticker.weatherAdvisories": "Weather-aware advisories",
  "home.ticker.farmRecords": "Digital farm records",
  "home.ticker.advisoryLanguages": "Advisory in 7 languages",
  "home.ticker.pestAlerts": "Pest outbreak alerts",
  "home.ticker.offlineSms": "Offline-first + SMS",
  "home.problem.eyebrow": "The problem",
  "home.problem.title": "Farming decisions shouldn't be a guessing game",
  "home.problem.subtitle": "Across Pakistan, farmers make high-stakes choices with tradition, local advice, and scattered information. The cost is paid at harvest.",
  "home.problem.item1Title": "Uncertain timing",
  "home.problem.item1Body": "Irrigation, fertiliser, pesticide, planting, harvest — critical moments are still guessed, costing yield and wasted inputs.",
  "home.problem.item2Title": "Lost farm history",
  "home.problem.item2Body": "Seasons of knowledge live in memory or scattered notebooks. What worked last year is impossible to learn from this year.",
  "home.problem.item3Title": "Fragmented advice",
  "home.problem.item3Body": "Neighbours, vendors, and videos all offer answers — few match the farmer's crop, soil, weather, or location.",
  "home.problem.kicker": "The cost of guessing is paid at harvest",
  "home.solution.eyebrow": "The solution",
  "home.solution.titleA": "Your farm's intelligence,",
  "home.solution.titleB": "in one place",
  "home.solution.subtitle": "One intelligence platform for the whole season — advisory, records, weather, and markets working from your land's data, not generic advice.",
  "home.solution.card1Title": "What to do",
  "home.solution.card1Body": "Personalised recommendations for irrigation, fertiliser, pest control, and harvest timing — based on your crop and conditions.",
  "home.solution.card1Answer": "Clear, specific advice for this field, this week.",
  "home.solution.card2Title": "When to do it",
  "home.solution.card2Body": "Weather-aware guidance tells you the right moment to act, so bad timing and sudden conditions stop costing you yield.",
  "home.solution.card2Answer": "Timing tuned to real weather and growth stage.",
  "home.solution.card3Title": "What has been done",
  "home.solution.card3Body": "Every activity — irrigation, inputs, disease, expenses, harvest — kept as a structured record that makes each season smarter.",
  "home.solution.card3Answer": "A complete history, always within reach.",
} as const;

export type CatalogKey = keyof typeof en;
