import type { CatalogKey } from "./en.ts";

/** ہندکو — AI-drafted, founder-reviewed copy (plan D4). */
export const hno: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کیویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ موجود نئیں",
  "notFound.body": "تساں جیہڑا صفہ لبھیا اودو موجود نئیں یا منتقل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے گھر واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت نال فارم دی ذہانت دا پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کاشتکاری لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک پلیٹ فارم جیڑھا اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تساڈے فارم دے ریکارڈ اک تھاں رلاوندا اے — ڈیٹا سوچ فیصلہ بناندا اے، تساڈی اپنی بولی چ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کیویں کم کردا اے",
  "home.hero.imageAlt": "کسان کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "ودھیا",
  "home.hero.noteClearSky": "صاف اسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان وچ کسان ریایت، مقامی صلاحاں تے کھنڈریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان کٹائی تے چکندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، کٹائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹدی تے خرچ ضائع تھیندی اے۔",
  "home.problem.item2Title": "گواچیا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھنڈریاں کاپیاں وچ رہندا اے۔ پچھلے سال جیہڑا کم آیا، اوں توں ایں سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھنڈریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کسان دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت کٹائی تے چکندی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تساڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک ذہانت دا پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈی تساڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیمیا مار تے کٹائی دے ویلیے لئی ذاتی صلاحاں — تساڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تساڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا گیا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، کٹائی — ترتیب والے ریکارڈ وچ محفوظ جیہڑا ہر سیزن نوں ودھ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ موجود۔",
};
