import type { CatalogKey } from "./en.ts";

/** ہندکو — AI-drafted, founder-reviewed copy (plan D4). */
export const hno: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کیویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ موجود نئیں",
  "notFound.body": "تساں جیہڑا صفہ لبھیا اودو موجود نئیں یا منتقل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے گھر واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت نال فارم دی ذہانت دا پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کاشتکاری لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک پلیٹ فارم جیڑھا اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تساڈے فارم دے ریکارڈ اک تھاں رلاوندا اے — ڈیٹا سوچ فیصلہ بناندا اے، تساڈی اپنی بولی چ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کیویں کم کردا اے",
  "home.hero.imageAlt": "کسان کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "ودھیا",
  "home.hero.noteClearSky": "صاف اسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان وچ کسان ریایت، مقامی صلاحاں تے کھنڈریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان کٹائی تے چکندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، کٹائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹدی تے خرچ ضائع تھیندی اے۔",
  "home.problem.item2Title": "گواچیا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھنڈریاں کاپیاں وچ رہندا اے۔ پچھلے سال جیہڑا کم آیا، اوں توں ایں سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھنڈریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کسان دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت کٹائی تے چکندی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تساڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک ذہانت دا پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈی تساڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیمیا مار تے کٹائی دے ویلیے لئی ذاتی صلاحاں — تساڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تساڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا گیا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، کٹائی — ترتیب والے ریکارڈ وچ محفوظ جیہڑا ہر سیزن نوں ودھ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ موجود۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "کئی انجن،",
  "home.features.titleB": "اک ذہین پلیٹ فارم",
  "home.features.subtitle": "تساڈے اپنے بولاں توں پہلے سوال توں لے کے سارے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی نوں تقویت دیوے اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی کاشتکاری مشیر",
  "home.features.advisorTopics": "پانی · کھاد · کیمیا تے بیماری · کٹائی",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "پیلیاں پتریاں والی گندم بارے اگروپیو مشیر نال نمونہ گل بات",
  "home.features.advisorUserMsg": "میری گندم دے پتر پیالے ہو رے نیں — کی کراں؟",
  "home.features.advisorReplyTitle": "پیالے پتر — دو عام وجوہات:",
  "home.features.advisorReplyCause1": "پانی دی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے وقتاں وچ، سویرے 9 وجے توں پہلاں پانی دیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سبھ توں پرانے پتر پہلاں ویکھو؛ لوڑ ہووے تاں یوریا پاؤ۔",
  "home.features.advisorReplyFooter": "جے پتریاں تھلے پیلیاں لیکاں دسن، فوٹو بھیجو — main بیماری دی جانچ کر دیسانگی۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھو یا بولو…",
  "home.features.advisorFooter": "اپنی فصل بارے کجھ وی پچھو — روزمرہ سوالاں خوش آمدید نیں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر کم ترتیب نال لکھیا — تے جے صلاح تساڈی اپنی زمین توں سکھے۔",
  "home.features.record1Activity": "پانی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتریاں دا سکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "گندم · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · بولی",
  "home.features.languageTitle": "تساڈی بولی، تساڈے بول",
  "home.features.languageDesc": "جدوں سوچدے او ادوں بول کے یا لکھو — تکنیکی انگریزی دی لوڑ نئیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں جانو رہنمائی",
  "home.features.weatherDesc": "صلاح تساڈے کول پجدیاں پہلاں اصلی حالات ویکھدی اے — mینہ توں پہلاں سپرے کیتا تے سارا کھاد وہ جانا اے۔",
  "home.features.weatherMockAria": "پنج دناں دی پیشنگوئی جیندے وچ جمعرات نوں سپرے نہ کرن دی صلاح نمایاں اے",
  "home.features.dayMon": "سوموار",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "سپرے روکو",
  "home.features.weatherLegend": "مقامی موسم پیشنگوئی توں صلاح والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودھدا جا ریا اے — ساریاں صلاحیتاں ویکھو",
  "home.journey.eyebrow": "ایہ کیویں کم کردا اے",
  "home.journey.title": "اک سوال سیزن شروع کردا اے",
  "home.journey.subtitle": "تساڈے پہلے سوال توں مکمل، ذہین فارم تریخ تک سادہ راہ۔",
  "home.journey.step1Title": "اپنا فارم پایو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بناؤن لئی تھاں، فصل تے بنیادی جانکاری بھرو۔",
  "home.journey.step2Title": "اے آئی توں پچھو",
  "home.journey.step2Body": "اپنا سوال اس بولی وچ لکھو یا بولو جس نوں تساں سبھ توں ودھ سمجھدے او۔",
  "home.journey.step3Title": "رہنمائی پاؤ",
  "home.journey.step3Body": "اپنی فصل، موسم، تھاں تے فارم تریخ تے بیسیاں صلاحاں پاؤ۔",
  "home.journey.step4Title": "کم لکھو",
  "home.journey.step4Body": "تھوڑھے ٹیپاں وچ پانی، کھاد، دوائی جاں بیماری لکھو۔",
  "home.journey.step5Title": "تریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ آن والیاں صلاحاں نوں ودھ سمجھدار تے موزاں بناندا اے۔",
  "home.journey.step6Title": "نگراں کردے رہو",
  "home.journey.step6Body": "سارے سیزن دوران ریکارڈ ویکھو تے ترقی تے نگاہ رکھو۔",
  "home.matrix.eyebrow": "ساریاں صلاحیتاں دا مجموعہ",
  "home.matrix.title": "لوڑ توں حیران کرن والے تک",
  "home.matrix.subtitle": "ہر خاصیت فصل بچاندی اے، خرچ گھٹاندی اے جاں کمائی ودھاندی اے۔ اسنوں جنتری وانگر پڑھو — ہر درجہ پچھلے تے کھڑا اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتاں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی پدھر",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری پچھان",
  "home.matrix.t1f1Body": "متاثرہ پتر دی فوٹو چاڑھو تے فوری جانچ، شدت تے علاج دیاں صلاحاں پاؤ۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت نگرانی",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد نشان لگاؤ تے مفت سینٹینل-2 تصویراں توں این ڈی وی آئی بیسڈ فصل صحت ویکھو۔",
  "home.matrix.t1f3Title": "ہوشیار موسمی صلاح",
  "home.matrix.t1f3Body": "مقامی موسم پیشنگوئی تساڈی فصل تے ودھدے پڑاءُ نال مل کے روزانہ کماں دی صلاح بن جاندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیشنگوئی",
  "home.matrix.t1f4Body": "نزدیکی منڈی دیاں قیمتیں اے آئی رجحاناں نال ویکھو، تے ٹھیک ویلیے تے ویچو۔",
  "home.matrix.tier2Name": "وکھریاں خاصیتاں",
  "home.matrix.tier2Badge": "نمانا",
  "home.matrix.t2f1Title": "علاقائی بولیاں دی وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولو جاں لکھو — جواب اس بولی وچ سنو جس تساں بہتر سمجھدے او۔",
  "home.matrix.t2f2Title": "سرکاری سکیم میچر",
  "home.matrix.t2f2Body": "اپنیاں جانکاریاں بھرو تے ہر اہل سکیم لبھو — دستاویزاں تے اپلائی لنکاں سمیت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن تساڈی مٹی، موسم، منڈی دی منگ تے بجٹ مطابق سبھ توں ودھ منافع والی فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے اصلی خرچ، پیداوار، کمائی تے نفع — بریک ایون تے آر او آئی نال۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوال پاؤ، فوٹو شیئر کرو، ساتھی کساناں تے تصدیق شدہ ماہراں پاسوں جواب لو۔",
  "home.matrix.tier3Name": "حیران کن",
  "home.matrix.tier3Badge": "سبھ توں اگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی نگرانی",
  "home.matrix.t3f1Body": "سلائیڈر نال ویلے نال سیٹلائٹ تصویراں تولو — ودھاءُ، نقصان جاں قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیشنگوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے پڑاءُ تے تریخ دے بنیاد تے ممکنہ حملے توں پہلاں سوچنا۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر تے کال کرو، سوال بولو، اپنی بولی وچ صلاح سنو — اسمارٹ فون دی لوڑ نئیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ اندازہ",
  "home.matrix.t3f4Body": "ٹکاؤ طریقے لکھو تے رضاکارانہ مارکیٹاں توں کاربن کریڈٹ دا اندازہ لاو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت وچ آف لائن کم کرے، کنکشن تے سنک ہووے، کمزور نیٹ تے ایس ایم ایس خبر دیوے۔",
  "home.vision.eyebrow": "وژن",
  "home.vision.titleA": "پاکستان لئی بنایا گیا۔",
  "home.vision.titleB": "دنیا لئی تیار۔",
  "home.vision.pkTitle": "پہلوں پاکستان والا ول",
  "home.vision.pkBody": "پہلا ورژن پاکستان دے کھیتاں لئی بنایا گیا اے: مقامی فصلاں، علاقائی بولیاں، اصلی کاشتکاری دے طریقیاں تے اصلی کھیتاں دیاں حالتاں۔",
  "home.vision.pkPoint1": "مقامی فصل تے موسم دی سمجھ",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "اصلی کساناں دے فیڈبیک نال بہتر بنایا گیا",
  "home.vision.worldTitle": "دنیا بھر پھیلن دا وژن",
  "home.vision.worldBody": "موزاں تھیوݨ لئی بنایا گیا۔جدوں پلیٹ فارم ودھدا اے تے نویں دیساں، بولیاں، فصلاں تے موسماں تک جاندا اے—شروعوں نویں سرے نہ بݨاوݨ۔",
  "home.vision.worldPoint1": "دیس مطابق کھیتی بار دی سمجھ",
  "home.vision.worldPoint2": "ہور بولیاں تے مقامی فصلاں",
  "home.vision.worldPoint3": "ڈونگھی ڈیٹا جوڑ تے تجزیے",
  "home.users.title1": "انفرادی کسان",
  "home.users.desc1": "نکے تے وچولے فارم جنہاں نوں عملی صلاح تے ہر کم دا ترتیب والا ریکارڈ چاہیدا اے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہاں نوں ترتیب والی جانکاری، فیصلے دی مدد تے ٹیم دے ریکارڈ چاہیدن۔",
  "home.users.title3": "ایکو سسٹم ساتھی",
  "home.users.desc3": "ان پٹ سپلائر، کوآپریٹو، بیمہ تے ایکسٹینشن سروساں جیہڑیاں ویلے نال پلیٹ فارم نال جڑن گیاں۔",
  "home.users.tagline": "پہلوں کساناں لئی بنایا گیا — ایکو سسٹم نال ودھدا ہویا",
  "home.cta.eyebrow": "شروعاتی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم تے لیاؤ",
  "home.cta.subtitle": "اگروپیو نال بہتر فیصلے کرن والے کساناں وچ رل تھیوو — پاکستان توں شروع، دنیا بھر وچ ودھاءُ۔",
  "home.cta.success": "تسیں لسٹ وچ او۔جدوں تہاڈا علاقہ کھلسیگا اساں رابطہ کرساں۔",
  "home.cta.emailLabel": "ای میل پتہ",
  "home.cta.fineprint": "کوئی سپام نہیں۔جس وی ویلے ان سبسکرائب کرو۔",
  "home.footer.tagline": "اے آئی والا فارم انٹیلیجنس پلیٹ فارم۔صلاح، سیٹلائٹ نگرانی، منڈی دیاں قیمتیں تے ریکارڈ—مٹی تے سگنل، نال نال۔",
  "home.footer.pagesHeading": "ورقے",
  "home.footer.pagesNavLabel": "فوٹر ورقے",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس دیاں شرطاں",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کرو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔سارے حق محفوظ نیں۔",
  "home.footer.motto": "پاکستان لئی بنیا · دنیا لئی تیار",
  "hiw.meta.title": "ایہ کویں کم کردا اے — اگروپیو",
  "hiw.meta.description":
    "اک منٹ دے فارم پروفائل توں لگاتار بہتر ہووݨ والے موسمی چکر تائیں: ݙیکھو اگروپیو سوال، سرگرمیاں تے ریکارڈ کویں ذاتی کھیتی رہنمائی وچ بدلدا اے۔",
  "hiw.hero.eyebrow": "ایہ کویں کم کردا اے",
  "hiw.hero.titleA": "چھ نکے مرحلے۔",
  "hiw.hero.titleLead": "اک",
  "hiw.hero.titleAccent": "ودھیرے سمجھدار سیزن۔",
  "hiw.hero.subtitle":
    "اگروپیو اوس طرح کم کردا اے جویں کھیتی پہلوں توں چلدی اے — تسیں بیج بچاؤ، پچھو، کم کرو تے ریکارڈ کرو۔ فرق صرف ایہ اے کہ ہُن ہر مرحلہ اگلا سکھاندا اے۔",
  "hiw.hero.browseFeatures": "خصوصیتاں ݙیکھو",
  "hiw.route.navLabel": "اگروپیو دے موسمی چکر دے چھ مرحلے",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بناؤ",
  "hiw.route.stop2": "پچھو",
  "hiw.route.stop3": "رہنمائی",
  "hiw.route.stop4": "کم کرو",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "اک واری سیٹ اپ کرو",
  "hiw.setup.title": "تواڈا فارم جیندا پروفائل بݨ جاندا اے",
  "hiw.setup.body":
    "چار خانے، اک منٹ توں گھٹ — ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ۔ ایہو سارا فارم اے۔ ایندے بعد ہر جواب ڄاندا اے جو ایہ کتھاں تے کہڑیاں حالتاں وچ اگھدا پئے۔",
  "hiw.setup.point1": "فصل بدلو یا کسے وی ویلے فارم شامل کرو",
  "hiw.setup.point2": "ٹھیکیداراں تے ڈیلراں لئی کئی فارم",
  "hiw.setup.point3": "کجھ تکنیکی نہیں پچھیا جاندا — مٹی دی رپورٹ دی لوڑ نہیں",
  "hiw.setup.mockHeading": "نواں فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بناؤ",
  "hiw.setup.mockFootnote": "اک منٹ توں گھٹ لگدا اے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جیندے وچ ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ بھریا ہویا اے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربیع",
  "hiw.setup.rowSowing": "بیج دی تاریخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "۱۲ ایکڑ",
  "hiw.ask.eyebrow": "جو منگے پچھو",
  "hiw.ask.titleA": "اک سوال ونجے۔",
  "hiw.ask.titleB": "تواڈا سارا فارم جواب ڈیندا اے۔",
  "hiw.ask.body":
    "اکو جیہا سوال وکھرے فارماں تے وکھرا مطلب رکھدا اے۔ ایں کیتے جواب ڈیوݨ توں پہلاں اگروپیو سوال کوں تواڈے فارم بارے ڄاتیا ہویا ہر شے نال ملا تے ݙیدھا اے۔",
  "hiw.ask.pipelineLabel":
    "کسان دے سوال کوں فصل، ضلع، موسم تے تاریخ دے تناظر نال ملا تے ذاتی جواب بنایا جاندا اے",
  "hiw.ask.question": "ہُݨ پانی ڈیونا چاہیدا اے یا تھولا انتظار؟",
  "hiw.ask.checkedAgainst": "اناں شیواں نال ملا تے",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · گٹھیاں پے گئیاں",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "۲۶° • خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخ",
  "hiw.ask.chipValHistory": "یوریا ۹ ڈینہہ پہلاں",
  "hiw.ask.answer":
    "ڈو ڈینہہ رکو — مینہہ دا امکان اے، تے یوریا توں بعد زمین ہلی اے۔ جمعے تائیں ݙیکھ گھننا کافی اے۔",
  "hiw.ask.answerMeta": "ذاتی جواب · گندم، یوریا توں ۹ ڈینہہ بعد",
  "hiw.ask.footnote": "لکھو، بولو یا کال کرو — جواب ہر صورت تواڈے فارم دا اپنا ہوندے",
  "hiw.engine.eyebrow": "جواب دے پچھوں",
  "hiw.engine.title": "چار جانچاں اوس توں پہلاں جدوں تسیں اک لائین ݙیکھو",
  "hiw.engine.body":
    "رہنمائی کوئی سرچ نتیجہ نہیں۔ ایہ چار دروازےآں وچوں لنگھدی اے تاں جو تسیڈے تک جو پجدے او اوہو کھیت لئی، اوہو ہفتے لئی محفوظ ہووے۔",
  "hiw.engine.check1Title": "جانکاری اکٹھی کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم تے فصل دا پڑاؤ بھیجن دے لمحے نال نال اکٹھے تھیندے نیں۔",
  "hiw.engine.check2Title": "ملان دی جانچ",
  "hiw.engine.check2Desc":
    "مشورہ موسم دی پیش گوئی نال پرکھیا جاندا اے — مینہہ وچ بیکار ہووݨ والا سپرے انجن وچوں نکلدا ای نہیں۔",
  "hiw.engine.check3Title": "ذاتی بناؤنا",
  "hiw.engine.check3Desc":
    "تواڈے کھیت دی تاریخ جواب بدل ڈیندی اے — اوہو فصل، وکھری مٹی، وکھرا مشورہ۔",
  "hiw.engine.check4Title": "پچاؤنا",
  "hiw.engine.check4Desc":
    "ول تواڈی زبان وچ صاف قدم بݨ تے آندا اے — سکرین تے، آواز وچ یا فون کال تے۔",
  "hiw.engine.safetyStrong": "جے کجھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تاں اگروپیو اڈیک دا آکھدا اے — دیر نال ملݨ والا جواب بیکار تھیا سپرے یا برباد فصل توں بہتر اے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کرو",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی ڈیونا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل لہاوݨ",
  "hiw.record.row1Time": "اج • سویرے 6:40",
  "hiw.record.row1Label": "پانی ڈیونا درج تھیا",
  "hiw.record.row1Detail": "نہر دا موڑ • ۴۰ منٹ • پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج تھئی",
  "hiw.record.row2Detail": "DAP ۲۰ کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف ڈو ٹیپ — آف لائن وی چلدا اے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جیندے وچ فوری ایکشن چپس تے حالی درج تھئے اندراج نیں",
  "hiw.record.eyebrow": "جیویں جیویں کم کرو، ریکارڈ کردے جاؤ",
  "hiw.record.titleA": "ہُݨ ڈو ٹیپ،",
  "hiw.record.titleB": "سارے سیزن بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت لئی بنائی گئی اے — وڈے بٹن، گھٹ خانے، ٹائپنگ دی لوڑ نہیں۔ ہر اندراج فارم دی یادداشت دا انگ بݨدا اے، ایں کیتے مشورہ وی فصل نال نال تکھا تھیندا ویندے۔",
  "hiw.record.point1": "پانی، کھاداں، بیماری، خرچ، فصل — سب اک ٹائم لائین تے",
  "hiw.record.point2": "پوری طرح آف لائن چلدا اے؛ سگنل آنے تے خودکار سنک تھی جاندا اے",
  "hiw.record.point3": "بینک، خریدار یا بیمے لئی سیزن خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "ایہ فصل لہاوݨ تے ختم نیں تھیندا۔",
  "hiw.loop.titleB": "اوتھوں شروع تھیندا اے۔",
  "hiw.loop.body":
    "پچھو، کم کرو، ریکارڈ کرو — ول ول۔ چکر دی ہر واری اگروپیو تواڈی زمین بارے نواں کجھ سکھاندا اے، تاں اگلا سیزن پچھلے توں اگے شروع تھیوے۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماؤندا اے",
  "hiw.loop.benefit1Desc":
    "پچھلے سیزن دیاں بیماریاں، خوراکاں تے تریخاں ایں سیزن دا پہلا جواب بناندیاں نیں۔",
  "hiw.loop.benefit2Title": "کجھ دہرانا نہیں پیندا",
  "hiw.loop.benefit2Desc":
    "مشاورت ڄاندی اے جو کیہ پہلوں سپرے یا کھاد تھی چکیا اے — دوہری خوراک دا خطرہ نہیں۔",
  "hiw.loop.benefit3Title": "ہر سیزن دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرضے، خریدار، بیمہ یا اگلی فصل دے فیصلے لئی تیار راہندا اے۔",
    "hiw.loop.stepLearn": "سکھو",
  "hiw.loop.stepImprove": "بہتر کرو",
  "hiw.loop.diagramLabel": "گول چکر خاکہ: پچھو، کم کرو، ریکارڈ کرو، سکھو، بہتر کرو",
  "hiw.loop.centerSeason": "سیزن",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر سیزن، پچھلے توں بہتر",
  "feat.meta.title": "خصوصیات — اگروپیو",
  "feat.meta.description": "اگروپیو دی ہر خصوصیت ویکھو: اے آئی فصل ڈاکٹر، سیٹلائٹ NDVI نگرانی، منڈی قیمت پیش گوئی، مقامی بولیاں چ آوازی صلاح، آف لائن رسائی تے ایس ایم ایس الرٹس، تے ہور بوہت کجھ۔",
  "feat.hero.eyebrow": "خصوصیات",
  "feat.hero.titleLead": "تساں دے موسم دی ہر",
  "feat.hero.titleAccent": "لوڑ پوری",
  "feat.hero.subtitle": "چوڈاں خصوصیات رل تے کم کردیاں نیں — پتے سکین کردیاں نیں، خلا توں کھیت ویکھدیاں نیں، منڈی پڑھدیاں نیں تے تساں دی زبان بولدیاں نیں۔ ویکھو ہر ہک تساں دے فارم لئی کیا کردی اے۔",
  "feat.hero.ctaPrimary": "شروعاتی رسائی حاصل کرو",
  "feat.hero.ctaSecondary": "ایہ کیویں چلدا اے ویکھو",
  "feat.hero.builtFor": "پاکستان لئی بنایا گیا",
  "feat.hero.productOf": "Aplinode دی پیداوار",
  "feat.hero.tile1Label": "پتہ سکین",
  "feat.hero.tile1Value": "94% صحتمند",
  "feat.hero.tile2Label": "منڈی گندم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کھیت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کیڑے دا خطرہ",
  "feat.hero.tile4Value": "گھٹ · 7 دن",
  "feat.hero.voiceReady": "آوازی صلاح تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "ایس ایم ایس الرٹ · آف لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — سپرے روکو",
  "feat.intel.eyebrow": "فصل دی سمجھ",
  "feat.intel.heading": "مسلے نقصان توں پہلاں ویکھو",
  "feat.intel.sub": "بیماری، کیڑے، موسم تے فصل دا انتخاب — چار فیصلے جو فصل طے کردے نیں، ہر ہک اپنے انجن نال۔",
  "feat.intel.included": "شامل نیں",
  "feat.intel.doctorCode": "F·01 · وژن",
  "feat.intel.doctorTitle": "اے آئی فصل ڈاکٹر",
  "feat.intel.doctorDesc": "متاثرہ پتے دی تصویر کڈھو تے سیکنڈاں چ بیماری دا ناں، شدت تے علاج دا منصوبہ لبھو۔",
  "feat.intel.doctorMock": "پتہ سکین نتیجہ جس چ پیلا زنگ زیادہ یقین نال تشخیص کیتا",
  "feat.intel.diseaseName": "پیلا زنگ",
  "feat.intel.matchScore": "94% میل",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درمیانہ",
  "feat.intel.pestCode": "F·02 · پیش گوئی",
  "feat.intel.pestTitle": "کیڑیاں دے حملے دی الرٹ",
  "feat.intel.pestDesc": "موسم تے فصل دا پڑاؤ خطرے دے ماڈل نوں کارآمد کردا اے جیہڑا حملے توں دن پہلاں خبردار کر دیندا اے۔",
  "feat.intel.pestMock": "سات دناں دے کیڑے خطرے دے چارٹ جیہڑا چھیویں دن مہاندرا تھی جاندا اے",
  "feat.intel.pestAlert": "ہفتہ · ٹڈی دل دا خطرہ 74% — نویں گندم بچاؤ",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم مطابق صلاحاں",
  "feat.intel.weatherDesc": "مقامی پیش گوئیاں تساں دی فصل تے نشونما دے پڑاؤ نال ملدیاں نیں — صلاح صاف رہنمائی بن کے آندی اے، خام ڈیٹا کوئی نیں۔",
  "feat.intel.weatherMock": "بہترین موسمی صلاح جیہڑی بارش توں پہلاں آبپاشی چ تاخیر دا آکھدی اے",
  "feat.intel.delayIrrigation": "اج پانی دین چ تاخیر کرو",
  "feat.intel.rainNote": "شام 3 وجے بارش دا امکان — پہلاں اسمان کھیت بھنجاوے۔",
  "feat.intel.waterSaved": "پانی دی بچت",
  "feat.intel.cropCode": "F·04 · منصوبہ بندی",
  "feat.intel.cropTitle": "فصل دی سفارش",
  "feat.intel.cropDesc": "مٹی، موسم، منگ تے تساں دا بجٹ رل جانچے جاندے نیں — اوہ بوؤ جیہڑا اس موسم منافع دیوے۔",
  "feat.intel.cropMock": "درجہ بند فصل سفارشات جیہناں چ گندم اتے",
  "feat.intel.crop1": "گندم",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کھیت تے منڈی دی سمجھ",
  "feat.field.headingA": "تساں دی زمین خلا توں نپی جاندی اے۔",
  "feat.field.headingB": "تساں دی فصل ڈیٹا نال پرکی جاندی اے۔",
  "feat.field.sub": "ہر ایکڑ تے سیٹلائٹ دا نظارہ تے قریبی ہر منڈی دا جائزہ — تاکہ ودھ تے ویچن دوویں صحیح وقت ہون۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کھیت نگرانی",
  "feat.field.ndviDesc": "اپنی حد ہک واری نشان زد کرو؛ ہر روشن سیٹلائٹ پاس تے صحت دے زون اپ ڈیٹ ہوندے نیں — کمزور حصے اکھ توں پہلاں سامنے آؤندے نیں۔",
  "feat.field.ndviMock": "کھیت دی صحت گرڈ جس چ گہرا سبز مضبوط فصل واڈ ڈکھاندا اے",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈی",
  "feat.field.priceTitle": "منڈی قیمت پیش گوئی",
  "feat.field.priceDesc": "قریبی منڈیاں دے موجودہ ریٹ تے رجحان پیش گوئی — تڈاں ویچو جدوں گراف آکھے، خریدار جدوں آکھے او کوئی نیں۔",
  "feat.field.priceMock": "گندم قیمت رجحان اٹھ ہفتیاں چ مہاندرے ول، روکے رہن دی سفارش نال",
  "feat.field.wheatTrend": "گندم · 8 ہفتے",
  "feat.field.holdStock": "↑ 12% — مال رکھو",
  "feat.field.financeCode": "F·07 · مالیات",
  "feat.field.financeTitle": "نفع نقصان جوچ",
  "feat.field.financeDesc": "ہر روپیا آن جان دا، پورا موسم — منڈی یا بینک جان توں پہلاں بریک ایون تے آر او آئی تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ جس چ ان پٹ، مزدوری، آبپاشی تے آمدنی",
  "feat.field.rowInputs": "ان پٹ",
  "feat.field.rowLabour": "مزدوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (اندازہ)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سب لئی رسائی",
  "feat.voice.headingA": "اسمارٹ فون کوئی نیں؟",
  "feat.voice.headingB": "انگریزی کوئی؟ پھر وی شامل۔",
  "feat.voice.sub": "ودھیا توں بہترین صلاح بے کار اے جے اوہ کسان تک پہنچے ہی کوئی۔ ہر خصوصیت فون کال جواب دیندی اے، آواز سُن دی اے تے سگنل ختم علاقے چ وی چلدی اے۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "اپنا سوال بولو",
  "feat.voice.speakMock": "رومن ہندکو چ صلاح نال آوازی گل بات",
  "feat.voice.chatUser": "میڈی فصل دے پتیاں تے داغ نیں",
  "feat.voice.chatAdvisor": "داغاں دی تصویر بھیجو — میں ہُنیں تشخیص کریندا واں۔",
  "feat.voice.inputPlaceholder": "بول تے پچھو…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کرو",
  "feat.voice.callMock": "اگروپیو آوازی مددگار نال ٹول فری کال دی نقل",
  "feat.voice.greetingLine": "اگروپیو چ تساں نوں جی آیاں",
  "feat.voice.heardLine": "آواز سمجھ لئی — جواب تیار اے",
  "feat.voice.callEnded": "کال ختم · خلاصہ محفوظ",
  "feat.voice.anyPhone": "ہر فون تے · انٹرنیٹ دی لوڑ کوئی نیں",
  "feat.voice.offlineCode": "F·10 · آف لائن + ایس ایم ایس",
  "feat.voice.offlineTitle": "سگنل ختم علاقے وی نہیں روکدے",
  "feat.voice.offlineDesc": "صلاحاں، ریکارڈ تے کیلکولیٹر بغیر سگنل کم کردے رہندے نیں؛ نیٹ ورک واپسی تے سب سنک ہو جاندے نیں تے اہم الرٹس ایس ایم ایس نال آؤندے نیں۔",
  "feat.voice.networkStatus": "نیٹ حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 ریکارڈ قطار چ",
  "feat.voice.smsStamp": "ایس ایم ایس · 07:42",
  "feat.voice.smsMsg": "موسمی الرٹ: بارش شام 3 وجے — سپرے دا ویلہ بدل لو۔",
  "feat.manage.eyebrow": "سنبھال تے ودھاؤ",
  "feat.manage.headingA": "صلاح شروعات اے۔",
  "feat.manage.headingB": "باقی سب ریکارڈ تے چلدا اے۔",
  "feat.manage.sub": "تریخ، سبسڈی، پائیداری تے کساناں دی کمیونٹی — خاموش خصوصیات جیہڑیاں ہر موسم جمع ہوندیاں نیں۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈ",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی توں فصل کپن تک، سب ہک ٹائم لائن تے جسنوں صلاح جواب توں پہلاں پڑھدی اے۔",
  "feat.manage.timelineMock": "اگست دی فارم سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "نہر دی واری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریا پایا گیا",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "پتہ سکین",
  "feat.manage.tl3Detail": "صحتمند · کوئی بیماری کوئی نیں",
  "feat.manage.schemeCode": "F·12 · اسکیمز",
  "feat.manage.schemeTitle": "سبسڈی تے اسکیم لبھو",
  "feat.manage.schemeDesc": "سرکاری رقم جس دے تساں پہلاں توں اہل ہو — لبھی، سمجھائی تے ہک ٹیپ درخواست لئی جوڑی گئی۔",
  "feat.manage.checklistMock": "اہلیت چیک لسٹ جس چ چار وچوں تن شرطاں مکمل",
  "feat.manage.check1": "زمین دی تصدیق ہو گئی",
  "feat.manage.check2": "فصل دا موسم مطابقت رکھدا اے",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بینک اکاؤنٹ جڑیا",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پائیداری",
  "feat.manage.carbonTitle": "ساویں طریقےآں دے انعام",
  "feat.manage.carbonDesc": "نامیاتی تے گھٹ ہل دے طریقے درج کرو؛ سیٹلائٹ ساوا احاطہ تصدیق کردا اے تے کاربن کریڈٹ دی قدر دا اندازہ لاندا اے۔",
  "feat.manage.carbonMock": "کاربن خلاصہ جس چ قبضے والیاں ٹن تے سالانا اندازی قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ قدر / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کسان فورم + ماہر",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کرو، ان کساناں توں جواب گھنو جنہاں پن آپ سامنا کیتا — تصدیق شدہ ماہر صحیح حل نشان زد کردے نیں۔",
  "feat.manage.threadMock": "کمیونٹی بحث جس چ ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadQuestion": "کپاس چ سفید مکھی دا بہترین علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "نیم دے تیل دی سپرے، شام نوں — دو واری، 5 دناں دے وقفے تے۔",
  "vp.meta.title": "وژن — اگروپیو",
  "vp.meta.description": "اگروپیو دا وژن: ہر کسان دی جیب وچ ذہین زرعی رہنمائی — پاکستان توں شروعات، پنج یقیناں، تن افق تے او وعدے جنہاں نال کوئی سمجھوتہ نہیں۔",
  "vp.hero.eyebrow": "ساڈا وژن",
  "vp.hero.titleLead": "اک بھروسہ مند مشیر",
  "vp.hero.titleAccent": "ہر کسان دی جیب وچ۔",
  "vp.hero.sub": "ذہین رہنمائی دا تعلق دولت، پڑھائی یا بولی نال نہیں ہونا چاہیدا۔ اگروپیو اس لئی اے تاکہ ہر کسان — کسے وی فون تے، کسے وی پنڈ وچ — اودے ہی بھروسے نال کھیتی کرے جیویں کوئی ماہر نال کھڑا ہووے۔",
  "vp.hero.tagStart": "پہلاں اوتھے جتھے لوڑ سبھ توں ودھ",
  "vp.hero.tagThen": "پھر ساری دنیا",
  "vp.hero.ctaLink": "ویکھو اساں کی بنایا",
  "vp.beliefs.eyebrow": "ساڈے یقین",
  "vp.beliefs.heading": "پنج یقین ہر فیصلے دی شکل دیندے نیں",
  "vp.beliefs.b1Title": "ودھ",
  "vp.beliefs.b1Desc": "جیوندیاں فصلاں، صحتمند زمین، خوشحال کسان۔",
  "vp.beliefs.b2Title": "سمجھ",
  "vp.beliefs.b2Desc": "مقامی موسم، اتہاس تے فصل سائنس تے بیسڈ اے آئی۔",
  "vp.beliefs.b3Title": "رسائی",
  "vp.beliefs.b3Desc": "ہر کسان دی اپنی بولی تے اپنے ماحول وچ رہنمائی۔",
  "vp.beliefs.b4Title": "بھروسہ",
  "vp.beliefs.b4Desc": "عملی، ویلھے تے صلاح جیہڑی روزگار بچاؤندے۔",
  "vp.beliefs.b5Title": "مستقبل",
  "vp.beliefs.b5Desc": "روایت دا ادبار کرن والی ودھدی ٹیکنالوجی۔",
  "vp.horizons.eyebrow": "اگے دا راہ",
  "vp.horizons.heading": "تن افق، اک سمت",
  "vp.horizons.h1Tag": "افق 01",
  "vp.horizons.h1Phase": "ہُن",
  "vp.horizons.h1Status": "کھیتاں وچ",
  "vp.horizons.h1Body": "سبھ توں پہلاں پاکستان۔ مرکزی مشیر، ڈیجیٹل فارم ریکارڈ، موسم جان صلاح تے چھ علاقائی بولیاں — ہور کسے شے توں پہلاں سچے کساناں دی رائے نال پکیاں۔",
  "vp.horizons.h1P1": "مرکزی مشیر + ریکارڈ",
  "vp.horizons.h1P2": "چھ بولیاں",
  "vp.horizons.h1P3": "سچے کساناں توں بہتری",
  "vp.horizons.h2Tag": "افق 02",
  "vp.horizons.h2Phase": "اگلا",
  "vp.horizons.h2Status": "پھیلاؤ",
  "vp.horizons.h2Body": "گھر وچ گہرائی تے پھیلاؤ — پاکستان بھر وچ ہور فصلاں تے علاقے، زرعی ڈیٹا ذریعاں نال مضبوط تعلق، تے او تجزیے جیہڑے ہر سفارش نوں ہور ذاتی بنا دیندے نیں۔",
  "vp.horizons.h2P1": "ہور فصلاں تے علاقے",
  "vp.horizons.h2P2": "ڈیٹا جوڑ",
  "vp.horizons.h2P3": "اچے تجزیے",
  "vp.horizons.h3Tag": "افق 03",
  "vp.horizons.h3Phase": "بعد وچ",
  "vp.horizons.h3Status": "دنیا بھر",
  "vp.horizons.h3Body": "پلیٹ فارم نویں دیساں، موسماں، فصلاں، بولیاں تے طریقےآں نال ڈھل جاندا اے — دنیا بھر وچ ڈھلن والی زرعی سمجھ، صفر توں شروع کیتے بغیر۔",
  "vp.horizons.h3P1": "نویں دیس",
  "vp.horizons.h3P2": "نویاں بولیاں تے موسم",
  "vp.horizons.h3P3": "دنیا بھر پلیٹ فارم",
  "vp.outcomes.eyebrow": "کامیابی دی شکل",
  "vp.outcomes.heading": "چار نتیجے جنہاں تے اساں آپ نوں تولدے ہاں",
  "vp.outcomes.sub": "وژن ایپ نہیں — کھیت تے بدلن والی حالت اے۔ ہر شے ان چار نتیجیاں دے مقابل چلدی اے۔",
  "vp.outcomes.o1Title": "ودھیا فیصلے",
  "vp.outcomes.o1Desc": "ہر چون — پانی، ان پٹ، ویلہ — عادت دی تھاں ڈیٹا تے۔",
  "vp.outcomes.o2Title": "ودھ پیداوار",
  "vp.outcomes.o2Desc": "صحت مند فصلاں، ویلھے تے ان پٹ، تے چوٹی تے کٹی فصل۔",
  "vp.outcomes.o3Title": "گھٹ بچائی سگدے نقصان",
  "vp.outcomes.o3Desc": "بیماری، کیڑے تے موسم ویلھے تے پکڑے — فصل گنواون توں پہلاں۔",
  "vp.outcomes.o4Title": "فارم کاروبار وانگوں",
  "vp.outcomes.o4Desc": "ترتیب وار ریکارڈ تے موسمی سمجھ جیہنوں بینک تے خریدار مندے نیں۔",
  "vp.principles.eyebrow": "سمجھوتہ کوئی نہیں",
  "vp.principles.heading": "او وعدے جنہاں تے اساں بناوندے ہاں",
  "vp.principles.sub": "وژن تفصیلاں وچ ناکام ہوندا اے۔ ایہ وعدے ہر خاصیت، ہر صفحے، ہر ریلیز تے لاگو نیں — اج توں۔",
  "vp.principles.c1Title": "کسان دا فائدہ پہلاں",
  "vp.principles.c1Desc": "ہر خاصیت کھیت دی لوڑ توں شروع ہوندی اے — ٹیکنالوجی توں کدے نہیں۔",
  "vp.principles.c2Title": "بولی پہلاں",
  "vp.principles.c2Desc": "ہر سکرین تے ہر جواب کسان دی اپنی بولی وچ پجدے نیں۔",
  "vp.principles.c3Title": "دھوپ وچ پڑھن جوگ",
  "vp.principles.c3Desc": "گہرا کنٹراسٹ دوپہر دی دھوپ لئی، صرف دفتر لئی نہیں۔",
  "vp.principles.c4Title": "سادے بول",
  "vp.principles.c4Desc": "اونے سادے جو اک گوانڈھی دوجے نوں سمجھا سگے۔",
  "vp.principles.c5Title": "پہلاں فون",
  "vp.principles.c5Desc": "موبائل پہلاں، وڈے ٹچ نشان — ہُن کھیتی فون تے ای چلدی اے۔",
  "vp.principles.c6Title": "طرز وچ قدرتی",
  "vp.principles.c6Desc": "ہلکت تے ترتیب جیہڑی فطری لگے — ودھ، کدے مشینری نہیں۔",
  "vp.principles.motto": "مٹی تے سگنل — نال نال",
  "wy.meta.title": "اگروپیو کیوں — اے آئی آلا فارم عقل",
  "wy.meta.description": "کھیتی دے فیصلے اندازے تے نہیں چھڈے جا سکندے۔ ویکھو اگروپیو کیویں اے آئی مشیر، فارم ریکارڈ، موسم جانن والی رہنمائی تے مقامی بولیاں ہک پاکستان اول پلیٹ فارم تے اکٹھیاں کریندا اے۔",
  "wy.hero.eyebrow": "اگروپیو کیوں",
  "wy.hero.titleLead": "جتھے مٹی ملدی اے",
  "wy.hero.titleAccent": "سگنل نال",
  "wy.hero.sub": "کھیتی دے فیصلے اندازے تے نہیں چھڈے ویندے۔ اگروپیو ہک ای پلیٹ فارم وچ اے آئی مشیر، تہاڈے فارم دا ریکارڈ، موسم جانن والی رہنمائی تے تہاڈی اپنی بولی ݙیندا اے — تاں جو ہر فیصلہ تہاڈی زمین دی حقیقت تے کھڑا ہووے۔",
  "wy.hero.ctaPrimary": "جلدی رسائی حاصل کرو",
  "wy.hero.ctaSecondary": "پلیٹ فارم ویکھو",
  "wy.hero.tagStart": "پاکستان کیتے بنایا گیا",
  "wy.hero.tagThen": "Aplinode دی پروڈکٹ",
  "wy.hero.svgLabel": "کھیت تے لہردیاں واڑیاں آلیاں خم دار لکیراں",
  "wy.origin.eyebrow": "اسیں ایہ کیوں بنایا",
  "wy.origin.heading": "وڈے فیصلے صرف اندازے تے نہیں ٹکنے چاہیدے",
  "wy.origin.sub": "اگروپیو دی شروعات ہک سادے مشاہدے توں تھئی: کسان دا سیزل چند فیصلیاں نال طے تھیندا اے، تے ہر فیصلہ اصلی عقل دا حق‌دار اے۔",
  "wy.origin.g1Title": "ویلے دا اندازہ",
  "wy.origin.g1Desc": "پاݨی ݙیوݨ، کھاد پاوݨ، بیج پاوݨ، فصل لہاوݨ — سیزل دے فیصلے کرن والے لمحے اج وی عادت تے امید توں چنے ویندے نیں۔",
  "wy.origin.g2Title": "تاریخ مِٹ ویندی اے",
  "wy.origin.g2Desc": "کݙاں سپرے تھئی، کݙاں کھیت سیراب تھیا، پچھلے سال کہڑی بیماری لگی — کجھ وی لکھیا نہیں ویندا، ایں کیتے ایندے توں کجھ وی سکھیا نہیں جا سکدا۔",
  "wy.origin.g3Title": "مشورے کھنڈے ہوئے ہن",
  "wy.origin.g3Desc": "گیوانڈھی، دکاندار تے ویڈیوز ہر ہک جواب ݙیندے نیں — پر کہیں کول تہاڈی فصل، تہاڈی مٹی یا ایں ہفتے دے موسم دی اصلی جانکار نہیں ہوندی۔",
  "wy.origin.banner": "اندازے دی قیمت لہاوݨ دے ݙینہ ادا تھیندی اے",
  "wy.diff.eyebrow": "اینکوں وکھرا کیا بناندا اے",
  "wy.diff.heading1": "محض ہک ٻئی مشورے آلی ایپ نہیں۔",
  "wy.diff.heading2": "فارم عقل دا پلیٹ فارم اے۔",
  "wy.diff.sub": "زیادہ تر اوزار محض سوالاں دے جواب ݙیندے نیں۔ اگروپیو تہاڈا فارم سکھدا اے — تے تہاڈے درج کیتے ہر کم نال ودھ کارآمد تھیندا ویندے۔",
  "wy.diff.personalTitle": "ذاتی قسم دا، عام نہیں",
  "wy.diff.personalDesc": "تجویزاں تہاڈی فصل، تہاڈے مقام، موجودہ موسم تے تہاڈے فارم دی اپنی تاریخ توں بندیاں نیں — کݙاہیں وی ساریاں کیتے ہکو نسخہ نہیں۔",
  "wy.diff.chip1": "تہاڈی فصل",
  "wy.diff.chip2": "تہاڈا ضلع",
  "wy.diff.chip3": "ایں ہفتے دا موسم",
  "wy.diff.chip4": "تہاڈا پچھلا سیزل",
  "wy.diff.langTitle": "تہاڈی بولی ٻولدا اے",
  "wy.diff.langDesc": "جیویں تسیں اصلی ٻولدے او اوویں پچھو تے سمجھو — کوئی اوکھی انگریزی لوڑ نہیں۔",
  "wy.diff.memoryTitle": "ہر فارم دی یادداشت",
  "wy.diff.memoryDesc": "پاݨی، ان پٹ، بیماری، خرچ، لہاوݨ — ہر کم منظم ریکارڈ وچ محفوظ، تاں جو ہر سیزل پچھلے توں بہتر شروع کرے۔",
  "wy.diff.weatherTitle": "بنیادی طور تے موسم جانن آلا",
  "wy.diff.weatherDesc": "رہنمائی تہاڈے کول پُڄݨ توں پہلوں اصلی حالت ݙیدھی اے — تاں جو مینہہ توں گھنٹے پہلوں سپرے دا مشورہ نہ ݙتا ونڄے۔",
  "wy.diff.platformTitle": "ہک پلیٹ فارم، پورا سیزل",
  "wy.diff.platformDesc": "مشیر، ریکارڈ، موسم رہنمائی تے صلاح رل تے کم کریندے نیں — وکھریاں ایپس تے کاپیاں وچ نہیں کھنڈدے۔",
  "wy.diff.pakTitle": "پاکستان اول",
  "wy.diff.pakDesc": "مقامی فصلاں، علاقائی طریقیاں تے اصلی کھیت دیاں حالتاں پہلے ݙینہ توں ڈیزائن وچ نیں — بعد وچ جوڑی ڳئی سوچ دے طور تے نہیں۔",
  "wy.diff.pakBadge": "ایتھوں شروعات",
  "wy.life.eyebrow": "مشیر کہڑے کہڑے وچ رہنمائی کریندا اے",
  "wy.life.heading": "فصل دے چکر دے ہر فیصلے کیتے رہنمائی",
  "wy.life.sub": "ہک مشیر پورے فصلی دور وچ تہاڈے نال رہندا اے — سیزل دی منصوبہ بندی توں گھن تے فصل گھر پُچاوݨ تائیں۔",
  "wy.life.s1Title": "پاݨی ݙیوݨ دا ویلھا",
  "wy.life.s1Desc": "ڄاݨو کݙاں پاݨی ݙیوݨ اے — تے کݙاں اڈیک کرݨ اے۔",
  "wy.life.s2Title": "فصل دی منصوبہ بندی",
  "wy.life.s2Desc": "اپنی زمین دے موافق فصلاں تے بیج پاوݨ دے ویلیاں چونڑھو۔",
  "wy.life.s3Title": "کھاد تے کیڑے مار دوائیاں دی رہنمائی",
  "wy.life.s3Desc": "سچا ان پٹ، سچی مقدار وچ، سچے ویلے تے۔",
  "wy.life.s4Title": "کیڑے تے بیماری وچ مدد",
  "wy.life.s4Desc": "مسلے جلدی پکڑو تے پھیلݨ توں پہلوں عمل کرو۔",
  "wy.life.s5Title": "لہاوݨ دا ویلھا",
  "wy.life.s5Desc": "اوں لحظے لہاؤ جیڑھا پیداوار تے معیار دی حفاظت کرے۔",
  "wy.life.s6Title": "موسم جانن آلیاں تجویزاں",
  "wy.life.s6Desc": "ہر مشورہ پہلوں اج دیاں حالتاں ݙیدھے۔",
  "wy.life.s7Title": "روزمرہ سوال",
  "wy.life.s7Desc": "اپنی فصل بارے کجھ وی پچھو، سیزل دے کہیں وی ݙینہ۔",
  "wy.value.eyebrow": "وعدہ",
  "wy.value.heading1": "کیا کرݨ اے۔ کݙاں کرݨ اے۔",
  "wy.value.heading2": "تے کیا تھی چکا اے۔",
  "wy.value.sub": "اگروپیو دی ہر سہولت انہاں ترائے جواباں وچوں ہک دی خدمت کریندی اے — اینج فیصلیاں دا سیزل بھروسے دا سیزل بن ویندے۔",
  "wy.value.p1Heading": "کیا کرݨ اے",
  "wy.value.p1Desc": "تہاڈی فصل تے حالتیں مطابق صاف، خاص تجویزاں — عام اشارے نہیں۔",
  "wy.value.p2Heading": "کݙاں کرݨ اے",
  "wy.value.p2Desc": "اصلی موسم تے ودھارے دے مرحلے مطابق ویلھا، تاں جو سچا قدم سچے لحظے تے تھیوے۔",
  "wy.value.p3Heading": "کیا تھی چکا اے",
  "wy.value.p3Desc": "ہر کم دی منظم تاریخ — ہمیشہ دستیاب، ہمیشہ بہتر مشورے دی بنیاد۔",
  "wy.who.eyebrow": "کس کس کیتے اے",
  "wy.who.heading": "کسان توں شروع تھی تے اگے",
  "wy.who.a1Title": "انفرادی کسان",
  "wy.who.a1Desc": "ہر فیصلے وچ عملی، ذاتی رہنمائی — تے جیڑھا کجھ تھی چکا اے اوندا منظم ریکارڈ۔",
  "wy.who.a2Title": "وپاری فارم تے زرعی کاروبار",
  "wy.who.a2Desc": "ٹیماں، کھیتاں تے سیزلاں وچ منظم فارم جانکار تے بھروسے جوڳی فیصلہ سازی دی مدد۔",
  "wy.who.a3Title": "ایکو سسٹم دے ساجھے دار",
  "wy.who.a3Desc": "ان پٹ ݙیوݨ آلے، کوآپریٹو، بیمہ کمپنیاں تے زرعی توسیعی خدمات — جیویں جیویں پلیٹ فارم ودھدا اے۔",
  "wy.who.strip": "فارم دے دوالے ماحول نال ودھدے ہوئے",

  "auth.backHome": "ہوم تے واپس",
  "auth.emailLabel": "ای میل پتہ",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاس ورڈ",
  "auth.showPassword": "پاس ورڈ وکھاؤ",
  "auth.hidePassword": "پاس ورڈ لکاؤ",
  "auth.err.emailRequired": "اپنا ای میل پتہ لکھو۔",
  "auth.err.emailInvalid": "درست ای میل پتہ لکھو۔",
  "auth.err.passwordRequired": "پاس ورڈ بناو۔",
  "auth.err.passwordMin": "گھٹو گھٹ ۸ حروف ورتو۔",
  "auth.err.passwordMax": "وڈھے توں وڈھے ۶۴ حروف ورتو۔",
  "auth.err.nameRequired": "اپنا پورا ناں لکھو۔",
  "auth.err.phoneInvalid": "درست فون نمبر لکھو۔",
  "auth.err.confirmRequired": "اپنا پاس ورڈ ولا لکھو۔",
  "auth.err.termsRequired": "اگے ودھن واسطے شرطاں منو۔",
  "auth.err.passwordMismatch": "پاس ورڈ ہکو جیہے نیں۔",
  "auth.err.loginPasswordRequired": "اپنا پاس ورڈ لکھو۔",
  "auth.err.tooManyAttempts": "بہت زیادہ کوششاں — مہربانی کر تھوڑی دیر بعد ولا کوشش کرو۔",
  "auth.err.serverError": "ساڈے پاسوں خرابی آئی۔ مہربانی کر ولا کوشش کرو۔",
  "auth.err.invalidCredentials": "ای میل یا پاس ورڈ غلط اے۔",

  "li.meta.title": "سائن اِن — اگروپیو",
  "li.meta.description":
    "اگروپیو، اے آئی والی فارم ذہانت دے پلیٹ فارم وچ سائن اِن کرو۔ تہاڈا مشیر، ریکارڈ تے رہنمائیاں — اوتھے موجود جتھے تسیں چھڈے سن۔",
  "li.brand.headingA": "تہاڈے فارم دی ذہانت،",
  "li.brand.headingB": "اوتھے انتظار وچ جتھے تسیں چھڈی سی۔",
  "li.demo.aria": "اگروپیو مشیر نال گل بات دی جھلک",
  "li.demo.user": "میری کنک دے پترے پیلس تھیندے پئے نیں — کیہ کراں؟",
  "li.demo.advisorLabel": "دو کارن:",
  "li.demo.advisorBody": "پاݨی دی کمی یا نائٹروجن دی کمی۔ پہلے سویرے ٹھنڈے ویلے تے پاݨی دیو۔",
  "li.point1": "تہاڈی اپنی بولی وچ اے آئی مشیر",
  "li.point2": "سیٹیلائٹ راہیں فصل دی صحت دی نگرانی",
  "li.point3": "ہر موسم دا ڈیجیٹل ریکارڈ",
  "li.eyebrow": "سائن اِن",
  "li.heading": "تہاڈے فارم تے ولا خوش آمدید",
  "li.sub": "سائن اِن کرو تاں جو تہاڈے فارم دے مشیر، ریکارڈ تے رہنمائیاں تائیں پہنچ سکو۔",
  "li.passwordPlaceholder": "تہاڈا پاس ورڈ",
  "li.forgot": "پاس ورڈ بھل گئے او؟",
  "li.submitting": "سائن اِن تھیندا پیا اے…",
  "li.noAccount": "حالاں اکاؤنٹ نہیں؟ ابتدائی رسائی علاقہ علاقہ کھلدی جا رہی اے —",
  "li.noAccountEnd": "۔",
  "li.createAccount": "اپنا اکاؤنٹ بناؤ",

  "su.meta.title": "اکاؤنٹ بناؤ — اگروپیو",
  "su.meta.description":
    "اپنا اگروپیو اکاؤنٹ بناؤ: ذاتی قسم دا اے آئی مشیر، موسم جانن والی رہنمائی، تے فارم ریکارڈ جیڑھے ہر موسم نوں بہتر بناؤندے نیں۔ پاکستان واسطے بنایا گیا۔",
  "su.brand.headingA": "اپنا موسم شروع کرو",
  "su.brand.headingB": "ذہانت نال۔",
  "su.profile.aria": "سائن اپ دے بعد بݨن آلے فارم پروفائل دی جھلک",
  "su.profile.badge": "فارم پروفائل · ہک منٹ وچ تیار",
  "su.profile.district": "ضلع",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشورے دی بولی",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "کنک · ربیع",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پہلے ݙینہ توں ذاتی قسم دا مشیر",
  "su.included2": "تہاڈے ضلعے واسطے موسم جانن والی رہنمائی",
  "su.included3": "فارم ریکارڈ جیڑھے ہر موسم نوں بہتر بناؤندے نیں",
  "su.eyebrow": "اکاؤنٹ بناؤ",
  "su.heading": "اپنا فارم اگروپیو لیاؤ",
  "su.sub": "اک اکاؤنٹ — تہاڈے مشیر، ریکارڈ تے ایں موسم دی ہر رہنمائی واسطے۔",
  "su.registered.title": "ایہ ای میل پہلے توں رجسٹرڈ اے۔",
  "su.registered.body":
    "سائن اِن کرو، یا جے پاس ورڈ بھل گئے او تے ری سیٹ کرو — تہاڈا فارم اوتھے انتظار وچ اے جتھے تسیں چھڈیا سی۔",
  "su.registered.reset": "پاس ورڈ ری سیٹ کرو",
  "su.name.label": "پورا ناں",
  "su.name.placeholder": "مثلاً محمد احمد",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختیاری)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آف لائن ہووݨ تے ایس ایم ایس الرٹس واسطے۔",
  "su.password.placeholder": "گھٹو گھٹ ۸ حروف",
  "su.confirm.label": "پاس ورڈ دی تصدیق کرو",
  "su.confirm.placeholder": "اپنا پاس ورڈ ولا لکھو",
  "su.strength0": "بہت تھولا",
  "su.strength1": "ٹھیک اے",
  "su.strength2": "چنگا",
  "su.strength3": "مضبوط",
  "su.terms.prefix": "میں",
  "su.terms.tos": "خدمت دیاں شرطاں",
  "su.terms.and": "تے",
  "su.terms.privacy": "پرائیویسی پالیسی",
  "su.terms.end": "منیندا واں۔",
  "su.submit": "میرا اکاؤنٹ بناؤ",
  "su.submitting": "اکاؤنٹ بݨدا پیا اے…",
  "su.haveAccount": "پہلے توں اکاؤنٹ اے؟",
  "app.shell.metadataTitle": "اگروپیو — مصنوعی ذہانت نال چلݨ آلا فارم ذہانت دا پلیٹ فارم",
  "app.shell.metadataDescription":
    "اَج دی رہنمائی، موسم، الرٹ تے اگروپیو دا ہر ٹول — پاکستان لئی بنایا گیا۔ اپلینوڈ دی پروڈکٹ۔",

  /* ── شیل نیویگیشن ─────────────────────────────────── */
  "app.shell.nav.dashboard": "ڈیش بورڈ",
  "app.shell.nav.farms": "کھیت",
  "app.shell.nav.advisor": "مشیر",
  "app.shell.nav.detect": "تشخیص",
  "app.shell.nav.prices": "قیمتاں",
  "app.shell.nav.notifications": "اطلاعات",
  "app.shell.nav.settings": "ترتیبات",
  "app.shell.nav.more": "ور ",
  "app.shell.signOut": "لاگ آؤٹ",
  "app.shell.aria.farmerTools": "کسان دے ٹول",
  "app.shell.aria.currentPage": "موجودہ صفحہ",
  /* ── ڈیش بورڈ UI ──────────────────────────────────── */
  "app.dashboard.greeting": "ہیلو، {name}",
  "app.dashboard.aria.profileMenu": "پروفائل مینو",
  "app.dashboard.welcomeEyebrow": "اگروپیو وچ خوش آمدید",
  "app.dashboard.welcomeTitle": "اپنا پہلا کھیت شروع کرو۔",
  "app.dashboard.welcomeBody":
    "تہاڈی فصل، تہاڈی زمین، تہاڈا موسم — جِدّوں تہاڈا کھیت ہوئے گا ہر رہنمائی اُس دے مطابق ہوئے گی۔",
  "app.dashboard.addFirstFarm": "اپنا پہلا کھیت شامل کرو",
  "app.dashboard.badge.today": "اَج",
  "app.dashboard.aria.advisoryTitle": "اَج دی رہنمائی",
  "app.dashboard.carryToField": "اِس نوں کھیت وِچ لے کے جاؤ",
  "app.dashboard.askAdvisor": "مشیر نال پوچھو",
  "app.dashboard.aria.weatherTitle": "موسم \u00b7 {location}",
  "app.dashboard.aria.degreesCelsius": "{n} ڈگری سیلسیس",
  "app.dashboard.fullForecast": "مکمل پیشگوئی",
  "app.dashboard.weatherUnavailable":
    "موسم ہُن لوڈ نہیں ہو ریہا۔ تھوڑی دیر بعد دوبارہ چیک کرو — تہاڈیاں رہنمائیاں چالیاں۔",
  "app.dashboard.seasonTipBadge": "موسمی تجاویز",
  "app.dashboard.alertsHeading": "الرٹ",
  "app.dashboard.newCount": "{n} نئیاں",
  "app.dashboard.viewAllAlerts": "سارے الرٹ ویکھو",
  "app.dashboard.noAlerts": "اَج کوئی الرٹ نہیں — تہاڈیاں فصلیں سکون وچ ہیں۔",
  "app.dashboard.aria.alert": "الرٹ",
  "app.dashboard.severity.critical": "سنگین",
  "app.dashboard.severity.watch": "خبردار",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "بولی",
  "app.dashboard.quickActionsHeading": "فوری عمل",
  "app.dashboard.cropDoctor": "فصل دا ڈاکٹر",
  "app.dashboard.detectTitle": "بیماری پھیلنے توں پہلے پہچانو",
  "app.dashboard.detectBody":
    "متاثرے پتے دی تصویر اپلوڈ کaro — فوری تشخیص تے اگلا قدم تہاڈے فون تے۔",
  "app.dashboard.myFarms": "میرے کھیت",
  "app.dashboard.addFarm": "کھیت شامل کرو",
  "app.dashboard.health.good": "چنگا",
  "app.dashboard.health.watch": "خبردار",
  "app.dashboard.setupChecklist": "اپنا کھیت ترتیب کرو",
  "app.dashboard.checklistProgress": "{total} وِچوں {done} مکمل",
  "app.dashboard.aria.dismissChecklist": "سیٹ اپ چیک لسٹ بند کرو",
  "app.dashboard.aria.setupProgress": "سیٹ اپ دی پیشرفت",
  "app.dashboard.demoFooter": "ڈیمو بلڈ \u00b7 صرف نمونہ ڈیٹا",
  /* ── ڈیش بورڈ ڈیمو ڈیٹا ──────────────────────────── */
  "app.dashboard.demo.todayLabel": "اتوار، ۲۳ اگست",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "سبزی کا مرحلہ",
  "app.dashboard.demo.advisoryAction": "اَج آبپاشی وِچ تاخیر کرو",
  "app.dashboard.demo.advisoryWhy":
    "اَج دوپہر توں بعد بارش دا امکان ہے — تہاڈا کھیت قدرتی طور تے پانی پائے گا۔",
  "app.dashboard.demo.seasonAction": "بارش آنے توں پہلے اپنے کھیتاں وِچ چلو",
  "app.dashboard.demo.seasonWhy":
    "خشک دناں توں بعد ہولی چلنا دکھاؤں دا ہے کِہ کُڈّے نکاسی خراب کرتے ہیں — بونے توں پہلے نوٹ کرو۔",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "دوپہر ۲ بجے توں بعد بارش دا امکان \u00b7 ۸۰٪ امکان",
  "app.dashboard.demo.alertWhitefly":
    "ملتان ضلع وِچ اِس ہفتے کپاس تے سفید مکھی دا خطرہ زیادہ ہے۔",
  "app.dashboard.demo.alertRain":
    "اَج دوپہر ۲ بجے توں بعد بارش متوقع ہے — چھڑی چھڑکنے دا منصوبہ ملتوی کرو۔",
  "app.dashboard.demo.alertPrice":
    "ملتان مڑی تے گندم دیاں قیمتاں گزشتہ ہفتے دے مقابلے وِچ ۴٪ زیادہ ہیں۔",
  "app.dashboard.demo.farm1Name": "خلیل پور کھیت",
  "app.dashboard.demo.farm1Location": "خلیل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "سبزی کا مرحلہ",
  "app.dashboard.demo.farm2Name": "سہیوال پلاٹ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڈ، سہیوال",
  "app.dashboard.demo.farm2Crops": "کپاس",
  "app.dashboard.demo.farm2Stage": "پھول آنا",
  "app.dashboard.demo.farm3Name": "چک ۶۲ جی بی",
  "app.dashboard.demo.farm3Location": "چک ۶۲ جی بی، فیصل آباد",
  "app.dashboard.demo.farm3Crops": "گنا",
  "app.dashboard.demo.farm3Stage": "پَرچی کا مرحلہ",
  "app.dashboard.demo.checklistAdvisor": "اِک واری مشیر نال پوچھو",
  "app.dashboard.demo.checklistDetect": "اپنی پہلی تشخیص چلاؤ",
  "app.dashboard.demo.actionAdvisor": "مشیر نال پوچھو",
  "app.dashboard.demo.actionScan": "فصل اسکین کرو",
  "app.dashboard.demo.actionPrices": "قیمتاں چیک کرو",
  "app.dashboard.demo.actionRecord": "ریکارڈ شامل کرو",

  /* ── کھیت عام ──────────────────────────────────────── */
  "app.farms.eyebrow": "کھیت",
  "app.farms.health.good": "چنگا",
  "app.farms.health.watch": "خبردار",
  "app.farms.units.acres": "ایکڑ",
  "app.farms.stages.sowing": "بوئی",
  "app.farms.stages.tillering": "شاخاں کا نکلنا",
  "app.farms.stages.vegetative": "نباتاتی",
  "app.farms.stages.grainFilling": "دنہاں بھرنا",
  "app.farms.stages.ready": "تیار",
  "app.farms.stages.squaring": "فال بندی",
  "app.farms.stages.flowering": "پھول آنا",
  "app.farms.stages.bollFilling": "تہائی بھرنا",
  "app.farms.stages.grandGrowth": "عریض نشوونما",
  "app.farms.stages.ripening": "پکنا",
  "app.farms.stages.harvest": "کٹائی",

  /* ── ضلع تے فصلیں ──────────────────────────────────── */
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سہیوال",
  "app.farms.districts.faisalabad": "فیصل آباد",
  "app.farms.districts.vehari": "وہاڑی",
  "app.farms.districts.bahawalpur": "بہاولپور",
  "app.farms.districts.lodhran": "لودھراں",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "کپاس",
  "app.farms.crops.sugarcane": "گنا",
  "app.farms.crops.maize": "مکئی",
  "app.farms.crops.rice": "چاول",

  /* ── کھیتاں دی فہرست ────────────────────────────────── */
  "app.farms.list.pageTitle": "کھیت — اگروپیو",
  "app.farms.list.heading": "تہاڈے سارے کھیت، اک فہرست",
  "app.farms.list.description":
    "ہر کھیت اپنیاں فصلیں، نشوونما دے مرحلے تے صحت دے ساتھ — اک نظر وِچ۔ کھیت دی مکمل کہانی واسطے ٹیپ کرو۔",
  "app.farms.list.addLink": "شامل کرو",
  "app.farms.list.openFarm": "کھیت کھولو",
  "app.farms.list.addNewFarm": "نیا کھیت شامل کرو",

  /* ── نیا کھیت ────────────────────────────────────────── */
  "app.farms.new.pageTitle": "کھیت شامل کرو — اگروپیو",
  "app.farms.new.heading": "کھیت شامل کرو",
  "app.farms.new.description":
    "اگروپیو نوں اپنی زمین بارے وِچ دسو — مقام، فصل تے رقبہ — تاں جو ہر رہنمائی اُس دے مطابق ہووے۔",
  "app.farms.new.fields.name": "کھیت دا ناں",
  "app.farms.new.placeholders.name": "مثلاً خلیل پور کھیت",
  "app.farms.new.fields.district": "ضلع",
  "app.farms.new.placeholders.district": "ضلع چنو",
  "app.farms.new.fields.crop": "بنیادی فصل",
  "app.farms.new.placeholders.crop": "فصل چنو",
  "app.farms.new.fields.acres": "رقبہ (ایکڑ)",
  "app.farms.new.placeholders.acres": "مثلاً ۱۲.۵",
  "app.farms.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.farms.new.buttons.save": "کھیت محفوظ کرو",
  "app.farms.new.demoNotice": "ڈیمو — محفوظ کرنا ہُن ڈیٹابیس نال نہیں جُڑیا",
  "app.farms.new.success.heading": "کھیت ڈیمو وِچ محفوظ ہو گیا",
  "app.farms.new.success.description":
    "مکمل بلڈ وِچ اِہ کھیت تہاڈے ڈیش بورڈ تے دکھائے گا تے رہنمائیاں شکل لینا شروع کریں گیاں۔",
  "app.farms.new.success.goToFarms": "میرے کھیتاں تے جاؤ",
  "app.farms.new.success.backToDashboard": "واپس ڈیش بورڈ تے",
  "app.farms.new.errors.nameRequired": "کھیت نوں ناں دیو۔",
  "app.farms.new.errors.districtRequired": "ضلع چنو۔",
  "app.farms.new.errors.cropRequired": "بنیادی فصل چنو۔",
  "app.farms.new.errors.acresRequired": "رقبہ ایکڑ وِچ درج کرو۔",

  /* ── کھیت دی تفصیل ──────────────────────────────────── */
  "app.farms.detail.pageTitle": "کھیت دی تفصیل — اگروپیو",
  "app.farms.detail.heroEyebrow": "کھیت دی تفصیل",
  "app.farms.detail.goodHealth": "چنگی صحت",
  "app.farms.detail.needsWatching": "توجہ لاگم",
  "app.farms.detail.sownLabel": "بوئی",
  "app.farms.detail.seasonHeading": "فصل کِتھے اے",
  "app.farms.detail.activityHeading": "کھیت دی سرگرمی",
  "app.farms.detail.viewAllRecords": "سارے ریکارڈ ویکھو",
  "app.farms.detail.logFieldEvent": "کھیت دا واقعہ درج کرو",
  "app.farms.detail.scanCrop": "فصل اسکین کرو",

  /* ── ریکارڈ عام ──────────────────────────────────────── */
  "app.records.eyebrow": "کھیت دے ریکارڈ",
  "app.records.types.irrigation": "آبپاشی",
  "app.records.types.fertilizer": "کھاد",
  "app.records.types.pesticide": "کیڑے مار",
  "app.records.types.disease": "بیماری",
  "app.records.types.harvest": "کٹائی",

  /* ── ریکارڈاں دی فہرست ──────────────────────────────── */
  "app.records.farmRecords.pageTitle": "کھیت دے ریکارڈ — اگروپیو",
  "app.records.farmRecords.heading": "کھیت دی یادداشت",
  "app.records.farmRecords.description":
    "ہر آبپاشی، اسپرے تے علاج لکھیا ہویا — تاں جو اگلے ہفتے دے فیصلے یادداشت تے منحصر نہ ہوں۔",
  "app.records.farmRecords.demoNotice":
    "ڈیمو — صرف نمونہ اندراجات — نئے محفوظ کرنا ہُن نہیں جُڑیا",

  /* ── نیا ریکارڈ ──────────────────────────────────────── */
  "app.records.new.pageTitle": "نیا ریکارڈ — اگروپیو",
  "app.records.new.heading": "کھیت وِچ جو ہویا اُہ درج کرو",
  "app.records.new.description":
    "آبپاشی، کھاد، کیڑے مار، بیماری تے کٹائی دے اندراجات — تہاڈے کھیت دی یادداشت، اِک اِک لائن۔",
  "app.records.new.fields.type": "کیا ہویا؟",
  "app.records.new.fields.farm": "کھیت",
  "app.records.new.placeholders.farm": "کھیت چنو",
  "app.records.new.fields.date": "تاریخ",
  "app.records.new.fields.title": "مختصر عنوان",
  "app.records.new.fields.optional": "(اختیاری)",
  "app.records.new.placeholders.titleIrrigation": "مثلاً نہری پانی — مکمل کھیت",
  "app.records.new.placeholders.titleOther": "دوسرا چھڑکاؤ پتواروں تے",
  "app.records.new.fields.details": "تفصیلات",
  "app.records.new.placeholders.details":
    "اگلے ہفتے واسطے جو وی یاد رکھنا ضروری ہو — مقدار، موسم، کھیت دی صورتحال۔",
  "app.records.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.records.new.buttons.save": "ریکارڈ محفوظ کرو",
  "app.records.new.demoNotice": "ڈیمو — محفوظ کرنا ہُن ڈیٹابیس نال نہیں جُڑیا",
  "app.records.new.success.heading": "ریکارڈ ڈیمو وِچ محفوظ ہو گیا",
  "app.records.new.success.description":
    "مکمل بلڈ وِچ اِہ اندراج تہاڈے کھیت دے ریکارڈ وِچ شامل ہوگا تے مستقبل دیاں رہنمائیاں تیز ہوں گیاں۔",
  "app.records.new.success.backToDashboard": "واپس ڈیش بورڈ تے",
  "app.records.new.success.viewFarms": "میرے کھیت ویکھو",
  "app.records.new.errors.farmRequired": "چنو اِہ کس کھیت تے ہویا۔",
  "app.records.new.errors.dateRequired": "تاریخ چنو۔",
};
