import type { CatalogKey } from "./en.ts";

/** ہندکو — AI-drafted, founder-reviewed copy (plan D4). */
export const hno: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کیویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ موجود نئیں",
  "notFound.body": "تساں جیہڑا صفہ لبھیا اودو موجود نئیں یا منتقل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے گھر واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت نال فارم دی ذہانت دا پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کاشتکاری لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک پلیٹ فارم جیڑھا اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تساڈے فارم دے ریکارڈ اک تھاں رلاوندا اے — ڈیٹا سوچ فیصلہ بناندا اے، تساڈی اپنی بولی چ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کیویں کم کردا اے",
  "home.hero.imageAlt": "کسان کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "ودھیا",
  "home.hero.noteClearSky": "صاف اسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "کاشتکاری دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان وچ کسان ریایت، مقامی صلاحاں تے کھنڈریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان کٹائی تے چکندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، کٹائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹدی تے خرچ ضائع تھیندی اے۔",
  "home.problem.item2Title": "گواچیا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھنڈریاں کاپیاں وچ رہندا اے۔ پچھلے سال جیہڑا کم آیا، اوں توں ایں سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھنڈریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کسان دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت کٹائی تے چکندی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تساڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک ذہانت دا پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈی تساڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیمیا مار تے کٹائی دے ویلیے لئی ذاتی صلاحاں — تساڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تساڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا گیا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، کٹائی — ترتیب والے ریکارڈ وچ محفوظ جیہڑا ہر سیزن نوں ودھ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "مکمل تریخ، ہمیشہ موجود۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "کئی انجن،",
  "home.features.titleB": "اک ذہین پلیٹ فارم",
  "home.features.subtitle": "تساڈے اپنے بولاں توں پہلے سوال توں لے کے سارے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی نوں تقویت دیوے اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی کاشتکاری مشیر",
  "home.features.advisorTopics": "پانی · کھاد · کیمیا تے بیماری · کٹائی",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "پیلیاں پتریاں والی گندم بارے اگروپیو مشیر نال نمونہ گل بات",
  "home.features.advisorUserMsg": "میری گندم دے پتر پیالے ہو رے نیں — کی کراں؟",
  "home.features.advisorReplyTitle": "پیالے پتر — دو عام وجوہات:",
  "home.features.advisorReplyCause1": "پانی دی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے وقتاں وچ، سویرے 9 وجے توں پہلاں پانی دیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سبھ توں پرانے پتر پہلاں ویکھو؛ لوڑ ہووے تاں یوریا پاؤ۔",
  "home.features.advisorReplyFooter": "جے پتریاں تھلے پیلیاں لیکاں دسن، فوٹو بھیجو — main بیماری دی جانچ کر دیسانگی۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھو یا بولو…",
  "home.features.advisorFooter": "اپنی فصل بارے کجھ وی پچھو — روزمرہ سوالاں خوش آمدید نیں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر کم ترتیب نال لکھیا — تے جے صلاح تساڈی اپنی زمین توں سکھے۔",
  "home.features.record1Activity": "پانی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتریاں دا سکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "گندم · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · بولی",
  "home.features.languageTitle": "تساڈی بولی، تساڈے بول",
  "home.features.languageDesc": "جدوں سوچدے او ادوں بول کے یا لکھو — تکنیکی انگریزی دی لوڑ نئیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں جانو رہنمائی",
  "home.features.weatherDesc": "صلاح تساڈے کول پجدیاں پہلاں اصلی حالات ویکھدی اے — mینہ توں پہلاں سپرے کیتا تے سارا کھاد وہ جانا اے۔",
  "home.features.weatherMockAria": "پنج دناں دی پیشنگوئی جیندے وچ جمعرات نوں سپرے نہ کرن دی صلاح نمایاں اے",
  "home.features.dayMon": "سوموار",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "سپرے روکو",
  "home.features.weatherLegend": "مقامی موسم پیشنگوئی توں صلاح والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودھدا جا ریا اے — ساریاں صلاحیتاں ویکھو",
  "home.journey.eyebrow": "ایہ کیویں کم کردا اے",
  "home.journey.title": "اک سوال سیزن شروع کردا اے",
  "home.journey.subtitle": "تساڈے پہلے سوال توں مکمل، ذہین فارم تریخ تک سادہ راہ۔",
  "home.journey.step1Title": "اپنا فارم پایو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بناؤن لئی تھاں، فصل تے بنیادی جانکاری بھرو۔",
  "home.journey.step2Title": "اے آئی توں پچھو",
  "home.journey.step2Body": "اپنا سوال اس بولی وچ لکھو یا بولو جس نوں تساں سبھ توں ودھ سمجھدے او۔",
  "home.journey.step3Title": "رہنمائی پاؤ",
  "home.journey.step3Body": "اپنی فصل، موسم، تھاں تے فارم تریخ تے بیسیاں صلاحاں پاؤ۔",
  "home.journey.step4Title": "کم لکھو",
  "home.journey.step4Body": "تھوڑھے ٹیپاں وچ پانی، کھاد، دوائی جاں بیماری لکھو۔",
  "home.journey.step5Title": "تریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ آن والیاں صلاحاں نوں ودھ سمجھدار تے موزاں بناندا اے۔",
  "home.journey.step6Title": "نگراں کردے رہو",
  "home.journey.step6Body": "سارے سیزن دوران ریکارڈ ویکھو تے ترقی تے نگاہ رکھو۔",
  "home.matrix.eyebrow": "ساریاں صلاحیتاں دا مجموعہ",
  "home.matrix.title": "لوڑ توں حیران کرن والے تک",
  "home.matrix.subtitle": "ہر خاصیت فصل بچاندی اے، خرچ گھٹاندی اے جاں کمائی ودھاندی اے۔ اسنوں جنتری وانگر پڑھو — ہر درجہ پچھلے تے کھڑا اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتاں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی پدھر",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری پچھان",
  "home.matrix.t1f1Body": "متاثرہ پتر دی فوٹو چاڑھو تے فوری جانچ، شدت تے علاج دیاں صلاحاں پاؤ۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت نگرانی",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد نشان لگاؤ تے مفت سینٹینل-2 تصویراں توں این ڈی وی آئی بیسڈ فصل صحت ویکھو۔",
  "home.matrix.t1f3Title": "ہوشیار موسمی صلاح",
  "home.matrix.t1f3Body": "مقامی موسم پیشنگوئی تساڈی فصل تے ودھدے پڑاءُ نال مل کے روزانہ کماں دی صلاح بن جاندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیشنگوئی",
  "home.matrix.t1f4Body": "نزدیکی منڈی دیاں قیمتیں اے آئی رجحاناں نال ویکھو، تے ٹھیک ویلیے تے ویچو۔",
  "home.matrix.tier2Name": "وکھریاں خاصیتاں",
  "home.matrix.tier2Badge": "نمانا",
  "home.matrix.t2f1Title": "علاقائی بولیاں دی وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولو جاں لکھو — جواب اس بولی وچ سنو جس تساں بہتر سمجھدے او۔",
  "home.matrix.t2f2Title": "سرکاری سکیم میچر",
  "home.matrix.t2f2Body": "اپنیاں جانکاریاں بھرو تے ہر اہل سکیم لبھو — دستاویزاں تے اپلائی لنکاں سمیت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن تساڈی مٹی، موسم، منڈی دی منگ تے بجٹ مطابق سبھ توں ودھ منافع والی فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے اصلی خرچ، پیداوار، کمائی تے نفع — بریک ایون تے آر او آئی نال۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوال پاؤ، فوٹو شیئر کرو، ساتھی کساناں تے تصدیق شدہ ماہراں پاسوں جواب لو۔",
  "home.matrix.tier3Name": "حیران کن",
  "home.matrix.tier3Badge": "سبھ توں اگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی نگرانی",
  "home.matrix.t3f1Body": "سلائیڈر نال ویلے نال سیٹلائٹ تصویراں تولو — ودھاءُ، نقصان جاں قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیشنگوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے پڑاءُ تے تریخ دے بنیاد تے ممکنہ حملے توں پہلاں سوچنا۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر تے کال کرو، سوال بولو، اپنی بولی وچ صلاح سنو — اسمارٹ فون دی لوڑ نئیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ اندازہ",
  "home.matrix.t3f4Body": "ٹکاؤ طریقے لکھو تے رضاکارانہ مارکیٹاں توں کاربن کریڈٹ دا اندازہ لاو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت وچ آف لائن کم کرے، کنکشن تے سنک ہووے، کمزور نیٹ تے ایس ایم ایس خبر دیوے۔",
  "home.vision.eyebrow": "وژن",
  "home.vision.titleA": "پاکستان لئی بنایا گیا۔",
  "home.vision.titleB": "دنیا لئی تیار۔",
  "home.vision.pkTitle": "پہلوں پاکستان والا ول",
  "home.vision.pkBody": "پہلا ورژن پاکستان دے کھیتاں لئی بنایا گیا اے: مقامی فصلاں، علاقائی بولیاں، اصلی کاشتکاری دے طریقیاں تے اصلی کھیتاں دیاں حالتاں۔",
  "home.vision.pkPoint1": "مقامی فصل تے موسم دی سمجھ",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "اصلی کساناں دے فیڈبیک نال بہتر بنایا گیا",
  "home.vision.worldTitle": "دنیا بھر پھیلن دا وژن",
  "home.vision.worldBody": "موزاں تھیوݨ لئی بنایا گیا۔جدوں پلیٹ فارم ودھدا اے تے نویں دیساں، بولیاں، فصلاں تے موسماں تک جاندا اے—شروعوں نویں سرے نہ بݨاوݨ۔",
  "home.vision.worldPoint1": "دیس مطابق کھیتی بار دی سمجھ",
  "home.vision.worldPoint2": "ہور بولیاں تے مقامی فصلاں",
  "home.vision.worldPoint3": "ڈونگھی ڈیٹا جوڑ تے تجزیے",
  "home.users.title1": "انفرادی کسان",
  "home.users.desc1": "نکے تے وچولے فارم جنہاں نوں عملی صلاح تے ہر کم دا ترتیب والا ریکارڈ چاہیدا اے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہاں نوں ترتیب والی جانکاری، فیصلے دی مدد تے ٹیم دے ریکارڈ چاہیدن۔",
  "home.users.title3": "ایکو سسٹم ساتھی",
  "home.users.desc3": "ان پٹ سپلائر، کوآپریٹو، بیمہ تے ایکسٹینشن سروساں جیہڑیاں ویلے نال پلیٹ فارم نال جڑن گیاں۔",
  "home.users.tagline": "پہلوں کساناں لئی بنایا گیا — ایکو سسٹم نال ودھدا ہویا",
  "home.cta.eyebrow": "شروعاتی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم تے لیاؤ",
  "home.cta.subtitle": "اگروپیو نال بہتر فیصلے کرن والے کساناں وچ رل تھیوو — پاکستان توں شروع، دنیا بھر وچ ودھاءُ۔",
  "home.cta.success": "تسیں لسٹ وچ او۔جدوں تہاڈا علاقہ کھلسیگا اساں رابطہ کرساں۔",
  "home.cta.emailLabel": "ای میل پتہ",
  "home.cta.fineprint": "کوئی سپام نہیں۔جس وی ویلے ان سبسکرائب کرو۔",
  "home.footer.tagline": "اے آئی والا فارم انٹیلیجنس پلیٹ فارم۔صلاح، سیٹلائٹ نگرانی، منڈی دیاں قیمتیں تے ریکارڈ—مٹی تے سگنل، نال نال۔",
  "home.footer.pagesHeading": "ورقے",
  "home.footer.pagesNavLabel": "فوٹر ورقے",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس دیاں شرطاں",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کرو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔سارے حق محفوظ نیں۔",
  "home.footer.motto": "پاکستان لئی بنیا · دنیا لئی تیار",
  "hiw.meta.title": "ایہ کویں کم کردا اے — اگروپیو",
  "hiw.meta.description":
    "اک منٹ دے فارم پروفائل توں لگاتار بہتر ہووݨ والے موسمی چکر تائیں: ݙیکھو اگروپیو سوال، سرگرمیاں تے ریکارڈ کویں ذاتی کھیتی رہنمائی وچ بدلدا اے۔",
  "hiw.hero.eyebrow": "ایہ کویں کم کردا اے",
  "hiw.hero.titleA": "چھ نکے مرحلے۔",
  "hiw.hero.titleLead": "اک",
  "hiw.hero.titleAccent": "ودھیرے سمجھدار سیزن۔",
  "hiw.hero.subtitle":
    "اگروپیو اوس طرح کم کردا اے جویں کھیتی پہلوں توں چلدی اے — تسیں بیج بچاؤ، پچھو، کم کرو تے ریکارڈ کرو۔ فرق صرف ایہ اے کہ ہُن ہر مرحلہ اگلا سکھاندا اے۔",
  "hiw.hero.browseFeatures": "خصوصیتاں ݙیکھو",
  "hiw.route.navLabel": "اگروپیو دے موسمی چکر دے چھ مرحلے",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بناؤ",
  "hiw.route.stop2": "پچھو",
  "hiw.route.stop3": "رہنمائی",
  "hiw.route.stop4": "کم کرو",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "اک واری سیٹ اپ کرو",
  "hiw.setup.title": "تواڈا فارم جیندا پروفائل بݨ جاندا اے",
  "hiw.setup.body":
    "چار خانے، اک منٹ توں گھٹ — ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ۔ ایہو سارا فارم اے۔ ایندے بعد ہر جواب ڄاندا اے جو ایہ کتھاں تے کہڑیاں حالتاں وچ اگھدا پئے۔",
  "hiw.setup.point1": "فصل بدلو یا کسے وی ویلے فارم شامل کرو",
  "hiw.setup.point2": "ٹھیکیداراں تے ڈیلراں لئی کئی فارم",
  "hiw.setup.point3": "کجھ تکنیکی نہیں پچھیا جاندا — مٹی دی رپورٹ دی لوڑ نہیں",
  "hiw.setup.mockHeading": "نواں فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بناؤ",
  "hiw.setup.mockFootnote": "اک منٹ توں گھٹ لگدا اے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جیندے وچ ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ بھریا ہویا اے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربیع",
  "hiw.setup.rowSowing": "بیج دی تاریخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "۱۲ ایکڑ",
  "hiw.ask.eyebrow": "جو منگے پچھو",
  "hiw.ask.titleA": "اک سوال ونجے۔",
  "hiw.ask.titleB": "تواڈا سارا فارم جواب ڈیندا اے۔",
  "hiw.ask.body":
    "اکو جیہا سوال وکھرے فارماں تے وکھرا مطلب رکھدا اے۔ ایں کیتے جواب ڈیوݨ توں پہلاں اگروپیو سوال کوں تواڈے فارم بارے ڄاتیا ہویا ہر شے نال ملا تے ݙیدھا اے۔",
  "hiw.ask.pipelineLabel":
    "کسان دے سوال کوں فصل، ضلع، موسم تے تاریخ دے تناظر نال ملا تے ذاتی جواب بنایا جاندا اے",
  "hiw.ask.question": "ہُݨ پانی ڈیونا چاہیدا اے یا تھولا انتظار؟",
  "hiw.ask.checkedAgainst": "اناں شیواں نال ملا تے",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · گٹھیاں پے گئیاں",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "۲۶° • خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخ",
  "hiw.ask.chipValHistory": "یوریا ۹ ڈینہہ پہلاں",
  "hiw.ask.answer":
    "ڈو ڈینہہ رکو — مینہہ دا امکان اے، تے یوریا توں بعد زمین ہلی اے۔ جمعے تائیں ݙیکھ گھننا کافی اے۔",
  "hiw.ask.answerMeta": "ذاتی جواب · گندم، یوریا توں ۹ ڈینہہ بعد",
  "hiw.ask.footnote": "لکھو، بولو یا کال کرو — جواب ہر صورت تواڈے فارم دا اپنا ہوندے",
  "hiw.engine.eyebrow": "جواب دے پچھوں",
  "hiw.engine.title": "چار جانچاں اوس توں پہلاں جدوں تسیں اک لائین ݙیکھو",
  "hiw.engine.body":
    "رہنمائی کوئی سرچ نتیجہ نہیں۔ ایہ چار دروازےآں وچوں لنگھدی اے تاں جو تسیڈے تک جو پجدے او اوہو کھیت لئی، اوہو ہفتے لئی محفوظ ہووے۔",
  "hiw.engine.check1Title": "جانکاری اکٹھی کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم تے فصل دا پڑاؤ بھیجن دے لمحے نال نال اکٹھے تھیندے نیں۔",
  "hiw.engine.check2Title": "ملان دی جانچ",
  "hiw.engine.check2Desc":
    "مشورہ موسم دی پیش گوئی نال پرکھیا جاندا اے — مینہہ وچ بیکار ہووݨ والا سپرے انجن وچوں نکلدا ای نہیں۔",
  "hiw.engine.check3Title": "ذاتی بناؤنا",
  "hiw.engine.check3Desc":
    "تواڈے کھیت دی تاریخ جواب بدل ڈیندی اے — اوہو فصل، وکھری مٹی، وکھرا مشورہ۔",
  "hiw.engine.check4Title": "پچاؤنا",
  "hiw.engine.check4Desc":
    "ول تواڈی زبان وچ صاف قدم بݨ تے آندا اے — سکرین تے، آواز وچ یا فون کال تے۔",
  "hiw.engine.safetyStrong": "جے کجھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تاں اگروپیو اڈیک دا آکھدا اے — دیر نال ملݨ والا جواب بیکار تھیا سپرے یا برباد فصل توں بہتر اے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کرو",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی ڈیونا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل لہاوݨ",
  "hiw.record.row1Time": "اج • سویرے 6:40",
  "hiw.record.row1Label": "پانی ڈیونا درج تھیا",
  "hiw.record.row1Detail": "نہر دا موڑ • ۴۰ منٹ • پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج تھئی",
  "hiw.record.row2Detail": "DAP ۲۰ کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف ڈو ٹیپ — آف لائن وی چلدا اے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جیندے وچ فوری ایکشن چپس تے حالی درج تھئے اندراج نیں",
  "hiw.record.eyebrow": "جیویں جیویں کم کرو، ریکارڈ کردے جاؤ",
  "hiw.record.titleA": "ہُݨ ڈو ٹیپ،",
  "hiw.record.titleB": "سارے سیزن بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت لئی بنائی گئی اے — وڈے بٹن، گھٹ خانے، ٹائپنگ دی لوڑ نہیں۔ ہر اندراج فارم دی یادداشت دا انگ بݨدا اے، ایں کیتے مشورہ وی فصل نال نال تکھا تھیندا ویندے۔",
  "hiw.record.point1": "پانی، کھاداں، بیماری، خرچ، فصل — سب اک ٹائم لائین تے",
  "hiw.record.point2": "پوری طرح آف لائن چلدا اے؛ سگنل آنے تے خودکار سنک تھی جاندا اے",
  "hiw.record.point3": "بینک، خریدار یا بیمے لئی سیزن خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "ایہ فصل لہاوݨ تے ختم نیں تھیندا۔",
  "hiw.loop.titleB": "اوتھوں شروع تھیندا اے۔",
  "hiw.loop.body":
    "پچھو، کم کرو، ریکارڈ کرو — ول ول۔ چکر دی ہر واری اگروپیو تواڈی زمین بارے نواں کجھ سکھاندا اے، تاں اگلا سیزن پچھلے توں اگے شروع تھیوے۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماؤندا اے",
  "hiw.loop.benefit1Desc":
    "پچھلے سیزن دیاں بیماریاں، خوراکاں تے تریخاں ایں سیزن دا پہلا جواب بناندیاں نیں۔",
  "hiw.loop.benefit2Title": "کجھ دہرانا نہیں پیندا",
  "hiw.loop.benefit2Desc":
    "مشاورت ڄاندی اے جو کیہ پہلوں سپرے یا کھاد تھی چکیا اے — دوہری خوراک دا خطرہ نہیں۔",
  "hiw.loop.benefit3Title": "ہر سیزن دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرضے، خریدار، بیمہ یا اگلی فصل دے فیصلے لئی تیار راہندا اے۔",
    "hiw.loop.stepLearn": "سکھو",
  "hiw.loop.stepImprove": "بہتر کرو",
"hiw.loop.diagramLabel": "گول چکر خاکہ: پچھو، کم کرو، ریکارڈ کرو، سکھو، بہتر کرو",
  "hiw.loop.centerSeason": "سیزن",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر سیزن، پچھلے توں بہتر",
};
