import type { CatalogKey } from "./en.ts";

/** پنجابی (شاہ مکھی) — AI-drafted, founder-reviewed copy (plan D4). */
export const pa: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "شروعاتی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ نہیں لبھیا",
  "notFound.body": "تسیں جیہڑا صفہ لبھ رہے او اوہ موجود نہیں جاں تبدیل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے ہوم تے واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کھیتی باڑی لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڈے فارم دے ریکارڈ اک تھاں تے جمع کردا اے — ڈیٹا نوں صاف فیصلیاں وچ بدلدا اے، تہاڈی اپنی بولی وچ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کویں کم کردا اے",
  "home.hero.imageAlt": "کاشکر کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "شاندار",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلا",
  "home.problem.title": "کھیتی باڑی دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان چ کاشکر ریایت، مقامی صلاحاں تے کھلریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان وڈی تے چکنا پیندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، وڈائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹ تے خرچ برباد ہوندی اے۔",
  "home.problem.item2Title": "گُواچا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھلریاں کاپیاں چ رہندا اے۔ پچھلے سال جو کم آیا، اوہدیوں اس سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھلریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کاشکر دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت وڈی تے چکدی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک انٹیلیجنس پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈا تہاڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیڑے مار تے وڈائی دے ویلیے لئی ذاتی صلاحاں — تہاڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تہاڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا جا چکا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، وڈائی — ترتیب والے ریکارڈ چ محفوظ جو ہر سیزن نوں زیادہ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "پوری تریخ، ہمیشہ موجود۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "کئی انجن،",
  "home.features.titleB": "اک ذہین پلیٹ فارم",
  "home.features.subtitle": "تہاڈے اپنے بولاں چ پہلا سوالوں لے کے سارے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی نوں تقویت دیندی اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی کھیتی مشیر",
  "home.features.advisorTopics": "پانی · کھاد · کیمیا تے بیماری · وڈائی",
  "home.features.advisorBadge": "رومن پنجابی",
  "home.features.advisorMockAria": "پیلا پتریاں والی کنک تے اگروپیو مشیر نال نمونہ گل بات",
  "home.features.advisorUserMsg": "میری کنک دے پتے پیالے ہو رے نیں — کراں؟",
  "home.features.advisorReplyTitle": "پیلے پتر — دو عام کارن:",
  "home.features.advisorReplyCause1": "پانی دی تنگی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے ویلیے چ، سویرے 9 وجے توں پہلاں پانی دیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سبھ توں پرانے پتر پہلاں ویکھو؛ لوڑ ہووے تے یوریا پاؤ۔",
  "home.features.advisorReplyFooter": "جے پتریاں ہیٹھ پیلیاں لیکاں دسن، تصویر بھیجو — main بیماری دی جانچ کر دوانگی۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھو یا بولو…",
  "home.features.advisorFooter": "اپنی فصل بارے کجھ وی پچھو — روزمرہ سوالاں جی آیاں نوں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر کم ترتیب نال درج — تے جے صلاح تہاڈی اپنی زمین توں سکھے۔",
  "home.features.record1Activity": "پانی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتریاں دا اسکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "کنک · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · بولی",
  "home.features.languageTitle": "تہاڈی بولی، تہاڈے بول",
  "home.features.languageDesc": "جدوں سوچدے او ادوں بول کے یا لکھ کے کہو — تکنیکی انگریزی دی لوڑ نہیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں جانو رہنمائی",
  "home.features.weatherDesc": "صلاح تسیں تک آن توں پہلاں سچے حالات ویکھدی اے — mینہ توں پہلاں چھڑکاؤ کیتا تے سارا کھاد پانی بن گیا۔",
  "home.features.weatherMockAria": "پنج دن دی پیش گوئی جس چ جمعرات نوں چھڑکاؤ نہ کرن دی صلاح نمایاں اے",
  "home.features.dayMon": "سوموار",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "ویروار",
  "home.features.dayFri": "شکروار",
  "home.features.holdSpray": "چھڑکاؤ روکو",
  "home.features.weatherLegend": "مقامی موسم دی پیش گوئی توں صلاح والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودھدا جا ریا اے — پوریاں صلاحیتاں ویکھو",
  "home.journey.eyebrow": "ایہ کویں کم کردا اے",
  "home.journey.title": "اک سوال سیزن شروع کردا اے",
  "home.journey.subtitle": "تہاڈے پہلے سوالوں توں مکمل، ذہین فارم تریخ تک سادہ راہ۔",
  "home.journey.step1Title": "اپنا فارم پایو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بنان لئی تھاں، فصل تے بنیادی جانکاری بھرو۔",
  "home.journey.step2Title": "اے آئی توں پچھو",
  "home.journey.step2Body": "اپنا سوال اسی بولی چ لکھو یا بولو جس تسیں سبھ توں زیادہ آرام نال بولدے او۔",
  "home.journey.step3Title": "رہنمائی پاؤ",
  "home.journey.step3Body": "اپنی فصل، موسم، تھاں تے فارم تریخ تے بیسیا صلاحاں پاؤ۔",
  "home.journey.step4Title": "کم درج کرو",
  "home.journey.step4Body": "کجھ ٹیپاں چ پانی، کھاد، دوائی جاں بیماری درج کرو۔",
  "home.journey.step5Title": "تریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ اگیاں صلاحاں نوں ہور سمجھدار تے موزوں بناندا اے۔",
  "home.journey.step6Title": "نگرانی جاری رکھو",
  "home.journey.step6Body": "سارے سیزن دوران ریکارڈ ویکھو تے ترقی تے نظر رکھو۔",
  "home.matrix.eyebrow": "پوریاں صلاحیتاں دا مجموعہ",
  "home.matrix.title": "ضروری توں حیرانی والے تک",
  "home.matrix.subtitle": "ہر خاصیت فصل بچاندی اے، خرچ گھٹاندی اے جاں آمدنی ودھاندی اے۔ اس نوں جنتری وانگ پڑھو — ہر پڑھی پچھلی تے بنی اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتاں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی پدھر",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری پچھان",
  "home.matrix.t1f1Body": "متاثرہ پتر دی فوٹو اپلوڈ کرو تے فوری جانچ، شدت تے علاج دیاں صلاحاں پاؤ۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت نگاری",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد نشان زد کرو تے مفت سینٹینل-2 تصویراں توں این ڈی وی آئی بیسی فصل دی صحت ویکھو۔",
  "home.matrix.t1f3Title": "ہوشیار موسمی صلاح",
  "home.matrix.t1f3Body": "مقامی موسم پیش گوئی تہاڈی فصل تے ودھدے پڑاءُ نال مل کے روزانہ کم دی صلاح بن جاندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیش گوئی",
  "home.matrix.t1f4Body": "نزدیکی منڈی دیاں قیمتیں اے آئی رجحاناں نال ویکھو، تے ٹھیک ویلیے تے ویکو۔",
  "home.matrix.tier2Name": "وکھریاں خاصیتاں",
  "home.matrix.tier2Badge": "نمانہ",
  "home.matrix.t2f1Title": "علاقائی بولیاں دا وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولو جاں لکھو — جواب اسی بولی چ سنو جس تسیں بہتر سمجھدے او۔",
  "home.matrix.t2f2Title": "سرکاری سکیم میچر",
  "home.matrix.t2f2Body": "اپنی جانکاری بھرو تے ہر اہل سکیم لبھو — دستاویزاں تے اپلائی لنکاں سمیت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن چ تہاڈی مٹی، موسم، منڈی دی منگ تے بجٹ مطابق سبھ توں ودھ منافع والی فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے اصلی خرچ، پیداوار، آمدنی تے نفع — بریک ایون تے آر او آئی نال۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوال پاؤ، تصویراں شیئر کرو، ساتھی کاشکراں تے تصدیق شدہ ماہراں توں جواب لو۔",
  "home.matrix.tier3Name": "حیرانی والیاں",
  "home.matrix.tier3Badge": "سبھ توں اگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی نگاری",
  "home.matrix.t3f1Body": "سلائیڈر نال ویلا بدلدیاں سیٹلائٹ تصویراں تولو — ودھواءُ، نقصان جاں قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیش گوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے پڑاءُ تے تریخ دے بنیاد تے ممکنہ کیڑا حملے توں پہلاں سوچنا۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر تے کال کرو، سوال بولو، اپنی بولی چ صلاح سنو — اسمارٹ فون دی لوڑ نہیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ اندازہ",
  "home.matrix.t3f4Body": "ٹکاؤ طریقے درج کرو تے رضامندی مارکیٹاں توں کاربن کریڈٹ دا اندازہ لو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت چ آف لائن کم کرے، کنکشن تے سنک ہووے، کمزور نیٹ تے ایس ایم ایس خبر دیوے۔",
  "home.vision.eyebrow": "وژن",
  "home.vision.titleA": "پاکستان لئی بنایا گیا۔",
  "home.vision.titleB": "دنیا لئی تیار۔",
  "home.vision.pkTitle": "پاکستان پہلوں والا ول",
  "home.vision.pkBody": "پہلا ورژن پاکستان دے کھیتاں لئی بنایا گیا اے: مقامی فصلاں، علاقائی بولیاں، اصلی کھیتی باڑی دے طریقاں تے اصلی کھیتاں دیاں حالتاں۔",
  "home.vision.pkPoint1": "مقامی فصلاں تے موسم دی جانکاری",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "اصلی کاشکراں دے فیڈبیک نال بہتر بنایا گیا",
  "home.vision.worldTitle": "دنیا بھر وچ پھیلن دا وژن",
  "home.vision.worldBody": "موزوں ہون لئی بنایا گیا۔جدوں پلیٹ فارم ودھدا اے تے نویں دیساں، بولیاں، فصلاں تے موسماں تک جاندا اے—شروعوں نویں سرے نہ بناوے۔",
  "home.vision.worldPoint1": "دیس مطابق کھیتی باڑی دی جانکاری",
  "home.vision.worldPoint2": "ہور بولیاں تے مقامی فصلاں",
  "home.vision.worldPoint3": "ڈونگھے ڈیٹا جوڑ تے تجزیے",
  "home.users.title1": "انفرادی کاشکر",
  "home.users.desc1": "نکے تے وچولے فارم جنہاں نوں عملی صلاح تے ہر کم دا ترتیب والا ریکارڈ لوڑ اے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہاں نوں ترتیب والی جانکاری، فیصلے دی مدد تے ٹیم والے ریکارڈ لوڑ اے۔",
  "home.users.title3": "ایکو سسٹم ساتھی",
  "home.users.desc3": "ان پٹ سپلائر، کوآپریٹو، بیمہ کمپنیاں تے ایکسٹینشن سروسز جیہڑے ویلے نال پلیٹ فارم نال جڑن گے۔",
  "home.users.tagline": "پہلاں کاشکراں لئی بنایا گیا — ایکو سسٹم نال ودھدا ہویا",
  "home.cta.eyebrow": "شروعاتی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم تے لیاؤ",
  "home.cta.subtitle": "اگروپیو نال بہتر فیصلے کرن والے کاشکراں نال رلت کرو — پاکستان توں شروع، دنیا بھر وچ ودھاءُ۔",
  "home.cta.success": "تسیں لسٹ وچ او۔جدوں تہاڈا علاقہ کھلے گا اساں تہاڈے نال رابطہ کراں گے۔",
  "home.cta.emailLabel": "ای میل پتہ",
  "home.cta.fineprint": "کوئی سپام نہیں۔کدے وی ان سبسکرائب کرو۔",
  "home.footer.tagline": "اے آئی والا فارم انٹیلیجنس پلیٹ فارم۔صلح، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے ریکارڈ — مٹی تے سگنل، نال نال۔",
  "home.footer.pagesHeading": "صفحے",
  "home.footer.pagesNavLabel": "فوٹر صفحے",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس شرطاں",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کرو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔سارے حق محفوظ نیں۔",
  "home.footer.motto": "پاکستان لئی بنیا · دنیا لئی تیار",
  "hiw.meta.title": "ایہ کسے کم کردا اے — اگروپیو",
  "hiw.meta.description":
    "اک منٹ دے فارم پروفائل توں لے کے لگاتار بہتر ہون والے موسمی چکر تک: ویکھو اگروپیو سوالاں، سرگرمیاں تے ریکارڈ نوں ذاتی کھیتی رہنمائی وچ کسے بدلدا اے۔",
  "hiw.hero.eyebrow": "ایہ کسے کم کردا اے",
  "hiw.hero.titleA": "چھ نکے پڑاؤ۔",
  "hiw.hero.titleLead": "اک",
  "hiw.hero.titleAccent": "ودھیرے سمجھدار سیزن۔",
  "hiw.hero.subtitle":
    "اگروپیو اوس طرح کم کردا اے جویں کھیتی باڑی پہلاں توں چلدی اے — تسیں بیج بیجدے او، پچھدے او، کم کردے او تے ریکارڈ کردے او۔ فرق صرف ایہ اے کہ ہُن ہر پڑاؤ اگلے نوں سکھاندا اے۔",
  "hiw.hero.browseFeatures": "خصوصیتاں ویکھو",
  "hiw.route.navLabel": "اگروپیو دے موسمی چکر دے چھ پڑاؤ",
  "hiw.route.stepLabel": "پڑاؤ {n}: {stop}",
  "hiw.route.stop1": "فارم بناؤ",
  "hiw.route.stop2": "پچھو",
  "hiw.route.stop3": "صلاح",
  "hiw.route.stop4": "کم کرو",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "اک واری سیٹ اپ کرو",
  "hiw.setup.title": "تواڈا فارم جیوندا پروفائل بن جاندا اے",
  "hiw.setup.body":
    "چار خانے، اک منٹ توں گھٹ — ضلع، فصل، بیجی دی تاریخ تے زمین دا رقبہ۔ ایہو سارا فارم اے۔ ایتھوں بعد ہر جواب جاندا اے کہ ایہ کتھے تے کن حالتاں وچ اگ رہیا اے۔",
  "hiw.setup.point1": "فصل بدلو یا کسے وی ویلے فارم شامل کرو",
  "hiw.setup.point2": "ٹھیکیداراں تے ڈیلراں لئی کئی فارم",
  "hiw.setup.point3": "کجھ تکنیکی نہیں پچھیا جاندا — مٹی دی رپورٹ دی لوڑ نہیں",
  "hiw.setup.mockHeading": "نیواں فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بناؤ",
  "hiw.setup.mockFootnote": "اک منٹ توں گھٹ لگدا اے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جیدے وچ ضلع، فصل، بیجی دی تاریخ تے زمین دا رقبہ بھریا ہویا اے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "کنک · ربیع",
  "hiw.setup.rowSowing": "بیجی دی تاریخ",
  "hiw.setup.valSowing": "20 نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "12 ایکڑ",
  "hiw.ask.eyebrow": "جو منگے پچھو",
  "hiw.ask.titleA": "اک سوال جاوے۔",
  "hiw.ask.titleB": "تواڈا سارا فارم جواب دیندا اے۔",
  "hiw.ask.body":
    "اکو جیہا سوال وکھرے فارماں تے وکھرے مطلب رکھدا اے۔ اس لئی جواب دین توں پہلاں اگروپیو سوال نوں تواڈے فارم بارے جانکاری ہر شے نال ملا کے ویکھدا اے۔",
  "hiw.ask.pipelineLabel":
    "کاشکر دے سوال نوں فصل، ضلع، موسم تے اتہاس دے تناظر نال ملا کے ذاتی جواب بنایا جاندا اے",
  "hiw.ask.question": "ہُن پانی دیونا چاہیدا اے یا تھوڑا انتظار؟",
  "hiw.ask.checkedAgainst": "ایناں شیواں نال ملا کے",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "کنک · گٹھیاں پے گئیاں",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26° · خشک ہفتہ",
  "hiw.ask.chipHistory": "اتہاس",
  "hiw.ask.chipValHistory": "یوریا 9 دن پہلاں",
  "hiw.ask.answer":
    "دو دن رکو — مینہہ دا امکان اے، تے یوریا توں بعد زمین ہلی اے۔ جمعے تک ویکھ لینا کافی اے۔",
  "hiw.ask.answerMeta": "ذاتی جواب · کنک، یوریا توں 9 دن بعد",
  "hiw.ask.footnote": "لکھو، بولو یا کال کرو — جواب ہر صورت تواڈے فارم دا اپنا ہندا اے",
  "hiw.engine.eyebrow": "جواب دے پچھے",
  "hiw.engine.title": "چار جانچاں اوس توں پہلاں جدوں تساں اک لائن ویکھو",
  "hiw.engine.body":
    "صلاح کوئی سرچ نتیجہ نہیں۔ ایہ چار دروازےآں وچوں لنگھدی اے تاں جو تسیں تک جو پہنچے او اسے کھیت لئی، اسے ہفتے لئی محفوظ ہووے۔",
  "hiw.engine.check1Title": "جانکاری اکٹھی کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم تے فصل دا پڑاؤ بھیجن دے لمحے نال نال اکٹھے کیتے جاندے نیں۔",
  "hiw.engine.check2Title": "ملان دی جانچ",
  "hiw.engine.check2Desc":
    "مشورے نوں موسم دی پیش گوئی نال پرکھیا جاندا اے — مینہہ وچ بیکار ہون والا سپرے انجن وچوں نکلدا ای نہیں۔",
  "hiw.engine.check3Title": "ذاتی بنانا",
  "hiw.engine.check3Desc":
    "تواڈے کھیت دی اتہاس جواب بدل دندی اے — اوہی فصل، وکھری مٹی، وکھرا مشورہ۔",
  "hiw.engine.check4Title": "پہنچانا",
  "hiw.engine.check4Desc":
    "فیر ایہ تواڈی بولی وچ صاف قدم بݨ کے آؤندا اے — سکرین تے، آواز وچ یا فون کال تے۔",
  "hiw.engine.safetyStrong": "جے کجھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تاں اگروپیو اڈیک دا کہندا اے — دیر نال ملن والا جواب بیکار ہوئے سپرے یا تباہ فصل توں بہتر اے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کرو",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی دیونا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل وڈنا",
  "hiw.record.row1Time": "اج · سویرے 6:40",
  "hiw.record.row1Label": "پانی دیونا درج ہویا",
  "hiw.record.row1Detail": "نہر دا موڑ · 40 منٹ · پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج ہوئی",
  "hiw.record.row2Detail": "DAP 20 کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف دو ٹیپ — آف لائن وی چلدا اے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جیدے وچ فوری ایکشن چپس تے حال وچ درج اندراج نيں",
  "hiw.record.eyebrow": "جیویں جیویں کم کرو، ریکارڈ کردے جاؤ",
  "hiw.record.titleA": "ہُن دو ٹیپ،",
  "hiw.record.titleB": "سارے سیزن بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت لئی بنائی گئی اے — وڈے بٹن، گھٹ خانے، ٹائپنگ دی لوڑ نہیں۔ ہر اندراج فارم دی یادداشت دا انگ بݨدا اے، تاں مشورہ وی فصل نال نال تکھا ہوندا جاندا اے۔",
  "hiw.record.point1": "پانی، کھاداں، بیماری، خرچ، فصل — سب اک ٹائم لائن تے",
  "hiw.record.point2": "پوری طرح آف لائن چلدا اے؛ سگنل آن تے خود سنک ہو جاندا اے",
  "hiw.record.point3": "بینک، خریدار یا بیمے لئی سیزن خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "ایہ فصل وڈن تے ختم نہیں ہوندا۔",
  "hiw.loop.titleB": "اوتھوں شروع ہوندا اے۔",
  "hiw.loop.body":
    "پچھو، کم کرو، ریکارڈ کرو — دہراؤ۔ چکر دی ہر واری اگروپیو نوں تواڈی زمین بارے نواں کجھ سکھاندی اے، تاں اگلا سیزن پچھلے توں اگے شروع ہووے۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماؤندا اے",
  "hiw.loop.benefit1Desc":
    "پچھلے سیزن دیاں بیماریاں، خوراکاں تے تریخاں اس سیزن دا پہلا جواب بناندیاں نیں۔",
  "hiw.loop.benefit2Title": "کجھ دہرانا نہیں پیندا",
  "hiw.loop.benefit2Desc":
    "مشاورت جاندی اے کہ کیہ پہلاں سپرے یا کھاد ہو چکیا اے — دوہری خوراک دا خطرہ نہیں۔",
  "hiw.loop.benefit3Title": "ہر سیزن دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف اتہاس قرضے، خریدار، بیمہ یا اگلی فصل دے فیصلے لئی تیار رہندا اے۔",
    "hiw.loop.stepLearn": "سکھو",
  "hiw.loop.stepImprove": "بہتر کرو",
  "hiw.loop.diagramLabel": "گول چکر خاکہ: پچھو، کم کرو، ریکارڈ کرو، سکھو، بہتر کرو",
  "hiw.loop.centerSeason": "سیزن",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر سیزن، پچھلے توں بہتر",
  "feat.meta.title": "خصوصیات — اگروپیو",
  "feat.meta.description": "اگروپیو دی ہر خصوصیت ویکھو: اے آئی فصل ڈاکٹر، سیٹلائٹ NDVI نگرانی، منڈی بھاء پیش گوئی، مقامی بولیاں وچ آوازی صلاح، آف لائن رسائی تے ایس ایم ایس الرٹس، تے ہور بوہت کجھ۔",
  "feat.hero.eyebrow": "خصوصیات",
  "feat.hero.titleLead": "تواڈے موسم دی ہر",
  "feat.hero.titleAccent": "لوڑ پوری",
  "feat.hero.subtitle": "چوداں خصوصیات اکٹھیاں کم کردیاں نیں — پتے سکین کردیاں نیں، خلا توں کھیت ویکھدیاں نیں، منڈی پڑھدیاں نیں تے تہاڈی زبان بولدیاں نیں۔ ویکھو ہر اک تواڈے فارم لئی کی کردی اے۔",
  "feat.hero.ctaPrimary": "مُڈھلی رسائی حاصل کرو",
  "feat.hero.ctaSecondary": "ایہ کیویں چلدا اے ویکھو",
  "feat.hero.builtFor": "پاکستان لئی بنایا گیا",
  "feat.hero.productOf": "Aplinode دی پیداوار",
  "feat.hero.tile1Label": "پتہ سکین",
  "feat.hero.tile1Value": "94% ٹھیک",
  "feat.hero.tile2Label": "منڈی کنک",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کھیت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کیڑے دا خطرہ",
  "feat.hero.tile4Value": "گھٹ · 7 دن",
  "feat.hero.voiceReady": "آوازی صلاح تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "ایس ایم ایس الرٹ · آف لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — سپرے روکو",
  "feat.intel.eyebrow": "فصل دی سمجھ",
  "feat.intel.heading": "مسلے نقصان توں پہلاں ویکھو",
  "feat.intel.sub": "بیماری، کیڑے، موسم تے فصل دا انتخاب — چار فیصلے جو فصل طے کردے نیں، ہر اک اپنے انجن نال۔",
  "feat.intel.included": "شامل اے",
  "feat.intel.doctorCode": "F·01 · وژن",
  "feat.intel.doctorTitle": "اے آئی فصل ڈاکٹر",
  "feat.intel.doctorDesc": "متاثرہ پتے دی تصویر کڈھو تے سیکنڈاں وچ بیماری دا ناں، شدت تے علاج دا پلان پاؤ۔",
  "feat.intel.doctorMock": "پتہ سکین نتیجہ جس وچ پیلا زنگ زیادہ یقین نال تشخیص",
  "feat.intel.diseaseName": "پیلا زنگ",
  "feat.intel.matchScore": "94% میل",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درمیانہ",
  "feat.intel.pestCode": "F·02 · پیش گوئی",
  "feat.intel.pestTitle": "کیڑیاں دے حملے دی الرٹ",
  "feat.intel.pestDesc": "موسم تے فصل دا پڑاؤ خطرے دے ماڈل نوں کھاندا اے جو حملے توں دن پہلاں خبردار کر دیندا اے۔",
  "feat.intel.pestMock": "سات دن دے کیڑے خطرے دے بار جو چھیویں دن اچائی ول جاندا اے",
  "feat.intel.pestAlert": "ہفتہ · ٹڈی دل دا خطرہ 74% — نویں کنک نوں محفوظ بناؤ",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم مطابق صلاحاں",
  "feat.intel.weatherDesc": "مقامی پیش گوئیاں تواڈی فصل تے نشونما دے پڑاؤ نال ملدیاں نیں — صلاح صاف ہدایت بن کے آندی اے، کچھ ڈیٹا نہیں۔",
  "feat.intel.weatherMock": "مثالی موسمی صلاح جو بارش توں پہلاں آبپاشی وچ تاخیر دا کہندی اے",
  "feat.intel.delayIrrigation": "اج پانی دین وچ تاخیر کرو",
  "feat.intel.rainNote": "شام 3 وجے بارش دا امکان — پہلاں اسمان نوں کھیت سیراب کرن دیو۔",
  "feat.intel.waterSaved": "پانی دی بچت",
  "feat.intel.cropCode": "F·04 · پلاننگ",
  "feat.intel.cropTitle": "فصل دی سفارش",
  "feat.intel.cropDesc": "مٹی، موسم، منگ تے تہاڈا بجٹ اکٹھے جانچے جاندے نیں — اوہ بجو جو ایس موسم منافع دیوے۔",
  "feat.intel.cropMock": "درجہ بند فصل سفارشات جنہاں وچ کنک اتے",
  "feat.intel.crop1": "کنک",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کھیت تے منڈی دی سمجھ",
  "feat.field.headingA": "تواڈی زمین خلا توں نپی جاندی اے۔",
  "feat.field.headingB": "تواڈی فصل ڈیٹا نال پرکی جاندی اے۔",
  "feat.field.sub": "ہر ایکڑ تے سیٹلائٹ دے نظارے تے قریبی ہر منڈی دا جائزہ — تاکہ نشونما تے ویچن دونوں صحیح وقت تے ہون۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کھیت نگرانی",
  "feat.field.ndviDesc": "اپنی حد اک واری نشان زد کرو؛ ہر صاف سیٹلائٹ پاس تے صحت دے زون اپ ڈیٹ ہوندے نیں — کمزور حصے اکھ توں پہلاں سامنے آؤندے نیں۔",
  "feat.field.ndviMock": "کھیت صحت گرڈ جس وچ گہرا سبز مضبوط فصل نشونما دکھاندا اے",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈی",
  "feat.field.priceTitle": "منڈی بھاء پیش گوئی",
  "feat.field.priceDesc": "قریبی منڈیاں دے موجودہ ریٹ تے رجحان پیش گوئی — اودوں ویچو جدوں گراف کہے، خریدار جدوں کہے نہیں۔",
  "feat.field.priceMock": "کنک بھاء رجحان اٹھ ہفتیاں وچ اچائی ول، رکے رہن دی سفارش نال",
  "feat.field.wheatTrend": "کنک · 8 ہفتے",
  "feat.field.holdStock": "↑ 12% — مال رکھو",
  "feat.field.financeCode": "F·07 · مالیات",
  "feat.field.financeTitle": "نفع نقصان ٹریک",
  "feat.field.financeDesc": "ہر روپیا آن نال جان تک، پورا موسم — منڈی یا بینک جان توں پہلاں بریک ایون تے آر او آئی تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ جس وچ ان پٹ، مزدوری، آبپاشی تے آمدنی",
  "feat.field.rowInputs": "ان پٹ",
  "feat.field.rowLabour": "مزدوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (اندازا)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سب لئی رسائی",
  "feat.voice.headingA": "اسمارٹ فون نہیں؟",
  "feat.voice.headingB": "انگریزی نہیں؟ پھر وی شامل۔",
  "feat.voice.sub": "وڈی توں ودھیا صلاح بے کار اے جے اوہ کسان تک پہنچے ہی نہیں۔ ہر خصوصیت فون کال جواب دیندی اے، آواز سندی اے تے سگنل ختم علاقے وچ وی چلدی اے۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "اپنا سوال بولو",
  "feat.voice.speakMock": "رومن پنجابی وچ صلاح نال آوازی گل بات",
  "feat.voice.chatUser": "میری فصل دے پتیاں تے دھبے نیں",
  "feat.voice.chatAdvisor": "دھباں دی تصویر بھیجو — میں ہُنے تشخیص کردا واں۔",
  "feat.voice.inputPlaceholder": "بول کے پچھو…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کرو",
  "feat.voice.callMock": "اگروپیو وائس اسسٹنٹ نال ٹول فری کال دی نقل",
  "feat.voice.greetingLine": "اگروپیو وچ تہاڈا جی آیاں نوں",
  "feat.voice.heardLine": "آواز سمجھ لئی — جواب تیار اے",
  "feat.voice.callEnded": "کال ختم · خلاصہ محفوظ",
  "feat.voice.anyPhone": "کسے وی فون تے · انٹرنیٹ دی لوڑ نہیں",
  "feat.voice.offlineCode": "F·10 · آف لائن + ایس ایم ایس",
  "feat.voice.offlineTitle": "سگنل ختم علاقے وی نہیں روکدے",
  "feat.voice.offlineDesc": "صلاحاں، ریکارڈ تے کیلکولیٹر بنا سگنل کم کردے رہندے نیں؛ نیٹ ورک واپسی تے سب سنک ہو جاندا اے تے اہم الرٹس ایس ایم ایس نال آؤندے نیں۔",
  "feat.voice.networkStatus": "نیٹ ورک حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 ریکارڈ قطار وچ",
  "feat.voice.smsStamp": "ایس ایم ایس · 07:42",
  "feat.voice.smsMsg": "موسم الرٹ: بارش شام 3 وجے — سپرے دا وقت بدل لو۔",
  "feat.manage.eyebrow": "سنبھالو تے ودھاؤ",
  "feat.manage.headingA": "صلاح شروعات اے۔",
  "feat.manage.headingB": "باقی سب ریکارڈ تے چلدا اے۔",
  "feat.manage.sub": "تریخ، سبسڈی، پائیداری تے کساناں دی کمیونٹی — خاموش خصوصیات جو ہر موسم جمع ہوندیاں نیں۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈ",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی توں کٹائی تک، سب اک ٹائم لائن تے جسنوں صلاح جواب توں پہلاں پڑھدی اے۔",
  "feat.manage.timelineMock": "اگست دی فارم سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "نہر دی واری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریا پایا گیا",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "پتہ سکین",
  "feat.manage.tl3Detail": "صاف · کوئی بیماری نہیں",
  "feat.manage.schemeCode": "F·12 · سکیمز",
  "feat.manage.schemeTitle": "سبسڈی تے سکیم لبھو",
  "feat.manage.schemeDesc": "سرکاری رقم جس دے تسیں پہلاں توں اہل ہو — ملی، سمجھائی تے اک ٹیپ درخواست لئی جوڑی جاندی اے۔",
  "feat.manage.checklistMock": "اہلیت چیک لسٹ جس وچ چار وچوں تن شرطاں مکمل",
  "feat.manage.check1": "زمین دی تصدیق ہو گئی",
  "feat.manage.check2": "فصل دا موسم مطابقت رکھدا اے",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بینک اکاؤنٹ جڑیا",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پائیداری",
  "feat.manage.carbonTitle": "سبھے طریقےآں دے انعام",
  "feat.manage.carbonDesc": "نامیاتی تے گھٹ ہل دے طریقے درج کرو؛ سیٹلائٹ سبز احاطہ تصدیق کردا اے تے کاربن کریڈٹ دی قدر دا اندازہ لگدا اے۔",
  "feat.manage.carbonMock": "کاربن خلاصہ جس وچ قبضہ شدہ ٹن تے سالانہ تخمینی قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ قدر / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کسان فورم + ماہر",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کرو، ان کساناں توں جواب پاؤ جنہاں نے خود سامنا کیتا — تصدیق شدہ ماہر صحیح حل نشان زد کردے نیں۔",
  "feat.manage.threadMock": "کمیونٹی بحث جس وچ ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadQuestion": "کپاس وچ سفید مکھی دا ودھیا علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "نیم دے تیل دا سپرے، شام نوں — دو واری، 5 دن دے وقفے تے۔",
  "vp.meta.title": "ਵਿਜ਼ਨ — ਅਗਰੋਪਿਓ",
  "vp.meta.description": "ਅਗਰੋਪਿਓ ਦਾ ਵਿਜ਼ਨ: ਹਰ ਕਿਸਾਨ ਦੀ ਜੇਬ ਵਿੱਚ ਹੁਸ਼ਿਆਰ ਖੇਤੀ ਸਲਾਹ — ਪਾਕਿਸਤਾਨ ਤੋਂ ਸ਼ੁਰੂਆਤ, ਪੰਜ ਵਿਸ਼ਵਾਸ, ਤਿੰਨ ਕਿਤਾਸੇ ਅਤੇ ਉਹ ਵਾਅਦੇ ਜਿਨ੍ਹਾਂ ਨਾਲ ਕੋਈ ਸਮਝੌਤਾ ਨਹੀਂ।",
  "vp.hero.eyebrow": "ਸਾਡਾ ਵਿਜ਼ਨ",
  "vp.hero.titleLead": "ਇੱਕ ਭਰੋਸੇਯੋਗ ਸਲਾਹਕਾਰ",
  "vp.hero.titleAccent": "ਹਰ ਕਿਸਾਨ ਦੀ ਜੇਬ ਵਿੱਚ।",
  "vp.hero.sub": "ਹੁਸ਼ਿਆਰ ਸਲਾਹ ਦਾ ਭਰੋਸਾ ਦੌਲਤ, ਪੜ੍ਹਾਈ ਜਾਂ ਬੋਲੀ ਉੱਤੇ ਨਹੀਂ ਹੋਣਾ ਚਾਹੀਦਾ। ਅਗਰੋਪਿਓ ਇਸ ਲਈ ਹੈ ਤਾਂ ਜੋ ਹਰ ਕਿਸਾਨ — ਕਿਸੇ ਵੀ ਫ਼ੋਨ ਉੱਤੇ, ਕਿਸੇ ਵੀ ਪਿੰਡ ਵਿੱਚ — ਉਸੇ ਹੌਸਲੇ ਨਾਲ ਖੇਤੀ ਕਰੇ ਜਿਵੇਂ ਕੋਈ ਮਾਹਰ ਨਾਲ ਖੜ੍ਹਾ ਹੋਵੇ।",
  "vp.hero.tagStart": "ਲੋੜ ਸਭ ਤੋਂ ਪਹਿਲਾਂ",
  "vp.hero.tagThen": "ਫਿਰ ਸਾਰੀ ਦੁਨੀਆ",
  "vp.hero.ctaLink": "ਵੇਖੋ ਅਸੀਂ ਕੀ ਬਣਾਇਆ",
  "vp.beliefs.eyebrow": "ਸਾਡੇ ਵਿਸ਼ਵਾਸ",
  "vp.beliefs.heading": "ਪੰਜ ਵਿਸ਼ਵਾਸ ਹਰ ਫ਼ੈਸਲੇ ਨੂੰ ਰੂਪ ਦਿੰਦੇ ਹਨ",
  "vp.beliefs.b1Title": "ਵਾਧਾ",
  "vp.beliefs.b1Desc": "ਜੀਵਤ ਫ਼ਸਲਾਂ, ਸਿਹਤਮੰਦ ਜ਼ਮੀਨ, ਖੁਸ਼ਹਾਲ ਕਿਸਾਨ।",
  "vp.beliefs.b2Title": "ਹੁਸ਼ਿਆਰੀ",
  "vp.beliefs.b2Desc": "ਸਥਾਨਕ ਮੌਸਮ, ਇਤਿਹਾਸ ਅਤੇ ਫ਼ਸਲ ਵਿਗਿਆਨ ਉੱਤੇ ਅਧਾਰਤ ਏਆਈ।",
  "vp.beliefs.b3Title": "ਪਹੁੰਚ",
  "vp.beliefs.b3Desc": "ਹਰ ਕਿਸਾਨ ਦੀ ਆਪਣੀ ਬੋਲੀ ਅਤੇ ਆਪਣੇ ਢੰਗ ਵਿੱਚ ਸਲਾਹ।",
  "vp.beliefs.b4Title": "ਭਰੋਸਾ",
  "vp.beliefs.b4Desc": "ਅਮਲੀ, ਸਮੇਂ ਸਿਰ ਸਲਾਹ ਜੋ ਰੋਟੀ ਦੀ ਰਾਖੀ ਕਰੇ।",
  "vp.beliefs.b5Title": "ਭਵਿੱਖ",
  "vp.beliefs.b5Desc": "ਪਰੰਪਰਾ ਦਾ ਸਤਿਕਾਰ ਕਰਨ ਵਾਲੀ ਵਧਣਯੋਗ ਤਕਨਾਲੋਜੀ।",
  "vp.horizons.eyebrow": "ਅੱਗੇ ਦਾ ਰਾਹ",
  "vp.horizons.heading": "ਤਿੰਨ ਕਿਤਾਸੇ, ਇੱਕ ਦਿਸ਼ਾ",
  "vp.horizons.h1Tag": "ਕਿਤਾਸ 01",
  "vp.horizons.h1Phase": "ਹੁਣ",
  "vp.horizons.h1Status": "ਖੇਤਾਂ ਵਿੱਚ",
  "vp.horizons.h1Body": "ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਪਾਕਿਸਤਾਨ। ਮੁੱਖ ਸਲਾਹਕਾਰ, ਡਿਜੀਟਲ ਫ਼ਾਰਮ ਰਿਕਾਰਡ, ਮੌਸਮ ਅਨੁਸਾਰ ਸਲਾਹ ਅਤੇ ਛੇ ਖੇਤਰੀ ਬੋਲੀਆਂ — ਹੋਰ ਕਿਸੇ ਚੀਜ਼ ਤੋਂ ਪਹਿਲਾਂ ਸੱਚੇ ਕਿਸਾਨਾਂ ਦੇ ਸੁਝਾਅ ਨਾਲ ਪੱਕੀਆਂ।",
  "vp.horizons.h1P1": "ਮੁੱਖ ਸਲਾਹਕਾਰ + ਰਿਕਾਰਡ",
  "vp.horizons.h1P2": "ਛੇ ਬੋਲੀਆਂ",
  "vp.horizons.h1P3": "ਸੱਚੇ ਕਿਸਾਨਾਂ ਤੋਂ ਸੁਧਾਰ",
  "vp.horizons.h2Tag": "ਕਿਤਾਸ 02",
  "vp.horizons.h2Phase": "ਅਗਲਾ",
  "vp.horizons.h2Status": "ਵਿਸਥਾਰ",
  "vp.horizons.h2Body": "ਘਰ ਵਿੱਚ ਡੂੰਘਾਈ ਅਤੇ ਫੈਲਾਅ — ਪਾਕਿਸਤਾਨ ਭਰ ਵਿੱਚ ਹੋਰ ਫ਼ਸਲਾਂ ਅਤੇ ਇਲਾਕੇ, ਖੇਤੀ ਡਾਟਾ ਸਰੋਤਾਂ ਨਾਲ ਮਜ਼ਬੂਤ ਜੋੜ, ਅਤੇ ਅਜਿਹੇ ਵਿਸ਼ਲੇਸ਼ਣ ਜੋ ਹਰ ਸਿਫ਼ਾਰਿਸ਼ ਨੂੰ ਹੋਰ ਨਿੱਜੀ ਬਣਾਉਂਦੇ ਹਨ।",
  "vp.horizons.h2P1": "ਹੋਰ ਫ਼ਸਲਾਂ ਤੇ ਇਲਾਕੇ",
  "vp.horizons.h2P2": "ਡਾਟਾ ਜੋੜ",
  "vp.horizons.h2P3": "ਉੱਚੇ ਵਿਸ਼ਲੇਸ਼ਣ",
  "vp.horizons.h3Tag": "ਕਿਤਾਸ 03",
  "vp.horizons.h3Phase": "ਬਾਅਦ ਵਿੱਚ",
  "vp.horizons.h3Status": "ਦੁਨੀਆ ਭਰ",
  "vp.horizons.h3Body": "ਪਲੇਟਫ਼ਾਰਮ ਨਵੇਂ ਦੇਸ਼ਾਂ, ਮੌਸਮਾਂ, ਫ਼ਸਲਾਂ, ਬੋਲੀਆਂ ਅਤੇ ਢੰਗਾਂ ਦੇ ਮੁਤਾਬਕ ਢਲ ਜਾਂਦਾ ਹੈ — ਦੁਨੀਆ ਭਰ ਵਿੱਚ ਢਲਣਯੋਗ ਖੇਤੀ ਹੁਸ਼ਿਆਰੀ, ਜ਼ੀਰੋ ਤੋਂ ਸ਼ੁਰੂ ਕੀਤੇ ਬਿਨਾਂ।",
  "vp.horizons.h3P1": "ਨਵੇਂ ਦੇਸ਼",
  "vp.horizons.h3P2": "ਨਵੀਆਂ ਬੋਲੀਆਂ ਤੇ ਮੌਸਮ",
  "vp.horizons.h3P3": "ਦੁਨੀਆਵੀ ਪਲੇਟਫ਼ਾਰਮ",
  "vp.outcomes.eyebrow": "ਕਾਮਯਾਬੀ ਦੀ ਸ਼ਕਲ",
  "vp.outcomes.heading": "ਚਾਰ ਨਤੀਜੇ ਜਿਨ੍ਹਾਂ ਉੱਤੇ ਅਸੀਂ ਆਪ ਨੂੰ ਤੋਲਦੇ ਹਾਂ",
  "vp.outcomes.sub": "ਵਿਜ਼ਨ ਐਪ ਨਹੀਂ — ਫ਼ਾਰਮ ਉੱਤੇ ਬਦਲਣ ਵਾਲੀ ਹਾਲਤ ਹੈ। ਹਰ ਚੀਜ਼ ਇਨ੍ਹਾਂ ਚਾਰ ਨਤੀਜਿਆਂ ਦੇ ਮੁਕਾਬਲੇ ਜਾਰੀ ਹੁੰਦੀ ਹੈ।",
  "vp.outcomes.o1Title": "ਵਧੀਆ ਫ਼ੈਸਲੇ",
  "vp.outcomes.o1Desc": "ਹਰ ਚੋਣ — ਪਾਣੀ, ਇਨਪੁਟ, ਸਮਾਂ — ਆਦਤ ਦੀ ਥਾਂ ਡਾਟੇ ਉੱਤੇ।",
  "vp.outcomes.o2Title": "ਵੱਧ ਝਾੜ",
  "vp.outcomes.o2Desc": "ਸਿਹਤਮੰਦ ਫ਼ਸਲਾਂ, ਸਮੇਂ ਸਿਰ ਇਨਪੁਟ, ਅਤੇ ਠੀਕ ਸਮੇਂ ਵੱਢਿਆ ਝਾੜ।",
  "vp.outcomes.o3Title": "ਘੱਟ ਬਚਣਯੋਗ ਨੁਕਸਾਨ",
  "vp.outcomes.o3Desc": "ਬਿਮਾਰੀ, ਕੀੜੇ ਅਤੇ ਮੌਸਮ ਸਮੇਂ ਤੇ ਫੜੇ — ਫ਼ਸਲ ਗੁਆਉਣ ਤੋਂ ਪਹਿਲਾਂ।",
  "vp.outcomes.o4Title": "ਫ਼ਾਰਮ ਕਾਰੋਬਾਰ ਵਾਂਗ",
  "vp.outcomes.o4Desc": "ਵਿਵਸਥਿਤ ਰਿਕਾਰਡ ਅਤੇ ਸੀਜ਼ਨ ਹੁਸ਼ਿਆਰੀ ਜਿਸ ਨੂੰ ਬੈਂਕ ਤੇ ਖ਼ਰੀਦਦਾਰ ਮੰਨਣ।",
  "vp.principles.eyebrow": "ਸਮਝੌਤਾ ਨਹੀਂ",
  "vp.principles.heading": "ਉਹ ਵਾਅਦੇ ਜਿਨ੍ਹਾਂ ਉੱਤੇ ਅਸੀਂ ਬਣਾਉਂਦੇ ਹਾਂ",
  "vp.principles.sub": "ਵਿਜ਼ਨ ਵੇਰਵਿਆਂ ਵਿੱਚ ਅਸਫ਼ਲ ਹੁੰਦਾ ਹੈ। ਇਹ ਵਾਅਦੇ ਹਰ ਵਿਸ਼ੇਸ਼ਤਾ, ਹਰ ਪੰਨੇ, ਹਰ ਰੀਲਿਜ਼ ਉੱਤੇ ਲਾਗੂ ਹਨ — ਅੱਜ ਤੋਂ।",
  "vp.principles.c1Title": "ਕਿਸਾਨ ਦਾ ਫ਼ਾਇਦਾ ਪਹਿਲਾਂ",
  "vp.principles.c1Desc": "ਹਰ ਵਿਸ਼ੇਸ਼ਤਾ ਖੇਤ ਦੀ ਲੋੜ ਤੋਂ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ — ਤਕਨਾਲੋਜੀ ਤੋਂ ਕਦੇ ਨਹੀਂ।",
  "vp.principles.c2Title": "ਬੋਲੀ ਪਹਿਲਾਂ",
  "vp.principles.c2Desc": "ਹਰ ਸਕਰੀਨ ਅਤੇ ਹਰ ਜਵਾਬ ਕਿਸਾਨ ਦੀ ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਪਹੁੰਚਦਾ ਹੈ।",
  "vp.principles.c3Title": "ਧੁੱਪ ਵਿੱਚ ਪੜ੍ਹਨਯੋਗ",
  "vp.principles.c3Desc": "ਗਹਿਰਾ ਕੰਟ੍ਰਾਸਟ ਦੁਪਹਿਰ ਦੀ ਧੁੱਪ ਲਈ, ਸਿਰਫ਼ ਦਫ਼ਤਰ ਲਈ ਨਹੀਂ।",
  "vp.principles.c4Title": "ਸਾਦੇ ਸ਼ਬਦ",
  "vp.principles.c4Desc": "ਓਨੇ ਸਾਦੇ ਕਿ ਇੱਕ ਗੁਆਂਢੀ ਦੂਜੇ ਨੂੰ ਸਮਝਾ ਸਕੇ।",
  "vp.principles.c5Title": "ਪਹਿਲਾਂ ਫ਼ੋਨ",
  "vp.principles.c5Desc": "ਮੋਬਾਈਲ ਪਹਿਲਾਂ, ਵੱਡੇ ਟੱਚ ਟਾਰਗਟ — ਹੁਣ ਖੇਤੀ ਫ਼ੋਨ ਉੱਤੇ ਹੀ ਚੱਲਦੀ ਹੈ।",
  "vp.principles.c6Title": "ਢੰਗ ਵਿੱਚ ਕੁਦਰਤੀ",
  "vp.principles.c6Desc": "ਹਰਕਤ ਅਤੇ ਢਾਂਚਾ ਜੋ ਨਿੱਤ ਜਿਹਾ ਲੱਗੇ — ਵਾਧਾ, ਮਸ਼ੀਨ ਕਦੇ ਨਹੀਂ।",
  "vp.principles.motto": "ਮਿੱਟੀ ਤੇ ਸਿਗਨਲ — ਨਾਲ ਨਾਲ",
  "wy.meta.title": "اگروپیو کیوں — اے آئی والی فارم ذہانت",
  "wy.meta.description": "کاشتکاری دے فیصلے اندازے تے نہیں چھڈے جا سکدے۔ ویکھو اگروپیو کیویں اے آئی مشیر، فارم ریکارڈ، موسم جانن والی رہنمائی تے مقامی بولیاں اک پاکستان اول پلیٹ فارم تے اکٹھیاں کردا اے۔",
  "wy.hero.eyebrow": "اگروپیو کیوں",
  "wy.hero.titleLead": "جتھے مٹی ملدی اے",
  "wy.hero.titleAccent": "سگنل نال",
  "wy.hero.sub": "کاشتکاری دے فیصلے اندازے تے نہیں چھڈے جاندے۔ اگروپیو اک ای پلیٹ فارم وچ اے آئی مشیر، تہاڈے فارم دا ریکارڈ، موسم جانن والی رہنمائی تے تہاڈی اپنی بولی دیندا اے — تاں جو ہر فیصلہ تہاڈی زمین دی حقیقت اتے کھڑا ہووے۔",
  "wy.hero.ctaPrimary": "جلدی رسائی حاصل کرو",
  "wy.hero.ctaSecondary": "پلیٹ فارم ویکھو",
  "wy.hero.tagStart": "پاکستان لئی بنایا گیا",
  "wy.hero.tagThen": "Aplinode دی پروڈکٹ",
  "wy.hero.svgLabel": "کھیت اتے لہردیاں وَلّ ورگیاں خم دار لکیراں",
  "wy.origin.eyebrow": "اسیں ایہ کیوں بنایا",
  "wy.origin.heading": "وڈے فیصلے صرف اندازے اتے نہیں ٹکنے چاہیدے",
  "wy.origin.sub": "اگروپیو دی شروعات اک سادے مشاہدے توں ہوئی: کسان دا سیزل چند فیصلیاں نال طے ہندا اے، تے ہر فیصلہ اصلی عقل دا حق‌دار اے۔",
  "wy.origin.g1Title": "ویلے دا اندازہ",
  "wy.origin.g1Desc": "پانی دینا، کھاد پاؤنا، بیج بونا، فصل کٹنا — سیزل دے فیصلے کرن والے لمحے اج وی عادت تے امید توں چنے جاندے نیں۔",
  "wy.origin.g2Title": "اتہاس مِٹ جاندا اے",
  "wy.origin.g2Desc": "کدوں سپرے ہوئی، کدوں کھیت سیراب ہوئیا، پچھلے سال کیہڑی بیماری لگی — کجھ وی لکھیا نہیں جاندا، اس لئی اس توں کجھ وی سکھیا نہیں جا سکدا۔",
  "wy.origin.g3Title": "مشورے کھلرے ہوئے نیں",
  "wy.origin.g3Desc": "گوانڈی، دکاندار تے ویڈیوز ہر اک جواب دیندے نیں — پر کسے کول تہاڈی فصل، تہاڈی مٹی یا اس ہفتے دے موسم دی اصلی جانکاری نہیں ہوندی۔",
  "wy.origin.banner": "اندازے دی قیمت کٹائی دے دن چکائی پیندی اے",
  "wy.diff.eyebrow": "ایہنوں وکھرا کی بناندا اے",
  "wy.diff.heading1": "محض اک ہور مشورے والی ایپ نہیں۔",
  "wy.diff.heading2": "اک فارم عقل والا پلیٹ فارم اے۔",
  "wy.diff.sub": "زیادہ تر ٹول صرف سوالاں دے جواب دیندے نیں۔ اگروپیو تہاڈا فارم سکھدا اے — تے تہاڈے درج کیتے ہر کم نال ہور کارآمد ہوندا جاندا اے۔",
  "wy.diff.personalTitle": "ذاتی قسم دا، عام نہیں",
  "wy.diff.personalDesc": "تجویزاں تہاڈی فصل، تہاڈے مقام، موجودہ موسم تے تہاڈے فارم دی اپنی تاریخ توں بندیاں نیں — کدے وی سارےآں لئی اکو نسخہ نہیں۔",
  "wy.diff.chip1": "تہاڈی فصل",
  "wy.diff.chip2": "تہاڈا ضلع",
  "wy.diff.chip3": "اس ہفتے دا موسم",
  "wy.diff.chip4": "تہاڈا پچھلا سیزل",
  "wy.diff.langTitle": "تہاڈی بولی بولدا اے",
  "wy.diff.langDesc": "جیویں تسیں اصلی بولدے او اویں پچھو تے سمجھو — کوئی مشکل انگریزی لوڑ نہیں۔",
  "wy.diff.memoryTitle": "ہر فارم دی یادداشت",
  "wy.diff.memoryDesc": "پانی، ان پٹ، بیماری، خرچ، کٹائی — ہر کم منظم ریکارڈ وچ محفوظ، تاں جو ہر سیزل پچھلے توں بہتر شروع کرے۔",
  "wy.diff.weatherTitle": "بنیادی طور اتے موسم جانن والا",
  "wy.diff.weatherDesc": "رہنمائی تہاڈے تک پجن توں پہلاں اصلی حالت ویکھدی اے — تاں جو مینہہ توں گھنٹے پہلاں سپرے دا مشورہ نہ دتا جاوے۔",
  "wy.diff.platformTitle": "اک پلیٹ فارم، پورا سیزل",
  "wy.diff.platformDesc": "مشیر، ریکارڈ، موسم رہنمائی تے مشاورت مل کے کم کردے نیں — وکھریاں ایپاں تے کاپیاں وچ نہیں کھلردے۔",
  "wy.diff.pakTitle": "پاکستان اول",
  "wy.diff.pakDesc": "مقامی فصلاں، علاقائی طریقیاں تے اصلی کھیت دیاں حالتاں پہلے دن توں ڈیزائن وچ نیں — بعد وچ جوڑی گئی سوچ دے طور اتے نہیں۔",
  "wy.diff.pakBadge": "ایتھوں ای شروعات",
  "wy.life.eyebrow": "مشیر کن کن وچ رہنمائی کردا اے",
  "wy.life.heading": "فصل دے چکر دے ہر فیصلے لئی رہنمائی",
  "wy.life.sub": "اک مشیر پورے فصلی دور وچ تہاڈے نال رہندا اے — سیزل دی منصوبہ بندی توں لے کے فصل گھر پہنچان تک۔",
  "wy.life.s1Title": "پانی دین دا وقت",
  "wy.life.s1Desc": "جانو کدوں پانی دینا اے — تے کدوں اڈیک کرنی اے۔",
  "wy.life.s2Title": "فصل دی منصوبہ بندی",
  "wy.life.s2Desc": "اپنی زمین دے موافق فصلاں تے بوائی دیاں کھڑکیاں چنو۔",
  "wy.life.s3Title": "کھاد تے کیڑے مار دوائیاں دی رہنمائی",
  "wy.life.s3Desc": "صحیح ان پٹ، صحیح مقدار وچ، صحیح ویلے اتے۔",
  "wy.life.s4Title": "کیڑے تے بیماری وچ مدد",
  "wy.life.s4Desc": "مسئلے جلدی پکڑو تے پھیلن توں پہلاں عمل کرو۔",
  "wy.life.s5Title": "کٹائی دا وقت",
  "wy.life.s5Desc": "اس لمحے کٹو جیہڑا پیدوار تے معیار دی حفاظت کرے۔",
  "wy.life.s6Title": "موسم جانن والیاں تجویزاں",
  "wy.life.s6Desc": "ہر مشورہ پہلاں اج دیاں حالتاں ویکھدا اے۔",
  "wy.life.s7Title": "روزمرہ سوال",
  "wy.life.s7Desc": "اپنی فصل بارے کجھ وی پچھو، سیزل دے کسے وی دن۔",
  "wy.value.eyebrow": "وعدہ",
  "wy.value.heading1": "کی کرنا اے۔ کد کرنا اے۔",
  "wy.value.heading2": "تے کی ہو چکا اے۔",
  "wy.value.sub": "اگروپیو دی ہر سہولت انہاں تن جواباں وچوں اک دی خدمت کردی اے — اینج فیصلیاں دا سیزل اعتماد دا سیزل بن جاندا اے۔",
  "wy.value.p1Heading": "کی کرنا اے",
  "wy.value.p1Desc": "تہاڈی فصل تے حالتاں مطابق صاف، خاص تجویزاں — عام نشانیاں نہیں۔",
  "wy.value.p2Heading": "کد کرنا اے",
  "wy.value.p2Desc": "اصلی موسم تے وادھے دے پڑاء مطابق ویلھا، تاں جو صحیح قدم صحیح لمحے اتے ہووے۔",
  "wy.value.p3Heading": "کی ہو چکا اے",
  "wy.value.p3Desc": "ہر کم دی منظم تاریخ — ہمیشہ دستیاب، ہمیشہ بہتر مشورے دی بنیاد۔",
  "wy.who.eyebrow": "کس کس لئی اے",
  "wy.who.heading": "کسان توں شروع ہو کے اگے",
  "wy.who.a1Title": "انفرادی کسان",
  "wy.who.a1Desc": "ہر فیصلے وچ عملی، ذاتی رہنمائی — تے جو کجھ ہو چکا اے اس دا منظم ریکارڈ۔",
  "wy.who.a2Title": "تجارتی فارم تے زرعی کاروبار",
  "wy.who.a2Desc": "ٹیماں، کھیتاں تے سیزلاں وچ منظم فارم جانکاری تے بھروسے یوگ فیصلہ سازی دی مدد۔",
  "wy.who.a3Title": "ایکو سسٹم دے ساجھے دار",
  "wy.who.a3Desc": "ان پٹ دین والے، کوآپریٹو، بیمہ کمپنیاں تے زرعی توسیعی خدمات — جیویں جیویں پلیٹ فارم ودھدا اے۔",
  "wy.who.strip": "فارم دے دوالے ماحول نال ودھدے ہوئے",

  "auth.backHome": "واپس ہوم تے",
  "auth.emailLabel": "ای میل پتہ",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاس ورڈ",
  "auth.showPassword": "پاس ورڈ وکھاؤ",
  "auth.hidePassword": "پاس ورڈ لکاؤ",
  "auth.err.emailRequired": "اپنا ای میل پتہ لکھو۔",
  "auth.err.emailInvalid": "درست ای میل پتہ لکھو۔",
  "auth.err.passwordRequired": "پاس ورڈ بناو۔",
  "auth.err.passwordMin": "گھٹو گھٹ ۸ اکر ورتو۔",
  "auth.err.passwordMax": "ودھ توں ودھ ۶۴ اکر ورتو۔",
  "auth.err.nameRequired": "اپنا پورا ناں لکھو۔",
  "auth.err.phoneInvalid": "درست فون نمبر لکھو۔",
  "auth.err.confirmRequired": "اپنا پاس ورڈ دوبارہ لکھو۔",
  "auth.err.termsRequired": "اگے ودھن لئی شرطاں منو۔",
  "auth.err.passwordMismatch": "پاس ورڈ ایکو جہے نہیں نیں۔",
  "auth.err.loginPasswordRequired": "اپنا پاس ورڈ لکھو۔",
  "auth.err.tooManyAttempts": "بہت زیادہ کوششاں — مہربانی کرکے تھوڑی دیر بعد دوبارہ کوشش کرو۔",
  "auth.err.serverError": "ساڈے پاسوں خرابی آئی۔ مہربانی کرکے دوبارہ کوشش کرو۔",
  "auth.err.invalidCredentials": "ای میل جا پاس ورڈ غلط اے۔",

  "li.meta.title": "سائن اِن — اگروپیو",
  "li.meta.description":
    "اگروپیو، اے آئی والی فارم ذہانت دے پلیٹ فارم وچ سائن اِن کرو۔ تہاڈا مشیر، ریکارڈ تے رہنمائیاں — اوتھے موجود جتھے تسیں چھڈیاں سن۔",
  "li.brand.headingA": "تہاڈے فارم دی ذہانت،",
  "li.brand.headingB": "اوتھے موجود جتھے تسیں چھڈی سی۔",
  "li.demo.aria": "اگروپیو مشیر نال گل بات دی جھلک",
  "li.demo.user": "میری کنک دیاں پتیاں پیلیاں ہو رہیاں نیں — کیہ کراں؟",
  "li.demo.advisorLabel": "دو کارن:",
  "li.demo.advisorBody": "پانی دی کمی جا نائٹروجن دی کمی۔ پہلے سویرے ٹھنڈے ویلے تے پانی دیو۔",
  "li.point1": "تہاڈی اپنی بولی وچ اے آئی مشیر",
  "li.point2": "سیٹیلائٹ راہیں فصل دی صحت دی نگھرداری",
  "li.point3": "ہر موسم دا ڈیجیٹل ریکارڈ",
  "li.eyebrow": "سائن اِن",
  "li.heading": "تہاڈے فارم تے دوبارہ خوش آمدید",
  "li.sub": "سائن اِن کرو تاں جو تہاڈے فارم دے مشیر، ریکارڈ تے رہنمائیاں تک پہنچ سکو۔",
  "li.passwordPlaceholder": "تہاڈا پاس ورڈ",
  "li.forgot": "پاس ورڈ بھل گئے او؟",
  "li.submitting": "سائن اِن ہو رہیا نیں…",
  "li.noAccount": "اجے اکاؤنٹ نہیں؟ ابتدائی رسائی علاقہ در علاقہ کھلدی جا رہی اے —",
  "li.noAccountEnd": "۔",
  "li.createAccount": "اپنا اکاؤنٹ بناؤ",

  "su.meta.title": "اکاؤنٹ بناؤ — اگروپیو",
  "su.meta.description":
    "اپنا اگروپیو اکاؤنٹ بناؤ: ذاتی قسم دا اے آئی مشیر، موسم جانن والی رہنمائی، تے فارم ریکارڈ جو ہر موسم نوں بہتر بناندے نیں۔ پاکستان لئی بنایا گیا۔",
  "su.brand.headingA": "اپنا موسم شروع کرو",
  "su.brand.headingB": "ذہانت نال۔",
  "su.profile.aria": "سائن اپ مگروں بننوالے فارم پروفائل دی جھلک",
  "su.profile.badge": "فارم پروفائل · اک منٹ وچ تیار",
  "su.profile.district": "ضلع",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشیرے دی بولی",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "کنک · ربیع",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پہلے دن توں ذاتی قسم دا مشیر",
  "su.included2": "تہاڈے ضلعے لئی موسم جانن والی رہنمائی",
  "su.included3": "فارم ریکارڈ جو ہر موسم نوں بہتر بناندے نیں",
  "su.eyebrow": "اکاؤنٹ بناؤ",
  "su.heading": "اپنا فارم اگروپیو لیاؤ",
  "su.sub": "اک اکاؤنٹ — تہاڈے مشیر، ریکارڈ تے اس موسم دی ہر رہنمائی لئی۔",
  "su.registered.title": "ایہ ای میل پہلاں توں رجسٹرڈ اے۔",
  "su.registered.body":
    "سائن اِن کرو، جاں جے پاس ورڈ بھل گئے او تے ری سیٹ کرو — تہاڈا فارم اوتھے اڈیک وچ اے جتھے تسیں چھڈیا سی۔",
  "su.registered.reset": "پاس ورڈ ری سیٹ کرو",
  "su.name.label": "پورا ناں",
  "su.name.placeholder": "مثلاً محمد احمد",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختیاری)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آف لائن ہون تے ایس ایم ایس الرٹس لئی۔",
  "su.password.placeholder": "گھٹو گھٹ ۸ اکر",
  "su.confirm.label": "پاس ورڈ دی تصدیق کرو",
  "su.confirm.placeholder": "اپنا پاس ورڈ دوبارہ لکھو",
  "su.strength0": "بہت تھوڑا",
  "su.strength1": "ٹھیک اے",
  "su.strength2": "چنگا",
  "su.strength3": "مضبوط",
  "su.terms.prefix": "میں",
  "su.terms.tos": "شرطاں خدمت",
  "su.terms.and": "تے",
  "su.terms.privacy": "پرائیویسی پالیسی",
  "su.terms.end": "منوں واں۔",
  "su.submit": "میرا اکاؤنٹ بناؤ",
  "su.submitting": "اکاؤنٹ بن رہیا اے…",
  "su.haveAccount": "پہلاں توں اکاؤنٹ اے؟",
  "app.shell.metadataTitle": "اگروپیو — مصنوعی ذہانت تے مبنی فارم انٹیلیجنس پلیٹ فارم",
  "app.shell.metadataDescription":
    "اَج دی رہنمائی، موسم، الرٹ تے اگروپیو دا ہر آلہ — پاکستان لئی۔ اپلینوڈ دی پروڈکٹ۔",

  /* ── شیل نیویگیشن ─────────────────────────────────── */
  "app.shell.nav.dashboard": "ڈیش بورڈ",
  "app.shell.nav.farms": "کھیت",
  "app.shell.nav.advisor": "مشیر",
  "app.shell.nav.detect": "تشخیص",
  "app.shell.nav.prices": "قیمتاں",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "اطلاعات",
  "app.shell.nav.settings": "ترتیبات",
  "app.shell.nav.more": "ور ",
  "app.shell.signOut": "لاگ آؤٹ",
  "app.shell.aria.farmerTools": "کسان دے اوزار",
  "app.shell.aria.currentPage": "موجودہ صفحہ",

  /* ── ڈیش بورڈ UI ──────────────────────────────────── */
  "app.dashboard.greeting": "ہیلو، {name}",
  "app.dashboard.aria.profileMenu": "پروفائل مینو",
  "app.dashboard.welcomeEyebrow": "اگروپیو وچ خوش آمدید",
  "app.dashboard.welcomeTitle": "اپنا پہلا کھیت شروع کرو۔",
  "app.dashboard.welcomeBody":
    "تہاڈی فصل، تہاڈی زمین، تہاڈا موسم — جِدّوں تہاڈا کھیت ہوئے گا ہر رہنمائی اُس دے مطابق ہوئے گی۔",
  "app.dashboard.addFirstFarm": "اپنا پہلا کھیت شامل کرو",
  "app.dashboard.badge.today": "اَج",
  "app.dashboard.aria.advisoryTitle": "اَج دی رہنمائی",
  "app.dashboard.carryToField": "اِس نوں کھیت وِچ لے کے جاؤ",
  "app.dashboard.askAdvisor": "مشیر نال پوچھو",
  "app.dashboard.aria.weatherTitle": "موسم \u00b7 {location}",
  "app.dashboard.aria.degreesCelsius": "{n} ڈگری سیلسیس",
  "app.dashboard.fullForecast": "مکمل پیشگوئی",
  "app.dashboard.weatherUnavailable":
    "موسم ہُن لوڈ نہیں ہو ریہا۔ تھوڑی دیر بعد دوبارہ چیک کرو — تہاڈیاں رہنمائیاں چالیاں۔",
  "app.dashboard.seasonTipBadge": "موسمی تجاویز",
  "app.dashboard.alertsHeading": "الرٹ",
  "app.dashboard.newCount": "{n} نئیاں",
  "app.dashboard.viewAllAlerts": "سارے الرٹ ویکھو",
  "app.dashboard.noAlerts": "اَج کوئی الرٹ نہیں — تہاڈیاں فصلیں سکون وچ ہیں۔",
  "app.dashboard.aria.alert": "الرٹ",
  "app.dashboard.severity.critical": "سنگین",
  "app.dashboard.severity.watch": "خبردار",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "بولی",
  "app.dashboard.quickActionsHeading": "فوری عمل",
  "app.dashboard.cropDoctor": "فصل دا ڈاکٹر",
  "app.dashboard.detectTitle": "بیماری پھیلنے تو پہلے پہچانو",
  "app.dashboard.detectBody":
    "متاثرے پتے دی تصویر اپلوڈ کaro — فوری تشخیص تے اگلا قدم تہاڈے فون تے۔",
  "app.dashboard.myFarms": "میرے کھیت",
  "app.dashboard.addFarm": "کھیت شامل کرو",
  "app.dashboard.viewAllFarms": "سارے کھیت ویکھو",
  "app.dashboard.health.good": "چنگا",
  "app.dashboard.health.watch": "خبردار",
  "app.dashboard.setupChecklist": "اپنا کھیت ترتیب کرو",
  "app.dashboard.checklistProgress": "{done} وِچوں {total} مکمل",
  "app.dashboard.aria.dismissChecklist": "سیٹ اپ چیک لسٹ بند کرو",
  "app.dashboard.aria.setupProgress": "سیٹ اپ دی پیشرفت",
  "app.dashboard.demoFooter": "ڈیمو بلڈ \u00b7 صرف نمونہ ڈیٹا",

  /* ── ڈیش بورڈ ڈیمو ڈیٹا ──────────────────────────── */
  "app.dashboard.demo.todayLabel": "اتوار، 23 اگست",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "سبزی کا مرحلہ",
  "app.dashboard.demo.advisoryAction": "اَج آبپاشی وِچ تاخیر کرو",
  "app.dashboard.demo.advisoryWhy":
    "اَج دوپہر توں بعد بارش دا امکان ہے — تہاڈا کھیت قدرتی طور تے پانی پائے گا۔",
  "app.dashboard.demo.seasonAction": "بارش آنے توں پہلے اپنے کھیتاں وِچ چلو",
  "app.dashboard.demo.seasonWhy":
    "خشک دناں توں بعد ہولی چلنا دکھاؤں دا ہے کِہ کُڈّے نکاسی خراب کرتے ہیں — بونے توں پہلے نوٹ کرو۔",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "دوپہر 2 بجے توں بعد بارش دا امکان \u00b7 80% امکان",
  "app.dashboard.demo.alertWhitefly":
    "ملتان ضلع وِچ اِس ہفتے کپاس تے سفید مکھی دا خطرہ زیادہ ہے۔",
  "app.dashboard.demo.alertRain":
    "اَج دوپہر 2 بجے توں بعد بارش متوقع ہے — چھڑی چھڑکنے دا منصوبہ ملتوی کرو۔",
  "app.dashboard.demo.alertPrice":
    "ملتان مڑی تے گندم دیاں قیمتاں گزشتہ ہفتے دے مقابلے وِچ 4% زیادہ ہیں۔",
  "app.dashboard.demo.farm1Name": "خلیل پور کھیت",
  "app.dashboard.demo.farm1Location": "خلیل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "سبزی کا مرحلہ",
  "app.dashboard.demo.farm2Name": "سہیوال پلاٹ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڈ، سہیوال",
  "app.dashboard.demo.farm2Crops": "کپاس",
  "app.dashboard.demo.farm2Stage": "پھول آنا",
  "app.dashboard.demo.farm3Name": "چک 62 جی بی",
  "app.dashboard.demo.farm3Location": "چک 62 جی بی، فیصل آباد",
  "app.dashboard.demo.farm3Crops": "گنا",
  "app.dashboard.demo.farm3Stage": "پَرچی کا مرحلہ",
  "app.dashboard.demo.checklistAdvisor": "اِک واری مشیر نال پوچھو",
  "app.dashboard.demo.checklistDetect": "اپنی پہلی تشخیص چلاؤ",
  "app.dashboard.demo.actionAdvisor": "مشیر نال پوچھو",
  "app.dashboard.demo.actionScan": "فصل اسکین کرو",
  "app.dashboard.demo.actionPrices": "قیمتاں چیک کرو",
  "app.dashboard.demo.actionRecord": "ریکارڈ شامل کرو",

  /* ── کھیت عام ──────────────────────────────────────── */
  "app.farms.eyebrow": "کھیت",
  "app.farms.health.good": "چنگا",
  "app.farms.health.watch": "خبردار",
  "app.farms.units.acres": "ایکڑ",
  "app.farms.stages.sowing": "بوئی",
  "app.farms.stages.tillering": "شاخاں کا نکلنا",
  "app.farms.stages.vegetative": "نباتاتی",
  "app.farms.stages.grainFilling": "دنہاں بھرنا",
  "app.farms.stages.ready": "تیار",
  "app.farms.stages.squaring": "فال بندی",
  "app.farms.stages.flowering": "پھول آنا",
  "app.farms.stages.bollFilling": "تہائی بھرنا",
  "app.farms.stages.grandGrowth": "عریض نشوونما",
  "app.farms.stages.ripening": "پکنا",
  "app.farms.stages.harvest": "کٹائی",
  "app.farms.stages.panicleInitiation": "پنجڑا چادھنا",

  /* ── ضلع تے فصلیں ──────────────────────────────────── */
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سہیوال",
  "app.farms.districts.faisalabad": "فیصل آباد",
  "app.farms.districts.vehari": "وہاڑی",
  "app.farms.districts.bahawalpur": "بہاولپور",
  "app.farms.districts.lodhran": "لودھراں",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "کپاس",
  "app.farms.crops.sugarcane": "گنا",
  "app.farms.crops.maize": "مکئی",
  "app.farms.crops.rice": "چاول",

  /* ── کھیتاں دی فہرست ────────────────────────────────── */
  "app.farms.list.pageTitle": "کھیت — اگروپیو",
  "app.farms.list.heading": "تہاڈے سارے کھیت، اک فہرست",
  "app.farms.list.description":
    "ہر کھیت اپنیاں فصلیں، نشوونما دے مرحلے تے صحت دے ساتھ — اک نظر وِچ۔ کھیت دی مکمل کہانی لئی ٹیپ کرو۔",
  "app.farms.list.addLink": "شامل کرو",
  "app.farms.list.openFarm": "کھیت کھولو",
  "app.farms.list.addNewFarm": "نیا کھیت شامل کرو",
  "app.farms.list.emptyHeading": "تہاڈے کول کویں کھیت نئیں",

  /* ── نیا کھیت ────────────────────────────────────────── */
  "app.farms.new.pageTitle": "کھیت شامل کرو — اگروپیو",
  "app.farms.new.heading": "کھیت شامل کرو",
  "app.farms.new.description":
    "اگروپیو نوں اپنی زمین بارے وِچ دسو — مقام، فصل تے رقبہ — تاں جو ہر رہنمائی اُس دے مطابق ہووے۔",
  "app.farms.new.fields.name": "کھیت دا ناں",
  "app.farms.new.placeholders.name": "مثلاً خلیل پور کھیت",
  "app.farms.new.fields.district": "ضلع",
  "app.farms.new.placeholders.district": "ضلع چنو",
  "app.farms.new.fields.crop": "بنیادی فصل",
  "app.farms.new.placeholders.crop": "فصل چنو",
  "app.farms.new.fields.acres": "رقبہ (ایکڑ)",
  "app.farms.new.placeholders.acres": "مثلاً ۱۲.۵",
  "app.farms.new.fields.location": "مقام / گاں",
  "app.farms.new.placeholders.location": "گاں یا شہر دا ناں لکھو",
  "app.farms.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.farms.new.buttons.save": "کھیت محفوظ کرو",
  "app.farms.new.demoNotice": "ڈیمو — محفوظ کرنا ہُن ڈیٹابیس نال نہیں جُڑیا",
  "app.farms.new.success.heading": "کھیت ڈیمو وِچ محفوظ ہو گیا",
  "app.farms.new.success.description":
    "مکمل بلڈ وِچ اِہ کھیت تہاڈے ڈیش بورڈ تے دکھائے گا تے رہنمائیاں شکل لینا شروع کریں گیاں۔",
  "app.farms.new.success.goToFarms": "میرے کھیتاں تے جاؤ",
  "app.farms.new.success.backToDashboard": "واپس ڈیش بورڈ تے",
  "app.farms.new.errors.nameRequired": "کھیت نوں ناں دیو۔",
  "app.farms.new.errors.districtRequired": "ضلع چنو۔",
  "app.farms.new.errors.cropRequired": "بنیادی فصل چنو۔",
  "app.farms.new.errors.acresRequired": "رقبہ ایکڑ وِچ درج کرو۔",

  /* ── کھیت دی تفصیل ──────────────────────────────────── */
  "app.farms.detail.pageTitle": "کھیت دی تفصیل — اگروپیو",
  "app.farms.detail.heroEyebrow": "کھیت دی تفصیل",
  "app.farms.detail.goodHealth": "چنگی صحت",
  "app.farms.detail.needsWatching": "توجہ لاگم",
  "app.farms.detail.sownLabel": "بوئی",
  "app.farms.detail.seasonHeading": "فصل کِتھے اے",
  "app.farms.detail.activityHeading": "کھیت دی سرگرمی",
  "app.farms.detail.viewAllRecords": "سارے ریکارڈ ویکھو",
  "app.farms.detail.logFieldEvent": "کھیت دا واقعہ درج کرو",
  "app.farms.detail.scanCrop": "فصل اسکین کرو",

  /* ── ریکارڈ عام ──────────────────────────────────────── */
  "app.records.eyebrow": "کھیت دے ریکارڈ",
  "app.records.types.irrigation": "آبپاشی",
  "app.records.types.fertilizer": "کھاد",
  "app.records.types.pesticide": "کیڑے مار",
  "app.records.types.disease": "بیماری",
  "app.records.types.harvest": "کٹائی",

  /* ── ریکارڈاں دی فہرست ──────────────────────────────── */
  "app.records.farmRecords.pageTitle": "کھیت دے ریکارڈ — اگروپیو",
  "app.records.farmRecords.heading": "کھیت دی یادداشت",
  "app.records.farmRecords.description":
    "ہر آبپاشی، اسپرے تے علاج لکھیا ہویا — تاں جو اگلے ہفتے دے فیصلے یادداشت تے منحصر نہ ہوں۔",
  "app.records.farmRecords.demoNotice":
    "ڈیمو — صرف نمونہ اندراجات — نئے محفوظ کرنا ہُن نہیں جُڑیا",

  /* ── نیا ریکارڈ ──────────────────────────────────────── */
  "app.records.new.pageTitle": "نیا ریکارڈ — اگروپیو",
  "app.records.new.heading": "کھیت وِچ جو ہویا اُہ درج کرو",
  "app.records.new.description":
    "آبپاشی، کھاد، کیڑے مار، بیماری تے کٹائی دے اندراجات — تہاڈے کھیت دی یادداشت، اِک اِک لائن۔",
  "app.records.new.fields.type": "کیا ہویا؟",
  "app.records.new.fields.farm": "کھیت",
  "app.records.new.placeholders.farm": "کھیت چنو",
  "app.records.new.fields.date": "تاریخ",
  "app.records.new.fields.title": "مختصر عنوان",
  "app.records.new.fields.optional": "(اختیاری)",
  "app.records.new.placeholders.titleIrrigation": "مثلاً نہری پانی — مکمل کھیت",
  "app.records.new.placeholders.titleOther": "دوسرا چھڑکاؤ پتواروں تے",
  "app.records.new.fields.details": "تفصیلات",
  "app.records.new.placeholders.details":
    "اگلے ہفتے لئی جو وی یاد رکھنا ضروری ہو — مقدار، موسم، کھیت دی صورتحال۔",
  "app.records.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.records.new.buttons.save": "ریکارڈ محفوظ کرو",
  "app.records.new.demoNotice": "ڈیمو — محفوظ کرنا ہُن ڈیٹابیس نال نہیں جُڑیا",
  "app.records.new.success.heading": "ریکارڈ ڈیمو وِچ محفوظ ہو گیا",
  "app.records.new.success.description":
    "مکمل بلڈ وِچ اِہ اندراج تہاڈے کھیت دے ریکارڈ وِچ شامل ہوگا تے مستقبل دیاں رہنمائیاں تیز ہوں گیاں۔",
  "app.records.new.success.backToDashboard": "واپس ڈیش بورڈ تے",
  "app.records.new.success.viewFarms": "میرے کھیت ویکھو",
  "app.records.new.errors.farmRequired": "چنو اِہ کس کھیت تے ہویا۔",
  "app.records.new.errors.dateRequired": "تاریخ چنو۔",
  "app.advisor.chat.tryAsking": "ایہہ پچھ کے ویکھو",
  "app.advisor.chat.suggested1": "میری کݨک نوں کیہڑی بیماری لگی اے؟",
  "app.advisor.chat.suggested2": "کیہ اج ملتان وچ مینہہ پوۓ گا؟",
  "app.advisor.chat.suggested3": "اج منڈی دے بھا کیہ نیں؟",
  "app.advisor.chat.suggested4": "کسان کارڈ سکیم بارے دسو",

  "app.advisor.pageTitle": "مشیر",
  "app.advisor.sidebar.title": "گفتگو",
  "app.advisor.sidebar.newConversation": "نئی گفتگو",
  "app.advisor.sidebar.noConversations": "اب تک کوئی گفتگو نہیں۔ نئی شروع کرو!",
  "app.advisor.sidebar.rename": "نام بدلو",
  "app.advisor.sidebar.delete": "مٹاؤ",
  "app.advisor.sidebar.deleteTitle": "گفتگو مٹاؤ",
  "app.advisor.sidebar.deleteConfirm": "کیا یہ گفتگو مٹا دیں؟ یہ واپس نہیں ہو سکتی۔",
  "app.advisor.sidebar.cancel": "منسوخ",
  "app.advisor.sidebar.closeSidebar": "سائیڈ بار بند کرو",
  "app.advisor.chat.placeholder": "اپنی فصل، موسم، منڈی کے بارے پوچھو…",
  "app.advisor.chat.send": "بھیجو",
  "app.advisor.chat.thinking": "سوچ رہا ہے…",
  "app.advisor.chat.openingGreeting": "السلام عليكم! میں آپ کا اگروپیو زرعی مشیر ہوں۔ اپنی فصل، موسم، منڈی قیمت یا سرکاری اسکیموں کے بارے کچھ بھی پوچھیں۔",
  "app.advisor.chat.photoRedirect": "تصویری تشخیص پہچان صفحے پر ہے — بیماریوں کی پہچان کے لیے فصل اسکین کریں۔",
  "app.advisor.chat.nonFarmingRedirect": "میں زرعی سوالات میں مدد کے لیے یہاں ہوں۔ میں اپنی فصل یا فارم کے بارے کیسے مدد کر سکتا ہوں؟",
  "app.advisor.errors.serviceUnavailable": "مشیر سروس عارضی طور پر دستیاب نہیں ہے۔ براہ کرم کچھ دیر بعد کوشش کریں۔",
  "app.advisor.errors.rateLimited": "بہت زیادہ درخواستیں۔ براہ کرم ایک لمحہ انتظار کریں اور دوبارہ کوشش کریں۔",
  "app.advisor.errors.network": "نیٹ ورک کی غلطی۔ اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
  "app.advisor.errors.generic": "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",
  "app.advisor.aria.openSidebar": "گفتگو کھولیں",
  "app.advisor.aria.sendMessage": "پیام بھیجیں",
  "app.advisor.aria.chatMessages": "چیٹ پیامات"};
