import type { CatalogKey } from "./en.ts";

/** پنجابی (شاہ مکھی) — AI-drafted, founder-reviewed copy (plan D4). */
export const pa: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "شروعاتی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ نہیں لبھیا",
  "notFound.body": "تسیں جیہڑا صفہ لبھ رہے او اوہ موجود نہیں جاں تبدیل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے ہوم تے واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کھیتی باڑی لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڈے فارم دے ریکارڈ اک تھاں تے جمع کردا اے — ڈیٹا نوں صاف فیصلیاں وچ بدلدا اے، تہاڈی اپنی بولی وچ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کویں کم کردا اے",
  "home.hero.imageAlt": "کاشکر کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "شاندار",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلا",
  "home.problem.title": "کھیتی باڑی دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان چ کاشکر ریایت، مقامی صلاحاں تے کھلریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان وڈی تے چکنا پیندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، وڈائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹ تے خرچ برباد ہوندی اے۔",
  "home.problem.item2Title": "گُواچا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھلریاں کاپیاں چ رہندا اے۔ پچھلے سال جو کم آیا، اوہدیوں اس سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھلریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کاشکر دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت وڈی تے چکدی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک انٹیلیجنس پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈا تہاڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیڑے مار تے وڈائی دے ویلیے لئی ذاتی صلاحاں — تہاڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تہاڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا جا چکا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، وڈائی — ترتیب والے ریکارڈ چ محفوظ جو ہر سیزن نوں زیادہ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "پوری تریخ، ہمیشہ موجود۔",
};
