import type { CatalogKey } from "./en.ts";

/** پنجابی (شاہ مکھی) — AI-drafted, founder-reviewed copy (plan D4). */
export const pa: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "شروعاتی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "صفہ نہیں لبھیا",
  "notFound.body": "تسیں جیہڑا صفہ لبھ رہے او اوہ موجود نہیں جاں تبدیل ہو گیا اے۔",
  "notFound.backHome": "اگروپیو دے ہوم تے واپس جاؤ",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار کھیتی باڑی لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڈے فارم دے ریکارڈ اک تھاں تے جمع کردا اے — ڈیٹا نوں صاف فیصلیاں وچ بدلدا اے، تہاڈی اپنی بولی وچ۔",
  "home.hero.ctaSecondary": "ویکھو ایہ کویں کم کردا اے",
  "home.hero.imageAlt": "کاشکر کھیت وچ ٹیبلٹ تے اگروپیو ورتدا ہویا",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "شاندار",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "کیمیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلا",
  "home.problem.title": "کھیتی باڑی دے فیصلے اندازے دی کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان چ کاشکر ریایت، مقامی صلاحاں تے کھلریاں معلومات نال وڈے رسک والے فیصلے کردے نیں۔ نقصان وڈی تے چکنا پیندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، وڈائی — اہم لمحے اجے وی اندازے نال طے ہوندے نیں، جس نال پیداوار گھٹ تے خرچ برباد ہوندی اے۔",
  "home.problem.item2Title": "گُواچا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھلریاں کاپیاں چ رہندا اے۔ پچھلے سال جو کم آیا، اوہدیوں اس سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھلریاں صلاحاں",
  "home.problem.item3Body": "گوانڈی، دکاندار تے ویڈیوز سب جواب دیندے نیں — پر کجھ ہی کاشکر دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت وڈی تے چکدی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک انٹیلیجنس پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈا تہاڈی زمین دے ڈیٹا نال کم کردے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، کیڑے مار تے وڈائی دے ویلیے لئی ذاتی صلاحاں — تہاڈی فصل تے حالات مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کدوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی دسدی اے کم کدوں کرنا اے، تاں جو غلط ویلا تے اچانک حالات تہاڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما مطابق ویلا۔",
  "home.solution.card3Title": "کی کیتا جا چکا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، وڈائی — ترتیب والے ریکارڈ چ محفوظ جو ہر سیزن نوں زیادہ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "پوری تریخ، ہمیشہ موجود۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "کئی انجن،",
  "home.features.titleB": "اک ذہین پلیٹ فارم",
  "home.features.subtitle": "تہاڈے اپنے بولاں چ پہلا سوالوں لے کے سارے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی نوں تقویت دیندی اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی کھیتی مشیر",
  "home.features.advisorTopics": "پانی · کھاد · کیمیا تے بیماری · وڈائی",
  "home.features.advisorBadge": "رومن پنجابی",
  "home.features.advisorMockAria": "پیلا پتریاں والی کنک تے اگروپیو مشیر نال نمونہ گل بات",
  "home.features.advisorUserMsg": "میری کنک دے پتے پیالے ہو رے نیں — کراں؟",
  "home.features.advisorReplyTitle": "پیلے پتر — دو عام کارن:",
  "home.features.advisorReplyCause1": "پانی دی تنگی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے ویلیے چ، سویرے 9 وجے توں پہلاں پانی دیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سبھ توں پرانے پتر پہلاں ویکھو؛ لوڑ ہووے تے یوریا پاؤ۔",
  "home.features.advisorReplyFooter": "جے پتریاں ہیٹھ پیلیاں لیکاں دسن، تصویر بھیجو — main بیماری دی جانچ کر دوانگی۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھو یا بولو…",
  "home.features.advisorFooter": "اپنی فصل بارے کجھ وی پچھو — روزمرہ سوالاں جی آیاں نوں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر کم ترتیب نال درج — تے جے صلاح تہاڈی اپنی زمین توں سکھے۔",
  "home.features.record1Activity": "پانی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتریاں دا اسکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "کنک · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · بولی",
  "home.features.languageTitle": "تہاڈی بولی، تہاڈے بول",
  "home.features.languageDesc": "جدوں سوچدے او ادوں بول کے یا لکھ کے کہو — تکنیکی انگریزی دی لوڑ نہیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں جانو رہنمائی",
  "home.features.weatherDesc": "صلاح تسیں تک آن توں پہلاں سچے حالات ویکھدی اے — mینہ توں پہلاں چھڑکاؤ کیتا تے سارا کھاد پانی بن گیا۔",
  "home.features.weatherMockAria": "پنج دن دی پیش گوئی جس چ جمعرات نوں چھڑکاؤ نہ کرن دی صلاح نمایاں اے",
  "home.features.dayMon": "سوموار",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "ویروار",
  "home.features.dayFri": "شکروار",
  "home.features.holdSpray": "چھڑکاؤ روکو",
  "home.features.weatherLegend": "مقامی موسم دی پیش گوئی توں صلاح والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودھدا جا ریا اے — پوریاں صلاحیتاں ویکھو",
  "home.journey.eyebrow": "ایہ کویں کم کردا اے",
  "home.journey.title": "اک سوال سیزن شروع کردا اے",
  "home.journey.subtitle": "تہاڈے پہلے سوالوں توں مکمل، ذہین فارم تریخ تک سادہ راہ۔",
  "home.journey.step1Title": "اپنا فارم پایو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بنان لئی تھاں، فصل تے بنیادی جانکاری بھرو۔",
  "home.journey.step2Title": "اے آئی توں پچھو",
  "home.journey.step2Body": "اپنا سوال اسی بولی چ لکھو یا بولو جس تسیں سبھ توں زیادہ آرام نال بولدے او۔",
  "home.journey.step3Title": "رہنمائی پاؤ",
  "home.journey.step3Body": "اپنی فصل، موسم، تھاں تے فارم تریخ تے بیسیا صلاحاں پاؤ۔",
  "home.journey.step4Title": "کم درج کرو",
  "home.journey.step4Body": "کجھ ٹیپاں چ پانی، کھاد، دوائی جاں بیماری درج کرو۔",
  "home.journey.step5Title": "تریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ اگیاں صلاحاں نوں ہور سمجھدار تے موزوں بناندا اے۔",
  "home.journey.step6Title": "نگرانی جاری رکھو",
  "home.journey.step6Body": "سارے سیزن دوران ریکارڈ ویکھو تے ترقی تے نظر رکھو۔",
  "home.matrix.eyebrow": "پوریاں صلاحیتاں دا مجموعہ",
  "home.matrix.title": "ضروری توں حیرانی والے تک",
  "home.matrix.subtitle": "ہر خاصیت فصل بچاندی اے، خرچ گھٹاندی اے جاں آمدنی ودھاندی اے۔ اس نوں جنتری وانگ پڑھو — ہر پڑھی پچھلی تے بنی اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتاں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی پدھر",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری پچھان",
  "home.matrix.t1f1Body": "متاثرہ پتر دی فوٹو اپلوڈ کرو تے فوری جانچ، شدت تے علاج دیاں صلاحاں پاؤ۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت نگاری",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد نشان زد کرو تے مفت سینٹینل-2 تصویراں توں این ڈی وی آئی بیسی فصل دی صحت ویکھو۔",
  "home.matrix.t1f3Title": "ہوشیار موسمی صلاح",
  "home.matrix.t1f3Body": "مقامی موسم پیش گوئی تہاڈی فصل تے ودھدے پڑاءُ نال مل کے روزانہ کم دی صلاح بن جاندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیش گوئی",
  "home.matrix.t1f4Body": "نزدیکی منڈی دیاں قیمتیں اے آئی رجحاناں نال ویکھو، تے ٹھیک ویلیے تے ویکو۔",
  "home.matrix.tier2Name": "وکھریاں خاصیتاں",
  "home.matrix.tier2Badge": "نمانہ",
  "home.matrix.t2f1Title": "علاقائی بولیاں دا وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولو جاں لکھو — جواب اسی بولی چ سنو جس تسیں بہتر سمجھدے او۔",
  "home.matrix.t2f2Title": "سرکاری سکیم میچر",
  "home.matrix.t2f2Body": "اپنی جانکاری بھرو تے ہر اہل سکیم لبھو — دستاویزاں تے اپلائی لنکاں سمیت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن چ تہاڈی مٹی، موسم، منڈی دی منگ تے بجٹ مطابق سبھ توں ودھ منافع والی فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے اصلی خرچ، پیداوار، آمدنی تے نفع — بریک ایون تے آر او آئی نال۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوال پاؤ، تصویراں شیئر کرو، ساتھی کاشکراں تے تصدیق شدہ ماہراں توں جواب لو۔",
  "home.matrix.tier3Name": "حیرانی والیاں",
  "home.matrix.tier3Badge": "سبھ توں اگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی نگاری",
  "home.matrix.t3f1Body": "سلائیڈر نال ویلا بدلدیاں سیٹلائٹ تصویراں تولو — ودھواءُ، نقصان جاں قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیش گوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے پڑاءُ تے تریخ دے بنیاد تے ممکنہ کیڑا حملے توں پہلاں سوچنا۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر تے کال کرو، سوال بولو، اپنی بولی چ صلاح سنو — اسمارٹ فون دی لوڑ نہیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ اندازہ",
  "home.matrix.t3f4Body": "ٹکاؤ طریقے درج کرو تے رضامندی مارکیٹاں توں کاربن کریڈٹ دا اندازہ لو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت چ آف لائن کم کرے، کنکشن تے سنک ہووے، کمزور نیٹ تے ایس ایم ایس خبر دیوے۔",
};
