import type { CatalogKey } from "./en.ts";

/** پښتو — AI-drafted, founder-reviewed copy (plan D4). */
export const ps: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اګروپیو ولې؟",
  "nav.features": "ځانګړنې",
  "nav.howItWorks": "دا څنګه کار کوي",
  "nav.vision": "زموږ لیدلوری",
  "nav.signIn": "ننوتل",
  "nav.getEarlyAccess": "لومړنی لاسرسی ترلاسه کړئ",
  "nav.openMenu": "مینو پرانیستل",
  "nav.closeMenu": "مینو بندول",
  "common.languageSwitcherLabel": "ژبه بدله کړئ",
  "notFound.title": "پاڼه نه موندل شوه",
  "notFound.body": "هغه پاڼه چې تاسو یې لټوې موجوده نشته یا لیږدول شوې ده.",
  "notFound.backHome": "بېرته اګروپیو کور ته",
  "common.builtForPakistan": "د پاکستان لپاره جوړ شوی",
  "common.productOfAplinode": "د اپلینوډ محصول",
  "home.hero.eyebrow": "د مصنوعي ځیرکتیا پر بنسټ د کروندې پوهاوی پلیټفارم",
  "home.hero.titleLead": "د هوښیارې کړنې لپاره",
  "home.hero.titleAccent": "پوهاوی",
  "home.hero.subtitle": "یو پلیټفارم چې د AI سلاکار، سپوږمکۍ کتنه، بازار نرخونه او ستاسو د کروندې ریکارډونه یو ځای کوي — معلومات ستاسو په خپله ژبه روښانه پرېکړو ته بدلوي.",
  "home.hero.ctaSecondary": "وګورئ دا څنګه کار کوي",
  "home.hero.imageAlt": "بزګ په کره کې په ټابلیټ اګروپیو کاروي",
  "home.hero.readingCrop": "د فصل روغتیا",
  "home.hero.readingWeather": "هوا",
  "home.hero.readingSoil": "د خاورې لمدگی",
  "home.hero.noteExcellent": "غوره",
  "home.hero.noteClearSky": "پاکه آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "د اګروپیو وسیلې",
  "home.ticker.cropDoctor": "د فصل AI ډاکتر",
  "home.ticker.satelliteNdvi": "سپوږمکۍ NDVI کتنه",
  "home.ticker.mandiPrices": "بازار د نرخونو پوهه",
  "home.ticker.weatherAdvisories": "هوا سره سم مشورې",
  "home.ticker.farmRecords": "ډیجیټل کروندې ریکارډ",
  "home.ticker.advisoryLanguages": "په ۷ ژبو مشوره",
  "home.ticker.pestAlerts": "د حشراتو خبرداری",
  "home.ticker.offlineSms": "آفلاین + SMS",
  "home.problem.eyebrow": "ستونزه",
  "home.problem.title": "د کړنې پرېکړې باید اټکل نه وي",
  "home.problem.subtitle": "په ټول پاکستان کې بزګان د دود، سیمه ایزو مشورو او خپرو شویو معلوماتو سره سترې پرېکړې کوي. تاوان تر رېبلې وروسته ورکول کیږي.",
  "home.problem.item1Title": "ناڅرګند وخت",
  "home.problem.item1Body": "اوبه، سره، درمل، کینال، رېبل — مهم وختونه لا هم اټکلي دي، چې حاصل کموي او لګښت ضایع کوي.",
  "home.problem.item2Title": "ورک شوی ریکارډ",
  "home.problem.item2Body": "د موسمو پوهه په حافظه یا خپریدلو کتابچو کې پاتې کیږي. تیر کال چې څه کار وکړل، له هغه زده کړه ستونزه ده.",
  "home.problem.item3Title": "خپرې مشورې",
  "home.problem.item3Body": "ګاونډیان، پلورنان او ویډیوګاني ټول ځواب وایي — خو لږ یې د بزګ فصل، خاورې، هوا یا سیمې سره برابر وي.",
  "home.problem.kicker": "د اټکل تاوان تر رېبلې ورسته دی",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "ستاسو د کروندې پوهاوی،",
  "home.solution.titleB": "په یو ځای کې",
  "home.solution.subtitle": "د ټول موسم لپاره یو پلیټفارم — مشوره، ریکارډونه، هوا او بازار ستاسو د ځمکې له معلوماتو کار کوي، نه له عمومي مشورو.",
  "home.solution.card1Title": "څه کول",
  "home.solution.card1Body": "د اوبو، سرې، حشراتو کنټرول او د رېبلې وخت لپاره ځانګړي مشورې — ستاسو د فصل او حالاتو سره سم.",
  "home.solution.card1Answer": "د دې کري، د دې اونۍ لپاره روښانه مشوره.",
  "home.solution.card2Title": "کله یې کول",
  "home.solution.card2Body": "هوایی لارښود درته وايي کله کار وکړه، تر څو بده وخت او ناڅاپي حالات حاصل نه خوري.",
  "home.solution.card2Answer": "وخت د ریښتینې هوا او د فصل ودې سره سم.",
  "home.solution.card3Title": "څه شوي دي",
  "home.solution.card3Body": "هره کار — اوبه، ان پټ، ناروغي، لګښتونه، رېبل — په منظم ریکارډ کې ساتل شوي چې هر موسم ځیرک کوي.",
  "home.solution.card3Answer": "بشپړ تاریخ، تل موجود.",
  "home.features.eyebrow": "د پلیټفارم دننه",
  "home.features.titleA": "ګڼ انجنونه،",
  "home.features.titleB": "یو ځیرک پلیټفارم",
  "home.features.subtitle": "ستاسو په خپلو ټکو کې له لومړي پوښتنې تر د موسم بشپړ ریکارډ — هره وسیله بلې ته ځواک ورکوي.",
  "home.features.advisorModule": "ماډیول 01 · سلاکار",
  "home.features.advisorTitle": "د کرنې AI سلاکار",
  "home.features.advisorTopics": "اوبه · سره · حشرات او ناروغۍ · رېبل",
  "home.features.advisorBadge": "رومن پښتو",
  "home.features.advisorMockAria": "د زیړو پاڼو لرونکي غنم په اړه له اګروپیو سلاکار سره بېلګه ییز خبرې",
  "home.features.advisorUserMsg": "زما غنم پاڼې زیږې کیږي — څه وکړم؟",
  "home.features.advisorReplyTitle": "زیړې پاڼې — دوه عام لاملونه:",
  "home.features.advisorReplyCause1": "د اوبو کمښت",
  "home.features.advisorReplyCause1Rest": "— په سوړ وختونو کې، له سهار ۹ بجو مخکې اوبه ورکړئ.",
  "home.features.advisorReplyCause2": "د نایتروجن کمښت",
  "home.features.advisorReplyCause2Rest": "— لرغونې پاڼې لومړۍ وګورئ؛ که اړتیا وي یوریه واچوئ.",
  "home.features.advisorReplyFooter": "که د پاڼو لاندې زیړې کرښې ښکاري، انځور راولېږئ — زه به ناروغي تشخیص کړم.",
  "home.features.advisorInputPlaceholder": "خپله پوښتنه ولیکئ یا ویاست…",
  "home.features.advisorFooter": "د فصل په اړه هر څه پوښتئ — ورځني پوښتنې ښه راغلاست.",
  "home.features.recordsModule": "ماډیول 02 · ریکارډ",
  "home.features.recordsTitle": "ډیجیټل کروندې ریکارډ",
  "home.features.recordsDesc": "هره کار منظم ثبت — ترڅو مشوره ستاسو له خپle ځمکې زده کړه وکړي.",
  "home.features.record1Activity": "اوبه",
  "home.features.record1Detail": "کانال · ۴۰ دقیقې",
  "home.features.record2Activity": "یوریا ۴۶٪ N",
  "home.features.record2Detail": "۲۵ کیلو / جریب",
  "home.features.record3Activity": "د پاڼو سکن",
  "home.features.record3Detail": "نوره ناروغي نه وه",
  "home.features.recordsCropTag": "غنم · ربیع موسم",
  "home.features.languageModule": "ماډیول 03 · ژبه",
  "home.features.languageTitle": "ستاسو ژبه، ستاسو ټکي",
  "home.features.languageDesc": "هغسې ویاست یا ولیکئ لکه هغسې چې فکر کوئ — تخنیکي انګلیسي ته اړتیا نشته.",
  "home.features.weatherModule": "ماډیول 04 · هوا",
  "home.features.weatherTitle": "له هوا خبر لارښوونه",
  "home.features.weatherDesc": "مشوره له رسېدو مخکې ریښتیني حالات ګوري — د باران دمخه سپرې وکړئ او ټول مصرف اوبه شو.",
  "home.features.weatherMockAria": "د پنځو ورځو وړاندوینه چې پنجشنبه د سپرې بندیز ورځ ټاکي",
  "home.features.dayMon": "دوشنبه",
  "home.features.dayTue": "سه‌شنبه",
  "home.features.dayWed": "چهارشنبه",
  "home.features.dayThu": "پنجشنبه",
  "home.features.dayFri": "جمعه",
  "home.features.holdSpray": "سپره وباسه",
  "home.features.weatherLegend": "د سیمه ایزې وړاندوینې له مخې د مشورې ورځ ټاکل شوې",
  "home.features.moreLink": "پلیټفارم پراخیږي — بشپړې وسیلې وګورئ",
  "home.journey.eyebrow": "دا څنګه کار کوي",
  "home.journey.title": "یوه پوښتنه موسم پیلیږي",
  "home.journey.subtitle": "له ستاسو لومړنۍ پوښتنې تر بشپړې ځیرکې کروندې تاریخ ساده لار.",
  "home.journey.step1Title": "خپله کرونده اضافه کړئ",
  "home.journey.step1Body": "د ډیجیټل پروفایل جوړولو لپاره موقعیت، فصل او بنسټیز معلومات ولیکئ.",
  "home.journey.step2Title": "له AI پوښتئ",
  "home.journey.step2Body": "خپله پوښتنه په هغه ژبه ولیکئ یا ویاست چې تر ټوله آرام یې یاست.",
  "home.journey.step3Title": "لارښوونه ترلاسه کړئ",
  "home.journey.step3Body": "د فصل، هوا، موقعیت او کروندې تاریخ پر بنسټ مشوره ترلاسه کړئ.",
  "home.journey.step4Title": "کار ثبت کړئ",
  "home.journey.step4Body": "په څو ټیکونو اوبه، سره، درمل یا ناروغي ثبت کړئ.",
  "home.journey.step5Title": "تاریخ جوړ کړئ",
  "home.journey.step5Body": "هر ریکارډ راتلونکې مشورې ځیرکې او مناسبه کوي.",
  "home.journey.step6Title": "کتنه ادامه ورکړئ",
  "home.journey.step6Body": "د موسم په اوږدو کې ریکارډونه وګورئ او پرمختګ تعقیب کړئ.",
  "home.matrix.eyebrow": "بشپړې وسیلې",
  "home.matrix.title": "له اړتیاوو تر حیرانونکو",
  "home.matrix.subtitle": "هره وسیله فصل خوندي ساتي، لګښت کموي یا عاید زیاتوي. یې لکه تقویم ولولئ — هر پوړ پر بل جوړ دی.",
  "home.matrix.capabilitiesLabel": "وسایل",
  "home.matrix.tier1Name": "بنسټیز",
  "home.matrix.tier1Badge": "بنسټ",
  "home.matrix.t1f1Title": "د فصل ناروغۍ پیژندنه",
  "home.matrix.t1f1Body": "د اغېزمنې پاڼې انځور اپلوډ کړئ او سمدلاسه تشخیص، درجه او درملنه ترلاسه کړئ.",
  "home.matrix.t1f2Title": "سپوږمکۍ کره کتنه",
  "home.matrix.t1f2Body": "د کري حدود نشان کړئ او له وړیا سینټینل-۲ انځورونو NDVI روغتیایي ساحې وګورئ.",
  "home.matrix.t1f3Title": "ځیرکه هوا مشوره",
  "home.matrix.t1f3Body": "سیمه ایزه وړاندوینه ستاسو له فصل او د ودې پړاو سره یوځای ورځنۍ عملي مشوره کیږي.",
  "home.matrix.t1f4Title": "بازار نرخ تعقیب او وړاندوینه",
  "home.matrix.t1f4Body": "نږدې بازار نرخونه د AI میلان سره وګورئ، ترڅو سم وخت پلورئ.",
  "home.matrix.tier2Name": "توپير کوونکې",
  "home.matrix.tier2Badge": "ځلېدونکی",
  "home.matrix.t2f1Title": "سیمه ایزو ژبو غږیز چیټ بوٹ",
  "home.matrix.t2f1Body": "په اردو، پنجابي، سرائیکي او نورو ویاست یا ولیکئ — ځواب په هغه ژبه واورئ چې ښه یې پوهیږئ.",
  "home.matrix.t2f2Title": "د حکومتي طرحې سمون",
  "home.matrix.t2f2Body": "خپل معلومات دننه کړئ او هره اهله طرحه ومومئ، له اسنادو او د غوښتنې لنکونو سره.",
  "home.matrix.t2f3Title": "د فصل سپارښتنه انجن",
  "home.matrix.t2f3Body": "دې موسم کې ستاسو د خاورې، هوا، بازار غوښتنې او بودجې سره سم تر ټولو ګټور فصل.",
  "home.matrix.t2f4Title": "د کروندې ګټ/زیان محاسب",
  "home.matrix.t2f4Body": "اټکلي او اصلي لګښتونه، حاصل، عاید او ګټ — د بریک ایون او ROI سره.",
  "home.matrix.t2f5Title": "کمیونټي فورم + متخصص اتصال",
  "home.matrix.t2f5Body": "پوښتنې شې کړئ، انځورونه شریک کړئ، له ملګرو بزګانو او تصدیق شویو متخصصینو ځواب ترلاسه کړئ.",
  "home.matrix.tier3Name": "حیرانوونکې",
  "home.matrix.tier3Badge": "له میدانه مخکې",
  "home.matrix.t3f1Title": "د سپوږمکۍ بدلون کشف",
  "home.matrix.t3f1Body": "د وخت په تیریدو سپوږمکیو انځورونه د سلایډر سره پرتله کړئ — ودې، زیان یا قابضا تعقیب کړئ.",
  "home.matrix.t3f2Title": "د حشراتو د برید وړاندوینه",
  "home.matrix.t3f2Body": "د هوا، د فصل پړاو او تاریخ پر بنسټ له احتمالي برید مخکې خبردارۍ.",
  "home.matrix.t3f3Title": "غږ لومړی تلیفونی حالت",
  "home.matrix.t3f3Body": "وړیا شمېره ووهئ، پوښتنه ویاست، په خپله ژبه مشوره واورئ — سمارټ فون ته اړتیا نشته.",
  "home.matrix.t3f4Title": "د کاربن کریډټ اټکل",
  "home.matrix.t3f4Body": "پایداوال طریقې ثبت کړئ او له رضاکارانه مارکیټونو کاربن کریډټ اټکل کړئ.",
  "home.matrix.t3f5Title": "آفلاین PWA + SMS خبردارۍ",
  "home.matrix.t3f5Body": "په کره کې آفلاین کار کوي، له اتصال سره سنکیږي، په کمزوري شبکه کې SMS درولېږي.",
  "home.vision.eyebrow": "لیدلوری",
  "home.vision.titleA": "د پاکستان لپاره جوړ شوی.",
  "home.vision.titleB": "د نړۍ لپاره چمتو.",
  "home.vision.pkTitle": "پاکستان لومړی تګلاره",
  "home.vision.pkBody": "لومړۍ نسخه د پاکستان کروندو لپاره ډیزاین شوې ده: سیمه ییز فصلونه، سیمه ییزې ژبې، ریښتینې بزګرۍ طريقې او ریښتیني کښتي شرایط.",
  "home.vision.pkPoint1": "سیمه ییز فصل او اقلیم پوهه",
  "home.vision.pkPoint2": "اردو، پنجابي، پښتو، سندهي، سرائيکي، بلوچي، هندکو",
  "home.vision.pkPoint3": "د ریښتینو بزګرانو له نظرونو سره سم ښه شوی",
  "home.vision.worldTitle": "نړیوالې پراختیا لیدلوری",
  "home.vision.worldBody": "د برابرېدو لپاره جوړ شوی. کله چې پلیټفارم پاخه شي، نوي هېوادونو، ژبو، فصلونو او اقلیمونو ته غځېږي — له سره بیا جوړولو پرته.",
  "home.vision.worldPoint1": "د هر هېواد د کرنې ځانګړې پوهه",
  "home.vision.worldPoint2": "اضافي ژبې او سیمه ییز فصلونه",
  "home.vision.worldPoint3": "ژورې ډاټا یوځای کېدنې او شننې",
  "home.users.title1": "انفرادي بزګران",
  "home.users.desc1": "کوچنۍ او منځنۍ کروندې چې عملي مشورې او د هر کار تنظیم شوی ریکارډ ته اړتیا لري.",
  "home.users.title2": "تجارتي کروندې",
  "home.users.desc2": "کرنيز سوداګرۍ چې تنظیم شوي معلومات، د پرېکړې ملاتړ او د ټیم ریکارډونه ته اړتیا لري.",
  "home.users.title3": "ایکوسیستم شریکان",
  "home.users.desc3": "این پټ رسوونکي، کوآپریټیفونه، بیمه او د پراختیا خدمتونه چې په وخت سره پلیټفارم ته راځي.",
  "home.users.tagline": "لومړی بزګرانو لپاره ډیزاین شوی — له ایکوسیستم سره وده کوونکی",
  "home.cta.eyebrow": "لومړنی لاسرسی",
  "home.cta.title": "خپله کرونده پلیټفارم ته راوړئ",
  "home.cta.subtitle": "د اګروپیو سره د ښې پرېکړې کوونکو بزګرانو له ډلې شئ — له پاکستان پیل، په ټوله نړۍ کې پراختیا.",
  "home.cta.success": "تاسو په لیست کې یاست. کله چې ستاسو سیمه خلاصه شي، موږ به درسره اړیکه ونیسو.",
  "home.cta.emailLabel": "بریښنالیک پته",
  "home.cta.fineprint": "اسپیم نشته. هر وخت یې ان سبسکرایب کولای شئ.",
  "home.footer.tagline": "د مصنوعي ځیرکتیا کروندې پوهه پلیټفارم. مشورې، سپوږمکۍ کتنه، بازار نرخونه او ریکارډونه — خاوره او سګنل، یوځای.",
  "home.footer.pagesHeading": "پاڼې",
  "home.footer.pagesNavLabel": "د فوټر پاڼې",
  "home.footer.legalHeading": "قانوني",
  "home.footer.legalNavLabel": "قانوني",
  "home.footer.privacy": "د محرمیت تګلاره",
  "home.footer.terms": "د خدمت شرایط",
  "home.footer.cookies": "د کوکیز تګلاره",
  "home.footer.disclaimer": "اعلامیه",
  "home.footer.contactHeading": "اړیکه ونیسئ",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اګروپیو. ټول حقونه خوندي دي.",
  "home.footer.motto": "د پاکستان لپاره جوړ · د نړۍ لپاره چمتو",
  "hiw.meta.title": "دا څنګه کار کوي — اګروپیو",
  "hiw.meta.description":
    "له یو دقیقې کروندې پروفایل څخه تر دوامداره ښه کېدونکي فصلي سایکل پورې: وګورئ چې اګروپیو پوښتنې، فعالیتونه او ریکارډونه څنګه شخصي کرهني لارښوونې ته اړوي.",
  "hiw.hero.eyebrow": "دا څنګه کار کوي",
  "hiw.hero.titleA": "شپږ کوچني ګامه.",
  "hiw.hero.titleLead": "یو",
  "hiw.hero.titleAccent": "زیات هوښیار فصل.",
  "hiw.hero.subtitle":
    "اګروپیو هماغسې کار کوي لکه بزګري چې لا دمخاله کیږي — تاسو کښت کوئ، پوښتنه کوئ، کار کوئ او ریکارډ کوئ. توپير یوازې دا دی چې اوس هر ګام بل زده کوي.",
  "hiw.hero.browseFeatures": "ځانګړنې وګورئ",
  "hiw.route.navLabel": "د اګروپیو فصلي سایکل شپږ ګامه",
  "hiw.route.stepLabel": "ګام {n}: {stop}",
  "hiw.route.stop1": "کرونده جوړه کړئ",
  "hiw.route.stop2": "پوښتنه وکړئ",
  "hiw.route.stop3": "لارښوونه",
  "hiw.route.stop4": "کار وکړئ",
  "hiw.route.stop5": "ریکارډ",
  "hiw.route.stop6": "غوره مشوره",
  "hiw.setup.eyebrow": "یو ځل سیټ اپ کړئ",
  "hiw.setup.title": "ستاسو کرونده ژوندی پروفایل جوړیږي",
  "hiw.setup.body":
    "څلور خانې، یو دقیقې کم — ولسوالی، فصل، د کښت نېټه او د ځمکې مساحت. همدا ټوله فورمه ده. له دې وروسته هر ځواب پوهیږي چې دا چېرته او په کومو حالاتو کې ودېږي.",
  "hiw.setup.point1": "فصل بدله کړئ یا په هر وخت کروندې زیاتې کړئ",
  "hiw.setup.point2": "د قرارداديانو او سوداگریزو استازو لپاره څو کروندې",
  "hiw.setup.point3": "هېڅ تخنیکي څه نه پوښتل کیږي — د خاورې راپور ته اړتیا نشته",
  "hiw.setup.mockHeading": "نوې کروندې پروفایل",
  "hiw.setup.mockButton": "د کروندې پروفایل جوړ کړئ",
  "hiw.setup.mockFootnote": "له یو دقیقې کم وخت نیسي",
  "hiw.setup.mockLabel":
    "د کروندې پروفایل فورمه چې ولسوالی، فصل، د کښت نېټه او د ځمکې مساحت پکې ډک دي",
  "hiw.setup.rowDistrict": "ولسوالي",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "غنم · ربيع",
  "hiw.setup.rowSowing": "د کښت نېټه",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "ځمکه",
  "hiw.setup.valLand": "۱۲ ایکړه",
  "hiw.ask.eyebrow": "هر څه وپوښتئ",
  "hiw.ask.titleA": "یوه پوښتنه داخلیږي.",
  "hiw.ask.titleB": "ستاسو ټوله کرونده ځواب ورکوي.",
  "hiw.ask.body":
    "یوه پوښتنه په بیلابیلو کروندو کې بیل معنا لري. نو له ځوابولو دمخاله اګروپیو پوښتنه د ستاسو کروندې په اړه له هرې هغې خبرې سره پرتله کوي چې دمخاله یې پوهیږي.",
  "hiw.ask.pipelineLabel":
    "د بزګر پوښتنه د فصل، ولسوالۍ، موسم او تاریخچې له شرایطو سره یوځای کیږي ترڅو شخصي ځواب جوړ شي",
  "hiw.ask.question": "اوس اوبه ورکول سم دي یا لږ انتظار؟",
  "hiw.ask.checkedAgainst": "د دې شیانو سره پرتله کیږي",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "غنم · ودانېدو پوره",
  "hiw.ask.chipDistrict": "ولسوالي",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26° • وچه اونۍ",
  "hiw.ask.chipHistory": "تاریخچه",
  "hiw.ask.chipValHistory": "یوریا ۹ ورځې دمخه",
  "hiw.ask.answer":
    "دوې ورځې تم شه — د باران امکان شته، او له یوریا وروسته ځمکه لا لنده ده. تر جمعې پورې کتل کافي دي.",
  "hiw.ask.answerMeta": "شخصي ځواب • غنم، له یوریا ۹ ورځې وروسته",
  "hiw.ask.footnote": "لیکئ، ویاست یا زنګ ووهئ — ځواب په هره بڼه ستاسو د کروندې ځانګړی وي",
  "hiw.engine.eyebrow": "له ځواب شاته",
  "hiw.engine.title": "څلور کتنې له دې دمخه چې تاسو یوه کرښه وګورئ",
  "hiw.engine.body":
    "لارښوونه د پلټنې پایله نه ده. دا له څلورو دروازو تیریږي ترڅو هغه څه چې ستاسو ته رسیږي د همدې کښتۍ، همدې اونۍ لپاره خوندي وي.",
  "hiw.engine.check1Title": "معلومات راټولول",
  "hiw.engine.check1Desc":
    "د کروندې پروفایل، سمه هوا او د فصل پړاو د لیږلو په شېبه سره یوځای راټولیږي.",
  "hiw.engine.check2Title": "د پرتلنې کتنه",
  "hiw.engine.check2Desc":
    "مشوره د هوا له وینا سره ازمویل کیږي — هغه سپرې چې باران به یې ضایع کړي انجن پرېنوزي.",
  "hiw.engine.check3Title": "شخصي کول",
  "hiw.engine.check3Desc":
    "ستاسو د کښتۍ تاریخچه ځواب بدلوي — هماغه فصل، بله خاوره، بله مشوره.",
  "hiw.engine.check4Title": "رسول",
  "hiw.engine.check4Desc":
    "بیا ستاسو په ژبه د روښانه ګامونو په بڼه راځي — پر سکرین، په غږ یا په تلیفوني اړیکه.",
  "hiw.engine.safetyStrong": "که څه خطرناک ښکاري،",
  "hiw.engine.safetyRest":
    "اګروپیو انتظار وايي — ناوخته ځواب د ضایع شوې سپرې یا ویجاړې فصل څخه غوره دی.",
  "hiw.record.recorderHeading": "فعالیت ثبت کړئ",
  "hiw.record.syncBadge": "اتومات سنک فعال",
  "hiw.record.actionIrrigation": "اوبه ورکول",
  "hiw.record.actionFertiliser": "سره",
  "hiw.record.actionPesticide": "حشره کش",
  "hiw.record.actionDisease": "ناروغي",
  "hiw.record.actionExpense": "لګښت",
  "hiw.record.actionHarvest": "د فصل ریښتیا",
  "hiw.record.row1Time": "نن • سهار 6:40",
  "hiw.record.row1Label": "اوبه ورکول ثبت شول",
  "hiw.record.row1Detail": "د کانال تاو • ۴۰ دقیقې • پلاټ B",
  "hiw.record.row2Time": "پرون",
  "hiw.record.row2Label": "سره ثبت شوه",
  "hiw.record.row2Detail": "DAP ۲۰ کیلو / ایکړه",
  "hiw.record.offlineNote": "→ هر ثبت یوازې دوه ټېپونه — افلاین هم کار کوي",
  "hiw.record.mockLabel":
    "د فعالیت ثبتونکی چې چټک عمل چیپونه او نوي ثبت شوي کتارونه لري",
  "hiw.record.eyebrow": "له کار سره سم ثبت کړئ",
  "hiw.record.titleA": "اوس دوه ټېپونه،",
  "hiw.record.titleB": "ټول فصل غوره ځوابونه",
  "hiw.record.body":
    "ثبت د کښتۍ لپاره جوړ شوی — لوی تڼۍ، لږ خانې، د ټایپ کولو اړتیا نشته. هر ثبت د کروندې حافظې برخه کیږي، نو مشوره هم له فصل سره سم تېره کیږي.",
  "hiw.record.point1": "اوبه، سرې، ناروغۍ، لګښتونه، فصل — یوه ټایملاین",
  "hiw.record.point2": "بشپړ افلاین کار کوي؛ د سیګنال په راتګ خودکار سنک کیږي",
  "hiw.record.point3": "د بانکونو، پیرودونکو یا بیمې لپاره فصلي لنډیز چمتو",
  "hiw.loop.eyebrow": "فصلي سایکل",
  "hiw.loop.titleA": "دا د فصل پرېکولو پای نه لري.",
  "hiw.loop.titleB": "له هغه ځایه پیل کیږي.",
  "hiw.loop.body":
    "پوښتنه، کار، ثبت — بیا بیا. د سایکل هر څرخ اګروپیو ته ستاسو د ځمکې په اړه نوی څه زده کوي، ترڅو راتلونکی فصل له تېري څخه مخکې پیل شي.",
  "hiw.loop.benefit1Title": "مشوره پانګه جمع کوي",
  "hiw.loop.benefit1Desc":
    "د تېر فصل ناروغۍ، اندازې او نېټې د دې فصل لومړنی ځواب جوړوي.",
  "hiw.loop.benefit2Title": "هېڅ تکرار نه کیږي",
  "hiw.loop.benefit2Desc":
    "مشاورې پوهیږي چې څه دمخه سپری یا سره شوې — د دوه ځله اندازې خطر نشته.",
  "hiw.loop.benefit3Title": "هر فصل مستند",
  "hiw.loop.benefit3Desc":
    "پاک تاریخچه د پورونو، پیرودونکو، بیمې یا راتلونکي فصلي پرېکړې لپاره چمتو پاتې کیږي.",
    "hiw.loop.stepLearn": "زده کړه",
  "hiw.loop.stepImprove": "ښه کړه",
"hiw.loop.diagramLabel": "کړۍ ډیاګرام: پوښتنه، کار، ثبت، زده کړه، ښه کول",
  "hiw.loop.centerSeason": "فصل",
  "hiw.loop.centerLoop": "سایکل",
  "hiw.loop.caption": "هر فصل، له تېري څخه غوره",
  "feat.meta.title": "ځانګړنې — اګروپیو",
  "feat.meta.description": "د اګروپیو هره ځانګړنه وګورئ: د AI فصل ډاکټر، د سپوږمکۍ NDVI څارنه، د منډي بیو وړاندوینه، په سیمه‌ییزو ژبو کې غږیز مشوره، له انټرنېټ پرته لاسرسی او SMS خبرتیاوې، او ډېر نور.",
  "feat.hero.eyebrow": "ځانګړنې",
  "feat.hero.titleLead": "ستاسو د موسم هره",
  "feat.hero.titleAccent": "اړتیا بشپړه",
  "feat.hero.subtitle": "څوارلس ځانګړنې یو ځای کار کوي — پاڼې سکین کوي، له فضا کې کره ګوري، منډي لوستله کوي او ستاسو په ژبه غږیږي. وګورئ هره یوه ستاسو فارم ته څه ورکوي.",
  "feat.hero.ctaPrimary": "لومړنی لاسرسی ترلاسه کړئ",
  "feat.hero.ctaSecondary": "دا څنګه کار کوي وګورئ",
  "feat.hero.builtFor": "د پاکستان لپاره جوړ شوی",
  "feat.hero.productOf": "د Aplinode محصول",
  "feat.hero.tile1Label": "پاڼه سکین",
  "feat.hero.tile1Value": "94% سالم",
  "feat.hero.tile2Label": "منډي غنم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کره",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "د حشرات ګواښ",
  "feat.hero.tile4Value": "ټیټ · 7 ورځې",
  "feat.hero.voiceReady": "غږیزه مشوره چمتو ده",
  "feat.hero.voiceLangs": "اردو · پنجابي · سرائیکي",
  "feat.hero.liveBadge": "ژوندۍ",
  "feat.hero.smsLabel": "SMS خبرتیا · آف لاین حالت",
  "feat.hero.smsMsg": "باران 3 غرمه — سپرې ودروئ",
  "feat.intel.eyebrow": "د فصل پوهه",
  "feat.intel.heading": "ستونزې له زیان مخکې وګورئ",
  "feat.intel.sub": "ناروغي، حشرات، موسم او د فصل ټاکنه — څلور پرېکړې چې فصل ټاکي، هره یوه خپل ماشین سره.",
  "feat.intel.included": "شامل دي",
  "feat.intel.doctorCode": "F·01 · لیدنه",
  "feat.intel.doctorTitle": "د AI فصل ډاکټر",
  "feat.intel.doctorDesc": "د ناوړه پاڼې انځور واخلئ او په څو ثانیو کې د ناروغي نوم، شدت او درملنې پلان ترلاسه کړئ.",
  "feat.intel.doctorMock": "د پاڼې سکین پایله چې زرد زنګ لوړ باور سره تشخیص کړی",
  "feat.intel.diseaseName": "زرد زنګ",
  "feat.intel.matchScore": "94% ورته والی",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "منځنی",
  "feat.intel.pestCode": "F·02 · وړاندوینه",
  "feat.intel.pestTitle": "د حشراتو برید خبرتیاوې",
  "feat.intel.pestDesc": "موسم او د فصل مرحله ګواښ ماډل ته تغذیه ورکوي چې له برید یوه ورځ مخکې خبرداری ورکوي.",
  "feat.intel.pestMock": "اووه ورځو د حشراتو ګواښ چارټ چې شپږمه ورځ لوړوالی ته ځي",
  "feat.intel.pestAlert": "شنبه · د ٹوډو ګواښ 74% — نوې غنمه وساتئ",
  "feat.intel.weatherCode": "F·03 · هوا",
  "feat.intel.weatherTitle": "د هوا مطابق مشورې",
  "feat.intel.weatherDesc": "سیمه‌ییزې وړاندوینې ستاسو فصل او د ودې مرحلې سره برابرېږي — مشوره روښانه لارښود راځي، خام معلومات نه.",
  "feat.intel.weatherMock": "مثالي هوا مشوره چې له باران مخکې اوبو ورکول وځنډوي",
  "feat.intel.delayIrrigation": "نن اوبو ورکول وځنډوئ",
  "feat.intel.rainNote": "غرمه 3 بجې د باران احتمال — لومړی اسمان کره خړوبوي.",
  "feat.intel.waterSaved": "د اوبو سپما",
  "feat.intel.cropCode": "F·04 · پلان جوړونه",
  "feat.intel.cropTitle": "د فصل سپارښتنه",
  "feat.intel.cropDesc": "خاوره، موسم، غوښتنه او ستاسو بودجه یو ځای ارزول کیږي — هغه ومېږئ چې دې موسم ګټه درکړي.",
  "feat.intel.cropMock": "درجه بندي شوې فصل سپارښتنې چې غنم یې سر کې دی",
  "feat.intel.crop1": "غنم",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "نخود",
  "feat.field.eyebrow": "کره او منډي پوهه",
  "feat.field.headingA": "ستاسو ځمکه له فضا کې کتل کیږي.",
  "feat.field.headingB": "ستاسو فصل له معلوماتو سره پرتله کیږي.",
  "feat.field.sub": "هر ایکړ ته د سپوږمکۍ کتنې او هرې نږدې منډي کتنه — ترڅو وده او پلور دواړه سم وخت وي.",
  "feat.field.ndviCode": "F·05 · سپوږمکی",
  "feat.field.ndviTitle": "NDVI کره څارنه",
  "feat.field.ndviDesc": "خپله پوله یو ځل په نښه کړئ؛ په هر روښانه سپوږمکۍ تېرېدو کې د روغتیا زونونه تازه کیږي — کمزوري برخې له سترګو مخکې راښکاره کیږي.",
  "feat.field.ndviMock": "د کروندې روغتیا ګریډ چې تور شین قوي فصل وده ښیي",
  "feat.field.weakZone": "کمزوری زون · قطار 2",
  "feat.field.priceCode": "F·06 · منډي",
  "feat.field.priceTitle": "د منډي بیو وړاندوینه",
  "feat.field.priceDesc": "نږدې منډیو اوسني نرخونه او د رجحان وړاندوینه — هغه مهال وپلورئ کله چې ګراف وايي، نه کله چې اخیستونکی وايي.",
  "feat.field.priceMock": "د غنمو بیو رجحان اتو اونیو کې لوړوالۍ ته، د ودېرو سپارښتنه سره",
  "feat.field.wheatTrend": "غنم · 8 اونۍ",
  "feat.field.holdStock": "↑ 12% — ماله وساتئ",
  "feat.field.financeCode": "F·07 · مالیې",
  "feat.field.financeTitle": "ګټه زیان تعقیب",
  "feat.field.financeDesc": "هره روپیې راتګ او تګ، بشپړ موسم — له منډي یا بانک مخکې بریک ایوین او ROI چمتو.",
  "feat.field.ledgerMock": "فصلي مصارف ثبت چې ان پټ، کارګري، اوبو او عاید لري",
  "feat.field.rowInputs": "ان پټونه",
  "feat.field.rowLabour": "کارګري",
  "feat.field.rowIrrigation": "اوبو ورکول",
  "feat.field.rowRevenue": "عاید (اټکل)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "د ټولو لپاره لاسرسی",
  "feat.voice.headingA": "سمارټ فون نشته؟",
  "feat.voice.headingB": "انګلیسي نه؟ بیا هم شامل.",
  "feat.voice.sub": "بهترینه مشوره بې ګټه ده که بزګر ته ونه رسېږي. هره ځانګړنه تلیفوني اړیکې ته ځواب وایي، غږ اوري او له سیګنال پرته سیمه کې هم کار کوي.",
  "feat.voice.speakCode": "F·08 · غږ",
  "feat.voice.speakTitle": "خپله پوښتنه ووایاست",
  "feat.voice.speakMock": "په رومن پښتو کې د مشورې سره غږیز خبرې اترې",
  "feat.voice.chatUser": "زما فصل پاڼو داغونه دي",
  "feat.voice.chatAdvisor": "د داغونو انځور راولېږئ — سمدلاسه تشخیص کوم.",
  "feat.voice.inputPlaceholder": "په غږ پوښتنه وکړئ…",
  "feat.voice.callCode": "F·09 · اړیکه",
  "feat.voice.callTitle": "وړیا تلیفون نمبر ولګوئ",
  "feat.voice.callMock": "د اګروپیو غږیز مرستیال سره د وړیا اړیکې نقل",
  "feat.voice.greetingLine": "اګروپیو ته ښه راغلاست",
  "feat.voice.heardLine": "غږ واورید — ځواب چمتو دی",
  "feat.voice.callEnded": "اړیکه پای · لنډیز خوندي",
  "feat.voice.anyPhone": "هر تلیفون · انټرنېټ ته اړتیا نشته",
  "feat.voice.offlineCode": "F·10 · آف لاین + SMS",
  "feat.voice.offlineTitle": "له سیګنال پرته سیمې هم نه دریږي",
  "feat.voice.offlineDesc": "مشورې، ریکارډونه او کیلکولیټر له سیګنال پرته کار کوي؛ د نیټ ورک بیرته راتګ سره هرڅه سنک کیږي او مهم خبرتیاوې SMS راځي.",
  "feat.voice.networkStatus": "د نیټ حالت",
  "feat.voice.offlineQueued": "آف لاین · 3 ریکارډونه په قطار کې",
  "feat.voice.smsStamp": "SMS · 07:42",
  "feat.voice.smsMsg": "د هوا خبرتیا: باران غرمه 3 بجې — د سپرې وخت بدل کړئ.",
  "feat.manage.eyebrow": "اداره او وده",
  "feat.manage.headingA": "مشوره پیل ده.",
  "feat.manage.headingB": "پاتې ټول په ریکارډ چلي.",
  "feat.manage.sub": "تاریخچه، سبسیدي، دوامدارتیا او د بزګرانو ټولنه — خامې ځانګړنې چې هر موسم راټولیږي.",
  "feat.manage.diaryCode": "F·11 · ریکارډونه",
  "feat.manage.diaryTitle": "ډیجیټل فارم ورځنی",
  "feat.manage.diaryDesc": "له اوبو ورکولو تر حاصل راټولولو، ټول په یوه ټایم لاین کې چې مشوره له ځواب مخکې لولي.",
  "feat.manage.timelineMock": "د اګست فارم فعالیت ټایم لاین",
  "feat.manage.tl1Date": "12 اګست",
  "feat.manage.tl1Label": "اوبو ورکول",
  "feat.manage.tl1Detail": "د کانال وار · 40 دقیقې",
  "feat.manage.tl2Date": "09 اګست",
  "feat.manage.tl2Label": "یوریه ورکړل شو",
  "feat.manage.tl2Detail": "25 کیلو / ایکړ",
  "feat.manage.tl3Date": "02 اګست",
  "feat.manage.tl3Label": "پاڼه سکین",
  "feat.manage.tl3Detail": "روغ · کومه ناروغي نشته",
  "feat.manage.schemeCode": "F·12 · سکیمونه",
  "feat.manage.schemeTitle": "سبسیدي او سکیم موندل",
  "feat.manage.schemeDesc": "حکومتي پیسې چې تاسو لا دمخه یې اهل یاست — موندل، تشریح او یو ټیپ غوښتنې ته ونښلول کیږي.",
  "feat.manage.checklistMock": "د اهلیت چیک لیست چې له څلورو درې شرطونه بشپړ دي",
  "feat.manage.check1": "د ځمکې تصدیق شوې",
  "feat.manage.check2": "د فصل موسم سمون لري",
  "feat.manage.check3": "پیژندپاڼه ثبت شوې",
  "feat.manage.check4": "بانکي حساب ونښلول شو",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% چمتو",
  "feat.manage.carbonCode": "F·13 · دوامدارتیا",
  "feat.manage.carbonTitle": "د شین طریقو انعامونه",
  "feat.manage.carbonDesc": "بیولوژیکي او کمې کیندنې طریقې ثبت کړئ؛ سپوږمکۍ شین پوښښ تصدیقوي او د کاربن کریډټ ارزښت اټکلوي.",
  "feat.manage.carbonMock": "کاربن لنډیز چې نیول شوې ټنه او کلني اټکل شوی ارزښت لري",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریډټ ارزښت / کال",
  "feat.manage.forumCode": "F·14 · ټولنه",
  "feat.manage.forumTitle": "بزګر فورم + متخصصین",
  "feat.manage.forumDesc": "ستونزه پوسټ کړئ، له هغو بزګرانو ځواب ترلاسه کړئ چې پخپله مخ شوي — تصدیق شوي متخصصین سم حل په نښه کوي.",
  "feat.manage.threadMock": "د ټولنې بحث چې د متخصص تصدیق شوې ځواب لري",
  "feat.manage.threadQuestion": "په کپاس کې د سپین مچ غوره درملنه؟",
  "feat.manage.threadMeta": "ملتان · 12 ځوابونه · 34 رایې",
  "feat.manage.expertBadge": "د متخصص تصدیق شوې ځواب",
  "feat.manage.threadAnswer": "د نییم تیل سپرې، ماسپښین — دوه ځله، په 5 ورځو وقفه.",
};
