import type { CatalogKey } from "./en.ts";

/** Pashto (پښتو) — AI-translated. RTL language. */
export const ps: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اګروپیو طور ته ایاست؟",
  "nav.features": "ځانګړتیاوې",
  "nav.howItWorks": "دا څنګه کارووي",
  "nav.vision": "موږ سره ویسون",
  "nav.signIn": "ننوزرکوئ",
  "nav.signUp": "ګراونی رواني کړئ",
  "nav.getEarlyAccess": "مخکینی رسایی تر لاسه کړئ",
  "nav.openMenu": "مینو خلاصه کړئ",
  "nav.closeMenu": "مینو بند کړئ",
  "nav.dashboard": "ډیشبورډ",
  "common.languageSwitcherLabel": "ژبه بدل کړئ",
  "notFound.title": "صفحه شته نه دی",
  "notFound.body": "هغه صفحه چې تاسو لټوي شته نه دی یا بدله شوی وي.",
  "notFound.backHome": "اګروپیو اصلي په شته برګرئ",
  "common.builtForPakistan": "پاکستان لپاره جوړ شوی",
  "common.productOfAplinode": "اپلینوډ ته یوه پروډکټ",
  "home.hero.eyebrow": "مصنوعی هوښه پر بڼه د ځمکی هوښه پلیټفارم",
  "home.hero.titleLead": "تر اټکل لپاره",
  "home.hero.titleAccent": "泽赫نه کښتکاری",
  "home.hero.subtitle": "یوه یوازې پلیټفارم چې AI مشير، سیټلایټ مانیټرنګ، بازاری قیمته، او ستا د ځمکی یاداشتې په یوه ځای یوځای کوي — ډیټا ته واضح وړتیاوې ته بدلووي، ستا د خپلې ژبه کې.",
  "home.hero.ctaSecondary": "وګورئ کومته څنګه کارووي",
  "home.hero.imageAlt": "کښتکار د ټبلیټ پر اګروپیو استعمال کوي په کشتی ټکي کې",
  "home.hero.readingCrop": "د کشت په进展情况",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "د خاورو نمی",
  "home.hero.noteExcellent": "ښه",
  "home.hero.noteClearSky": "ساف آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "اګروپیو پلیټفارم توانایي",
  "home.ticker.cropDoctor": "AI د کشت ډاکټر",
  "home.ticker.satelliteNdvi": "سیټلایټ NDVI مانیټرنګ",
  "home.ticker.mandiPrices": "منډی قیمتو اعلان",
  "home.ticker.weatherAdvisories": "موسمی مشورې",
  "home.ticker.farmRecords": "ډیجیټل د ځمکه یاداشتې",
  "home.ticker.advisoryLanguages": "۷ ژبو میش مشوره",
  "home.ticker.pestAlerts": "د حشراتو خطرې اعلان",
  "home.ticker.offlineSms": "آفلاین + SMS",
  "home.problem.eyebrow": "ستونزه",
  "home.problem.title": "د کښتکاری وړتیاوې نشته ډاګه وي",
  "home.problem.subtitle": "د پاکستان په ټولو پهځای کې کښتکار روایت، محلي مشورې، او پخټل شوې معلومات سره لوړ ریسک وړتیاوې کوي. نقصان په ټولونګي کې ادایي شي.",
  "home.problem.item1Title": "غیر یقینی وخت",
  "home.problem.item1Body": "آبیاري، کود، حشره‌کش، بونۍ، ټولونګي — اهالی لحظې ابھی ډاګه ته انتخاب شي، چې پیداړه کومه کوي او لګد اضافي.",
  "home.problem.item2Title": "ورک شوی د ځمکه تاريخ",
  "home.problem.item2Body": "د سیzonو علم یادداشت کې پاتې کېدلی شي یا پخټلي نوټبوکونو کې. څه چې پismatch شوی یې و، نوموړی ته د بیا سیکلو د بیرته نه کول کېدلی.",
  "home.problem.item3Title": "شیا شیا شوی مشوره",
  "home.problem.item3Body": "سیوري، واپارونه، او ویډیو هر څه جواب ورکوي — خو په نړۍواله په کښت، خاورو، موسم، یا ځای کې راټول نه شي.",
  "home.problem.kicker": "د ډاګه نقصان په ټولونګي کې ادایي شي",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "ستا د ځمکه هوښه،",
  "home.solution.titleB": "په یوه ځای",
  "home.solution.subtitle": "د ټول سیzon لپاره یوه هوښه پلیټفارم — مشوره، یاداشتې، موسم، او بازار ستا د ځمکه ډیټا سره کوي، نه عمومي مشورې.",
  "home.solution.card1Title": "څه کړي",
  "home.solution.card1Body": "د آبیاري، کود، حشره‌کش، او ټولونګي وخت لپاره شخصي مشورې — ستا د کشت او حالاتو پر بیا.",
  "home.solution.card1Answer": "د دې کشت، د دې اونۍ لپاره واضح مشوره.",
  "home.solution.card2Title": "کله کړي",
  "home.solution.card2Body": "موسمی لارښوونکي ورته وایي چې څه کله کړئ، ترڅو بد وخت او ناڅاپه حالات ستا پیداړه مه خورئ.",
  "home.solution.card2Answer": "د حقیقي موسم او د نشوونمو مرحلې پر بیا وخت.",
  "home.solution.card3Title": "څه کېدلی دی",
  "home.solution.card3Body": "هره سرګرمۍ — آبیاري، مواد، ناروغۍ، لګدې، ټولونګي — په منظم یادداشت کې وسیږي چې هر سیzon ګټور کوي.",
  "home.solution.card3Answer": " بشپړ تاريخ، همیشه شته.",
  "home.features.eyebrow": "د پلیټفارم په شته کې",
  "home.features.titleA": "متعدد انجنو،",
  "home.features.titleB": "یوه هوښه پلیټفارم",
  "home.features.subtitle": "ستا د خپلو کلمو په یوه پرسه څخه تر د سیzon یاداشتونو تک — هر توانایي بلنه راغوه کوي.",
  "home.features.advisorModule": "ماډیول ۰۱ · مشیر",
  "home.features.advisorTitle": "AI د کښتکاری مشير",
  "home.features.advisorTopics": "آبیاري · کود · حشره‌کش او ناروغۍ · ټولونګي",
  "home.features.advisorBadge": "رومان اردو",
  "home.features.advisorMockAria": "د زردي پتو د ګندم پر اګروپیو مشیر سره نمونه خبرې",
  "home.features.advisorUserMsg": "زما د ګندم پټۍ زردي شي وي — څه وکړم؟",
  "home.features.advisorReplyTitle": "زردي پټۍ — دو عادي وجوهات:",
  "home.features.advisorReplyCause1": "د اوبو کمبودي",
  "home.features.advisorReplyCause1Rest": "— ټکلي کې، ماسپر ۹ بجې مخکې آبیاري وکړئ.",
  "home.features.advisorReplyCause2": "نایټروجن کمبودي",
  "home.features.advisorReplyCause2Rest": "— لومړۍ شونډۍ وګورئ؛ اګر اړینه وي یوریا غرقي کړئ.",
  "home.features.advisorReplyFooter": "اګر د پتو ټکي لاندې زردي خشې وګورئ، عکس واستوئ — زه بیماري ته ویکشف کوم.",
  "home.features.advisorInputPlaceholder": "خپله پرسه لیکئ یا وایئ…",
  "home.features.advisorFooter": "خپل کشت پر څه بیا هر څه وپرسئ — ورځنۍ پرسې ښه راغلې.",
  "home.features.recordsModule": "ماډیول ۰۲ · یاداشتې",
  "home.features.recordsTitle": "ډیجیټل د ځمکه یاداشتې",
  "home.features.recordsDesc": "هره سرګرمۍ منظم او ثبت شوې — ترڅو مشوره ستا د خپلې ځمکه څخه یاد کړي.",
  "home.features.record1Activity": "آبیاري",
  "home.features.record1Detail": "نهري · ۴۰ منټ",
  "home.features.record2Activity": "یوریا ۴۶٪ N",
  "home.features.record2Detail": "۲۵ کلو / ایکړ",
  "home.features.record3Activity": "د پتو اسکین",
  "home.features.record3Detail": "هیڅ ناروغۍ نه ده",
  "home.features.recordsCropTag": "ګندم · ربیع سیzon",
  "home.features.languageModule": "ماډیول ۰۳ · ژبه",
  "home.features.languageTitle": "ستا ژبه، ستا کلمې",
  "home.features.languageDesc": "هغه شی واوئ یا لیکئ چې ویلی — ډیر تکنیکی انګلیزي نه ده اړینه.",
  "home.features.weatherModule": "ماډیول ۰۴ · موسم",
  "home.features.weatherTitle": "موسمی لارښوونکي",
  "home.features.weatherDesc": "مشوره د تاسو ته راشونکي مخکې حقیقي حالت وګوري — بارش مخکې سپری وکړئ او تاسو خپل مواد ویشوي.",
  "home.features.weatherMockAria": "پنځه ورځنۍ پیش‌گویي چې پنځښنبېر ته د سپری نه کولو مشوره ښکاره کوي",
  "home.features.dayMon": "دونۍ",
  "home.features.dayTue": "درېنۍ",
  "home.features.dayWed": "څلورنۍ",
  "home.features.dayThu": "پنځښنبېر",
  "home.features.dayFri": "جمعه",
  "home.features.holdSpray": "سپری وکړئ",
  "home.features.weatherLegend": "د ورځ اعلان د ډیځاینیک موسمی پیش‌گویی څخه",
  "home.features.moreLink": "پلیټفارم د بیا ښودل کېږي — بشپړ توانایي وګورئ",
  "home.journey.eyebrow": "څنګه کارووي",
  "home.journey.title": "یوه پرسه سیzon پیل کوي",
  "home.journey.subtitle": "ستا د لومړۍ پرسه څخه بشپړ، هوښه د ځمکه تاريخ تک ساده لاره.",
  "home.journey.step1Title": "خپل ځمکه اضافه کړئ",
  "home.journey.step1Body": "د ډیجیټل د ځمکه پروفایل جوړولو لپاره خپل ځای، کشت، او اساسي تفصیلات ثبت کړئ.",
  "home.journey.step2Title": "AI ته وپرسئ",
  "home.journey.step2Body": "خپله پرسه هغه ژبه کې لیکئ یا وایئ چې تاسو ته ډیر راحت دي.",
  "home.journey.step3Title": "لارښوونکي تر لاسه کړئ",
  "home.journey.step3Body": "ستا کشت، موسم، ځای، او د ځمکه تاريخ ته اساس شوی مشوره تر لاسه کړئ.",
  "home.journey.step4Title": "سرګرمۍ ثبت کړئ",
  "home.journey.step4Body": "د څند کېل سره آبیاري، کود، حشره‌کش، یا ناروغۍ ثبت کړئ.",
  "home.journey.step5Title": "تاریخ جوړ کړئ",
  "home.journey.step5Body": "هر یاداشت راتلونکو مشورو ډیره هوښه‌ور او ښه ته بدلووي.",
  "home.journey.step6Title": "یوه نگرانی تjobs بلنه کړئ",
  "home.journey.step6Body": "د ټول سیzon په دریمنی یاداشتې وګورئ او پیشرفت وګورئ.",
  "home.matrix.eyebrow": " بشپړ توانایي مجموعه",
  "home.matrix.title": "د اړینو څخه حیرانونکو تک",
  "home.matrix.subtitle": "هره ځانګړتیا کشت وسیږي، لګد کومه کوي یا عایدي بره کوي. دا دا پنځه څخه پوښتنه په څنګه وګورئ — هر برخه د یو بل ته اساس شوې.",
  "home.matrix.capabilitiesLabel": "توانایي",
  "home.matrix.tier1Name": "اړین",
  "home.matrix.tier1Badge": "اصلي",
  "home.matrix.t1f1Title": "AI د کشت ناروغۍ ویش",
  "home.matrix.t1f1Body": "متاثر د پته عکس پورته کړئ او فوري تشخیص، شدت، او تداوی سفارشات تر لاسه کړئ.",
  "home.matrix.t1f2Title": "سیټلایټ د کشت نگرانی",
  "home.matrix.t1f2Body": "خپل کشت حدو معلوم کړئ او د ریتن-۲ عکسونو څخه NDVI اساس شوې د کشت صحت وګورئ.",
  "home.matrix.t1f3Title": "هوښه‌ور موسمی مشوره",
  "home.matrix.t1f3Body": "ډیځاینیکو پیش‌گویي ستا کشت او د نشوونمو مرحله سره تر اټکل ورته راشي او روزانه عملی مشوره کوي.",
  "home.matrix.t1f4Title": "منډی قیمو ټریکر او پیش‌گویي",
  "home.matrix.t1f4Body": "د نزدیکو بازارونو قیمو AI لارښوونکی سره وګورئ، ترڅو په مناسب وخت بیچئ.",
  "home.matrix.tier2Name": "جلاوونکي",
  "home.matrix.tier2Badge": "جلا",
  "home.matrix.t2f1Title": "د علاقایي ژبو وائس چیټ بوټ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی پورته وویئ یا لیکئ — جواب هغه ژبه کې واوئ چې ډیر ښه و理解和.",
  "home.matrix.t2f2Title": "د حکومتي پروګرامونو مچ",
  "home.matrix.t2f2Body": "خپل پروفایل ثبت کړئ او هر غړی پروګرام ومومئ، د اسنادو او غوښتنې لینکونو سره.",
  "home.matrix.t2f3Title": "د کشت سفارش انجن",
  "home.matrix.t2f3Body": "د خاورو، موسم، بازار غوښتنه، او ستا بیودیټا پر بیا د دې سیzon ټولو ګټور کشت.",
  "home.matrix.t2f4Title": "د ځمکه ګټه/نقصان حسابوونکي",
  "home.matrix.t2f4Body": "متوقع او حقیقي لګدې، پیداړه، عایدي، او ګټه — بریک ایون او ROI وړتیاوې سره.",
  "home.matrix.t2f5Title": "ټولنیز فورم + ماهرینو رابطه",
  "home.matrix.t2f5Body": "پرسې وړاندیز کړئ، عکسونه شریک کړئ، د یو څه کښتکارونو او تایید شوو ماهرو څخه جوابونه تر لاسه کړئ.",
  "home.matrix.tier3Name": "حیرانونکی",
  "home.matrix.tier3Badge": "تر ټولو مخکې",
  "home.matrix.t3f1Title": "سیټلایټ بدلون ویش",
  "home.matrix.t3f1Body": "د وخت په تیر کې سیټلایټ عکسونه سلایدر سره سیمه‌ییز کړئ — د نشوونمو، نقصان، یا غصب ټریک کړئ.",
  "home.matrix.t3f2Title": "AI د حشراتو پیش‌گویي",
  "home.matrix.t3f2Body": "موسم، د کشت مرحله، او تاریخ ته اساس شوی ممکنه حملو مخکې مخنیوی.",
  "home.matrix.t3f3Title": "وائس فرسټ فون کال موډ",
  "home.matrix.t3f3Body": "د ټل فری نمره ته کال کړئ، پرسه وویئ، خپله ژبه کې مشوره وواوئ — اسمارټ فون نه دی اړین.",
  "home.matrix.t3f4Title": "کاربن کریډټ حسابوونکي",
  "home.matrix.t3f4Body": "پایدار طریقې ثبت کړئ او رضاکارانه بازارونو څخه د کاربن کریډټ اړینه قیمت حسابوئ.",
  "home.matrix.t3f5Title": "آفلاین PWA + SMS",
  "home.matrix.t3f5Body": "کشتی کې آفلاین کاروي، د کنکشن پر یوځای شي، د ډیټا نه شونکي ځایونو ته SMS اعلان ورکوي.",
  "home.vision.eyebrow": "موږ سره ویسون",
  "home.vision.titleA": "پاکستان لپاره جوړ شوی.",
  "home.vision.titleB": "نړۍ ته چمتو.",
  "home.vision.pkTitle": "پاکستان په لومړۍ ځای",
  "home.vision.pkBody": "لومړۍ نسخه پاکستان د کشتونو لپاره ډیزاین شوې: محلي کشتې، علاقایي ژبې، حقیقي کښتکاری طریقې، او حقیقي حالات.",
  "home.vision.pkPoint1": "محلي کشت او موسم پهatology",
  "home.vision.pkPoint2": "اردو، پنجابی، پښتو، سندی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "د حقیقي کښتکارونو غوښتنه سره ښه شوی",
  "home.vision.worldTitle": "نړیوال د پیل شریکي",
  "home.vision.worldBody": "د چمتو جوړ شوی. هیله څومه چې پلیټفارم ډېر ډېر ورو ورو د نو ممالک، ژبو، کشتونو، او موسمونو ته ګام اورسی شي.",
  "home.vision.worldPoint1": "د هر ملک پر بیا د کښتکاری علم",
  "home.vision.worldPoint2": "اضافي ژبې او محلي کشتې",
  "home.vision.worldPoint3": "ګاهري ډیټا تړاوونه او تجزیه",
  "home.users.title1": "انفرادي کښتکار",
  "home.users.desc1": "کوچنه او منځنۍ ځمکه‌داري چې عملی لارښوونکي او د هر سرګرمۍ منظم یاداشت ته اړینه دي.",
  "home.users.title2": "تاجراني ځمکه‌داري",
  "home.users.desc2": "کښتکاري کاروبار چې منظم معلومات، د وړتیاوو ملاتړ، او ټیم وړ یاداشتې ته اړینه دي.",
  "home.users.title3": "د ماحولیاتي ګرځنکو شراکت دار",
  "home.users.desc3": "د مواد راوړونه، کوآپریټو، بیمه‌کوونه، او توسیعي خدمات چې د وخت په تیر کې د پلیټفارم سره غړي شي.",
  "home.users.tagline": "د لومړي ځای کښتکارونو لپاره ډیزاین شوی — د ماحولیاتي ګرځنکو سره ګrowing",
  "home.cta.eyebrow": "مخکینی رسایی",
  "home.cta.title": "خپل ځمکه پلیټفارم په شته بیا وړاندیز کړئ",
  "home.cta.subtitle": "د اګروپیو سره ښه وړتیاوې د کښتکارونو کې شامل شي — پاکستان څخه پیل، نړۍ پورته.",
  "home.cta.success": "تاسو فهرست کې شته و. ستا د ځای کله چې خلاص شي موږ تاسو سره اړیکه لري.",
  "home.cta.emailLabel": "ایمیل پته",
  "home.cta.fineprint": "هیڅ اسپم نه. هیله کېدلی.",
  "home.footer.tagline": "AI پر بڼه د ځمکه هوښه پلیټفارم. مشوره، سیټلایټ مانیټرنګ، بازاری قیمته، او یاداشتې — خاورو او سیګنل، یوځای.",
  "home.footer.pagesHeading": "صفحات",
  "home.footer.pagesNavLabel": "د فیوټر صفحات",
  "home.footer.legalHeading": "قانوني",
  "home.footer.legalNavLabel": "قانوني",
  "home.footer.privacy": "د محرمیت پالیسي",
  "home.footer.terms": "د خدمات شرایط",
  "home.footer.cookies": "کوکي پالیسي",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "ارتباط وکړئ",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اګروپیو. ټول ملکیت واحفظ شوې.",
  "home.footer.motto": "پاکستان لپاره جوړ شوی · نړۍ ته چمتو",
  "hiw.meta.title": "څنګه کارووي — اګروپیو",
  "hiw.meta.description": "د یو منټ د ځمکه پروفایل څخه تر سیzon چرخ تک: وګورئ اګروپیو څه کله شخصي د کښتکاری لارښوونکي بدلووي.",
  "hiw.hero.eyebrow": "څنګه کارووي",
  "hiw.hero.titleA": "شپږ کوچنۍ ګامونه.",
  "hiw.hero.titleLead": "یوه",
  "hiw.hero.titleAccent": "ګټوره سیzon.",
  "hiw.hero.subtitle": "اګروپیو دا شی کوي چې کښتکاری په تلو څخه کوي — تاسو بونۍ کوي، وپرسوئ، وویوئ، او یاداشتې کوي. یوازې فرق دا دی چې ابھی هر ګام بلنه میانووي.",
  "hiw.hero.browseFeatures": "ځانګړتیاوې وګورئ",
  "hiw.route.navLabel": "د اګروپیو سیzon چرخ د شپږ ګامونو لاره",
  "hiw.route.stepLabel": "ګام {n}: {stop}",
  "hiw.route.stop1": "ځمکه اضافه کړئ",
  "hiw.route.stop2": "وپرسئ",
  "hiw.route.stop3": "لارښوونکي",
  "hiw.route.stop4": "وویوئ",
  "hiw.route.stop5": "یاداشت",
  "hiw.route.stop6": "ښه مشوره",
  "hiw.setup.eyebrow": "یوه ځای ټول کړئ",
  "hiw.setup.title": "ستا ځمکه زونده پروفایل شي",
  "hiw.setup.body": "څلورو خانو، د یو منټ کم — ضلع، کشت، د بونۍ تاریخ، او د ځمکه اندازه. دا بشپړ فارم دی. د دې نه مخکې هر جواب ویي چې کومه ځای، څه حالات کېږي.",
  "hiw.setup.point1": "کشت بدل کړئ یا هیله کې د ځمکه اضافه کړئ",
  "hiw.setup.point2": "د لیږدلي کېدلونو او ډیلرو لپاره متعدد ځمکه‌داري",
  "hiw.setup.point3": "هیڅ تکنیکی پرسه نه شي — د خاورو رپورټ نه دی اړین",
  "hiw.setup.mockHeading": "نوی د ځمکه پروفایل",
  "hiw.setup.mockButton": "د ځمکه پروفایل جوړ کړئ",
  "hiw.setup.mockFootnote": "د یو منټ کم لري",
  "hiw.setup.mockLabel": "د ځمکه پروفایل فورمه چې ضلع، کشت، د بونۍ تاریخ، او د ځمکه اندازه پورته کړی",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "کشت",
  "hiw.setup.valCrop": "ګندم · ربیع",
  "hiw.setup.rowSowing": "د بونۍ تاریخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "ځمکه",
  "hiw.setup.valLand": "۱۲ ایکړ",
  "hiw.ask.eyebrow": "هر څه وپرسئ",
  "hiw.ask.titleA": "یوه پرسه درسره.",
  "hiw.ask.titleB": "ستا ټول ځمکه ورته زRBووي.",
  "hiw.ask.body": "یوه ویلیه پرسه په بېلERAL بل ځمکه‌داري کې بېل بېل مانا لري. نو د جواب ورکولو مخکې اګروپیو دا پرسه ستا ځمکه په غاړه د هر شی پر بیا وګوري.",
  "hiw.ask.pipelineLabel": "د کښتکار پرسه کشت، ضلع، موسم، او تاریخ سره تر اټکل شخصي جواب جوړیږي",
  "hiw.ask.question": "ابھی ابیاري وکړي یا څه ورو انتظار کړي؟",
  "hiw.ask.checkedAgainst": "د دینو سره سیمه‌ییز",
  "hiw.ask.chipCrop": "کشت",
  "hiw.ask.chipValCrop": "ګندم · ګل نه شوی",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "۲۶° · ښه ورځ",
  "hiw.ask.chipHistory": "تاریخچه",
  "hiw.ask.chipValHistory": "یوریا ۹ ورځې مخکې",
  "hiw.ask.answer": "دوه ورځې انتظار کړئ — بارش راتلی شي، او یوریا ورو ورو ځمکه ابھی ګیله ده. د جمعه مخکې چیک ورته ډیره دي.",
  "hiw.ask.answerMeta": "شخصي · ګندم، یوریا ورو ۹ ورځې مخکې",
  "hiw.ask.footnote": "لیکئ، وویئ یا کال کړئ — جواب همیشه شخصي دی",
  "hiw.engine.eyebrow": "د جواب په شته کې",
  "hiw.engine.title": "څلور چیکونه د تاسو ته یو کیشی ده مخکې",
  "hiw.engine.body": "لارښوونکي هیڅ سرچ نتیجه نه دی. دا څلورو دروازو څخه تیري ترڅو هغه چې تاسو ته ورسیږي د دې کشت، د دې اونۍ لپاره واوړا وي.",
  "hiw.engine.check1Title": "د معلوماتو راتول",
  "hiw.engine.check1Desc": "د ځمکه پروفایل، فعلي موسم، او کشت مرحله د واستلو مخکې یوځای شي.",
  "hiw.engine.check2Title": "د چیکونو ملاتړ",
  "hiw.engine.check2Desc": "مشوره د پیش‌گویي سره چیکیږي — بارش ویشل شوی سپری د انجنو څخه نه شي.",
  "hiw.engine.check3Title": "شخصي کول",
  "hiw.engine.check3Desc": "ستا د کشت تاريخ جواب بدلووي — هیله ویلیه کشت، بېل خاورو، بېل مشوره.",
  "hiw.engine.check4Title": "رسانېدل",
  "hiw.engine.check4Desc": "په بیرته ستا ژبه کې واضح ګامونه شي — په سکرین، وائس، یا فون کال.",
  "hiw.engine.safetyStrong": "اګر څه غیر واوړا وګورئ،",
  "hiw.engine.safetyRest": "اګروپیو ورته وایي انتظار کړئ — د ورو ورو د راتلونکي جواب څخه ښه دي.",
  "hiw.record.recorderHeading": "سرګرمۍ ثبت کړئ",
  "hiw.record.syncBadge": "خودکار سنک ان",
  "hiw.record.actionIrrigation": "آبیاري",
  "hiw.record.actionFertiliser": "کود",
  "hiw.record.actionPesticide": "حشره‌کش",
  "hiw.record.actionDisease": "ناروغۍ",
  "hiw.record.actionExpense": "لګد",
  "hiw.record.actionHarvest": "ټولونګي",
  "hiw.record.row1Time": "نن · ماسپر ۶:۴۰",
  "hiw.record.row1Label": "آبیاري ثبت شوې",
  "hiw.record.row1Detail": "نهري ته لیږدleague · ۴۰ منټ · پلاټ B",
  "hiw.record.row2Time": "پ Luna",
  "hiw.record.row2Label": "کود ثبت شوې",
  "hiw.record.row2Detail": "DAP ۲۰ کلو / ایکړ",
  "hiw.record.offlineNote": "→ د هر درسره یوازې دو ټیپ — آفلاین هم کاروي",
  "hiw.record.mockLabel": "د سرګرمۍ ثبتونکي په چټکه اکشن چپس او ورو ورو ثبت شوې ډلې سره",
  "hiw.record.eyebrow": "کله چې کاروي، یاداشت کړئ",
  "hiw.record.titleA": "ابھی دو ټیپ،",
  "hiw.record.titleB": "د ټول سیzon ښه جوابونه",
  "hiw.record.body": "ثبتونه د کشتی لپاره جوړ شوي — لوړه بټن، کم خانه، ټایپ کولو اړینه نه. هر درسره د ځمکه د یاداشتې برخه شي، نو مشوره هم د کشت سره تیزیږي.",
  "hiw.record.point1": "آبیاري، مواد، ناروغۍ، لګدې، ټولونګي — ټول په یوه ټایملاین",
  "hiw.record.point2": " بشپړ آفلاین کاروي؛ سیګنل راتلو ته یوځای شي",
  "hiw.record.point3": "بانک، واپارونه، یا بیمه لپاره سیzon خلاصه چمتو",
  "hiw.loop.eyebrow": "د سیzon چرخ",
  "hiw.loop.titleA": "دا د ټولونګي پر بشته نه شي.",
  "hiw.loop.titleB": "هیله څومه څخه پیل شي.",
  "hiw.loop.body": "وپرسئ، وویوئ، یاداشت وکړئ — بیرته وکړئ. د چرخ هر ګری د اګروپیو ستا ځمکه پر غاړه ښه کوي، ترڅو ابل سیzon د پیل څخه وړتیانک دي.",
  "hiw.loop.benefit1Title": "مشوره وړتیاني شي",
  "hiw.loop.benefit1Desc": "تیر شوې سیzon د ناروغۍ، لیږدلي مقدارو، او تاریخونو پر بیا ستا لومړۍ جواب ډیزاین کوي.",
  "hiw.loop.benefit2Title": "هیڅ بیرته نه کېږي",
  "hiw.loop.benefit2Desc": "مشیر پوه دي چې څه مخکې سپری شوی یا لیږدل شوی — بېرته ملاتړ نه شي.",
  "hiw.loop.benefit3Title": "هره سیzon ثبت شوې",
  "hiw.loop.benefit3Desc": "ساف تاريخ په حاضر حالت کې پاتې دی — د پریکشل، واپارونو، بیمو، یا راتلونکي د کشت فیصلې لپاره.",
  "hiw.loop.stepLearn": "زده کړئ",
  "hiw.loop.stepImprove": "ښه کړئ",
  "hiw.loop.diagramLabel": "د ګردش چرخ ډیاګرام: وپرسئ، وویوئ، یاداشت، زده کړئ، ښه کړئ",
  "hiw.loop.centerSeason": "سیzon",
  "hiw.loop.centerLoop": "چرخ",
  "hiw.loop.caption": "هره سیzon، پخټل سره ښه",
  "feat.meta.title": "ځانګړتیاوې — اګروپیو",
  "feat.meta.description": "د اګروپیو هر توانایي وګورئ: AI د کشت ډاکټر، سیټلایټ NDVI مانیټرنګ، منډی قیمتو پیش‌گویي، د محلي ژبو وائس مشوره، آفلاین رسایی SMS اعلانونو سره، او نور.",
  "feat.hero.eyebrow": "ځانګړتیاوې",
  "feat.hero.titleLead": "ټول هغه شیان",
  "feat.hero.titleAccent": "ستا سیzon ته اړین",
  "feat.hero.subtitle": "څلور توانایي په یوه په څه کې کاروي — پټۍ اسکین، سیټلایټ څخه ځمکه وګوري، منډی وIntermediate، او ستا ژبه ویل. وګورئ هره توانایي ستا ځمکه ته څه کوي.",
  "feat.hero.ctaPrimary": "مخکینی رسایی تر لاسه کړئ",
  "feat.hero.ctaSecondary": "وګورئ کومته څنګه کارووي",
  "feat.hero.builtFor": "پاکستان لپاره جوړ شوی",
  "feat.hero.productOf": "اپلینوډ ته یوه پروډکټ",
  "feat.hero.tile1Label": "پتو اسکین",
  "feat.hero.tile1Value": "۹۴٪ ښه",
  "feat.hero.tile2Label": "منډی ګندم",
  "feat.hero.tile2Value": "+۱۲٪",
  "feat.hero.tile3Label": "سیټلایټ ځمکه",
  "feat.hero.tile3Value": "۰.۸۲",
  "feat.hero.tile4Label": "د حشراتو خطره",
  "feat.hero.tile4Value": "کم · ۷ ورځې",
  "feat.hero.voiceReady": "وائس مشوره چمتو دی",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "په ریالټم کې",
  "feat.hero.smsLabel": "SMS اعلان · آفلاین موډ",
  "feat.hero.smsMsg": "بارش ۳ بجې — سپری وکړئ",
  "feat.intel.eyebrow": "د کشت هوښه",
  "feat.intel.heading": "ستونزې وګورئ مخکې چې تاسو ته لګد ورکړي",
  "feat.intel.sub": "ناروغۍ، حشرې، موسم، او د کشت غوښتنه — د څلورو فیصلو چې یوه ټولونګی ت Decide کوي، هره په جلا انجن بڼه.",
  "feat.intel.included": "شامل دي",
  "feat.intel.doctorCode": "F·۰۱ · بینش",
  "feat.intel.doctorTitle": "AI د کشت ډاکټر",
  "feat.intel.doctorDesc": "متاثر پته عکس ونیسئ او ثانیو کې ناروغۍ نوم، شدت سطحه، او تداوی پلان تر لاسه کړئ.",
  "feat.intel.doctorMock": "د پتو اسکین نتیجه چې زردي زنګه په لوړ باوري سره وموندل شوی",
  "feat.intel.diseaseName": "زردي زنګه",
  "feat.intel.matchScore": "۹۴٪ مچ",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "منځنۍ",
  "feat.intel.pestCode": "F·۰۲ · پیش‌گویي",
  "feat.intel.pestTitle": "د حشراتو حملو اعلان",
  "feat.intel.pestDesc": "موسم او د کشت مرحله خطره ماډل ته ورکوي چې د حملو مخکې ورځې وښيي.",
  "feat.intel.pestMock": "۷ ورځنۍ د حشراتو خطره برکي چې شپږمۍ ورځ ته لوړ ته وګرځي",
  "feat.intel.pestAlert": "نندیزه · څtring ۷۴٪ خطره — ټکلي ګندم بند کړئ",
  "feat.intel.weatherCode": "F·۰۳ · موسم",
  "feat.intel.weatherTitle": "موسمی مشورې",
  "feat.intel.weatherDesc": "ډیځاینیکو پیش‌گویي ستا کشت او د نشوونمو مرحله سره یوځای شي — مشوره په واضح حکم په بدل وي، نه خام ډیټا.",
  "feat.intel.weatherMock": "د موسمی مشوره نمونه چې بارش مخکې آبیاري ورو کول ته ویل کوي",
  "feat.intel.delayIrrigation": "نن آبیاري ورو کړئ",
  "feat.intel.rainNote": "م moral ۳ بجې بارش ته امید — اول آسمان ستا ځمکه ابیاري کړي.",
  "feat.intel.waterSaved": "اوبه خوندي شوې",
  "feat.intel.cropCode": "F·۰۴ · планировка",
  "feat.intel.cropTitle": "د کشت سفارش",
  "feat.intel.cropDesc": "خاورو، موسم، غوښتنه، او ستا بودیټه یوځای حساب شي — هغه کشت وکړئ چې دې سیzon ګټه ورکوي.",
  "feat.intel.cropMock": "د ګندم په لومړۍ ځای سره رتبه شوې د کشت سفارشې",
  "feat.intel.crop1": "ګندم",
  "feat.intel.crop2": "توریا",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "ځمکه او بازار هوښه",
  "feat.field.headingA": "ستا ځمکه د سیټلایټ څخه پیمایل شوې.",
  "feat.field.headingB": "ستا کشت د ډیټا څخه قیمت شوی.",
  "feat.field.sub": "سیټلایټ ستوري په هر ایکړ او هر نزدیک منډی ته — ترڅو نشوونه او پخټل هر دو په مناسب وخت شي.",
  "feat.field.ndviCode": "F·۰۵ · سیټلایټ",
  "feat.field.ndviTitle": "سیټلایټ ځمکه مانیټرنګ",
  "feat.field.ndviDesc": "خپل حدو یو ځای ثبت کړئ؛ صحت سیمونه هره saf سیټلایټ تیره سره نوېږي — کمزور برخې د عیني نه مخکې پیدا شي.",
  "feat.field.ndviMock": "د ځمکه صحت ګریډ چې تیاره شنه ګونه ټول شته نشوونه ښکاره کوي",
  "feat.field.weakZone": "کمزور سیمه · ۲ اونۍ",
  "feat.field.priceCode": "F·۰۶ · بازار",
  "feat.field.priceTitle": "منډی قیمتو پیش‌گویي",
  "feat.field.priceDesc": "د نزدیکو بازارونو ریلټم نرخونه او روند پیش‌گویي سره — کله چې خوندي وی بیچئ، نه کله چې واپار تاسو ته ووایي.",
  "feat.field.priceMock": "د ګندم قیمت روند ۸ اونۍ پورته او خوندي کولو مشوره",
  "feat.field.wheatTrend": "ګندم · ۸ اونۍ",
  "feat.field.holdStock": "↑ ۱۲٪ — مواد خوندي کړئ",
  "feat.field.financeCode": "F·۰۷ · مالیات",
  "feat.field.financeTitle": "ګټه / نقصان ټریکر",
  "feat.field.financeDesc": "هر روپیه د داخل او بیرته — د بریک ایون او ROI سره مخکې چې تاسو منډی یا بانک ته ورکیدل شي.",
  "feat.field.ledgerMock": "د سیzon لیږدلي مواد حساب چې مواد، کار، آبیاري، او عایدي ښکاره کوي",
  "feat.field.rowInputs": "مواد",
  "feat.field.rowLabour": "کار",
  "feat.field.rowIrrigation": "آبیاري",
  "feat.field.rowRevenue": "عایدي (تخمیني)",
  "feat.field.netMargin": "خالص سود",
  "feat.voice.eyebrow": "د ټولو لپاره رسایی",
  "feat.voice.headingA": "اسمارټ فون نه لري؟",
  "feat.voice.headingB": "انګلیزي نه پوهیږئ؟ باز هم شته.",
  "feat.voice.sub": "ښه مشوره بې سوده ده اګر د کښتکار ته مه رسیږي. هره توانایي د تلیفون کال، د وائس واویلو، او د مرګي زونونو ته مقاومت کوي.",
  "feat.voice.speakCode": "F·۰۸ · وائس",
  "feat.voice.speakTitle": "خپله پرسه وویئ",
  "feat.voice.speakMock": "د مشیر سره د رومان اردو کې وائس خبرې",
  "feat.voice.chatUser": "زما د فصل پټۍ پر دحابي",
  "feat.voice.chatAdvisor": "د دحابو عکس واستوئ — زه ابھی تشخیص کوم.",
  "feat.voice.inputPlaceholder": "وویئ او وپرسئ…",
  "feat.voice.callCode": "F·۰۹ · کال",
  "feat.voice.callTitle": "فری ټلیفون شمیره ته کال وکړئ",
  "feat.voice.callMock": "فری ټلیفون خبرې اترې اګروپیو وائس معاون سره",
  "feat.voice.greetingLine": "اګروپیو کې تاسو ته ښه راغلاست",
  "feat.voice.heardLine": "غږ ته پوه شوې — جواب چمتو دی",
  "feat.voice.callEnded": "کال پای ته ورسې — خلاصه خوندي شوې",
  "feat.voice.anyPhone": "هر تلیفون کې کاروي · انټرنیټ نه دی اړین",
  "feat.voice.offlineCode": "F·۱۰ · آفلاین + SMS",
  "feat.voice.offlineTitle": "مرګي زونونه نه بندوي",
  "feat.voice.offlineDesc": "مشورې، یاداشتې، او حسابوونکي بې سیګنل هم کاروي؛ ټول شیا د نیټه راتلو ته یوځای شي، او اړیني اعلانه SMS څخه راشي.",
  "feat.voice.networkStatus": "نیټه حالت",
  "feat.voice.offlineQueued": "آفلاین · ۳ یاداشتې په لیست کې",
  "feat.voice.smsStamp": "SMS · ۰۷:۴۲",
  "feat.voice.smsMsg": "موسم اعلان: بارش شپته ۳ بجې — سپری د وخت بدل کړئ.",
  "feat.manage.eyebrow": "اداره او پیشرفت",
  "feat.manage.headingA": "مشوره د پیل دی.",
  "feat.manage.headingB": "بقي په یاداشتунو ته اړین دی.",
  "feat.manage.sub": "تاریخچه، سوبسیډۍ، پایداري، او د کښتکارونو ټولنه — ابھی ځانګړتیاوې چې هره سیzon وړتیاني کوي.",
  "feat.manage.diaryCode": "F·۱۱ · یاداشتې",
  "feat.manage.diaryTitle": "ډیجیټل د ځمکه ویلو",
  "feat.manage.diaryDesc": "آبیاري تر ټولونګي تک، هر شی د یوه ټایملاین پورته شي چې مشیر د جواب ورکولو مخکې ویلي.",
  "feat.manage.timelineMock": "د اګست د ځمکه سرګرمۍ ټایملاین",
  "feat.manage.tl1Date": "۱۲ اګست",
  "feat.manage.tl1Label": "آبیاري",
  "feat.manage.tl1Detail": "نهري · ۴۰ منټ",
  "feat.manage.tl2Date": "۰۹ اګست",
  "feat.manage.tl2Label": "یوریا لیږدل شوی",
  "feat.manage.tl2Detail": "۲۵ کلو / ایکړ",
  "feat.manage.tl3Date": "۰۲ اګست",
  "feat.manage.tl3Label": "پتو اسکین",
  "feat.manage.tl3Detail": "صاف شوی · ناروغۍ نه",
  "feat.manage.schemeCode": "F·۱۲ · پروګرامونه",
  "feat.manage.schemeTitle": "سوبسیډۍ او حکومتي پروګرامونه",
  "feat.manage.schemeDesc": "د حکومت پیسه چې تاسو هم د وړ دي — مچ شوی، تشریح شوی، او د یو ټیپ غوښتنې لینک شوی.",
  "feat.manage.checklistMock": "د وړتیاوې چیک لسټ چې څلور نه دری بشپړ دي",
  "feat.manage.check1": "ځمکه تایید شوې",
  "feat.manage.check2": "کشت سیzon مچ دی",
  "feat.manage.check3": "شناختی پته ثبت شوې",
  "feat.manage.check4": "بانک حساب وصل شوی",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "۷۵٪ چمتو",
  "feat.manage.carbonCode": "F·۱۳ · پایداري",
  "feat.manage.carbonTitle": "شنه عملونو انعامونه",
  "feat.manage.carbonDesc": "د کاربن حسابوونکي ثبت کړئ؛ سیټلایټ شنه پوښله تایید کوي او د کاربن کریډټ قیمت تخمینه شي.",
  "feat.manage.carbonMock": "د کاربن خلاصه چې ټنونه شته او سالیه تخمینه شوې قیمت ښکاره کوي",
  "feat.manage.co2Label": "CO₂ شته",
  "feat.manage.creditLabel": "کریډټ قیمت / سال",
  "feat.manage.forumCode": "F·۱۴ · ټولنه",
  "feat.manage.forumTitle": "کښتکارو فورم + ماهرینه",
  "feat.manage.forumDesc": "ستونزه وړاندیز کړئ، هغه کښتکارونو څخه جوابونه تر لاسه کړئ چې دا تجربه کړی — تایید شوي اګرونومسټ ښه علاج تاییدوي.",
  "feat.manage.threadMock": "ټولنیز ریټ چې د ماهر تایید شوې جواب لري",
  "feat.manage.threadQuestion": "د کچو کې سپین مړی ته غبرګونی علاج کوم دی؟",
  "feat.manage.threadMeta": "ملتان · ۱۲ جوابونه · ۳۴ لیکونه",
  "feat.manage.expertBadge": "د ماهر تایید شوې جواب",
  "feat.manage.threadAnswer": "نیم تیل سپری، شپته — دوه ځلې، ۵ ورځو فاصله سره.",
  "vp.meta.title": "ویسون — اګروپیو",
  "vp.meta.description": "اګروپیو د ویسون: هوښه‌ور کښتکاری لارښوونکي د هر کښتکار په جیب کې — پاکستان څخه پیل شوی، پنځه باورونو، دری افقونو، او د پیمانونو پر بیا چې هیڅکله مال شوئ نه شي.",
  "vp.hero.eyebrow": "موږ د ویسون",
  "vp.hero.titleLead": "یوه باورمنده مشیر",
  "vp.hero.titleAccent": "د هر کښتکار په جیب کې.",
  "vp.hero.sub": "هوښه‌ور لارښوونکي نه شي کېدلی د ثروت، سویا، یا ژبه ته اړین شي. اګروپیو دا لپاره شته دی چې هر کښتکار — په هر تلیفون، په هر کلي کې — همان اطمینان سره کارووي چې یوه ماهر شخص په یوه مخ ته وي.",
  "vp.hero.tagStart": "هغه ځای پیل کړئ چې ډیره اړینه ده",
  "vp.hero.tagThen": "بیا نړۍ ته decorators",
  "vp.hero.ctaLink": "وګورئ څه جوړ کړو",
  "vp.beliefs.eyebrow": "موږ څه باوروي",
  "vp.beliefs.heading": "پنځه باورې هره فیصله ډیزاینوي",
  "vp.beliefs.b1Title": "پیشرفت",
  "vp.beliefs.b1Desc": "زونده کشتې، صحتمنده ځمکه، خوشاله کښتکار.",
  "vp.beliefs.b2Title": "هوښه",
  "vp.beliefs.b2Desc": "د محلي موسم، تاریخچه، او د کشت ساینس بڼه هوښه.",
  "vp.beliefs.b3Title": "رسایی",
  "vp.beliefs.b3Desc": "د کښتکار د خپلې ژبه او حالات کې لارښوونکي.",
  "vp.beliefs.b4Title": "باور",
  "vp.beliefs.b4Desc": "عملي، وخت په وقت مشوره چې ژوند ت保护 کوي.",
  "vp.beliefs.b5Title": "راټلوکي",
  "vp.beliefs.b5Desc": "تکنالوژي چې روایت ته احترام راشي.",
  "vp.horizons.eyebrow": "راټلوکي لاره",
  "vp.horizons.heading": "دری افق، یوه لاره",
  "vp.horizons.h1Tag": "افق ۰۱",
  "vp.horizons.h1Phase": "ابھی",
  "vp.horizons.h1Status": "د ځمکو کې",
  "vp.horizons.h1Body": "پاکستان لومړۍ. اصلي مشیر، ډیجیټل د ځمکه یاداشتې، موسمی لارښوونکي، او شپږ محلي ژبې — مخکې څه بل ته د حقیقي کښتکارونو فیدبیک سره ښه شوی.",
  "vp.horizons.h1P1": "اصلي مشیر + یاداشتې",
  "vp.horizons.h1P2": "شپږ ژبې",
  "vp.horizons.h1P3": "د حقیقي کښتکارونو ښه کول",
  "vp.horizons.h2Tag": "افق ۰۲",
  "vp.horizons.h2Phase": "بل",
  "vp.horizons.h2Status": "وسيع کول",
  "vp.horizons.h2Body": "د پاکستان په ټولو ځایونو کې ډیره ګہرۍ او وسیعه — ډیر کشتې او علاقې، ډیره د کښتکاری معلوماتو تړاوونه، او تجزیه چې هره سفارش شخصي کوي.",
  "vp.horizons.h2P1": "ډیر کشتې او علاقې",
  "vp.horizons.h2P2": "د معلوماتو تړاوونه",
  "vp.horizons.h2P3": "پیشرفته تجزیه",
  "vp.horizons.h3Tag": "افق ۰۳",
  "vp.horizons.h3Phase": "وروسته",
  "vp.horizons.h3Status": "نړیوال",
  "vp.horizons.h3Body": "پلیټفارم نو ممالک، اوبو هوا، کشتې، ژبې، او طریقې ته ګومار شي — یوه نړیواله ګوتي کېدلی د کښتکاری هوښه چې د پیل څخه بیا جوړ نه شي.",
  "vp.horizons.h3P1": "نو ممالک",
  "vp.horizons.h3P2": "نو ژبې او اوبو هوا",
  "vp.horizons.h3P3": "نړیواله پلیټفارم",
  "vp.outcomes.eyebrow": "بریالیتوب څنګه لري",
  "vp.outcomes.heading": "څلور نتیجه چې موږ خپل ته ډک کوي",
  "vp.outcomes.sub": "د ویسون پلیټفارم نه ده — دا د ځمکه ته بدلون دی. ټول شیا د دې څلورو نتیجو پر بیا.",
  "vp.outcomes.o1Title": "ښه فیصلې",
  "vp.outcomes.o1Desc": "هره غوښتنه — اوبه، مواد، وخت — د ډیټا بڼه، نه عادت.",
  "vp.outcomes.o2Title": "لوړه پیداړه",
  "vp.outcomes.o2Desc": "صحتمنده کشتې، مناسب وخت مواد، او ټولونګي په خپل وخت.",
  "vp.outcomes.o3Title": "کم د اجتناب وړ ګټې",
  "vp.outcomes.o3Desc": "ناروغۍ، حشرې، او موسم مخکې ویشل شي — مخکې چې پیداړه وايي.",
  "vp.outcomes.o4Title": "ځمکې د کسب وبار په څه کې",
  "vp.outcomes.o4Desc": "منظم یاداشتې او سیzon هوښه چې بانکونه او واپارونه احتراموي.",
  "vp.principles.eyebrow": "غیر قابل مذاکره",
  "vp.principles.heading": "د پیمانونو بڼه چې موږ جوړوو",
  "vp.principles.sub": "د ویسون ناکامی په جزیات کې شي. دا تعهدات په هر ځانګړتیا، هر صفحه، هر اعلان پورته دي — نن څخه پیل کوي.",
  "vp.principles.c1Title": "د کښتکار ګټه مخکې",
  "vp.principles.c1Desc": "هره ځانګړتیا د ځمکه غوښتنه څخه پیل کوي — هیڅکله نه د تکنالوژي.",
  "vp.principles.c2Title": "ژبه مخکې",
  "vp.principles.c2Desc": "هر سکرین او هر جواب د کښتکار د خپلې ژبه کې راشي.",
  "vp.principles.c3Title": "د نمر د وخت واوړا",
  "vp.principles.c3Desc": "لوړه لیکه د منځنۍ نمر لپاره ډیزاین شوې، نه یوازې د offs.",
  "vp.principles.c4Title": "ساده کلمې",
  "vp.principles.c4Desc": "هغه اندازه ساده چې یوه چا ته بیا یوه بل ته تشریح کول شي.",
  "vp.principles.c5Title": "تلیفون مخکې ټولو",
  "vp.principles.c5Desc": "موبایل مخکې، لوړه ټاپل شونکي — کښتکاری ابھی په تلیفونو کې کاروي.",
  "vp.principles.c6Title": "طبيعتي د ډیزاین",
  "vp.principles.c6Desc": "حرکت او ترتیب چې طبیعی لري — نشوونه، هیڅکله نه ماشین.",
  "vp.principles.motto": "خاورو او سیګنل — یوځای ښه کېږوو",
  "wy.meta.title": "ځای اګروپیو — AI پر بڼه د ځمکه هوښه",
  "wy.meta.description": "د کښتکاری فیصلې د حدس لپاره ډیره اړینه دي. وګورئ اګروپیو AI مشیر، د ځمکه یاداشتې، موسمی لارښوونکي، او محلي ژبې په یوه پاکستان مخکې پلیټفارم پورته کوموي.",
  "wy.hero.eyebrow": "ځای اګروپیو",
  "wy.hero.titleLead": "کله چې خاورو",
  "wy.hero.titleAccent": "سیګنل ته م contact",
  "wy.hero.sub": "د کښتکاری فیصلې د حدس لپاره ډیره اړینه دي. اګروپیو AI مشیر، ستا د ځمکه یاداشتې، موسمی لارښوونکي، او ستا د خپلې ژبه په یوه پلیټفارم پورته کوي — ترڅو هره غوښتنه ستا د ځمکه حقیقت ته اساس شي.",
  "wy.hero.ctaPrimary": "مخکینی رسایی تر لاسه کړئ",
  "wy.hero.ctaSecondary": "پلیټفارم وګورئ",
  "wy.hero.tagStart": "پاکستان لپاره جوړ شوی",
  "wy.hero.tagThen": "اپلینوډ ته یوه پروډکټ",
  "wy.hero.svgLabel": "د ځمکه په سیمه کې راتلونکي څنډه",
  "wy.origin.eyebrow": "موږ دا څنګه جوړ کړو",
  "wy.origin.heading": "لوړه ریسک فیصلې د حدس ته نه شي کېدلی",
  "wy.origin.sub": "اګروپیو د یوه ساده مشاهده څخه پیل شوی: د کښتکار سیzon د پنځه غوښتنو پر بیا فیصله شي، او هره غوښتنه د هوښه پشتونې ته اړینه ده.",
  "wy.origin.g1Title": "وخت حدس دی",
  "wy.origin.g1Desc": "آبیاري، کود، بونۍ، ټولونګي — هغه لحظې چې سیzon فیصلهوي ابھی په عادت او هیله بڼه غوره شي.",
  "wy.origin.g2Title": "تاریخچه ورکېږي",
  "wy.origin.g2Desc": "څه سپری شوی و، کله ځمکه ابیاري شوې، کومه ناروغۍ پختمله تېرېدلې — هیڅکله ثبت نه شي، نو هیڅکله زده کېدلی نشي.",
  "wy.origin.g3Title": "مشوره شیا شیا دی",
  "wy.origin.g3Desc": "ګاګينه، دENCYALUN، او ویډیو هره یوه جواب ورکوي — خو هیڅ سرچ ستا کشت، ستا خاورو، یا دا اونۍ آسمان ویلي.",
  "wy.origin.banner": "د حدس لګد په ټولونګي کې ادایي شي",
  "wy.diff.eyebrow": "څنګه جلا دي",
  "wy.diff.heading1": "ن بل مشوره اپلیکیشن نه.",
  "wy.diff.heading2": "یوه د ځمکه هوښه پلیټفارم.",
  "wy.diff.sub": "ډیره امترز جوابونه ورکوي. اګروپیو ستا ځمکه زده کوي — او د هر سرګرمۍ چې تاسو ثبت کوي ډیره ګټوره کېږي.",
  "wy.diff.personalTitle": "شخصي، نه عمومي",
  "wy.diff.personalDesc": "سفارشې د ستا کشت، ستا ځای، فعلي موسم، او ستا د ځمکه تاريخ بڼه جوړ شي — هیڅکله یوه سایز ټولو لپاره نه.",
  "wy.diff.chip1": "ستا کشت",
  "wy.diff.chip2": "ستا ضلع",
  "wy.diff.chip3": "دا اونۍ موسم",
  "wy.diff.chip4": "ستا پختمله سیzon",
  "wy.diff.langTitle": "ستا ژبه ویلي",
  "wy.diff.langDesc": "د هغه اندازه وپرسئ او پوه شئ چې تاسو واقعي ویل کوي — تکنیکی انګلیزي نه دی اړین.",
  "wy.diff.memoryTitle": "د هر ځمکه یاد",
  "wy.diff.memoryDesc": "آبیاري، مواد، ناروغۍ، لګدې، ټولونګي — هره سرګرمۍ منظم یاداشت په بدل شي، ترڅو هره سیzon د پختملې څخه ښه پیل شي.",
  "wy.diff.weatherTitle": "دموسم بڼه اصلي",
  "wy.diff.weatherDesc": "لارښوونکي حقیقي حالات ویلي مخکې ورسیږي — ترڅو سپری مخکې بارش نه شي.",
  "wy.diff.platformTitle": "یوه پلیټفارم، بشپړ سیzon",
  "wy.diff.platformDesc": "مشیر، یاداشتې، موسمی لارښوونکي، او مشورې یوځای کاروي نه په جلا اپلیکیشنونو کې.",
  "wy.diff.pakTitle": "پاکستان مخکې",
  "wy.diff.pakDesc": "محلي کشتې، محلي طریقې، او حقیقي حالات د لومړۍ ورځ څخه ډیزاین شوي — نه ورو ورو تر لاسه شوی.",
  "wy.diff.pakBadge": "دلته مخکې جوړ شوی",
  "wy.life.eyebrow": "مشیر څه څه پوښیږي",
  "wy.life.heading": "د ټولو فیصلو لپاره لارښوونکي",
  "wy.life.sub": "یوه مشیر د بشپړ د کشت ژوند سیکل سه تاسو سره تلیږي — د سیzon راتلو ته تر ټولونګي ته.",
  "wy.life.s1Title": "د آبیاري وخت",
  "wy.life.s1Desc": "زوئ کله ابیاري کړئ — او کله انتظار کړئ.",
  "wy.life.s2Title": "د کشت منځلی",
  "wy.life.s2Desc": "کشتې او بونۍ مخکې غوره کړئ چې ستا ځمکه سره ښه شي.",
  "wy.life.s3Title": "کود او حشره‌کش لارښوونکي",
  "wy.life.s3Desc": "مناسب مواد، مناسب مقدار، مناسب لحظه.",
  "wy.life.s4Title": "د حشراتو او ناروغۍ ملاتړ",
  "wy.life.s4Desc": "ستونزې مخکې وګورئ او مخکې چې په ټولو کې شي.",
  "wy.life.s5Title": "د ټولونګي وخت",
  "wy.life.s5Desc": "هغه لحظه غوره کړئ چې پیداړه او معیار خوندي کوي.",
  "wy.life.s6Title": "موسم بڼه سفارشې",
  "wy.life.s6Desc": "هر مشوره نن حالت اول ویلي.",
  "wy.life.s7Title": "ورځنۍ پرسې",
  "wy.life.s7Desc": "ستا د کشت په اړه هر څه وپرسئ، د سیzon هر ورځ.",
  "wy.value.eyebrow": "د پیمان",
  "wy.value.heading1": "څه کړئ. کله کړئ.",
  "wy.value.heading2": "او څه کېدلی دی.",
  "wy.value.sub": "د اګروپیو هره ځانګړتیا یوه د دې دریو جوابونو څخه خدمت کوي — دا ده چې یوه سیzon فیصلو څخه یوه سیzon اطمینان ته بدلووي.",
  "wy.value.p1Heading": "څه کړئ",
  "wy.value.p1Desc": "ستا کشت او حالات لپاره واضح، معلوم سفارشې — نه عمومي مشورې.",
  "wy.value.p2Heading": "کله کړئ",
  "wy.value.p2Desc": "وخت د حقیقي موسم او نشوونمو مرحله سره تنظیم شوی، ترڅو مناسب عمل په مناسب لحظه شي.",
  "wy.value.p3Heading": "څه کېدلی دی",
  "wy.value.p3Desc": "د هر سرګرمۍ منظم تاریخچه — همیشه شته، همیشه ډیره ښه مشوره ته ویلي.",
  "wy.who.eyebrow": "د کومو لپاره",
  "wy.who.heading": "د کښتکار څخه ورو ورو وسیع",
  "wy.who.a1Title": "انفرادي کښتکار",
  "wy.who.a1Desc": "عملي، شخصي ملاتړ د هر فیصلې لپاره — بیا د هر کېدلی شی منظم یاداشت.",
  "wy.who.a2Title": "تاجراني ځمکې او کښتکاري کسب",
  "wy.who.a2Desc": "منظم د ځمکه معلومات او باورګانی فیصله ملاتړ د ټیمو، ځمکو، او سیzonو پورته.",
  "wy.who.a3Title": "د ټولنې شراکت دار",
  "wy.who.a3Desc": "د مواد راوړونه، کوآپریټو، بیمه‌کوونه، او وروشیو خدمات چې د پلیټفارم سره غړي شي.",
  "wy.who.strip": "د ځمکه په څنګر کې د ټولنې سره غړيږي",
  "auth.backHome": "اصل ته بیرته",
  "auth.emailLabel": "ایمیل پته",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "رمز",
  "auth.showPassword": "رمز ښکاره کړئ",
  "auth.hidePassword": "رمز پټ کړئ",
  "auth.err.emailRequired": "خپل ایمیل پته ورکړئ.",
  "auth.err.emailInvalid": "سمه ایمیل پته ورکړئ.",
  "auth.err.passwordRequired": "رمز غوره کړئ.",
  "auth.err.passwordMin": "لاږه ۸ توري وکاروئ.",
  "auth.err.passwordMax": "تر ۶۴ توري.",
  "auth.err.nameRequired": "خپل بشپړ نوم ورکړئ.",
  "auth.err.phoneInvalid": "سمه ټلیفون شمیره ورکړئ.",
  "auth.err.confirmRequired": "خپل رمز بیرته ورکړئ.",
  "auth.err.termsRequired": "د بیرته تل لپاره شرایط قبول کړئ.",
  "auth.err.passwordMismatch": "رمزونه مطابقت نه لري.",
  "auth.err.loginPasswordRequired": "خپل رمز ورکړئ.",
  "auth.err.tooManyAttempts": "ډیره څېړنه — بیا هڅه وکړئ.",
  "auth.err.serverError": "موږ ته ستونزه راغله. بیا هڅه وکړئ.",
  "auth.err.invalidCredentials": "نسمه ایمیل یا رمز.",
  "li.meta.title": "ننوزرکوئ — اګروپیو",
  "li.meta.description": "اګروپیو ته ننوزرکوئ، د AI پر بڼه د ځمکه هوښه پلیټفارم. ستا مشیر، یاداشتې، او مشورې — هغه ځای کې چې تاسو پریږدئ.",
  "li.brand.headingA": "ستا د ځمکه هوښه،",
  "li.brand.headingB": "هغه ځای کې چې تاسو پریږدئ.",
  "li.demo.aria": "د اګروپیو مشیر سره د بیانو نمونه",
  "li.demo.user": "زما د ګندم پټۍ زردي شي وي — څه وکړم؟",
  "li.demo.advisorLabel": "دوه وجوهات:",
  "li.demo.advisorBody": "د اوبو کمبودي یا نایټروجن کمبودي. اول منځنۍ وخت کې اوبه ورکړئ.",
  "li.point1": "ستا د خپلې ژبه کې AI مشیر",
  "li.point2": "سیټلایټ د کشت صحت مانیټرنګ",
  "li.point3": "د هر سیzon ډیجیټل یاداشتې",
  "li.eyebrow": "ننوزرکوئ",
  "li.heading": "ستا د ځمکه ته بیرته راغلاست",
  "li.sub": "ستا د ځمکه مشیر، یاداشتې، او مشورې ته ننوزرکوئ.",
  "li.passwordPlaceholder": "ستا رمز",
  "li.forgot": "رمز مو هېدلی دی؟",
  "li.submitting": "ننوزرکوو…",
  "li.noAccount": "ابھی حساب نه لري؟ مخکینی رسایی د علاقو بedly ورکوي —",
  "li.noAccountEnd": ".",
  "li.createAccount": "حساب جوړ کړئ",
  "su.meta.title": "حساب جوړ کړئ — اګروپیو",
  "su.meta.description": "خپل اګروپیو حساب جوړ کړئ: شخصي AI مشیر، موسمی لارښوونکي، او د ځمکه یاداشتې چې هره سیzon ډیره ښه کوي. پاکستان لپاره جوړ شوی.",
  "su.brand.headingA": "خپل سیzon پیل کړئ",
  "su.brand.headingB": "د هوښه سره.",
  "su.profile.aria": "د ثبت نامو بعد جوړ شوې د ځمکه پروفایل نمونه",
  "su.profile.badge": "د ځمکه پروفایل · د یو منټ کې چمتو",
  "su.profile.district": "ضلع",
  "su.profile.crop": "کشت",
  "su.profile.language": "د مشورې ژبه",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "ګندم · ربیع",
  "su.profile.langValue": "رومان اردو",
  "su.included1": "د لومړۍ ورځ څخه شخصي مشیر",
  "su.included2": "ستا ضلع لپاره موسمی لارښوونکي",
  "su.included3": "د ځمکه یاداشتې چې هره سیzon ډیره ښه کوي",
  "su.eyebrow": "حساب جوړ کړئ",
  "su.heading": "خپل ځمکه اګروپیو ته راشي",
  "su.sub": "ستا مشیر، یاداشتې، او دې سیzon هر مشورې لپاره یوه حساب.",
  "su.registered.title": "دا ایمیل مخکې ثبت شوی دی.",
  "su.registered.body": "بیا ننوزرکوئ، یا رمز بیرته ورکړئ اګر مو هېدلی — ستا ځمکه هغه ځای کې پاتې ده چې تاسو پریږدئ.",
  "su.registered.reset": "رمز بیرته ورکړئ",
  "su.name.label": "بشپړ نوم",
  "su.name.placeholder": "لاندې مثلاً محمد احمد",
  "su.phone.label": "ټلیفون شمیره",
  "su.phone.optional": "(اختیاري)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "د SMS اعلانونو لپاره کله چې تاسو آفلاین وي.",
  "su.password.placeholder": "لاږه ۸ توري",
  "su.confirm.label": "رمز تایید کړئ",
  "su.confirm.placeholder": "خپل رمز بیرته ورکړئ",
  "su.strength0": "ډیره کم",
  "su.strength1": "سم دی",
  "su.strength2": "ښه دی",
  "su.strength3": "تیز دی",
  "su.terms.prefix": "زه شرایط قبول کوم",
  "su.terms.tos": "د خدمات شرایط",
  "su.terms.and": "او",
  "su.terms.privacy": "د محرمیت پالیسي",
  "su.terms.end": ".",
  "su.submit": "زما حساب جوړ کړئ",
  "su.submitting": "حساب جوړیږي…",
  "su.haveAccount": "مخکې حساب لري؟",
  "app.shell.metadataTitle": "اګروپیو — AI پر بڼه د ځمکه هوښه پلیټفارم",
  "app.shell.metadataDescription": "نن د مشورې، موسم، اعلان، او هر اګروپیو امترز — پاکستان لپاره جوړ شوی. اپلینوډ ته یوه پروډکټ.",
  "app.shell.nav.dashboard": "ډیشبورډ",
  "app.shell.nav.farms": "ځمکې",
  "app.shell.nav.advisor": "مشیر",
  "app.shell.nav.detect": "ویش",
  "app.shell.nav.crops": "کشتې",
  "app.shell.nav.prices": "قیمته",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "اعلانات",
  "app.shell.nav.settings": "ترتیبات",
  "app.shell.nav.more": "نور",
  "app.shell.signOut": "وتونه",
  "app.shell.aria.farmerTools": "د کښتکار امترز",
  "app.shell.aria.currentPage": "فعلي صفحه",
  "app.dashboard.greeting": "سلام، {name}",
  "app.dashboard.aria.profileMenu": "د پروفایل مینو",
  "app.dashboard.welcomeEyebrow": "اګروپیو ته ښه راغلاست",
  "app.dashboard.welcomeTitle": "خپل لومړۍ ځمکه پیل کړئ.",
  "app.dashboard.welcomeBody": "ستا کشت، ستا خاورو، ستا موسم — هره مشوره د ویلو ته م芒 شیږي کله چې ستا ځمکه شته شي.",
  "app.dashboard.addFirstFarm": "لومړۍ ځمکه اضافه کړئ",
  "app.dashboard.badge.today": "نن",
  "app.dashboard.aria.advisoryTitle": "نن د مشورې",
  "app.dashboard.carryToField": "د ځمکه ته وړوئ",
  "app.dashboard.askAdvisor": "مشیر ته وپرسئ",
  "app.dashboard.aria.weatherTitle": "موسم · {location}",
  "app.dashboard.aria.degreesCelsius": "{n} درجه سیلسیس",
  "app.dashboard.fullForecast": "بشپړ پیش‌گویي",
  "app.dashboard.weatherUnavailable": "موسم ابھی لودل نشي. ورو ورو بیا وګورئ — ستا مشورې ابھی کارووي.",
  "app.dashboard.seasonTipBadge": "د سیzon مشوره",
  "app.dashboard.alertsHeading": "اعلانات",
  "app.dashboard.newCount": "{n} نوي",
  "app.dashboard.viewAllAlerts": "ټول اعلانات وګورئ",
  "app.dashboard.noAlerts": "نن اعلانات نه دي — ستا کشتې آرام دي.",
  "app.dashboard.aria.alert": "اعلان",
  "app.dashboard.severity.critical": "سخت",
  "app.dashboard.severity.watch": "وګورئ",
  "app.dashboard.severity.info": "معلومه",
  "app.dashboard.languageLabel": "ژبه",
  "app.dashboard.weatherNoLocation": "د موسم ډیټا د ستا ځمکه ځای تایید شو په بدل شي.",
  "app.dashboard.weatherYourArea": "ستا سیمه",
  "app.dashboard.quickActionsHeading": "چټک اعمال",
  "app.dashboard.cropDoctor": "د کشت ډاکټر",
  "app.dashboard.detectTitle": "ناروغۍ مخکې ویشئ",
  "app.dashboard.detectBody": "متاثر پته عکس ونیسئ — تشخیص او بل څه کړئ د تلیفون پورته.",
  "app.dashboard.recommendCrops": "د کشت سفارش",
  "app.dashboard.recommendCropsBody": "ستا خاورو، موسم، او ځای بڼه شخصي د کشت سفارشې تر لاسه کړئ.",
  "app.dashboard.myFarms": "زما ځمکې",
  "app.dashboard.addFarm": "ځمکه اضافه کړئ",
  "app.dashboard.viewAllFarms": "ټول ځمکې وګورئ",
  "app.dashboard.health.good": "ښه",
  "app.dashboard.health.watch": "وګورئ",
  "app.dashboard.setupChecklist": "ځمکه تنظیم کړئ",
  "app.dashboard.checklistProgress": "{done} د {total} بشپړ",
  "app.dashboard.aria.dismissChecklist": "د تنظیم چیک لسټ پریږدئ",
  "app.dashboard.aria.setupProgress": "د تنظیم پیشرفت",
  "app.dashboard.demoFooter": "د ډیمو جوړونه · یوازې نمونه ډیټا",
  "app.prices.globalSearchViewPrices": "قیمته وګورئ",
  "app.prices.globalSearchNoResults": "هیڅ نتیجه نه دی",
  "app.prices.globalSearchMandis": "بازارونه",
  "app.prices.globalSearchCrops": "کشتې",
  "app.prices.globalSearchPlaceholder": "کشتې یا بازارونه لټونه…",
  "app.advisor.chat.farmerYou": "تاسو",
  "app.advisor.chat.composerHint": "خپله پرسه لیکئ…",
  "app.advisor.chat.typing": "لیکي…",
  "app.advisor.chat.onlineStatus": "آنلاین",
  "app.advisor.chat.emptyBody": "د کشت، موسم، خاورو، او بازاری قیمتو په اړه مشوره تر لاسه کړئ.",
  "app.advisor.chat.emptyTitle": "ستا د ځمکه په اړه هر څه وپرسئ",
  "app.advisor.chat.emptyEyebrow": "د مشیر چیټ",
  "app.dashboard.pricesWidgetNoTracked": "قیمته وګورئ د کشتونو تر لاسه",
  "app.dashboard.pricesWidgetPerMaund": "د منډۍ پر",
  "app.dashboard.pricesWidgetView": "قیمته وګورئ",
  "app.dashboard.pricesWidgetTitle": "بازاري قیمته",
  "app.dashboard.demo.todayLabel": "یکشنبه، ۲۳ اګست",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "ګندم",
  "app.dashboard.demo.advisoryStage": "شنه",
  "app.dashboard.demo.advisoryAction": "نن آبیاري ورو کړئ",
  "app.dashboard.demo.advisoryWhy": "شپته ډیره بارش ته امید — ستا ځمکه ابahi آسمان ته.",
  "app.dashboard.demo.seasonAction": "بارش مخکې خپل ځمکې ګږئ",
  "app.dashboard.demo.seasonWhy": "د خشکه تیر تاتیی ورو ګږئ ویلي چې کومه برخې ابahi اوبه مه شي — بونۍ مخکې ثبت کړئ.",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "احمال",
  "app.dashboard.demo.rainNote": "۲ بجې بعد بارش احتمالي · ۸۰٪ احتمال",
  "app.dashboard.demo.alertWhitefly": "د سپین مړی خطره د کچو په ملتان ضلع کې دا اونۍ لوړه ده.",
  "app.dashboard.demo.alertRain": "نن ۲ بجې بعد بارش ته امید — سپری وړاندیزه پریږدئ.",
  "app.dashboard.demo.alertPrice": "د ګندم قیمته ملتان منډی کې د پختملې اونۍ څخه ۴٪ پورته شوې.",
  "app.dashboard.demo.farm1Name": "خلیل پور ځمکه",
  "app.dashboard.demo.farm1Location": "خلیل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "ګندم",
  "app.dashboard.demo.farm1Stage": "شنه",
  "app.dashboard.demo.farm2Name": "سahiwal ډټ",
  "app.dashboard.demo.farm2Location": "د دیپالپور لاره، سahiwal",
  "app.dashboard.demo.farm2Crops": "کچه",
  "app.dashboard.demo.farm2Stage": "ګل بند",
  "app.dashboard.demo.farm3Name": "چک ۶۲ GB",
  "app.dashboard.demo.farm3Location": "چک ۶۲ GB، فیصل اباد",
  "app.dashboard.demo.farm3Crops": "ګنی",
  "app.dashboard.demo.farm3Stage": "شنه ورو",
  "app.dashboard.demo.checklistAdvisor": "مشیر ته یو ځل وپرسئ",
  "app.dashboard.demo.checklistDetect": "لومړۍ ویش ته ټوله",
  "app.dashboard.demo.actionAdvisor": "مشیر ته وپرسئ",
  "app.dashboard.demo.actionScan": "کشت اسکین",
  "app.dashboard.demo.actionPrices": "قیمته وګورئ",
  "app.dashboard.demo.actionRecord": "یاداشت اضافه کړئ",
  "app.dashboard.demo.actionRecommend": "کشتې سفارش کړئ",
  "app.farms.eyebrow": "ځمکې",
  "app.farms.health.good": "ښه",
  "app.farms.health.watch": "وګورئ",
  "app.farms.units.acres": "ایکړ",
  "app.farms.stages.sowing": "بونۍ",
  "app.farms.stages.tillering": "شنه ورو",
  "app.farms.stages.vegetative": "شنه",
  "app.farms.stages.grainFilling": "د غوتي ډکول",
  "app.farms.stages.ready": "چمتو",
  "app.farms.stages.squaring": "ګل بند",
  "app.farms.stages.flowering": "ګل پیداول",
  "app.farms.stages.bollFilling": "د ګنی ډکول",
  "app.farms.stages.grandGrowth": "لوړه شنه",
  "app.farms.stages.ripening": "پخته کېدل",
  "app.farms.stages.harvest": "ټولونګي",
  "app.farms.stages.panicleInitiation": "پنکل پیل",
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سahiwal",
  "app.farms.districts.faisalabad": "فیصل اباد",
  "app.farms.districts.vehari": "ویهاری",
  "app.farms.districts.bahawalpur": "بهوالپور",
  "app.farms.districts.lodhran": "لودھرن",
  "app.farms.crops.wheat": "ګندم",
  "app.farms.crops.cotton": "کچه",
  "app.farms.crops.sugarcane": "ګنی",
  "app.farms.crops.maize": "جار",
  "app.farms.crops.rice": "بریَنه",
  "app.farms.list.pageTitle": "ځمکې — اګروپیو",
  "app.farms.list.heading": "ټول ستا ځمکې، یوه لیست",
  "app.farms.list.description": "هره ځمکه د کشتونو، نشوونمو مرحلو، او صحت سره یو لید. ځمکه ټیپ کړئ د بشپړ کیسه لپاره.",
  "app.farms.list.addLink": "اضافه",
  "app.farms.list.openFarm": "ځمکه خلاصه کړئ",
  "app.farms.list.addNewFarm": "نوې ځمکه اضافه کړئ",
  "app.farms.list.emptyHeading": "ابھی ځمکې نه دي",
  "app.farms.new.pageTitle": "ځمکه اضافه کړئ — اګروپیو",
  "app.farms.new.heading": "ځمکه اضافه کړئ",
  "app.farms.new.description": "اګروپیو ته خپله ځمکه ویئ — ځای، کشت، او اندازه — ترڅو هره مشوره دا سره ډیزاین شي.",
  "app.farms.new.fields.name": "د ځمکه نوم",
  "app.farms.new.placeholders.name": "لاندې مثلاً خلیل پور ځمکه",
  "app.farms.new.fields.district": "ضلع / شار",
  "app.farms.new.placeholders.district": "ضلع / شار غوره کړئ",
  "app.farms.new.fields.crop": "اصلي کشت",
  "app.farms.new.placeholders.crop": "کشت غوره کړئ",
  "app.farms.new.fields.acres": "سیمه (ایکړ)",
  "app.farms.new.placeholders.acres": "لاندې مثلاً ۱۲.۵",
  "app.farms.new.fields.location": "ځای / کلي",
  "app.farms.new.placeholders.location": "کلي یا شار نوم لیکئ",
  "app.farms.new.fields.primaryCrop": "اصلي کشت",
  "app.farms.new.fields.sowingDate": "د بونۍ تاریخ",
  "app.farms.new.fields.soilType": "د خاورو ډول",
  "app.farms.new.fields.irrigationMethod": "د آبیاري تریبه",
  "app.farms.new.placeholders.soilType": "خاورو، لوهم، ریملی، یا سیلت",
  "app.farms.new.buttons.saving": "خونديږي…",
  "app.farms.new.buttons.save": "ځمکه خوندي کړئ",
  "app.farms.new.demoNotice": "د ډیمو · خوندي کول بانک ته نه ده وصل شوی",
  "app.farms.new.success.heading": "ځمکه د ډیمو کې خوندي شوې",
  "app.farms.new.success.description": "د بشپړ جوړونو کې دا ځمکه ستا ډیشبورډ پورته شي او ستا مشورې پیل کوي.",
  "app.farms.new.success.goToFarms": "زما ځمکې ته",
  "app.farms.new.success.backToDashboard": "ډیشبورډ ته بیرته",
  "app.farms.new.errors.nameRequired": "ځمکه ته نوم ورکړئ.",
  "app.farms.new.errors.districtRequired": "ضلع غوره کړئ.",
  "app.farms.new.errors.cropRequired": "اصلي کشت غوره کړئ.",
  "app.farms.new.errors.acresRequired": "سیمه د ایکړونو کې ورکړئ.",
  "app.farms.detail.pageTitle": "د ځمکه تفصیلات — اګروپیو",
  "app.farms.detail.heroEyebrow": "د ځمکه تفصیلات",
  "app.farms.detail.goodHealth": "ښه صحت",
  "app.farms.detail.needsWatching": "وګورئ وړ",
  "app.farms.detail.sownLabel": "بونۍ وشوه",
  "app.farms.detail.seasonHeading": "کشت څنګه دي",
  "app.farms.detail.activityHeading": "د ځمکه سرګرمۍ",
  "app.farms.detail.viewAllRecords": "ټول یاداشتې وګورئ",
  "app.farms.detail.logFieldEvent": "د ځمکه پیښه ثبت کړئ",
  "app.farms.detail.scanCrop": "دا کشت اسکین کړئ",
  "app.farms.detail.noRecords": "ابھی یاداشتې نه دي — د ځمکه یاد د جوړولو لپاره سرګرمۍ ثبت کړئ.",
  "app.records.eyebrow": "د ځمکه یاداشتې",
  "app.records.types.irrigation": "آبیاري",
  "app.records.types.fertilizer": "کود",
  "app.records.types.pesticide": "حشره‌کش",
  "app.records.types.disease": "ناروغۍ",
  "app.records.types.harvest": "ټولونګي",
  "app.records.farmRecords.pageTitle": "د ځمکه یاداشتې — اګروپیو",
  "app.records.farmRecords.heading": "د ځمکه یاد",
  "app.records.farmRecords.description": "هره آبیاري، سپری، او تداوی ثبت شوې — ترڅو راتلونکي فیصلې د یاد ته اړین نه شي.",
  "app.records.farmRecords.demoNotice": "د ډیمو · یوازې نمونه یاداشتې — نوې خوندي کول بانک ته نه ده وصل شوی",
  "app.records.new.pageTitle": "نوې یاداشت — اګروپیو",
  "app.records.new.heading": "ځمکه کې څه وشلي ثبت کړئ",
  "app.records.new.description": "آبیاري، کود، حشره‌کش، ناروغۍ، او ټولونګي — ستا د ځمکه یاد، یو لیک په یو وخت.",
  "app.records.new.fields.type": "څه وشلي دی؟",
  "app.records.new.fields.farm": "ځمکه",
  "app.records.new.placeholders.farm": "ځمکه غوره کړئ",
  "app.records.new.fields.date": "نیټه",
  "app.records.new.fields.title": "لنډ سرلیک",
  "app.records.new.fields.optional": "(اختیاري)",
  "app.records.new.placeholders.titleIrrigation": "لاندې مثلاً نهري · بشپړ ځمکه",
  "app.records.new.placeholders.titleOther": "دوه منډۍ سره ګندې",
  "app.records.new.fields.details": "تفصیلات",
  "app.records.new.placeholders.details": "هر شی چې راتلونکي ورځ یاد ایښودل شته دي — مقدارونه، موسم، ځمکه څنګه لید.",
  "app.records.new.buttons.saving": "خونديږي…",
  "app.records.new.buttons.save": "یاداشت خوندي کړئ",
  "app.records.new.demoNotice": "د ډیمو · خوندي کول بانک ته نه ده وصل شوی",
  "app.records.new.success.heading": "یاداشت د ډیمو کې خوندي شوې",
  "app.records.new.success.description": "د بشپړ جوړونو کې دا یاداشت ستا د ځمکه یاداشتونو لیست کې شي او راتلونکي مشورې ډیره ښه کوي.",
  "app.records.new.success.backToDashboard": "ډیشبورډ ته بیرته",
  "app.records.new.success.viewFarms": "زما ځمکې وګورئ",
  "app.records.new.errors.farmRequired": "ځمکه غوره کړئ.",
  "app.records.new.errors.dateRequired": "نیټه غوره کړئ.",
  "app.advisor.pageTitle": "مشیر",
  "app.advisor.sidebar.title": "خبرې اترې",
  "app.advisor.sidebar.newConversation": "نوې خبرې اترې",
  "app.advisor.sidebar.noConversations": "ابھی خبرې اترې نه دي. نوې پیل کړئ!",
  "app.advisor.sidebar.rename": "بیرته نوم کړئ",
  "app.advisor.sidebar.delete": "ړنګ کړئ",
  "app.advisor.sidebar.deleteTitle": "خبرې اترې ړنګ کړئ",
  "app.advisor.sidebar.deleteConfirm": "دا خبرې اترې ړنګ کړئ؟ دا بیرته نه کېدلی.",
  "app.advisor.sidebar.cancel": "لغوه",
  "app.advisor.sidebar.closeSidebar": "باندې بند کړئ",
  "app.advisor.chat.placeholder": "ستا د کشت، موسم، قیمتو په اړه…",
  "app.advisor.chat.send": "استوئ",
  "app.advisor.chat.thinking": "فکر کوي…",
  "app.advisor.chat.openingGreeting": "سلام! زه ستا د اګروپیو د کښتکاری مشیر یم. ستا د کشت، موسم، منډی قیمتو، یا حکومتي پروګرامونو په اړه هر څه وپرسئ.",
  "app.advisor.chat.photoRedirect": "د عکس ویش د ویش صفحه کې دي — کشت اسکین ټیپ کړئ د عکسونو څخه ناروغۍ ویشل.",
  "app.advisor.chat.nonFarmingRedirect": "زه د کښتکاری پرسې ته ملاتړ کوم. ستا کشت یا ځمکه تهڅنګه ملاتړ کول شي؟",
  "app.advisor.chat.tryAsking": "دا وپرسئ",
  "app.advisor.chat.suggested1": "د ګندم کومه ناروغۍ دی؟",
  "app.advisor.chat.suggested2": "نن ملتان کې بارش وي؟",
  "app.advisor.chat.suggested3": "نن منډی قیمته څه دي؟",
  "app.advisor.chat.suggested4": "Kissan Card پروګرام ته ویئ",
  "app.advisor.errors.serviceUnavailable": "د مشیر خدمت موقتي طور ته نه شته. بیا هڅه وکړئ.",
  "app.advisor.errors.rateLimited": "ډیره غوښتنه. لرې ورو ورو بیا هڅه وکړئ.",
  "app.advisor.errors.network": "د نیټه ستونزه. خپله اړیکه وګورئ او بیا هڅه وکړئ.",
  "app.advisor.errors.generic": "ستونزه راغله. بیا هڅه وکړئ.",
  "app.advisor.aria.openSidebar": "خبرې اترې خلاصه کړئ",
  "app.advisor.aria.sendMessage": "پیغام استوئ",
  "app.advisor.aria.chatMessages": "چیټ پیغامونه",
  "app.detect.eyebrow": "د کشت ډاکټر",
  "app.detect.title": "ناروغۍ مخکې ویشئ",
  "app.detect.uploadPrompt": "ناروغه پته عکس ونیسئ",
  "app.detect.takePhoto": "عکس ونیسئ یا غوره کړئ",
  "app.detect.sampleScan": "عکس نه لري؟ نمونه اسکین وکړئ",
  "app.detect.readingLeaf": "پته لوستل کېږي…",
  "app.detect.analyzing": "تجزیه کېږي…",
  "app.detect.scanAnother": "بلا پته اسکین کړئ",
  "app.detect.discussAdvisor": "مشیر سره ویل کړئ",
  "app.detect.saveToFarm": "ځمکه ته خوندي کړئ",
  "app.detect.savedToFarm": "خوندي شوې د {farm}",
  "app.detect.notSaved": "خوندي نه شوې",
  "app.detect.confidence": "باوري {pct}٪",
  "app.detect.whatToDo": "ابھی څه کړئ",
  "app.detect.caution": "هیڅکله سپری مخکې خپل محلي د کښتکاری office ته تایید کړئ.",
  "app.detect.noFarmsTitle": "لومړۍ ځمکه ثبت کړئ",
  "app.detect.noFarmsBody": "خپل اسکین ځمکه ته وصل کړئ ترڅو بشپړ د ناروغۍ تاريخ جوړ شي.",
  "app.detect.addFarm": "ځمکه اضافه کړئ",
  "app.detect.dismiss": "زه دا ورو ورو کوم",
  "app.detect.pastScans": "تیر شوي اسکین",
  "app.detect.loadMore": "نور بار کړئ",
  "app.detect.invalidFile": "عکس فایل ونیسئ.",
  "app.detect.serviceUnavailable": "خدمت موقتي طور ته نه شته. بیا هڅه وکړئ.",
  "app.detect.noDiagnosis": "ناروغۍ ویشل نه شي — د متاثر سیمه صافتر عکس ویسئ.",
  "app.detect.retry": "بیا هڅه",
  "app.detect.savedStatus": "خوندي شوې د {farm}",
  "app.detect.unsavedStatus": "خوندي نه شوې",
  "app.detect.dragDropPrompt": "عکس دلته وشئ یا کلیک کړئ",
  "app.detect.dragDropPromptLine1": "عکس دلته وشئ",
  "app.detect.dragDropPromptLine2": "یا کلیک کړئ",
  "app.detect.historyEmpty": "ابھی اسکین نه دي. عکس ونیسئ.",
  "app.detect.linkToFarm": "ځمکه ته وصل کړئ",
  "app.detect.severity.watch": "وګورئ",
  "app.detect.severity.treatNow": "ابھی علاج کړئ",
  "app.detect.severity.clear": "صاف",
  "app.detect.chat.newScan": "نوی اسکین",
  "app.detect.chat.placeholder": "د دې ویش په اړه…",
  "app.detect.chat.send": "استوئ",
  "app.detect.chat.thinking": "فکر کوي…",
  "app.detect.chat.imagePreview": "بشپړ عکس وګورئ",
  "app.detect.chat.closePreview": "نمونه بند کړئ",
  "app.detect.chat.emptyState": "د دې ویش په اړه اضافي پرسه وپرسئ.",
  "app.detect.chat.sessionsTitle": "د ویش چیټ",
  "app.detect.chat.noSessions": "ابھی د ویش چیټ نه دي.",
  "app.detect.chat.deleteSession": "session ړنګ کړئ",
  "app.detect.chat.deleteConfirm": "ایا تاسو یقین لري چې دا چیټ ړنګ کړئ؟",
  "app.detect.chat.cancel": "لغوه",
  "app.detect.sidebar.title": "تاریخچه",
  "app.detect.sidebar.newScan": "نوی اسکین",
  "app.detect.sidebar.closeSidebar": "باندې بند کړئ",
  "app.detect.sidebar.noHistory": "ابھی اسکین یا چیټ نه دي.",
  "app.detect.sidebar.scansTitle": "تیر شوي اسکین",
  "app.detect.sidebar.chatsTitle": "د چیټ sessionونه",
  "app.detect.crop.apple": "مټه",
  "app.detect.crop.blueberry": "بلیو بیری",
  "app.detect.crop.cherry": "چیری",
  "app.detect.crop.corn": "جار",
  "app.detect.crop.grape": "میوه",
  "app.detect.crop.orange": "مالٹه",
  "app.detect.crop.peach": "آرو",
  "app.detect.crop.pepper": "مرچ",
  "app.detect.crop.potato": "آلو",
  "app.detect.crop.raspberry": " Респberry",
  "app.detect.crop.soybean": "سویا بین",
  "app.detect.crop.squash": "کدو",
  "app.detect.crop.strawberry": "اسٹرابیری",
  "app.detect.crop.tomato": "ګندنه",
  "app.detect.rescan.7": "۷ ورځې بعد بیا اسکین کړئ",
  "app.detect.rescan.14": "۱۴ ورځې بعد بیا اسکین کړئ",
  "app.detect.rescan.21": "۲۱ ورځې بعد بیا اسکین کړئ",
  "app.detect.healthy.name": "صحتمند",
  "app.detect.healthy.causes": "د دې پته په ناروغۍ نه لیدل شوې.",
  "app.detect.healthy.steps.0": "د تداوی اړینه نه. بشپړ پاملرنه او ویشتونه دوامه.",
  "app.detect.disease.apple_scab.name": "د مټې اڃونه",
  "app.detect.disease.apple_scab.causes": "د ډېرمEnumer سپورې سردي او ګیلي اونۍ کې شیږي او ټکلي پټۍ او میوه ته واوبه.",
  "app.detect.disease.apple_scab.steps.0": "د ایزان پټۍ ویشتئ او ورکړئ د بیرته ډوس کېدو مخنیوی لپاره.",
  "app.detect.disease.apple_scab.steps.1": "د بهار کې د بټن پر خونه کې حاورو تیل یا مس ته اساس شوی fungicide سپری کړئ.",
  "app.detect.disease.apple_scab.steps.2": "هوا نیول غونډلي او ابahi آبياري ونکړئ.",
  "app.detect.disease.apple_black_rot.name": "د مټېتور سیاه نکرو",
  "app.detect.disease.apple_black_rot.causes": "د ډېرمEnumer fungi میوه او شاخونه ته واوبه، د ګیلي او ګرم موسم څخه.",
  "app.detect.disease.apple_black_rot.steps.0": "متاثر شاخونه وTabControl مخکې سوزئ.",
  "app.detect.disease.apple_black_rot.steps.1": "د ګل او پته څیدل بعد fungicide وکړئ.",
  "app.detect.disease.apple_black_rot.steps.2": "غونډه خلاصه کړئ او mulch نه وکړئ.",
  "app.detect.disease.apple_cedar_rust.name": "سیډر-مټې اڃونه",
  "app.detect.disease.apple_cedar_rust.causes": "د ګیلي اอำเภونه سردي بهار کې د مټې او شرقی سیډر ته واوبه.",
  "app.detect.disease.apple_cedar_rust.steps.0": "د اڃونه مقاومت لرونکي جوټه غوره کړئ.",
  "app.detect.disease.apple_cedar_rust.steps.1": "د بټن خونه او شونdzi بهار کې copper سپری کړئ.",
  "app.detect.disease.apple_cedar_rust.steps.2": "۵۰۰ میټر په نږدې red cedar ویشتئ.",
  "app.detect.disease.cherry_powdery_mildew.name": "د چیري سپین ډېرمEnumer",
  "app.detect.disease.cherry_powdery_mildew.causes": "د ګرم ورځو او سردي شپن سره سپین پود پټۍ پورته کوي.",
  "app.detect.disease.cherry_powdery_mildew.steps.0": "د ډک غونډو شاخونه وipayele hevi hevi.",
  "app.detect.disease.cherry_powdery_mildew.steps.1": "لومړۍ خشې لیدل شول sulfur یا fungicide سپری کړئ.",
  "app.detect.disease.cherry_powdery_mildew.steps.2": "د نایټروجن ډیر کود نه وکړئ.",
  "app.detect.disease.corn_gray_leaf_spot.name": " wzgl غبرګونه",
  "app.detect.disease.corn_gray_leaf_spot.causes": "د ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.corn_gray_leaf_spot.steps.0": "د اڃونه مقاومت لرونکي جوټه غوره کړئ.",
  "app.detect.disease.corn_gray_leaf_spot.steps.1": "د ګل کېfungicide وکړئ.",
  "app.detect.disease.corn_gray_leaf_spot.steps.2": "ماسپر آبیاري کړئ.",
  "app.detect.disease.corn_common_rust.name": "د جار عام اڃونه",
  "app.detect.disease.corn_common_rust.causes": "د شبنم او منځنۍ حرارت څخه ا念佛.",
  "app.detect.disease.corn_common_rust.steps.0": "د ا念佛 مقاومت لرونکي جوټه غوره کړئ.",
  "app.detect.disease.corn_common_rust.steps.1": "د ګل کېsystemic fungicide وکړئ.",
  "app.detect.disease.corn_common_rust.steps.2": "جار د جار ورو نه وکړئ.",
  "app.detect.disease.corn_northern_leaf_blight.name": "شمالي پته ا念佛",
  "app.detect.disease.corn_northern_leaf_blight.causes": "سردي او ګیلي موسم کې ویشږي.",
  "app.detect.disease.corn_northern_leaf_blight.steps.0": "سویا بین سره ګریزه وکړئ.",
  "app.detect.disease.corn_northern_leaf_blight.steps.1": "د ا念佛 مقاومت لرونکي جوټه غوره کړئ.",
  "app.detect.disease.corn_northern_leaf_blight.steps.2": "هوا نیولو لپاره فاصله وکړئ.",
  "app.detect.disease.grape_black_rot.name": "د میوه سیاه نکرو",
  "app.detect.disease.grape_black_rot.causes": "ګیلي بهار کې ویشږي.",
  "app.detect.disease.grape_black_rot.steps.0": "متاثر شاخونه ویشتئ.",
  "app.detect.disease.grape_black_rot.steps.1": "د ګل کې fungicide وکړئ.",
  "app.detect.disease.grape_black_rot.steps.2": "د ګل کې ابahi آبياري ونکړئ.",
  "app.detect.disease.grape_esca.name": "د میوه اسکا (سیاه میلا)",
  "app.detect.disease.grape_esca.causes": "د رګونو fungi سیاه خشې او پټۍ ورو کوي.",
  "app.detect.disease.grape_esca.steps.0": "متاثر چوب ویشتئ او ورکړئ.",
  "app.detect.disease.grape_esca.steps.1": "د بټن خونه کېlime sulfur یا copper سپری کړئ.",
  "app.detect.disease.grape_esca.steps.2": "د اوبو استرس ورو کړئ.",
  "app.detect.disease.grape_leaf_blight.name": "د میوه پته ا念佛",
  "app.detect.disease.grape_leaf_blight.causes": "ګیلي حالات کې سیاه خشې او زردي حلقو.",
  "app.detect.disease.grape_leaf_blight.steps.0": "لومړۍ متاثر پټۍ ویشتئ او ورکړئ.",
  "app.detect.disease.grape_leaf_blight.steps.1": "د نشوونمو وخت کې fungicide وکړئ.",
  "app.detect.disease.grape_leaf_blight.steps.2": "هوا نیول غونډلي.",
  "app.detect.disease.orange_huanglongbing.name": "د مالټې ناروغۍ (Huanglongbing)",
  "app.detect.disease.orange_huanglongbing.causes": "د psyllids څخه ا念佛، زردي خشې، نسمه میوه، او درخت دgi.",
  "app.detect.disease.orange_huanglongbing.steps.0": "د Asian citrus psyllid سپری وکړئ.",
  "app.detect.disease.orange_huanglongbing.steps.1": "متاثر درختې ویشتئ — نه کېدلی.",
  "app.detect.disease.orange_huanglongbing.steps.2": "د ناروغۍ وړتیاوې نه لرونکي نسلي مواد استعمال کړئ.",
  "app.detect.disease.peach_bacterial_spot.name": "د آرو باکټیریل خشې",
  "app.detect.disease.peach_bacterial_spot.causes": "د اوبو څیدل څخه ا念佛.",
  "app.detect.disease.peach_bacterial_spot.steps.0": "خشکه موسم کې وipayele او امترز.",
  "app.detect.disease.peach_bacterial_spot.steps.1": "د ګل او بارش بعد copper وکړئ.",
  "app.detect.disease.peach_bacterial_spot.steps.2": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.pepper_bacterial_spot.name": "د مرچ باکټیریل خشې",
  "app.detect.disease.pepper_bacterial_spot.causes": "ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.pepper_bacterial_spot.steps.0": "هوا نیولو لپاره فاصله وکړئ.",
  "app.detect.disease.pepper_bacterial_spot.steps.1": " copper وکړئ.",
  "app.detect.disease.pepper_bacterial_spot.steps.2": "متاثر پټۍ ویشتئ.",
  "app.detect.disease.potato_early_blight.name": "د آلو اولی ا念佛",
  "app.detect.disease.potato_early_blight.causes": "ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.potato_early_blight.steps.0": "د نسلي آلو غوره کړئ او ګریزه وکړئ.",
  "app.detect.disease.potato_early_blight.steps.1": "لومړۍ خشې لیدل شول fungicide وکړئ.",
  "app.detect.disease.potato_early_blight.steps.2": "خاورو ګندې ټکلي شاخونه ته وړوئ.",
  "app.detect.disease.potato_late_blight.name": "د آلو وروستی ا念佛",
  "app.detect.disease.potato_late_blight.causes": "د ګیلي موسم کې ډیره ویشږي.",
  "app.detect.disease.potato_late_blight.steps.0": "متاثر آلو او پټۍ ویشتئ — مه کمپوسټ.",
  "app.detect.disease.potato_late_blight.steps.1": "systemic fungicide وکړئ او هر ۵-۷ ورځې بیا.",
  "app.detect.disease.potato_late_blight.steps.2": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.squash_powdery_mildew.name": "د کدو سپین ډېرمEnumer",
  "app.detect.disease.squash_powdery_mildew.causes": "ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.squash_powdery_mildew.steps.0": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.squash_powdery_mildew.steps.1": "sulfur یا potassium bicarbonate وکړئ.",
  "app.detect.disease.squash_powdery_mildew.steps.2": "ماسپر ابahi.",
  "app.detect.disease.strawberry_leaf_scorch.name": "د اسٹرابیری پته ا念佛",
  "app.detect.disease.strawberry_leaf_scorch.causes": "ګیلي بهار کې ویشږي.",
  "app.detect.disease.strawberry_leaf_scorch.steps.0": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.strawberry_leaf_scorch.steps.1": "fungicide وکړئ.",
  "app.detect.disease.strawberry_leaf_scorch.steps.2": "متاثر پټۍ ویشتئ.",
  "app.detect.disease.tomato_bacterial_spot.name": "د ګندنه باکټیریل خشې",
  "app.detect.disease.tomato_bacterial_spot.causes": "د اوبو څیدل څخه ا念佛.",
  "app.detect.disease.tomato_bacterial_spot.steps.0": "د ناروغۍ نه لرونکي بونۍ غوره کړئ.",
  "app.detect.disease.tomato_bacterial_spot.steps.1": "copper وکړئ.",
  "app.detect.disease.tomato_bacterial_spot.steps.2": "متاثر پټۍ او میوه ویشتئ.",
  "app.detect.disease.tomato_early_blight.name": "د ګندنه اولی ا念佛",
  "app.detect.disease.tomato_early_blight.causes": "ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.tomato_early_blight.steps.0": "mulch وکړئ او ماسپر ابahi.",
  "app.detect.disease.tomato_early_blight.steps.1": " fungicide وکړئ.",
  "app.detect.disease.tomato_early_blight.steps.2": "متاثر پټۍ ویشتئ.",
  "app.detect.disease.tomato_late_blight.name": "د ګندنه وروستی ا念佛",
  "app.detect.disease.tomato_late_blight.causes": "ګیلي موسم کې ډیره ویشږي.",
  "app.detect.disease.tomato_late_blight.steps.0": "متاثر پټۍ او میوه ویشتئ — مه کمپوسټ.",
  "app.detect.disease.tomato_late_blight.steps.1": "systemic fungicide وکړئ او بارش بعد بیا.",
  "app.detect.disease.tomato_late_blight.steps.2": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.tomato_leaf_mold.name": "د ګندنه پته ډېرمEnumer",
  "app.detect.disease.tomato_leaf_mold.causes": "ګیلي او خفی هوا کې ویشږي.",
  "app.detect.disease.tomato_leaf_mold.steps.0": "هوا وړاندیز کړئ.",
  "app.detect.disease.tomato_leaf_mold.steps.1": " fungicide وکړئ.",
  "app.detect.disease.tomato_leaf_mold.steps.2": "ماسپر ابahi.",
  "app.detect.disease.tomato_septoria.name": "د ګندنه سیپټوریا خشې",
  "app.detect.disease.tomato_septoria.causes": "د ګرم موسم کې ویشږي.",
  "app.detect.disease.tomato_septoria.steps.0": "کشتې ګریزه وکړئ.",
  "app.detect.disease.tomato_septoria.steps.1": "fungicide وکړئ.",
  "app.detect.disease.tomato_septoria.steps.2": "متاثر پټۍ ویشتئ.",
  "app.detect.disease.tomato_spider_mites.name": "د ګندنه عنکبوتی ډېرمEnumer",
  "app.detect.disease.tomato_spider_mites.causes": "د اوبو څیدل څخه ا念佛.",
  "app.detect.disease.tomato_spider_mites.steps.0": "اوبو سره ډېرمEnumer وړوئ.",
  "app.detect.disease.tomato_spider_mites.steps.1": "neem oil وکړئ.",
  "app.detect.disease.tomato_spider_mites.steps.2": "عمومي insecticides ونکړئ.",
  "app.detect.disease.tomato_target_spot.name": "د ګندنه هدف خشې",
  "app.detect.disease.tomato_target_spot.causes": "ګرم او ګیلي موسم کې ویشږي.",
  "app.detect.disease.tomato_target_spot.steps.0": "هوا وړاندیز کړئ.",
  "app.detect.disease.tomato_target_spot.steps.1": "fungicide وکړئ.",
  "app.detect.disease.tomato_target_spot.steps.2": "ماسپر ابahi.",
  "app.detect.disease.tomato_ylcv.name": "د ګندنه زردي پته ویروس",
  "app.detect.disease.tomato_ylcv.causes": "د سپین مړی څخه ا念佛.",
  "app.detect.disease.tomato_ylcv.steps.0": "سپین مړی کtrl وکړئ.",
  "app.detect.disease.tomato_ylcv.steps.1": "متاثر غوښه ویشتئ — نه کېدلی.",
  "app.detect.disease.tomato_ylcv.steps.2": "د ا念佛 مقاومت لرونکي غوره کړئ.",
  "app.detect.disease.tomato_mosaic_virus.name": "د ګندنه موزاییک ویروس",
  "app.detect.disease.tomato_mosaic_virus.causes": "د امترزو او لاسو څخه ا念佛.",
  "app.detect.disease.tomato_mosaic_virus.steps.0": "امترز کIFE وکړئ.",
  "app.detect.disease.tomato_mosaic_virus.steps.1": "متاثر غوښه ویشتئ.",
  "app.detect.disease.tomato_mosaic_virus.steps.2": "د ا念佛 مرسته کړئ.",
  "app.weather.pageTitle": "د موسم مشوره",
  "app.weather.eyebrow": "موسم",
  "app.weather.description": "ستا د کشت لپاره ورځنۍ کښتکاری مشورې، د پیش‌گویي او کشت د نشوونمو مرحله سره.",
  "app.weather.todayAdvisory": "نن د مشورې",
  "app.weather.growthStage": "د نشوونمو مرحله",
  "app.weather.severity.info": "معلومه",
  "app.weather.severity.warning": "خبرتیا",
  "app.weather.severity.critical": "سخت",
  "app.weather.forecastTitle": "۷ ورځنۍ پیش‌گویي",
  "app.weather.forecastSubtitle": "هر ورځ موسم او ستا کشت لپاره یوه کښتکاری مشوره.",
  "app.weather.weatherUnavailable": "د موسم ډیټا نه شته",
  "app.weather.weatherUnavailableBody": "ستا پختمله مشوره ښکاره کېږي. نوې مشوره راتلو ته پیش‌گویي.",
  "app.weather.farmSelectorLabel": "ځمکه",
  "app.weather.registerTitle": "ځمکه ثبت کړئ",
  "app.weather.registerBody": "ستا کشت، بونۍ، او ځای ورکړئ ترڅو ورځنۍ شخصي مشورې تر لاسه کړئ.",
  "app.weather.registerCta": "ځمکه ثبت کړئ",
  "app.weather.registerForm.crop": "اصلي کشت",
  "app.weather.registerForm.sowing": "د بونۍ تاریخ",
  "app.weather.registerForm.soil": "د خاورو ډول",
  "app.weather.registerForm.irrigation": "د آبیاري تریبه",
  "app.weather.registerForm.soilTypes": "خاورو، لوهم، ریملی، یا سیلت",
  "app.weather.registerForm.irrigationMethods": "قطره، ښbern، اوبه، یا باران",
  "app.weather.registerForm.save": "خوندي کړئ او زما مشوره وګورئ",
  "app.weather.registerForm.saving": "خونديږي…",
  "app.weather.registerForm.success": "خوندي شوی — دا ستا مشوره ده",
  "app.weather.registerForm.error": "ځمکه تفصیلات خوندي نه شي. بیا هڅه وکړئ.",
  "app.weather.historyTitle": "د مشورې تاریخچه",
  "app.weather.historySubtitle": "ستا ځمکو لپاره تیر شوي سفارشې، نوې مخکې.",
  "app.weather.history.empty": "ابھی تیر شوي مشورې نه دي.",
  "app.weather.history.date": "نیټه",
  "app.weather.history.severity": "شدت",
  "app.weather.history.status": "حالت",
  "app.weather.history.status.new": "نوی",
  "app.weather.history.status.seen": "وګورل شوی",
  "app.weather.history.status.acted": "عمل شوی",
  "app.weather.history.loadMore": "نور بار کړئ",
  "app.weather.history.viewAll": "بشپړ تاریخچه وګورئ",
  "app.weather.detail.back": "تاریخچه ته بیرته",
  "app.weather.detail.weatherConditions": "موسمی حالات",
  "app.weather.detail.recommendation": "سفارش",
  "app.weather.detail.markActed": "عمل شوی په بدل شي",
  "app.weather.detail.markAcknowledged": "وګورل شوی په بدل شي",
  "app.weather.detail.markedActed": "عمل شوی په بدل شوی",
  "app.weather.detail.markedSeen": "وګورل شوی په بدل شوی",
  "app.weather.alerts.title": "فعلي اعلانات",
  "app.weather.alerts.heavyRain": "ډیره بارش ته امید — آبیاري ورو کړئ او ټولونګي خوندي کړئ.",
  "app.weather.alerts.frost": "د یخ خطره — نسبت پټۍ ابahi.",
  "app.weather.alerts.extremeHeat": "تیزه ګرمۍ — آبیاري زیات کړئ او منځنۍ ځمکه نه.",
  "app.weather.alerts.diseaseRisk": "ګیلي ناروغۍ ته مرسته — د خشکه ماسپر fungicide.",
  "app.weather.alerts.dismiss": "پریږدئ",
  "app.weather.alerts.noAlerts": "ابھی فعلي اعلانات نه دي.",
  "app.weather.alerts.viewAll": "ټول اعلانات وګورئ",
  "app.weather.stages.seedling": "تیارکونکی",
  "app.weather.stages.vegetative": "شنه",
  "app.weather.stages.flowering": "ګل پیداول",
  "app.weather.stages.maturation": "پخته کېدل",
  "app.weather.stages.harvestReady": "ټولونګي چمتو",
  "app.weather.stages.generic": "عمومي",
  "app.weather.source.live": "ریالټم پیش‌گویي · OpenWeather",
  "app.weather.source.cached": "پختمله خوندي شوې پیش‌گویي",
  "app.weather.source.demo": "نمونه پیش‌گویي — ریالټم ډیټا لپاره API key ورکړئ",
  "app.weather.advisory.recommendation.irrigation": "نن آبیاري ونکړئ — بارش ته امید. اوبه خوندي کړئ.",
  "app.weather.advisory.recommendation.irrigateNow": "د سردي وختونو کې آبیاري — ګرمۍ زیاته کېږي او خاورو خشکیږي.",
  "app.weather.advisory.recommendation.fertilize": "کود لیږدلو مناسب وخت.",
  "app.weather.advisory.recommendation.sprayDisease": "ګیلي ناروغۍ ته مرسته — د خشکه ماسپر fungicide.",
  "app.weather.advisory.recommendation.heatProtect": "تیزه ګرمۍ — آبیاري زیات کړئ او منځنۍ ځمکه نه.",
  "app.weather.advisory.recommendation.frostProtect": "نن شپه یخ خطره — ټکلي غوښه ابahi یا اوبه ورکړئ.",
  "app.weather.advisory.recommendation.harvest": "کشتې د ټولونګي نږدې — خشکه ورځ لپاره ټولونګي وړاندیز کړئ.",
  "app.weather.advisory.recommendation.plantCare": "ساده نشوونه مرحله — منظم آبیاري او ویښتنې.",
  "app.weather.advisory.recommendation.generic": "نن مخصوص عمل نه — ځمکه او پیش‌گویي وګورئ.",
  "app.weather.buttons.register": "ځمکه ثبت کړئ",
  "app.weather.buttons.refresh": "بیا بار کړئ",
  "app.weather.errors.generic": "ستونزه راغله. بیا هڅه وکړئ.",
  "app.weather.errors.noFarm": "ځمکه غوره کړئ د مشورې لپاره.",
  "app.weather.metric.temperature": "حرارت",
  "app.weather.metric.precipitation": "بارش",
  "app.weather.metric.wind": " baş",
  "app.weather.metric.humidity": "ګیلي",
  "app.prices.eyebrow": "منډی قیمته",
  "app.prices.title": "بیا مخکې زوئ",
  "app.prices.description": "د نزدیکو منډیو نن نرخونه، ساده کلمه سره خوندي یا بیچئ.",
  "app.prices.selectCrop": "کشت غوره کړئ",
  "app.prices.searchPlaceholder": "پاکستان په ټولو کې کشت یا منډی لټونه",
  "app.prices.noData": "د قیمت ډیټا نه شته",
  "app.prices.updatedToday": "نن نو شوی",
  "app.prices.updatedDaysAgo": "{days} ورځې مخکې نو شوی",
  "app.prices.marketHoliday": "منډی بند / بازاری ورځ",
  "app.prices.perMaund": "/ منډۍ",
  "app.prices.bestPrice": "ښه نرخه",
  "app.prices.distanceKm": "{km} کیلومټر لرې",
  "app.prices.hold": "خوندي",
  "app.prices.sell": "بیچئ",
  "app.prices.recommendationHold": "د ښه نرخه لپاره خوندي",
  "app.prices.recommendationSell": "چټک بیچئ",
  "app.prices.volatilityWarning": "لوړ غیر یقیني / کم ډیټا",
  "app.prices.predictionTitle": "۱۴ ورځنۍ نرخ پیش‌گویي",
  "app.prices.historyTitle": "د نرخو تاریخچه",
  "app.prices.range1M": "۱ میاشت",
  "app.prices.range3M": "۳ میاشتې",
  "app.prices.range6M": "۶ میاشتې",
  "app.prices.range12M": "۱ کال",
  "app.prices.setAlert": "د نرخ اعلان",
  "app.prices.editAlert": "اعلان سمون",
  "app.prices.saveAlert": "اعلان خوندي کړئ",
  "app.prices.cancel": "لغوه",
  "app.prices.alertCrop": "کشت",
  "app.prices.alertMandi": "منډی",
  "app.prices.alertMandiOptional": "منډی (اختیاري)",
  "app.prices.alertStatus": "حالت",
  "app.prices.targetPrice": "غرض نرخ (PKR / منډۍ)",
  "app.prices.alertActive": "فعال",
  "app.prices.alertPaused": "درند",
  "app.prices.deleteAlert": "اعلان ړنګ کړئ",
  "app.prices.fallbackBanner": "ځمکه ځای ورکړئ ترڅو ستا ضلع څخه نرخونه خودکار وګورئ.",
  "app.prices.comparisonTitle": "بازارونه غبرګون",
  "app.prices.market": "بازار",
  "app.prices.modalPrice": "منځنۍ نرخه",
  "app.prices.minPrice": "کمترین نرخه",
  "app.prices.maxPrice": "لوړترین نرخه",
  "app.prices.change": "بدلون",
  "app.prices.distance": "فاصله",
  "app.prices.adminTitle": "د قیمت د کار غوره",
  "app.prices.adminDate": "نیټه",
  "app.prices.adminModalPrice": "منځنۍ نرخه",
  "app.prices.adminMinPrice": "کمترین نرخه",
  "app.prices.adminMaxPrice": "لوړترین نرخه",
  "app.prices.adminHoliday": "بازاري ورځ",
  "app.prices.adminSave": "نرخه خوندي کړئ",
  "app.prices.loading": "قیمته لري…",
  "app.prices.retry": "بیا هڅه",
  "app.prices.noPricesForCrop": "د دې کشت لپاره په نږدې نرخونه نه دي.",
  "app.prices.comingSoon": "ږدې راتلونکي",
  "app.crops.eyebrow": "د کشت سفارش",
  "app.crops.title": "دې سیzon څه منځلی؟",
  "app.crops.description": "ستا د ځمکه په اړه ویئ او موږ ستا خاورو، موسم، او بودیټه لپاره ټولو ګټور او پایداره کشتې رتبه کوو.",
  "app.crops.nav": "کشتې",
  "app.crops.form.farmLabel": "ځمکه",
  "app.crops.form.seasonLabel": "هدف سیzon",
  "app.crops.form.yearLabel": "هدف کال",
  "app.crops.form.soilLabel": "د خاورو ډول",
  "app.crops.form.irrigationLabel": "آبیاري",
  "app.crops.form.budgetLabel": "بودیټه",
  "app.crops.form.soilOther": "نه پوهیږم / بل",
  "app.crops.form.submit": "سفارشې تر لاسه کړئ",
  "app.crops.form.submitting": "سفارشې حسابیږي…",
  "app.crops.form.lowestViableWarning": "د ستا بودیټه لپاره هیڅ کشت نه شي. ستا د ځمکه لپاره اقل هېلو بودیټه \"{bracket}\" دی.",
  "app.crops.form.switchBracket": "{bracket} ته بدل کړئ",
  "app.crops.form.noFarm": "لومړۍ ځمکه اضافه کړئ.",
  "app.crops.form.geoError": "سفارشې یوازې پاکستان کې د ځمکو لپاره دي.",
  "app.crops.form.regionalSoilNote": "د ستا ضلع د علاقایي د خاورو پروفایل بڼه.",
  "app.crops.form.nationalSoilNote": "د ټولپلاز ټوکنی بڼه، نه ستا علاقې.",
  "app.crops.seasons.summer": " Spaß",
  "app.crops.seasons.winter": "ژر",
  "app.crops.seasons.autumn": "خاورو",
  "app.crops.seasons.spring": "بهار",
  "app.crops.seasons.rainy": "باراني",
  "app.crops.seasons.windy": "سیم",
  "app.crops.soil.sandy": "ریملی",
  "app.crops.soil.sandy_loam": "ریملی لوهم",
  "app.crops.soil.loamy": "لوهم",
  "app.crops.soil.clay_loam": "خاورو لوهم",
  "app.crops.soil.clay": "خاورو",
  "app.crops.soil.silty": "سیلت",
  "app.crops.soil.saline": "شوري",
  "app.crops.soil.rocky": "د څاڅکو",
  "app.crops.soil.other": "نه پوهیږم / بل",
  "app.crops.budget.low": "کم (تر ۲۵,۰۰۰ روپیو / ایکړ)",
  "app.crops.budget.medium": "منځنۍ (۲۵,۰۰۰–۶۰,۰۰۰ روپیو / ایکړ)",
  "app.crops.budget.high": "لوړ (۶۰,۰۰۰–۱۲۰,۰۰۰ روپیو / ایکړ)",
  "app.crops.budget.very_high": "ډیره لوړ (۱۲۰,۰۰۰ روپیو پورته)",
  "app.crops.irrigation.rainfed": "باراني",
  "app.crops.irrigation.canal": "نهري",
  "app.crops.irrigation.tubewell": "ټیوب ول",
  "app.crops.irrigation.mixed": "ګوني",
  "app.crops.results.title": "ستا د لومړی ۳ کشتې",
  "app.crops.results.rank": "رتبه {n}",
  "app.crops.results.revenue": "تخمیني عایدي / ایکړ",
  "app.crops.results.reason": "څنګه دا کشت",
  "app.crops.results.risks": "اصلي خطرې",
  "app.crops.results.saveToPlan": "د ځمکه منځلي ته خوندي",
  "app.crops.results.saved": "منځلي ته خوندي شوی",
  "app.crops.results.compare": "کشتې غبرګون",
  "app.crops.results.projectionNote": "عایدي تخمینه ده، نه ضمانت — {sources} بڼه.",
  "app.crops.results.sourceWeather": "موسم",
  "app.crops.results.sourceMarket": "بازار",
  "app.crops.results.sourceSoil": "خاورو",
  "app.crops.results.weatherMissing": "د موسم ډیټا نه شته — دا سفارش کم د موسم تفصیل استعمال کوي.",
  "app.crops.results.marketMissing": "د بازار نرخه نه شته، نو عایدي غیر موثق.",
  "app.crops.results.soilMissing": "د خاورو ډیټا محدود و، نو باوري کم.",
  "app.crops.results.regenerate": "بیا جوړ کړئ",
  "app.crops.results.regenerateConfirm": "دا ستا اوسني سفارشې بدل کوي. ادامه؟",
  "app.crops.results.alreadyExists": "ستا تل دا سفارش شته ده.",
  "app.crops.results.viewExisting": "شته وګورئ",
  "app.crops.results.noCandidates": "د ستا سیzon او بودیټه لپاره هیڅ کشت نه شي. لوړ بودیټه غوره کړئ.",
  "app.crops.results.replacedPlan": "ستا پختمله منځلي بدل شوی.",
  "app.crops.detail.title": "د سفارش تفصیل",
  "app.crops.detail.back": "سفارشې ته بیرته",
  "app.crops.detail.confidence": "باوري",
  "app.crops.detail.scoreBreakdown": "د نمر تفصیل",
  "app.crops.detail.suitability": "مطابقت",
  "app.crops.detail.weatherFit": "د موسم مطابقت",
  "app.crops.detail.profitability": "ګټه",
  "app.crops.detail.risk": "خطره (کمتر ښه ده)",
  "app.crops.detail.sustainability": "پایداري",
  "app.crops.detail.final": "وروستی نمره",
  "app.crops.detail.dataFreshness": "د ډیټا عمر: {seconds} ثانیې",
  "app.crops.detail.soilImpact": "د خاورو اثر",
  "app.crops.water.low": "کم",
  "app.crops.water.medium": "منځنۍ",
  "app.crops.water.high": "لوړ",
  "app.crops.confidence.high": "لوړ",
  "app.crops.confidence.medium": "منځنۍ",
  "app.crops.confidence.low": "کم",
  "app.crops.confidence.unreliable": "غیر موثق",
  "app.crops.risk.price_volatility": "د نرخو غیر یقیني",
  "app.crops.risk.pest_pressure": "د حشراتو خطره",
  "app.crops.risk.weather": "د موسم خطره",
  "app.crops.risk.water_stress": "د اوبو خطره",
  "app.crops.risk.input_cost": "د مواد لګد",
  "app.crops.soilImpact.improves": "خاورو ښه کوي",
  "app.crops.soilImpact.neutral": "بې طرف",
  "app.crops.soilImpact.depletes": "خاورو ته کوي",
  "app.crops.compare.title": "ستا د لومړی ۳ کشتې غبرګون",
  "app.crops.compare.close": "غبرګون بند",
  "app.crops.compare.revenue": "تخمیني عایدي / ایکړ",
  "app.crops.compare.duration": "د نشوونمو ورځې",
  "app.crops.compare.water": "د اوبو اړینه",
  "app.crops.compare.marketRisk": "د بازار خطره",
  "app.crops.compare.soilImpact": "د خاورو اثر",
  "app.crops.compare.labour": "د کار لګد",
  "app.crops.compare.chartAria": "د دریو سفارش شوو کشتونو غبرګونی برک",
  "app.crops.compare.chartUnavailable": "برک نه شته — جدول ښکاره کېږي.",
  "app.crops.compare.selectToSave": "کشت غوره کړئ خونديولو",
  "app.crops.compare.saveSelected": "غوره شوې خوندي کړئ",
  "app.crops.rotation.title": "د کشت ګریزه منځلي",
  "app.crops.rotation.subtitle": "د خاورو صحت لپاره بیا څه منځلی.",
  "app.crops.rotation.generic": "عمومي مشوره — نه ستا د ځمکه تاریخچه بڼه.",
  "app.crops.rotation.nextSeason": "بل: {season} {year}",
  "app.crops.rotation.savedTitle": "خوندي شوی منځلي او ګریزه",
  "app.crops.catalogue.empty": "هیڅ کشت نه شي.",
  "app.crops.errors.serviceUnavailable": "د سفارش خدمت موقتي طور ته نه. بیا هڅه.",
  "app.crops.errors.generic": "ستونزه راغله. بیا هڅه.",
  "app.crops.errors.notFound": "سفارش نه موندل شوې.",
  "app.crops.errors.rateLimited": "ډیره غوښتنه. لرې ورو ورو.",
  "app.crops.reason.suitability": "{crop} ستا {soil} خاورو ته ډیره مطابقت لري.",
  "app.crops.reason.weather_fit": "{crop} ستا علاقې {season} موسم سره مطابقت لري.",
  "app.crops.reason.profit": "{crop} ستا بودیټه لپاره ډیره ګټه لري.",
  "app.crops.reason.rotation_fit": "{crop} ستا پختمله منځلي سره ښه تلیږي او خاورو بیا جوړوي.",
  "app.crops.reason.low_risk": "{crop} دې سیzon لپاره ټولو کم خطره لري.",
  "app.crops.reason.generic": "{crop} ستا د مواد لپاره ښه غوره دی.",
  "app.crops.rotation.wheat_then_mung": "منګ د ګندم بعد نایټروجن ثابت کوي.",
  "app.crops.rotation.wheat_then_chickpea": "چنا د ګندم بعد خاورو ښه کوي.",
  "app.crops.rotation.wheat_then_cotton": "کچه د ګندم بعد د پنجاب کې عام تلیږي.",
  "app.crops.rotation.cotton_then_wheat": "ګندم د کچو بعد ځمکه بیا جوړوي.",
  "app.crops.rotation.cotton_then_maize": "جار د کچو بعد ښه ځمکه ته تلیږي.",
  "app.crops.rotation.rice_then_wheat": "د بریَنه بعد ګندم عام ترتیب.",
  "app.crops.rotation.rice_then_maize": "جار د بریَنه بعد باقي ویلي اوبه.",
  "app.crops.rotation.maize_then_potato": "آلو د جار بعد لوهم خاورو کې.",
  "app.crops.rotation.maize_then_wheat": "ګندم د جار بعد ګریزه.",
  "app.crops.rotation.potato_then_maize": "جار د آلو بعد.",
  "app.crops.rotation.sugarcane_then_maize": "جار د ګنی بعد.",
  "app.crops.rotation.mung_then_wheat": "ګندم د منګ بعد حاصل.",
  "app.crops.rotation.chickpea_then_cotton": "کچه د چنا بعد ثابت شوې نایټروجن.",
  "app.crops.rotation.mustard_then_cotton": "کچه د توریا بعد.",
  "app.crops.rotation.soybean_then_wheat": "ګندم د سویا بعد.",
  "app.crops.rotation.onion_then_maize": "جار د پیاز بعد.",
  "app.crops.rotation.tomato_then_wheat": "ګندم د ګندنه بعد.",
  "app.crops.catalogue.barley": "جو",
  "app.crops.catalogue.bajra": "بجرا",
  "app.crops.catalogue.jowar": "جوار",
  "app.crops.catalogue.tobacco": "ټباکو",
  "app.crops.catalogue.sunflower": "ګل آفتاب",
  "app.crops.catalogue.canola": "کینولا",
  "app.crops.catalogue.sesame": "ګندنه",
  "app.crops.catalogue.lentil": "مسور",
  "app.crops.catalogue.pigeon_pea": "د کبوتر مٹر",
  "app.crops.catalogue.black_gram": "تور مٹر",
  "app.crops.catalogue.pea": "مٹر",
  "app.crops.catalogue.cowpea": "کویا",
  "app.crops.catalogue.cauliflower": "پل‌ګنۍ",
  "app.crops.catalogue.cabbage": "ګنۍ",
  "app.crops.catalogue.brinjal": "بازنۍ",
  "app.crops.catalogue.okra": "بامی",
  "app.crops.catalogue.chili": "مرچ",
  "app.crops.catalogue.garlic": "ګارلک",
  "app.crops.catalogue.ginger": "ادرک",
  "app.crops.catalogue.cucumber": "ګوا",
  "app.crops.catalogue.watermelon": "هندونه",
  "app.crops.catalogue.pumpkin": "کدو",
  "app.crops.catalogue.carrot": "ګاجر",
  "app.crops.catalogue.spinach": "اسپیناچ",
  "app.crops.catalogue.fenugreek": "میتھی",
  "app.crops.catalogue.mango": "امب",
  "app.crops.catalogue.citrus": "مالټه",
  "app.crops.catalogue.guava": "ګواوا",
  "app.crops.catalogue.apple": "مټه",
  "app.crops.rotation.barley_then_chickpea": "د ګریزه ګټه: جو تر چنا",
  "app.crops.rotation.bajra_then_cowpea": "د ګریزه ګټه: بجرا تر کویا",
  "app.crops.rotation.sunflower_then_wheat": "د ګریزه ګټه: ګل آفتاب تر ګندم",
  "app.crops.rotation.canola_then_wheat": "د ګریزه ګټه: کینولا تر ګندم",
  "app.crops.rotation.lentil_then_cotton": "د ګریزه ګټه: مسور تر کچه",
  "app.crops.rotation.pea_then_maize": "د ګریزه ګټه: مٹر تر جار",
  "app.crops.rotation.cauliflower_then_pea": "د ګریزه ګټه: پل‌ګنۍ تر مٹر",
  "app.crops.rotation.okra_then_cowpea": "د ګریزه ګټه: بامی تر کویا",
  "app.crops.rotation.garlic_then_wheat": "د ګریزه ګټه: ګارلک تر ګندم",
  "app.shell.nav.profitLoss": "منفعت / نقصان",
  "app.records.noRecordsFound": "د دې فلټر لپاره هیڅ ریکارډ نه موندل شو.",
};

export type CatalogKey = keyof typeof ps;

