import type { CatalogKey } from "./en.ts";

/** پښتو — AI-drafted, founder-reviewed copy (plan D4). */
export const ps: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اګروپیو ولې؟",
  "nav.features": "ځانګړنې",
  "nav.howItWorks": "دا څنګه کار کوي",
  "nav.vision": "زموږ لیدلوری",
  "nav.signIn": "ننوتل",
  "nav.getEarlyAccess": "لومړنی لاسرسی ترلاسه کړئ",
  "nav.openMenu": "مینو پرانیستل",
  "nav.closeMenu": "مینو بندول",
  "common.languageSwitcherLabel": "ژبه بدله کړئ",
  "notFound.title": "پاڼه نه موندل شوه",
  "notFound.body": "هغه پاڼه چې تاسو یې لټوې موجوده نشته یا لیږدول شوې ده.",
  "notFound.backHome": "بېرته اګروپیو کور ته",
  "common.builtForPakistan": "د پاکستان لپاره جوړ شوی",
  "common.productOfAplinode": "د اپلینوډ محصول",
  "home.hero.eyebrow": "د مصنوعي ځیرکتیا پر بنسټ د کروندې پوهاوی پلیټفارم",
  "home.hero.titleLead": "د هوښیارې کړنې لپاره",
  "home.hero.titleAccent": "پوهاوی",
  "home.hero.subtitle": "یو پلیټفارم چې د AI سلاکار، سپوږمکۍ کتنه، بازار نرخونه او ستاسو د کروندې ریکارډونه یو ځای کوي — معلومات ستاسو په خپله ژبه روښانه پرېکړو ته بدلوي.",
  "home.hero.ctaSecondary": "وګورئ دا څنګه کار کوي",
  "home.hero.imageAlt": "بزګ په کره کې په ټابلیټ اګروپیو کاروي",
  "home.hero.readingCrop": "د فصل روغتیا",
  "home.hero.readingWeather": "هوا",
  "home.hero.readingSoil": "د خاورې لمدگی",
  "home.hero.noteExcellent": "غوره",
  "home.hero.noteClearSky": "پاکه آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "د اګروپیو وسیلې",
  "home.ticker.cropDoctor": "د فصل AI ډاکتر",
  "home.ticker.satelliteNdvi": "سپوږمکۍ NDVI کتنه",
  "home.ticker.mandiPrices": "بازار د نرخونو پوهه",
  "home.ticker.weatherAdvisories": "هوا سره سم مشورې",
  "home.ticker.farmRecords": "ډیجیټل کروندې ریکارډ",
  "home.ticker.advisoryLanguages": "په ۷ ژبو مشوره",
  "home.ticker.pestAlerts": "د حشراتو خبرداری",
  "home.ticker.offlineSms": "آفلاین + SMS",
  "home.problem.eyebrow": "ستونزه",
  "home.problem.title": "د کړنې پرېکړې باید اټکل نه وي",
  "home.problem.subtitle": "په ټول پاکستان کې بزګان د دود، سیمه ایزو مشورو او خپرو شویو معلوماتو سره سترې پرېکړې کوي. تاوان تر رېبلې وروسته ورکول کیږي.",
  "home.problem.item1Title": "ناڅرګند وخت",
  "home.problem.item1Body": "اوبه، سره، درمل، کینال، رېبل — مهم وختونه لا هم اټکلي دي، چې حاصل کموي او لګښت ضایع کوي.",
  "home.problem.item2Title": "ورک شوی ریکارډ",
  "home.problem.item2Body": "د موسمو پوهه په حافظه یا خپریدلو کتابچو کې پاتې کیږي. تیر کال چې څه کار وکړل، له هغه زده کړه ستونزه ده.",
  "home.problem.item3Title": "خپرې مشورې",
  "home.problem.item3Body": "ګاونډیان، پلورنان او ویډیوګاني ټول ځواب وایي — خو لږ یې د بزګ فصل، خاورې، هوا یا سیمې سره برابر وي.",
  "home.problem.kicker": "د اټکل تاوان تر رېبلې ورسته دی",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "ستاسو د کروندې پوهاوی،",
  "home.solution.titleB": "په یو ځای کې",
  "home.solution.subtitle": "د ټول موسم لپاره یو پلیټفارم — مشوره، ریکارډونه، هوا او بازار ستاسو د ځمکې له معلوماتو کار کوي، نه له عمومي مشورو.",
  "home.solution.card1Title": "څه کول",
  "home.solution.card1Body": "د اوبو، سرې، حشراتو کنټرول او د رېبلې وخت لپاره ځانګړي مشورې — ستاسو د فصل او حالاتو سره سم.",
  "home.solution.card1Answer": "د دې کري، د دې اونۍ لپاره روښانه مشوره.",
  "home.solution.card2Title": "کله یې کول",
  "home.solution.card2Body": "هوایی لارښود درته وايي کله کار وکړه، تر څو بده وخت او ناڅاپي حالات حاصل نه خوري.",
  "home.solution.card2Answer": "وخت د ریښتینې هوا او د فصل ودې سره سم.",
  "home.solution.card3Title": "څه شوي دي",
  "home.solution.card3Body": "هره کار — اوبه، ان پټ، ناروغي، لګښتونه، رېبل — په منظم ریکارډ کې ساتل شوي چې هر موسم ځیرک کوي.",
  "home.solution.card3Answer": "بشپړ تاریخ، تل موجود.",
};
