import type { CatalogKey } from "./en.ts";

/** Sindhi (سنڌي) — AI-translated. RTL language. */
export const sd: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "ڇو Agropioo",
  "nav.features": "خصوصيتيون",
  "nav.howItWorks": "هن ڪيئن ڪم ڪري ٿو",
  "nav.vision": "دريسن",
  "nav.signIn": "ننوزرکو",
  "nav.signUp": "رجسٽر",
  "nav.getEarlyAccess": "جلدي رسائي حاصل ڪريو",
  "nav.openMenu": "مینو کوليو",
  "nav.closeMenu": "مینو بند ڪريو",
  "nav.dashboard": "ڊيش بورڊ",
  "common.languageSwitcherLabel": "ٻولي بدلائيو",
  "notFound.title": "صفحو نه مليو",
  "notFound.body": "توھان جو ڳوليل صفحو موجود ناهي يا ٿي ويو هئي.",
  "notFound.backHome": "Agropioo گھر تي واپس",
  "common.builtForPakistan": "پاکستان لاءِ بڻايل",
  "common.productOfAplinode": "Aplinode جو پيداوار",
  "home.hero.eyebrow": "AI طاقتور کي crops جي انڊلنس پليٽ فارم",
  "home.hero.titleLead": "انڊلنس",
  "home.hero.titleAccent": "ذہين کي زراعت",
  "home.hero.subtitle": "هڪ پليٽ فارم جيڪو AI مشاور، سیٽلائٽ نگراني، بازار جا قيمتون، ۽ توھان جي کيerc جا ریکارڊ ڀيٽي آهي — بيانات کي صاف فیصلن ۾ بدلائي آهي، توھان جي ٻولي ۾.",
  "home.hero.ctaSecondary": "ڏيڪو ڇو هن ڪم ڪري ٿو",
  "home.hero.imageAlt": "کhet ۾ تيبلٽ تي Agropioo استعمال ڪندو کيec",
  "home.hero.readingCrop": "فصل جي صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٽي جي نمي",
  "home.hero.noteExcellent": " Ấbu",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "بهترين",
  "home.ticker.ariaLabel": "Agropioo پليٽ فارم جا قابلية",
  "home.ticker.cropDoctor": "AI فصل ڊاڪٽر",
  "home.ticker.satelliteNdvi": "سیٽلائٽ NDVI نگراني",
  "home.ticker.mandiPrices": "منڊي قيمت جي انڊلنس",
  "home.ticker.weatherAdvisories": "موسم واري مشورن",
  "home.ticker.farmRecords": "ڊجٽل کيec ریکارڊ",
  "home.ticker.advisoryLanguages": "7 ٻولين ۾ مشورو",
  "home.ticker.pestAlerts": "حشرات جا خبرداريون",
  "home.ticker.offlineSms": "آفلاين پهرين + SMS",
  "home.problem.eyebrow": "سامSy",
  "home.problem.title": "کيec جا فیصلن ڳانٽھ ڪيئن نه هئڻ",
  "home.problem.subtitle": "سڄري پاکستان ۾، کيec وارا اونچي استرس جا فیصلن روائتون، مقامي مشوري، ۽ بکرري معلومات سان ڪرتا آهن. قيمت ڏينهن تي ادا ٿي آهي.",
  "home.problem.item1Title": "بي يقين وقت",
  "home.problem.item1Body": "آبپاشي، کوDate، زهي کيمریکل، اچاء، ڏينهن — اهم لمحن اڃا تائي ڳانٽھ نال ڪئي جا رهيا آهن، output خسارو ۽ ضايع وڌار کي خريو آهي.",
  "home.problem.item2Title": "گم شدہ کيec تاريخ",
  "home.problem.item2Body": "موسمن جا علم ياد شخصن ۾ يا بکرري نوٽ بڪن ۾ رهيا آهن. پکيئن ڪم ڪيو، هن سال تي ٿاڳوليو نه سگهيو.",
  "home.problem.item3Title": "بکرري مشورا",
  "home.problem.item3Body": "پاسines، وڊيโอ، ۽ وڪري وارا سڀ جواب ڏيندە آهن — گھنوري کيec جي فصل، مٽي، موسم، يا مقام سان ملتا ناهن.",
  "home.problem.kicker": "ڳانٽھ جي قيمت ڏينهن تي ادا ٿي آهي",
  "home.solution.eyebrow": " حل",
  "home.solution.titleA": "توھان جي کيec جي انڊلنس،",
  "home.solution.titleB": "هڪ ڍڍي ۾",
  "home.solution.subtitle": "هڪ موسم لاءِ هڪ انڊلنس پليٽ فارم — مشورا، ریکارڊ، موسم، ۽ بازار توھان جي زمين جي بيانات سان ڪم ڪندا آهن، عام مشوري سان نه.",
  "home.solution.card1Title": "ڇو ڪريو",
  "home.solution.card1Body": "آبپاشي، کوDate، حشرات کنٹرول، ۽ ڏينهن جي وقتن لاءِ شخصي صلاح — توھان جي فصل ۽ حالت تي مبني.",
  "home.solution.card1Answer": "هن کhet، هن هفتو لاءِ صاف، مخصوص مشورو.",
  "home.solution.card2Title": "ڪڻهن ڪريو",
  "home.solution.card2Body": "موسم واري رهنمايي توهان کي سلي لمحو ۾ ڪم ڪرڻ جي راه ڏيکاري آهي، تاڪن برا وقت ۽ اچاڪ حالتون توھان جي output ضايع نه ڪن.",
  "home.solution.card2Answer": "وقت حقيقي موسم ۽ وڌنڊ جي مرحلو تي بنياد.",
  "home.solution.card3Title": "ڇو ڪيل آهي",
  "home.solution.card3Body": "هر سرگرمي — آبپاشي، وڌار، بيماري، خرچا، ڏينهن — هڪ منظم ریکارڊ طرح رکيل آهي جيڪو هر موسم کي ذہين بڻائي آهي.",
  "home.solution.card3Answer": "هڪ مکمل تاريخ، هميشه قريبي.",
  "home.features.eyebrow": "پليٽ فارم ۾",
  "home.features.titleA": "ڳڻا انجمن،",
  "home.features.titleB": "هڪ انڊلنس پليٽ فارم",
  "home.features.subtitle": "توھان جي ٻولي ۾ هڪ سوال مان لري موسم جي ریکارڊ تي — هر قابلية اڳيون کي ڏيندي آهي.",
  "home.features.advisorModule": "موڊل 01 · مشاور",
  "home.features.advisorTitle": "AI زراعتي مشاور",
  "home.features.advisorTopics": "آبپاشي · کوDate · حشرات ۽ بيماري · ڏينهن",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "Agropioo مشاور سان گفتگو جو نمونو ڪن جو ڳاڙهي پتي ڪن",
  "home.features.advisorUserMsg": "Meri gandum ki pattiyan peeli ho rahi hain — kya karoon?",
  "home.features.advisorReplyTitle": "Peeli pattiyan — do common causes:",
  "home.features.advisorReplyCause1": "پاني جو تناؤ",
  "home.features.advisorReplyCause1Rest": "— irrigate in the cool hours, before 9 AM.",
  "home.features.advisorReplyCause2": "نايٽروجن جوڪم",
  "home.features.advisorReplyCause2Rest": "— check the oldest leaves first; feed urea if needed.",
  "home.features.advisorReplyFooter": "Agar pattiyon ke neeche peeli dhariyan nazar aayein, photo bhejein — main bimari ki tashkhees kar dunga.",
  "home.features.advisorInputPlaceholder": "Apna sawal likhein ya bolein…",
  "home.features.advisorFooter": "Apni fasal ke baray mein kuch bhi puchain — rozana ke sawal bhi chaltay hain.",
  "home.features.recordsModule": "موڊل 02 · ریکارڊ",
  "home.features.recordsTitle": "ڊجٽل کيec ریکارڊ",
  "home.features.recordsDesc": "هر سرگرمي ليکيل ۽ منظم — تاڪن مشورا توھان جي زمين مان سيکهي.",
  "home.features.record1Activity": "آبپاشي",
  "home.features.record1Detail": "نہر · 40 منٽ",
  "home.features.record2Activity": "Urea 46% N",
  "home.features.record2Detail": "25 kg / acre",
  "home.features.record3Activity": "پتي جي اسڪين",
  "home.features.record3Detail": "بيماري نه ملي",
  "home.features.recordsCropTag": "گندم · ربي موسم",
  "home.features.languageModule": "موڊل 03 · ٻولي",
  "home.features.languageTitle": "توھان جي ٻولي، توھان جا لفظ",
  "home.features.languageDesc": "جئن توھان سوچوojisn آواز يا ټائپ ڪريو — ڪوبهٔ تکنیکي انگريزي ضروري ناهي.",
  "home.features.weatherModule": "موڊل 04 · موسم",
  "home.features.weatherTitle": "موسم واري رهنمايي",
  "home.features.weatherDesc": "مشورا ڏينھن جي حالتون چيڏوڳي ڏيندоро تي وڃي — بارش کان اڳ اسپري ڪريو ۽ توھان وڌار ضايع ڪري وڌار ٿي وئي آهي.",
  "home.features.weatherMockAria": "پانچ ڏينهن جي پيش گوئي جي پٽي جن جيitre بOUSE تي نه اسپري ڪرڻ جو مشورو آهي",
  "home.features.dayMon": "پير",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "خميس",
  "home.features.dayFri": "جمعو",
  "home.features.holdSpray": "اسپري رکو",
  "home.features.weatherLegend": "مشورو ڏينھن هائيپرلوڪل پيش گوئي مان ڌارايل",
  "home.features.moreLink": "پليٽ فارم وڌي رهيو آهي — سڄري قابلية جو ڍنچو ڏيڪو",
  "home.journey.eyebrow": "هن ڪيئن ڪم ڪري ٿو",
  "home.journey.title": "هڪ سوال موسم شروع ڪري ٿو",
  "home.journey.subtitle": "توھان جي پهرين سوال مان هڪ مکمل، ذہين کيec تاريخ تي آسان راه.",
  "home.journey.step1Title": "توھان جي کيec شامل ڪريو",
  "home.journey.step1Body": "توھان جو مقام، فصل، ۽ ابنيادي تفصيلون داخل ڪريو هڪ ڊجٽل کيec پروفايل بڻائڻ لاءِ.",
  "home.journey.step2Title": "AI کي پڇھو",
  "home.journey.step2Body": "توھان جو سوال ٻولي ۾ ڏنو يا بوليو جن ۾ توھان کي سهه آهي.",
  "home.journey.step3Title": "رهنمايي حاصل ڪريو",
  "home.journey.step3Body": "توھان جي فصل، موسم، مقام، ۽ کيec تاريخ تي بنياد مشورا وٺو.",
  "home.journey.step4Title": "سرگرمي ریکارڊ ڪريو",
  "home.journey.step4Body": "آبپاشي، کوDate، زهي کيمریکل، يا بيماري چند ٽيپن سان لاگ ڪريو.",
  "home.journey.step5Title": "تاريخ بنايو",
  "home.journey.step5Body": "هر ریکارڊ مستقبل جا تجويزن ذہين ۽ مربوط بڻائي ٿو.",
  "home.journey.step6Title": "نگراني جاري رکو",
  "home.journey.step6Body": "ريکارڊ جانچيو ۽ سڄري موسم ۾ ترقي نگراني ڪريو.",
  "home.matrix.eyebrow": "سڄري قابلية جو ڍنچو",
  "home.matrix.title": "ضروري تا حيرت",
  "home.matrix.subtitle": "هر خصوصيت ٻج بچائيندي آهي، خرچا گھٽائيندي آهي، يا آمدنی وڌائيندي آهي. هن ڪتاب طرح پڇھو — هر ڍنچو اڳيون تي بنياد.",
  "home.matrix.capabilitiesLabel": "قابلين",
  "home.matrix.tier1Name": "ضروري",
  "home.matrix.tier1Badge": "بنیادي",
  "home.matrix.t1f1Title": "AI فصل بيماري جي نشانديهي",
  "home.matrix.t1f1Body": "متاثر پتي جو فوٹو اپلوڊ ڪريو ۽ فوري بيماري جو تشخيص، شدت، ۽ علاج جا تجويز وٺو.",
  "home.matrix.t1f2Title": "سیٽلائٽ کhet نگراني",
  "home.matrix.t1f2Body": "توھان جي کhet جي حدون علامت ڪريو ۽ مفت Sentinel-2 تصوiren مان NDVI بنياد فصل جي صحت جا زون ڏيکاري.",
  "home.matrix.t1f3Title": "ذہين موسم جو مشورو",
  "home.matrix.t1f3Body": "هائيپرلوڪل پيش گوئي توھان جي فصل ۽ وڌنڊ جي مرحلو سان مل کي روزانو، عملي مشورا بڻائيندا آهن.",
  "home.matrix.t1f4Title": "منڊي قيمت ٽریکر ۽ پيش گوئي",
  "home.matrix.t1f4Body": "ذہين AI پيش گوئي سان قرباني بازار جا قيمتون ٽریک ڪريو، تاڪن توھان سلي وقتي وڃيئن.",
  "home.matrix.tier2Name": "درميانو",
  "home.matrix.tier2Badge": "هڪار",
  "home.matrix.t2f1Title": "علاقائي ٻولي وائيس چيٽ بوٽ",
  "home.matrix.t2f1Body": "Urdu، Punjabi، Saraiki، ۽ ٻين ٻولين ۾ بوليو يا ڏنو — پڌرو ٻولي ۾ سنڌي.",
  "home.matrix.t2f2Title": "حکومتي اسکيم ملائيندڙ",
  "home.matrix.t2f2Body": "توھان جو پروفايل داخل ڪريو ۽ هر اسکيم وڌائيو جن ۾ توھان حق رکندو آهي، دستاويزون ۽ درخواست جي لنکن سان.",
  "home.matrix.t2f3Title": "فصل جي تجويز انجمن",
  "home.matrix.t2f3Body": "توھان جي مٽي، موسم، بازار جي مانگ، ۽ بجٽ لاءِ سبب کان وڌيڪ منافع بخش فصل هن موسم.",
  "home.matrix.t2f4Title": "کيec منافع / نقصان جو حساب",
  "home.matrix.t2f4Body": " متوقع ۽ حقيقي خرچا، output، آمدنی، ۽ منافع — بریک ایون ۽ ROI انڊز سان.",
  "home.matrix.t2f5Title": "سماجي فورم + ماہر رابطو",
  "home.matrix.t2f5Body": "سوال پوښتي، فوٹوز شير ڪريو، ٻين کيec وارن ۽ تصدیق شدہ زراعتي ماہرن جا جواب وٺو.",
  "home.matrix.tier3Name": "حیرت",
  "home.matrix.tier3Badge": "کhet کان اڳي",
  "home.matrix.t3f1Title": "سیٽلائٽ تبديلي جي نشانديهي",
  "home.matrix.t3f1Body": "سلاڊر سان سیٽلائٽ تصوiren جو وڌنڊ، نقصان، يا بدعناني ٽریک ڪرڻ لاءِ موازنو ڪريو.",
  "home.matrix.t3f2Title": "AI حشرات جي وهن جي پيش گوئي",
  "home.matrix.t3f2Body": "موسم، فصل جي مرحلو، ۽ تاريخ تي بنياد حشرات جي حملن کان اڳ اڳوڙهي خبرون.",
  "home.matrix.t3f3Title": "آواز پهرين فون ڪال موڊ",
  "home.matrix.t3f3Body": "مفت نمبر ڊائيل ڪريو، پوښتي بوليو، پڌرو ٻولي ۾ سنڌي — سمارٽ فون ضروري ناهي.",
  "home.matrix.t3f4Title": "کاربن ڪريڊ thus老人家",
  "home.matrix.t3f4Body": "پائيدار مشton ڊگ هليو ۽ اختياري بازارن مان کاربن ڪريڊ thus老人家 ڪريو.",
  "home.matrix.t3f5Title": "آفلاين پهرين PWA + SMS خبرون",
  "home.matrix.t3f5Body": "کhet ۾ آفلاين ڪم ڪري ٿو، رابطو اتي ۾ سنڪريو، بيانات نه هئڻ تي SMS ذريعي خبرون.",
  "home.vision.eyebrow": "دريسن",
  "home.vision.titleA": "پاکستان لاءِ بڻايل.",
  "home.vision.titleB": "سني تي تيار.",
  "home.vision.pkTitle": "پاکستان پهرين طريقو",
  "home.vision.pkBody": "پهريون ورجن پاکستان جي کheten لاءِ بنياد آهي: مقامي فصلن، علاقائي ٻولين، حقيقي زراعتي مشتون، ۽ حقيقي کhet جا حالت.",
  "home.vision.pkPoint1": "مقامي فصل ۽ موسم جو علم",
  "home.vision.pkPoint2": "Urdu، Punjabi، Pashto، Sindhi، Saraiki، Balochi، Hindko",
  "home.vision.pkPoint3": "هکيکي کيec وارن جي رائء سان بہتر",
  "home.vision.worldTitle": "عالمي توسيعي nego",
  "home.vision.worldBody": "بڻايل ۾ تبديلي لاءِ. جيئن پليٽ فارم بڻي وڃي ٿو، هن نئين ملکن، ٻولين، فصلن، ۽ موسمن تي وڌي آهي — اڳي مان شروع نه ڪندي.",
  "home.vision.worldPoint1": "mlak ڪڍي daycare زراعتي علم",
  "home.vision.worldPoint2": "وڌيڪ ٻولين ۽ مقامي فصلن",
  "home.vision.worldPoint3": "گہرائي بيانات انTEGRATION ۽ تجزيio",
  "home.users.title1": "انفرادي کيec وارا",
  "home.users.desc1": "ننھا ۽ درميانا درجاي کيec جن کي عملي رهنمايي ۽ هر سرگرمي جو منظم ریکارڊ گهر آهي.",
  "home.users.title2": " thương mại کيec",
  "home.users.desc2": "زراعتي کاروبار جن کي منظم معلومات، فیصلو جي مدد، ۽ ٽيم بلي جا ریکارڊ گهر آهن.",
  "home.users.title3": "eco system ڪا رفيق",
  "home.users.desc3": "وڌار وڌري، سهڪاريو، بیمہ وارا، ۽ ترقي خدمتون جيڪي ڪم سان پليٽ فارم ۾ شامل ٿي رهيا آهن.",
  "home.users.tagline": "کيec وارن لاءِ پهرين بڻايل — eco system سان ڌيڙي رهيو",
  "home.cta.eyebrow": "جلدي رسائي",
  "home.cta.title": "توھان جي کيec کي پليٽ فارم تي ڏنو",
  "home.cta.subtitle": "Agropioo سان بہتر فیصلن ڪندن کيec وارن سان جوڈيو — پاکستان مان شروع، سني بلي وڌي رهيو.",
  "home.cta.success": "توھان فہرست ۾ آھيو. جڏھن توھان جو علاقه کھلاسي ٿو اسان رابطو ڪندا.",
  "home.cta.emailLabel": "اي ميل پتو",
  "home.cta.fineprint": "سپيم ناهي. ڪبهي نه نال withdrawal ڪريو.",
  "home.footer.tagline": "AI طاقتور کيec انڊلنس پليٽ فارم. مشورا، سیٽلائٽ نگراني، بازار جا قيمتون، ۽ ریکارڊ — مٽي ۽ سگنال، ھڪ ڀيٽ.",
  "home.footer.pagesHeading": "صفحا",
  "home.footer.pagesNavLabel": "footer صفحا",
  "home.footer.legalHeading": "قانوني",
  "home.footer.legalNavLabel": "قانوني",
  "home.footer.privacy": "رازداري پاليسی",
  "home.footer.terms": "خدمت جي شرائط",
  "home.footer.cookies": "ڪوڪي پاليسی",
  "home.footer.disclaimer": "ڊسڪليمر",
  "home.footer.contactHeading": "رابطو ڪريو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} Agropioo. تمام حق محفوظ آهن.",
  "home.footer.motto": "پاکستان لاءِ بڻايل · سني تي تيار",
  "hiw.meta.title": "هن ڪيئن ڪم ڪري ٿو — Agropioo",
  "hiw.meta.description": "هڪ منٽ جي کيec پروفايل مان موسم جي چکري تي جيڪو بہتر ٿي رهيو آهي: ڏيڪو ڳڻا Agropioo سوالن، سرگرمين، ۽ ریکارڊن کي شخصي زراعتي رهنمايي ۾ بدلائي ٿو.",
  "hiw.hero.eyebrow": "هن ڪيئن ڪم ڪري ٿو",
  "hiw.hero.titleA": "ڏاڍا ڇوٽا قدم.",
  "hiw.hero.titleLead": "هڪ",
  "hiw.hero.titleAccent": "بہتر موسم.",
  "hiw.hero.subtitle": "Agropioo اُن ٽري طرح ڪم ڪري ٿو جئن زراعتي اڳي ڪم ڪري آهي — توھان وڃو، پڇھو، ڪم ڪريو، ۽ ریکارڊ ڪريو. واحد فرق هن آهي ته هر قدم اڳيون ۾ سکھائيندو آهي.",
  "hiw.hero.browseFeatures": "خصوصيتيون ڏيڪو",
  "hiw.route.navLabel": "Agropioo موسم جي چکري جا ڏاڍا ڇوٽا قدم",
  "hiw.route.stepLabel": "قدم {n}: {stop}",
  "hiw.route.stop1": "کيec شامل ڪريو",
  "hiw.route.stop2": "پڇھو",
  "hiw.route.stop3": "رهنمايي",
  "hiw.route.stop4": "ڪم ڪريو",
  "hiw.route.stop5": "ریکارڊ",
  "hiw.route.stop6": "بہتر مشورو",
  "hiw.setup.eyebrow": "هڪ ڀيٽ سيٽ اپ ڪريو",
  "hiw.setup.title": "توھان جي کيec هڪ زندو پروفايل بڻي وڃي",
  "hiw.setup.body": "ڏاڍا فيلڊ، منٽ ۾ — ضلع، فصل، اچاء جي تاريخ، ۽ زمين جي حد. هن بيٽ فارم آهي. هن کان پوءِ، هر جواب پ Detay جانن ٿو ته ڇو وڌي رهيو آهي ۽ ڇو وڌي رهيو آهي.",
  "hiw.setup.point1": "ڪبهي بدل ڪريو فصل يا فيلڊ شامل ڪريو",
  "hiw.setup.point2": "وڪري وارن ۽ ڊيلرن لاءِ ڳڻا کيec",
  "hiw.setup.point3": "ڪوبهٔ تکنیکي سوال نه — مٽي رپورٹ ضروري ناهي",
  "hiw.setup.mockHeading": "نئون کيec پروفايل",
  "hiw.setup.mockButton": "کيec پروفايل بنايو",
  "hiw.setup.mockFootnote": "منٽ کان ڪم",
  "hiw.setup.mockLabel": "ضلع، فصل، اچاء جي تاريخ، ۽ زمين جي حد سان بھريل کيec پروفايل فارم",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربي",
  "hiw.setup.rowSowing": "اچاء جي تاريخ",
  "hiw.setup.valSowing": "20 نومبر",
  "hiw.setup.rowLand": "زمين",
  "hiw.setup.valLand": "12 acre",
  "hiw.ask.eyebrow": "ڪجهه بھي پڇھو",
  "hiw.ask.titleA": "هڪ سوال انڌر.",
  "hiw.ask.titleB": "توھان جي سڄري کيec جواب ڏيندي.",
  "hiw.ask.body": "هڪ سوال مختلف کheten ۾ مختلف شڪل وٺي ٿو. تنهن لاءِ جواب ڏيڻ کان اڳ، Agropioo سوال کي توهان جي کيec جي سڄري معلومات سان چيکي آهي.",
  "hiw.ask.pipelineLabel": "کيec وارو سوال فصل، ضلع، موسم، ۽ تاريخ جي متن سان مل شخصي جواب بنايو آهي",
  "hiw.ask.question": "اب پاني ڏينdsa چاهيي يا ٿوري انتظار؟",
  "hiw.ask.checkedAgainst": "محملي",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · ٽلرlnq",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26°C · خشک هفتو",
  "hiw.ask.chipHistory": "تاريخ",
  "hiw.ask.chipValHistory": "Urea 9 ڏينهن اڳ",
  "hiw.ask.answer": "Do din rukein — barish ka chance hai, aur urea ke baad zameen abhi geeli hai. Jumma tak check karna kaafi hai.",
  "hiw.ask.answerMeta": "شخصي · گندم، Urea کان 9 ڏينهن",
  "hiw.ask.footnote": "ڏنو، بوليو، يا فون ڪال ڪريو — جواب شخصي رهندو آهي",
  "hiw.engine.eyebrow": "جواب پيچھي",
  "hiw.engine.title": "هڪ لائين کان اڳ ڏاڍا چيڪ",
  "hiw.engine.body": "رهنمايي تلاشو جو نتيجه ناهي. هن ڏاڍا دروازون کان ونڊي آهي تنهن لاءِ ته جيڪو توهان تي وڃي ٿو هن کhet، هن هفتو لاءِ محفوظ آهي.",
  "hiw.engine.check1Title": "جمع ڪريو",
  "hiw.engine.check1Desc": "کيec پروxFAEL، معاش جو موسم، ۽ فصل جو مرحلو اکي ۾ ڀريل آهن جڏھن توھان بھيجو ٿو.",
  "hiw.engine.check2Title": "محملي",
  "hiw.engine.check2Desc": "مشورو پيش گوئي سان چيکيو وڃي ٿو — اسپري جيڪو بارش ضايع ڪري ڇوتي آهي ڪبھي انجمن کان نه وڃي ٿو.",
  "hiw.engine.check3Title": "شخصي ڪريو",
  "hiw.engine.check3Desc": "توھان جي کhet تاريخ جواب کي موڙي ٿو — هڪ فصل، مختلف مٽي، مختلف مشورو.",
  "hiw.engine.check4Title": "پهچائيو",
  "hiw.engine.check4Desc": "هن توھان جي ٻولي ۾ صاف قدم طرح وڃي ٿو — سکريён تي، آواز ذريعي، يا فون ڪال ذريعي.",
  "hiw.engine.safetyStrong": "جو کوڇو ڪوبي غير محفوظ لڳي،",
  "hiw.engine.safetyRest": "Agropioo وDataExchange ڪري ٿو — ڏندل جواب وڌار وڌار اسپري يا خراب ٿيل فصل کان بہتر آهي.",
  "hiw.record.recorderHeading": "سرگرمي لاگ ڪريو",
  "hiw.record.syncBadge": "آٹو سنڪ فعال",
  "hiw.record.actionIrrigation": "آبپاشي",
  "hiw.record.actionFertiliser": "کوDate",
  "hiw.record.actionPesticide": "زهي کيمریکل",
  "hiw.record.actionDisease": "بيماري",
  "hiw.record.actionExpense": "خرچا",
  "hiw.record.actionHarvest": "ڏينهن",
  "hiw.record.row1Time": "اڄ · صبح 6:40",
  "hiw.record.row1Label": "آبپاشي لاگ",
  "hiw.record.row1Detail": "نہر گھو · 40 منٽ · پلاٽ B",
  "hiw.record.row2Time": "ڪالهه",
  "hiw.record.row2Label": "کوDate لاگ",
  "hiw.record.row2Detail": "DAP 20 kg / acre",
  "hiw.record.offlineNote": "→ ڇوٽو ٽيپ فِلڊ — آفلاين بھي چلي ٿو",
  "hiw.record.mockLabel": "سرگرمي ریڪارڊر ڳڙڙي سرگرمي چپن ۽ بلي ٽائپ واري قطارن سان",
  "hiw.record.eyebrow": "जतू ریکارڊ ڪريو",
  "hiw.record.titleA": "هاڻو ڇوٽا ٽيپ،",
  "hiw.record.titleB": "سڄري موسم بہتر جواب",
  "hiw.record.body": "ریکارڊنگ کhet لاءِ بنياد آهي — ڍاڍا بٽن، ڳڹھا فيلڊ، ټائپنگ ضروري ناهي. هر فيلڊ کيec جي يادداشت جو حصو بڻي وڃي ٿو، تنهن لاءِ ته مشورا ببهتر ٿي رهيو آهي جڏھن فصل وڌي رهيو آهي.",
  "hiw.record.point1": "آبپاشي، وڌار، بيماري، خرچا، ڏينهن — هڪ ٽائم لائين",
  "hiw.record.point2": "سڄري آفلاين ڪم ڪري ٿو؛ سن ko چلا وڃي ٿو جڏھن سنگل واپس آهي",
  "hiw.record.point3": "موسم جا خلاصا بانکن، وڌري، يا بيمې 对于 لاءِ تيار",
  "hiw.loop.eyebrow": "موسم جي چکري",
  "hiw.loop.titleA": "هن ڏينهن تي ختم نه ٿي.",
  "hiw.loop.titleB": "هن هتي شروع ٿي آهي.",
  "hiw.loop.body": "پڇھو، ڪم ڪريو، ریکارڊ ڪريو — هر بار چکري جي موڙ توهان جي زمين جي معلومات کي وڌائي ٿو، تنهن لاءِ ته پکيون موسم اڳون کان بہتر شروع ٿي ٿو.",
  "hiw.loop.benefit1Title": "مشورا وڌي وڃي ٿو",
  "hiw.loop.benefit1Desc": "پکيئن موسم جي بيماري، مقدارين، ۽ تاريخ هن موسم جو پهرين جواب بنايو.",
  "hiw.loop.benefit2Title": "ڪجهه نه دوباره ٿي وڃي",
  "hiw.loop.benefit2Desc": "مشاور جانندو آهي ته ڇو اڳي اسپري ڪيل آهي يا ڏن — ڊبل ڊوز نه.",
  "hiw.loop.benefit3Title": "هر موسم دستاويز",
  "hiw.loop.benefit3Desc": "صاف تاريخ قرضن، وڌري، بيمې 对于، يا پکيئن فصل جي فیصلو لاءِ تيار رهندو آهي.",
  "hiw.loop.stepLearn": "سيکهو",
  "hiw.loop.stepImprove": "بہتر ڪريو",
  "hiw.loop.diagramLabel": "دائرə چکري ڊائگرام: پڇھو، ڪم ڪريو، ریکارڊ ڪريو، سيکهو، بہتر ڪريو",
  "hiw.loop.centerSeason": "موسم",
  "hiw.loop.centerLoop": "چکري",
  "hiw.loop.caption": "هر موسم، اڳون کان بہتر",
  "feat.meta.title": "خصوصيتيون — Agropioo",
  "feat.meta.description": "هر Agropioo قابلية ڏيڪو: AI فصل ڊاڪٽر، سیٽلائٽ NDVI نگراني، منڊي قيمت جي پيش گوئي، مقامي ٻولين ۾ آواز مشورا، SMS خبرون سان آفلاين رسائي، ۽ ٻين.",
  "feat.hero.eyebrow": "خصوصيتيون",
  "feat.hero.titleLead": "سڀ کچھ جيڪو توھان جي",
  "feat.hero.titleAccent": "موسم گهر آهي",
  "feat.hero.subtitle": "ڏاڍا قابلين هڪ طرح ڪم ڪندا آهن — پتي اسڪين ڪندا آهن، آسمان مان کhet نگراني ڪندا آهن، منڊي پڇھندا آهن، ۽ توھان جي ٻولي ۾ بولندا آهن. ڏيڪو هر قابلية توھان جي کيec لاءِ ڇو ڪري ٿو.",
  "feat.hero.ctaPrimary": "جلدي رسائي حاصل ڪريو",
  "feat.hero.ctaSecondary": "ڏيڪو ڇو هن ڪم ڪري ٿو",
  "feat.hero.builtFor": "پاکستان لاءِ بڻايل",
  "feat.hero.productOf": "Aplinode جو پيداوار",
  "feat.hero.tile1Label": "پتي جي اسڪين",
  "feat.hero.tile1Value": "94% ٺيڪ",
  "feat.hero.tile2Label": "منڊي گندم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کhet",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "حشرات جي خطرن",
  "feat.hero.tile4Value": "ڪم · 7ڏينهن",
  "feat.hero.voiceReady": "آواز مشورو تيار",
  "feat.hero.voiceLangs": "Urdu · پنجابی · Saraiki",
  "feat.hero.liveBadge": "ライブ",
  "feat.hero.smsLabel": "SMS خبرو · آفلاين موڊ",
  "feat.hero.smsMsg": "بارش شام 3 بجے — اسپري بند ڪريو",
  "feat.intel.eyebrow": "فصل جي انڊلنس",
  "feat.intel.heading": "خرچو ڪرڻ کان اڳ مسئلن ڏيڪو",
  "feat.intel.sub": "بيماري، حشرات، موسم، ۽ فصل جي چونڊ — ڏاڍا فیصلن جن ۾ ڏينهن جي قسمت م decides، هر هڪ جي پيچھي هڪ انجمن آهي.",
  "feat.intel.included": "شامل",
  "feat.intel.doctorCode": "F·01 · Vision",
  "feat.intel.doctorTitle": "AI فصل ڊاڪٽر",
  "feat.intel.doctorDesc": "متاثر پتي جو فوٹو ڪڍيو ۽ ثانیون ۾ بيماري جو نالو، شدت، ۽ علاج جا تجويز وٺو.",
  "feat.intel.doctorMock": "پتي جي اسڪين جو نتيجه ڄاڻايلآهي ته زرد رنگ جي زنگ معلوم آهي ۽ وڌيڪ يقين سان",
  "feat.intel.diseaseName": "زرد رنگ جي زنگ",
  "feat.intel.matchScore": "94% ملتا",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درميانو",
  "feat.intel.pestCode": "F·02 · Forecast",
  "feat.intel.pestTitle": "حشرات جي وهن جا خبرون",
  "feat.intel.pestDesc": "موسم ۽ فصل جو مرحلو خطرن جو ماڊل ڀري ٿو جيڪو ڏينهن کان اڳ خبر وڌائي ٿو جڏھن حالتون حملن جي initialised دين.",
  "feat.intel.pestMock": "سات ڏينهن جا حشرات خطرن جا پٽي ڇوٽي ۾ اڇي وڌي رهيا آهن",
  "feat.intel.pestAlert": "ڇنچر · پؾشا خطرن 74% — ننھي گندم ڏيپو",
  "feat.intel.weatherCode": "F·03 · Weather",
  "feat.intel.weatherTitle": "موسم واري مشورن",
  "feat.intel.weatherDesc": "هائيپرلوڪل پيش گوئي توھان جي فصل ۽ وڌنڊ جي مرحلو تي مل ٿي آهن — مشورو صاف هدايت طرح وڃي ٿو، خام بيانات نه.",
  "feat.intel.weatherMock": "نمونو موسم مشورو جيڪو بارش کان اڳ آبپاشي ڏندل لاءِ وڌائي آهي",
  "feat.intel.delayIrrigation": "اڄ آبپاشي ڏندل",
  "feat.intel.rainNote": "شام 3 بجے بارش متوقع آهي — آسمان کي توھان جي کhet پاني پهچائڻ ڏيرو.",
  "feat.intel.waterSaved": "پاني بچايو",
  "feat.intel.cropCode": "F·04 · Planning",
  "feat.intel.cropTitle": "فصل جي تجويز",
  "feat.intel.cropDesc": "مٽي، موسم، مانگ، ۽ توھان جو بجٽ هڪ밪 جي مل ۾ چڱيو وڃي ٿو — هن موسم ڳنڍڻ لاءِ وڌيڪ منافع بخش فصل.",
  "feat.intel.cropMock": "ترتيب واري فصل جا تجويز ڳندم پهرين تي",
  "feat.intel.crop1": "گندم",
  "feat.intel.crop2": "رائي",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کhet ۽ بازار جي انڊلنس",
  "feat.field.headingA": "توھان جي زمين آسمان مان ماپيل.",
  "feat.field.headingB": "توھان جي فصل بيانات جي مل تي قيمت آهي.",
  "feat.field.sub": "سیٽلائٽ هر acre تي ۽ هر قرباني منڊي تي نگراني — تنهن لاءِ ته وڌنڊ ۽ وڌري سلي لمحو ۾ ٿيندا.",
  "feat.field.ndviCode": "F·05 · Satellite",
  "feat.field.ndviTitle": "NDVI کhet نگراني",
  "feat.field.ndviDesc": "هڪ ڀيٽ توھان جي حدون علامت ڪريو؛ صحت جا زون هر صاف سیٽلائٽ کان وڌندا آهن — ڪمزور ڌارا آنکھ چيڏوڳي اڳي وڌي آهن.",
  "feat.field.ndviMock": "کhet جي صحت ڳريڊ جتي ڳاڙهو رنگ ڳڍي فصل جي وڌنڊ ظاهر ڪري ٿو",
  "feat.field.weakZone": "ڪمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · Market",
  "feat.field.priceTitle": "منڊي قيمت جي پيش گوئي",
  "feat.field.priceDesc": "قرباني بازارن مان لائوا قيمتون ۽ رجحان جي پيش گوئي — جڏھنurve ڪهي ٿو اني وڌي، وڌري وڌري، وڌري وڌري.",
  "feat.field.priceMock": "گندم جي قيمت جي رجحان آٹ هفتن مان وڌي رهيو آهي ۽ ڏندل جي تجووز آهي",
  "feat.field.wheatTrend": "گندم · 8 هفتن",
  "feat.field.holdStock": "↑ 12% — اسٽاڪ ڏندل",
  "feat.field.financeCode": "F·07 · Finance",
  "feat.field.financeTitle": "منافع ۽ نقصان ٽریڪر",
  "feat.field.financeDesc": "هر روپيو انڌر ۽ باہر، سڄري موسم — بریک ایون ۽ ROI تيures کان اڳ جڏھن توھان منڊي يا بانک تي وڃي ٿو.",
  "feat.field.ledgerMock": "موسم خرچا ليڊر جن جي inputs labour آبپاشي ۽ آمدنی آهن",
  "feat.field.rowInputs": "وڌار",
  "feat.field.rowLabour": "مشقت",
  "feat.field.rowIrrigation": "آبپاشي",
  "feat.field.rowRevenue": "آمدنی (متوقع)",
  "feat.field.netMargin": "خالص منافع",
  "feat.voice.eyebrow": "سڀکي لاءِ رسائي",
  "feat.voice.headingA": "سمارٽ فون نه آهي؟",
  "feat.voice.headingB": "انگريزي نه آهي؟ ته بھي شامل.",
  "feat.voice.sub": "بهترين مشورو بے ضرورت آهي جو ڪبهي کيec واري تي نه وڃي. هر قابلية فون ڪال جواب ڏيندي آهي، آواز سندي آهي، ۽ مري ڏيش ۾ ڄدري آهي.",
  "feat.voice.speakCode": "F·08 · Voice",
  "feat.voice.speakTitle": "توھان جي سوال بوليو",
  "feat.voice.speakMock": "مشاور سان Roman Urdu ۾ آواز ڳلیا",
  "feat.voice.chatUser": "منھن جي پتيون تي دھببا آھن",
  "feat.voice.chatAdvisor": "Dhabbon ki photo bhejein — main abhi tashkhees karta hoon.",
  "feat.voice.inputPlaceholder": "بول ڪري پڇھو…",
  "feat.voice.callCode": "F·09 · Call",
  "feat.voice.callTitle": "مفت نمبر ڊائيل ڪريو",
  "feat.voice.callMock": "Agropioo آواز معاون سان مفت ڪال ٽرانسڪريپٽ",
  "feat.voice.greetingLine": "Agropioo ۾ توھان جوoard آهي",
  "feat.voice.heardLine": "Awaaz samajh li — jawab tayar hai",
  "feat.voice.callEnded": "ڪال ختم · خلاصا محفوظ",
  "feat.voice.anyPhone": "هر فون تي ڪم ڪري ٿو · انٽرنيٽ نه",
  "feat.voice.offlineCode": "F·10 · Offline + SMS",
  "feat.voice.offlineTitle": "مري ڏيش ٿاندي نه وڌندي",
  "feat.voice.offlineDesc": "مشورا، ریکارڊ، ۽ حساب جا ڪالون سنگل بنا آفلاين ڪم ڪندا آهن؛ رابطو وٺي وڃي تي سڀ سنڪريو وڃي ٿو، ۽ اهم خبرون SMS ذريعي وڃندا آهن.",
  "feat.voice.networkStatus": "نيٽ ورڪ حالت",
  "feat.voice.offlineQueued": "آفلاين · 3 ریکارڊ قطار",
  "feat.voice.smsStamp": "SMS · 07:42",
  "feat.voice.smsMsg": "موسم خبرون: بارش شام 3 بجے — اسپري جو وقت بدلائيو.",
  "feat.manage.eyebrow": " management ۽ وڌو",
  "feat.manage.headingA": "مشورو شروع آهي.",
  "feat.manage.headingB": "باقي ریکارڊ سان چلي ٿو.",
  "feat.manage.sub": "تاريخ، سبسبڈي، پائيداريتا، ۽ کيec وارن جو سماج — خاموش خصوصيتيون جن جي هر موسم بہتر ٿي وڃي.",
  "feat.manage.diaryCode": "F·11 · Records",
  "feat.manage.diaryTitle": "ڊجٽل کيec ڊائري",
  "feat.manage.diaryDesc": "آبپاشي کان ڏينهن تي، سبڪچھ هڪ ٽائم لائين تي آهي جن جي مشاور جواب ڏيڻ کان اڳ پڇھي ٿو.",
  "feat.manage.timelineMock": "اگسٽ لاءِ کيec سرگرمي ٽائم لائين",
  "feat.manage.tl1Date": "12 اگسٽ",
  "feat.manage.tl1Label": "آبپاشي",
  "feat.manage.tl1Detail": "نہر گھو · 40 منٽ",
  "feat.manage.tl2Date": "09 اگسٽ",
  "feat.manage.tl2Label": "Urea لاگ",
  "feat.manage.tl2Detail": "25 kg / acre",
  "feat.manage.tl3Date": "02 اگسٽ",
  "feat.manage.tl3Label": "پتي جي اسڪين",
  "feat.manage.tl3Detail": "صاف · بيماري نه",
  "feat.manage.schemeCode": "F·12 · Schemes",
  "feat.manage.schemeTitle": "سبسبڈي ۽ اسکيم جو لڳندڙ",
  "feat.manage.schemeDesc": "حکومتي مال جن ۾ توھان اڳي حق رکندو آهي — ملائيل، سمجھايل، ۽ هڪ ٽيپ جي درخواست لاءِ لنڪ ڪيل.",
  "feat.manage.checklistMock": "اِنڊ looping جو چيڪ لسٽ چار ۾ ۽ري مולים پورا",
  "feat.manage.check1": "زمين جي مالکيت تصدیق",
  "feat.manage.check2": "فصل جا موسم ملتا",
  "feat.manage.check3": "CNIC رجسٽر",
  "feat.manage.check4": "بینک اکائونٽ لنڪ",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تيار",
  "feat.manage.carbonCode": "F·13 · Sustainability",
  "feat.manage.carbonTitle": "سبز مشتون جي بونس",
  "feat.manage.carbonDesc": "آرگانڪ ۽ ڪم زرع مشتون ڊگ هليو؛ سیٽلائٽ سبز ڍپن تصدیق ڪندا آهن ۽ کاربن ڪريڊ thus老人家 محاسبو وڃي ٿو.",
  "feat.manage.carbonMock": "کاربن خلاصا ٽن ڪيپچر ۽ متوقع سالي قيمت",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "ڪريڊ thus老人家 / سال",
  "feat.manage.forumCode": "F·14 · Community",
  "feat.manage.forumTitle": "کيec وارن جو فورم + ماہر",
  "feat.manage.forumDesc": "مسئلو پوښتي، جواب وٺو ٻين کيec وارن مان جن سان آيو — تصدیق شدہ زراعتي ماہر ٺيڪ حل علامت ڪندا آهن.",
  "feat.manage.threadMock": "سماجي ٿريڊ تصدیق شدہ جواب سان",
  "feat.manage.threadQuestion": "کپاس ۾ اڇو سگھو جو بہترين علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 upvotes",
  "feat.manage.expertBadge": "ماہر جي تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "Neem oil spray, shaam ko — do baar, 5 din ke gap par.",
  "vp.meta.title": "nego — Agropioo",
  "vp.meta.description": "Agropioo nego: هر کيec وارو جي جيب ۾ ذہين زراعتي رهنمايي — پاکستان مان شروع، پنج យقينن، ڏاڍا horizonن، ۽  promised جن ۾ ڪبهي نه موڙيندا آهن.",
  "vp.hero.eyebrow": "اسان جو nego",
  "vp.hero.titleLead": "هڪ بھروسمند مشاور هر",
  "vp.hero.titleAccent": "کيec وارو جي جيب ۾.",
  "vp.hero.sub": "ذہين رهنمايي ٿڌي، تعلیم، يا ٻولي تي منحصر نه هئڻي. Agropioo موڙو آهي ته هر کيec وارو — هر فون تي، هر ڳوٺ ۾ — هڪ ماہر طرح هي Confidence سان زراعت ڪري.",
  "vp.hero.tagStart": "جتي ضرورت ڌيڙي آهي شروع ڪريو",
  "vp.hero.tagThen": "پوءِ دنيا وڌائيو",
  "vp.hero.ctaLink": "ڏيڪو اسان کيڏي بنايل",
  "vp.beliefs.eyebrow": "اسان کي ڇو يقين آهي",
  "vp.beliefs.heading": "پنج یقین هر فيصلو ۾ شکل وٺندا آهن",
  "vp.beliefs.b1Title": "وڌنڊ",
  "vp.beliefs.b1Desc": "زندو فصلن، صحت مند زمين، ۽ خوشحال کيec وارا.",
  "vp.beliefs.b2Title": "انڊلنس",
  "vp.beliefs.b2Desc": "AI مقامي موسم، تاريخ، ۽ فصل جي سائنس تي بنياد.",
  "vp.beliefs.b3Title": "رسائي",
  "vp.beliefs.b3Desc": "کيec وارو جي ٻولي ۽ متن ۾ رهنمايي.",
  "vp.beliefs.b4Title": "भरوسو",
  "vp.beliefs.b4Desc": "عملي، وقتي مشورو جن جي روزي بچائيندا آهن.",
  "vp.beliefs.b5Title": "مستقبل",
  "vp.beliefs.b5Desc": "پائيدار ٹیکنالوجي جن جي روائتون جي عزت ڪري ٿو.",
  "vp.horizons.eyebrow": "آگهه جي راه",
  "vp.horizons.heading": "ڏاڍا horizon، هڪ سمت",
  "vp.horizons.h1Tag": "Horizon 01",
  "vp.horizons.h1Phase": "هاڻو",
  "vp.horizons.h1Status": "کheten ۾",
  "vp.horizons.h1Body": "پاکستان پهرين. بنيادي مشاور، ڊجٽل کيec ریکارڊ، موسم واري رهنمايي، ۽ ڏاڍا علاقائي ٻولين — هکيکي کيec وارن جي رائء سان بہتر ڪيل.",
  "vp.horizons.h1P1": "بنيادي مشاور + ریکارڊ",
  "vp.horizons.h1P2": "ڏاڍا ٻولين",
  "vp.horizons.h1P3": "هکيکي کيec وارن جي بہتر",
  "vp.horizons.h2Tag": "Horizon 02",
  "vp.horizons.h2Phase": "اڳيون",
  "vp.horizons.h2Status": "توسيع",
  "vp.horizons.h2Body": "گھر ۾ گہرائي ۽ ڳنڍي — پاکستان بلي فصلن ۽ علاقن، زراعتي بيانات جنگن سان ڳڍي انTEGRATION، ۽ تجزيio جن جي هر تجويز بہتر شخصي بنايو.",
  "vp.horizons.h2P1": "وڌيڪ فصلن ۽ علاقن",
  "vp.horizons.h2P2": "بيانات انTEGRATION",
  "vp.horizons.h2P3": "پيشرفته تجزيio",
  "vp.horizons.h3Tag": "Horizon 03",
  "vp.horizons.h3Phase": "بعد",
  "vp.horizons.h3Status": "عالمي",
  "vp.horizons.h3Body": "پليٽ فارم نئين ملکن، موسمن، فصلن، ٻولين، ۽ مشتون تي ڪري ٿو — اڳي مان شروع نه ڪندي هڪ عالمي قابل زراعتي انڊلنس.",
  "vp.horizons.h3P1": "نئنا ملک",
  "vp.horizons.h3P2": "نئنا ٻولين ۽ موسم",
  "vp.horizons.h3P3": "عالمي پليٽ فارم",
  "vp.outcomes.eyebrow": "کاميابي ڪيئن لڳي",
  "vp.outcomes.heading": "ڏاڍا نتيجا جن لاءِ اسان خود کي ڊڄلي آهيون",
  "vp.outcomes.sub": "nego app نه آهي — هن جيڪو کيec تي بدلائي آهي. سبڪچھ هن ڏاڍا نتيجن تي بنايل آهي.",
  "vp.outcomes.o1Title": "بہتر فيصلن",
  "vp.outcomes.o1Desc": "هر چونڊ — پاني، وڌار، وقت — عادت جي بجاي بيانات تي بنياد.",
  "vp.outcomes.o2Title": "وڌيڪ output",
  "vp.outcomes.o2Desc": "صحت مند فصلن، وقتي وڌار، ۽ سلي وقتي ڏينهن.",
  "vp.outcomes.o3Title": "گھٽلي خسارا",
  "vp.outcomes.o3Desc": "بيماري، حشرات، ۽ موسم ڳڍن کان اڳ — output نه وٺي.",
  "vp.outcomes.o4Title": "کيec کاروبار طرح چلي",
  "vp.outcomes.o4Desc": "منظم ریکارڊ ۽ موسم جي انڊلنس جن کي بانک ۽ وڌري عزت ڪندا آهن.",
  "vp.principles.eyebrow": " غير قابل مذاکرة",
  "vp.principles.heading": " promises جن تي اسان بنايو آهيون",
  "vp.principles.sub": "nego تفصيلن ۾ ختم ٿي ٿو. هن commitments هر خصوصيتي، هر صفحي، هر release تي لاڳو آهن — اڄ مان شروع.",
  "vp.principles.c1Title": "کيec وارو جي فائدو پهرين",
  "vp.principles.c1Desc": "هر خصوصيت کhet جي ضرورت مان شروع ٿي ٿو — ڪبهي ٹیکنالوجي مان نه.",
  "vp.principles.c2Title": "ٻولي پهرين",
  "vp.principles.c2Desc": "هر سکريён ۽ هر جواب کيec وارو جي ٻولي ۾ وڃي ٿو.",
  "vp.principles.c3Title": "دھوپ ۾ پڙھڻي",
  "vp.principles.c3Desc": " mükem ymin ۾ بلند contrast ڊزائن — صرف دفتر لاءِ نه.",
  "vp.principles.c4Title": "سادي لفظ",
  "vp.principles.c4Desc": "ايترا آسان ته هڪ پاسين ٻين کي سمجھا سکي.",
  "vp.principles.c5Title": "فونون سڀ کان اڳ",
  "vp.principles.c5Desc": "موبائل پهرين، ڍاڍا ٽيپ ٽارگيٹس — زراعتي اڃا فونون تي آهي.",
  "vp.principles.c6Title": "قھري طرح بڻايل",
  "vp.principles.c6Desc": "حرڪت ۽ لے آؤٹ جن ۾ قحري لڳندا آهن — وڌنڊ، ڪبھي مشينن نه.",
  "vp.principles.motto": "مٽي ۽ سگنال — ھڪ ڀيٽ ڌيڙي رهيو",

  // --- Why Agropioo page (wy.*) ---
  "wy.meta.title": "ڇو Agropioo — AI طاقتور کيec انڊلنس",
  "wy.meta.description": "کيec جا فيصلن ڳانٽھ لاءِ ايترا اهم آهن. ڏيڪو ڇو Agropioo AI مشاور، کيec ریکارڊ، موسم واري رهنمايي، ۽ مقامي ٻولين هڪ پاکستان پهرين پليٽ فارم تي ڀيٽي آهي.",
  "wy.hero.eyebrow": "ڇو Agropioo",
  "wy.hero.titleLead": "جتي مٽي ۾ ملندو آهي",
  "wy.hero.titleAccent": "سگنال",
  "wy.hero.sub": "کيec جا فيصلن ڳانٽھ لاءِ ايترا اهم آهن. Agropioo AI مشاور، توھان جي کيec جا ریکارڊ، موسم واري رهنمايي، ۽ توھان جي ٻولي هڪ پليٽ فارم تي ڏيڏي آهي — تنهن لاءِ ته هر چونڊ توھان جي زمين جي حقيقت تي بنياد.",
  "wy.hero.ctaPrimary": "جلدي رسائي حاصل ڪريو",
  "wy.hero.ctaSecondary": "پليٽ فارم ڏيڪو",
  "wy.hero.tagStart": "پاکستان لاءِ بڻايل",
  "wy.hero.tagThen": "Aplinode جو پيداوار",
  "wy.hero.svgLabel": "کhet ۾ ڳومڙل واري فھري",
  "wy.origin.eyebrow": "اسان کيڏي هن جي بنايل",
  "wy.origin.heading": "اونچي استرس جا فيصلن ڳانٽھ تي نه هئڻي",
  "wy.origin.sub": "Agropioo هڪ سادي مشاکدي سان شروع ٿيو: کيec وارو جو موسم ڳڙھا فيصلن جي قسمت ۽ هر فيصلي لاءِ حقيقي انڊلنس ضروري آهي.",
  "wy.origin.g1Title": "وقت ڳانٽھ آهي",
  "wy.origin.g1Desc": "آبپاشي، کوDate، اچاء، ڏينهن — موسم جا فيصلن اڃا عادت ۽ اميد سان ٿيندا آهن.",
  "wy.origin.g2Title": "تاريخ ختم ٿي وڃي ٿو",
  "wy.origin.g2Desc": "ڇو اسپري ڪيل، ڇو کhet تي پاني ڏنو، گزري سال ڪهڙي بيماري آئي — ڪجهه نه ليکيل، تنهن لاءِ ته ڪجهه نه سيکهيو سگهيو.",
  "wy.origin.g3Title": "مشورو بکرري آهي",
  "wy.origin.g3Desc": "پاسين، دوکاندار، ۽ وڊييون هر هڪ جواب ڏيندە آهن — پر ڪوبهٔ ذريعي توھان جي فصل، مٽي، يا هن هفتو جا آسمان نه پڇھي ٿو.",
  "wy.origin.banner": "ڳانٽھ جي قيمت ڏينهن تي ادا ٿي آهي",
  "wy.diff.eyebrow": "ڇو ھن جو فرق آهي",
  "wy.diff.heading1": "هڪ ٻيو مشورو app نه.",
  "wy.diff.heading2": "هڪ کيec انڊلنس پليٽ فارم.",
  "wy.diff.sub": "گھنوري ڪالون جواب ڏيندا آهن. Agropioo توھان جي کيec سیکهي ٿو — ۽ هر سرگرمي سان بہتر ٿي وڃي ٿو.",
  "wy.diff.personalTitle": "شخصي، عام نه",
  "wy.diff.personalDesc": "تجوORIZATIONS توھان جي فصل، مقام، عاشق موسم، ۽ کيec تاريخ تي بنياد آهن — ڪبهي عام مشوري نه.",
  "wy.diff.chip1": "توھان جي فصل",
  "wy.diff.chip2": "توھان جو ضلع",
  "wy.diff.chip3": "هن هفتو جو موسم",
  "wy.diff.chip4": "توھان جو گزريو موسم",
  "wy.diff.langTitle": "توھان جي ٻولي ۾ بولي ٿو",
  "wy.diff.langDesc": "جئن توھان واقعي بولندا آھيو پڇھو ۽ سمجھو — ڪوبهٔ تکنیکي انگريزي ضروري ناهي.",
  "wy.diff.memoryTitle": "هر کيec لاءِ يادداشت",
  "wy.diff.memoryDesc": "آبپاشي، وڌار، بيماري، خرچا، ڏينهن — هر سرگرمي منظم ریکارڊ طرح رکيل، تنهن لاءِ ته هر موسم اڳون کان بہتر شروع ٿي ٿو.",
  "wy.diff.weatherTitle": "موسم واري بنيادي",
  "wy.diff.weatherDesc": "رهنمايي حقيقي حالتون چيڏوڳي ڏيندورو تي وڃي ٿو — تنهن لاءِ ته اسپري بارش ضايع ڪرڻ کان ڪجهه ڳنٽ پهceso نه ٿي وڃي.",
  "wy.diff.platformTitle": "هڪ پليٽ فارم، سڄري موسم",
  "wy.diff.platformDesc": "مشاور، ریکارڊ، موسم جي رهنمايي، ۽ مشورا ھڪ ڀيٽ ڪم ڪندا آهن بلڪه الگ apps ۽ نوٽ بڪن ۾ نه رهندە.",
  "wy.diff.pakTitle": "پاکستان پهرين",
  "wy.diff.pakDesc": "مقامي فصلن، علاقائي مشتون، ۽ حقيقي کhet جا حالت پهرين ڊن سان ڊزائن آهن — بعد ۾ موڙي وڃن نه.",
  "wy.diff.pakBadge": "اهيتي پهرين بڻايل",
  "wy.life.eyebrow": "مشاور ڇو شامل آهي",
  "wy.life.heading": "چکري ۾ هر فيصلي لاءِ رهنمايي",
  "wy.life.sub": "هڪ مشاور سڄري فصل جي lifecycle سان توهان سان وڃي ٿو — موسم جي منصوبنديزي مان ڏينهن گھر وٺڻ تي.",
  "wy.life.s1Title": "آبپاشي جو وقت",
  "wy.life.s1Desc": "جانڊو ڇو پاني ڏنو — ۽ ڇو انتظار ڪرڻ.",
  "wy.life.s2Title": "فصل جي منصوبنديزي",
  "wy.life.s2Desc": "توھان جي زمين لاءِ مناسب فصلن ۽ اچاء جا وقت چونڊيو.",
  "wy.life.s3Title": "کوDate ۽ زهي کيمریکل جي رهنمايي",
  "wy.life.s3Desc": "سلي وڌار، سلي مقدار، سلي لمحو.",
  "wy.life.s4Title": "حشرات ۽ بيماري جي مدد",
  "wy.life.s4Desc": "ڳڍي مان اڳ مسئلن ڏيڪو ۽ ڪم ڪريو.",
  "wy.life.s5Title": "ڏينهن جو وقت",
  "wy.life.s5Desc": "output ۽ معیار بچائڻ وقتي ڏينهن.",
  "wy.life.s6Title": "موسم واري تجويز",
  "wy.life.s6Desc": "هر مشورو پهرين اڄ جي حالتون پڇھي ٿو.",
  "wy.life.s7Title": "روزانे سوال",
  "wy.life.s7Desc": "توھان جي فصل بارattery پوښتي، موسم جي هر ڏينهن.",
  "wy.value.eyebrow": "وڌي",
  "wy.value.heading1": "ڇو ڪريو. ڪڻهن ڪريو.",
  "wy.value.heading2": "۽ ڇو ڪيل آهي.",
  "wy.value.sub": "Agropioo جي هر خصوصيت هن ڏاڍا جوابن مان هڪ تي خدمت ڪري ٿو — هن طرح فيصلن جو موسم اعتماد جو موسم بڻي وڃي ٿو.",
  "wy.value.p1Heading": "ڇو ڪريو",
  "wy.value.p1Desc": "توھان جي فصل ۽ حالت لاءِ صاف، مключения تجويز — عام مشوري نه.",
  "wy.value.p2Heading": "ڪڻهن ڪريو",
  "wy.value.p2Desc": "وقت حقيقي موسم ۽ وڌنڊ جي مرحلو تي بنياد، تنهن لاءِ ته سلي سرگرمي سلي لمحو تي وڃي.",
  "wy.value.p3Heading": "ڇو ڪيل آهي",
  "wy.value.p3Desc": "هر سرگرمي جي منظم تاريخ — هميشه قريبي، هميشه بہتر مشوروڏيڏي.",
  "wy.who.eyebrow": "ڇو لاءِ خدمت ڪري ٿو",
  "wy.who.heading": "کيec واري کان ڳنڍي",
  "wy.who.a1Title": "انفرادي کيec وارا",
  "wy.who.a1Desc": "عملي، شخصي مدد هر فيصلو سان — ساتھ ۾ تجربibo放过 ڪيل هر ڪم جو منظم ریکارڊ.",
  "wy.who.a2Title": "tcharmar کيec ۽ زراعتي کاروبار",
  "wy.who.a2Desc": "منظم کيec معلومات ۽ ڍوکي فيصلن جي مدد ٽيمن، کheten، ۽ موسمن ۾.",
  "wy.who.a3Title": "eco system ڪا رفيق",
  "wy.who.a3Desc": "وڌار وڌري، سهڪاريو، بیمہ وارا، ۽ ترقي خدمتون جيڪي ڪم سان پليٽ فارم ۾ شامل ٿي رهيا آهن.",
  "wy.who.strip": "کيec جي پيچھي سماج سان ڌيڙي رهيو",

  "auth.backHome": "گھر تي واپس",
  "auth.emailLabel": "اي ميل پتو",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاسورڊ",
  "auth.showPassword": "پاسورڊ ڏيڪو",
  "auth.hidePassword": "پاسورڊ ڏن_DF",
  "auth.err.emailRequired": "توھان جو اي ميل پتو داخل ڪريو.",
  "auth.err.emailInvalid": "سلي اي ميل پتو داخل ڪريو.",
  "auth.err.passwordRequired": "پاسورڊ چونڊيو.",
  "auth.err.passwordMin": "گھنوري 8 حروف استعمال ڪريو.",
  "auth.err.passwordMax": "وڌيڪ 64 حروف استعمال ڪريو.",
  "auth.err.nameRequired": "توھان جي ڏيڏي نالو داخل ڪريو.",
  "auth.err.phoneInvalid": "سلي فون نمبر داخل ڪريو.",
  "auth.err.confirmRequired": "پاسورڊ دوباره ڏنو.",
  "auth.err.termsRequired": "مھرباني ڪري جاري رکڻ لاءِ شرائط قبول ڪريو.",
  "auth.err.passwordMismatch": "پاسورڊ ملتا ناهن.",
  "auth.err.loginPasswordRequired": "توھان جو پاسورڊ داخل ڪريو.",
  "auth.err.tooManyAttempts": "گھنوري ڪوششن — مھرباني ڪري بعد ۾ ٻيATIO ڪريو.",
  "auth.err.serverError": "اسان جي طرف ڪچھ خراب ٿيو. مھرباني ڪري ٻيATIO ڪريو.",
  "auth.err.invalidCredentials": "غلط اي ميل يا پاسورڊ.",

  "li.meta.title": "ننوزرکو — Agropioo",
  "li.meta.description": "Agropioo تي ننوزرکو، AI طatori کيec انڊلنس پليٽ فارم. توھان جي مشاور، ریکارڊ، ۽ مشورا — جتي توھان ڏنل آهيون انتظار ڪندا آهن.",
  "li.brand.headingA": "توھان جي کيec جي انڊلنس،",
  "li.brand.headingB": "جتي توھان ڏنل آهيون انتظار ڪندا آهي.",
  "li.demo.aria": "Agropioo مشاور سان ڳلیا جي پيش منظر",
  "li.demo.user": "Meri gandum ki pattiyan peeli ho rahi hain — kya karoon?",
  "li.demo.advisorLabel": "دو causes:",
  "li.demo.advisorBody": "پاني جوتنائون يا نايٽروجن جو ڪم. پهريون سهري ڪول ۾ پاني ڏيو.",
  "li.point1": "توھان جي ٻولي ۾ AI مشاور",
  "li.point2": "سیٽلائٽ فصل جي صحت نگراني",
  "li.point3": "هر موسم لاءِ ڊجٽل ریکارڊ",
  "li.eyebrow": "ننوزرکو",
  "li.heading": "توھان جي کيec تي ڀيٽ swaps وٺي",
  "li.sub": "توھان جي کيec جي مشاور، ریکارڊ، ۽ مشورن تي رسائي لاءِ ننوزرکو.",
  "li.passwordPlaceholder": "توھان جو پاسورڊ",
  "li.forgot": "پاسورڊ وڌو گم شد؟",
  "li.submitting": "ننوزرکو ٿي رهيو آهي…",
  "li.noAccount": "اکائونٽ نه آهي؟ جلدي رسائي علاقو بلي کھلاسي ٿي رهيو آهي —",
  "li.noAccountEnd": ".",
  "li.createAccount": "اکائونٽ بنايو",
  "su.meta.title": "اکائونٽ بنايو — Agropioo",
  "su.meta.description": "توھان جو Agropioo اکائونٽ بنايو: شخصي AI مشاور، موسم واري رهنمايي، ۽ کيec ریکارڊ جيڪي هر موسم بہتر ڪندا آهن. پاکستان لاءِ بڻايل.",
  "su.brand.headingA": "توھان جو موسم شروع ڪريو",
  "su.brand.headingB": "انڊلنس سان.",
  "su.profile.aria": "رجسٽر ڪرڻ کان پوءِ بنايل کيec پروفايل جي پيش منظر",
  "su.profile.badge": "کيec پروفايل · منٽ ۾ تيار",
  "su.profile.district": "ضلع",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشورو جي ٻولي",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "گندم · ربي",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پهرين ڏينهن شخصي مشاور",
  "su.included2": "توھان جي ضلع لاءِ موسم واري رهنمايي",
  "su.included3": "کيec ریکارڊ جيڪي هر موسم بہتر ڪندا آهن",
  "su.eyebrow": "اکائونٽ بنايو",
  "su.heading": "توھان جي کيec کي Agropioo تي ڏنو",
  "su.sub": "توھان جي مشاور، ریکارڊ، ۽ هن موسم جي هر مشورو لاءِ هڪ اکائونٽ.",
  "su.registered.title": "هن اي ميل اڳي رجسٽر آهي.",
  "su.registered.body": "ننوزرکو، يا پاسورڊ موڙيو جڏھن توھان گم ڪيو آهي — توھان جي کيec جتي توھان ڏنل آهيون انتظار ڪندا آهي.",
  "su.registered.reset": "پاسورڊ موڙيو",
  "su.name.label": "ڏيڏي نالو",
  "su.name.placeholder": "مثلا Muhammad Ahmad",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختياري)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آفلاين تي SMS خبرن لاءِ.",
  "su.password.placeholder": "گھنوري 8 حروف",
  "su.confirm.label": "پاسورڊ تائيد",
  "su.confirm.placeholder": "پاسورڊ دوباره ڏنو",
  "su.strength0": "ايترا ڊهڻو",
  "su.strength1": "ٺيڪ",
  "su.strength2": "اچو",
  "su.strength3": "طاقتور",
  "su.terms.prefix": "مان موافقت ڪري ٿو",
  "su.terms.tos": "خدمت جي شرائط",
  "su.terms.and": "۽",
  "su.terms.privacy": "رازداري پاليسی",
  "su.terms.end": ".",
  "su.submit": "مFalsy اکائونٽ بنايو",
  "su.submitting": "اکائونٽ بنايو ٿي رهيو آهي…",
  "su.haveAccount": "اکائونٽ آهي؟",
  "app.shell.metadataTitle": "Agropioo — AI طatori کيec انڊلنس پليٽ فارم",
  "app.shell.metadataDescription": "اڄ جو مشورا، موسم، خبرون، ۽ هر Agropioo ڪال — پاکستان لاءِ بڻايل. Aplinode جو پيداوار.",

  /* ── Shell nav ─────────────────────────────────────── */
  "app.shell.nav.dashboard": "ڊيش بورڊ",
  "app.shell.nav.farms": "کيec",
  "app.shell.nav.advisor": "مشاور",
  "app.shell.nav.detect": "پکڙاء",
  "app.shell.nav.crops": "فصلن",
  "app.shell.nav.prices": "قيمتون",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "خبرون",
  "app.shell.nav.settings": "ترتيبون",
  "app.shell.nav.more": "وڌيڪ",
  "app.shell.signOut": "لاگ آئيٽ",
  "app.shell.aria.farmerTools": "کيec وارو جا ڪال",
  "app.shell.aria.currentPage": "موجوده صفحو",

  /* ── Dashboard UI chrome ───────────────────────────── */
  "app.dashboard.greeting": "السلام عليکم، {name}",
  "app.dashboard.aria.profileMenu": "پروفائل مینو",
  "app.dashboard.welcomeEyebrow": "Agropioo ۾ خوش آمدید",
  "app.dashboard.welcomeTitle": "توھان جي پهريني کيec سان شروع ڪريو.",
  "app.dashboard.welcomeBody": "توھان جي فصل، مٽي، موسم — جڏھن توھان جي کيec انتېري وڃي ٿو هر مشورا هن مان بنايو وڃي ٿو.",
  "app.dashboard.addFirstFarm": "پهرين کيec شامل ڪريو",
  "app.dashboard.badge.today": "اڄ",
  "app.dashboard.aria.advisoryTitle": "اڄ جو مشورو",
  "app.dashboard.carryToField": "کhet تي وٺي وڃي",
  "app.dashboard.askAdvisor": "مشاور کي پڇھو",
  "app.dashboard.aria.weatherTitle": "موسم · {location}",
  "app.dashboard.aria.degreesCelsius": "سلسيس {n} ڊگري",
  "app.dashboard.fullForecast": "سڄري پيش گوئي",
  "app.dashboard.weatherUnavailable": "موسم هن وقتي لوڊ نه ٿي رهيو. تھوڙي ڇوٽي ٻيATIO ڪريو — توهان جا مشورا جاري رهندە آهن.",
  "app.dashboard.seasonTipBadge": "موسم جي مشورو",
  "app.dashboard.alertsHeading": "خبرون",
  "app.dashboard.newCount": "{n} نئون",
  "app.dashboard.viewAllAlerts": "سڀ خبرون ڏيڪو",
  "app.dashboard.noAlerts": "اڄ ڪو خبر نه — توھان جا فصل قائم آهن.",
  "app.dashboard.aria.alert": "خبر",
  "app.dashboard.severity.critical": "اهم",
  "app.dashboard.severity.watch": "نگراني",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "ٻولي",
  "app.dashboard.weatherNoLocation": "بيانات جي موسم توھان جي کيec جو مقام سيٽ ٿي وڃي تي هتي ظاهر ٿي ٿو.",
  "app.dashboard.weatherYourArea": "توھان جو علاقه",
  "app.dashboard.quickActionsHeading": "چوڙهي سرگرميون",
  "app.dashboard.cropDoctor": "فصل ڊاڪٽر",
  "app.dashboard.detectTitle": "بيناري کان اڳ بيماري پکڙاء",
  "app.dashboard.detectBody": "متاثر پتي جو فوٹو اپلوڊ ڪريو — تشخيص وٺو ۽ ڇو ڪريو، توھان جي فون تي.",
  "app.dashboard.recommendCrops": "فصل جي تجويز",
  "app.dashboard.recommendCropsBody": "توھان جي مٽي، موسم، ۽ مقام تي بنياد شخصي فصل جا تجويز وٺو.",
  "app.dashboard.myFarms": "مaji کيec",
  "app.dashboard.addFarm": "کيec شامل ڪريو",
  "app.dashboard.viewAllFarms": "سڀ کيec ڏيڪو",
  "app.dashboard.health.good": "اچو",
  "app.dashboard.health.watch": "نگراني",
  "app.dashboard.setupChecklist": "کيec سيٽ اپ ڪريو",
  "app.dashboard.checklistProgress": "{total} ۾ {done} مکمل",
  "app.dashboard.aria.dismissChecklist": "سيٽ اپ چيڪ لسٽ رد ڪريو",
  "app.dashboard.aria.setupProgress": "سيٽ اپ ترقي",
  "app.dashboard.demoFooter": "ڊيمو بلڊ · صرف نمونو بيانات",
  "app.prices.globalSearchViewPrices": "قيمتون ڏيڪو",
  "app.prices.globalSearchNoResults": "ڪو نتيجه نه مليو",
  "app.prices.globalSearchMandis": "بازارون",
  "app.prices.globalSearchCrops": "فصلن",
  "app.prices.globalSearchPlaceholder": "پاکستان بلي فصلن يا بازارون ڳولڳول…",
  "app.advisor.chat.farmerYou": "توھان",
  "app.advisor.chat.composerHint": "توھان جي سوال ڏنو…",
  "app.advisor.chat.typing": "ڏنو ٿي رهيو آهي…",
  "app.advisor.chat.onlineStatus": "آنلاين",
  "app.advisor.chat.emptyBody": "فصلن، موسم، مٽي، ۽ بازار جي قيمتون بارATTERY مشورو حاصل ڪرڻ لاءِ ڳلیا شروع ڪريو.",
  "app.advisor.chat.emptyTitle": "توھان جي کيec بارATTERY ڪجهه بھي پڇھو",
  "app.advisor.chat.emptyEyebrow": "مشاور ڳلیا",
  "app.dashboard.pricesWidgetNoTracked": "قيمتون ڏيڪڻ لاءِ فصلن ٽریک ڪريو",
  "app.dashboard.pricesWidgetPerMaund": "في مونڊ",
  "app.dashboard.pricesWidgetView": "قيمتون ڏيڪو",
  "app.dashboard.pricesWidgetTitle": "بازار جا قيمتون",

  /* ── Dashboard demo data ───────────────────────────── */
  "app.dashboard.demo.todayLabel": "اتوار، 23 اگسٽ",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "نباتاتي",
  "app.dashboard.demo.advisoryAction": "اڄ آبپاشي ڏندل",
  "app.dashboard.demo.advisoryWhy": "잇飞扬heavy rain is expected this afternoon — your field will get the water naturally.",
  "app.dashboard.demo.seasonAction": "بارش آڻي کان اڳ کheten ۾ وڃيئن",
  "app.dashboard.demo.seasonWhy": "خشک عرصن کان پوءِ آهسته وائ낱ي ڏيکاري ٿو ته ڪهڙا ڌارا برآمد نه ٿيندا — اچاء کان اڳ انھن کي نوٽ ڪريو.",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "شام 2 بجے کان پوءِ بارش متوقع · 80% امکان",
  "app.dashboard.demo.alertWhitefly": "ملتان ضلع ۾ هن هفتو cotton تي سفيد مکھي جي خطرن اڇي آهن.",
  "app.dashboard.demo.alertRain": "اڄ شام 2 بجے کان پوءِ بارش متпущен — اسپري جي منصوبنديزي ڏندلي.",
  "app.dashboard.demo.alertPrice": "ملتان منڊي تي گندم جا قيمتون گزري هفتي کان 4% وڌي آهن.",
  "app.dashboard.demo.farm1Name": "خليل پور کيec",
  "app.dashboard.demo.farm1Location": "خليل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "نباتاتي",
  "app.dashboard.demo.farm2Name": "سahiwal پلاٽ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڊ، سahiwal",
  "app.dashboard.demo.farm2Crops": "کاپاس",
  "app.dashboard.demo.farm2Stage": "سگھو بڻاء",
  "app.dashboard.demo.farm3Name": "چک 62 ڊي بي",
  "app.dashboard.demo.farm3Location": "چک 62 ڊي بي، فيصل آباد",
  "app.dashboard.demo.farm3Crops": "گڏڻ",
  "app.dashboard.demo.farm3Stage": "شاخ وڌاڻ",
  "app.dashboard.demo.checklistAdvisor": "هڪ ڀيٽ مشاور کي پڇھو",
  "app.dashboard.demo.checklistDetect": "پهريون نشانديهي ڪريو",
  "app.dashboard.demo.actionAdvisor": "مشاور کي پڇھو",
  "app.dashboard.demo.actionScan": "فصل اسڪين ڪريو",
  "app.dashboard.demo.actionPrices": "قيمتون چيڪ ڪريو",
  "app.dashboard.demo.actionRecord": "ریکارڊ شامل ڪريو",
  "app.dashboard.demo.actionRecommend": "فصلن جا تجويز",

  /* ── Farms common ───────────────────────────────────── */
  "app.farms.eyebrow": "کيec",
  "app.farms.health.good": "اچو",
  "app.farms.health.watch": "نگراني",
  "app.farms.units.acres": "اڪڙ",
  "app.farms.stages.sowing": "اچاء",
  "app.farms.stages.tillering": "شاخ وڌاڻ",
  "app.farms.stages.vegetative": "نباتاتي",
  "app.farms.stages.grainFilling": "دانہ بھرپ",
  "app.farms.stages.ready": "تيار",
  "app.farms.stages.squaring": "سگھو بڻاء",
  "app.farms.stages.flowering": "پوڻ",
  "app.farms.stages.bollFilling": "بول بھرپ",
  "app.farms.stages.grandGrowth": "وڏي وڌنڊ",
  "app.farms.stages.ripening": "پکرپ",
  "app.farms.stages.harvest": "ڏينهن",
  "app.farms.stages.panicleInitiation": "پنسل شروع",

  /* ── Districts & crops ──────────────────────────────── */
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سahiwal",
  "app.farms.districts.faisalabad": "فيصل آباد",
  "app.farms.districts.vehari": "ويهاري",
  "app.farms.districts.bahawalpur": "بهوالپور",
  "app.farms.districts.lodhran": "لودهراڻ",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "کاپاس",
  "app.farms.crops.sugarcane": "گڏڻ",
  "app.farms.crops.maize": "مڪي",
  "app.farms.crops.rice": "کر",

  /* ── Farms list ─────────────────────────────────────── */
  "app.farms.list.pageTitle": "کيec — Agropioo",
  "app.farms.list.heading": "توھان جا سڀ کيec، هڪ فهرست",
  "app.farms.list.description": "هر کيec آپنن فصلن، وڌنڊ جي مرحلو، ۽ صحت سان. کيec تي ٽيپ ڪريو بڻائڻ لاءِ.",
  "app.farms.list.addLink": "شامل ڪريو",
  "app.farms.list.openFarm": "کيec کوليو",
  "app.farms.list.addNewFarm": "نئون کيec شامل ڪريو",
  "app.farms.list.emptyHeading": "اڃا تائين ڪو کيec نه آهي",

  /* ── Farms new ──────────────────────────────────────── */
  "app.farms.new.pageTitle": "کيec شامل ڪريو — Agropioo",
  "app.farms.new.heading": "کيec شامل ڪريو",
  "app.farms.new.description": "Agropioo کي توھان جي زمين بار battery — مقام، فصل، ۽ حد — ڏنو تاڪن هر مشورا هن مان بنايو وڃي.",
  "app.farms.new.fields.name": "کيec جو نالو",
  "app.farms.new.placeholders.name": "مثلا خليل پور کيec",
  "app.farms.new.fields.district": "ضلع / شهر",
  "app.farms.new.placeholders.district": "ضلع / شهر چونڊيو",
  "app.farms.new.fields.crop": "مکھي فصل",
  "app.farms.new.placeholders.crop": "فصل چونڊيو",
  "app.farms.new.fields.acres": "حد (acre)",
  "app.farms.new.placeholders.acres": "مثلا 12.5",
  "app.farms.new.fields.location": "مقام / ڳوٺ",
  "app.farms.new.placeholders.location": "ڳوٺ يا شهر جو نالو ڏنو",
  "app.farms.new.fields.primaryCrop": "مکھي فصل",
  "app.farms.new.fields.sowingDate": "اچاء جي تاريخ",
  "app.farms.new.fields.soilType": "مٽي جو قسم",
  "app.farms.new.fields.irrigationMethod": "آبپاشي جو طريقو",
  "app.farms.new.placeholders.soilType": "مٹي، وڸي، ريتال، يا سلٽ",
  "app.farms.new.buttons.saving": "محفوظ ٿي رهيو آهي…",
  "app.farms.new.buttons.save": "کيec محفوظ ڪريو",
  "app.farms.new.demoNotice": "ڊيمو · محفوظ کرڻ اڃا ڊيٽابيز تي نه جوڊيل آهي",
  "app.farms.new.success.heading": "کيec ڊيمو ۾ محفوظ ٿيو",
  "app.farms.new.success.description": "پورن بلڊ ۾ هن کيec کي توھان جي ڊيش بورڊ تي ظاهر ٿي ۽ توھان جا مشورا شروع ڪرڻ.",
  "app.farms.new.success.goToFarms": "مaji کيec تي وڃو",
  "app.farms.new.success.backToDashboard": "ڊيش بورڊ تي واپس",
  "app.farms.new.errors.nameRequired": "توھان جي کيec لاءِ نالو ڏنو.",
  "app.farms.new.errors.districtRequired": "ضلع چونڊيو.",
  "app.farms.new.errors.cropRequired": "مکھي فصل چونڊيو.",
  "app.farms.new.errors.acresRequired": "حد acre ۾ داخل ڪريو.",

  /* ── Farm detail ────────────────────────────────────── */
  "app.farms.detail.pageTitle": "کيec جا تفصيل — Agropioo",
  "app.farms.detail.heroEyebrow": "کيec جا تفصيل",
  "app.farms.detail.goodHealth": "اچو صحت",
  "app.farms.detail.needsWatching": "نگراني گهر آهي",
  "app.farms.detail.sownLabel": "اچاء",
  "app.farms.detail.seasonHeading": "فصل کيتھي آهي",
  "app.farms.detail.activityHeading": "کhet سرگرمي",
  "app.farms.detail.viewAllRecords": "سڀ ریکارڊ ڏيڪو",
  "app.farms.detail.logFieldEvent": "کhet جي واقعو لاگ ڪريو",
  "app.farms.detail.scanCrop": "هن فصل اسڪين ڪريو",
  "app.farms.detail.noRecords": "اڃا تائين ڪو ریکارڊ نه آهي — کيec جي يادداشت بنايڻ لاءِ کhet واقعن لاگ شروع ڪريو.",

  /* ── Records common ─────────────────────────────────── */
  "app.records.eyebrow": "کيec جا ریکارڊ",
  "app.records.types.irrigation": "آبپاشي",
  "app.records.types.fertilizer": "کوDate",
  "app.records.types.pesticide": "زهي کيمریکل",
  "app.records.types.disease": "بيماري",
  "app.records.types.harvest": "ڏينهن",

  /* ── Records list ───────────────────────────────────── */
  "app.records.farmRecords.pageTitle": "کيec جا ریکارڊ — Agropioo",
  "app.records.farmRecords.heading": "کيec جي يادداشت",
  "app.records.farmRecords.description": "هر آبپاشي، اسپري، ۽ علاج ليکيل آهي — تنهن لاءِ ته اڳيئل هفتو جا فيصلن يادداشت تي منحصر نه آهن.",
  "app.records.farmRecords.demoNotice": "ڊيمو · صرف نمونو اندراج",

  /* ── Records new ────────────────────────────────────── */
  "app.records.new.pageTitle": "نئون ریکارڊ — Agropioo",
  "app.records.new.heading": "کhet ۾ ڇو ٿيسي ليکيو",
  "app.records.new.description": "آبپاشي، کوDate، زهي کيمریکل، بيماري، ۽ ڏينهن جا اندراج — توھان جي کيec جي يادداشت، هڪ قطار.",
  "app.records.new.fields.type": "ڇو ٿيسي؟",
  "app.records.new.fields.farm": "کيec",
  "app.records.new.placeholders.farm": "کيec چونڊيو",
  "app.records.new.fields.date": "تاريخ",
  "app.records.new.fields.title": "مختصر عنوان",
  "app.records.new.fields.optional": "(اختياري)",
  "app.records.new.placeholders.titleIrrigation": "مثلا نہر گھو · سڄري کhet",
  "app.records.new.placeholders.titleOther": "پلاٽن تي وڌيڪ ڊوز",
  "app.records.new.fields.details": "تفصيلون",
  "app.records.new.placeholders.details": "ڪجهه بھي جيڪو اڳيئل هفتو ۾ ڪم آهي — مقدارين، موسم، کhet ڪيئن لڳو.",
  "app.records.new.buttons.saving": "محفوظ ٿي رهيو آهي…",
  "app.records.new.buttons.save": "ریکارڊ محفوظ ڪريو",
  "app.records.new.demoNotice": "ڊيمو · محفوظ کرڻ اڃا ڊيٽابيز تي نه جوڊيل آهي",
  "app.records.new.success.heading": "ریکارڊ ڊيمو ۾ محفوظ ٿيو",
  "app.records.new.success.description": "پورن بلڊ ۾ هن اندراج کي توھان جي کيec جي ریکارڊ ۾ ظاهر ٿي ۽ مستقبل جا مشورا بہتر ڪن.",
  "app.records.new.success.backToDashboard": "ڊيش بورڊ تي واپس",
  "app.records.new.success.viewFarms": "مaji کيec ڏيڪو",
  "app.records.new.errors.farmRequired": "هڪ کيec چونڊيو جتي هن واقعو ٿيسي.",
  "app.records.new.errors.dateRequired": "تاريخ چونڊيو.",

  /* ── Advisor ────────────────────────────────────────── */
  "app.advisor.pageTitle": "مشاور",
  "app.advisor.sidebar.title": "ڳلیا",
  "app.advisor.sidebar.newConversation": "نئون ڳلیا",
  "app.advisor.sidebar.noConversations": "اڃا تائين ڪو ڳلیا نه آهي. هڪ نئون شروع ڪريو!",
  "app.advisor.sidebar.rename": "نالو بدلائيو",
  "app.advisor.sidebar.delete": "ختم ڪريو",
  "app.advisor.sidebar.deleteTitle": "ڳلیا ختم ڪريو",
  "app.advisor.sidebar.deleteConfirm": "هن ڳلیا ختم ڪريو؟ هن جي واپسي نه آهي.",
  "app.advisor.sidebar.cancel": "رد ڪريو",
  "app.advisor.sidebar.closeSidebar": "بانurity بند ڪريو",
  "app.advisor.chat.placeholder": "توھان جي فصلن، موسم، قيمتون بار battery…",
  "app.advisor.chat.send": "بھيجو",
  "app.advisor.chat.thinking": "سوچي رهيو آهي…",
  "app.advisor.chat.openingGreeting": "السلام عليکم! مان توھان جو Agropioo زراعتي مشاور آهي.",
  "app.advisor.chat.photoRedirect": "فوٹو جي نشانديهي ڊيٽيڪٽ صفحي تي آهي.",
  "app.advisor.chat.nonFarmingRedirect": "مان زراعتي سوالن لاءِ يار آهي.",
  "app.advisor.chat.tryAsking": "هڙن پڇھو",
  "app.advisor.chat.suggested1": "مaji گندم تي ڪهڙي بيماري آهي؟",
  "app.advisor.chat.suggested2": "اڄ ملتان ۾ بارش ٿي ٿي؟",
  "app.advisor.chat.suggested3": "اڄ جا منڊي قيمتون ڇا آهن؟",
  "app.advisor.chat.suggested4": "Kissan Card اسکيم بار battery ڏيرو",
  "app.advisor.errors.serviceUnavailable": "مشاور جي خدمت عارضي طور موقوف آهي.",
  "app.advisor.errors.rateLimited": "گھنوري درخواستون.",
  "app.advisor.errors.network": "نيٽ ورڪ جي خرابي.",
  "app.advisor.errors.generic": "ڪچھ خراب ٿيسي.",
  "app.advisor.aria.openSidebar": "ڳلیا کوليو",
  "app.advisor.aria.sendMessage": "سنديز بھيجو",
  "app.advisor.aria.chatMessages": "ڳلیا جا سنديز",

  /* ── Detect UI ──────────────────────────────────────── */
  "app.detect.eyebrow": "فصل ڊاڪٽر",
  "app.detect.title": "بيناري کان اڳ بيماري پکڙاء",
  "app.detect.uploadPrompt": "بيمار پتي جو فوٹو ڏنو",
  "app.detect.takePhoto": "فوٹو وٺيو يا چونڊيو",
  "app.detect.sampleScan": "فوٹو نه آهي؟ نمونو اسڪين ڪريو",
  "app.detect.readingLeaf": "پتي پڇھي رهيو آهي…",
  "app.detect.analyzing": "تجزيو ٿي رهيو آهي…",
  "app.detect.scanAnother": "ٻيو پتي اسڪين ڪريو",
  "app.detect.discussAdvisor": "مشاور سان ڳلیا ڪريو",
  "app.detect.saveToFarm": "کيec ۾ محفوظ ڪريو",
  "app.detect.savedToFarm": "{farm} ۾ محفوظ ٿيسي",
  "app.detect.notSaved": "محفوظ نه",
  "app.detect.confidence": "ياتو {pct}%",
  "app.detect.whatToDo": "هاڻو ڇو ڪريو",
  "app.detect.caution": "اسپري ڪرڻ کان اڳ هميشه خود زراعتي دفتر سان تائيد ڪريو.",
  "app.detect.noFarmsTitle": "پهرين کيec رجسٽر ڪريو",
  "app.detect.noFarmsBody": "۽ري بيماري تاريخ بنايڻ لاءِ پنن اسڪينن کي کيec سان جوڊيو.",
  "app.detect.addFarm": "کيec شامل ڪريو",
  "app.detect.dismiss": "مان هن کان پوءِ ڪريسان",
  "app.detect.pastScans": "پکيئن اسڪين",
  "app.detect.loadMore": "وڌيڪ لوڊ ڪريو",
  "app.detect.invalidFile": "مھرباني ڪري تصووپ فائل اپلوڊ ڪريو.",
  "app.detect.serviceUnavailable": "خدمت عارضي طور موقوف آهي.",
  "app.detect.noDiagnosis": "بيماري پکڙائي نه سگهيو.",
  "app.detect.retry": "ٻيATIO ڪريو",
  "app.detect.savedStatus": "{farm} ۾ محفوظ",
  "app.detect.unsavedStatus": "محفوظ نه",
  "app.detect.dragDropPrompt": "تصووپ هتي ڏنو يا ڳولڻ لاءِ ڪليڪ ڪريو",
  "app.detect.dragDropPromptLine1": "تصووپ هتي ڏنو",
  "app.detect.dragDropPromptLine2": "يا ڳولڻ لاءِ ڪليڪ ڪريو",
  "app.detect.historyEmpty": "اڃا تائين ڪو اسڪين نه آهي.",
  "app.detect.linkToFarm": "کيec سان جوڊيو",
  "app.detect.severity.watch": "نگراني",
  "app.detect.severity.treatNow": "هاڻو علاج ڪريو",
  "app.detect.severity.clear": "صاف",

  "app.detect.chat.newScan": "نئون اسڪين",
  "app.detect.chat.placeholder": "هن نشانديهي بار battery پڇھو…",
  "app.detect.chat.send": "بھيجو",
  "app.detect.chat.thinking": "سوچي رهيو آهي…",
  "app.detect.chat.imagePreview": "پوري تصووپ ڏيڪو",
  "app.detect.chat.closePreview": "پيش منظر بند ڪريو",
  "app.detect.chat.emptyState": "هن نشانديهي بار battery پوھڙو سوال پڇھو.",
  "app.detect.chat.sessionsTitle": "نشانديهي جا ڳلیا",
  "app.detect.chat.noSessions": "اڃا تائين ڪو ڳلیا نه آهي.",
  "app.detect.chat.deleteSession": "نشانديهي ختم ڪريو",
  "app.detect.chat.deleteConfirm": "توھان کي يقين آهي ته هن ڳلیا ختم ڪرڻ آھيو؟",
  "app.detect.chat.cancel": "رد ڪريو",

  "app.detect.sidebar.title": "تاريخ",
  "app.detect.sidebar.newScan": "نئون اسڪين",
  "app.detect.sidebar.closeSidebar": "بانurity بند ڪريو",
  "app.detect.sidebar.noHistory": "اڃا تائين ڪو اسڪين يا ڳلیا نه آهي.",
  "app.detect.sidebar.scansTitle": "پکيئن اسڪين",
  "app.detect.sidebar.chatsTitle": "ڳلیا جا نشانديهي",

  /* ── Detect shared crops ─────────────────────────────── */
  "app.detect.crop.apple": "سیب",
  "app.detect.crop.blueberry": "بلو بيري",
  "app.detect.crop.cherry": "چيري",
  "app.detect.crop.corn": "مڪي",
  "app.detect.crop.grape": "انگور",
  "app.detect.crop.orange": "نارنگي",
  "app.detect.crop.peach": "آڑو",
  "app.detect.crop.pepper": "مرچ",
  "app.detect.crop.potato": "آلو",
  "app.detect.crop.raspberry": "رسپ بيري",
  "app.detect.crop.soybean": "سويابين",
  "app.detect.crop.squash": "کدو",
  "app.detect.crop.strawberry": "اسٽرابيري",
  "app.detect.crop.tomato": "ٽماٽو",

  /* ── Detect shared rescan timings ────────────────────── */
  "app.detect.rescan.7": "7 ڏينهن بعد ٻي اسڪين ڪريو",
  "app.detect.rescan.14": "14 ڏينهن بعد ٻي اسڪين ڪريو",
  "app.detect.rescan.21": "21 ڏينهن بعد ٻي اسڪين ڪريو",

  /* ── Healthy leaf ────────────────────────────────────── */
  "app.detect.healthy.name": "صحت مند",
  "app.detect.healthy.causes": "هن پتي تي ڪو بيماري جي نشاني نه ملي.",
  "app.detect.healthy.steps.0": "علاج ضروري ناهي. عام خدمت ۽ جانچ جاري رکو.",

  /* ── Apple diseases ──────────────────────────────────── */
  "app.detect.disease.apple_scab.name": "سیب جي زنگ",
  "app.detect.disease.apple_scab.causes": "فungi (Venturia inaequalis) ٿڌي، نم بهاريون ۾ پھيلن ٿا.",
  "app.detect.disease.apple_scab.steps.0": "خزاڻ ۾ متاثر ڳوپن پتي ٺاھو ۽ ختم ڪريو.",
  "app.detect.disease.apple_scab.steps.1": "بهاريون ۾ fungicide اسپري ڪريو.",
  "app.detect.disease.apple_scab.steps.2": "وڌيڪ هوا ڏيڻ لاءِ ڪاٽ ڪريو ۽ اوپر آبپاشي نه ڪريو.",
  "app.detect.disease.apple_black_rot.name": "سیب جي ڪري",
  "app.detect.disease.apple_black_rot.causes": "فungi (Botryosphaeria obtusa) ٺان ۽ ٽٽن تي حملو ڪري ٿو.",
  "app.detect.disease.apple_black_rot.steps.0": "متاثر اندراج ڪاٽ ڪريو ۽ ساڙي.",
  "app.detect.disease.apple_black_rot.steps.1": "حفاظتي fungicide لڳائيو.",
  "app.detect.disease.apple_black_rot.steps.2": "کاڻو کھلا رکو.",
  "app.detect.disease.apple_cedar_rust.name": "سیب-ايدي جي زنگ",
  "app.detect.disease.apple_cedar_rust.causes": "زنگ fungi جيڪو سیب ۽ eedar جي وچ ۾ وچول وڃي ٿو.",
  "app.detect.disease.apple_cedar_rust.steps.0": "سلي جي سامنا واري قسم وٺو.",
  "app.detect.disease.apple_cedar_rust.steps.1": "fungicide اسپري ڪريو.",
  "app.detect.disease.apple_cedar_rust.steps.2": "500m ۾ قريبي eedar ختم ڪريو.",

  /* ── Cherry diseases ─────────────────────────────────── */
  "app.detect.disease.cherry_powdery_mildew.name": "چيري جي پانixin",
  "app.detect.disease.cherry_powdery_mildew.causes": "ف fungi جيڪو پتي تي ابيض پانixin بنايو ٿا.",
  "app.detect.disease.cherry_powdery_mildew.steps.0": "هوا جي گردش بہتر ڪريو.",
  "app.detect.disease.cherry_powdery_mildew.steps.1": "fungicide اسپري ڪريو.",
  "app.detect.disease.cherry_powdery_mildew.steps.2": "نائتروجن وڌيڪ فارم سان بچو.",

  /* ── Corn diseases ───────────────────────────────────── */
  "app.detect.disease.corn_gray_leaf_spot.name": "سلي ڊھبہ",
  "app.detect.disease.corn_gray_leaf_spot.causes": "ف fungi جيڪو گرم، نم حالت ۾ پھيلن ٿو.",
  "app.detect.disease.corn_gray_leaf_spot.steps.0": "سلي جي مukt هائيبرڊ استعمال ڪريو.",
  "app.detect.disease.corn_gray_leaf_spot.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.corn_gray_leaf_spot.steps.2": "صبح آبپاشي ڪريو.",
  "app.detect.disease.corn_common_rust.name": "مڪي جي عام زنگ",
  "app.detect.disease.corn_common_rust.causes": "ف fungi جيڪو پتي تي نارنگي بثر بنائي ٿو.",
  "app.detect.disease.corn_common_rust.steps.0": "سلي جي سامنا واري هائيبرڊ وٺو.",
  "app.detect.disease.corn_common_rust.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.corn_common_rust.steps.2": "مکي کان پوءِ مکي نه وٺو.",
  "app.detect.disease.corn_northern_leaf_blight.name": "اترن leaf blight",
  "app.detect.disease.corn_northern_leaf_blight.causes": "ف fungi جيڪو ٿڌي، نم موسم ۾ لامبو ڊھبہ بنايو ٿو.",
  "app.detect.disease.corn_northern_leaf_blight.steps.0": "فصل بدلائيو.",
  "app.detect.disease.corn_northern_leaf_blight.steps.1": "سلي جي مukt هائيبرڊ وٺو.",
  "app.detect.disease.corn_northern_leaf_blight.steps.2": "وڌيڪ هوا ڏيڻ لاءِ پنن جي وڌيڪ دوري رکو.",

  /* ── Grape diseases ──────────────────────────────────── */
  "app.detect.disease.grape_black_rot.name": "انگور جي ڪري",
  "app.detect.disease.grape_black_rot.causes": "ف fungi جيڪو نم بهاريون ۾ انگور تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.grape_black_rot.steps.0": "متاثر شاخن ڪاٽ ڪريو.",
  "app.detect.disease.grape_black_rot.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.grape_black_rot.steps.2": "پڻ جو وقت اوپر آبپاشي نه ڪريو.",
  "app.detect.disease.grape_esca.name": "انگور جي esca",
  "app.detect.disease.grape_esca.causes": "فungi جيڪو شاخن تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.grape_esca.steps.0": "متاثر لڪڙي ڪاٽ ڪريو.",
  "app.detect.disease.grape_esca.steps.1": "fungicide اسپري ڪريو.",
  "app.detect.disease.grape_esca.steps.2": "آبپاشي جو انتظام ڪريو.",
  "app.detect.disease.grape_leaf_blight.name": "انگور جي leaf blight",
  "app.detect.disease.grape_leaf_blight.causes": "ف fungi جيڪو ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.grape_leaf_blight.steps.0": "متاثر پتي ختم ڪريو.",
  "app.detect.disease.grape_leaf_blight.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.grape_leaf_blight.steps.2": "هوا گردش بہتر ڪريو.",

  /* ── Orange diseases ─────────────────────────────────── */
  "app.detect.disease.orange_huanglongbing.name": "نارنگي جي بيماري",
  "app.detect.disease.orange_huanglongbing.causes": "بیکٽيريا جي بيماري جيڪو psyllids ذريعي پھيلن ٿي.",
  "app.detect.disease.orange_huanglongbing.steps.0": "psyllid کي کنٽرول ڪريو.",
  "app.detect.disease.orange_huanglongbing.steps.1": "متاثر رکن ختم ڪريو.",
  "app.detect.disease.orange_huanglongbing.steps.2": "بيماري مکfree نرسرئي وٺو.",

  /* ── Peach diseases ──────────────────────────────────── */
  "app.detect.disease.peach_bacterial_spot.name": "آڑو جي بیکٽيريا ڊھبہ",
  "app.detect.disease.peach_bacterial_spot.causes": "بیکٽيريا (Xanthomonas) جيڪو پتي ۽ ٺان تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.peach_bacterial_spot.steps.0": "خشک موسم ۾ ڪاٽ ڪريو.",
  "app.detect.disease.peach_bacterial_spot.steps.1": "بیکٽيريا کيل لڳائيو.",
  "app.detect.disease.peach_bacterial_spot.steps.2": "اوپر آبپاشي نه ڪريو.",

  /* ── Pepper diseases ─────────────────────────────────── */
  "app.detect.disease.pepper_bacterial_spot.name": "مرچ جي بیکٽيريا ڊھبہ",
  "app.detect.disease.pepper_bacterial_spot.causes": "بیکٽيريا (Xanthomonas) جيڪو گرم، نم موسم ۾ مرچ تي ڪري ڊھبن بنائي ٿي.",
  "app.detect.disease.pepper_bacterial_spot.steps.0": "وڌيڪ هوا ڏيڻ لاءِ پنن جي وڌيڪ دوري رکو.",
  "app.detect.disease.pepper_bacterial_spot.steps.1": "ٿPros hydroxide لڳائيو.",
  "app.detect.disease.pepper_bacterial_spot.steps.2": "متاثر پتي فوري ختم ڪريو.",

  /* ── Potato diseases ─────────────────────────────────── */
  "app.detect.disease.potato_early_blight.name": "آلو جي زود blight",
  "app.detect.disease.potato_early_blight.causes": "ف fungi (Alternaria solani) جيڪو گرم، نم حالت ۾ پتي تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.potato_early_blight.steps.0": "تصديق شدہ بج استعمال ڪريو.",
  "app.detect.disease.potato_early_blight.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.potato_early_blight.steps.2": "پن خشک رکڻ لاءِ وڌيڪ دوري رکو.",
  "app.detect.disease.potato_late_blight.name": "آلو جي پکي blight",
  "app.detect.disease.potato_late_blight.causes": "پاني جو fungi (Phytophthora infestans) جيڪو ٿڌي، نم موسم ۾ بہت خراب.",
  "app.detect.disease.potato_late_blight.steps.0": "متاثر آلو ۽ پن فوري ختم ڪريو.",
  "app.detect.disease.potato_late_blight.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.potato_late_blight.steps.2": "سامنا واري قسم وٺو.",

  /* ── Squash diseases ─────────────────────────────────── */
  "app.detect.disease.squash_powdery_mildew.name": "کدو جي پانixin",
  "app.detect.disease.squash_powdery_mildew.causes": "ف fungi جيڪو پتي تي ابيض پانixin بنايو ٿا.",
  "app.detect.disease.squash_powdery_mildew.steps.0": "سامنا واري قسم وٺو.",
  "app.detect.disease.squash_powdery_mildew.steps.1": "fungicide اسپري ڪريو.",
  "app.detect.disease.squash_powdery_mildew.steps.2": "صبح پن خشک رکڻ لاءِ مول تي پاني ڏنو.",

  /* ── Strawberry diseases ─────────────────────────────── */
  "app.detect.disease.strawberry_leaf_scorch.name": "اسٽرابيري جي leaf scorch",
  "app.detect.disease.strawberry_leaf_scorch.causes": "ف fungi جيڪو پتي تي ڳاڙهو ڊھبہ بنائي ٿو.",
  "app.detect.disease.strawberry_leaf_scorch.steps.0": "اوپر آبپاشي نه ڪريو.",
  "app.detect.disease.strawberry_leaf_scorch.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.strawberry_leaf_scorch.steps.2": "شديد متاثر پتي ختم ڪريو.",

  /* ── Tomato diseases ─────────────────────────────────── */
  "app.detect.disease.tomato_bacterial_spot.name": "ٽماٽو جي بیکٽيريا ڊھبہ",
  "app.detect.disease.tomato_bacterial_spot.causes": "بیکٽيريا (Xanthomonas) جيڪو پتي ۽ ٺان تي ڪري ڊھبن بنائي ٿي.",
  "app.detect.disease.tomato_bacterial_spot.steps.0": "بيماري مکfree بج استعمال ڪريو.",
  "app.detect.disease.tomato_bacterial_spot.steps.1": "بیکٽيريا کيل لڳائيو.",
  "app.detect.disease.tomato_bacterial_spot.steps.2": "متاثر پتي ۽ ٺان ختم ڪريو.",
  "app.detect.disease.tomato_early_blight.name": "ٽماٽو جي زود blight",
  "app.detect.disease.tomato_early_blight.causes": "ف fungi (Alternaria solani) جيڪو ڍرين پتي تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.tomato_early_blight.steps.0": "مالچ ڏيرو ۽ مول تي پاني ڏنو.",
  "app.detect.disease.tomato_early_blight.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.tomato_early_blight.steps.2": "متاثر پن ڊانٽ ڪريو.",
  "app.detect.disease.tomato_late_blight.name": "ٽماٽو جي پکي blight",
  "app.detect.disease.tomato_late_blight.causes": "پاني جو fungi جيڪو پتي ۽ ٺان تي بہت خراب.",
  "app.detect.disease.tomato_late_blight.steps.0": "متاثر پن ۽ ٺان فوري ختم ڪريو.",
  "app.detect.disease.tomato_late_blight.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.tomato_late_blight.steps.2": "سامنا واري قسم وٺو.",
  "app.detect.disease.tomato_leaf_mold.name": "ٽماٽو جي leaf mold",
  "app.detect.disease.tomato_leaf_mold.causes": "ف fungi جيڪو پتي تي زرد ڊھبن بنائي ٿو.",
  "app.detect.disease.tomato_leaf_mold.steps.0": "هوا گردش بہتر ڪريو.",
  "app.detect.disease.tomato_leaf_mold.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.tomato_leaf_mold.steps.2": "مُول تي پاني ڏنو.",
  "app.detect.disease.tomato_septoria.name": "ٽماٽو جي septoria ڊھبہ",
  "app.detect.disease.tomato_septoria.causes": "ف fungi جيڪو پکين پتي تي چھوٽا ڊھبہ بنائي ٿو.",
  "app.detect.disease.tomato_septoria.steps.0": "فصل بدلائيو.",
  "app.detect.disease.tomato_septoria.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.tomato_septoria.steps.2": "متاثر ڍرين پتي ختم ڪريو.",
  "app.detect.disease.tomato_spider_mites.name": "ٽماٽو جي spider mites",
  "app.detect.disease.tomato_spider_mites.causes": "ننھن mites جيڪو پتي جو رس چوسن ٿا.",
  "app.detect.disease.tomato_spider_mites.steps.0": "پاني سان mites ڌوئي.",
  "app.detect.disease.tomato_spider_mites.steps.1": "فائدمند حشرات ڏيرو يا neem oil لڳائيو.",
  "app.detect.disease.tomato_spider_mites.steps.2": "عام حشرات نه وٺو.",
  "app.detect.disease.tomato_target_spot.name": "ٽماٽو جي target ڊھبہ",
  "app.detect.disease.tomato_target_spot.causes": "ف fungi جيڪو پتي تي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.tomato_target_spot.steps.0": "ڍرين پتي ڪاٽ ڪريو.",
  "app.detect.disease.tomato_target_spot.steps.1": "fungicide لڳائيو.",
  "app.detect.disease.tomato_target_spot.steps.2": "صبح مول تي پاني ڏنو.",
  "app.detect.disease.tomato_ylcv.name": "ٽماٽو جي yellow leaf curl virus",
  "app.detect.disease.tomato_ylcv.causes": "وائرس جيڪو whiteflies ذريعي پھيلن ٿي.",
  "app.detect.disease.tomato_ylcv.steps.0": "whiteflies کي کنٽرول ڪريو.",
  "app.detect.disease.tomato_ylcv.steps.1": "متاثر پن ختم ڪريو.",
  "app.detect.disease.tomato_ylcv.steps.2": "سامنا واري قسم وٺو.",
  "app.detect.disease.tomato_mosaic_virus.name": "ٽماٽو جي mosaic virus",
  "app.detect.disease.tomato_mosaic_virus.causes": "وائرس جيڪو پتي ڪري ڊھبن بنائي ٿو.",
  "app.detect.disease.tomato_mosaic_virus.steps.0": "ڪالن خالص ڪريو.",
  "app.detect.disease.tomato_mosaic_virus.steps.1": "متاثر پن ختم ڪريو.",
  "app.detect.disease.tomato_mosaic_virus.steps.2": "aphid حشرات کنٽرول ڪريو.",

  // --- Weather Advisory ---
  "app.weather.pageTitle": "موسم مشورو",
  "app.weather.eyebrow": "موسم",
  "app.weather.description": "توهان جي فصلن لاءِ روزانه معاونت، پيش گوتي۽ ۽ فصل جي وڌن جي مرحلن موجب.",
  "app.weather.todayAdvisory": "اڄ جو مشورو",
  "app.weather.growthStage": "وڌن جو مرحلو",
  "app.weather.severity.info": "معلومات",
  "app.weather.severity.warning": "خبرداري",
  "app.weather.severity.critical": ",height엄 serious",
  "app.weather.forecastTitle": "7 ڏينهن جو پيش گوئي",
  "app.weather.forecastSubtitle": "هر ڏينهن جو موسم توهان جي فصل لاءِ هڪ کسان جي س硁جو.",
  "app.weather.weatherUnavailable": "موسم جي معلومات دستياب ناهي",
  "app.weather.weatherUnavailableBody": "پاڻ جي بچت ڪريو ۽ پاڻي جي بھراؤ مان بچو.",
  "app.weather.farmSelectorLabel": "ف.getSelectionModel",
  "app.weather.registerTitle": "پاڻ جو کhet نالهنو",
  "app.weather.registerBody": "خوشڪي تي مbangge تهت اonic بanger اني بanger اني بanger بanger",
  "app.weather.registerCta": "کhet نالهنو",
  "app.weather.registerForm.crop": "مرکزي فصل",
  "app.weather.registerForm.sowing": "بaji جي تاريخ",
  "app.weather.registerForm.soil": "مzai جي قسم",
  "app.weather.registerForm.irrigation": "آبپاشي جو طريقو",
  "app.weather.registerForm.soilTypes": "ميتي، رميتي، رميتي، رميتي",
  "app.weather.registerForm.irrigationMethods": "Drip، sprinkler، flood، يا rainfed",
  "app.weather.registerForm.save": "saved ڪريو ۽ منھنجو مشورو ڏسو",
  "app.weather.registerForm.saving": "saved ٿي رهيو آهي...",
  "app.weather.registerForm.success": "saved — هنڌو توهان جو مشورو",
  "app.weather.registerForm.error": "توهان جي کhet جي تفصيل نه saved ٿي سکي. مهرباني ڪري ڪري ٻي.",
  "app.weather.historyTitle": "مشاوري جي تاريخ",
  "app.weather.historySubtitle": "گذリー سفارهات، سڀ تازه پهريون.",
  "app.weather.history.empty": "اڃي تائين ڪو مشورو نه آهي.",
  "app.weather.history.date": "تاريخ",
  "app.weather.history.severity": "سنگيني",
  "app.weather.history.status": "حالت",
  "app.weather.history.status.new": "نئون",
  "app.weather.history.status.seen": "ڏسلي",
  "app.weather.history.status.acted": "عمل ڪري",
  "app.weather.history.loadMore": " criticised وڌيڪ loader",
  "app.weather.history.viewAll": "ساري تاريخ ڏسو",
  "app.weather.detail.back": "تاريخ تي واپس",
  "app.weather.detail.weatherConditions": "موسم جي حالت",
  "app.weather.detail.recommendation": "سفارهات",
  "app.weather.detail.markActed": "عمل ڪئي طرح نشاني لڳائيو",
  "app.weather.detail.markAcknowledged": "ڏسنئي طرح نشاني لڳائيو",
  "app.weather.detail.markedActed": "عمل ڪئي طرح نشاني لڳائي",
  "app.weather.detail.markedSeen": "ڏسنئي طرح نشاني لڳائي",
  "app.weather.alerts.title": "فعال alerts",
  "app.weather.alerts.heavyRain": "شديد بارش متوقع — آبپاشي تاخير ڪريو ۽ گنايل فصل خاص خ behaviour.",
  "app.weather.alerts.frost": "پاڻ جا خطرن — آج رات حساس فصل خاص خ behaviour.",
  "app.weather.alerts.extremeHeat": "انتهاي گرمي — آبپاشي وڌائيو ۽ من ڄاں کhet ڪم نه ڪريو.",
  "app.weather.alerts.diseaseRisk": "ني_GENERIC رطوبت بيماري جي liability آهي — خشڪ صبح جي وقت احتیاطي fungicide لڳائيو.",
  "app.weather.alerts.dismiss": "نNr CGRectDismiss",
  "app.weather.alerts.noAlerts": "اڃي تائين ڪو فعال alert نه آهي.",
  "app.weather.alerts.viewAll": "ساري notifications ڏسو",
  "app.weather.stages.seedling": "پيل",
  "app.weather.stages.vegetative": "پودن جو مرحلو",
  "app.weather.stages.flowering": "پهولن جو مرحلو",
  "app.weather.stages.maturation": "پک جو مرحلو",
  "app.weather.stages.harvestReady": "وٺڻ لاءِ تيار",
  "app.weather.stages.generic": "عام",
  "app.weather.source.live": "लाइब forecast · OpenWeather",
  "app.weather.source.cached": "آخري saved forecast",
  "app.weather.source.demo": "نمونه forecast — live data لاءِ API key اضافو ڪريو",
  "app.weather.advisory.recommendation.irrigation": "اڄ آبپاشي نه ڪريو — بارش متوقع آهي. پاڻ بچائيو ۽ پاڻي جي بھراؤ مان بچو.",
  "app.weather.advisory.recommendation.irrigateNow": "پاڻ جي گرمي جي وقت (صبح 9 بجاء تي) آبپاشي ڪريو — گرمي وڌي رهي آهي ۽ زمين خشڪ ٿي رهي آهي.",
  "app.weather.advisory.recommendation.fertilize": "موسمي weather مان پهرين fertilizer لڳائيجي وڳ سARED.",
  "app.weather.advisory.recommendation.sprayDisease": "ني_GENERIC رطوبت بيماري جي liability آهي — خشڪ صبح جي وقت احتیاطي fungicide لڳائيو.",
  "app.weather.advisory.recommendation.heatProtect": "انتهاي گرمي — آبپاشي وڌائيو ۽ من ڄاں کhet ڪم نه ڪريو.",
  "app.weather.advisory.recommendation.frostProtect": "آج رات پاڻ جا خطرن — نو渴ون جو ڍڪي آهي يا زمين گرم ڪرڻ لاءِ آبپاشي ڪريو.",
  "app.weather.advisory.recommendation.harvest": "فصل وٺڻ ٿي آهي — خشڪ ڏينهن وٺڻ منصوب بڻائيو ۽ پکيل فصل بارش مان بچائيو.",
  "app.weather.advisory.recommendation.plantCare": "وڌن جو مرحلو稳定 آهي — باقاعدگي آبپاشي ۽ نيند بناي رکو.",
  "app.weather.advisory.recommendation.generic": "اڄ ڪو خاص عمل نه آهي — کhet ۽ forecast تي نظر رکو.",
  "app.weather.buttons.register": "کhet نالهنو",
  "app.weather.buttons.refresh": "تازه ڪريو",
  "app.weather.errors.generic": "ڪو ٿي. مهرباني ڪري ٻي.",
  "app.weather.errors.noFarm": "مشاوري ڏسان لاءِ هڪ farm منتخب ڪريو.",
  "app.weather.metric.temperature": "درجه حرارت",
  "app.weather.metric.precipitation": "بارش",
  "app.weather.metric.wind": "هوا",
  "app.weather.metric.humidity": "ني_GENERIC",

  /* ── Mandi Price Tracker ─────────────────────────────── */
  "app.prices.eyebrow": "مينڊي جا قيمت",
  "app.prices.title": "وڏيي ڀاء ريال قيمت ڄاڻهيو",
  "app.prices.description": "هازيل قريبين مينڊين جا قيمت، وڏيي يا وڌيڪ وڃو.",
  "app.prices.selectCrop": "فصل چونڊيو",
  "app.prices.searchPlaceholder": "پاکستان بھر ۾ فصل يا مينڊي ڳوليyo",
  "app.prices.noData": "قيمت جي معلومات دستياب ناهي",
  "app.prices.updatedToday": "اڄ تازه ٿي",
  "app.prices.updatedDaysAgo": "{days} ڏينهن پهرين تازه ٿي",
  "app.prices.marketHoliday": "مينڊي بند آهي / بازار جي چھٹي",
  "app.prices.perMaund": "/ مونڊ",
  "app.prices.bestPrice": "بہترين قيمت",
  "app.prices.distanceKm": "{km} km دور",
  "app.prices.hold": "وهرو",
  "app.prices.sell": "وڏيي",
  "app.prices.recommendationHold": "بہتر قيمت لاءِ وهرو",
  "app.prices.recommendationSell": "جلدي وڏيي",
  "app.prices.volatilityWarning": "زياده تبديلي / گھڻي معلومات",
  "app.prices.predictionTitle": "14 ڏينهن جي قيمت جي پيش گوئي",
  "app.prices.historyTitle": "قيمت جي تاريخ",
  "app.prices.range1M": "1 مهينو",
  "app.prices.range3M": "3 مهينا",
  "app.prices.range6M": "6 مهينا",
  "app.prices.range12M": "1 سال",
  "app.prices.setAlert": "قيمت جو alert سattyو",
  "app.prices.editAlert": "alert سمپديت ڪريو",
  "app.prices.saveAlert": "alert saved ڪريو",
  "app.prices.cancel": "منسوخ",
  "app.prices.alertCrop": "فصل",
  "app.prices.alertMandi": "مينڊي",
  "app.prices.alertMandiOptional": "مينڊي (اختياري)",
  "app.prices.alertStatus": "حالت",
  "app.prices.targetPrice": "هداف قيمت (PKR / مونڊ)",
  "app.prices.alertActive": "فعال",
  "app.prices.alertPaused": "روکل",
  "app.prices.deleteAlert": "alert ختم ڪريو",
  "app.prices.fallbackBanner": "خودڪار طور تي پلوڻي جا قيمت ڏسان لاءِ پاڻ جي farm جي پوزيشن سattyو.",
  "app.prices.comparisonTitle": "بازارن جي سمپتي",
  "app.prices.market": "بازار",
  "app.prices.modalPrice": "モdal قيمت",
  "app.prices.minPrice": "کم ترین قيمت",
  "app.prices.maxPrice": "وڌيڪ قيمت",
  "app.prices.change": "تبدلي",
  "app.prices.distance": "دوري",
  "app.prices.adminTitle": "دستي قيمت اندار",
  "app.prices.adminDate": "تاريخ",
  "app.prices.adminModalPrice": "モdal قيمت",
  "app.prices.adminMinPrice": "کم ترین قيمت",
  "app.prices.adminMaxPrice": "وڌيڪ قيمت",
  "app.prices.adminHoliday": "بازار جي چھٹي",
  "app.prices.adminSave": "قيمت saved ڪريو",
  "app.prices.loading": "قيمت لوڊ ٿي رهي آهي...",
  "app.prices.retry": "ٻي ڪريو",
  "app.prices.noPricesForCrop": "ھتي قريب ھنڌي فصل لاءِ قيمت نه مليل.",
  "app.prices.comingSoon": "جلدي آهي",

  /* ── Crop Recommendation Engine ─────────────────────── */
  "app.crops.eyebrow": "فصل جي سفارهات",
  "app.crops.title": "ھن موسم مون کيا لڳائڻ چاهيئي؟",
  "app.crops.description": "پاڻ جي کhet بار ڪريو ۽ اسان توهان جي زمين، موسم ۽ بجٹ لاءِ بہترين، پائيدار فصلن جي درجه بندي ڪندا.",
  "app.crops.nav": "فصل",
  "app.crops.form.farmLabel": "کhet",
  "app.crops.form.seasonLabel": "موسم",
  "app.crops.form.yearLabel": "سال",
  "app.crops.form.soilLabel": "زمين جي قسم",
  "app.crops.form.irrigationLabel": "آبپاشي",
  "app.crops.form.budgetLabel": "بجٹ",
  "app.crops.form.soilOther": "نهاڻيو / ٻيو",
  "app.crops.form.submit": "سفارهات حاصل ڪريو",
  "app.crops.form.submitting": "حساب ٿي رهيو آهي...",
  "app.crops.form.lowestViableWarning": "توهان جي بجٹ لاءِ ڪو فصل نه آهي. توهان جي کhet لاءِ گھٽ ترین بجٹ ڌاريو \"{bracket}\" آهي.",
  "app.crops.form.switchBracket": "بدلو ڪريو \"{bracket}\" تي",
  "app.crops.form.noFarm": "سفارهات حاصل ڪرڻ لاءِ پهرين farm شامل ڪريو.",
  "app.crops.form.geoError": "سفارهات صرف پاکستان جي کhetن لاءِ دستياب آهن.",
  "app.crops.form.regionalSoilNote": "توهان جي ضلع جي علائقي جي زمين جي پروفائل موجب (نه توھان جي پاڻ جي کhet جي جانچ).",
  "app.crops.form.nationalSoilNote": "قومي انداز موجب، نه توهان جي علائقي جو.",
  "app.crops.seasons.summer": "گرمي",
  "app.crops.seasons.winter": "سردي",
  "app.crops.seasons.autumn": "خORIZ",
  "app.crops.seasons.spring": "بهار",
  "app.crops.seasons.rainy": "بارشي",
  "app.crops.seasons.windy": "هري",
  "app.crops.soil.sandy": "رتيلي",
  "app.crops.soil.sandy_loam": "رتيلي رميتي",
  "app.crops.soil.loamy": "رميتي",
  "app.crops.soil.clay_loam": "ميتي رميتي",
  "app.crops.soil.clay": "ميتي",
  "app.crops.soil.silty": "ميتي",
  "app.crops.soil.saline": "نمکين",
  "app.crops.soil.rocky": "پهري",
  "app.crops.soil.other": "نهاڻيو / ٻيو",
  "app.crops.budget.low": "ويجھو (Rs 25,000/acre تائين)",
  "app.crops.budget.medium": "درميانو (Rs 25,000–60,000/acre)",
  "app.crops.budget.high": "وتري (Rs 60,000–120,000/acre)",
  "app.crops.budget.very_high": "orna وچو (Rs 120,000/acre مان وڌيڪ)",
  "app.crops.irrigation.rainfed": "بارشي",
  "app.crops.irrigation.canal": "نہر",
  "app.crops.irrigation.tubewell": "ٹیوب ويل",
  "app.crops.irrigation.mixed": "مرکب",
  "app.crops.results.title": "توهان جا ٣ بہترين فصل",
  "app.crops.results.rank": "درجه {n}",
  "app.crops.results.revenue": "اندازه آمدنی/acre",
  "app.crops.results.reason": "ڇو ھي فصل",
  "app.crops.results.risks": "اهم خطرن",
  "app.crops.results.saveToPlan": "منصوب ۾ saved ڪريو",
  "app.crops.results.saved": "منصوب ۾ saved ٿي",
  "app.crops.results.compare": "فصلن جي سمپتي",
  "app.crops.results.projectionNote": "آمدنی هڪ پيش گوئي آهي، ضمانت نه آهي — {sources} موجب.",
  "app.crops.results.sourceWeather": "موسم",
  "app.crops.results.sourceMarket": "بازار",
  "app.crops.results.sourceSoil": "زمين",
  "app.crops.results.weatherMissing": "موسم جي معلومات دستياب نه هو — ھنڌي سفارهات گھٽ موسم جي تفصيل استعمال ڪئي.",
  "app.crops.results.marketMissing": "بازاري قيمت دستياب نه هو، لهٖڻي آمدنی غیر يقيني آهي.",
  "app.crops.results.soilMissing": "زمين جي معلومات محدود هو، لهٖڻي يقين کم آهي.",
  "app.crops.results.regenerate": "نئون بنايو",
  "app.crops.results.regenerateConfirm": "ھنڌي سفارهات بدليون ويجھن. جاري رکن؟",
  "app.crops.results.alreadyExists": "توهان کي ھن farm، موسم ۽ سال لاءِ اڳي ھي سفاره آهي.",
  "app.crops.results.viewExisting": "اڳي ھي ڏسو",
  "app.crops.results.noCandidates": "توهان جي موسم ۽ بجٹ سان ڪو فصل مeil نه آهي. وڌيڪ بجٹ ڌاريو وڌيڪ وڃو.",
  "app.crops.results.replacedPlan": "توهان جو پاڻ جي موسم لاءِ پاڻ جي منصوبو بدلائي ويو.",
  "app.crops.detail.title": "تفصيلي سفارهات",
  "app.crops.detail.back": "سفارهات تي واپس",
  "app.crops.detail.confidence": "يقين",
  "app.crops.detail.scoreBreakdown": "نمبر جي تقسيم",
  "app.crops.detail.suitability": "لاڳاپو",
  "app.crops.detail.weatherFit": "موسم جي مطابقت",
  "app.crops.detail.profitability": "فيض آوري",
  "app.crops.detail.risk": "خطرن (کم بہتر)",
  "app.crops.detail.sustainability": "پائيداري",
  "app.crops.detail.final": "آخري نمبر",
  "app.crops.detail.dataFreshness": "معلومات جي عمر: {seconds} سیکنڊ",
  "app.crops.detail.soilImpact": "زمين تي اثر",
  "app.crops.water.low": "کم",
  "app.crops.water.medium": "درميانو",
  "app.crops.water.high": "وڌيڪ",
  "app.crops.confidence.high": "وڌيڪ",
  "app.crops.confidence.medium": "درميانو",
  "app.crops.confidence.low": "کم",
  "app.crops.confidence.unreliable": "غير يقيني",
  "app.crops.risk.price_volatility": "قيمت جي تبديلي",
  "app.crops.risk.pest_pressure": "حشرات جا خطرن",
  "app.crops.risk.weather": "موسم جو خطرن",
  "app.crops.risk.water_stress": "پاڻي جي تکلیف",
  "app.crops.risk.input_cost": "inputs جي قيمت",
  "app.crops.soilImpact.improves": "زمين بہتر ڪن",
  "app.crops.soilImpact.neutral": "بي طرف",
  "app.crops.soilImpact.depletes": "زمين خراب ڪن",

  /* ── Crops comparison ────────────────────────────────── */
  "app.crops.compare.title": "توهان جا بہترين فصل جي سمپتي",
  "app.crops.compare.close": "سمپتي بند ڪريو",
  "app.crops.compare.revenue": "اندازه آمدنی/acre",
  "app.crops.compare.duration": "وڌن جا ڏينهن",
  "app.crops.compare.water": "پاڻي جي ضرورت",
  "app.crops.compare.marketRisk": "بازاري خطرن",
  "app.crops.compare.soilImpact": "زمين تي اثر",
  "app.crops.compare.labour": " metre جي خرچو",
  "app.crops.compare.chartAria": "٣ بہترين فصلن جي آمدنی جي سمپتي بار چارٽ",
  "app.crops.compare.chartUnavailable": "چارٽ دستياب ناهي — ڌريلو ڏسلي آهي.",
  "app.crops.compare.selectToSave": "saved ڪرڻ لاءِ فصل چونڊيو",
  "app.crops.compare.saveSelected": "منتخب saved ڪريو",

  /* ── Crop rotation ────────────────────────────────────── */
  "app.crops.rotation.title": "فصل جي گردش منصوبو",
  "app.crops.rotation.subtitle": "زمين صحت منflt رکڻ لاءِ اڳيون ڪيا لڳائڻ چاهيئي.",
  "app.crops.rotation.generic": "عام مشورو — عام رسم موجب، نه توهان جي کhet جي تاريخ موجب.",
  "app.crops.rotation.nextSeason": "اڳيون: {season} {year}",
  "app.crops.rotation.savedTitle": "saved منصوبو ۽ گردش",

  /* ── Crops catalogue ──────────────────────────────────── */
  "app.crops.catalogue.empty": "ھن فلٹر سان ڪو فصل مeil نه آهي.",

  /* ── Crops errors ─────────────────────────────────────── */
  "app.crops.errors.serviceUnavailable": "سفارهات جي سروس عارضي طور تي دستياب ناهي. مهرباني ڪري ٻي.",
  "app.crops.errors.generic": "ڪو ٿي. مهرباني ڪري ٻي.",
  "app.crops.errors.notFound": "سفارهات نه مليل.",
  "app.crops.errors.rateLimited": "گھڻي درخواستن. مهرباني ڪري ڪم wait ڪريو.",

  /* ── Crop reasons ─────────────────────────────────────── */
  "app.crops.reason.suitability": "{crop} توهان جي {soil} زمين لاءِ ٻين فصلن مان بہتر لاڳاپو رکن ٿو.",
  "app.crops.reason.weather_fit": "{crop} توهان جي علائقي جي {season} موسم جي پيش گوئي سان مeil آهي.",
  "app.crops.reason.profit": "{crop} توهان جي بجٹ لاءِ وڌيڪ آمدنی پيش ڪن ٿو.",
  "app.crops.reason.rotation_fit": "{crop} توهان جي ڍيني فصلن کان پوءِ اڃي آهي ۽ زمين بني تي.",
  "app.crops.reason.generic": "{crop} توهان جي inputs لاءِ ھن موسم مان پائيدار اختيار آهي.",

  /* ── Rotation benefits ─────────────────────────────────── */
  "app.crops.rotation.wheat_then_mung": "مونگ ویټ کان پوءِ نائتروجن بني تي.",
  "app.crops.rotation.wheat_then_chickpea": "ونگن ویټ کان پوءِ زمين بني تي.",
  "app.crops.rotation.wheat_then_cotton": "ڪاڇو ویټ کان پوءِ عام آهي.",
  "app.crops.rotation.cotton_then_wheat": "ویټ کاڇو کان پوءِ کhet بني تي.",
  "app.crops.rotation.cotton_then_maize": "مکئي کاڇو کان پوءِ اڃي آهي.",
  "app.crops.rotation.rice_then_wheat": "چاول ویټ کان پوءِ عام kharif-to-rabi sequence.",
  "app.crops.rotation.rice_then_maize": "مکئي چاول کان پوءِ باقي پاڻي استعمال ڪن.",
  "app.crops.rotation.maize_then_potato": "آلو مکئي کان پوءِ رميتي زمين تي.",
  "app.crops.rotation.maize_then_wheat": "ویټ مکئي کان پoxideِ گردش پائيدار رکن.",
  "app.crops.rotation.potato_then_maize": "مکئي آلو کان پوءِ اڃي آهي.",
  "app.crops.rotation.sugarcane_then_maize": "مکئي رتين sugarcane کان پوءِ.",
  "app.crops.rotation.mung_then_wheat": "ویټ pulse کان پoxideِ وڌو بني تي.",
  "app.crops.rotation.chickpea_then_cotton": "ڪاڇو legume کان پoxideِ ثابت نائتروجن فائدمند.",
  "app.crops.rotation.mustard_then_cotton": "ڪاڇو mustard oilseed کان پoxideِ.",
  "app.crops.rotation.soybean_then_wheat": "ویټ soybean کان پoxideِ.",
  "app.crops.rotation.onion_then_maize": "مکئي پياز کان پoxideِ حاصلخيز زمين تي.",
  "app.crops.rotation.tomato_then_wheat": "ویټ ٽماٽو کان پoxideِ.",

  /* ── Crop catalogue names ─────────────────────────────── */
  "app.crops.catalogue.barley": "جو",
  "app.crops.catalogue.bajra": "بجرا",
  "app.crops.catalogue.jowar": "جوار",
  "app.crops.catalogue.tobacco": "تمباکو",
  "app.crops.catalogue.sunflower": "سورج مکھي",
  "app.crops.catalogue.canola": "سرسو",
  "app.crops.catalogue.sesame": "تل",
  "app.crops.catalogue.lentil": "مسور",
  "app.crops.catalogue.pigeon_pea": "دوسرا",
  "app.crops.catalogue.black_gram": "ڪالي ڏال",
  "app.crops.catalogue.pea": "مٹر",
  "app.crops.catalogue.cowpea": "لوبيا",
  "app.crops.catalogue.cauliflower": "پھول گوبھي",
  "app.crops.catalogue.cabbage": "بند گوبھي",
  "app.crops.catalogue.brinjal": "بينگن",
  "app.crops.catalogue.okra": "باميا",
  "app.crops.catalogue.chili": "مرچ",
  "app.crops.catalogue.garlic": "لهسن",
  "app.crops.catalogue.ginger": "ادرک",
  "app.crops.catalogue.cucumber": "کيڙا",
  "app.crops.catalogue.watermelon": "ترべوز",
  "app.crops.catalogue.pumpkin": "ڪدو",
  "app.crops.catalogue.carrot": "گاجر",
  "app.crops.catalogue.spinach": "پالڪ",
  "app.crops.catalogue.fenugreek": "شنيبليهه",
  "app.crops.catalogue.mango": "آم",
  "app.crops.catalogue.citrus": "مالٽا",
  "app.crops.catalogue.guava": "ژمي",
  "app.crops.catalogue.apple": "سيب",

  /* ── Additional rotation benefits ─────────────────────── */
  "app.crops.rotation.barley_then_chickpea": "جو ۽ ڇنا گردش جو فائدو",
  "app.crops.rotation.bajra_then_cowpea": "باجرہ ۽ لobia گردش جو فائدو",
  "app.crops.rotation.sunflower_then_wheat": "سورج پھول ۽ ویټ گردش جو فائدو",
  "app.crops.rotation.canola_then_wheat": "کنولا ۽ ویټ گردش جو فائدو",
  "app.crops.rotation.lentil_then_cotton": "مسور ۽ ڪاڇو گردش جو فائدو",
  "app.crops.rotation.pea_then_maize": "مٹر ۽ مکئي گردش جو فائدو",
  "app.crops.rotation.cauliflower_then_pea": "پھول گوبھي ۽ مٹر گردش جو فائدو",
  "app.crops.rotation.okra_then_cowpea": "بھنڊي ۽ لobia گردش جو فائدو",
  "app.crops.rotation.garlic_then_wheat": "لہسن ۽ ویټ گردش جو فائدو",

  /* ── Satellite monitoring ─────────────────────────────── */
  "app.crops.reason.low_risk": "{crop} ڪم خطرو آهي.",
  "app.shell.nav.profitLoss": "Profit / Loss",
  "app.records.noRecordsFound": "No records found for this filter.",
};
