import type { CatalogKey } from "./en.ts";

/** سنڌي — AI-drafted, founder-reviewed copy (plan D4). */
export const sd: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپيو ڇو؟",
  "nav.features": "خاصيتون",
  "nav.howItWorks": "هيءُ ڪيئن ڪم ڪري ٿو",
  "nav.vision": "اسان جو درشھ",
  "nav.signIn": "داخل ٿيءُ",
  "nav.getEarlyAccess": "شروعاتي رسائي حاصل ڪريو",
  "nav.openMenu": "مينيو کوليو",
  "nav.closeMenu": "مينيو بند ڪريو",
  "common.languageSwitcherLabel": "ٻولي مٽايو",
  "notFound.title": "صفحو موجود ناهي",
  "notFound.body": "جيڪو صفحو توهان ڳوليو پئو اهو موجود ناهي يا منتقل ٿي ويو آهي.",
  "notFound.backHome": "واپس اگروپيو گهر ڏانهن",
  "common.builtForPakistan": "پاڪستان لاءِ ٺاهيل",
  "common.productOfAplinode": "اپلينوڊ جي پروڊڪٽ",
  "home.hero.eyebrow": "مصنوعي ذهانت تي ٻڌل فارم ذهانت جو پليٽ فارم",
  "home.hero.titleLead": "هوشيار ٻوڪرائيءَ لاءِ",
  "home.hero.titleAccent": "ذهانت",
  "home.hero.subtitle": "هڪ ئي پليٽ فارم جيڪو اے آئي مشير، سيٽلائٽ مانيٽرنگ، منڊي جون قيمتون ۽ توهان جي فارم جا رڪارڊ هڪ جاءِ تي گڏ ڪري ٿو — ڊيٽا کي صاف فيصلن ۾ بدلين ٿو، توهان جي پنهنجي ٻوليءَ ۾.",
  "home.hero.ctaSecondary": "ڏسو هيءُ ڪيئن ڪم ڪري ٿو",
  "home.hero.imageAlt": "هاري ٻنيءَ ۾ ٽئبليٽ تي اگروپيو استعمال ڪندي",
  "home.hero.readingCrop": "فصل جي صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٽي جي نمي",
  "home.hero.noteExcellent": "بهترين",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "موافق",
  "home.ticker.ariaLabel": "اگروپيو پليٽ فارم جون صلاحيتون",
  "home.ticker.cropDoctor": "اے آئي فصل ڊاڪٽر",
  "home.ticker.satelliteNdvi": "سيٽلائٽ اين ڊي وي آئي مانيٽرنگ",
  "home.ticker.mandiPrices": "منڊي قيمتن جي ڄاڻ",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحون",
  "home.ticker.farmRecords": "ڊجيٽل فارم رڪارڊ",
  "home.ticker.advisoryLanguages": "7 ٻولين ۾ صلاح",
  "home.ticker.pestAlerts": "ڪيڙاڪوپي جي خطري جي اطلاع",
  "home.ticker.offlineSms": "آف لائن سهولت + ايس ايم ايس",
  "home.problem.eyebrow": "مسلو",
  "home.problem.title": "ٻوڪرائيءَ جا فيصلا اندازي جي راند نه هجن گهرجن",
  "home.problem.subtitle": "سمورو پاڪستان ۾ هاري روايت، مقامي صلاحون ۽ کڻيل معلومات سان وڏا فيصلو ڪن ٿا. نقصان لاباريءَ تي ادا ٿيندو آهي.",
  "home.problem.item1Title": "غير يقيني وقت",
  "home.problem.item1Body": "پاڻي، کاڏ، دواءِ، پوک، لاباري — اهم لمحا اڃا اندازي سان طے ٿين ٿا، جيڪي پيداوار گھٽائين ۽ خرچ ضايع ڪن ٿا.",
  "home.problem.item2Title": "وڃيل فارم رڪارڊ",
  "home.problem.item2Body": "موسمن جو علم يادَشتي يا کڻيل نوٽ بڪن ۾ رهندو آهي. پوئلن سال جيڪو ڪم آيو، ان مان هن سال سکندو ڏکيو آهي.",
  "home.problem.item3Title": "کڻيل صلاحون",
  "home.problem.item3Body": "گوانڊي، دڪاندار ۽ ويڊيوز سڀ جواب ڏين ٿا — پر ٿورا ئي هاريءَ جي فصل، مٽي، موسم يا علائقي سان ملن ٿا.",
  "home.problem.kicker": "اندازي جي قيمت لاباريءَ تي ادا ٿيندي آهي",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "توهان جي فارم جي ذهانت،",
  "home.solution.titleB": "هڪ جاءِ تي",
  "home.solution.subtitle": "سمورين موسم لاءِ هڪ ذهانت جو پليٽ فارم — صلاح، رڪارڊ، موسم ۽ بازار توهان جي زمين جي ڊيٽا مان ڪم ڪن ٿا، عام صلاحن مان نه.",
  "home.solution.card1Title": "ڇا ڪرڻو آهي",
  "home.solution.card1Body": "پاڻي، کاڏ، ڪيڙاڪوپي ڪنٽرول ۽ لاباريءَ جي وقت لاءِ ذاتي صلاحون — توهان جي فصل ۽ حالتن مطابق.",
  "home.solution.card1Answer": "هن ٻني، هن هفتي لاءِ صاف صلاح.",
  "home.solution.card2Title": "ڪڍي ڪرڻو آهي",
  "home.solution.card2Body": "موسمي رهنمائي ٻڌائين ٿي ڪم ڪڍي ڪجي، جيئن غلط وقت ۽ اوچان حالتون توهان جي پيداوار نه کائن.",
  "home.solution.card2Answer": "وقت حقيقي موسم ۽ فصل جي واڌ مطابق.",
  "home.solution.card3Title": "ڇا ٿي چڪو آهي",
  "home.solution.card3Body": "هر سرگرمي — پاڻي، ان پُٽ، بيماري، خرچ، لاباري — ترتيب وار رڪارڊ ۾ محفوظ جيڪو هر موسم کي وڌيڪ سمجههدار بڻائي ٿو.",
  "home.solution.card3Answer": "مڪمل تاريخ، هميشہ دستياب.",
};
