import type { CatalogKey } from "./en.ts";

/** سنڌي — AI-drafted, founder-reviewed copy (plan D4). */
export const sd: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپيو ڇو؟",
  "nav.features": "خاصيتون",
  "nav.howItWorks": "هيءُ ڪيئن ڪم ڪري ٿو",
  "nav.vision": "اسان جو درشھ",
  "nav.signIn": "داخل ٿيءُ",
  "nav.getEarlyAccess": "شروعاتي رسائي حاصل ڪريو",
  "nav.openMenu": "مينيو کوليو",
  "nav.closeMenu": "مينيو بند ڪريو",
  "common.languageSwitcherLabel": "ٻولي مٽايو",
  "notFound.title": "صفحو موجود ناهي",
  "notFound.body": "جيڪو صفحو توهان ڳوليو پئو اهو موجود ناهي يا منتقل ٿي ويو آهي.",
  "notFound.backHome": "واپس اگروپيو گهر ڏانهن",
  "common.builtForPakistan": "پاڪستان لاءِ ٺاهيل",
  "common.productOfAplinode": "اپلينوڊ جي پروڊڪٽ",
  "home.hero.eyebrow": "مصنوعي ذهانت تي ٻڌل فارم ذهانت جو پليٽ فارم",
  "home.hero.titleLead": "هوشيار ٻوڪرائيءَ لاءِ",
  "home.hero.titleAccent": "ذهانت",
  "home.hero.subtitle": "هڪ ئي پليٽ فارم جيڪو اے آئي مشير، سيٽلائٽ مانيٽرنگ، منڊي جون قيمتون ۽ توهان جي فارم جا رڪارڊ هڪ جاءِ تي گڏ ڪري ٿو — ڊيٽا کي صاف فيصلن ۾ بدلين ٿو، توهان جي پنهنجي ٻوليءَ ۾.",
  "home.hero.ctaSecondary": "ڏسو هيءُ ڪيئن ڪم ڪري ٿو",
  "home.hero.imageAlt": "هاري ٻنيءَ ۾ ٽئبليٽ تي اگروپيو استعمال ڪندي",
  "home.hero.readingCrop": "فصل جي صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٽي جي نمي",
  "home.hero.noteExcellent": "بهترين",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "موافق",
  "home.ticker.ariaLabel": "اگروپيو پليٽ فارم جون صلاحيتون",
  "home.ticker.cropDoctor": "اے آئي فصل ڊاڪٽر",
  "home.ticker.satelliteNdvi": "سيٽلائٽ اين ڊي وي آئي مانيٽرنگ",
  "home.ticker.mandiPrices": "منڊي قيمتن جي ڄاڻ",
  "home.ticker.weatherAdvisories": "موسم مطابق صلاحون",
  "home.ticker.farmRecords": "ڊجيٽل فارم رڪارڊ",
  "home.ticker.advisoryLanguages": "7 ٻولين ۾ صلاح",
  "home.ticker.pestAlerts": "ڪيڙاڪوپي جي خطري جي اطلاع",
  "home.ticker.offlineSms": "آف لائن سهولت + ايس ايم ايس",
  "home.problem.eyebrow": "مسلو",
  "home.problem.title": "ٻوڪرائيءَ جا فيصلا اندازي جي راند نه هجن گهرجن",
  "home.problem.subtitle": "سمورو پاڪستان ۾ هاري روايت، مقامي صلاحون ۽ کڻيل معلومات سان وڏا فيصلو ڪن ٿا. نقصان لاباريءَ تي ادا ٿيندو آهي.",
  "home.problem.item1Title": "غير يقيني وقت",
  "home.problem.item1Body": "پاڻي، کاڏ، دواءِ، پوک، لاباري — اهم لمحا اڃا اندازي سان طے ٿين ٿا، جيڪي پيداوار گھٽائين ۽ خرچ ضايع ڪن ٿا.",
  "home.problem.item2Title": "وڃيل فارم رڪارڊ",
  "home.problem.item2Body": "موسمن جو علم يادَشتي يا کڻيل نوٽ بڪن ۾ رهندو آهي. پوئلن سال جيڪو ڪم آيو، ان مان هن سال سکندو ڏکيو آهي.",
  "home.problem.item3Title": "کڻيل صلاحون",
  "home.problem.item3Body": "گوانڊي، دڪاندار ۽ ويڊيوز سڀ جواب ڏين ٿا — پر ٿورا ئي هاريءَ جي فصل، مٽي، موسم يا علائقي سان ملن ٿا.",
  "home.problem.kicker": "اندازي جي قيمت لاباريءَ تي ادا ٿيندي آهي",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "توهان جي فارم جي ذهانت،",
  "home.solution.titleB": "هڪ جاءِ تي",
  "home.solution.subtitle": "سمورين موسم لاءِ هڪ ذهانت جو پليٽ فارم — صلاح، رڪارڊ، موسم ۽ بازار توهان جي زمين جي ڊيٽا مان ڪم ڪن ٿا، عام صلاحن مان نه.",
  "home.solution.card1Title": "ڇا ڪرڻو آهي",
  "home.solution.card1Body": "پاڻي، کاڏ، ڪيڙاڪوپي ڪنٽرول ۽ لاباريءَ جي وقت لاءِ ذاتي صلاحون — توهان جي فصل ۽ حالتن مطابق.",
  "home.solution.card1Answer": "هن ٻني، هن هفتي لاءِ صاف صلاح.",
  "home.solution.card2Title": "ڪڍي ڪرڻو آهي",
  "home.solution.card2Body": "موسمي رهنمائي ٻڌائين ٿي ڪم ڪڍي ڪجي، جيئن غلط وقت ۽ اوچان حالتون توهان جي پيداوار نه کائن.",
  "home.solution.card2Answer": "وقت حقيقي موسم ۽ فصل جي واڌ مطابق.",
  "home.solution.card3Title": "ڇا ٿي چڪو آهي",
  "home.solution.card3Body": "هر سرگرمي — پاڻي، ان پُٽ، بيماري، خرچ، لاباري — ترتيب وار رڪارڊ ۾ محفوظ جيڪو هر موسم کي وڌيڪ سمجههدار بڻائي ٿو.",
  "home.solution.card3Answer": "مڪمل تاريخ، هميشہ دستياب.",
  "home.features.eyebrow": "پليٽ فارم جي اندر",
  "home.features.titleA": "ڪيترائي انجن،",
  "home.features.titleB": "هڪ ذهين پليٽ فارم",
  "home.features.subtitle": "توهان جي پنهنجن لفظن ۾ پهرين سوال کان سموري موسم جي رڪارڊ تائين — هر صلاحيت ايٻي کي طاقت ڏئي ٿي.",
  "home.features.advisorModule": "ماڊيول 01 · مشير",
  "home.features.advisorTitle": "اے آئي زرعي مشير",
  "home.features.advisorTopics": "پاڻي · کاڏ · کيڙا ۽ بيماري · لاباري",
  "home.features.advisorBadge": "رومن سنڌي",
  "home.features.advisorMockAria": "پيلن پنن واري ڪڻڪ تي اگروپيو مشير سان نموني گفتگو",
  "home.features.advisorUserMsg": "مونڙي ڪڻڪ جا پنا پيلا ٿي رهيا آهن — ڇا ڪران؟",
  "home.features.advisorReplyTitle": "پيلا پنا — ٻه عام سبب:",
  "home.features.advisorReplyCause1": "پاڻي جي کوٽ",
  "home.features.advisorReplyCause1Rest": "— ٿڌي وقت ۾، صبح 9 وڳي کان اڳ پاڻي ڏيو.",
  "home.features.advisorReplyCause2": "نائٽروجن جي کوٽ",
  "home.features.advisorReplyCause2Rest": "— سڀ کان پراڻا پنا پهرين ڏسو؛ ضرورت هجي تہ يوريا وجو.",
  "home.features.advisorReplyFooter": "جيڪڏهن پنن جي هيٺان پيلا دھاريون نظر اچن، تصوير موڪليو — مان بيماري جي تشخيص ڪري ڏيندس۔",
  "home.features.advisorInputPlaceholder": "پنهنجو سوال لکو يا چيو…",
  "home.features.advisorFooter": "پنهنجي فصل بابت ڪجهه بھي پڇو — روزمره سوالن جوڀن آهي۔",
  "home.features.recordsModule": "ماڊيول 02 · رڪارڈ",
  "home.features.recordsTitle": "ڊجيٽل فارم رڪارڈ",
  "home.features.recordsDesc": "هر سرگرمي ترتيب سان درج — تہ جيئن صلاح توهان جي پنهنجي زمين مان سکندو۔",
  "home.features.record1Activity": "پاڻي",
  "home.features.record1Detail": "نهرو · 40 منٹ",
  "home.features.record2Activity": "يوريا 46% N",
  "home.features.record2Detail": "25 ڪلو / ايڪڙ",
  "home.features.record3Activity": "پنن جو اسڪين",
  "home.features.record3Detail": "ڪا بيماري ناهي",
  "home.features.recordsCropTag": "ڪڻڪ · ربيع سيزن",
  "home.features.languageModule": "ماڊيول 03 · ٻولي",
  "home.features.languageTitle": "توهان جي ٻولي، توهان جا لفظ",
  "home.features.languageDesc": "جيئن سوچيو تيئن چئو يا لکو — تکنيكي انگريزي جي ضرورت ناهي۔",
  "home.features.weatherModule": "ماڊيول 04 · موسم",
  "home.features.weatherTitle": "موسم کان واقف رهنمائي",
  "home.features.weatherDesc": "صلاح توهان تائين پهچڻ کان اڳ حقيقي حالت چڪاسي ٿي — mينهوان اڳ اسپري ڪري ويٺو تہ سارو کاڏ وڃي ويندو۔",
  "home.features.weatherMockAria": "پنج ڏينهن جي اڳڪٿي جنهن ۾ خميس کي اسپري نه ڪرڻ جي صلاح ظاهر آهي",
  "home.features.dayMon": "سومر",
  "home.features.dayTue": "اڱارو",
  "home.features.dayWed": "اربع",
  "home.features.dayThu": "خميس",
  "home.features.dayFri": "جمعو",
  "home.features.holdSpray": "اسپري بند ڪريو",
  "home.features.weatherLegend": "مقامي موسم جي اڳڪٿي مان صلاح وارو ڏينهن ظاهر",
  "home.features.moreLink": "پليٽ فارم مسلسل وڌي رهيو آهي — سموريون صلاحيتون ڏسو",
  "home.journey.eyebrow": "هيءُ ڪيئن ڪم ڪري ٿو",
  "home.journey.title": "هڪ سوال موسم جي شروعات ڪري ٿو",
  "home.journey.subtitle": "توهان جي پهرين سوال کان مڪمل، ذهين فارم تاريخ تائين ساده رستو۔",
  "home.journey.step1Title": "پنهنجو فارم شامل ڪريو",
  "home.journey.step1Body": "ڊجيٽل فارم پروفائل ٺاهڻ لاءِ مقام، فصل ۽ بنيادي تفصيلون داخل ڪريو۔",
  "home.journey.step2Title": "اے آئي کان پڇو",
  "home.journey.step2Body": "پنهنجو سوال اها ٻولي لکو يا چئو جنهن ۾ توهان سڀ کان وڌيڪ آرامده آهيو۔",
  "home.journey.step3Title": "رهنمائي حاصل ڪريو",
  "home.journey.step3Body": "پنهنجي فصل، موسم، مقام ۽ فارم تاريخ تي ٻڌل صلاح حاصل ڪريو۔",
  "home.journey.step4Title": "سرگرمي درج ڪريو",
  "home.journey.step4Body": "ٿورن ٽيپن ۾ پاڻي، کاڏ، دواءِ يا بيماري درج ڪريو۔",
  "home.journey.step5Title": "تاريخ ٺاهيو",
  "home.journey.step5Body": "هر رڪارڈ اڳتي هلي صلاحن کي وڌيڪ سمجههدار ۽ موزون بڻائي ٿو۔",
  "home.journey.step6Title": "نگراني جاري رکو",
  "home.journey.step6Body": "سموري موسم ۾ رڪارڈ ڏسو ۽ پيش رفت تي نظر رکو۔",
  "home.matrix.eyebrow": "سموريون صلاحيتون",
  "home.matrix.title": "ضروري کان حيران ڪندڙ تائين",
  "home.matrix.subtitle": "هر خاصيت فصل بچائي ٿي، خرچ گھٽائي ٿي يا آمدني وڌائي ٿي. ان کي پنجنگ جيئن پڙهو — هر درجو اڳوڻي تي ٺهيل آهي۔",
  "home.matrix.capabilitiesLabel": "صلاحيتون",
  "home.matrix.tier1Name": "بنيادي",
  "home.matrix.tier1Badge": "بنيادي سطح",
  "home.matrix.t1f1Title": "اے آئي فصل بيماري جي سڃاڻ",
  "home.matrix.t1f1Body": "متاثر ٿيل پني جي تصوير اپلوڊ ڪريو ۽ فوري تشخيص، شدت ۽ علاج جون سفارشون حاصل ڪريو۔",
  "home.matrix.t1f2Title": "سيٽلائٽ ٻني نگاري",
  "home.matrix.t1f2Body": "پنهنجي ٻني جي حد نشان لڳايو ۽ مفت سينٽينل-2 تصويرن مان اين ڊي وي آئي مبني فصل جي صحت ڏسو۔",
  "home.matrix.t1f3Title": "هوشيار موسمي صلاح",
  "home.matrix.t1f3Body": "مقامي موسم جي اڳڪٿي توهان جي فصل ۽ واڌ جي مرحلي سان ملائي روزانہ قابلِ عمل صلاح بڻجي ٿي۔",
  "home.matrix.t1f4Title": "منڊي قيمت ٽريڪر ۽ اڳڪٿي",
  "home.matrix.t1f4Body": "ويجهين منڊين جون قيمتون اے آئي رجحانن سان ڏسو، تہ جيئن صحيح وقت تي وڪڻو۔",
  "home.matrix.tier2Name": "امتيازي خاصيتون",
  "home.matrix.tier2Badge": "نمايان",
  "home.matrix.t2f1Title": "علاقائي ٻولين ۾ وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابي، سرائیكي سميت بولو يا لکو — جواب اها ٻولي ٻڌو جيڪا توهان بهتر سمجهو۔",
  "home.matrix.t2f2Title": "سرڪاري اسكيم ميچر",
  "home.matrix.t2f2Body": "پنهنجيون تفصيلون داخل ڪريو ۽ هر اهل اسكيم ڳوليو — دستاويزن ۽ درخواست لنڪن سميت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": "هن موسم ۾ توهان جي مٽي، موسم، منڊي جي طلب ۽ بجٽ مطابق سڀ کان وڌيڪ منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان ڪيلڪوليٽر",
  "home.matrix.t2f4Body": "متوقع ۽ حقيقي خرچ، پيداوار، آمدني ۽ نفع — بريك ايون ۽ آر او آئي سان۔",
  "home.matrix.t2f5Title": "ڪميونٽي فورم ۽ ماهر رابطو",
  "home.matrix.t2f5Body": "سوال پوسٽ ڪريو، تصويرون شيئر ڪريو، ساٿي هارين ۽ تصديق ٿيل ماهرن کان جواب وٺو۔",
  "home.matrix.tier3Name": "حيران ڪندڙ",
  "home.matrix.tier3Badge": "سڀني کان اڳيان",
  "home.matrix.t3f1Title": "سيٽلائٽ تبديلي جو مشاهدو",
  "home.matrix.t3f1Body": "سلائیڊر سان وقت سان سيٽلائٽ تصويرن جو مقابلو ڪريو — واڌ، نقصان يا قبضو ٽريڪ ڪريو۔",
  "home.matrix.t3f2Title": "اے آئي ڪيڙا خطري جي اڳڪٿي",
  "home.matrix.t3f2Body": "موسم، فصل جي مرحلي ۽ تاريخ جي بنياد تي ممڪن حملي کان اڳ ابتدائي خبرداري۔",
  "home.matrix.t3f3Title": "وائس فون ڪال موڊ",
  "home.matrix.t3f3Body": "ٽول فري نمبر تي ڪال ڪريو، سوال چئو، پنهنجي ٻوليءَ ۾ صلاح ٻڌو — اسمارٽ فون جي ضرورت ناهي۔",
  "home.matrix.t3f4Title": "ڪاربن ڪريڊٽ اندازو",
  "home.matrix.t3f4Body": "پائيدار طريقا درج ڪريو ۽ رضاکارانه مارڪيٽن مان ڪاربن ڪريڊٽ جو اندازو لڳايو۔",
  "home.matrix.t3f5Title": "آف لائن پي ڊبليو اے + ايس ايم ايس",
  "home.matrix.t3f5Body": "ٻنيءَ ۾ آف لائن ڪم ڪري، ڪنيڪشن تي سنڪ ٿيوي، ڪمزور نيٽ تي ايس ايم ايس خبر ڏئي۔",
  "home.vision.eyebrow": "ڏسن",
  "home.vision.titleA": "پاڪستان لاءِ ٺاهيو ويو.",
  "home.vision.titleB": "دنيا لاءِ تيار.",
  "home.vision.pkTitle": "پهرين پاڪستان وارو طريقو",
  "home.vision.pkBody": "پهريون ورژن پاڪستان جي ٻنين لاءِ ٺاهيو ويو آهي: مقامي فصلون، علائقائي ٻوليون، حقيقي هاريءَ جا طريقا ۽ حقيقي ٻنيءَ جون حالتون۔",
  "home.vision.pkPoint1": "مقامي فصل ۽ آبهوا جو علم",
  "home.vision.pkPoint2": "اردو، پنجابي، پشتو، سنڌي، سرائیڪي، بلوچي، هندڪو",
  "home.vision.pkPoint3": "حقيقي هارين جي راءَ ذريعي بھتر ٿيل",
  "home.vision.worldTitle": "عالمي واڌ جو ڏسن",
  "home.vision.worldBody": "موافقت لاءِ ٺاهيو ويو. جيئن ئي پليٽ فارم پختو ٿيندو، نئين ملڪن، ٻولين، فصلن ۽ آبهوائن تائين پکڙندو — شروع کان ٻيهر ٺاهڻ کان سواءِ۔",
  "home.vision.worldPoint1": "ملڪ مطابق زرعي علم",
  "home.vision.worldPoint2": "إضافي ٻوليون ۽ مقامي فصلون",
  "home.vision.worldPoint3": "اونهائي ڊيٽا ڳنڍڻا ۽ تجزيا",
  "home.users.title1": "انفرادي هاري",
  "home.users.desc1": "ننڍا ۽ وچولي درجي جا ٻني جن کي عملي رهنمائي ۽ هر سرگرمي جو منظم رڪارڈ گهرجي۔",
  "home.users.title2": "تجارتي ٻني",
  "home.users.desc2": "زرعي ڪاروبار جن کي ترتيب سان معلومات، فيصلي ۾ مدد ۽ ٽيم جا رڪارڈ گهرجن۔",
  "home.users.title3": "ايڪو سسٽم ڀائيوار",
  "home.users.desc3": "ان پٽ سپلائر، ڪوآپريٽو، بيمه ۽ واڌ سروسون جي وقت سان پليٽ فارم سان گڏجنديون۔",
  "home.users.tagline": "پهرين هارين لاءِ ٺاهيو ويو — ايڪو سسٹم سان وڌندو",
  "home.cta.eyebrow": "شروعاتي رسائي",
  "home.cta.title": "پنهنجي ٻني پليٽ فارم تي آڻيو",
  "home.cta.subtitle": "اگروپيو سان بهتر فيصلا ڪندڙ هارين ۾ شامل ٿيو — پاڪستان کان شروعات، دنيا ۾ واڌ۔",
  "home.cta.success": "توهان فهرست ۾ آهيو. جڏهن توهان جو علائقو کُليندو ته اسين رابطو ڪنداسين۔",
  "home.cta.emailLabel": "اي ميل پتو",
  "home.cta.fineprint": "ڪوبه اسپيم نہيان۔ ڪنهن به وقت ان سبسڪرائب ڪريو۔",
  "home.footer.tagline": "اے آئي واري ٻنيءَ جي ذهانت جو پليٽ فارم. مشورو، سيٽلائٽ نگراني، منڊي جون قيمتون ۽ رڪارڈ — مٽي ۽ سگنل، گڏ۔",
  "home.footer.pagesHeading": "صفحا",
  "home.footer.pagesNavLabel": "فوٽر صفحا",
  "home.footer.legalHeading": "قانوني",
  "home.footer.legalNavLabel": "قانوني",
  "home.footer.privacy": "پرائيويسي پاليسي",
  "home.footer.terms": "سروس جون شرطون",
  "home.footer.cookies": "ڪوڪي پاليسي",
  "home.footer.disclaimer": "ڊسڪليمر",
  "home.footer.contactHeading": "رابطو ڪريو",
  "home.footer.country": "پاڪستان",
  "home.footer.copyright": "© {year} اگروپيو۔ سڀ حق محفوظ آهن۔",
  "home.footer.motto": "پاڪستان لاءِ ٺاهيو · دنيا لاءِ تيار",
  "hiw.meta.title": "هي ڪيئن ڪم ڪري ٿو — اگروپيو",
  "hiw.meta.description":
    "هڪ منٽ جي ٻنيءَ جي پروفائل کان مسلسل بھتر ٿيندڙ موسمي چڪر تائين: ڏسو ته اگروپيو سوالن، سرگرمين ۽ رڪارڈ کيں ذاتی زرعي رهنمائي ڪيئن ٺاهي ٿو.",
  "hiw.hero.eyebrow": "هي ڪيئن ڪم ڪري ٿو",
  "hiw.hero.titleA": "ڇهہ ننڍا مرحلا۔",
  "hiw.hero.titleLead": "هڪ",
  "hiw.hero.titleAccent": "وڌيڪ سمجھدار موسم۔",
  "hiw.hero.subtitle":
    "اگروپيو انهيءَ طرح ڪم ڪري ٿو جيئن هاريءَ جو ڪم پهرين کان هلندو آهي — توهان پوکبو، پڇندؤ، ڪم ڪندؤ ۽ رڪارڈ ڪندؤ. فرق رڳو اهو آهي تہ هاڻي هر مرحلو ايندڙ کي سکائي ٿو.",
  "hiw.hero.browseFeatures": "خاصيتون ڏسو",
  "hiw.route.navLabel": "اگروپيو جي موسمي چڪر جا ڇهہ مرحلا",
  "hiw.route.stepLabel": "مرحو {n}: {stop}",
  "hiw.route.stop1": "ٻني ٺاهيو",
  "hiw.route.stop2": "پڇو",
  "hiw.route.stop3": "رهنمائي",
  "hiw.route.stop4": "ڪم ڪريو",
  "hiw.route.stop5": "ريڪارڈ",
  "hiw.route.stop6": "بھتر مشورو",
  "hiw.setup.eyebrow": "هڪ دفعي سيٽ اپ ڪريو",
  "hiw.setup.title": "توهان جي ٻني هڪ جيوندڙ پروفائل بڻجي وڃي ٿو",
  "hiw.setup.body":
    "چار خانا، هڪ منٽ کان گهٽ — ضلعو، فصل، پوک جي تاريخ ۽ زمين جي ايراضي. هيءو سڄو فارم آهي. ان کان پوءِ هر جواب ڄاڻي ٿو تہ هي ڪٿي ۽ ڪهڙين حالتن ۾ اگھي رهيو آهي.",
  "hiw.setup.point1": "فصل مٽايو يا ڪنهن به وقت ٻنيون شامل ڪريو",
  "hiw.setup.point2": "ٺيڪيدارن ۽ ڊيلرن لاءِ ڪيتريون ئي ٻنيون",
  "hiw.setup.point3": "ڪوبه ٽيڪنيڪل نه پڇيو ويندو — مٽيءَ جي رپورٽ جي ضرورت ناهي",
  "hiw.setup.mockHeading": "نئون ٻني پروفائل",
  "hiw.setup.mockButton": "ٻني پروفائل ٺاهيو",
  "hiw.setup.mockFootnote": "هڪ منٽ کان گهٽ لڳندو آهي",
  "hiw.setup.mockLabel":
    "ٻني پروفائل فارم جنهن ۾ ضلعو، فصل، پوک جي تاريخ ۽ زمين جي ايراضي ڀريل آهي",
  "hiw.setup.rowDistrict": "ضلعو",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گھُن · ربيع",
  "hiw.setup.rowSowing": "پوک جي تاريخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "زمين",
  "hiw.setup.valLand": "۱۲ ايڪڙ",
  "hiw.ask.eyebrow": "جو دل چاهي پڇو",
  "hiw.ask.titleA": "هڪ سوال وڃي ٿو۔",
  "hiw.ask.titleB": "توهان جي سموري ٻني جواب ڏئي ٿي۔",
  "hiw.ask.body":
    "هڪ ئي سوال مختلف ٻنين تي مختلف مطلب رکي ٿو. تنهنڪري جواب ڏيڻ کان اڳ اگروپيو سوال کي توهان جي ٻنيءَ بابت ڄاڻايل هر شيءِ سان ملي ڪري ڏسندو آهي.",
  "hiw.ask.pipelineLabel":
    "هاريءَ جي سوال کي فصل، ضلعو، آبهوا ۽ تاريخ جي تناظر سان گڏي ڪري ذاتی جواب ٺاهيو ويندو آهي",
  "hiw.ask.question": "هاڻي پاڻي ڏيڻ گهرجي يا ٿورو انتظار؟",
  "hiw.ask.checkedAgainst": "انهن شين سان ملي ڪري",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گھُن · ڦٽ نڪرڻ جو وقت",
  "hiw.ask.chipDistrict": "ضلعو",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "آبهوا",
  "hiw.ask.chipValWeather": "26° • خشڪ هفتو",
  "hiw.ask.chipHistory": "تاريخچو",
  "hiw.ask.chipValHistory": "يوريا 9 ڏينهن اڳ",
  "hiw.ask.answer":
    "ٻہ ڏينهن رهجو — مينهن جو امڪان آهي، ۽ يوريا کان پوءِ زمين اڃا کليل آهي. جمعي تائين ڏسڻ ڪافي آهي.",
  "hiw.ask.answerMeta": "ذاتی جواب • گھُن، يوريا کان 9 ڏينهن پوءِ",
  "hiw.ask.footnote": "لکو، چئو يا ڪال ڪريو — جواب هر صورت ۾ توهان جي ٻنيءَ جو پنهنجو هوندو آهي",
  "hiw.engine.eyebrow": "جواب جي پويان",
  "hiw.engine.title": "چار جانچون ان کان اڳ جو توهان هڪ سطر ڏسو",
  "hiw.engine.body":
    "رهنمائي ڪا سرچ نتيجو ناهي. هي چار دروازن مان گذري ٿو تہ جيڪو توهان تائين پهچي سو انهيءَ ٻنيءَ لاءِ، انهيءَ هفتي لاءِ محفوظ هجي.",
  "hiw.engine.check1Title": "معلومات گڏ ڪرڻ",
  "hiw.engine.check1Desc":
    "ٻني پروفائل، موجودو آبهوا ۽ فصل جو مرحلو موڪلڻ جي لمحي سان گڏ گڏ ڪيا ويندا آهن.",
  "hiw.engine.check2Title": "ميل جي جانچ",
  "hiw.engine.check2Desc":
    "مشورو آبهوا جي اڳڪٿي سان پرکيو ويندو آهي — مينهن ۾ بيڪار ٿيندڙ سپرے انجن مان نڪتو ئي نه آهي.",
  "hiw.engine.check3Title": "ذاتی بناؤڻ",
  "hiw.engine.check3Desc":
    "توهان جي ٻنيءَ جي تاريخ جواب بدلائي ٿي — ساڳي فصل، الڳ مٽي، الڳ مشورو.",
  "hiw.engine.check4Title": "پهچائڻ",
  "hiw.engine.check4Desc":
    "پوءِ سو توهان جي ٻوليءَ ۾ صاف قدم بڻجي اچي ٿو — اسکرين تي، آواز ۾ يا فون ڪال تي.",
  "hiw.engine.safetyStrong": "جيڪڏهن ڪجهه غير محفوظ لڳے،",
  "hiw.engine.safetyRest":
    "ته اگروپيو انتظار جو چوي ٿو — دير سان ملندڙ جواب بيڪار ٿيل سپرے يا تباهه فصل کان بھتر آهي.",
  "hiw.record.recorderHeading": "سرگرمي درج ڪريو",
  "hiw.record.syncBadge": "خودڪار سنڪ آن",
  "hiw.record.actionIrrigation": "پاڻي ڏيڻ",
  "hiw.record.actionFertiliser": "کاڌ",
  "hiw.record.actionPesticide": "ڪيري مار",
  "hiw.record.actionDisease": "بيماري",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل لهڻ",
  "hiw.record.row1Time": "اڄ • صبح 6:40",
  "hiw.record.row1Label": "پاڻي ڏيڻ درج ٿيو",
  "hiw.record.row1Detail": "نهر جو موڑ • 40 منٹ • پلاٽ B",
  "hiw.record.row2Time": "ڪالهه",
  "hiw.record.row2Label": "کاڌ درج ٿي",
  "hiw.record.row2Detail": "DAP 20 ڪلو / ايڪڙ",
  "hiw.record.offlineNote": "→ هر اندراج رڳو ٻہ ٽيپ — آف لائن به هلندو آهي",
  "hiw.record.mockLabel":
    "سرگرمي رڪارڈر جنهن ۾ فوري اڪشن چپس ۽ تازو درج ٿيل اندراج آهن",
  "hiw.record.eyebrow": "جيئن جيئن ڪم ڪريو، رڪارڈ ڪندا وڃو",
  "hiw.record.titleA": "هاڻي ٻہ ٽيپ،",
  "hiw.record.titleB": "سموري موسم بھتر جواب",
  "hiw.record.body":
    "ريڪارڈنگ ٻنيءَ لاءِ ٺاهي وئي آهي — وڏا بٽڻ، گهٽ خانا، ٽائيپنگ جي ضرورت ناهي. هر اندراج ٻنيءَ جي ياداشت جو حصو بڻجي ٿو، تنهنڪري مشورو به فصل سان گڏ تکو ٿيندو ويندو آهي.",
  "hiw.record.point1": "پاڻي، کاڌا، بيماريون، خرچ، فصل — سڀ هڪ ٽائم لائن تي",
  "hiw.record.point2": "مڪمل طور تي آف لائن هلندو آهي؛ سگنل اچي تي خودڪار سنڪ ٿي ويندو آهي",
  "hiw.record.point3": "بينڪ، خريدار يا بيمي لاءِ موسمي خلاصو تيار",
  "hiw.loop.eyebrow": "موسمي چڪر",
  "hiw.loop.titleA": "هي فصل لهڻ تي ختم نه ٿيندو آهي۔",
  "hiw.loop.titleB": "اتان کان شروع ٿيندو آهي۔",
  "hiw.loop.body":
    "پڇو، ڪم ڪريو، رڪارڈ ڪريو — ورجائيو. چڪر جي هر چڪ اگروپيو کي توهان جي زمين بابت نئون ڪجهه سکائي ٿو، تہ ايندڙ موسم پوئتي موسم کان اڳتي شروع ٿئي.",
  "hiw.loop.benefit1Title": "مشورو سودو ڪمائندو آهي",
  "hiw.loop.benefit1Desc":
    "پوئتي موسم جون بيماريون، خوراڪون ۽ تاريخون هن موسم جو پهريون جواب ٺاهين ٿيون.",
  "hiw.loop.benefit2Title": "ڪجهه به ورجائڻ نه پوي ٿو",
  "hiw.loop.benefit2Desc":
    "مشاورت ڄاڻي ٿي تہ ڇا اڳ ۾ ئي سپرے يا کاڌ ٿي چڪو آهي — ٻيڻي خوراک جو خطرو ناهي.",
  "hiw.loop.benefit3Title": "هر موسم دستاويزي",
  "hiw.loop.benefit3Desc":
    "صاف تاريخ قرضن، خريدارن، بيمي يا ايندڙ فصل جي فيصلي لاءِ تيار رهي ٿي.",
    "hiw.loop.stepLearn": "سکھو",
  "hiw.loop.stepImprove": "بھتر ڪريو",
  "hiw.loop.diagramLabel": "گول چڪر خاڪو: پڇو، ڪم ڪريو، رڪارڈ ڪريو، سکو، بھتر ڪريو",
  "hiw.loop.centerSeason": "موسم",
  "hiw.loop.centerLoop": "چڪر",
  "hiw.loop.caption": "هر موسم، پوئتي کان بھتر",
  "feat.meta.title": "خاصيتون — اگروپيو",
  "feat.meta.description": "اگروپيو جي هر خاصيت ڏسو: اے آءِ فصل ڊاڪٽر، سيٽلائيٽ NDVI نگراني، منڍي قيمت اڳڪٿي، مقامي ٻولين ۾ آوازي صلاح، آف لائن رسائي ۽ ايس ايم ايس خبرداري، ۽ گھڻو ڪجهه.",
  "feat.hero.eyebrow": "خاصيتون",
  "feat.hero.titleLead": "توھان جي موسم جي هر",
  "feat.hero.titleAccent": "گهرج پوري",
  "feat.hero.subtitle": "چوڏه خاصيتون گڏجي ڪم ڪن ٿيون — پنن کي سڪين ڪن ٿيون، خلا مان ڪڙو ڏسن ٿيون، منڍي پڙهن ٿيون ۽ توھان جي ٻولي ڳالھين ٿيون. ڏسو هر هڪ توھان جي فارم لاءِ ڇا ڪري ٿي.",
  "feat.hero.ctaPrimary": "شروعاتي رسائي حاصل ڪريو",
  "feat.hero.ctaSecondary": "اهو ڪيئن هل ٿو ڏسو",
  "feat.hero.builtFor": "پاڪستان لاءِ ٺاهيو ويو",
  "feat.hero.productOf": "Aplinode جي پيداوار",
  "feat.hero.tile1Label": "پن سڪين",
  "feat.hero.tile1Value": "94% صحتمند",
  "feat.hero.tile2Label": "منڍي ڪڻڪ",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI ڪڙو",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "ڪيڙي جو خطرو",
  "feat.hero.tile4Value": "گهٽ · 7 ڏينهن",
  "feat.hero.voiceReady": "آوازي صلاح تيار",
  "feat.hero.voiceLangs": "اردو · پنجابي · سرائیڪي",
  "feat.hero.liveBadge": "لائيو",
  "feat.hero.smsLabel": "ايس ايم ايس خبرداري · آف لائن موڊ",
  "feat.hero.smsMsg": "مينھان 3 منجهند — اسپري روڪيو",
  "feat.intel.eyebrow": "فصل جي سمجھ",
  "feat.intel.heading": "مسئلا نقصان کان اڳ ڏسو",
  "feat.intel.sub": "بيماري، ڪيڙا، موسم ۽ فصل جي چونڊ — چار فيصلا جيڪي فصل ٺاهين ٿا، هر هڪ پنهنجي انجن سان.",
  "feat.intel.included": "شامل آهن",
  "feat.intel.doctorCode": "F·01 · ڏيکار",
  "feat.intel.doctorTitle": "اے آءِ فصل ڊاڪٽر",
  "feat.intel.doctorDesc": "متاثر ٿيل پني جي تصوير وٺو ۽ سيڪنڈن ۾ بيماري جو نالو، شدت ۽ علاج جو خاڪو حاصل ڪريو.",
  "feat.intel.doctorMock": "پن سڪين نتيجو جنهن ۾ پيلي زنگ کي وڏي يقين سان تشخيص ڪئي",
  "feat.intel.diseaseName": "پيلو زنگ",
  "feat.intel.matchScore": "94% ملائت",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "وچولي",
  "feat.intel.pestCode": "F·02 · اڳڪٿي",
  "feat.intel.pestTitle": "ڪيڙن جي حملي جون خبردارياں",
  "feat.intel.pestDesc": "موسم ۽ فصل جو مرحلو خطري ماڊل کي کارائي ٿو جيڪو حملي کان هڪ ڏينهن اڳ خبردار ڪري ٿو.",
  "feat.intel.pestMock": "ست ڏينهن جو ڪيڙي خطري چارٽ جيڪو ڇهين ڏينهن مٿاهون ٿي ويندو",
  "feat.intel.pestAlert": "ڇنڇر · ٽڊي دل خطرو 74% — نئين ڪڻڪ بچايو",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم مطابق مشورا",
  "feat.intel.weatherDesc": "مقامي اڳڪٿيون توھان جي فصل ۽ واڌ جي مرحلي سان مليون ٿيون — مشورو صاف رهنمائي ٿي اچي، خام ڊيٽا نه.",
  "feat.intel.weatherMock": "بهترين موسمي مشورو جيڪو مينھان کان اڳ آبپاشي ۾ دير جو چوي",
  "feat.intel.delayIrrigation": "اڄ پاڻي ڏيڻ ۾ دير ڪريو",
  "feat.intel.rainNote": "منجهند 3 وڳي مينھان جو امكان — پهرين اسمان ڪڙو سيراب ڪري.",
  "feat.intel.waterSaved": "پاڻي جي بچت",
  "feat.intel.cropCode": "F·04 · رٿابندي",
  "feat.intel.cropTitle": "فصل جي سفارش",
  "feat.intel.cropDesc": "مٽي، موسم، طلب ۽ توھان جو بجٽ گڏ جانچيا ويندا آهن — اهو پوءِ جيڪو هن موسم نقصان ڏي.",
  "feat.intel.cropMock": "درجا بندي شده فصل سفارشون جن ۾ ڪڻڪ مٿانهين",
  "feat.intel.crop1": "ڪڻڪ",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "ڇنا",
  "feat.field.eyebrow": "ڪڙو ۽ منڍي جي سمجھ",
  "feat.field.headingA": "توھان جي زمين خلا مان ماپي وڃي ٿي.",
  "feat.field.headingB": "توھان جي فصل ڊيٽا سان پرکي وڃي ٿي.",
  "feat.field.sub": "هر ايڪڙ تي سيٽلائيٽ جون نظر ۽ قريب هر منڍي جو جائزو — ته جيئن واڌ ۽ وڪري ٻئي صحيح وقت هجن.",
  "feat.field.ndviCode": "F·05 · سيٽلائيٽ",
  "feat.field.ndviTitle": "NDVI ڪڙو نگراني",
  "feat.field.ndviDesc": "پنهنجي حد هڪ ڀيرو نشان لڳايو؛ هر روشن سيٽلائيٽ گذر تي صحت جا زون اپڊيٽ ٿين ٿا — ڪمزور حصا اک کان اڳ ظاهر ٿين ٿا.",
  "feat.field.ndviMock": "ڪڙي جي صحت گرڊ جنهن ۾ گهارو سائز مضبوط فصل واڌ ڏيکاري",
  "feat.field.weakZone": "ڪمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڍي",
  "feat.field.priceTitle": "منڍي قيمت اڳڪٿي",
  "feat.field.priceDesc": "قريب منڍين جا موجوده ريٽ ۽ رجحان جي اڳڪٿي — تڏهن وڪيو جڏهن گراف چوي، خريدار جڏهن چوي اهو نه.",
  "feat.field.priceMock": "ڪڻڪ قيمت رجحان اٺ هفتين ۾ مٿاهون ڏانهن، روڪي رهڻ جي سفارش سان",
  "feat.field.wheatTrend": "ڪڻڪ · 8 هفتا",
  "feat.field.holdStock": "↑ 12% — مال رکيو",
  "feat.field.financeCode": "F·07 · ماليه",
  "feat.field.financeTitle": "نفع نقصان جوچ",
  "feat.field.financeDesc": "هر روپي اچڻ ۽ وڃڻ جو، پورو موسم — منڍي يا بينڪ وڃڻ کان اڳ بريك اوون ۽ آر او آءِ تيار.",
  "feat.field.ledgerMock": "موسمي خرچ کاتو جنهن ۾ ان پٽ، مزدوري، آبپاشي ۽ آمدني",
  "feat.field.rowInputs": "ان پٽ",
  "feat.field.rowLabour": "مزدوري",
  "feat.field.rowIrrigation": "آبپاشي",
  "feat.field.rowRevenue": "آمدني (اندازي)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سڀني لاءِ رسائي",
  "feat.voice.headingA": "اسمارٽ فون ناهي؟",
  "feat.voice.headingB": "انگريزي نه؟ تڏهن به شامل.",
  "feat.voice.sub": "بهترين مشورو بيڪار آهي جيڪڏهن اهو ڪڙمي تائين پهتو ئي نه. هر خاصيت فون ڪال جواب ڏئي ٿي، آواز ٻڌي ٿي ۽ سگنل ختم علائقي ۾ به هلندي آهي.",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "پنهنجو سوال چيو",
  "feat.voice.speakMock": "رومن سنڌي ۾ صلاح سان آوازي گفتگو",
  "feat.voice.chatUser": "منهنجي فصل جي پنين تي داغ آهن",
  "feat.voice.chatAdvisor": "داغن جي تصوير موڪليو — مان هاڻي تشخيص ڪندان.",
  "feat.voice.inputPlaceholder": "بولي پڇو…",
  "feat.voice.callCode": "F·09 · ڪال",
  "feat.voice.callTitle": "ٽول فري نمبر ڊائل ڪريو",
  "feat.voice.callMock": "اگروپيو آوازي مددگار سان ٽول فري ڪال جي نقل",
  "feat.voice.greetingLine": "اگروپيو ۾ توھان جوڀي آيا",
  "feat.voice.heardLine": "آواز سمجهي ورتي — جواب تيار",
  "feat.voice.callEnded": "ڪال ختم · خلاصو محفوظ",
  "feat.voice.anyPhone": "هر فون تي · انٽرنيٽ جي گهرج ناهي",
  "feat.voice.offlineCode": "F·10 · آف لائن + ايس ايم ايس",
  "feat.voice.offlineTitle": "سگنل ختم علائقا به نه روڪن",
  "feat.voice.offlineDesc": "مشورا، رڪارڊ ۽ ڪيلڪوليٽر بغير سگنل ڪم ڪندا رهن؛ نيٽ ورک موٽڻ تي سڀ سنڪ ٿي ويندا آهن ۽ مهم خبردارياں ايس ايم ايس سان اچن ٿيون.",
  "feat.voice.networkStatus": "نيٽ حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 رڪارڊ قطار ۾",
  "feat.voice.smsStamp": "ايس ايم ايس · 07:42",
  "feat.voice.smsMsg": "موسمي خبرداري: مينھان منجهند 3 وڳي — اسپري جو وقت بدليو.",
  "feat.manage.eyebrow": "سنڀال ۽ واڌ",
  "feat.manage.headingA": "مشورو شروعات آهي.",
  "feat.manage.headingB": "باقي سڀ رڪارڊ تي هل ٿو.",
  "feat.manage.sub": "تاريخ، سبسيڊي، پائيداري ۽ ڪڙمين جي ڪميونٽي — خاموش خاصيتون جيڪي هر موسم گڏ ٿين ٿيون.",
  "feat.manage.diaryCode": "F·11 · رڪارڊ",
  "feat.manage.diaryTitle": "ڊجيٽل فارم ڊائري",
  "feat.manage.diaryDesc": "آبپاشي کان فصل ڪپڻ تائين، سڀ هڪ ٽائم لائين تي جنهن کي مشورو جواب کان اڳ پڙهي ٿو.",
  "feat.manage.timelineMock": "آگسٽ جي فارم سرگرمي ٽائم لائين",
  "feat.manage.tl1Date": "12 آگسٽ",
  "feat.manage.tl1Label": "آبپاشي",
  "feat.manage.tl1Detail": "واھ جي واري · 40 منٽ",
  "feat.manage.tl2Date": "09 آگسٽ",
  "feat.manage.tl2Label": "يوريا پاتو ويو",
  "feat.manage.tl2Detail": "25 ڪلو / ايڪڙ",
  "feat.manage.tl3Date": "02 آگسٽ",
  "feat.manage.tl3Label": "پن سڪين",
  "feat.manage.tl3Detail": "صحتمند · ڪا بيماري ناهي",
  "feat.manage.schemeCode": "F·12 · اسڪيمون",
  "feat.manage.schemeTitle": "سبسيڊي ۽ اسڪيم ڳوليو",
  "feat.manage.schemeDesc": "سرڪاري رقم جنهن جا توھان اڳ ۾ ئي اهل آهيو — لهبايل، سمجھايل ۽ هڪ ٽيپ درخواست لاءِ ڳنڍيل.",
  "feat.manage.checklistMock": "اہليت چيڪ لسٽ جنهن ۾ چارن مان ٽي شرطون مڪمل",
  "feat.manage.check1": "زمين جي تصديق ٿي",
  "feat.manage.check2": "فصل جو موسم مطابقت رکي ٿو",
  "feat.manage.check3": "سڃاڻپ ڪارڊ رجسٽرڊ",
  "feat.manage.check4": "بينڪ اڪائونٽ ڳنڍيو",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تيار",
  "feat.manage.carbonCode": "F·13 · پائيداري",
  "feat.manage.carbonTitle": "سائيز طريقن جا انعام",
  "feat.manage.carbonDesc": "حياتياتي ۽ گهٽ کوهن طريقا درج ڪريو؛ سيٽلائيٽ سائز احاطو تصديق ڪري ٿو ۽ ڪاربن ڪريڊٽ قدر جو اندازو لڳائي ٿو.",
  "feat.manage.carbonMock": "ڪاربن خلاصو جنهن ۾ قبضو ڪيل ٽن ۽ سالاني اندازي قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "ڪريڊٽ قدر / سال",
  "feat.manage.forumCode": "F·14 · ڪميونٽي",
  "feat.manage.forumTitle": "ڪڙمي فورم + ماهر",
  "feat.manage.forumDesc": "مسئلو پوسٽ ڪريو، ان ڪڙمين کان جواب حاصل ڪريو جن پاڻ منهن ڏنو — تصديق ٿيل ماهر درست حل نشان لڳائين ٿا.",
  "feat.manage.threadMock": "ڪميونٽي بحث جنهن ۾ ماهر جي تصديق ٿيل جواب",
  "feat.manage.threadQuestion": "ڪپهه ۾ اڇي مکي جي بهترين علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 ووٽ",
  "feat.manage.expertBadge": "ماهر جي تصديق ٿيل جواب",
  "feat.manage.threadAnswer": "نيم جي تيل جي اسپري، منجهند کان پوءِ — ٻه ڀيرا، 5 ڏينهن جي وقفي سان.",
  "vp.meta.title": "ڏس — اگروپيو",
  "vp.meta.description": "اگروپيو جو ڏس: هر ڪسان جي جيبي ۾ هوشيار زرعي رهنمائي — پاڪستان کان شروعات، پنج يقين، ٽن افق ۽ اهي واعدو جن سان ڪا سمجھوتو ناهي۔",
  "vp.hero.eyebrow": "اسانجو ڏس",
  "vp.hero.titleLead": "هڪ ڀروسي جوڳو مشير",
  "vp.hero.titleAccent": "هر ڪسان جي جيبي ۾.",
  "vp.hero.sub": "هوشيار رهنمائي جو دارومدار دولت، تعليم يا ٻوليءَ تي نه هجڻ گهرجي۔ اگروپيو ان لاءِ آهي ته هر ڪسان — ڪنهن به فون تي، ڪنهن به ڳوٺ ۾ — انهيا يقين سان کڙهي ڪري جيئن ڪو ماهر ساڻن بيٺل هجي۔",
  "vp.hero.tagStart": "پهرين اتي جتي ضرورت وڏي",
  "vp.hero.tagThen": "پوءِ دنيا کٽڻ",
  "vp.hero.ctaLink": "ڏسو اسان ڇا ٺاهيو",
  "vp.beliefs.eyebrow": "اسانجا يقين",
  "vp.beliefs.heading": "پنج يقين هر فيصلي کي روپ ڏين ٿا",
  "vp.beliefs.b1Title": "واڌ",
  "vp.beliefs.b1Desc": "جيوندڙ فصلون، صحتمند ڌرتي، خوشحال ڪسان۔",
  "vp.beliefs.b2Title": "هوشياري",
  "vp.beliefs.b2Desc": "مقامي موسم، تاريخ ۽ فصل سائنس تي ٻڌل اے آءِ۔",
  "vp.beliefs.b3Title": "رسائي",
  "vp.beliefs.b3Desc": "هر ڪسان جي پنهنجي ٻوليءَ ۽ پنهنجي ماحول ۾ رهنمائي۔",
  "vp.beliefs.b4Title": "ڀروسو",
  "vp.beliefs.b4Desc": "عملي، بروقت مشورو جيڪو روزگار جو تحفظ ڪري۔",
  "vp.beliefs.b5Title": "مستقبل",
  "vp.beliefs.b5Desc": "روايت جو احترام ڪندڙ وڌندڙ ٽيڪنالاجي۔",
  "vp.horizons.eyebrow": "اڳيان جو رستو",
  "vp.horizons.heading": "ٽي افق، هڪ رخ",
  "vp.horizons.h1Tag": "افق 01",
  "vp.horizons.h1Phase": "هاڻي",
  "vp.horizons.h1Status": "ٻنين ۾",
  "vp.horizons.h1Body": "سڀ کان پهرين پاڪستان۔ مرڪزي مشير، ڊجيٽل فارم رڪارڊ، موسم جي خبر واري رهنمائي ۽ ڇهه علائقائي ٻوليون — ٻئي ڪنهن شيءِ کان اڳ حقيقي ڪسانن جي راءِ سان پڪيون۔",
  "vp.horizons.h1P1": "مرڪزي مشير + رڪارڊ",
  "vp.horizons.h1P2": "ڇهه ٻوليون",
  "vp.horizons.h1P3": "حقيقي ڪسانن کان بهتري",
  "vp.horizons.h2Tag": "افق 02",
  "vp.horizons.h2Phase": "ايندڙ",
  "vp.horizons.h2Status": "پکڙ",
  "vp.horizons.h2Body": "گهر ۾ کوٽائي ۽ ڦهلاءُ — پاڪستان ۾ وڌيڪ فصلون ۽ علائقا، زرعي ڊيٽا ذريعن سان مضبوط لاڳاپا، ۽ اهڙا تجزيا جيڪي هر سفارشن کي وڌيڪ ذاتي بڻائين۔",
  "vp.horizons.h2P1": "وڌيڪ فصلون ۽ علائقا",
  "vp.horizons.h2P2": "ڊيٽا ڳنڍڻا",
  "vp.horizons.h2P3": "نئين دور جا تجزيا",
  "vp.horizons.h3Tag": "افق 03",
  "vp.horizons.h3Phase": "پوءِ",
  "vp.horizons.h3Status": "عالمگير",
  "vp.horizons.h3Body": "پليٽ فارم نون ملڪن، موسمين، فصلن، ٻولين ۽ طريقن سان پاڻ کي ملي وجهي — دنيا گير سطح تي موافقت واري زرعي هوش، شروعات صفر کان ڪيو بغير۔",
  "vp.horizons.h3P1": "نوان ملڪ",
  "vp.horizons.h3P2": "نيون ٻوليون ۽ موسم",
  "vp.horizons.h3P3": "دنيا گير پليٽ فارم",
  "vp.outcomes.eyebrow": "ڪاميابي جي صورت",
  "vp.outcomes.heading": "چار نتيجا جن تي اسان پاڻ کي توليون ٿا",
  "vp.outcomes.sub": "ڏس ايپ ناهي — ٻنيءَ تي مٽجندڙ حال آهي۔ هر شيءِ ان چار نتيجن جي مقابلي ۾ ٿيندي آهي۔",
  "vp.outcomes.o1Title": "بهتر فيصلا",
  "vp.outcomes.o1Desc": "هر چونڊ — پاڻي، ان پٽ، وقت — عادت جي بدران ڊيٹا تي۔",
  "vp.outcomes.o2Title": "وڌيڪ پيداوار",
  "vp.outcomes.o2Desc": "صحت مند فصلون، وقت تي ان پٽ، ۽ چوٽي تي کنڊايل فصل۔",
  "vp.outcomes.o3Title": "گهٽ بچائي سگهجندڙ نقصان",
  "vp.outcomes.o3Desc": "بيماري، ڪيرا ۽ موسم وقت تي پڪڙيا — فصل وڃائڻ کان اڳ۔",
  "vp.outcomes.o4Title": "فارم ڪاروبار وانگر",
  "vp.outcomes.o4Desc": "ترتيب وار رڪارڊ ۽ موسمي هوشيار جيڪي بينڪ ۽ خريدار مڃين۔",
  "vp.principles.eyebrow": "سمجھوتو ناهي",
  "vp.principles.heading": "اهي واعدو جن تي اسان ٺاهيون ٿا",
  "vp.principles.sub": "ڏس تفصيلن ۾ ناڪام ٿيندو آهي۔ هي واعدو هر خاصيت، هر صفحي، هر رليز تي لاڳو ٿين ٿا — اڄ کان۔",
  "vp.principles.c1Title": "ڪسان جو فائدو مقدم",
  "vp.principles.c1Desc": "هر خاصيت ٻنيءَ جي ضرورت کان شروع ٿيندي آهي — ڪڏهن به ٽيڪنالاجي کان نه۔",
  "vp.principles.c2Title": "ٻولي پهرين",
  "vp.principles.c2Desc": "هر اسڪرين ۽ هر جواب ڪسان جي پنهنجي ٻوليءَ ۾ پهچندو آهي۔",
  "vp.principles.c3Title": "سج ۾ پڙهڻ جوڳو",
  "vp.principles.c3Desc": "گهاڙو کنٽراسٽ دوپهر جي سج لاءِ، رڳو آفيس لاءِ نه۔",
  "vp.principles.c4Title": "سادا لفظ",
  "vp.principles.c4Desc": "ايترا سادا جو هڪ پاڙيسري ٻئي کي سمجائي سگهي۔",
  "vp.principles.c5Title": "پهرين فون",
  "vp.principles.c5Desc": "موبائل پهرين، وڏا ٽچ نشان — هاڻ ٻني فون تي ئي هليندي آهي۔",
  "vp.principles.c6Title": "انداز ۾ قدرتي",
  "vp.principles.c6Desc": "هلت ۽ ترتيب جيڪي فطري لڳن — واڌ، ڪڏهن به مشينري نه۔",
  "vp.principles.motto": "مٽي ۽ سگنل — گڏ گڏ",
  "wy.meta.title": "اگروپيو ڇو — اے آئي وارو فارم ذهنيت",
  "wy.meta.description": "ٻجڻ جا فيصلا اندازن تي نه ڇڏيا وڃن. ڏسو اگروپيو ڪيئن اے آئي مشير، فارم رڪارڊ، موسم جي آگاهي واري هدايت ۽ مقامي ٻوليون هڪ پاڪستان اول پليٽ فارم تي گڏ ڪري ٿو.",
  "wy.hero.eyebrow": "اگروپيو ڇو",
  "wy.hero.titleLead": "جتي مٽي ملي ٿي",
  "wy.hero.titleAccent": "سگنل سان",
  "wy.hero.sub": "ٻجڻ جا فيصلا اندازن تي نه ڇڏيا وڃن. اگروپيو هڪ ئي پليٽ فارم ۾ اے آئي مشير، توهان جي فارم جو رڪارڊ، موسم جي آگاهي واري هدايت ۽ توهان جي پنهنجي ٻولي مهيا ڪري ٿو — ته جيئن هر فيصلو توهان جي زمين جي حقيقت تي بيٺل هجي.",
  "wy.hero.ctaPrimary": "جلد رسائي حاصل ڪريو",
  "wy.hero.ctaSecondary": "پليٽ فارم ڏسو",
  "wy.hero.tagStart": "پاڪستان لاءِ ٺاهيو ويو",
  "wy.hero.tagThen": "Aplinode جي پيداوار",
  "wy.hero.svgLabel": "کيت ۾ لهرائينديون نار جهڙيون لڪيرون",
  "wy.origin.eyebrow": "اسان هي ڇو ٺاهيو",
  "wy.origin.heading": "وڏا فيصلا رڳو اندازن تي نه هجڻ گهرجن",
  "wy.origin.sub": "اگروپيو جي شروعات هڪ سادي مشاهدن سان ٿي: ڪيسان جو موسم ٿورن فيصلن سان طي ٿيندو آهي، ۽ هر فيصلو اصلي ذهانت جو حق‌دار آهي.",
  "wy.origin.g1Title": "وقت جو اندازو",
  "wy.origin.g1Desc": "ابھارڻ، ڀاڻ، پوک، لاباري — جن لحظن موسم جو فيصلو ڪرڻو هجي، اڃا به عادت ۽ اميد مان چونا وڃن ٿا.",
  "wy.origin.g2Title": "تاريخ مِٽجي ويندي آهي",
  "wy.origin.g2Desc": "ڪڏهن سپري ٿي، ڪڏهن ٻني سيجي، پوئتي سال ڪهڙي بيماري لڳي — ڪجهه به لکبو ناهي، تنهن ڪري ان مان ڪجهه به سکبو ناهي.",
  "wy.origin.g3Title": "مشورا ڇڙيل آهن",
  "wy.origin.g3Desc": "پاڙيسري، دڪاندار ۽ وڊيوز هر هڪ جواب ڏين ٿا — پر ڪنهن وٽ توهان جي فصل، توهان جي مٽي يا هن هفتي جي هوا جي اصل ڄاڻ ناهي هوندي.",
  "wy.origin.banner": "اندازي جي قيمت لاباري جي ڏينهن ادا ٿيندي آهي",
  "wy.diff.eyebrow": "هن کي مختلف ڇا ٿو بڻائي",
  "wy.diff.heading1": "رڳو هڪ ٻي مشوري واري ايپ ناهي.",
  "wy.diff.heading2": "فارم ذهانت جو پليٽ فارم آهي.",
  "wy.diff.sub": "گھڻا اوزار رڳو سوالن جا جواب ڏين ٿا. اگروپيو توهان جي فارم کي سکندو آهي — ۽ توهان جي درج ڪيل هر ڪم سان وڌيڪ ڪارائتو ٿيندو وڃي ٿو.",
  "wy.diff.personalTitle": "ذاتي نوعيت جو، عام نه",
  "wy.diff.personalDesc": "تجويزون توهان جي فصل، توهان جي جاءِ، موجوده موسم ۽ توهان جي فارم جي پنهنجي تاريخ مان بڻجن ٿيون — ڪڏهن به سڀني لاءِ هڪ ئي نسخو نه.",
  "wy.diff.chip1": "توهان جي فصل",
  "wy.diff.chip2": "توهان جو ضلعو",
  "wy.diff.chip3": "هن هفتي جو موسم",
  "wy.diff.chip4": "توهان جو پوئتي موسم",
  "wy.diff.langTitle": "توهان جي ٻولي ڳالهائي ٿو",
  "wy.diff.langDesc": "جيئن توهان واقعي ڳالهائيو ٿا ائين پڇو ۽ سمجو — ڪا ڏکي انگريزي ضروري ناهي.",
  "wy.diff.memoryTitle": "هر فارم جي يادداشت",
  "wy.diff.memoryDesc": "ابھارڻ، ان پٽ، بيماري، خرچ، لاباري — هر ڪم منظم رڪارڊ ۾ محفوظ، ته جيئن هر موسم پوئتي کان بهتر شروع ڪري.",
  "wy.diff.weatherTitle": "بنيادي طور تي موسم جي آگاهي سان",
  "wy.diff.weatherDesc": "هدايت توهان تائين پهچڻ کان اڳ اصل حالتون ڏسي ٿي — ته جيئن مينهن کان ڪجهه ڪلاڪ اڳ سپري جي تجويز نه ڏني وڃي.",
  "wy.diff.platformTitle": "هڪ پليٽ فارم، پورو موسم",
  "wy.diff.platformDesc": "مشير، رڪارڊ، موسم جي هدايت ۽ صلاح گڏجي ڪم ڪن ٿا — الڳ ايپس ۽ ڪاپين ۾ نه ڇڙيل هوندا آهن.",
  "wy.diff.pakTitle": "پاڪستان اول",
  "wy.diff.pakDesc": "مقامي فصلون، علائقائي طريقا ۽ حقيقي ٻني جون حالتون پهرئين ڏينهن کان ڊيزائن ۾ آهن — پوءِ شامل ڪيل سوچ جي طور تي نه.",
  "wy.diff.pakBadge": "هتان شروعات",
  "wy.life.eyebrow": "مشير ڪنهن ڪنهن ۾ هدايت ڪري ٿو",
  "wy.life.heading": "فصل جي چڪر جي هر فيصلي لاءِ هدايت",
  "wy.life.sub": "هڪ مشير پوري فصلي دور ۾ توهان سان گڏ هوندو آهي — موسم جي منصوبابندي کان وٺي فصل گهر پهچائڻ تائين.",
  "wy.life.s1Title": "ابھارڻ جو وقت",
  "wy.life.s1Desc": "ڄاڻو ڪڏهن پاڻي ڏجي — ۽ ڪڏهن انتظار ڪجي.",
  "wy.life.s2Title": "فصل جي منصوبابندي",
  "wy.life.s2Desc": "پنهنجي زمين موافق فصلون ۽ پوک جا وقت چونڊيو.",
  "wy.life.s3Title": "ڀاڻ ۽ جيت مار دوائن جي هدايت",
  "wy.life.s3Desc": "صحيح ان پٽ، صحيح مقدار ۾، صحيح وقت تي.",
  "wy.life.s4Title": "جيت ۽ بيماري ۾ مدد",
  "wy.life.s4Desc": "مسئلا جلد پڪڙيو ۽ پکڙجڻ کان اڳ اقدم ڪريو.",
  "wy.life.s5Title": "لاباري جو وقت",
  "wy.life.s5Desc": "ان لحظي تي لڻيو جيڪو پيداوار ۽ معيار جي حفاظت ڪري.",
  "wy.life.s6Title": "موسم جي آگاهي واريون تجويزون",
  "wy.life.s6Desc": "هر مشورو پهرين اڄ جون حالتون ڏسندو آهي.",
  "wy.life.s7Title": "روزمره سوال",
  "wy.life.s7Desc": "پنهنجي فصل بابت ڪجهه به پڇو، موسم جي ڪنهن به ڏينهن.",
  "wy.value.eyebrow": "واڌو",
  "wy.value.heading1": "ڇا ڪجي. ڪڏهن ڪجي.",
  "wy.value.heading2": "۽ ڇا ٿي چڪو آهي.",
  "wy.value.sub": "اگروپيو جي هر سهولت ان ٽن جوابن مان هڪ جي خدمت ڪري ٿي — انءَ طرح فيصلن جو موسم اعتماد جو موسم بڻجي وڃي ٿو.",
  "wy.value.p1Heading": "ڇا ڪجي",
  "wy.value.p1Desc": "توهان جي فصل ۽ حالتن مطابق واضح، مخصوص تجويزون — عام اشارا نه.",
  "wy.value.p2Heading": "ڪڏهن ڪجي",
  "wy.value.p2Desc": "حقيقي موسم ۽ واڌ ويجهه جي مرحلي مطابق وقت، ته جيئن صحيح اقدام صحيح لمحي تي ٿئي.",
  "wy.value.p3Heading": "ڇا ٿي چڪو آهي",
  "wy.value.p3Desc": "هر ڪم جي منظم تاريخ — هميشه دستياب، هميشه بهتر مشوري جي بنياد.",
  "wy.who.eyebrow": "ڪنهن لاءِ آهي",
  "wy.who.heading": "ڪيسان کان شروع ٿي اڳتي",
  "wy.who.a1Title": "انفرادي ڪيسان",
  "wy.who.a1Desc": "هر فيصلي ۾ عملي، ذاتي هدايت — ۽ جيڪو ڪجهه ٿي چڪو آهي ان جو منظم رڪارڊ.",
  "wy.who.a2Title": "واپاري فارم ۽ زرعي ڪاروبار",
  "wy.who.a2Desc": "ٽيمون، ٻنين ۽ موسمين ۾ منظم فارم معلومات ۽ ڀروسي جوڳي فيصلي سازي جي مدد.",
  "wy.who.a3Title": "ايڪو سسٽم جا ڀائيوار",
  "wy.who.a3Desc": "ان پٽ فراهم ڪندڙ، ڪوآپريٽو، بيمه ڪمپنيون ۽ زرعي توسيعي خدمتون — جيئن جيئن پليٽ فارم وڌندو آهي.",
  "wy.who.strip": "فارم جي گرد ماحول سان گڏ وڌندا",

  "auth.backHome": "هوم تي موٽو",
  "auth.emailLabel": "اي ميل پتو",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاسورڊ",
  "auth.showPassword": "پاسورڊ ڏيکاريو",
  "auth.hidePassword": "پاسورڊ لڪايو",
  "auth.err.emailRequired": "پنهنجو اي ميل پتو لکھيو.",
  "auth.err.emailInvalid": "صحيح اي ميل پتو لکھيو.",
  "auth.err.passwordRequired": "پاسورڊ بڻايو.",
  "auth.err.passwordMin": "گھٽ ۾ گھٽ ۸ اکر استعمال ڪريو.",
  "auth.err.passwordMax": "وڌ ۾ وڌ ۶۴ اکر استعمال ڪريو.",
  "auth.err.nameRequired": "پنهنجو پورو نالو لکھيو.",
  "auth.err.phoneInvalid": "صحيح فون نمبر لکھيو.",
  "auth.err.confirmRequired": "پنهنجو پاسورڊ ٻيهر لکھيو.",
  "auth.err.termsRequired": "اڳتي وڌڻ لاءِ شرطون قبول ڪريو.",
  "auth.err.passwordMismatch": "پاسورڊ هڪجهڙا نه آهن.",
  "auth.err.loginPasswordRequired": "پنهنجو پاسورڊ لکھيو.",
  "auth.err.tooManyAttempts": "تمام گھڻيون ڪوششون — مهرباني ڪري ٿوري وقت بعد ٻيهر ڪوشش ڪريو.",
  "auth.err.serverError": "اسان جي پاسي کان خرابي ٿي. مهرباني ڪري ٻيهر ڪوشش ڪريو.",
  "auth.err.invalidCredentials": "اي ميل يا پاسورڊ غلط آهي.",

  "li.meta.title": "داخل ٿيءُ — اگروپيو",
  "li.meta.description":
    "اگروپيو ۾ داخل ٿيو — اے آئي سان هلندڙ فارم ذهانت جو پليٽ فارم. توهان جو مشير، رڪارڊ ۽ هدايتون — اتي موجود جتي توهان ڇڏيون هيو.",
  "li.brand.headingA": "توهان جي فارم جي ذهانت،",
  "li.brand.headingB": "اتي انتظار ۾ جتي توهان ڇڏي.",
  "li.demo.aria": "اگروپيو مشير سان ڳالهه ٻولهه جي جھلڪ",
  "li.demo.user": "منهنجي ڪڻڪ جا پن پيل ٿي رهيا آهن — ڇا ڪيان؟",
  "li.demo.advisorLabel": "ٻه سبب:",
  "li.demo.advisorBody": "پاڻي جي کوٽ يا نائيٽروجن جي کوٽ. پهرين صبح ٿڌي وقت ۾ پاڻي ڏيو.",
  "li.point1": "توهان جي پنهنجي ٻولي ۾ اے آئي مشير",
  "li.point2": "سيٽيلائيٽ ذريعي فصل جي صحت جي نگراني",
  "li.point3": "هر موسم جو ڊجيٽل رڪارڊ",
  "li.eyebrow": "داخل ٿيءُ",
  "li.heading": "توهان جي فارم تي ٻيهر ڀلي ڪري آيا",
  "li.sub": "داخل ٿيءُ ته جيئن پنهنجي فارم جي مشير، رڪارڊ ۽ هدايتن تائين پهچو.",
  "li.passwordPlaceholder": "توهان جو پاسورڊ",
  "li.forgot": "پاسورڊ وساريو ويو؟",
  "li.submitting": "داخل ٿي رهيو آهي…",
  "li.noAccount": "اڃا اڪائونٽ ڪونهي؟ ابتدائي رسائي علائقو علائقو کليل ٿيندي پئي —",
  "li.noAccountEnd": ".",
  "li.createAccount": "پنهنجو اڪائونٽ ٺاهيو",

  "su.meta.title": "اڪائونٽ ٺاهيو — اگروپيو",
  "su.meta.description":
    "پنهنجو اگروپيو اڪائونٽ ٺاهيو: ذاتي نوعيت جو اے آئي مشير، موسم جي آگاهي واري هدايت، ۽ فارم رڪارڊ جي هر موسم کي بهتر بڻائين. پاڪستان لاءِ ٺاهيو ويو.",
  "su.brand.headingA": "پنهنجو موسم شروع ڪريو",
  "su.brand.headingB": "ذهنت سان.",
  "su.profile.aria": "سائن اپ بعد ٺهندڙ فارم پروفائل جي جھلڪ",
  "su.profile.badge": "فارم پروفائل · هڪ منٽ ۾ تيار",
  "su.profile.district": "ضلعو",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشوري جي ٻولي",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "گھُن · ربيع",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پهرين ڏينهن کان ذاتي نوعيت جو مشير",
  "su.included2": "توهان جي ضلعي لاءِ موسم جي آگاهي واري هدايت",
  "su.included3": "فارم رڪارڊ جي هر موسم کي بهتر بڻائين",
  "su.eyebrow": "اڪائونٽ ٺاهيو",
  "su.heading": "پنهنجو فارم اگروپيو آڻيو",
  "su.sub": "هڪ اڪائونٽ — توهان جي مشير، رڪارڊ ۽ هن موسم جي هر هدايت لاءِ.",
  "su.registered.title": "هي اي ميل اڳ ۾ ئي رجسٽرڊ آهي.",
  "su.registered.body":
    "داخل ٿيو، يا جي پاسورڊ وساريو ويو آهي ته ري سيٽ ڪريو — توهان جو فارم اتي انتظار ۾ آهي جتي توهان ڇڏيو هيو.",
  "su.registered.reset": "پاسورڊ ري سيٽ ڪريو",
  "su.name.label": "پورو نالو",
  "su.name.placeholder": "مثال طور محمد احمد",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختیاری)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آف لائن هجڻ تي ايس ايم ايس الرٽس لاءِ.",
  "su.password.placeholder": "گھٽ ۾ گھٽ ۸ اکر",
  "su.confirm.label": "پاسورڊ جي تصديق ڪريو",
  "su.confirm.placeholder": "پنهنجو پاسورڊ ٻيهر لکھيو",
  "su.strength0": "تمام ننڍو",
  "su.strength1": "ٺيڪ آهي",
  "su.strength2": "سٺو",
  "su.strength3": "مضبوط",
  "su.terms.prefix": "مان",
  "su.terms.tos": "خدمت جون شرطون",
  "su.terms.and": "۽",
  "su.terms.privacy": "پرائيويسي پاليسي",
  "su.terms.end": "قبول ڪيان ٿو.",
  "su.submit": "منهنجو اڪائونٽ ٺاهيو",
  "su.submitting": "اڪائونٽ ٺاهيو پيو وڃي…",
  "su.haveAccount": "اڳ ئي اڪائونٽ آهي؟",
  "app.shell.metadataTitle": "اگروپيو — مصنوعي ذھانت سان هلندڙ فارم ذھانت جو پليٽ فارم",
  "app.shell.metadataDescription":
    "اڄ جي رهنمايي، موسم، الرٽس۽ اگروپيو جا سڀ آله — پاڪستان لاءِ. اپلينوڊ جي پروڊڪٽ.",

  /* ── شيل نيويگيشن ─────────────────────────────────── */
  "app.shell.nav.dashboard": "ڊيش بورڊ",
  "app.shell.nav.farms": "کيثر",
  "app.shell.nav.advisor": "مشير",
  "app.shell.nav.detect": "تشخيص",
  "app.shell.nav.prices": "قیمتون",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "اطلاعات",
  "app.shell.nav.settings": "ترتيبون",
  "app.shell.nav.more": "هورين",
  "app.shell.signOut": "لاڳ آؤٽ",
  "app.shell.aria.farmerTools": "کسان جا آله",
  "app.shell.aria.currentPage": "مؤجودا صفحو",
  /* ── ڊيش بورڊ UI ──────────────────────────────────── */
  "app.dashboard.greeting": "هيلو، {name}",
  "app.dashboard.aria.profileMenu": "پروفايل مينو",
  "app.dashboard.welcomeEyebrow": "اگروپيو ۾ خوش آمدید",
  "app.dashboard.welcomeTitle": "پنھو پهريون کيثر شروع ڪريو.",
  "app.dashboard.welcomeBody":
    "توهان جي پלה، توهان جي زمين، توهان جو موسم — جيڪڏھن توهان جو کيثر هجي ته ساري رهنمايي تنهن جي مطابق هجي.",
  "app.dashboard.addFirstFarm": "پنھو پهريون کيثر شامل ڪريو",
  "app.dashboard.badge.today": "اڄ",
  "app.dashboard.aria.advisoryTitle": "اڄ جي رهنمايي",
  "app.dashboard.carryToField": "ان کيثر تي وڃائيو",
  "app.dashboard.askAdvisor": "مشير سان پڇھو",
  "app.dashboard.aria.weatherTitle": "موسم \u00b7 {location}",
  "app.dashboard.aria.degreesCelsius": "{n} ڊيگري سیلسيس",
  "app.dashboard.fullForecast": "مکمل پیشگوئي",
  "app.dashboard.weatherUnavailable":
    "موسم هن وقت لوڊ نهٿو. ٿوري دير بعد ٻيهر چيڪ ڪريو — توھان جي رهنمايي چاليا رهيا.",
  "app.dashboard.seasonTipBadge": "موسمي تجويزون",
  "app.dashboard.alertsHeading": "الرٽس",
  "app.dashboard.newCount": "{n} نئون",
  "app.dashboard.viewAllAlerts": "سڀ珥ٽ ڏيڪھو",
  "app.dashboard.noAlerts": "اڄ ڪوئي珥ٽ نه آهي — توھان جا پله سکون ۾ آهن.",
  "app.dashboard.aria.alert": "الرٽ",
  "app.dashboard.severity.critical": "سنگين",
  "app.dashboard.severity.watch": "خبردار",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "ٻولڻ",
  "app.dashboard.quickActionsHeading": "فوری عمل",
  "app.dashboard.cropDoctor": "پلا جو ڊاڪٽر",
  "app.dashboard.detectTitle": "بيماري پھیلن کان اڳ پهڙajo",
  "app.dashboard.detectBody":
    "متاثريل پتي جو تصویر اپلوڊ ڪريو — فوري تشخيص ۽ اڳلا قدم توھان جي فون تي.",
  "app.dashboard.myFarms": "منھنجا کيثر",
  "app.dashboard.addFarm": "کيثر شامل ڪريو",
  "app.dashboard.viewAllFarms": "سڀيو کيثر ڏيڪھو",
  "app.dashboard.health.good": "چڱو",
  "app.dashboard.health.watch": "خبردار",
  "app.dashboard.setupChecklist": "پنھو کيثر ترتيب ڪريو",
  "app.dashboard.checklistProgress": "{total} مان {done} مکمل",
  "app.dashboard.aria.dismissChecklist": "سيٽ اپ چيڪ لسٽ بند ڪريو",
  "app.dashboard.aria.setupProgress": "سيٽ اپ جي ترقي",
  "app.dashboard.demoFooter": "ڊيمو بلڊ \u00b7 صرف نمونو ڊيٽا",

  /* ── ڊيش بورڊ ڊيمو ڊيٽا ──────────────────────────── */
  "app.dashboard.demo.todayLabel": "آتوار، ۲۳ اگسٽ",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "سبزه جو مرحلو",
  "app.dashboard.demo.advisoryAction": "اڄ پاني پاشي ۾ تاخير ڪريو",
  "app.dashboard.demo.advisoryWhy":
    "اڄ دوپهر کان واري بارش جو امڪان آهي — توھان جو کيثر قدرتي طور تي پاني وڃي.",
  "app.dashboard.demo.seasonAction": "بارش آڻن کان اڳ پنھا کيثرن ۾ وڃو",
  "app.dashboard.demo.seasonWhy":
    "خشڪ ڏينهنن کان واري سست چال ڏکهايو ٿو ڪهڙا حصا خراب نڪاسڢي ڪري ٿا — بونن کان اڳ نوٽ ڪريو.",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "دوپهر ۲ بجيا کان واري بارش جو امڪان \u00b7 ۸۰٪ امڪان",
  "app.dashboard.demo.alertWhitefly":
    "ملتان ڍڙي ۾ هن هفتي کپاس تي سفيد مکي جو خطروڙو آهي.",
  "app.dashboard.demo.alertRain":
    "اڄ دوپهر ۲ بجيا کان واري بارش متوقع آهي — چھڙي چھڙڻ جو منصوبو ملتوی ڪريو.",
  "app.dashboard.demo.alertPrice":
    "ملتان منڊي تي گندم جا قیمتون گزشتہ هفتي جي بلانيتي ۴٪ وڌيون آهن.",
  "app.dashboard.demo.farm1Name": "خليل پور کيثر",
  "app.dashboard.demo.farm1Location": "خليل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "سبزه جو مرحلو",
  "app.dashboard.demo.farm2Name": "سahiوال پلاٽ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڊ، سahiوال",
  "app.dashboard.demo.farm2Crops": "کپاس",
  "app.dashboard.demo.farm2Stage": "پھول آڻڻ",
  "app.dashboard.demo.farm3Name": "چک ۶۲ جي بي",
  "app.dashboard.demo.farm3Location": "چک ۶۲ جي بي، فيصل آباد",
  "app.dashboard.demo.farm3Crops": "گنا",
  "app.dashboard.demo.farm3Stage": "پري جو مرحلو",
  "app.dashboard.demo.checklistAdvisor": "هڪ ڏفتي مشير سان پڇھو",
  "app.dashboard.demo.checklistDetect": "پنھو پهريون تشخيص چلائو",
  "app.dashboard.demo.actionAdvisor": "مشير سان پڇھو",
  "app.dashboard.demo.actionScan": "پله اسڪين ڪريو",
  "app.dashboard.demo.actionPrices": "قيمتون چيڪ ڪريو",
  "app.dashboard.demo.actionRecord": "ریڪارڊ شامل ڪريو",

  /* ── کيثر عام ────────────────────────────────────────── */
  "app.farms.eyebrow": "کيثر",
  "app.farms.health.good": "چڱو",
  "app.farms.health.watch": "خبردار",
  "app.farms.units.acres": "ایکڙ",
  "app.farms.stages.sowing": "بирования",
  "app.farms.stages.tillering": "شاخون",
  "app.farms.stages.vegetative": "نباتاتي",
  "app.farms.stages.grainFilling": "ڌان ڀرائڻ",
  "app.farms.stages.ready": "تيار",
  "app.farms.stages.squaring": "پھل باندھڻ",
  "app.farms.stages.flowering": "پھول آڻڻ",
  "app.farms.stages.bollFilling": "تہائي ڀرائڻ",
  "app.farms.stages.grandGrowth": "ويسو ش.effects",
  "app.farms.stages.ripening": "پکڻ",
  "app.farms.stages.harvest": "ڪٹائي",
  "app.farms.stages.panicleInitiation": "پاڻيڪل اينٿيئيولوشن",

  /* ── ضلعو ۽ فصلون ───────────────────────────────────── */
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سahiوال",
  "app.farms.districts.faisalabad": "فيصل آباد",
  "app.farms.districts.vehari": "وehari",
  "app.farms.districts.bahawalpur": "bahawalpur",
  "app.farms.districts.lodhran": "lodhran",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "ڪپاس",
  "app.farms.crops.sugarcane": "گنا",
  "app.farms.crops.maize": "مکئي",
  "app.farms.crops.rice": "چاول",

  /* ── کيثرن جي فهرست ──────────────────────────────────── */
  "app.farms.list.pageTitle": "کيثر — اگروپيو",
  "app.farms.list.heading": "توهان جا سڀ کيثر، هڪ فهرست",
  "app.farms.list.description":
    "هر کيثر پنهنجن فصلن، نشوونما جي مرحلي ۽ صحت سان — هڪ ڏيکھ ۾. کيثر جي بشپړ ڪهاڻي لاءِ ٽيپ ڪريو.",
  "app.farms.list.addLink": "شامل ڪريو",
  "app.farms.list.openFarm": "کيثر کوليو",
  "app.farms.list.addNewFarm": "نئون کيثر شامل ڪريو",
  "app.farms.list.emptyHeading": "اوس وقت کيثر نه آهي",

  /* ── نئون کيثر ────────────────────────────────────────── */
  "app.farms.new.pageTitle": "کيثر شامل ڪريو — اگروپيو",
  "app.farms.new.heading": "کيثر شامل ڪريو",
  "app.farms.new.description":
    "اگروپيو کان پنهنجي زمين بار ۾ آcoes — مقام، فصل ۽ اندازه — ته جيئن هر هدايت تنهن جي مطابق هجي.",
  "app.farms.new.fields.name": "کيثر جو نالو",
  "app.farms.new.placeholders.name": "مثال طور خليل پور کيثر",
  "app.farms.new.fields.district": "ضلعو",
  "app.farms.new.placeholders.district": "ضلعو ڏيڪھيو",
  "app.farms.new.fields.crop": "بنيادي فصل",
  "app.farms.new.placeholders.crop": "فصل ڏيڪھيو",
  "app.farms.new.fields.acres": "اندازه (ایکڙ)",
  "app.farms.new.placeholders.acres": "مثال طور ۱۲.۵",
  "app.farms.new.buttons.saving": "خوندي ٿي رهيو آهي…",
  "app.farms.new.buttons.save": "کيثر خوندي ڪريو",
  "app.farms.new.demoNotice": "ڊيمو — خوندي ڪرڻ هن وقت ڊيٽابیس سان نه جوڑي",
  "app.farms.new.success.heading": "کيثر ڊيمو ۾ خوندي ٿيو",
  "app.farms.new.success.description":
    "بشپړ بلڊ ۾ هن کيثر توهان جي ڊيش بورڊ تي ڏيکارو ۽ هدايتون شکل اخیستل شروع ڪنن.",
  "app.farms.new.success.goToFarms": "منھنجا کيثر تي وڃو",
  "app.farms.new.success.backToDashboard": "واپس ڊيش بورڊ تي",
  "app.farms.new.errors.nameRequired": "کيثر کان نالو ڏيو.",
  "app.farms.new.errors.districtRequired": "ضلعو ڏيڪھيو.",
  "app.farms.new.errors.cropRequired": "بنيادي فصل ڏيڪھيو.",
  "app.farms.new.errors.acresRequired": "اندازه ڪريو.",

  /* ── کيثر جي تفصيلون ─────────────────────────────────── */
  "app.farms.detail.pageTitle": "کيثر جي تفصيلون — اگروپيو",
  "app.farms.detail.heroEyebrow": "کيثر جي تفصيلون",
  "app.farms.detail.goodHealth": "چڱي صحت",
  "app.farms.detail.needsWatching": " uwag دستور",
  "app.farms.detail.sownLabel": "بиров",
  "app.farms.detail.seasonHeading": "فصل کيئن آهي",
  "app.farms.detail.activityHeading": "کيثر جي سرگرمي",
  "app.farms.detail.viewAllRecords": "سڀ رڪارڊ ڏيڪھو",
  "app.farms.detail.logFieldEvent": "کيثر جو واقعو درج ڪريو",
  "app.farms.detail.scanCrop": "فصل اسڪين ڪريو",

  /* ── رڪارڊ عام ───────────────────────────────────────── */
  "app.records.eyebrow": "کيثر جا رڪارڊ",
  "app.records.types.irrigation": "آبپاشي",
  "app.records.types.fertilizer": "کوڙ",
  "app.records.types.pesticide": "حشره مار",
  "app.records.types.disease": "بيماري",
  "app.records.types.harvest": "کٹائي",

  /* ── رڪارڊن جي فهرست ─────────────────────────────────── */
  "app.records.farmRecords.pageTitle": "کيثر جا رڪارڊ — اگروپيو",
  "app.records.farmRecords.heading": "کيثر جي يادداشت",
  "app.records.farmRecords.description":
    "هر آبپاشي، اسپري ۽ علاج لکييل — ته جيئن راتلونڪي ھفتا يادداشت تي منحصر نه ٿي.",
  "app.records.farmRecords.demoNotice":
    "ڊيمو — صرف نمونا اندراجات — نئون خوندي ڪرڻ هن وقت نه جوڑي",

  /* ── نئون رڪارڊ ──────────────────────────────────────── */
  "app.records.new.pageTitle": "نئون رڪارڊ — اگروپيو",
  "app.records.new.heading": "کيثر ۾ جي ٿييُو آهي ان کي درج ڪريو",
  "app.records.new.description":
    "آبپاشي، کوڙ، حشره مار، بيماري ۽ کٹائي جا اندراجات — توهان جي کيثر جي يادداشت، هڪ لڪير هڪ ڪري.",
  "app.records.new.fields.type": "ڇا ٿييُو آهي؟",
  "app.records.new.fields.farm": "کيثر",
  "app.records.new.placeholders.farm": "کيثر ڏيڪھيو",
  "app.records.new.fields.date": "تاريخ",
  "app.records.new.fields.title": "لنڊ عنوان",
  "app.records.new.fields.optional": "(اختیاری)",
  "app.records.new.placeholders.titleIrrigation": "مثال طور نهري پاني — بشپړو کيثر",
  "app.records.new.placeholders.titleOther": "ٻيو اسپري پتوارن تي",
  "app.records.new.fields.details": "تفصيلون",
  "app.records.new.placeholders.details":
    "راتلونڪي ھفتا لاءِ جيڪو ڳ travelled ڌاريو وڃي — مقدار، موسم، کيثر جي حالت.",
  "app.records.new.buttons.saving": "خوندي ٿي رهيو آهي…",
  "app.records.new.buttons.save": "رڪارڊ خوندي ڪريو",
  "app.records.new.demoNotice": "ڊيمو — خوندي ڪرڻ هن وقت ڊيٽابیس سان نه جوڑي",
  "app.records.new.success.heading": "رڪارڊ ڊيمو ۾ خوندي ٿيو",
  "app.records.new.success.description":
    "بشپړ بلڊ ۾ هن اندراج توهان جي کيثر جي رڪارڊ ۾ شامل ٿي جيڳو ۽ راتلونڪي هدايتون تيز ٿي ان.",
  "app.records.new.success.backToDashboard": "واپس ڊيش بورڊ تي",
  "app.records.new.success.viewFarms": "منھنجا کيثر ڏيڪھو",
  "app.records.new.errors.farmRequired": "ڏيڪھيو ڇا هن کيثر تي ٿييُو آهي.",
  "app.records.new.errors.dateRequired": "تاريخ ڏيڪھيو.",
  "app.advisor.chat.tryAsking": "ھي پڇي ڏسو",
  "app.advisor.chat.suggested1": "منھنجي ڪڻڪ تي ڪھڙي بيماري لڳي آھي؟",
  "app.advisor.chat.suggested2": "ڇا اڄ ملتان ۾ مينھن پوندو؟",
  "app.advisor.chat.suggested3": "اڄ منڊي جا اگھ ڇا آھن؟",
  "app.advisor.chat.suggested4": "ڪسان ڪارڊ اسڪيم بابت ٻڌايو",
};
