import type { CatalogKey } from "./en.ts";

/** سرائیکی — AI-drafted, founder-reviewed copy (plan D4). */
export const skr: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کیویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "ورقہ موجود کائنا",
  "notFound.body": "تساں جیہدا ورقہ لبھدا پئے او موجود کائنا یا بدل گیا ہے۔",
  "notFound.backHome": "اگروپیو دے گھر واپس ونجو",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم ذہانت دا پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار وہائی لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڈے فارم دے ریکارڈ اک تھاں کٹھے کردا اے — ڈیٹا کوں صاف فیصلیاں وچ بدلدا اے، تہاڈی اپنی بولی وچ۔",
  "home.hero.ctaSecondary": "ݙیکھو ایہ کیویں کم کردا اے",
  "home.hero.imageAlt": "وہائی کران وچ ٹیبلٹ تے اگروپیو ورتیندے ہوئے",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "چنگا",
  "home.hero.noteClearSky": "صاف اسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم موجب صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "سُکڑیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "وہائی دے فیصلے اندازے دا کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان وچ وہائی ریایت، مقامی صلاحاں تے کھنڈریاں معلومات نال وڈے رسک والے فیصلے کرندے نیں۔ نقصان کتائی تے چکندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلھا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، کتائی — اہم لمحے اجے وی اندازے نال طے تھیندے نیں، جس نال پیداوار گھٹدی تے خرچ ضائع تھیندی اے۔",
  "home.problem.item2Title": "گواچیا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھنڈریاں کاپیاں وچ رہندا اے۔ پچھلے سال جیہڑا کم آیا، اوں توں ایں سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھنڈریاں صلاحاں",
  "home.problem.item3Body": "گوآں ڈے، دکان دار تے ویڈیوز سب جواب ڈیندے نیں — پر تھوڑے جیہے وہائی دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت کتائی تے چکندی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک ذہانت دا پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈی تہاڈی زمین دے ڈیٹا نال کم کرندے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، سُکڑیاں مار تے کتائی دے ویلے لئی ذاتی صلاحاں — تہاڈی فصل تے حالات موجب۔",
  "home.solution.card1Answer": "ایں کھیت، ایں ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کڈوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی ڈسدی اے کم کڈوں کرنا اے، تاں جو غلط ویلھا تے اچانک حالات تہاڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما موجب ویلھا۔",
  "home.solution.card3Title": "کی کیتا گیا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، کتائی — ترتیب والے ریکارڈ وچ محفوظ جیہڑا ہر سیزن کوں ودھ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ موجود۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "کئی انجن،",
  "home.features.titleB": "اک ذہین پلیٹ فارم",
  "home.features.subtitle": "تہاڈے اپنے لفظاں وچ پہلے سوال توں سمورے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی کوں طاقت ڈیندی اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی وہائی مشیر",
  "home.features.advisorTopics": "پانی · کھاد · سُکڑے تے بیماری · کتائی",
  "home.features.advisorBadge": "رومن سرائیکی",
  "home.features.advisorMockAria": "پیلیں پتریں والی کنک تے اگروپیو مشیر نال نمونہ گل ملاقات",
  "home.features.advisorUserMsg": "میڈی کنک دے پتر پیالے تھیندے پئین — کراں؟",
  "home.features.advisorReplyTitle": "پیلے پتر — ڈو عام کارن:",
  "home.features.advisorReplyCause1": "پانی دی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھڈے ویلے وچ، سویرے 9 وجے توں پہلے پانی ڈیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سبھ توں پرانے پتر پہلے ڈیکھو؛ لوڑ ہووے تاں یوریا پاؤ۔",
  "home.features.advisorReplyFooter": "جے پتریں ہیٹھ پیلیاں دھاریاں نظر آن، تصویر بھیجو — main بیماری دی جانچ کر ڈیساں۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھو یا بولو…",
  "home.features.advisorFooter": "اپنی فصل بارے کجھ وی پچھو — روزمرہ سوالاں بھلیاں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر کم ترتیب نال درج — تے جیویں صلاح تہاڈی اپنی زمین توں سکھے۔",
  "home.features.record1Activity": "پانی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتریں دا اسکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "کنک · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · بولی",
  "home.features.languageTitle": "تہاڈی بولی، تہاڈے لفظ",
  "home.features.languageDesc": "جیویں سوچیندو او تیویں بولو یا لکھو — تکنیکی انگریزی دی لوڑ کائینی۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں جانو رہنمائی",
  "home.features.weatherDesc": "صلاح تسیں تک پجدن توں پہلے سچے حالات ڈیکھدی اے — mینہ توں پہلاں سپرے کر بیٹھو تے سارا کھاد وہہ ویسی۔",
  "home.features.weatherMockAria": "پنج ڈینہاں دی پیش گوئی جیندے وچ جمعرات کوں سپرے نہ کرن دی صلاح نمایاں اے",
  "home.features.dayMon": "سوموار",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "سپرہ روکو",
  "home.features.weatherLegend": "مقامی موسم دی پیش گوئی توں صلاح والا ڈینہ نمایاں",
  "home.features.moreLink": "پلیٹ فارم ودھدا پیا اے — ساریاں صلاحیتاں ڈیکھو",
  "home.journey.eyebrow": "ایہ کیویں کم کردا اے",
  "home.journey.title": "اک سوال سیزن دی شروعات کردا اے",
  "home.journey.subtitle": "تہاڈے پہلے سوال توں مکمل، ذہین فارم تاریخ تک سادہ راہ۔",
  "home.journey.step1Title": "اپنا فارم شامل کرو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بناون لئی تھاں، فصل تے بنیادی تفصیلات بھرو۔",
  "home.journey.step2Title": "اے آئی توں پچھو",
  "home.journey.step2Body": "اپنا سوال اسی بولی وچ لکھو یا بولو جیندے وچ تسیں سبھ توں آرام نال او۔",
  "home.journey.step3Title": "رہنمائی گھنو",
  "home.journey.step3Body": "اپنی فصل، موسم، تھاں تے فارم تاریخ تے بیسیاں صلاحاں گھنو۔",
  "home.journey.step4Title": "کم درج کرو",
  "home.journey.step4Body": "تھوڑے ٹیپاں وچ پانی، کھاد، دوائی یا بیماری درج کرو۔",
  "home.journey.step5Title": "تاریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ اگلیاں صلاحاں کوں ودھ سمجھدار تے موزوں بناندا اے۔",
  "home.journey.step6Title": "نگرانی جاری رکھو",
  "home.journey.step6Body": "سمورے سیزن دوران ریکارڈ ڈیکھو تے ترقی تے نظر رکھو۔",
  "home.matrix.eyebrow": "ساریاں صلاحیتاں دا مجموعہ",
  "home.matrix.title": "لوڑ توں حیران کن تک",
  "home.matrix.subtitle": "ہر خاصیت فصل بچیندی اے، خرچ گھٹیندی اے یا آمدنی ودھیندی اے۔ اینوں جنتری وانگوں پڑھو — ہر درجہ پچھلے تے بنیا ہوندا اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتاں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی پدھر",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری پچھان",
  "home.matrix.t1f1Body": "متاثرہ پتر دی تصویر اپلوڈ کرو تے فوری جانچ، شدت تے علاج دیاں صلاحاں گھنو۔",
  "home.matrix.t1f2Title": "سیٹلائٹ کھیت نگاری",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد نشان لگاؤ تے مفت سینٹینل-2 تصویراں توں این ڈی وی آئی بیسی فصل دی صحت ڈیکھو۔",
  "home.matrix.t1f3Title": "ہوشیار موسمی صلاح",
  "home.matrix.t1f3Body": "مقامی موسم پیش گوئی تہاڈی فصل تے ودھدے پڑاءُ نال مل کے روزانہ کم دی صلاح بن ویندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیش گوئی",
  "home.matrix.t1f4Body": "نزدیکی منڈی دیاں قیمتیں اے آئی رجحاناں نال ڈیکھو، تے ٹھیک ویلے تے ویکو۔",
  "home.matrix.tier2Name": "وکھریاں خاصیتاں",
  "home.matrix.tier2Badge": "نمانہ",
  "home.matrix.t2f1Title": "علاقائی بولیاں دا وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولو یا لکھو — جواب اسی بولی وچ سنو جیہڑی تسیں بہتر سمجھدو۔",
  "home.matrix.t2f2Title": "سرکاری سکیم میچر",
  "home.matrix.t2f2Body": "اپنیاں تفصیلات بھرو تے ہر اہل سکیم لبھو — دستاویزاں تے اپلائی لنکاں سمیت۔",
  "home.matrix.t2f3Title": "فصل سفارش انجن",
  "home.matrix.t2f3Body": " ایں سیزن تہاڈی مٹی، موسم، منڈی دی منگ تے بجٹ موجب سبھ توں ودھ نفع والی فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے اصلی خرچ، پیداوار، آمدنی تے نفع — بریک ایون تے آر او آئی نال۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوال پاؤ، تصویراں شیئر کرو، ساتھی وہائیاں تے تصدیق شدہ ماہراں توں جواب گھنو۔",
  "home.matrix.tier3Name": "حیران کن",
  "home.matrix.tier3Badge": "سبھ توں اگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی نگاری",
  "home.matrix.t3f1Body": "سلائیڈر نال ویلے نال سیٹلائٹ تصویراں تولو — ودھاءُ، نقصان یا قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی سُکڑا خطرہ پیش گوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے پڑاءُ تے تاریخ دے بنیاد تے ممکنہ حملے توں پہلاں سوچنا۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر تے کال کرو، سوال بولو، اپنی بولی وچ صلاح سنو — اسمارٹ فون دی لوڑ کائینی۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ اندازہ",
  "home.matrix.t3f4Body": "پائیدار طریقے درج کرو تے رضاکارانہ مارکیٹاں توں کاربن کریڈٹ دا اندازہ لاو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت وچ آف لائن کم کرے، کنکشن تے سنک تھیوے، کمزور نیٹ تے ایس ایم ایس خبر ڈیوے۔",
  "home.vision.eyebrow": "وژن",
  "home.vision.titleA": "پاکستان کیتے بنایا گیا۔",
  "home.vision.titleB": "دنیا کیتے تیار۔",
  "home.vision.pkTitle": "پہلے پاکستان والا ول",
  "home.vision.pkBody": "پہلا ورژن پاکستان دے کھیتاں کیتے بنایا گیا اے: مقامی فصلاں، علاقائی بولیاں، اصلی وہائی دے طریقاں تے اصلی کھیتاں دیاں حالتاں۔",
  "home.vision.pkPoint1": "مقامی فصل تے موسم دی سمجھ",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "اصلی وہائیاں دی رائے نال بہتر کیتا گیا",
  "home.vision.worldTitle": "دنیا بھر وچ پھیلن دا وژن",
  "home.vision.worldBody": "موزاں تھیوݨ کیتے بنایا گیا۔جدوں پلیٹ فارم ودھدا اے تے نویں دیساں، بولیاں، فصلاں تے موسماں تک جاندا اے—شروع کنوں نویں سرے نہ بناوے۔",
  "home.vision.worldPoint1": "دیس موجب کھیتی دی سمجھ",
  "home.vision.worldPoint2": "ودھو بولیاں تے مقامی فصلاں",
  "home.vision.worldPoint3": "ڈونگھے ڈیٹا جوڑ تے تجزیے",
  "home.users.title1": "انفرادی وہائی",
  "home.users.desc1": "نکے تے وچولے فارم جنہاں کوں عملی صلاح تے ہر کم دا ترتیب والا ریکارڈ لوڑ اے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہاں کوں ترتیب والی جانکاری، فیصلے دی مدد تے ٹیم دے ریکارڈ لوڑین۔",
  "home.users.title3": "ایکو سسٹم سنگتی",
  "home.users.desc3": "ان پٹ سپلائر، کوآپریٹو، بیمہ تے وادھو سروساں جیہڑے ویلے نال پلیٹ فارم نال رلوسن۔",
  "home.users.tagline": "پہلے وہائیاں کیتے بنایا گیا — ایکو سسٹم نال ودھدا ہویا",
  "home.cta.eyebrow": "شروعاتی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم تے گھن آؤ",
  "home.cta.subtitle": "اگروپیو نال بہتر فیصلے کرن والے وہائیاں وچ رل تھیوو — پاکستان کنوں شروع، دنیا بھر وچ ودھاءُ۔",
  "home.cta.success": "تسیں لسٹ وچ او۔جدوں تہاڈا علاقہ کھلسے اساں رابطہ کرسوں۔",
  "home.cta.emailLabel": "ای میل پتہ",
  "home.cta.fineprint": "کوئی سپام کائینی۔جڈاں وی مرضی ہووے ان سبسکرائب کرو۔",
  "home.footer.tagline": "اے آئی والا فارم انٹیلیجنس پلیٹ فارم۔صلاح، سیٹلائٹ نگهبانی، منڈی دیاں قیمتیں تے ریکارڈ—مٹی تے سگنل، نال نال۔",
  "home.footer.pagesHeading": "ورقے",
  "home.footer.pagesNavLabel": "فوٹر ورقے",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس دیاں شرطاں",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کرو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔سارے حق محفوظ نیں۔",
  "home.footer.motto": "پاکستان کیتے بنیا · دنیا کیتے تیار",
  "hiw.meta.title": "ایہ کیویں کم کردا اے — اگروپیو",
  "hiw.meta.description":
    "ہک منٹ دے فارم پروفائل کنوں لڳاتار بہتر تھیوݨ والے موسمی چکر تائین: ݙیکھو اگروپیو سوال، سرگرمیاں تے ریکارڈ کیویں ذاتی کھیتی رہنمائی وچ بدلدا اے۔",
  "hiw.hero.eyebrow": "ایہ کیویں کم کردا اے",
  "hiw.hero.titleA": "چھ نکے مرحلے۔",
  "hiw.hero.titleLead": "ہک",
  "hiw.hero.titleAccent": "ودھیرے سمجھدار سیزن۔",
  "hiw.hero.subtitle":
    "اگروپیو اوس طرح کم کردا اے جیویں وہائی پہلوں توں چلدی ہے — تسیں بیج بچاؤ، پُچھو، کم کرو تے ریکارڈ کرو۔ فرق صرف ایہ ہے جو ہُݨ ہر مرحلہ اگلا سکھیندا اے۔",
  "hiw.hero.browseFeatures": "خاصیتاں ݙیکھو",
  "hiw.route.navLabel": "اگروپیو دے موسمی چکر دے چھ مرحلے",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بناؤ",
  "hiw.route.stop2": "پُچھو",
  "hiw.route.stop3": "صلاح",
  "hiw.route.stop4": "کم کرو",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "ہک واری سیٹ اپ کرو",
  "hiw.setup.title": "تسیڈا فارم جیندا پروفائل بن ویندے",
  "hiw.setup.body":
    "چار خانے، ہک منٹ کنوں گھٹ — ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ۔ ایہو سارا فارم اے۔ ایندے بعد ہر جواب ڄاندا اے جو ایہ کتھاں تے کہڑیاں حالتاں وچ اگھدا پئے۔",
  "hiw.setup.point1": "فصل بدلو یا جڈاں وی مرضی ہووے فارم شامل کرو",
  "hiw.setup.point2": "ٹھیکیداراں تے ڈیلراں کیتے کئی فارم",
  "hiw.setup.point3": "کوئی تکنیکی گل نہیں پچھی ویندی — مٹی دی رپورٹ دی لوڑ نہیں",
  "hiw.setup.mockHeading": "نواں فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بناؤ",
  "hiw.setup.mockFootnote": "ہک منٹ کنوں گھٹ لگدا اے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جیندے وچ ضلع، فصل، بیج دی تاریخ تے زمین دا رقبہ بھریا ہویا اے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "کنک · ربیع",
  "hiw.setup.rowSowing": "بیج دی تاریخ",
  "hiw.setup.valSowing": "۲۰ نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "۱۲ ایکڑ",
  "hiw.ask.eyebrow": "جو منگے پُچھو",
  "hiw.ask.titleA": "ہک سوال ونجے۔",
  "hiw.ask.titleB": "تسیڈا سارا فارم جواب ڈیندا اے۔",
  "hiw.ask.body":
    "ہکو جیہا سوال وکھرے فارماں تے وکھرا مطلب رکھدا اے۔ ایں کیتے جواب ڈیوݨ توں پہلاں اگروپیو سوال کوں تسیڈے فارم بارے ڄاتیا ہویا ہر شے نال ملا تے ݙیدھا اے۔",
  "hiw.ask.pipelineLabel":
    "وہائی دے سوال کوں فصل، ضلع، موسم تے تاریخ دے تناظر نال ملا تے ذاتی جواب بنایا ویندے",
  "hiw.ask.question": "ہُݨ پانی ڈیونا چاہیدا اے یا تھولا انتظار؟",
  "hiw.ask.checkedAgainst": "اناں شیواں نال ملا تے",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "کنک · گٹھیاں پے گئیاں",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "۲۶° • خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخ",
  "hiw.ask.chipValHistory": "یوریا ۹ ڈینہہ پہلاں",
  "hiw.ask.answer":
    "ڈو ڈینہہ رکو — مینہہ دا امکان اے، تے یوریا توں بعد زمین ہلی اے۔ جمعے تائین ݙیکھ گھننا کافی اے۔",
  "hiw.ask.answerMeta": "ذاتی جواب • کنک، یوریا توں ۹ ڈینہہ بعد",
  "hiw.ask.footnote": "لکھو، بولو یا کال کرو — جواب ہر صورت تسیڈے فارم دا اپنا ہوندے",
  "hiw.engine.eyebrow": "جواب دے پچھوں",
  "hiw.engine.title": "چار جانچاں اوس توں پہلاں جدوں تساں ہک لائین ݙیکھو",
  "hiw.engine.body":
    "صلاح کوئی سرچ نتیجہ نیں۔ ایہ چار دروازےآں وچوں لنگھدا اے تاں جو تسیڈے تک جو پجدے او اوہوس کھیت کیتے، اوہوس ہفتے کیتے محفوظ ہووے۔",
  "hiw.engine.check1Title": "جانکاری اکٹھی کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم تے فصل دا پڑاؤ بھیجن دے لمحے نال نال اکٹھے تھیندے نیں۔",
  "hiw.engine.check2Title": "ملان دی جانچ",
  "hiw.engine.check2Desc":
    "مشورہ موسم دی پیش گوئی نال پرکھیا ویندے — مینہہ وچ بیکار تھیوݨ والا سپرے انجن وچوں نکلدا ای نیں۔",
  "hiw.engine.check3Title": "ذاتی بناؤنا",
  "hiw.engine.check3Desc":
    "تسیڈے کھیت دی تاریخ جواب بدل ڈیندی اے — اوہی فصل، وکھری مٹی، وکھرا مشورہ۔",
  "hiw.engine.check4Title": "پجاؤنا",
  "hiw.engine.check4Desc":
    "ول تسیڈی زبان وچ صاف قدم بݨ تے آندا اے — سکرین تے، آواز وچ یا فون کال تے۔",
  "hiw.engine.safetyStrong": "جے کجھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تاں اگروپیو اڈیک دا آکھدا اے — دیر نال ملݨ والا جواب بیکار تھیا سپرے یا برباد فصل توں بہتر اے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کرو",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی ڈیونا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل لہاوݨ",
  "hiw.record.row1Time": "اج • سویرے 6:40",
  "hiw.record.row1Label": "پانی ڈیونا درج تھیا",
  "hiw.record.row1Detail": "نہر دا موڑ • ۴۰ منٹ • پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج تھئی",
  "hiw.record.row2Detail": "DAP ۲۰ کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف ڈو ٹیپ — آف لائن وی چلدا اے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جیندے وچ فوری ایکشن چپس تے حالی درج تھئے اندراج نیں",
  "hiw.record.eyebrow": "جیویں جیویں کم کرو، ریکارڈ کردے ونجو",
  "hiw.record.titleA": "ہُݨ ڈو ٹیپ،",
  "hiw.record.titleB": "سارے سیزن بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت کیتے بنائی گئی اے — وڈے بٹن، گھٹ خانے، ٹائپنگ دی لوڑ نیں۔ ہر اندراج فارم دی یادداشت دا انگ بݨدا اے، ایں کیتے مشورہ وی فصل نال نال تکھا تھیندا ویندے۔",
  "hiw.record.point1": "پانی، کھاداں، بیماری، خرچ، فصل — سب ہک ٹائم لائین تے",
  "hiw.record.point2": "پوری طرح آف لائن چلدا اے؛ سگنل آنے تے خودکار سنک تھی ویندے",
  "hiw.record.point3": "بینک، خریدار یا بیمے کیتے سیزن خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "ایہ فصل لہاوݨ تے مکدا نیں۔",
  "hiw.loop.titleB": "اوتھوں شروع تھیندا اے۔",
  "hiw.loop.body":
    "پُچھو، کم کرو، ریکارڈ کرو — ول ول۔ چکر دی ہر واری اگروپیو تسیڈی زمین بارے نواں کجھ سکھدا اے، تاں اگلا سیزن پچھلے توں اگے شروع تھیوے۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کمائیندا اے",
  "hiw.loop.benefit1Desc":
    "پچھلے سیزن دیاں بیماریاں، خوراکاں تے تریخاں ایں سیزن دا پہلا جواب بنیندیاں نیں۔",
  "hiw.loop.benefit2Title": "کجھ دہرانا نیں پیندا",
  "hiw.loop.benefit2Desc":
    "مشاورت ڄاندی اے جو کیہ پہلوں سپرے یا کھاد تھی چکیا اے — دوہری خوراک دا خطرہ نیں۔",
  "hiw.loop.benefit3Title": "ہر سیزن دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرضے، خریدار، بیمہ یا اگلی فصل دے فیصلے کیتے تیار راہندا اے۔",
    "hiw.loop.stepLearn": "سکھو",
  "hiw.loop.stepImprove": "بہتر کرو",
"hiw.loop.diagramLabel": "گول چکر خاکہ: پُچھو، کم کرو، ریکارڈ کرو، سکھو، بہتر کرو",
  "hiw.loop.centerSeason": "سیزن",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر سیزن، پچھلے توں بہتر",
  "feat.meta.title": "خاصیتاں — اگروپیو",
  "feat.meta.description": "اگروپیو دی ہر خاصیت ݙیکھو: اے آئی فصل ڈاکٹر، سیٹلائٹ NDVI نگرانی، منڈی قیمت پیش گوئی، مقامی زباناں وچ آوازی صلاح، آف لائن رسائی تے ایس ایم ایس الرٹس، تے ٻہوں کجھ۔",
  "feat.hero.eyebrow": "خاصیتاں",
  "feat.hero.titleLead": "تہاݙے موسم دی ہر",
  "feat.hero.titleAccent": "لوڑ پوری",
  "feat.hero.subtitle": "چوݙاں خاصیتاں رل تے کم کردیاں نیں — پتے سکین کردیاں نیں، خلا توں کھیتی ݙیدھیاں نیں، منڈی پڑھدیاں نیں تے تہاڈی زبان بولدیاں نیں۔ ݙیکھو ہر ہک تہاݙے فارم کیتے کیا کردی اے۔",
  "feat.hero.ctaPrimary": "شروعاتی رسائی حاصل کرو",
  "feat.hero.ctaSecondary": "ایہ کیویں چلدا اے ݙیکھو",
  "feat.hero.builtFor": "پاکستان کیتے بنایا گیا",
  "feat.hero.productOf": "Aplinode دی پیداوار",
  "feat.hero.tile1Label": "پتہ سکین",
  "feat.hero.tile1Value": "94% صحتمند",
  "feat.hero.tile2Label": "منڈی کنک",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کھیت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کیڑے دا خطرہ",
  "feat.hero.tile4Value": "گھٹ · 7 ڈینہ",
  "feat.hero.voiceReady": "آوازی صلاح تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "ایس ایم ایس الرٹ · آف لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — سپرے روکو",
  "feat.intel.eyebrow": "فصل دی سمجھ",
  "feat.intel.heading": "مسلے نقصان توں پہلاں ݙیکھو",
  "feat.intel.sub": "بیماری، کیڑے، موسم تے فصل دا انتخاب — چار فیصلے جو فصل طے کریندن، ہر ہک اپنے انجن نال۔",
  "feat.intel.included": "شامل ہن",
  "feat.intel.doctorCode": "F·01 · ݙیکھݨ",
  "feat.intel.doctorTitle": "اے آئی فصل ڈاکٹر",
  "feat.intel.doctorDesc": "متاثرہ پتے دی تصویر کڈھو تے سیکنڈاں وچ بیماری دا ناں، شدت تے علاج دا منصوبہ گھنو۔",
  "feat.intel.doctorMock": "پتہ سکین نتیجہ جیندے وچ پیلا زنگ زیادہ یقین نال تشخیص کیتا",
  "feat.intel.diseaseName": "پیلا زنگ",
  "feat.intel.matchScore": "94% میل",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درمیانہ",
  "feat.intel.pestCode": "F·02 · پیش گوئی",
  "feat.intel.pestTitle": "کیڑیاں دے حملے دی الرٹ",
  "feat.intel.pestDesc": "موسم تے فصل دا پڑاؤ خطرے دے ماڈل کوں کارآمد کریندے جیہڑا حملے توں ڈینہ پہلاں خبردار کر ڈیندا اے۔",
  "feat.intel.pestMock": "ست ڈینہاں دے کیڑے خطرے دے چارٹ جیہڑا چھیویں ڈینہ مہاندرا تھی ویندا اے",
  "feat.intel.pestAlert": "ہفتہ · ٹڈی دل دا خطرہ 74% — نویں کنک بچاؤ",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم مطابق صلاحاں",
  "feat.intel.weatherDesc": "مقامی پیش گوئیاں تہاڈی فصل تے نشونما دے پڑاؤ نال ملدیاں نیں — صلاح صاف رہنمائی بندی اے، خام ڈیٹا کوئنیں۔",
  "feat.intel.weatherMock": "بہترین موسمی صلاح جیہڑی بارش توں پہلاں آبپاشی وچ تاخیر دا آکھدی اے",
  "feat.intel.delayIrrigation": "اج پانی ڈیون وچ تاخیر کرو",
  "feat.intel.rainNote": "شام 3 وجے بارش دا امکان — پہلاں اسمان کھیتی بھنجاوے۔",
  "feat.intel.waterSaved": "پانی دی بچت",
  "feat.intel.cropCode": "F·04 · منصوبہ بندی",
  "feat.intel.cropTitle": "فصل دی سفارش",
  "feat.intel.cropDesc": "مٹی، موسم، منگ تے تہاڈا بجٹ رل جانچے ویندن — اوہ بوؤ جیہڑا ایں موسم منافع ڈیوے۔",
  "feat.intel.cropMock": "درجہ بند فصل سفارشات جیہناں وچ کنک اتے",
  "feat.intel.crop1": "کنک",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کھیت تے منڈی دی سمجھ",
  "feat.field.headingA": "تہاڈی زمین خلا توں نپی جاندی اے۔",
  "feat.field.headingB": "تہاڈی فصل ڈیٹا نال پرکی جاندی اے۔",
  "feat.field.sub": "ہر ایکڑ تے سیٹلائٹ دا نظارہ تے قریبی ہر منڈی دا جائزہ — تاکہ ودھ تے ویچن ڈوہیں صحیح ویلے ہون۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کھیت نگرانی",
  "feat.field.ndviDesc": "اپنی حد ہک واری نشان زد کرو؛ ہر روشن سیٹلائٹ پاس تے صحت دے زون اپ ڈیٹ تھیندن — کمزور حصے اکھ توں پہلاں سامھے آندن۔",
  "feat.field.ndviMock": "کھیت دی صحت گرڈ جیندے وچ گہرا سبز مضبوط فصل واڈ ڈکھاندا اے",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈی",
  "feat.field.priceTitle": "منڈی قیمت پیش گوئی",
  "feat.field.priceDesc": "قریبی منڈیاں دے موجودہ ریٹ تے رجحان پیش گوئی — تڈاں ویچو جدوں گراف آکھے، خریدار جڈاں آکھے او کوئنیں۔",
  "feat.field.priceMock": "کنک قیمت رجحان اٹھ ہفتیاں وچ مہاندڑ ول، روکے رہن دی سفارش نال",
  "feat.field.wheatTrend": "کنک · 8 ہفتے",
  "feat.field.holdStock": "↑ 12% — مال رکھو",
  "feat.field.financeCode": "F·07 · مالیہ",
  "feat.field.financeTitle": "نفع نقصان جوچ",
  "feat.field.financeDesc": "ہر روپیا آون جان دا، پورا موسم — منڈی یا بینک جان توں پہلاں بریک ایون تے آر او آئی تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ جیندے وچ ان پٹ، مزدوری، آبپاشی تے آمدنی",
  "feat.field.rowInputs": "ان پٹ",
  "feat.field.rowLabour": "مزدوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (اندازہ)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سب کیتے رسائی",
  "feat.voice.headingA": "اسمارٹ فون کوئنیں؟",
  "feat.voice.headingB": "انگریزی کوئنیں؟ تے وی شامل۔",
  "feat.voice.sub": "ودھیا توں وڈی صلاح بے کار اے جے اوہ کسان تک پہنچے ہی کوئنیں۔ ہر خاصیت فون کال جواب ڈیندی اے، آواز سُن دی اے تے سگنل ختم علاقے وچ وی چلدی اے۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "اپنا سوال بولو",
  "feat.voice.speakMock": "رومن سرائیکی وچ صلاح نال آوازی گل ملاپ",
  "feat.voice.chatUser": "میڈی فصل دے پتیاں تے داغ ہن",
  "feat.voice.chatAdvisor": "داغاں دی تصویر بھیجو — میں ہُنیں تشخیص کرینداں۔",
  "feat.voice.inputPlaceholder": "بول تے پچھو…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کرو",
  "feat.voice.callMock": "اگروپیو آوازی مددگار نال ٹول فری کال دی نقل",
  "feat.voice.greetingLine": "اگروپیو وچ تہاڈا سوآگت اے",
  "feat.voice.heardLine": "آواز سمجھ گھدی — جواب تیار اے",
  "feat.voice.callEnded": "کال مکمل · خلاصہ محفوظ",
  "feat.voice.anyPhone": "ہر فون تے · انٹرنیٹ دی لوڑ کوئنیں",
  "feat.voice.offlineCode": "F·10 · آف لائن + ایس ایم ایس",
  "feat.voice.offlineTitle": "سگنل ختم علاقے وی نہیں روکدے",
  "feat.voice.offlineDesc": "صلاحاں، ریکارڈ تے کیلکولیٹر بغیر سگنل کم کردے رہندن؛ نیٹ ورک واپسی تے سنبھ سنک تھی ویندن تے اہم الرٹس ایس ایم ایس نال آندن۔",
  "feat.voice.networkStatus": "نیٹ حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 ریکارڈ قطار وچ",
  "feat.voice.smsStamp": "ایس ایم ایس · 07:42",
  "feat.voice.smsMsg": "موسمی الرٹ: بارش شام 3 وجے — سپرے دا ویلہ بدل گھنو۔",
  "feat.manage.eyebrow": "سنبھال تے ودھاؤ",
  "feat.manage.headingA": "صلاح شروعات اے۔",
  "feat.manage.headingB": "باقی سنبھ ریکارڈ تے چلدا اے۔",
  "feat.manage.sub": "تریخ، سبسڈی، پائیداری تے کساناں دی کمیونٹی — خاموش خاصیتاں جیہڑیاں ہر موسم جمع تھیندیاں نیں۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈ",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی توں فصل کپن تک، سنبھ ہک ٹائم لائن تے جینوں صلاح جواب توں پہلاں پڑھدی اے۔",
  "feat.manage.timelineMock": "اگست دی فارم سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "ناہر دی واری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریا پایا گیا",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "پتہ سکین",
  "feat.manage.tl3Detail": "صحتمند · کوئی بیماری کوئنیں",
  "feat.manage.schemeCode": "F·12 · اسکیمز",
  "feat.manage.schemeTitle": "سبسڈی تے اسکیم لبھو",
  "feat.manage.schemeDesc": "سرکاری رقم جیہدے تسیں پہلاں توں اہل ہو — لبھی، سمجھائی تے ہک ٹیپ درخواست کیتے جوڑی گئی۔",
  "feat.manage.checklistMock": "اہلیت چیک لسٹ جیندے وچ چار وچوں ترے شرطاں مکمل",
  "feat.manage.check1": "زمین دی تصدیق تھی گئی",
  "feat.manage.check2": "فصل دا موسم مطابقت رکھدا اے",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بینک اکاؤنٹ جڑیا",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پائیداری",
  "feat.manage.carbonTitle": "ساویں طریقےآں دے انعام",
  "feat.manage.carbonDesc": "نامیاتی تے گھٹ ہل دے طریقے درج کرو؛ سیٹلائٹ ساوا احاطہ تصدیق کریندا اے تے کاربن کریڈٹ دی قدر دا اندازہ لاندا اے۔",
  "feat.manage.carbonMock": "کاربن خلاصہ جیندے وچ قبضے والیاں ٹن تے سالانا اندازی قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ قدر / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کسان فورم + ماہر",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کرو، ان کساناں توں جواب گھنو جنہاں پن آپ سامنا کیتا — تصدیق شدہ ماہر صحیح حل نشان زد کریندن۔",
  "feat.manage.threadMock": "کمیونٹی بحث جیندے وچ ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadQuestion": "کپاس وچ سفید مکھی دا ودھیا علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جواب · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "نیم دے تیل دی سپرے، شام کوں — ڈو واری، 5 ڈینہاں دے وقفے تے۔",
};
