import type { CatalogKey } from "./en.ts";

export const skr: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "یہ کیہوں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن ان کرو",
  "nav.signUp": "سائن اپ کرو",
  "nav.getEarlyAccess": "شروعاتی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "nav.dashboard": "ڈیش بورڈ",
  "common.languageSwitcherLabel": "زبان بدلو",
  "notFound.title": "صفہ موجود نئیں",
  "notFound.body": "جو صفہ تہاڑی تلاش اے وہ موجود نئیں یا منتقل ہو چکا ہوگا۔",
  "notFound.backHome": "اگروپیو دے ہوم پر واپس جاؤ",
  "common.builtForPakistan": "پاکستان دے لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "اسمارٹ کھیتی دے لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "ایک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڑے فارم دے ریکارڈ ایک جگہ جمع کردا اے — ڈیٹا کو واضح فیصلوں وچ بدلا ہے، تہاڑی اپنی زبان وچ۔",
  "home.hero.ctaSecondary": "بیکو اہ کیہوں کم کردا اے",
  "home.hero.imageAlt": "کسان کھیت وچ ٹیبلٹ پر اگروپیو استعمال کر رہا اے",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "بہترین",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتیں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتواں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم دے مطابق مشورے",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 زباناں وچ مشورہ",
  "home.ticker.pestAlerts": "کیڑے مکوڑے دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسئلہ",
  "home.problem.title": "کھیتی دے فیصلے اندازے کا کھیل نئیں ہونا چاہیدے",
  "home.problem.subtitle": "پورے پاکستان وچ کسان روایت، مقامی مشورے تے بکھری ہوئی معلومات دے ساتھ بڑے رسک والے فیصلے کردا اں۔ نقصان کٹائی دے وقت چکنا پڑتا اے۔",
  "home.problem.item1Title": "غیر یقینی وقت",
  "home.problem.item1Body": "سینچائی، کھاد، دوا، بوائی، کٹائی — اہم لمحے ابھی بھی اندازے سے طے ہوتے اں، جس سے پیداوار کم تے خرچ ضائع ہوتا اے۔",
  "home.problem.item2Title": "کھویا ہوا فارم ریکارڈ",
  "home.problem.item2Body": "سیزنوں کا علم یادداشت یا بکھری نوٹ بکوں وچ رہتا اے۔ پچھلے سال جو کام آیا، اس سے اس سال سیکھنا ناممکن اے۔",
  "home.problem.item3Title": "بکھرا ہوا مشورہ",
  "home.problem.item3Body": "پڑوسی، دکاندار تے ویڈیوز سب جواب دیتے اں — لیکن چند ہی کسان دی فصل، مٹی، موسم یا علاقے سے ملتی اے۔",
  "home.problem.kicker": "اندازے دی قیمت کٹائی پر چکتی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڑے فارم دی ذہانت،",
  "home.solution.titleB": "ایک جگہ",
  "home.solution.subtitle": "پورے سیزن دے لئی ایک انٹیلیجنس پلیٹ فارم — مشورہ، ریکارڈ، موسم تے بازار تہاڑی زمین دے ڈیٹا سے کم کردا اے، عام مشوروں سے نئیں۔",
  "home.solution.card1Title": "کیا کرنا اے",
  "home.solution.card1Body": "سینچائی، کھاد، کیڑے مار تے کٹائی دے وقت دے لئی ذاتی مشورے — تہاڑی فصل تے حالات دے مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے دے لئی واضح مشورہ۔",
  "home.solution.card2Title": "کب کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی داسدی اے کہ کام کب کرو، تاکہ غلط وقت تے اچانک حالات تہاڑی پیداوار نہ کھائیں۔",
  "home.solution.card2Answer": "حقیقی موسم تے فصل دی نشوونما دے مطابق وقت۔",
  "home.solution.card3Title": "کیا کیا جا چکا اے",
  "home.solution.card3Body": "ہر سرگرمی — سینچائی، ان پٹ، بیماری، اخراجات، کٹائی — منظم ریکارڈ وچ محفوظ جو ہر سیزن کو زیادہ سمجھدار بنائی دیندا اے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ دستیاب۔",
  "home.features.eyebrow": "پلیٹ فارم دے اندر",
  "home.features.titleA": "متعدد انجن،",
  "home.features.titleB": "ایک ذہین پلیٹ فارم",
  "home.features.subtitle": "تہاڑے اپنے الفاظ وچ پہلے سوال توں لے کر پورے سیزن دے ریکارڈ تک — ہر صلاحیت اگلی کو تقویت دیتی اے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی زرعی مشیر",
  "home.features.advisorTopics": "سینچائی · کھاد · کیڑے تے بیماری · کٹائی",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "پیلی پتوں والی گندم پر اگروپیو مشیر توں نمونہ گفتگو",
  "home.features.advisorUserMsg": "میری گندم دے پتے پیلے ہو رہے اں — کیا کروں؟",
  "home.features.advisorReplyTitle": "پیلے پتے — دو عام وجوہات:",
  "home.features.advisorReplyCause1": "پانی دی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے اوقات وچ، صبح 9 بجے توں پہلے پانی دیو۔",
  "home.features.advisorReplyCause2": "نائٹروجن دی کمی",
  "home.features.advisorReplyCause2Rest": "— سب سے پرانے پتے پہلے چیک کرو؛ ضرورت ہو تا یوریا ڈالیو۔",
  "home.features.advisorReplyFooter": "اگر پتوں دے نیچے پیلی دھاریاں نظر آئیں، تصویر بھیجیو — میں بیماری دی تشخیص کر دیanga۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھیو یا بولیو…",
  "home.features.advisorFooter": "اپنی فصل دے بارے وچ کچھ بھی پوچھو — روزمرہ سوالات خوش آمدید اں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر سرگرمی منظم تے درج — تاکہ مشورہ تہاڑی اپنی زمین توں سیکھے۔",
  "home.features.record1Activity": "سینچائی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتوں کا اسکین",
  "home.features.record3Detail": "کوئی بیماری نئیں",
  "home.features.recordsCropTag": "گندم · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · زبان",
  "home.features.languageTitle": "تہاڑی زبان، تہاڑے الفاظ",
  "home.features.languageDesc": "جو سوچتے اں وہی بول کر یا لکھ کر کہیو — تکنیکی انگریزی دی ضرورت نئیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم توں آگاہ رہنمائی",
  "home.features.weatherDesc": "مشورہ تہاڑے تک پہنچنے توں پہلے حقیقی حالات چیک کردا اے — بارش توں پہلے سپرے کر بیٹھے تا سارا زرخیز مال بہہ جائے گا۔",
  "home.features.weatherMockAria": "پانچ دن دی پیشن گوئی جس وچ جمعرات کو اسپرے نہ کرنے دا مشورہ نمایاں اے",
  "home.features.dayMon": "پیر",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "اسپرے روکیو",
  "home.features.weatherLegend": "مقامی موسم دی پیشن گوئی توں مشورہ والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم مسلسل بڑھ رہا اے — مکمل صلاحیتوں کا مجموعہ دیکھو",
  "home.journey.eyebrow": "یہ کیسے کم کردا اے",
  "home.journey.title": "ایک سوال سیزن کا آغاز کردا اے",
  "home.journey.subtitle": "تہاڑے پہلے سوال توں مکمل، ذہین فارم تاریخ تک ایک سادہ راستہ۔",
  "home.journey.step1Title": "اپنا فارم شامل کرو",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بنانے دے لئی مقام، فصل تے بنیادی تفصیلات درج کرو۔",
  "home.journey.step2Title": "اے آئی توں پوچھو",
  "home.journey.step2Body": "اپنا سوال اسی زبان وچ لکھیو یا بولیو جس توں تاہوں سب سے زیادہ آرام دہ ہو۔",
  "home.journey.step3Title": "رہنمائی حاصل کرو",
  "home.journey.step3Body": "اپنی فصل، موسم، مقام تے فارم تاریخ پر مبنی مشورہ حاصل کرو۔",
  "home.journey.step4Title": "سرگرمی درج کرو",
  "home.journey.step4Body": "چند ٹیپاں وچ سینچائی، کھاد، دوا یا بیماری درج کرو۔",
  "home.journey.step5Title": "تاریخ بناؤ",
  "home.journey.step5Body": "ہر ریکارڈ مستقبل دے مشوروں کو زیادہ سمجھدار تے موزوں بنائی دیندا اے۔",
  "home.journey.step6Title": "نگهانی جاری رکھو",
  "home.journey.step6Body": "پورے سیزن وچ ریکارڈ دیکھو تے پیش رفت پر نظر رکھو۔",
  "home.matrix.eyebrow": "مکمل صلاحیتوں کا مجموعہ",
  "home.matrix.title": "ضروری توں حیران کن تک",
  "home.matrix.subtitle": "ہر خصوصیت فصل بچائی دیندی اے، خرچ کم کردا اے یا آمدنی بڑھائی دیندی اے۔ اسے پنچانگ دی طرح پڑھو — ہر درجہ پچھلے پر تعمیر ہوتا اے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتیں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی سطح",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری دی شناخت",
  "home.matrix.t1f1Body": "متاثرہ پتے دی تصویر اپ لوڈ کرو تے فوری تشخیص، شدت تے علاج دی سفارشات حاصل کرو۔",
  "home.matrix.t1f2Title": "سیٹلائٹ فیلڈ مانیٹرنگ",
  "home.matrix.t1f2Body": "اپنے کھیت دی حد متعین کرو تے مفت سینٹینل-2 تصویروں توں این ڈی وی آئی پر مبنی فصل دی صحت دیکھو۔",
  "home.matrix.t1f3Title": "سمارٹ موسمی مشورہ",
  "home.matrix.t1f3Body": "مقامی موسم دی پیشن گوئی تہاڑی فصل تے نشوونما دے مرحلے سے مل کر روزانہ قابلِ عمل مشورہ بنائی دیندی اے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر تے پیشن گوئی",
  "home.matrix.t1f4Body": "قریبی منڈی دیاں قیمتیں اے آئی رجحانات دے ساتھ دیکھو، تاکہ صحیح وقت پر بیچو۔",
  "home.matrix.tier2Name": "امتیازی خصوصیات",
  "home.matrix.tier2Badge": "نمایاں",
  "home.matrix.t2f1Title": "علاقائی زباناں وچ وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولیو یا لکھو — جواب اسی زبان وچ سنیو جو تاہوں بہتر سمجھدا اے۔",
  "home.matrix.t2f2Title": "سرکاری اسکیم میچر",
  "home.matrix.t2f2Body": "اپنی معلومات درج کرو تے ہر اہل اسکیم دریافت کرو — دستاویزات تے درخواست دے لنکس سمیت۔",
  "home.matrix.t2f3Title": "فصل دی سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن وچ تہاڑی مٹی، موسم، منڈی دی مانگ تے بجٹ دے مطابق سب سے منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع تے حقیقی اخراجات، پیداوار، آمدنی تے نفع — بریک ایون تے آر او آئی دے ساتھ۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم تے ماہر رابطہ",
  "home.matrix.t2f5Body": "سوالات پوسٹ کرو، تصاویر شیئر کرو، ہم منصف کساناں تے تصدیق شدہ ماہرین توں جواب لیو۔",
  "home.matrix.tier3Name": "حیرت انگیز",
  "home.matrix.tier3Badge": "سب سے آگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی دا مشاہدہ",
  "home.matrix.t3f1Body": "سلائیڈر دے ساتھ وقت دے ساتھ سیٹلائٹ تصاویر موازنہ کرو — نشوونما، نقصان یا قبضہ ٹریک کرو۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیشن گوئی",
  "home.matrix.t3f2Body": "موسم، فصل دے مرحلے تے تاریخ دی بنیاد پر ممکنہ کیڑے حملے توں پہلے ابتدائی انتباہ۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر پر کال کرو، سوال بولیو، اپنی زبان وچ مشورہ سنیو — اسمارٹ فون ضروری نئیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ تخمینہ",
  "home.matrix.t3f4Body": "پائیدار طریقے درج کرو تے رضاکارانہ مارکیٹوں توں کاربن کریڈٹ کا تخمینہ لیو۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت وچ آف لائن کم کرے، کنکشن پر سنک ہو، کمزور نیٹ پر ایس ایم ایس اطلاع دے۔",
  "home.vision.eyebrow": "تصور",
  "home.vision.titleA": "پاکستان دے لئی بنایا گیا۔",
  "home.vision.titleB": "دنیا دے لئی تیار۔",
  "home.vision.pkTitle": "پاکستان کو ترجیح دینے والا طریقہ",
  "home.vision.pkBody": "پہلا ورژن پاکستان دے کھیتوں دے لئی ڈیزائن کیا گیا اے: مقامی فصلیں، علاقائی زبانیں، حقیقی کھیتی دے طریقے تے حقیقی میدانی حالات۔",
  "home.vision.pkPoint1": "مقامی فصل تے موسم دا علم",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "حقیقی کساناں دی رائے توں بہتر بنایا گیا",
  "home.vision.worldTitle": "عالمی توسیع کا تصور",
  "home.vision.worldBody": "موافقت دے لئی بنایا گیا۔ جیویں جیویں پلیٹ فارم بالغ ہوگا، یہ نئے ممالک، زباناں، فصلوں تے موسموں تک پھیلے گا — شروع توں دوبارہ بنائے بغیر۔",
  "home.vision.worldPoint1": "ملک دے مطابق زرعی علم",
  "home.vision.worldPoint2": "اضافی زبانیں تے مقامی فصلیں",
  "home.vision.worldPoint3": "گہرے ڈیٹا انٹیگریشنز تے تجزیے",
  "home.users.title1": "انفرادی کسان",
  "home.users.desc1": "چھوٹے تے درمیانے فارم جنہیں عملی رہنمائی تے ہر سرگرمی دا منظم ریکارڈ درکار اے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہیں منظم معلومات، فیصلہ سازی وچ مدد تے ٹیم بھر دے ریکارڈ درکار اں۔",
  "home.users.title3": "ایکو سسٹم پارٹنرز",
  "home.users.desc3": "ان پٹ سپلائرز، کوآپریٹو، انشورنس کمپنیاں تے ایکسٹینشن سروسز جو وقت دے ساتھ پلیٹ فارم سے جڑیں گی۔",
  "home.users.tagline": "سب سے پہلے کساناں دے لئی ڈیزائن کردہ — ایکو سسٹم دے ساتھ بڑھتا ہوا",
  "home.cta.eyebrow": "ابتدائی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم پر لاؤ",
  "home.cta.subtitle": "اگروپیو دے ساتھ بہتر فیصلے کرنے والے کساناں وچ شامل ہو — پاکستان توں آغاز، دنیا بھر وچ توسیع۔",
  "home.cta.success": "تہاں فہرست وچ شامل ہو۔ جب تہاڑا علاقہ کھلے گا تا اساں تہاڑے نال رابطہ کریں گے۔",
  "home.cta.emailLabel": "ای میل کا پتہ",
  "home.cta.fineprint": "کوئی اسپام نئیں۔ کبھی بھی ان توں ان سبسکرائب کرو۔",
  "home.footer.tagline": "اے آئی توں چلنے والا فارم انٹیلیجنس پلیٹ فارم۔ مشاورت، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے ریکارڈ — مٹی تے سگنل، ساتھ ساتھ۔",
  "home.footer.pagesHeading": "صفحات",
  "home.footer.pagesNavLabel": "فوٹر صفحات",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس دیاں شرائط",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کرو",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔ جملہ حقوق محفوظ اں۔",
  "home.footer.motto": "پاکستان دے لئی بنایا · دنیا دے لئی تیار",
  "hiw.meta.title": "یہ کیسے کم کردا اے — اگروپیو",
  "hiw.meta.description": "ایک منٹ دے فارم پروفائل توں لے کر مسلسل بہتر ہونے والے موسمی چکر تک: دیکھو کہ اگروپیو سوالات، سرگرمیوں تے ریکارڈ کو ذاتی زرعی رہنمائی وچ کیسے بدلتا اے۔",
  "hiw.hero.eyebrow": "یہ کیسے کم کردا اے",
  "hiw.hero.titleA": "چھ چھوٹے مرحلے۔",
  "hiw.hero.titleLead": "ایک",
  "hiw.hero.titleAccent": "زیادہ سمجھدار موسم۔",
  "hiw.hero.subtitle": "اگروپیو ویسے ہی کم کردا اے جیویں کھیتی پہلے سے چلدی اے — تاہوں بوائی کردا اے، پوچھدا اے، کم کردا اے تے ریکارڈ کردا اے۔ فرق صرف یہ اے کہ اب ہر مرحلہ اگلے کو بہتر بنائی دیندا اے۔",
  "hiw.hero.browseFeatures": "خصوصیات دیکھو",
  "hiw.route.navLabel": "اگروپیو دے موسمی چکر دے چھ مرحلے",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بناؤ",
  "hiw.route.stop2": "پوچھو",
  "hiw.route.stop3": "رہنمائی",
  "hiw.route.stop4": "کم کرو",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "ایک بار سیٹ اپ کرو",
  "hiw.setup.title": "تہاڑا فارم ایک زندہ پروفائل بن جاںدا اے",
  "hiw.setup.body": "چار خانے، ایک منٹ توں کم — ضلع، فصل، بوائی دی تاریخ تے زمین کا رقبہ۔ یہی پورا فارم اے۔ اس دے بعد ہر جواب جاندا اے کہ یہ کہاں تے کن حالات وچ اگ رہا اے۔",
  "hiw.setup.point1": "فصل بدلو یا کسی بھی وقت نئے فارم شامل کرو",
  "hiw.setup.point2": "ٹھیکیداروں تے ڈیلرز دے لئی متعدد فارمز",
  "hiw.setup.point3": "کچھ تکنیکی نئیں پوچھا جاںدا — مٹی دی رپورٹ دی ضرورت نئیں",
  "hiw.setup.mockHeading": "نیا فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بناؤ",
  "hiw.setup.mockFootnote": "ایک منٹ توں کم لگدا اے",
  "hiw.setup.mockLabel": "فارم پروفائل فارم جس وچ ضلع، فصل، بوائی دی تاریخ تے زمین کا رقبہ درج اے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربیع",
  "hiw.setup.rowSowing": "بوائی دی تاریخ",
  "hiw.setup.valSowing": "20 نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "12 ایکڑ",
  "hiw.ask.eyebrow": "جو دل چاہے پوچھو",
  "hiw.ask.titleA": "ایک سوال جائے۔",
  "hiw.ask.titleB": "تہاڑا سارا فارم جواب دیندا اے۔",
  "hiw.ask.body": "ایک ہی سوال مختلف فارموں پر مختلف مطلب رکھدا اے۔ اس لئی جواب دینے توں پہلے اگروپیو اس سوال کو تہاڑے فارم دے بارے وچ معلوم ہر چیز سے ملا کر دیکھدا اے۔",
  "hiw.ask.pipelineLabel": "کسان کا سوال فصل، ضلع، موسم تے تاریخ دے تناظر دے ساتھ ملا کر ذاتی جواب بنایا جاںدا اے",
  "hiw.ask.question": "اب پانی دینا چاہیے یا تھوڑا انتظار؟",
  "hiw.ask.checkedAgainst": "ان چیزوں سے ملا کر",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · گٹھیاں نکلنے کا وقت",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26° · خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخچہ",
  "hiw.ask.chipValHistory": "یوریا 9 دن پہلے",
  "hiw.ask.answer": "دو دن رکیو — بارش کا امکان اے، تے یوریا دے بعد زمین ابھی گیلی اے۔ جمعے تک دیکھ لینا کافی اے۔",
  "hiw.ask.answerMeta": " ذاتی جواب · گندم، یوریا دے 9 دن بعد",
  "hiw.ask.footnote": "لکھو، بولیو یا کال کرو — جواب ہر صورت تہاڑے فارم دا اپنا ہوتا اے",
  "hiw.engine.eyebrow": "جواب دے پیچھے",
  "hiw.engine.title": "چار جانچیں اس سے پہلے کہ تاہوں ایک سطر دیکھیو",
  "hiw.engine.body": "رہنمائی کوئی سرچ نتیجہ نئیں۔ یہ چار دروازوں توں گزردا اے تاکہ جو تہاڑے تک پہنچے وہ اسی کھیت دے لئی، اسی ہفتے دے لئی محفوظ ہو۔",
  "hiw.engine.check1Title": "معلومات جمع کرنا",
  "hiw.engine.check1Desc": "فارم پروفائل، موجودہ موسم تے فصل دا مرحلہ بھیجنے دے لمحے ساتھ ساتھ جمع کیا جاںدا اے۔",
  "hiw.engine.check2Title": "مطابقت دی جانچ",
  "hiw.engine.check2Desc": "مشورے کو موسم دی پیش گوئی سے پرکھا جاںدا اے — بارش وچ بے کار ہونے والا سپرے انجن توں نکلدا ہی نئیں۔",
  "hiw.engine.check3Title": "ذاتی بنانا",
  "hiw.engine.check3Desc": "تہاڑے کھیت دی تاریخ جواب کو بدل دیندی اے — وہی فصل، الگ مٹی، الگ مشورہ۔",
  "hiw.engine.check4Title": "پہنچانا",
  "hiw.engine.check4Desc": "پھر وہ تہاڑی زبان وچ صاف اقدامات بن کر آتا اے — اسکرین پر، آواز وچ یا فون کال پر۔",
  "hiw.engine.safetyStrong": "اگر کچھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest": "تا اگروپیو انتظار دا کہہ دیندا اے — دیر توں ملنے والا جواب بے کار ہوا سپرے یا تباہ فصل توں بہتر اے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کرو",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی دینا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل کاٹنا",
  "hiw.record.row1Time": "آج · صبح 6:40",
  "hiw.record.row1Label": "پانی دینا درج ہوا",
  "hiw.record.row1Detail": "نہر کا موڑ · 40 منٹ · پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج ہوئی",
  "hiw.record.row2Detail": "DAP 20 کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف دو ٹیپ — آف لائن بھی چلدا اے",
  "hiw.record.mockLabel": "سرگرمی ریکارڈر جس وچ فوری ایکشن چپس تے حال ہی وچ درج شدہ اندراجات اں",
  "hiw.record.eyebrow": "جیویں جیویں کم کرو، ریکارڈ کرتے جاؤ",
  "hiw.record.titleA": "ابھی دو ٹیپ،",
  "hiw.record.titleB": "پورے موسم بہتر جواب",
  "hiw.record.body": "ریکارڈنگ کھیت دے لئی بنائی گئی اے — بڑے بٹن، کم خانے، ٹائپنگ دی ضرورت نئیں۔ ہر اندراج فارم دی یادداشت دا حصہ بن جاںدا اے، تا مشورہ بھی فصل دے ساتھ ساتھ تیز ہوتا جاںدا اے۔",
  "hiw.record.point1": "پانی، کھادیں، بیماری، خرچ، فصل — سب ایک ٹائم لائن پر",
  "hiw.record.point2": "مکمل آف لائن چلدا اے؛ سگنل آنے پر خود سنک ہو جاںدا اے",
  "hiw.record.point3": "بینک، خریدار یا انشورنس دے لئی موسمی خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "یہ فصل کاٹنے پر ختم نئیں ہوتا۔",
  "hiw.loop.titleB": "وہاں توں شروع ہوتا اے۔",
  "hiw.loop.body": "پوچھو، کم کرو، ریکارڈ کرو — دہرائیں۔ چکر دی ہر گرد اگروپیو کو تہاڑی زمین دے بارے وچ نیا کچھ سکھائی دیندا اے، تاکہ اگلا موسم پچھلے توں آگے شروع ہو۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماںدا اے",
  "hiw.loop.benefit1Desc": "پچھلے موسم دی بیماری، خوراک، تاریخیں اس موسم دا پہلا جواب بنا دیاں اں۔",
  "hiw.loop.benefit2Title": "کچھ دہرانا نئیں پڑدا",
  "hiw.loop.benefit2Desc": "مشاورت جاندی اے کہ کیا پہلے سپرے یا کھاد ہو چکی اے — دوہری خوراک دا خطرہ نئیں۔",
  "hiw.loop.benefit3Title": "ہر موسم دستاویزی",
  "hiw.loop.benefit3Desc": "صاف تاریخ قرضے، خریدار، انشورنس یا اگلی فصل دے فیصلے دے لئی تیار رہندی اے۔",
  "hiw.loop.stepLearn": "سیکھو",
  "hiw.loop.stepImprove": "بہتر بناؤ",
  "hiw.loop.diagramLabel": "گول چکر خاکہ: پوچھو، کم کرو، ریکارڈ کرو، سیکھو، بہتر بناؤ",
  "hiw.loop.centerSeason": "موسم",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر موسم، پچھلے توں بہتر",
  "feat.meta.title": "خصوصیات — اگروپیو",
  "feat.meta.description": "اگروپیو دی ہر خصوصیت دیکھو: اے آئی فصل ڈاکٹر، سیٹلائٹ NDVI نگرانی، منڈی قیمت دی پیشن گوئی، مقامی زباناں وچ آوازی مشاورت، آف لائن رسائی تے ایس ایم ایس الرٹس، تے بہت کچھ۔",
  "feat.hero.eyebrow": "خصوصیات",
  "feat.hero.titleLead": "تہاڑے موسم دی ہر",
  "feat.hero.titleAccent": "ضرورت پوری",
  "feat.hero.subtitle": "چودہ خصوصیات ایک ساتھ کم کردا اں — پتے اسکین کردا اں، خلا توں کھیت دیکھدا اں، منڈی پڑھدا اے تے تہاڑی زبان بولدا اے۔ دیکھو ہر ایک تہاڑے فارم دے لئی کیا کردا اے۔",
  "feat.hero.ctaPrimary": "ابتدائی رسائی حاصل کرو",
  "feat.hero.ctaSecondary": "دیکھو یہ کیسے کم کردا اے",
  "feat.hero.builtFor": "پاکستان دے لئی بنایا گیا",
  "feat.hero.productOf": "Aplinode دی پیداوار",
  "feat.hero.tile1Label": "پتہ اسکین",
  "feat.hero.tile1Value": "94% ٹھیک",
  "feat.hero.tile2Label": "منڈی گندم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کھیت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کیڑے دا خطرہ",
  "feat.hero.tile4Value": "کم · 7 دن",
  "feat.hero.voiceReady": "آوازی مشاورت تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "ایس ایم ایس الرٹ · آف لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — سپرے روکیو",
  "feat.intel.eyebrow": "فصل دی ذہانت",
  "feat.intel.heading": "مسائل نقصان توں پہلے دیکھو",
  "feat.intel.sub": "بیماری، کیڑے، موسم تے فصل دا انتخاب — چار فیصلے جو فصل طے کردا اں، ہر ایک اپنے انجن دے ساتھ۔",
  "feat.intel.included": "شامل اے",
  "feat.intel.doctorCode": "F·01 · وژن",
  "feat.intel.doctorTitle": "اے آئی فصل ڈاکٹر",
  "feat.intel.doctorDesc": "متاثرہ پتے دی تصویر لیو تے سیکنڈوں وچ بیماری دا نام، شدت تے علاج کا منصوبہ پائیو۔",
  "feat.intel.doctorMock": "پتہ اسکین نتیجہ جس وچ پیلے زنگ دی زیادہ یقین دے ساتھ تشخیص",
  "feat.intel.diseaseName": "پیلا زنگ",
  "feat.intel.matchScore": "94% مماثلت",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درمیانہ",
  "feat.intel.pestCode": "F·02 · پیش گوئی",
  "feat.intel.pestTitle": "کیڑوں دے حملے دے الرٹس",
  "feat.intel.pestDesc": "موسم تے فصل دا مرحلہ خطرے کے ماڈل کو کھلاتا اے جو حملے توں دن پہلے خبردار کر دیندا اے۔",
  "feat.intel.pestMock": "سات دن دے کیڑے خطرے دے بار جو چھٹے دن بلندی پر جاتے اں",
  "feat.intel.pestAlert": "ہفتہ · ٹڈی دل کا خطرہ 74% — نئی گندم کو محفوظ بناؤ",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم دے مطابق مشورے",
  "feat.intel.weatherDesc": "مقامی پیش گوئیاں تہاڑی فصل تے نشونما دے مرحلے سے ملیتی اں — مشورہ صاف ہدایت بن کر آتا اے، خام ڈیٹا نئیں۔",
  "feat.intel.weatherMock": "مثالی موسمی مشورہ جو بارش توں پہلے آبپاشی وچ تاخیر دا کہہ دیندا اے",
  "feat.intel.delayIrrigation": "آج پانی دینے وچ تاخیر کرو",
  "feat.intel.rainNote": "شام 3 بجے بارش کا امکان — پہلے آسمان کو کھیت سیراب کرن دیو۔",
  "feat.intel.waterSaved": "پانی دی بچت",
  "feat.intel.cropCode": "F·04 · منصوبہ بندی",
  "feat.intel.cropTitle": "فصل دی سفارش",
  "feat.intel.cropDesc": "مٹی، موسم، مانگ تے تہاڑا بجٹ ایک ساتھ جانچے جاتے اں — وہ بوئیں جو اس موسم منافع دیں۔",
  "feat.intel.cropMock": "درجہ بند فصل سفارشات جس وچ گندم اوپر",
  "feat.intel.crop1": "گندم",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کھیت تے منڈی دی ذہانت",
  "feat.field.headingA": "تہاڑی زمین خلا توں ناپی جاںدی اے۔",
  "feat.field.headingB": "تہاڑی فصل ڈیٹا توں پرکی جاںدی اے۔",
  "feat.field.sub": "ہر ایکڑ پر سیٹلائٹ دیاں نظریں تے قریبی ہر منڈی دا جائزہ — تاکہ نشونما تے فروخت دونوں صحیح وقت پر ہوں۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کھیت نگرانی",
  "feat.field.ndviDesc": "اپنی حد ایک بار نشان زد کرو؛ ہر صاف سیٹلائٹ پاس پر صحت کے زون اپ ڈیٹ ہوتے اں — کمزور حصے آنکھ توں پہلے سامنے آتے اں۔",
  "feat.field.ndviMock": "کھیت صحت گرڈ جس وچ گہرا سبز مضبوط فصل نشونما ظاہر کردا اے",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈی",
  "feat.field.priceTitle": "منڈی قیمت پیشن گوئی",
  "feat.field.priceDesc": "قریبی منڈیوں دی موجودہ ریٹس تے رجحان دی پیشن گوئی — اس وقت بیچو جب گراف کہے، خریدار جب کہے نئیں۔",
  "feat.field.priceMock": "گندم قیمت رجحان آٹھ ہفتوں وچ بلندی دی طرف، رکے رہنے دی سفارش دے ساتھ",
  "feat.field.wheatTrend": "گندم · 8 ہفتے",
  "feat.field.holdStock": "↑ 12% — مال رکھو",
  "feat.field.financeCode": "F·07 · مالیات",
  "feat.field.financeTitle": "نفع و نقصان ٹریک",
  "feat.field.financeDesc": "ہر روپیہ آنے تے جانے کا، پورے موسم — منڈی یا بینک جانے توں پہلے بریک ایون تے آر او آئی تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ جس وچ ان پٹ، مزدوری، آبپاشی تے آمدنی",
  "feat.field.rowInputs": "ان پٹس",
  "feat.field.rowLabour": "مزدوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (تخمینی)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سب دے لئی رسائی",
  "feat.voice.headingA": "اسمارٹ فون نئیں؟",
  "feat.voice.headingB": "انگریزی نئیں؟ پھر بھی شامل۔",
  "feat.voice.sub": "بہترین مشورہ بے کار اے اگر وہ کسان تک پہنچے ہی نئیں۔ ہر خصوصیت فون کال جواب دیندی اے، آواز سنتی اے تے سگنل ختم علاقے وچ بھی چلدا اے۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "اپنا سوال بولیو",
  "feat.voice.speakMock": "رومن اردو وچ مشاورت توں آوازی گفتگو",
  "feat.voice.chatUser": "میری فصل دے پتوں پر دھبے اں",
  "feat.voice.chatAdvisor": "دھبوں دی تصویر بھیجو — میں ابھی تشخیص کردا ہاں۔",
  "feat.voice.inputPlaceholder": "بول کر پوچھو…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کرو",
  "feat.voice.callMock": "اگروپیو وائس اسسٹنٹ دے ساتھ ٹول فری کال دی نقل",
  "feat.voice.greetingLine": "اگروپیو وچ تہاڑا خوش آمدید اے",
  "feat.voice.heardLine": "آواز سمجھ لی — جواب تیار اے",
  "feat.voice.callEnded": "کال ختم · خلاصہ محفوظ",
  "feat.voice.anyPhone": "کسی بھی فون پر · انٹرنیٹ نئیں چاہیدا",
  "feat.voice.offlineCode": "F·10 · آف لائن + ایس ایم ایس",
  "feat.voice.offlineTitle": "سگنل ختم علاقے بھی نئیں روکتے",
  "feat.voice.offlineDesc": "مشورے، ریکارڈ تے کیلکولیٹر بغیر سگنل کم کردا رہندے اں؛ نیٹ ورک واپسی پر سب سنک ہو جاںدا اے تے اہم الرٹس ایس ایم ایس توں آتے اں۔",
  "feat.voice.networkStatus": "نیٹ ورک حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 ریکارڈ قطار وچ",
  "feat.voice.smsStamp": "ایس ایم ایس · 07:42",
  "feat.voice.smsMsg": "موسم الرٹ: بارش شام 3 بجے — سپرے کا وقت بدل لیو۔",
  "feat.manage.eyebrow": "نبھاؤ تے بڑھاؤ",
  "feat.manage.headingA": "مشورہ ابتدا اے۔",
  "feat.manage.headingB": "باقی سب ریکارڈ پر چلدا اے۔",
  "feat.manage.sub": "تاریخچہ، سبسڈی، پائیداری تے کساناں دی کمیونٹی — خاموش خصوصیات جو ہر موسم جمع ہوتی اں۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈز",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی توں کٹائی تک، سب ایک ٹائم لائن پر جسے مشاورت جواب توں پہلے پڑھدا اے۔",
  "feat.manage.timelineMock": "اگست دی فارم سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "نہر دی باری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریا دیا گیا",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "پتہ اسکین",
  "feat.manage.tl3Detail": "صاف · کوئی بیماری نئیں",
  "feat.manage.schemeCode": "F·12 · اسکیمز",
  "feat.manage.schemeTitle": "سبسڈی تے اسکیم تلاش",
  "feat.manage.schemeDesc": "سرکاری رقم جس دے تاہوں پہلے سے اہل ہو — ملائی، سمجھائی تے ایک ٹیپ درخواست دے لئی جوڑی جاںدی اے۔",
  "feat.manage.checklistMock": "اہلیت چیک لسٹ جس وچ چار توں تین شرطیں مکمل",
  "feat.manage.check1": "زمین دی تصدیل ہوئی",
  "feat.manage.check2": "فصل دا موسم مطابقت رکھدا اے",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بینک اکاؤنٹ جڑا",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پائیداری",
  "feat.manage.carbonTitle": "سبز طریقوں دے انعامات",
  "feat.manage.carbonDesc": "نامیاتی تے کم ہل کے طریقے درج کرو؛ سیٹلائٹ سبز احاطہ تصدیق کردا اے تے کاربن کریڈٹ دی قدر کا تخمینہ لگائی دیندا اے۔",
  "feat.manage.carbonMock": "کاربن خلاصہ جس وچ قبضہ شدہ ٹن تے سالانہ تخمینی قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ قدر / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کسان فورم + ماہرین",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کرو، ان کساناں توں جواب پائیو جنہوں نے خود سامنا کیا — تصدیق شدہ ماہرین درست حل نشان زد کردا اں۔",
  "feat.manage.threadMock": "کمیونٹی بحث جس وچ ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadQuestion": "کپاس وچ سفید مکھی دا بہترین علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جوابات · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر دی تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "نیم دے تیل کا سپرے، شام کو — دو بار، 5 دن دے وقفے پر۔",
  "vp.meta.title": "ویژن — اگروپیو",
  "vp.meta.description": "اگروپیو کا وژن: ہر کسان دی جیب وچ ذہین زرعی رہنمائی — پاکستان توں آغاز، پانچ عقائد، تین افق تے وعدے جن توں کوئی سمجھوتہ نئیں۔",
  "vp.hero.eyebrow": "ساڈا وژن",
  "vp.hero.titleLead": "ایک قابل اعتماد مشیر",
  "vp.hero.titleAccent": "ہر کسان دی جیب وچ۔",
  "vp.hero.sub": "ذہین رہنمائی دا انحصار دولت، خواندگی یا زبان پر نئیں ہونا چاہیدا۔ اگروپیو اس لئی موجود اے تاکہ ہر کسان — کسی بھی فون پر، کسی بھی گاؤں وچ — اسی اعتماد سے کھیتی کرے جیویں کوئی ماہر ساتھ کھڑا ہو۔",
  "vp.hero.tagStart": "ضرورت سب سے پہلے",
  "vp.hero.tagThen": "پھر پوری دنیا",
  "vp.hero.ctaLink": "دیکھو اساں نے کیا بنایا",
  "vp.beliefs.eyebrow": "ساڈے عقائد",
  "vp.beliefs.heading": "پانچ عقائد ہر فیصلے کی شکل دیتے اں",
  "vp.beliefs.b1Title": "ترقی",
  "vp.beliefs.b1Desc": "زندہ فصلیں، صحتمند زمین، خوشحال کسان۔",
  "vp.beliefs.b2Title": "ذہانت",
  "vp.beliefs.b2Desc": "مقامی موسم، تاریخ تے فصل سائنس پر مبنی اے آئی۔",
  "vp.beliefs.b3Title": "رسائی",
  "vp.beliefs.b3Desc": "ہر کسان دی اپنی زبان تے اپنے ماحول وچ رہنمائی۔",
  "vp.beliefs.b4Title": "اعتماد",
  "vp.beliefs.b4Desc": "عملی، بروقت مشورہ جو روزگار کا تحفظ کرے۔",
  "vp.beliefs.b5Title": "مستقبل",
  "vp.beliefs.b5Desc": "روایت دا احترام کرن والی توسیع پذیر ٹیکنالوجی۔",
  "vp.horizons.eyebrow": "آنے والا راستہ",
  "vp.horizons.heading": "تین افق، ایک سمت",
  "vp.horizons.h1Tag": "افق 01",
  "vp.horizons.h1Phase": "ابھی",
  "vp.horizons.h1Status": "کھیتوں وچ",
  "vp.horizons.h1Body": "سب سے پہلے پاکستان۔ مرکزی مشیر، ڈیجیٹل فارم ریکارڈ، موسم توں آگاہ رہنمائی تے چھ علاقائی زبانیں — کسی اور چیز توں پہلے حقیقی کساناں دی رائے توں مکمل۔",
  "vp.horizons.h1P1": "مرکزی مشیر + ریکارڈ",
  "vp.horizons.h1P2": "چھ زبانیں",
  "vp.horizons.h1P3": "حقیقی کساناں توں بہتری",
  "vp.horizons.h2Tag": "افق 02",
  "vp.horizons.h2Phase": "اگلا مرحلہ",
  "vp.horizons.h2Status": "پھیلاؤ",
  "vp.horizons.h2Body": "گھر وچ گہرائی تے وسعت — پاکستان بھر وچ مزید فصلیں تے علاقے، زرعی ڈیٹا ذرائع توں مضبوط تعلق، تے وہ تجزیات جو ہر سفارش کو زیادہ ذاتی بنائی دیندے اں۔",
  "vp.horizons.h2P1": "مزید فصلیں تے علاقے",
  "vp.horizons.h2P2": "ڈیٹا انٹیگریشنز",
  "vp.horizons.h2P3": "جدید تجزیات",
  "vp.horizons.h3Tag": "افق 03",
  "vp.horizons.h3Phase": "بعد وچ",
  "vp.horizons.h3Status": "عالمگیر",
  "vp.horizons.h3Body": "پلیٹ فارم نئے ملکوں، موسموں، فصلوں، زباناں تے طریقوں دے مطابق ڈھل جاںدا اے — عالمی سطح پر ڈھلنے والی زرعی ذہانت، بغیر صفر توں شروع کیے۔",
  "vp.horizons.h3P1": "نئے ملک",
  "vp.horizons.h3P2": "نئی زبانیں تے موسم",
  "vp.horizons.h3P3": "عالمی پلیٹ فارم",
  "vp.outcomes.eyebrow": "کامیابی کی شکل",
  "vp.outcomes.heading": "چار نتائج جن پر اساں خود کو تولتے اں",
  "vp.outcomes.sub": "وژن ایپ نئیں — فارم پر بدلنے والی حالت اے۔ ہر چیز ان چار نتائج دے مقابل جاری ہوتی اے۔",
  "vp.outcomes.o1Title": "بہترین فیصلے",
  "vp.outcomes.o1Desc": "ہر انتخاب — پانی، ان پٹ، وقت — عادات دے بجائے ڈیٹا پر مبنی۔",
  "vp.outcomes.o2Title": "زیادہ پیداوار",
  "vp.outcomes.o2Desc": "صحتمند فصلیں، وقت پر ان پٹ، تے عروج پر کٹی فصل۔",
  "vp.outcomes.o3Title": "کم بچائے جا سکنے والے نقصانات",
  "vp.outcomes.o3Desc": "بیماری، کیڑے تے موسم بروقت پکڑے گئے — فصل کھونے توں پہلے۔",
  "vp.outcomes.o4Title": "فارم کاروبار کی طرح",
  "vp.outcomes.o4Desc": "منظم ریکارڈ تے موسمی ذہانت جسے بینک تے خریدار تسلیم کریں۔",
  "vp.principles.eyebrow": "سمجھوتہ نئیں",
  "vp.principles.heading": "وہ وعدے جن پر اساں بناتے اں",
  "vp.principles.sub": "وژن تفصیلات وچ ناکام ہوتا اے۔ یہ عہد ہر خاصیت، ہر صفحہ، ہر ریلیز پر لاگو اں — آج توں۔",
  "vp.principles.c1Title": "کسان کا فائدہ اول",
  "vp.principles.c1Desc": "ہر خاصیت کھیت دی ضرورت توں شروع ہوتی اے — ٹیکنالوجی توں کبھی نئیں۔",
  "vp.principles.c2Title": "زبان پہلے",
  "vp.principles.c2Desc": "ہر اسکرین تے ہر جواب کسان دی اپنی زبان وچ پہنچدا اے۔",
  "vp.principles.c3Title": "دھوپ وچ پڑھنے کے قابل",
  "vp.principles.c3Desc": "تیز کنٹراسٹ دوپہر دی دھوپ دے لئی، صرف دفتر دے لئی نئیں۔",
  "vp.principles.c4Title": "سادہ الفاظ",
  "vp.principles.c4Desc": "اتنے سادہ کہ ایک پڑوسی دوسرے کو سمجھا سکے۔",
  "vp.principles.c5Title": "پہلے فون",
  "vp.principles.c5Desc": "موبائل فرسٹ، بڑے ٹچ ٹارگٹ — اب کھیتی فون پر ہی چلدا اے۔",
  "vp.principles.c6Title": "طرز وچ قدرتی",
  "vp.principles.c6Desc": "حرکت تے خاکہ جو فطری محسوس ہو — نشوونما، مشینری کبھی نئیں۔",
  "vp.principles.motto": "مٹی تے سگنل — ساتھ ساتھ",
  "wy.meta.title": "اگروپیو کیوں — اے آئی سے لیس فارم ذہانت",
  "wy.meta.description": "کھیتی باڑی دے فیصلے اندازے پر نئیں چھوڑے جا سکتے۔ دیکھو اگروپیو کیسے اے آئی مشیر، فارم ریکارڈ، موسم توں آگاہ رہنمائی تے مقامی زبانیں ایک پاکستان اول پلیٹ فارم پر جمع کردا اے۔",
  "wy.hero.eyebrow": "اگروپیو کیوں",
  "wy.hero.titleLead": "جہاں مٹی ملتی اے",
  "wy.hero.titleAccent": "سگنل سے",
  "wy.hero.sub": "کھیتی باڑی دے فیصلے اندازوں پر نئیں چھوڑے جا سکتے۔ اگروپیو ایک ہی پلیٹ فارم وچ اے آئی مشیر، تہاڑے فارم دا ریکارڈ، موسم توں آگاہ رہنمائی تے تہاڑی اپنی زبان فراہم کردا اے — تاکہ ہر فیصلہ تہاڑی زمین دی حقیقت پر مبنی ہو۔",
  "wy.hero.ctaPrimary": "جلد رسائی حاصل کرو",
  "wy.hero.ctaSecondary": "پلیٹ فارم دیکھو",
  "wy.hero.tagStart": "پاکستان دے لئی بنایا گیا",
  "wy.hero.tagThen": "Aplinode دا پروڈکٹ",
  "wy.hero.svgLabel": "کھیت پر لہراتی ہوئی خم دار بیل بوٹی لکیریں",
  "wy.origin.eyebrow": "اساں نے یہ کیوں بنایا",
  "wy.origin.heading": "اہم فیصلے محض اندازے پر نئیں ٹکے ہونے چاہیدے",
  "wy.origin.sub": "اگروپیو دی شروعات ایک سادہ مشاہدے توں ہوئی: کسان دا موسم چند فیصلوں سے طے ہوتا اے، تے ہر فیصلہ اصل ذہانت دا حقدار اے۔",
  "wy.origin.g1Title": "وقت دا اندازہ",
  "wy.origin.g1Desc": "سینچائی، کھاد، بوائی، کٹائی — موسم دا فیصلہ کرن والے لمحے ابھی بھی عادت تے امید توں چنے جاتے اں۔",
  "wy.origin.g2Title": "تاریخ مٹ جاںدی اے",
  "wy.origin.g2Desc": "کب سپرے ہوا، کب کھیت سیراب ہوا، پچھلے سال کون سی بیماری لگی — کچھ بھی لکھا نئیں جاںدا، اس لئی اس توں کچھ سیکھا نئیں جاںدا۔",
  "wy.origin.g3Title": "مشورے بکھرے ہوئے اں",
  "wy.origin.g3Desc": "پڑوسی، دکاندار تے ویڈیوز ہر ایک جواب دیندا اے — مگر کسی کو پاس تہاڑی فصل، تہاڑی مٹی یا اس ہفتے دی فضا دا اصل علم نئیں ہوتا۔",
  "wy.origin.banner": "اندازے دی قیمت کٹائی دے دن چکانی پڑتی اے",
  "wy.diff.eyebrow": "اسے مختلف کیا بنائی دیندا اے",
  "wy.diff.heading1": "صرف ایک اور مشورے والی ایپ نئیں۔",
  "wy.diff.heading2": "ایک فارم ذہانت دا پلیٹ فارم۔",
  "wy.diff.sub": "زیادہ تر ٹولز صرف سوالوں دے جواب دیتے اں۔ اگروپیو تہاڑے فارم کو سیکھدا اے — تے تہاڑے درج کردہ ہر کم دے ساتھ زیادہ کارآمد ہوتا جاںدا اے۔",
  "wy.diff.personalTitle": "ذاتی نوعیت کا، عام نئیں",
  "wy.diff.personalDesc": "تجاویز تہاڑی فصل، تہاڑے مقام، موجودہ موسم تے تہاڑے فارم دی اپنی تاریخ توں بنتی اں — کبھی سب دے لئی ایک ہی نسخہ نئیں۔",
  "wy.diff.chip1": "تہاڑی فصل",
  "wy.diff.chip2": "تہاڑا ضلع",
  "wy.diff.chip3": "اس ہفتے دا موسم",
  "wy.diff.chip4": "تہاڑا پچھلا موسم",
  "wy.diff.langTitle": "تہاڑی زبان بولدا اے",
  "wy.diff.langDesc": "جیویں تاہوں واقعی بولدا اے اسی طرح پوچھو تے سمجھو — کوئی مشکل انگریزی ضروری نئیں۔",
  "wy.diff.memoryTitle": "ہر فارم دی یادداشت",
  "wy.diff.memoryDesc": "سینچائی، ان پٹ، بیماری، خرچ، کٹائی — ہر کام منظم ریکارڈ وچ محفوظ، تاکہ ہر موسم پچھلے توں بہتر آغاز کرے۔",
  "wy.diff.weatherTitle": "بنیادی طور پر موسم توں آگاہ",
  "wy.diff.weatherDesc": "رہنمائی تہاڑے تک پہنچنے توں پہلے اصل حالات دیکھدی اے — تاکہ بارش توں گھنٹوں پہلے سپرے دا مشورہ نہ دیا جاوے۔",
  "wy.diff.platformTitle": "ایک پلیٹ فارم، پورا موسم",
  "wy.diff.platformDesc": "مشیر، ریکارڈ، موسم دی رہنمائی تے مشاورت مل کر کم کردا اں — الگ ایپس تے کاپیوں وچ بکھرے نئیں رہندے۔",
  "wy.diff.pakTitle": "پاکستان اول",
  "wy.diff.pakDesc": "مقامی فصلیں، علاقائی طریقے تے حقیقی کھیت دے حالات پہلے دن سے ڈیزائن وچ شامل اں — بعد توں جوڑے گئے سوچ دے طور پر نئیں۔",
  "wy.diff.pakBadge": "یہیں توں شروعات",
  "wy.life.eyebrow": "مشیر کس کس وچ رہنمائی کردا اے",
  "wy.life.heading": "فصل دے چکر دے ہر فیصلے دے لئی رہنمائی",
  "wy.life.sub": "ایک مشیر پورے فصلی دور وچ تہاڑے ساتھ رہندا اے — موسم دی منصوبہ بندی توں لے کر فصل گھر پہنچانے تک۔",
  "wy.life.s1Title": "سینچائی دا وقت",
  "wy.life.s1Desc": "جانو کب پانی دینا اے — تے کب انتظار کرنا اے۔",
  "wy.life.s2Title": "فصل دی منصوبہ بندی",
  "wy.life.s2Desc": "اپنی زمین دے موافق فصلیں تے بوائی دی کھڑکیاں منتخب کرو۔",
  "wy.life.s3Title": "کھاد تے کیڑے مار دواؤں دی رہنمائی",
  "wy.life.s3Desc": "صحیح ان پٹ، صحیح مقدار وچ، صحیح وقت پر۔",
  "wy.life.s4Title": "کیڑے تے بیماری وچ مدد",
  "wy.life.s4Desc": "مسائل جلد پکڑو تے پھیلنے توں پہلے عمل کرو۔",
  "wy.life.s5Title": "کٹائی دا وقت",
  "wy.life.s5Desc": "اس لمحے کاٹو جو پیداوار تے معیار دی حفاظت کرے۔",
  "wy.life.s6Title": "موسم توں آگاہ تجاویز",
  "wy.life.s6Desc": "ہر مشورہ پہلے آج دے حالات دیکھدا اے۔",
  "wy.life.s7Title": "روزمرہ سوالات",
  "wy.life.s7Desc": "اپنی فصل دے بارے وچ کچھ بھی پوچھو، موسم دے کسی بھی دن۔",
  "wy.value.eyebrow": "وعدہ",
  "wy.value.heading1": "کیا کرنا اے۔ کب کرنا اے۔",
  "wy.value.heading2": "تے کیا ہو چکا اے۔",
  "wy.value.sub": "اگروپیو دی ہر سہولت ان تین جوابات توں ایک دی خدمت کردا اے — اسی طرح فیصلوں کا موسم اعتماد کا موسم بن جاںدا اے۔",
  "wy.value.p1Heading": "کیا کرنا اے",
  "wy.value.p1Desc": "تہاڑی فصل تے حالات دے مطابق واضح، مخصوص تجاویز — عام نکات نئیں۔",
  "wy.value.p2Heading": "کب کرنا اے",
  "wy.value.p2Desc": "اصل موسم تے نشوونما دے مرحلے دے مطابق وقت، تاکہ صحیح اقدام صحیح لمحے پر ہو۔",
  "wy.value.p3Heading": "کیا ہو چکا اے",
  "wy.value.p3Desc": "ہر کام دی منظم تاریخ — ہمیشہ دستیاب، ہمیشہ بہتر مشورے دی بنیاد۔",
  "wy.who.eyebrow": "کن دے لئی اے",
  "wy.who.heading": "کسان توں شروع ہو کر آگے",
  "wy.who.a1Title": "انفرادی کسان",
  "wy.who.a1Desc": "ہر فیصلے وچ عملی، ذاتی رہنمائی — تے جو کچھ ہو چکا اے اس دا منظم ریکارڈ۔",
  "wy.who.a2Title": "تجارتی فارم تے زرعی کاروبار",
  "wy.who.a2Desc": "ٹیموں، کھیتوں تے موسموں وچ منظم فارم معلومات تے قابلِ بھروسہ فیصلہ سازی دی مدد۔",
  "wy.who.a3Title": "ایکو سسٹم دے شراکت دار",
  "wy.who.a3Desc": "ان پٹ فراہم کرن والے، کوآپریٹو، بیمہ کمپنیاں تے زرعی توسیعی خدمات — جیویں جیویں پلیٹ فارم بڑھدا اے۔",
  "wy.who.strip": "فارم دے گرد ماحول دے ساتھ بڑھتے ہوئے",
  "auth.backHome": "واپس ہوم پر",
  "auth.emailLabel": "ای میل کا پتہ",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاس ورڈ",
  "auth.showPassword": "پاس ورڈ دکھاؤ",
  "auth.hidePassword": "پاس ورڈ چھپاؤ",
  "auth.err.emailRequired": "اپنا ای میل کا پتہ لکھو۔",
  "auth.err.emailInvalid": "درست ای میل کا پتہ لکھو۔",
  "auth.err.passwordRequired": "پاس ورڈ بناؤ۔",
  "auth.err.passwordMin": "کم از کم ۸ حروف استعمال کرو۔",
  "auth.err.passwordMax": "زیادہ سے زیادہ ۶۴ حروف استعمال کرو۔",
  "auth.err.nameRequired": "اپنا پورا نام لکھو۔",
  "auth.err.phoneInvalid": "درست فون نمبر لکھو۔",
  "auth.err.confirmRequired": "اپنا پاس ورڈ دوبارہ لکھو۔",
  "auth.err.termsRequired": "آگے بڑھنے دے لئی شرائط قبول کرو۔",
  "auth.err.passwordMismatch": "پاس ورڈ ایک جیسے نئیں اں۔",
  "auth.err.loginPasswordRequired": "اپنا پاس ورڈ لکھو۔",
  "auth.err.tooManyAttempts": "بہت زیادہ کوششیں — براہ کرم تھوڑی دیر بعد دوبارہ کوشش کرو۔",
  "auth.err.serverError": "ساڈی طرف توں خرابی پش آئی۔ براہ کرم دوبارہ کوشش کرو۔",
  "auth.err.invalidCredentials": "ای میل یا پاس ورڈ غلط اے۔",
  "li.meta.title": "سائن اِن — اگروپیو",
  "li.meta.description": "اگروپیو، اے آئی سے لیس فارم ذہانت دے پلیٹ فارم وچ سائن اِن کرو۔ تہاڑا مشیر، ریکارڈ تے رہنمائیاں — وہیں موجود جہاں تاہوں چھوڑی تھیں۔",
  "li.brand.headingA": "تہاڑے فارم دی ذہانت،",
  "li.brand.headingB": "وہیں منتظر جہاں تاہوں چھوڑی۔",
  "li.demo.aria": "اگروپیو مشیر توں گفتگو دی جھلک",
  "li.demo.user": "میری گندم دے پتے پیلے ہو رہے اں — کیا کروں؟",
  "li.demo.advisorLabel": "دو وجوہات:",
  "li.demo.advisorBody": "پانی دی کمی یا نائٹروجن دی کمی۔ پہلے صبح ٹھنڈے وقت وچ پانی دیو۔",
  "li.point1": "تہاڑی اپنی زبان وچ اے آئی مشیر",
  "li.point2": "سیٹیلائٹ توں فصل دی صحت دی نگرانی",
  "li.point3": "ہر موسم دا ڈیجیٹل ریکارڈ",
  "li.eyebrow": "سائن اِن",
  "li.heading": "تہاڑے فارم پر دوبارہ خوش آمدید",
  "li.sub": "سائن اِن کرو تاکہ اپنے فارم دے مشیر، ریکارڈ تے رہنمائیوں تک پہنچ سکیو۔",
  "li.passwordPlaceholder": "تہاڑا پاس ورڈ",
  "li.forgot": "پاس ورڈ بھول گئے؟",
  "li.submitting": "سائن اِن ہو رہا اے…",
  "li.noAccount": "ابھی اکاؤنٹ نئیں؟ ابتدائی رسائی خطہ در خطہ کھلی جا رہی اے —",
  "li.noAccountEnd": "۔",
  "li.createAccount": "اپنا اکاؤنٹ بناؤ",
  "su.meta.title": "اکاؤنٹ بناؤ — اگروپیو",
  "su.meta.description": "اپنا اگروپیو اکاؤنٹ بناؤ: ذاتی نوعیت کا اے آئی مشیر، موسم توں آگاہ رہنمائی، تے فارم ریکارڈ جو ہر موسم کو بہتر بنائی دیندے اں۔ پاکستان دے لئی بنایا گیا۔",
  "su.brand.headingA": "اپنا موسم شروع کرو",
  "su.brand.headingB": "ذہانت دے ساتھ۔",
  "su.profile.aria": "سائن اپ دے بعد بننے والے فارم پروفائل دی جھلک",
  "su.profile.badge": "فارم پروفائل · ایک منٹ وچ تیار",
  "su.profile.district": "ضلع",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشورے دی زبان",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "گندم · ربیع",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پہلے دن توں ذاتی نوعیت کا مشیر",
  "su.included2": "تہاڑے ضلع دے لئی موسم توں آگاہ رہنمائی",
  "su.included3": "فارم ریکارڈ جو ہر موسم کو بہتر بنائی دیندے اں",
  "su.eyebrow": "اکاؤنٹ بناؤ",
  "su.heading": "اپنا فارم اگروپیو لاؤ",
  "su.sub": "ایک اکاؤنٹ — تہاڑے مشیر، ریکارڈ تے اس موسم دی ہر رہنمائی دے لئی۔",
  "su.registered.title": "یہ ای میل پہلے سے رجسٹرڈ اے۔",
  "su.registered.body": "سائن اِن کرو، یا اگر پاس ورڈ بھول گئے ہو تا ری سیٹ کرو — تہاڑا فارم وہیں منتظر اے جہاں تاہوں چھوڑا تھا۔",
  "su.registered.reset": "پاس ورڈ ری سیٹ کرو",
  "su.name.label": "پورا نام",
  "su.name.placeholder": "مثلاً محمد احمد",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختیاری)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آف لائن ہونے پر ایس ایم ایس الرٹس دے لئی۔",
  "su.password.placeholder": "کم از کم ۸ حروف",
  "su.confirm.label": "پاس ورڈ دی تصدیق کرو",
  "su.confirm.placeholder": "اپنا پاس ورڈ دوبارہ لکھو",
  "su.strength0": "بہت مختصر",
  "su.strength1": "ٹھیک اے",
  "su.strength2": "اچھا",
  "su.strength3": "مضبوط",
  "su.terms.prefix": "میں",
  "su.terms.tos": "شرائط خدمت",
  "su.terms.and": "تے",
  "su.terms.privacy": "پرائیویسی پالیسی",
  "su.terms.end": "قبول کردا ہاں۔",
  "su.submit": "میرا اکاؤنٹ بناؤ",
  "su.submitting": "اکاؤنٹ بن رہا اے…",
  "su.haveAccount": "پہلے سے اکاؤنٹ اے؟",
  "app.shell.metadataTitle": "اگروپیو — مصنوعی ذہانت پر مبنی فارم انٹیلیجنس پلیٹ فارم",
  "app.shell.metadataDescription": "آج دی رہنمائی، موسم، الرٹس تے اگروپیو دا ہر آلہ — پاکستان دے لئی۔ اپلینوڈ دی پروڈکٹ۔",
  "app.shell.nav.dashboard": "ڈیش بورڈ",
  "app.shell.nav.farms": "کھیت",
  "app.shell.nav.profitLoss": "فائدہ / نقصان",
  "app.shell.nav.advisor": "مشیر",
  "app.shell.nav.detect": "تشخیص",
  "app.shell.nav.crops": "فصلیں",
  "app.shell.nav.prices": "قیمتیں",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "اطلاعات",
  "app.shell.nav.settings": "ترتیبات",
  "app.shell.nav.more": "مزید",
  "app.shell.signOut": "لاگ آؤٹ",
  "app.shell.aria.farmerTools": "کسان دے اوزار",
  "app.shell.aria.currentPage": "موجودہ صفحہ",
  "app.dashboard.greeting": "ہیلو، {name}",
  "app.dashboard.aria.profileMenu": "پروفائل مینو",
  "app.dashboard.welcomeEyebrow": "اگروپیو وچ خوش آمدید",
  "app.dashboard.welcomeTitle": "اپنا پہلا کھیت شروع کرو۔",
  "app.dashboard.welcomeBody": "تہاڑی فصل، تہاڑی زمین، تہاڑا موسم — جب تہاڑا کھیت ہوگا تا ہر رہنمائی اس دے مطابق ہوگی۔",
  "app.dashboard.addFirstFarm": "اپنا پہلا کھیت شامل کرو",
  "app.dashboard.badge.today": "آج",
  "app.dashboard.aria.advisoryTitle": "آج دی رہنمائی",
  "app.dashboard.carryToField": "اسے کھیت وچ لے جاؤ",
  "app.dashboard.askAdvisor": "مشیر توں پوچھو",
  "app.dashboard.aria.weatherTitle": "موسم · {location}",
  "app.dashboard.aria.degreesCelsius": "{n} ڈگری سیلسیس",
  "app.dashboard.fullForecast": "مکمل پیشگوئی",
  "app.dashboard.weatherUnavailable": "موسم اس وقت لوڈ نئیں ہو رہا۔ کچھ دیر بعد دوبارہ چیک کرو — تہاڑیاں رہنمائیاں جاری اں۔",
  "app.dashboard.seasonTipBadge": "موسمی تجاویز",
  "app.dashboard.alertsHeading": "الرٹس",
  "app.dashboard.newCount": "{n} نئی",
  "app.dashboard.viewAllAlerts": "تمام الرٹس دیکھو",
  "app.dashboard.noAlerts": "آج کوئی الرٹ نئیں — تہاڑیاں فصلیں سکون وچ اں۔",
  "app.dashboard.aria.alert": "الرٹ",
  "app.dashboard.severity.critical": "سنگین",
  "app.dashboard.severity.watch": "خبردار",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "زبان",
  "app.dashboard.weatherNoLocation": "موسمی ڈیٹا تہاڑے کھیت دے مقام دے سیٹ ہونے دے بعد یہاں ظاہر ہوگا۔",
  "app.dashboard.weatherYourArea": "تہاڑا علاقہ",
  "app.dashboard.quickActionsHeading": "فوری اعمال",
  "app.dashboard.cropDoctor": "فصل دا ڈاکٹر",
  "app.dashboard.detectTitle": "بیماری پھیلنے توں پہلے پہچانو",
  "app.dashboard.detectBody": "متاثرے پتے دی تصیر اپلوڈ کرو — فوری تشخیص تے اگلا قدم تہاڑے فون پر۔",
  "app.dashboard.recommendCrops": "فصل دی سفارش",
  "app.dashboard.recommendCropsBody": "اپنی مٹی، موسم، تے مقام دی بنیاد پر ذاتی نوعیت کے فصل دی سفارشات حاصل کرو۔",
  "app.dashboard.myFarms": "میرے کھیت",
  "app.dashboard.addFarm": "کھیت شامل کرو",
  "app.dashboard.viewAllFarms": "تمام کھیت دیکھو",
  "app.dashboard.health.good": "اچھا",
  "app.dashboard.health.watch": "خبردار",
  "app.dashboard.setupChecklist": "اپنا کھیت ترتیب دیو",
  "app.dashboard.checklistProgress": "{done} توں {total} مکمل",
  "app.dashboard.aria.dismissChecklist": "سیٹ اپ چیک لسٹ بند کرو",
  "app.dashboard.aria.setupProgress": "سیٹ اپ دی پیشرفت",
  "app.dashboard.demoFooter": "ڈیمو بلڈ · صرف نمونہ ڈیٹا",
  "app.dashboard.demo.todayLabel": "اتوار، 23 اگست",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "سبزی کا مرحلہ",
  "app.dashboard.demo.advisoryAction": "آج آبپاشی وچ تاخیر کرو",
  "app.dashboard.demo.advisoryWhy": "آج دوپہر کے بعد بارش کا امکان اے — تہاڑا کھیت قدرتی طور پر پانی پائے گا۔",
  "app.dashboard.demo.seasonAction": "بارش آنے توں پہلے اپنے کھیتوں وچ چلیو",
  "app.dashboard.demo.seasonWhy": "خشک دنوں کے بعد آہستہ چلنا دکھاتا اے کہ کون سے حصے خراب نکاسی کردا اں — بونے توں پہلے نوٹ کرو۔",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "دوپہر 2 بجے کے بعد بارش کا امکان · 80% امکان",
  "app.dashboard.demo.alertWhitefly": "ملتان ضلع وچ اس ہفتے کپاس پر سفید مکھی دا خطرہ زیادہ اے۔",
  "app.dashboard.demo.alertRain": "آج دوپہر 2 بجے کے بعد بارش متوقع اے — چھڑی چھڑکنے کا منصوبہ ملتوی کرو۔",
  "app.dashboard.demo.alertPrice": "ملتان مڑی پر گندم دیاں قیمتیں گزشتہ ہفتے دے مقابلے وچ 4% زیادہ اں۔",
  "app.dashboard.demo.farm1Name": "خلیل پور کھیت",
  "app.dashboard.demo.farm1Location": "خلیل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "سبزی کا مرحلہ",
  "app.dashboard.demo.farm2Name": "سہیوال پلاٹ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڈ، سہیوال",
  "app.dashboard.demo.farm2Crops": "کپاس",
  "app.dashboard.demo.farm2Stage": "پھول آنا",
  "app.dashboard.demo.farm3Name": "چک 62 جی بی",
  "app.dashboard.demo.farm3Location": "چک 62 جی بی، فیصل آباد",
  "app.dashboard.demo.farm3Crops": "گنا",
  "app.dashboard.demo.farm3Stage": "پَرچی کا مرحلہ",
  "app.dashboard.demo.checklistAdvisor": "ایک بار مشیر توں پوچھو",
  "app.dashboard.demo.checklistDetect": "اپنی پہلی تشخیص چلاؤ",
  "app.dashboard.demo.actionAdvisor": "مشیر توں پوچھو",
  "app.dashboard.demo.actionScan": "فصل اسکین کرو",
  "app.dashboard.demo.actionPrices": "قیمتیں چیک کرو",
  "app.dashboard.demo.actionRecord": "ریکارڈ شامل کرو",
  "app.dashboard.demo.actionRecommend": "فصل دی سفارش",
  "app.dashboard.pricesWidgetTitle": "منڈی دیاں قیمتیں",
  "app.dashboard.pricesWidgetView": "قیمتیں دیکھو",
  "app.dashboard.pricesWidgetPerMaund": "فی من",
  "app.dashboard.pricesWidgetNoTracked": "قیمتاں دیکھن لئی فصلیں ٹریک کرو",
  "app.farms.eyebrow": "کھیت",
  "app.farms.health.good": "اچھا",
  "app.farms.health.watch": "خبردار",
  "app.farms.units.acres": "ایکڑ",
  "app.farms.stages.sowing": "بوائی",
  "app.farms.stages.tillering": "شاخیں نکلنا",
  "app.farms.stages.vegetative": "نباتاتی",
  "app.farms.stages.grainFilling": "دانہ بھرنا",
  "app.farms.stages.ready": "تیار",
  "app.farms.stages.squaring": "فال بندی",
  "app.farms.stages.flowering": "پھول آنا",
  "app.farms.stages.bollFilling": "تہائی بھرنا",
  "app.farms.stages.grandGrowth": "عریض نشوونما",
  "app.farms.stages.ripening": "پکنا",
  "app.farms.stages.harvest": "کٹائی",
  "app.farms.stages.panicleInitiation": "پہنچائپن",
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سہیوال",
  "app.farms.districts.faisalabad": "فیصل آباد",
  "app.farms.districts.vehari": "وہاڑی",
  "app.farms.districts.bahawalpur": "بہاولپور",
  "app.farms.districts.lodhran": "لودھراں",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "کپاس",
  "app.farms.crops.sugarcane": "گنا",
  "app.farms.crops.maize": "مکئی",
  "app.farms.crops.rice": "چاول",
  "app.farms.list.pageTitle": "کھیت — اگروپیو",
  "app.farms.list.heading": "تہاڑے سارے کھیت، ایک فہرست",
  "app.farms.list.description": "ہر کھیت اپنی فصلوں، نشوونما دے مرحلے تے صحت دے ساتھ — ایک نظر وچ۔ کھیت دی مکمل کہانی دے لئی ٹیپ کرو۔",
  "app.farms.list.addLink": "شامل کرو",
  "app.farms.list.openFarm": "کھیت کھولو",
  "app.farms.list.addNewFarm": "نیا کھیت شامل کرو",
  "app.farms.list.emptyHeading": "ابھی تک کوئی کھیت نئیں",
  "app.farms.new.pageTitle": "کھیت شامل کرو — اگروپیو",
  "app.farms.new.heading": "کھیت شامل کرو",
  "app.farms.new.description": "اگروپیو کو اپنی زمین دے بارے وچ بتاؤ — مقام، فصل تے رقبہ — تاکہ ہر رہنمائی اس دے مطابق ہو۔",
  "app.farms.new.fields.name": "کھیت دا نام",
  "app.farms.new.placeholders.name": "مثلاً خلیل پور کھیت",
  "app.farms.new.fields.district": "ضلع / شہر",
  "app.farms.new.placeholders.district": "ضلع / شہر منتخب کرو",
  "app.farms.new.fields.crop": "بنیادی فصل",
  "app.farms.new.placeholders.crop": "فصل منتخب کرو",
  "app.farms.new.fields.acres": "رقبہ (ایکڑ)",
  "app.farms.new.placeholders.acres": "مثلاً ۱۲.۵",
  "app.farms.new.fields.location": "مقام / گاؤں",
  "app.farms.new.placeholders.location": "گاؤں یا شہر دا نام لکھو",
  "app.farms.new.fields.primaryCrop": "اہم فصل",
  "app.farms.new.fields.sowingDate": "بوائی دی تاریخ",
  "app.farms.new.fields.soilType": "مٹی دی قسم",
  "app.farms.new.fields.irrigationMethod": "آبپاشی کا طریقہ",
  "app.farms.new.placeholders.soilType": "مٹی، لوم، ریتیلی، یا گاد",
  "app.farms.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.farms.new.buttons.save": "کھیت محفوظ کرو",
  "app.farms.new.demoNotice": "ڈیمو — محفوظ کرنا ابھی ڈیٹابیس توں نئیں جڑا",
  "app.farms.new.success.heading": "کھیت ڈیمو وچ محفوظ ہو گیا",
  "app.farms.new.success.description": "مکمل بلڈ وچ یہ کھیت تہاڑے ڈیش بورڈ پر دکھایا جاہگا تے رہنمائیاں شکل لینا شروع کریں گی۔",
  "app.farms.new.success.goToFarms": "میرے کھیتوں پر جاؤ",
  "app.farms.new.success.backToDashboard": "واپس ڈیش بورڈ پر",
  "app.farms.new.errors.nameRequired": "کھیت کو نام دیو۔",
  "app.farms.new.errors.districtRequired": "ضلع منتخب کرو۔",
  "app.farms.new.errors.cropRequired": "بنیادی فصل منتخب کرو۔",
  "app.farms.new.errors.acresRequired": "رقبہ ایکڑ وچ درج کرو۔",
  "app.farms.detail.pageTitle": "کھیت دی تفصیلات — اگروپیو",
  "app.farms.detail.heroEyebrow": "کھیت دی تفصیلات",
  "app.farms.detail.goodHealth": "اچھی صحت",
  "app.farms.detail.needsWatching": "توجہ درکار",
  "app.farms.detail.sownLabel": "بوائی",
  "app.farms.detail.seasonHeading": "فصل کہاں اے",
  "app.farms.detail.activityHeading": "کھیت دی سرگرمی",
  "app.farms.detail.viewAllRecords": "تمام ریکارڈ دیکھو",
  "app.farms.detail.logFieldEvent": "کھیت دا واقعہ درج کرو",
  "app.farms.detail.scanCrop": "فصل اسکین کرو",
  "app.farms.detail.noRecords": "ابھی تک کوئی ریکارڈ نئیں — اپنے فارم دی یاداشت بنانے دے لئی میدان دے واقعات دی لاگنگ شروع کرو۔",
  "app.records.eyebrow": "کھیت دے ریکارڈ",
  "app.records.types.irrigation": "آبپاشی",
  "app.records.types.fertilizer": "کھاد",
  "app.records.types.pesticide": "کیڑے مار",
  "app.records.types.disease": "بیماری",
  "app.records.types.harvest": "کٹائی",
  "app.records.farmRecords.pageTitle": "کھیت دے ریکارڈ — اگروپیو",
  "app.records.farmRecords.heading": "کھیت دی یادداشت",
  "app.records.farmRecords.description": "ہر آبپاشی، اسپرے تے علاج لکھا ہوا — تاکہ اگلے ہفتے دے فیصلے یادداشت پر منحصر نہ ہوں۔",
  "app.records.farmRecords.demoNotice": "ڈیمو — صرف نمونہ اندراجات — نئے محفوظ کرنا ابھی نئیں جڑا",
  "app.records.new.pageTitle": "نیا ریکارڈ — اگروپیو",
  "app.records.new.heading": "کھیت وچ جو ہوا وہ درج کرو",
  "app.records.new.description": "آبپاشی، کھاد، کیڑے مار، بیماری تے کٹائی دے اندراجات — تہاڑے کھیت دی یادداشت، ایک ایک لائن۔",
  "app.records.new.fields.type": "کیا ہوا؟",
  "app.records.new.fields.farm": "کھیت",
  "app.records.new.placeholders.farm": "کھیت منتخب کرو",
  "app.records.new.fields.date": "تاریخ",
  "app.records.new.fields.title": "مختصر عنوان",
  "app.records.new.fields.optional": "(اختیاری)",
  "app.records.new.placeholders.titleIrrigation": "مثلاً نہری پانی — مکمل کھیت",
  "app.records.new.placeholders.titleOther": "دوسرا چھڑکاؤ پتواروں پر",
  "app.records.new.fields.details": "تفصیلات",
  "app.records.new.placeholders.details": "اگلے ہفتے دے لئی جو بھی یاد رکھنا ضروری ہو — مقدار، موسم، کھیت دی صورتحال۔",
  "app.records.new.buttons.saving": "محفوظ ہو رہا اے…",
  "app.records.new.buttons.save": "ریکارڈ محفوظ کرو",
  "app.records.new.demoNotice": "ڈیمو — محفوظ کرنا ابھی ڈیٹابیس توں نئیں جڑا",
  "app.records.new.success.heading": "ریکارڈ ڈیمو وچ محفوظ ہو گیا",
  "app.records.new.success.description": "مکمل بلڈ وچ یہ اندراج تہاڑے کھیت دے ریکارڈ وچ شامل ہوگا تے مستقبل دیاں رہنمائیاں تیز ہوں گی۔",
  "app.records.new.success.backToDashboard": "واپس ڈیش بورڈ پر",
  "app.records.new.success.viewFarms": "میرے کھیت دیکھو",
  "app.records.new.errors.farmRequired": "منتخب کرو یہ کس کھیت پر ہوا۔",
  "app.records.new.errors.dateRequired": "تاریخ منتخب کرو۔",
  "app.records.noRecordsFound": "اس فلٹر لئی کوئی ریکارڈ نئیں ملیا۔",
  "app.advisor.pageTitle": "مشیر",
  "app.advisor.sidebar.title": "گفتگو",
  "app.advisor.sidebar.newConversation": "نئی گفتگو",
  "app.advisor.sidebar.noConversations": "ابھی کوئی گفتگو نئیں۔ نئی شروع کرو!",
  "app.advisor.sidebar.rename": "نام تبدیل کرو",
  "app.advisor.sidebar.delete": "حذف کرو",
  "app.advisor.sidebar.deleteTitle": "گفتگو حذف کرو",
  "app.advisor.sidebar.deleteConfirm": "یہ گفتگو حذف کرو؟ یہ واپس نئیں ہو سکتی۔",
  "app.advisor.sidebar.cancel": "منسوخ کرو",
  "app.advisor.sidebar.closeSidebar": "سائڈبار بند کرو",
  "app.advisor.chat.placeholder": "فصل، موسم، قیمتواں دے بارے وچ پوچھو…",
  "app.advisor.chat.composerHint": "اپنا سوال لکھو…",
  "app.advisor.chat.send": "بھیجو",
  "app.advisor.chat.typing": "ٹائپ کر رہا اے…",
  "app.advisor.chat.thinking": "سوچ رہا ہاں…",
  "app.advisor.chat.farmerYou": "تہاں",
  "app.advisor.chat.onlineStatus": "آن لائن",
  "app.advisor.chat.emptyEyebrow": "مشیر چیٹ",
  "app.advisor.chat.emptyTitle": "اپنے کھیت دے بارے وچ کچھ بھی پوچھو",
  "app.advisor.chat.emptyBody": "فصلوں، موسم، مٹی، بازار قیمتواں تے مشورہ حاصل کرن لئی گفتگو شروع کرو۔",
  "app.advisor.chat.openingGreeting": "السلام علیکم! میں تہاڑا اگروپیو زرعی مشیر ہاں۔ فصل، موسم، منڈی دی قیمت، یا سرکاری سکیموں دے بارے وچ کچھ بھی پوچھو۔",
  "app.advisor.chat.photoRedirect": "تصویر توں بیماری دی پہچان ڈیٹیکٹ پیج پر اے — فصل اسکین کرو پر جاؤ۔",
  "app.advisor.chat.nonFarmingRedirect": "میں زراعت دے سوالات وچ مدد دے لئی ہاں۔ تہاڑی فصل یا کھیت دے بارے وچ کیا مدد کر سکدا ہاں؟",
  "app.advisor.chat.tryAsking": "یہ پوچھ کر دیکھو",
  "app.advisor.chat.suggested1": "میری گندم پر کون سی بیماری لگی اے؟",
  "app.advisor.chat.suggested2": "کیا آج ملتان وچ بارش ہوگی؟",
  "app.advisor.chat.suggested3": "آج منڈی دے نرخ کیا اں؟",
  "app.advisor.chat.suggested4": "کسان کارڈ سکیم دے بارے وچ بتاؤ",
  "app.advisor.errors.serviceUnavailable": "مشیر دی سروس عارضی طور پر دستیاب نئیں۔ کچھ دیر بعد دوبارہ کوشش کرو۔",
  "app.advisor.errors.rateLimited": "بہت زیادہ درخواستیں۔ ایک لمحہ رکو تے دوبارہ کوشش کرو۔",
  "app.advisor.errors.network": "نیٹ ورک دی خرابی۔ اپنا کنکشن چیک کرو تے دوبارہ کوشش کرو۔",
  "app.advisor.errors.generic": "کچھ غلط ہو گیا۔ دوبارہ کوشش کرو۔",
  "app.advisor.aria.openSidebar": "گفتگو کھولو",
  "app.advisor.aria.sendMessage": "پیغام بھیجو",
  "app.advisor.aria.chatMessages": "چیٹ پیغامات",
  "app.detect.eyebrow": "فصل ڈاکٹر",
  "app.detect.title": "بیماری پھیلنے توں پہلے پکڑو",
  "app.detect.uploadPrompt": "بیمار پتے دی تصویر لیو",
  "app.detect.takePhoto": "تصویر لیو یا منتخب کرو",
  "app.detect.sampleScan": "کوئی تصویر نئیں؟ ایک مثالی اسکین چلاؤ",
  "app.detect.readingLeaf": "پتے کو پڑھ رہا اے…",
  "app.detect.analyzing": "تجزیہ کر رہا اے…",
  "app.detect.scanAnother": "ایک اور پتے کا اسکین کرو",
  "app.detect.discussAdvisor": "مشیر سے بات کرو",
  "app.detect.saveToFarm": "فارم وچ محفوظ کرو",
  "app.detect.savedToFarm": "محفوظ ہو گیا {farm}",
  "app.detect.notSaved": "محفوظ نئیں ہوا",
  "app.detect.confidence": "اعتبار {pct}%",
  "app.detect.whatToDo": "اب کیا کرو",
  "app.detect.caution": "استعمال کرنے توں پہلے مقامی زراعی حکام توں تصدیق کرو۔",
  "app.detect.noFarmsTitle": "پہلے ایک فارم رجسٹر کرو",
  "app.detect.noFarmsBody": "اپنے اسکین کو ایک فارم سے جوڑو تاکہ مکمل بیماری دی تاریخچہ بن سکے۔",
  "app.detect.addFarm": "فارم شامل کرو",
  "app.detect.dismiss": "میں یہ بعد وچ کروں گا",
  "app.detect.pastScans": "پچھلے اسکین",
  "app.detect.loadMore": "مزید پڑھو",
  "app.detect.invalidFile": "براہ کرم ایک تصویر اپلوڈ کرو۔",
  "app.detect.serviceUnavailable": "سروس بےقابو ہو گئی۔ براہ کرم دوبارہ کوشش کرو۔",
  "app.detect.noDiagnosis": "بیماری دی شناخت نئیں ہو سکی — ایک واضح تصویر لے کر دوبارہ کوشش کرو۔",
  "app.detect.retry": "دوبارہ کوشش کرو",
  "app.detect.savedStatus": "محفوظ ہو گیا {farm}",
  "app.detect.unsavedStatus": "محفوظ نئیں ہوا",
  "app.detect.dragDropPrompt": "تصویر یہاں ڈریگ کرو یا براؤز کرو",
  "app.detect.dragDropPromptLine1": "تصویر یہاں ڈریگ کرو",
  "app.detect.dragDropPromptLine2": "یا براؤز کرو",
  "app.detect.historyEmpty": "کوئی اسکین نئیں۔ ایک تصویر لے کر شروع کرو۔",
  "app.detect.linkToFarm": "فارم سے جوڑو",
  "app.detect.severity.watch": "دیکھو",
  "app.detect.severity.treatNow": "ابھی علاج کرو",
  "app.detect.severity.clear": "صحت مند",
  "app.detect.sidebar.title": "سابقہ",
  "app.detect.sidebar.newScan": "نیا سکین",
  "app.detect.sidebar.closeSidebar": "سائڈبار بند کرو",
  "app.detect.sidebar.noHistory": "ابھی کوئی سکین یا گفتگو نئیں۔",
  "app.detect.sidebar.scansTitle": "سابق سکینز",
  "app.detect.sidebar.chatsTitle": "گفتگوں دا سابقہ",
  "app.detect.crop.apple": "سیب",
  "app.detect.crop.blueberry": "بلوبری",
  "app.detect.crop.cherry": "چیری",
  "app.detect.crop.corn": "مکئی",
  "app.detect.crop.grape": "انگور",
  "app.detect.crop.orange": "نینبی",
  "app.detect.crop.peach": "آڑو",
  "app.detect.crop.pepper": "مرچ",
  "app.detect.crop.potato": "آلو",
  "app.detect.crop.raspberry": "ریسپبری",
  "app.detect.crop.soybean": "سویابین",
  "app.detect.crop.squash": "کدو",
  "app.detect.crop.strawberry": "سٹراوبری",
  "app.detect.crop.tomato": "ٹماٹر",
  "app.detect.rescan.7": "7 دن بعد دوبارہ اسکین کرو",
  "app.detect.rescan.14": "14 دن بعد دوبارہ اسکین کرو",
  "app.detect.rescan.21": "21 دن بعد دوبارہ اسکین کرو",
  "app.detect.healthy.name": "صحت مند",
  "app.detect.healthy.causes": "اس پتے پر کوئی مرض نئیں ملا۔",
  "app.detect.healthy.steps.0": "کوئی علاج دی ضرورت نئیں۔ معمولی دیکھ بھال جاری رکھو۔",
  "app.detect.chat.cancel": "منسوخ کرو",
  "app.detect.chat.closePreview": "پورا نظارہ بند کرو",
  "app.detect.chat.deleteConfirm": "کیا تہاں واقعی اس چیٹ کو حذف کرنا چاہتے ہو؟",
  "app.detect.chat.deleteSession": "سیشن حذف کرو",
  "app.detect.chat.emptyState": "اس تشخیص دے بارے وچ اگلا سوال پوچھو۔",
  "app.detect.chat.imagePreview": "مکمل تصویر دیکھو",
  "app.detect.chat.newScan": "نیا اسکین",
  "app.detect.chat.noSessions": "ابھی تک کوئی تشخیص دی چیٹ نئیں۔",
  "app.detect.chat.placeholder": "اس تشخیص دے بارے وچ پوچھو...",
  "app.detect.chat.send": "بھیجو",
  "app.detect.chat.sessionsTitle": "تشخیص دی چیٹس",
  "app.detect.chat.thinking": "سوچ رہا اے...",
  "app.detect.disease.apple_black_rot.causes": "ایک فنگس (Botryosphaeria obtusa) پھولوں تے ٹہنیوں کو حملہ کردا اے، گیلا، نمی والے موسم وچ زیادہ ہوتا اے۔",
  "app.detect.disease.apple_black_rot.name": "سیب کا سیاہ گلج",
  "app.detect.disease.apple_black_rot.steps.0": "زخمی ٹہنیوں کو دیکھنے توں نیچے کاٹ کر جلا دیو۔",
  "app.detect.disease.apple_black_rot.steps.1": "پھولوں تے پٹیوں دے گرنے توں بعد محافظ ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.apple_black_rot.steps.2": "پھولوں دی ہوا کا راستہ کھلا رکھو تاکہ نمی کم رہے۔",
  "app.detect.disease.apple_cedar_rust.causes": "ایک زنگ نما فنگس (Gymnosporangium) جو سیب دے درختوں تے سرخ دیودار دے درختوں کے درمیان نمی دے موسم وچ پھیلدا اے۔",
  "app.detect.disease.apple_cedar_rust.name": "دیودار-سیب زنگ",
  "app.detect.disease.apple_cedar_rust.steps.0": "جہاں ممکن ہو زنگ مزاحم جڑوں یا قسمیں لگاؤ۔",
  "app.detect.disease.apple_cedar_rust.steps.1": "پتوں ٹوٹنے تے گرمیوں دے آغاز پر کانچ یا myclobutanil مبنی ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.apple_cedar_rust.steps.2": "500 میٹر دے اندر سرخ دیودار دے درختوں کو ہٹا دیو۔",
  "app.detect.disease.apple_scab.causes": "فنگل spores (Venturia inaequalis) ٹھنڈے، گیلا موسم وچ پھیلتے اں تے نئے پتوں تے پھولوں کو متاثر کردا اں۔",
  "app.detect.disease.apple_scab.name": "سیب کا زنگ",
  "app.detect.disease.apple_scab.steps.0": "خزاں وچ زخمی پتے جما کر تباہ کر دیو۔",
  "app.detect.disease.apple_scab.steps.1": "بہار وچ پتوں ٹوٹنے پر ہارٹی کلچرل تیل یا کانچ مبنی ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.apple_scab.steps.2": "اچھی ہوا دے لئی ٹہنیوں کو کاٹیو تے اوپر توں پانی نہ دیو۔",
  "app.detect.disease.cherry_powdery_mildew.causes": "ایک فنگل بیماری (Podosphaera leucotricha) جو گرم دنوں تے ٹھنڈی راتوں وچ پتوں پر سفید پاؤڈری داغ بنائی دیندی اے۔",
  "app.detect.disease.cherry_powdery_mildew.name": "چیری پاؤڈری مائیڈیو",
  "app.detect.disease.cherry_powdery_mildew.steps.0": "بھری ہوئی ٹہنیوں کو گھٹا کر ہوا دے چکر وچ بہتری لاؤ۔",
  "app.detect.disease.cherry_powdery_mildew.steps.1": "پہلے داغ دکھائی دینے پر سلفر یا مائیڈیو مخصوص ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.cherry_powdery_mildew.steps.2": "نائٹروجن زیادہ اڑوات جو نرم نشوونما کو بڑھائی دیندا اے۔",
  "app.detect.disease.corn_common_rust.causes": "ایک زنگ نما فنگس (Puccinia sorghi) جو پتوں پر نارنجی پھٹی پیدا کردا اے، نمی تے معتدل ٹمپریچر وچ زیادہ ہوتا اے۔",
  "app.detect.disease.corn_common_rust.name": "مکئی کا عام زنگ",
  "app.detect.disease.corn_common_rust.steps.0": "جہاں دستیاب ہو زنگ مزاحم ہائبرڈ لگاؤ۔",
  "app.detect.disease.corn_common_rust.steps.1": "اگر انفیکشن زیادہ ہو تا جلدی تسیل پر سسٹمک ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.corn_common_rust.steps.2": "انکولم بننے دے لئی مکئی توں بعد مکئی نہ لگاؤ۔",
  "app.detect.disease.corn_gray_leaf_spot.causes": "ایک فنگس (Cercospora zeae) جو چھوٹے سرمے دے داغوں دے ساتھ پیلے ہالو بنائی دیندا اے، گرم، نمی والے حالات وچ پھیلدا اے۔",
  "app.detect.disease.corn_gray_leaf_spot.name": "مکئی دے پتوں کا سرمہ داغ",
  "app.detect.disease.corn_gray_leaf_spot.steps.0": "مزاحم ہائبرڈ استعمال کرو تے مکئی دے باقیات توں دور کروٹ کرو۔",
  "app.detect.disease.corn_gray_leaf_spot.steps.1": "اگر دباؤ زیادہ ہو تا تسیلنگ پر تریازول یا سٹروبیلورن مبنی ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.corn_gray_leaf_spot.steps.2": "صبح کو پانی دیو تاکہ پتے جلدی خشک ہو جائیں۔",
  "app.detect.disease.corn_northern_leaf_blight.causes": "ایک فنگس (Exserohilum turcicum) جو لمبے سرمے-تنک داغ پیدا کردا اے، ٹھنڈے، گیلا موسم وچ اور زیادہ باقیات پر خراب ہوتا اے۔",
  "app.detect.disease.corn_northern_leaf_blight.name": "مکئی دے پتوں کا شمالی گلج",
  "app.detect.disease.corn_northern_leaf_blight.steps.0": "سویابین یا پھل دار crops دے ساتھ کروٹ کرو تے باقیات کو تیل دے کر ملا دیو۔",
  "app.detect.disease.corn_northern_leaf_blight.steps.1": "مزاحم ہائبرڈ استعمال کرو تے وی ٹی مرحلے پر ضرورت دے مطابق ذرائع کا سپرے لگاؤ۔",
  "app.detect.disease.corn_northern_leaf_blight.steps.2": "اچھی ہوا دے لئی پودوں دے فاصلے رکھو تے زیادہ بھر مت کرو۔",
  "app.detect.disease.grape_black_rot.causes": "ایک فنگس (Guignardia bidwellii) جو گیلا موسم وچ بیریوں تے پتوں پر سیاہ گول داغ بنائی دیندا اے۔",
  "app.detect.disease.grape_black_rot.name": "انگور کا سیاہ گلج",
  "app.detect.disease.grape_black_rot.steps.0": "زخمی ٹہنیوں کو کاٹ کر مومified بیریوں کو ہٹا دیو۔",
  "app.detect.disease.grape_black_rot.steps.1": "سوئے تے پھولوں پر مؤثر ذرائع (mancozeb یا tebuconazole) کا سپرے لگاؤ۔",
  "app.detect.disease.grape_black_rot.steps.2": "پھولوں دے دن اوپر توں پانی نہ دیو۔",
  "app.detect.disease.grape_esca.causes": "ایک Vascular فنگل complex (Phaeoacremonium) جو ٹہنیوں پر سیاہ لکیریں تے مرجھائے پتے پیدا کردا اے۔",
  "app.detect.disease.grape_esca.name": "انگور کا اسکا (کالی Measurement)",
  "app.detect.disease.grape_esca.steps.0": "خزاں وچ زخمی لکڑی کو کاٹ کر تباہ کر دیو۔",
  "app.detect.disease.grape_esca.steps.1": "پتوں ٹوٹنے پر چونا سلفر یا کانچ کا سپرے لگا کر انکولم کم کرو۔",
  "app.detect.disease.grape_esca.steps.2": "پانی کے دباؤ توں بچاؤ کرکے آبپاشی کو انتظام کرو۔",
  "app.detect.disease.grape_leaf_blight.causes": "ایک فنگس جو چھوٹے سیاہ داغوں کو پیلے ہالو دے ساتھ پیدا کردا اے، نمی دے حالات وچ زیادہ نظر آتا اے۔",
  "app.detect.disease.grape_leaf_blight.name": "انگور پتوں کا جلن (Isariopsis)",
  "app.detect.disease.grape_leaf_blight.steps.0": "پہلے علامت پر زخمی پتوں کو ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.grape_leaf_blight.steps.1": "شاخوں دی نشوونما دے دوران broad-spectrum ذرائع (mancozeb یا captan) کا سپرے لگاؤ۔",
  "app.detect.disease.grape_leaf_blight.steps.2": "انتخابی کٹائی توں پھولوں دی ہوا وچ بہتری لاؤ۔",
  "app.detect.disease.orange_huanglongbing.causes": "ایک بیکٹیریل بیماری جو psyllids توں پھیلدی اے، پیلے رنگت، ٹیڑھے پھل، تے درخت دے زوال کا سبب بنائی دیندی اے۔",
  "app.detect.disease.orange_huanglongbing.name": "چائٹرس گریننگ (Huanglongbing)",
  "app.detect.disease.orange_huanglongbing.steps.0": "ایشین چائٹرس psyllid کو ہمвременно قتل کرن والے سپرے سے کنٹرول کرو۔",
  "app.detect.disease.orange_huanglongbing.steps.1": "زخمی درختوں کو ہٹا کر تباہ کر دیو — قائم ہونے توں بعد کوئی علاج نئیں۔",
  "app.detect.disease.orange_huanglongbing.steps.2": "تصدیق شدہ بیماری توں پاک nursery stock استعمال کرو۔",
  "app.detect.disease.peach_bacterial_spot.causes": "ایک بیکٹیریل پاتھوjen (Xanthomonas) جو پتوں تے پھلوں پر سیاہ داغ بنائی دیندا اے، بارش دے چھینٹوں توں پھیلدا اے۔",
  "app.detect.disease.peach_bacterial_spot.name": "آڑو کا بیکٹیریل داغ",
  "app.detect.disease.peach_bacterial_spot.steps.0": "خشک موسم وچ کاٹیو تے درختوں کے درمیان utensils کو صاف کرو۔",
  "app.detect.disease.peach_bacterial_spot.steps.1": "پھولوں تے بھاری بارش توں بعد کانچ مبنی بیکٹیریسائڈ کا سپرے لگاؤ۔",
  "app.detect.disease.peach_bacterial_spot.steps.2": "اوپر توں آبپاشی نہ کرو تے مزاحم اقسام چنو۔",
  "app.detect.disease.pepper_bacterial_spot.causes": "ایک بیکٹیریل انفیکشن (Xanthomonas) جو گرم، گیلا موسم وچ گرم، چکنی داغوں کو پیدا کردا اے۔",
  "app.detect.disease.pepper_bacterial_spot.name": "مرچ کا بیکٹیریل داغ",
  "app.detect.disease.pepper_bacterial_spot.steps.0": "اچھی ہوا دے لئی پودوں کا فاصلہ رکھو تے پتوں کو گیلا نہ کرو۔",
  "app.detect.disease.pepper_bacterial_spot.steps.1": "پہلی علامت پر کانچ ہائیڈرائکس کا سپرے لگاؤ۔",
  "app.detect.disease.pepper_bacterial_spot.steps.2": "زخمی پتوں کو جلدی ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.potato_early_blight.causes": "ایک فنگس (Alternaria solani) جو نچلے پتوں پر بھورے گول داغ بنائی دیندا اے، گرم، نمی والے حالات وچ خراب ہوتا اے۔",
  "app.detect.disease.potato_early_blight.name": "آلو کا پہلا گلج",
  "app.detect.disease.potato_early_blight.steps.0": "تصدیق شدہ بیج لگاؤ تے آلو تے ٹماٹر توں دور کروٹ کرو۔",
  "app.detect.disease.potato_early_blight.steps.1": "پہلے داغ دکھائی دینے پر ذرائع (chlorothalonil یا mancozeb) کا سپرے لگاؤ۔",
  "app.detect.disease.potato_early_blight.steps.2": "مٹی کو تنوں پر ڈھیر لگاؤ تے نچلے پتوں کو خشک رکھنے دے لئی وسیع فاصلہ رکھو۔",
  "app.detect.disease.potato_late_blight.causes": "ایک پانی کی mold (Phytophthora infestans) جو سیاہ، پانی بھرے داغ بنائی دیندی اے — آئرش آلو قحط کا سبب، ٹھنڈے، گیلا موسم وچ تیزی توں پھیلدی اے۔",
  "app.detect.disease.potato_late_blight.name": "آلو کا آخری گلج",
  "app.detect.disease.potato_late_blight.steps.0": "زخمی ٹیوبر تے haulm کو فوری طور پر ہٹا کر تباہ کر دیو — کمپوسٹ نہ کرو۔",
  "app.detect.disease.potato_late_blight.steps.1": "پہلی علامت پر سسٹمک ذرائع (metalaxyl-based) کا سپرے لگاؤ، گیلا رہنے پر ہر 5-7 دن پر دوبارہ۔",
  "app.detect.disease.potato_late_blight.steps.2": "مزاحم اقسام لگاؤ تے بعد دوپہر کو آبپاشی نہ کرو۔",
  "app.detect.disease.squash_powdery_mildew.causes": "ایک فنگس (Podosphaera xanthii) جو گرم دنوں وچ پتوں پر سفید پاؤڈری داغ بنائی دیندا اے۔",
  "app.detect.disease.squash_powdery_mildew.name": "کدو پاؤڈری مائیڈیو",
  "app.detect.disease.squash_powdery_mildew.steps.0": "مزاحم اقسام لگاؤ تے اچھی ہوا دے لئی بیلوں کا فاصلہ رکھو۔",
  "app.detect.disease.squash_powdery_mildew.steps.1": "علامات دکھنے پر ہفتہ وار سلفر یا پوٹاشیم بیکربونیٹ سپرے لگاؤ۔",
  "app.detect.disease.squash_powdery_mildew.steps.2": "بنیادی پانی دیو تاکہ صبح وچ پتے خشک رہیں۔",
  "app.detect.disease.strawberry_leaf_scorch.causes": "ایک فنگس (Physophella salicis) جو سرخ-بیجنی داغ بنائی دیندا اے جو بعد وچ سنہری ہوتے اں، گیلا موسم وچ عام اے۔",
  "app.detect.disease.strawberry_leaf_scorch.name": "سٹرابیری پتوں کا جلن",
  "app.detect.disease.strawberry_leaf_scorch.steps.0": "اوپر توں آبپاشی نہ کرو تے بستر اچھی drainage رکھو۔",
  "app.detect.disease.strawberry_leaf_scorch.steps.1": "پہلی علامت پر ذرائع (captan یا tebuconazole) کا سپرے لگاؤ۔",
  "app.detect.disease.strawberry_leaf_scorch.steps.2": "بھاری زخمی پتوں کو ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.tomato_bacterial_spot.causes": "ایک بیکٹیریل انفیکشن (Xanthomonas) جو ٹماٹر پر سیاہ، چکنی داغ بنائی دیندی اے، گرم، گیلا موسم وچ پھیلدی اے۔",
  "app.detect.disease.tomato_bacterial_spot.name": "ٹماٹر کا بیکٹیریل داغ",
  "app.detect.disease.tomato_bacterial_spot.steps.0": "اچھی ہوا دے لئی پودوں کا فاصلہ رکھو تے پتوں کو گیلا نہ کرو۔",
  "app.detect.disease.tomato_bacterial_spot.steps.1": "پہلی علامت پر کانچ ہائیڈرائکس کا سپرے لگاؤ۔",
  "app.detect.disease.tomato_bacterial_spot.steps.2": "زخمی پتوں تے پھلوں کو ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.tomato_early_blight.causes": "ایک فنگس (Alternaria solani) جو نچلے پتوں پر سیاہ گول داغ بنائی دیندا اے، مٹی توں اوپر دی طرف شروع ہوتا اے۔",
  "app.detect.disease.tomato_early_blight.name": "ٹماٹر کا پہلا گلج",
  "app.detect.disease.tomato_early_blight.steps.0": "مچر تے بنیاد پر پانی دیو تاکہ مٹی دے چھینٹے نہ لگیں۔",
  "app.detect.disease.tomato_early_blight.steps.1": "جب نچلے پتے داغ دکھائی دیں تا ذرائع (chlorothalonil یا mancozeb) کا سپرے لگاؤ۔",
  "app.detect.disease.tomato_early_blight.steps.2": "زخمی سب سے نچلے پتوں کو ہٹا دیو تے ہوا دے لئی پودوں کو باندھیو۔",
  "app.detect.disease.tomato_late_blight.causes": "ایک پانی کی mold (Phytophthora infestans) جو پتوں تے پھلوں پر سیاہ، fuzzy داغ بنائی دیندی اے — گیلا، ٹھنڈا موسم وچ انتہائی تباہ کن۔",
  "app.detect.disease.tomato_late_blight.name": "ٹماٹر کا آخری گلج",
  "app.detect.disease.tomato_late_blight.steps.0": "زخمی پتوں تے پھلوں کو فوری طور پر ہٹا کر تباہ کر دیو؛ کمپوسٹ نہ کرو۔",
  "app.detect.disease.tomato_late_blight.steps.1": "پہلی علامت پر سسٹمک ذرائع (metalaxyl-based) کا سپرے لگاؤ تے بارش توں بعد دوبارہ۔",
  "app.detect.disease.tomato_late_blight.steps.2": "جلن مزاحم اقسام لگاؤ تے اوپر توں پانی نہ دیو۔",
  "app.detect.disease.tomato_leaf_mold.causes": "ایک فنگس (Cladosporium fulvum) جو اوپری پتوں پر پیلے پٹ تے نمی والی حالات وچ fuzzy سنہری نیچے والے حصے بنائی دیندا اے۔",
  "app.detect.disease.tomato_leaf_mold.name": "ٹماٹر پتے کی mold",
  "app.detect.disease.tomato_leaf_mold.steps.0": "گرین ہاؤس وچ ہوا دیو تے ہوا دے لئی پودوں کا فاصلہ رکھو۔",
  "app.detect.disease.tomato_leaf_mold.steps.1": "پیلاہٹ دکھنے پر ذرائع (chlorothalonil) کا سپرے لگاؤ۔",
  "app.detect.disease.tomato_leaf_mold.steps.2": "بنیاد پر پانی دیو تے پتوں کو خشک رکھو۔",
  "app.detect.disease.tomato_mosaic_virus.causes": "ایک وائرس جو مٹیلڈ، بے ساختہ پتوں تے کم پھل کا سبب بنائی دیندا اے، utensils تے ہاتھوں توں پھیلدا اے۔",
  "app.detect.disease.tomato_mosaic_virus.name": "ٹماٹر موزیک وائرس",
  "app.detect.disease.tomato_mosaic_virus.steps.0": "پودوں کے درمیان utensils کو بلیچ یا الکحل سے صاف کرو۔",
  "app.detect.disease.tomato_mosaic_virus.steps.1": "زخمی پودوں کو ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.tomato_mosaic_virus.steps.2": "aphid vectors تے جھاڑیوں پر کنٹرول کرو۔",
  "app.detect.disease.tomato_septoria.causes": "ایک فنگس (Septoria lycopersici) جو پرانے پتوں پر چھوٹے سنہری داغوں کو سیاہ کناروں دے ساتھ پیدا کردا اے۔",
  "app.detect.disease.tomato_septoria.name": "ٹماٹر سپٹوریا پتے کا داغ",
  "app.detect.disease.tomato_septoria.steps.0": "کروٹ کرو تے مٹی دے چھینٹے روکنے دے لئی مچر لگاؤ۔",
  "app.detect.disease.tomato_septoria.steps.1": "پہلی علامت پر ذرائع (mancozeb یا chlorothalonil) کا سپرے لگاؤ۔",
  "app.detect.disease.tomato_septoria.steps.2": "زخمی نچلے پتوں کو ہٹا کر تباہ کر دیو۔",
  "app.detect.disease.tomato_spider_mites.causes": "چھوٹے مکڑی جیسے mites (Tetranychus urticae) جو پتوں کا رس چوسدا اں، stippled، برونز پتوں تے fine جالی بنائی دیندے اں۔",
  "app.detect.disease.tomato_spider_mites.name": "ٹماٹر سپائیڈر مائٹس",
  "app.detect.disease.tomato_spider_mites.steps.0": "صبح کو مضبوط پانی کے اسپرے توں mites کو دور کرو۔",
  "app.detect.disease.tomato_spider_mites.steps.1": "فائدہ مند حشرات (ladybugs، lacewings) رہا کرو یا neem oil لگاؤ۔",
  "app.detect.disease.tomato_spider_mites.steps.2": "قدرتی خارچین کو مارنے والے broad-spectrum کیڑے مار دوں توں بچو۔",
  "app.detect.disease.tomato_target_spot.causes": "ایک فنگس (Corynespora cassiicola) جو پتوں پر سیاہ گول 'target' داغ بنائی دیندا اے، گرم، نمی والے موسم وچ زیادہ ہوتا اے۔",
  "app.detect.disease.tomato_target_spot.name": "ٹماٹر ٹارگٹ سپاٹ",
  "app.detect.disease.tomato_target_spot.steps.0": "کٹائی توں ہوا وچ بہتری لاؤ تے پودوں کو باندھیو۔",
  "app.detect.disease.tomato_target_spot.steps.1": "داغ پہلے دکھائی دینے پر ذرائع (azoxystrobin یا chlorothalonil) کا سپرے لگاؤ۔",
  "app.detect.disease.tomato_target_spot.steps.2": "صبح کو بنیاد پر پانی دیو۔",
  "app.detect.disease.tomato_ylcv.causes": "ایک وائرس جو سفید مکھیوں توں پھیلدا اے، پتوں دی پیلاہٹ تے لچک تے بڑھنے وچ رکاوٹ پیدا کردا اے۔",
  "app.detect.disease.tomato_ylcv.name": "ٹماٹر پیلا پتہ لچک وائرس",
  "app.detect.disease.tomato_ylcv.steps.0": "reflective مچر تے transplan پر insecticides توں سفید مکھیوں پر کنٹرول کرو۔",
  "app.detect.disease.tomato_ylcv.steps.1": "زخمی پودوں کو ہٹا کر تباہ کر دیو — کوئی علاج نئیں۔",
  "app.detect.disease.tomato_ylcv.steps.2": "مزاحم اقسام لگاؤ تے سفید مکھیوں کو پالنے والی جھاڑیوں پر کنٹرول کرو۔",
  "app.weather.pageTitle": "موسمی مشورہ",
  "app.weather.eyebrow": "موسم",
  "app.weather.description": "اپنی فصل دی نشوونما دے مرحلے تے پیشن گوئی کے ذریعے روزانہ کھیتی دے مشورے۔",
  "app.weather.todayAdvisory": "آج دا مشورہ",
  "app.weather.growthStage": "نشوونما دا مرحلہ",
  "app.weather.severity.info": "معلومات",
  "app.weather.severity.warning": "انتباہ",
  "app.weather.severity.critical": "اہم",
  "app.weather.forecastTitle": "7 دن دی پیشن گوئی",
  "app.weather.forecastSubtitle": "اپنی فصل دے لئی ہر دن دا موسم تے کھیتی دی سفارش۔",
  "app.weather.weatherUnavailable": "موسمی ڈیٹا دستیاب نئیں",
  "app.weather.weatherUnavailableBody": "تہاڑا آخری محفوظ مشورہ دکھایا جا رہا اے۔ جب پیشن گوئی واپس آئے گی تا نیا مشورہ ظاہر ہوگا۔",
  "app.weather.farmSelectorLabel": "فارم",
  "app.weather.registerTitle": "اپنا فارم رجسٹر کرو",
  "app.weather.registerBody": "ذاتی روزانہ مشورے پانے دے لئی اپنی فصل، بوائی دی تاریخ تے مقام شامل کرو۔",
  "app.weather.registerCta": "فارم رجسٹر کرو",
  "app.weather.registerForm.crop": "اہلی فصل",
  "app.weather.registerForm.sowing": "بوائی دی تاریخ",
  "app.weather.registerForm.soil": "مٹی کا نوع",
  "app.weather.registerForm.irrigation": "آبپاشی کا طریقہ",
  "app.weather.registerForm.soilTypes": "مٹی، لوم، شناری، یا ریت",
  "app.weather.registerForm.irrigationMethods": "ڈرپ، سپرنکلر، فیض، یا بارانی",
  "app.weather.registerForm.save": "محفوظ کرو تے میرا مشورہ دیکھو",
  "app.weather.registerForm.saving": "محفوظ ہو رہا اے…",
  "app.weather.registerForm.success": "محفوظ ہو گیا — یہ تہاڑا مشورہ اے",
  "app.weather.registerForm.error": "تہاڑے فارم دی تفصیلات محفوظ نئیں کی جا سکیاں۔ براہ کرم دوبارہ کوشش کرو۔",
  "app.weather.historyTitle": "مشورے دی تاریخ",
  "app.weather.historySubtitle": "تہاڑے فارموں دے لئی ماضی دیاں سفارشات، نئی سب سے پہلے۔",
  "app.weather.history.empty": "ابھی تک کوئی ماضی کا مشورہ نئیں۔",
  "app.weather.history.date": "تاریخ",
  "app.weather.history.severity": "شدت",
  "app.weather.history.status": "حیثیت",
  "app.weather.history.status.new": "نئی",
  "app.weather.history.status.seen": "دیکھا گیا",
  "app.weather.history.status.acted": "عمل کر لیا",
  "app.weather.history.loadMore": "مزید لوڈ کرو",
  "app.weather.history.viewAll": "پوری تاریخ دیکھو",
  "app.weather.detail.back": "تاریخ وچ واپس",
  "app.weather.detail.weatherConditions": "موسم دی حالات",
  "app.weather.detail.recommendation": "سفارش",
  "app.weather.detail.markActed": "نشان زد: عمل کر لیا",
  "app.weather.detail.markAcknowledged": "نشان زد: دیکھا گیا",
  "app.weather.detail.markedActed": "نشان زد: عمل کر لیا",
  "app.weather.detail.markedSeen": "نشان زد: دیکھا گیا",
  "app.weather.alerts.title": "فعال الرٹس",
  "app.weather.alerts.heavyRain": "بھاری بارش متوقع — آبپاشی وچ تاخیر کرو تے کٹی ہوئی فصلوں دی حفاظت کرو۔",
  "app.weather.alerts.frost": "پالنی دا خطرہ — آج رات حساس فصلوں دی حفاظت کرو۔",
  "app.weather.alerts.extremeHeat": "شدید گرمی — آبپاشی بڑھاؤ تے دوپہر دے میدان وچ کم توں بچو۔",
  "app.weather.alerts.diseaseRisk": "نم مرضی دے موقع پر — صبح دے خشک وقت وچ پیشگی فنگسِسڈ لگاؤ۔",
  "app.weather.alerts.dismiss": "ختم کرو",
  "app.weather.alerts.noAlerts": "ابھی کوئی فعال الرٹ نئیں۔",
  "app.weather.alerts.viewAll": "سب اطلاعات دیکھو",
  "app.weather.stages.seedling": "پودا",
  "app.weather.stages.vegetative": "نباتاتی",
  "app.weather.stages.flowering": "پھولنا",
  "app.weather.stages.maturation": "پختگی",
  "app.weather.stages.harvestReady": "کٹائی تیار",
  "app.weather.stages.generic": "عام",
  "app.weather.source.live": "براہ راست پیشن گوئی · OpenWeather",
  "app.weather.source.cached": "آخری محفوظ پیشن گوئی",
  "app.weather.source.demo": "نمونہ پیشن گوئی — لائیو ڈیٹا دے لئی API کلید شامل کرو",
  "app.weather.advisory.recommendation.irrigation": "آج آبپاشی نہ کرو — بارش متوقع اے۔ پانی بچاؤ تے پانی سے بھر دینے توں بچو۔",
  "app.weather.advisory.recommendation.irrigateNow": "ٹھنڈے گھنٹوں وچ (صبح 9 بجے توں پہلے) آبپاشی کرو — گرمی بڑھ رہی اے تے مٹی خشک ہو رہی اے۔",
  "app.weather.advisory.recommendation.fertilize": "مستحکٹ موسم توں پہلے کھاد لگانے دا اچھا وقت اے۔",
  "app.weather.advisory.recommendation.sprayDisease": "نم مرضی دے موقع پر — صبح دے خشک وقت وچ پیشگی فنگسِسڈ لگاؤ۔",
  "app.weather.advisory.recommendation.heatProtect": "شدید گرمی — آبپاشی بڑھاؤ تے دوپہر دے میدان وچ کم توں بچو۔",
  "app.weather.advisory.recommendation.frostProtect": "آج رات پالنی دا خطرہ — نوجوں پودوں کو ڈھانپ لیو یا مٹی کو گرم کرنے دے لئی پانی دیو۔",
  "app.weather.advisory.recommendation.harvest": "فصل کٹائی دے قریب — کٹائی دے لئی خشک دن کا انتظام کرو تے پکی ہوئی فصلوں کو بارش توں بچاؤ۔",
  "app.weather.advisory.recommendation.plantCare": "مستحکٹ نشوونما دا مرحلہ — باقاعدہ آبپاشی تے جڑن جاری رکھو۔",
  "app.weather.advisory.recommendation.generic": "آج کوئی خاص اقدام نئیں — کھیت تے پیشن گوئی پر نظر رکھو۔",
  "app.weather.buttons.register": "فارم رجسٹر کرو",
  "app.weather.buttons.refresh": "تازہ کرو",
  "app.weather.errors.generic": "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کرو۔",
  "app.weather.errors.noFarm": "اپنا مشورہ دیکھنے دے لئی ایک فارم منتخب کرو۔",
  "app.weather.metric.temperature": "درجہ حرارت",
  "app.weather.metric.precipitation": "بارش",
  "app.weather.metric.wind": "ہوا",
  "app.weather.metric.humidity": "نمی",
  "app.prices.eyebrow": "منڈی دیاں قیمتیں",
  "app.prices.title": "بیچنے توں پہلے قیمت جانو",
  "app.prices.description": "آج دیاں قیمتیں قریبی منڈیوں توں، ہولڈ یا سیل دی سادہ رائے دے ساتھ۔",
  "app.prices.selectCrop": "فصل منتخب کرو",
  "app.prices.searchPlaceholder": "پاکستان بھر وچ فصل یا منڈی تلاش کرو",
  "app.prices.globalSearchPlaceholder": "فصل یا منڈی تلاش کرو…",
  "app.prices.globalSearchCrops": "فصلوں",
  "app.prices.globalSearchMandis": "منڈیاں",
  "app.prices.globalSearchNoResults": "کوئی نتیجہ نئیں ملا",
  "app.prices.globalSearchViewPrices": "قیمتیں دیکھو",
  "app.prices.noData": "قیمت دا کوئی ڈیٹا دستیاب نئیں",
  "app.prices.updatedToday": "آج تازہ ترین",
  "app.prices.updatedDaysAgo": "{days} دن پہلے تازہ کیا گیا",
  "app.prices.marketHoliday": "منڈی بند / مارکیٹ تعطیل",
  "app.prices.perMaund": "/ من",
  "app.prices.bestPrice": "بہترین قیمت",
  "app.prices.distanceKm": "{km} کلومیٹر دور",
  "app.prices.hold": "ہولڈ",
  "app.prices.sell": "فروخت",
  "app.prices.recommendationHold": "بہتر قیمت دے لئی ہولڈ کرو",
  "app.prices.recommendationSell": "جلد فروخت کرو",
  "app.prices.volatilityWarning": "اعلی اتار چڑھاو / کم ڈیٹا",
  "app.prices.predictionTitle": "14 دن دی قیمت پیشن گوئی",
  "app.prices.historyTitle": "قیمتواں دی تاریخ",
  "app.prices.range1M": "1 مہینہ",
  "app.prices.range3M": "3 مہینے",
  "app.prices.range6M": "6 مہینے",
  "app.prices.range12M": "1 سال",
  "app.prices.setAlert": "قیمت الرٹ سیٹ کرو",
  "app.prices.editAlert": "الرٹ وچ ترمیم کرو",
  "app.prices.saveAlert": "الرٹ محفوظ کرو",
  "app.prices.cancel": "منسوخ کرو",
  "app.prices.alertCrop": "فصل",
  "app.prices.alertMandi": "منڈی",
  "app.prices.alertMandiOptional": "منڈی (اختیاری)",
  "app.prices.alertStatus": "حالت",
  "app.prices.targetPrice": "ہدف قیمت (روپے / من)",
  "app.prices.alertActive": "فعال",
  "app.prices.alertPaused": "موقوف",
  "app.prices.deleteAlert": "الرٹ حذف کرو",
  "app.prices.fallbackBanner": "اپنے ضلع دیاں قیمتیں خود بخود دیکھنے دے لئی اپنا فارم مقام سیٹ کرو۔",
  "app.prices.comparisonTitle": "منڈیوں کا موازنہ کرو",
  "app.prices.market": "منڈی",
  "app.prices.modalPrice": "ماڈل قیمت",
  "app.prices.minPrice": "کم از کم قیمت",
  "app.prices.maxPrice": "زیادہ سے زیادہ قیمت",
  "app.prices.change": "تبدیلی",
  "app.prices.distance": "فاصلہ",
  "app.prices.adminTitle": "دستی قیمت درج کرو",
  "app.prices.adminDate": "تاریخ",
  "app.prices.adminModalPrice": "ماڈل قیمت",
  "app.prices.adminMinPrice": "کم از کم قیمت",
  "app.prices.adminMaxPrice": "زیادہ سے زیادہ قیمت",
  "app.prices.adminHoliday": "مارکیٹ تعطیل",
  "app.prices.adminSave": "قیمت محفوظ کرو",
  "app.prices.loading": "قیمتیں لوڈ ہو رہیاں ہیں...",
  "app.prices.retry": "دوبارہ کوشش کرو",
  "app.prices.noPricesForCrop": "اس فصل دے قریب کوئی قیمت نئیں ملی۔",
  "app.prices.comingSoon": "جلد آ رہا اے",
  "offline.banner": "تو آف لائن اے۔ تیرا ڈیٹا محفوظ ہو گیا اے تے جب تو واپس آن لائن آؤ گا تو خود بخود ہمگام ہو جائے گا۔",
  "offline.title": "تو آف لائن اے",
  "offline.body": "یہ صفحہ تیرے ڈیوائس توں موصول ہوئے ہے تاکہ تو مزید کام جاری رکھ سکے۔ جب تیرا کنکشن واپس آ جائے تا، جو کوئی ریکارڈ محفوظ کرواے، او خود بخود ہمگام ہو جائے گا۔",
  "offline.reload": "دوبارہ کوشش کرو",
  "offline.home": "ہوم تو جا",
  "offline.installTitle": "ہوم اسکرین نو شامل کرو",
  "offline.installBody": "تیز رفتار تے اپنے فارمز تے ریکارڈز دے لئی مکمل آف لائن رسائی دے لئی ایگروپیو انسٹال کرو۔",
  "offline.installAction": "ہوم اسکرین نو شامل کرو",
  "offline.dismiss": "رد کرو",
  "offline.iosPrompt": "مکمل آف لائن رسائی دے لئی اپنے ہوم اسکرین نو ایگروپیو شامل کرو۔ شیئر بٹن نو ٹیپ کرو، فر ہوم اسکرین نو شامل کرو۔",

  "app.crops.eyebrow": "فصل دی سفارش",
  "app.crops.title": "اس سیزن کیا بونا چاہیے؟",
  "app.crops.description": "اپنے کھیت دے بارے وچ بتاؤ، اساں مٹی، موسم تے بجٹ دے حساب توں بہترین فصلیں بنائیں گے۔",
  "app.crops.nav": "فصلیں",
  "app.crops.form.farmLabel": "کھیت",
  "app.crops.form.seasonLabel": "سیزن",
  "app.crops.form.yearLabel": "سال",
  "app.crops.form.soilLabel": "مٹی دی قسم",
  "app.crops.form.irrigationLabel": "آبپاشی",
  "app.crops.form.budgetLabel": "بجٹ",
  "app.crops.form.soilOther": "پتہ نئیں / دیگر",
  "app.crops.form.submit": "سفارشیں لاؤ",
  "app.crops.form.submitting": "سفارشیں تیار ہو رہیاں ہیں…",
  "app.crops.form.lowestViableWarning": "تہاڑے بجٹ وچ کوئی فصل نئیں آتی۔ کم از کم موزوں درجہ: {bracket}",
  "app.crops.form.switchBracket": "{bracket} منتخب کرو",
  "app.crops.form.noFarm": "سفارش دے لئی پہلے کھیت شامل کرو۔",
  "app.crops.form.geoError": "سفارشیں صرف پاکستان دے کھیتوں دے لئی اں۔",
  "app.crops.form.regionalSoilNote": "تہاڑے ضلع دی علاقائی مٹی دے مطابق (اپنی زمین دا ٹیسٹ نئیں)۔",
  "app.crops.form.nationalSoilNote": "قومی تخمینہ، علاقے دے مطابق نئیں۔",
  "app.crops.seasons.summer": "گرما",
  "app.crops.seasons.winter": "سردی",
  "app.crops.seasons.autumn": "خزاں",
  "app.crops.seasons.spring": "بہار",
  "app.crops.seasons.rainy": "برسات",
  "app.crops.seasons.windy": "ہوائی",
  "app.crops.soil.sandy": "ریتلی",
  "app.crops.soil.sandy_loam": "ریتلی دوآبی",
  "app.crops.soil.loamy": "دومٹ",
  "app.crops.soil.clay_loam": "چِکنی دوآبی",
  "app.crops.soil.clay": "چِکنی",
  "app.crops.soil.silty": "گاد والی",
  "app.crops.soil.saline": "نمکین",
  "app.crops.soil.rocky": "پتھریلی",
  "app.crops.soil.other": "پتہ نئیں / دیگر",
  "app.crops.budget.low": "کم (فی ایکڑ 25,000 روپے تک)",
  "app.crops.budget.medium": "درمیانہ (25,000–60,000 روپے)",
  "app.crops.budget.high": "زیادہ (60,000–120,000 روپے)",
  "app.crops.budget.very_high": "بہت زیادہ (120,000 روپے توں اوپر)",
  "app.crops.irrigation.rainfed": "بارش پر",
  "app.crops.irrigation.canal": "نہر",
  "app.crops.irrigation.tubewell": "ٹیوب ویل",
  "app.crops.irrigation.mixed": "مخلوط",
  "app.crops.results.title": "تہاڑی ٹاپ 3 فصلیں",
  "app.crops.results.rank": "درجہ {n}",
  "app.crops.results.revenue": "فی ایکڑ تخمینہ آمدنی",
  "app.crops.results.reason": "یہ فصل کیوں",
  "app.crops.results.risks": "اہم خطرات",
  "app.crops.results.saveToPlan": "فارم پلان وچ محفوظ کرو",
  "app.crops.results.saved": "پلان وچ محفوظ",
  "app.crops.results.compare": "فصلیں موازنہ کرو",
  "app.crops.results.projectionNote": "آمدنی صرف تخمینہ اے، ضمانت نئیں — ماخذ: {sources}۔",
  "app.crops.results.sourceWeather": "موسم",
  "app.crops.results.sourceMarket": "بازار",
  "app.crops.results.sourceSoil": "مٹی",
  "app.crops.results.weatherMissing": "موسم دا ڈیٹا دستیاب نئیں تھا۔",
  "app.crops.results.marketMissing": "منڈی بھاؤ دستیاب نئیں، آمدنی غیر یقینی۔",
  "app.crops.results.soilMissing": "مٹی دا ڈیٹا محدود تھا۔",
  "app.crops.results.regenerate": "دوبارہ بناؤ",
  "app.crops.results.regenerateConfirm": "یہ تہاڑی موجودہ سفارشات کو بدل دے گا۔ جاری رکھیں؟",
  "app.crops.results.alreadyExists": "اس کھیت، سیزن تے سال دے لئی پہلے سے سفارش موجود اے۔",
  "app.crops.results.viewExisting": "موجودہ دیکھو",
  "app.crops.results.noCandidates": "تہاڑے سیزن تے بجٹ وچ کوئی فصل نئیں۔ بجٹ بڑھاؤ۔",
  "app.crops.results.replacedPlan": "اس سیزن دا پرانا پلان بدل دیا گیا۔",
  "app.crops.detail.title": "سفارش دی تفصیل",
  "app.crops.detail.back": "واپس سفارشوں پر",
  "app.crops.detail.confidence": "اعتماد",
  "app.crops.detail.scoreBreakdown": "اسکور تفصیل",
  "app.crops.detail.suitability": "مناسب",
  "app.crops.detail.weatherFit": "موسمی مطابقت",
  "app.crops.detail.profitability": "منافع بخش",
  "app.crops.detail.risk": "خطرہ (کم بہتر اے)",
  "app.crops.detail.sustainability": "پائیداری",
  "app.crops.detail.final": "حتمی اسکور",
  "app.crops.detail.dataFreshness": "ڈیٹا عمر: {seconds} سیکنڈ",
  "app.crops.detail.soilImpact": "مٹی پر اثر",
  "app.crops.water.low": "کم",
  "app.crops.water.medium": "درمیانہ",
  "app.crops.water.high": "زیادہ",
  "app.crops.confidence.high": "زیادہ",
  "app.crops.confidence.medium": "درمیانہ",
  "app.crops.confidence.low": "کم",
  "app.crops.confidence.unreliable": "غیر یقینی",
  "app.crops.risk.price_volatility": "بھاؤ وچ اتار چڑھاو",
  "app.crops.risk.pest_pressure": "کیڑوں کا دباؤ",
  "app.crops.risk.weather": "موسمی خطرہ",
  "app.crops.risk.water_stress": "پانی دی کمی",
  "app.crops.risk.input_cost": "لاگت",
  "app.crops.soilImpact.improves": "مٹی بہتر کرے",
  "app.crops.soilImpact.neutral": "غیر جانبدار",
  "app.crops.soilImpact.depletes": "مٹی کمزور کرے",
  "app.crops.compare.title": "اپنی ٹاپ فصلیں موازنہ کرو",
  "app.crops.compare.close": "موازنہ بند کرو",
  "app.crops.compare.revenue": "فی ایکڑ آمدنی",
  "app.crops.compare.duration": "اگنے کے دن",
  "app.crops.compare.water": "پانی دی ضرورت",
  "app.crops.compare.marketRisk": "منڈی دا خطرہ",
  "app.crops.compare.soilImpact": "مٹی پر اثر",
  "app.crops.compare.labour": "مزدوری",
  "app.crops.compare.chartAria": "تین تجویز کردہ فصلوں کے درمیان آمدنی کا موازنہ بار چارٹ",
  "app.crops.compare.chartUnavailable": "چارٹ دستیاب نئیں — تَخَیُل دی بجایاں فہرست دکھائی جا رہی اے۔",
  "app.crops.compare.selectToSave": "محفوظ کرنے دے لئی منتخب کرو",
  "app.crops.compare.saveSelected": "منتخب محفوظ کرو",
  "app.crops.rotation.title": "فصلوں کی ترتیب",
  "app.crops.rotation.subtitle": "مٹی بچانے دے لئی اگلی فصلیں۔",
  "app.crops.rotation.generic": "عام مشورہ — تہاڑی فیلڈ دی تاریخ دے مطابق نئیں۔",
  "app.crops.rotation.nextSeason": "اگلا: {season} {year}",
  "app.crops.rotation.savedTitle": "محفوظ پلان تے ترتیب",
  "app.crops.catalogue.empty": "کوئی فصل نئیں ملی۔",
  "app.crops.errors.serviceUnavailable": "سروس عارضی دستیاب نئیں۔ دوبارہ کوشش کرو۔",
  "app.crops.errors.generic": "کچھ غلط ہوا۔ دوبارہ کوشش کرو۔",
  "app.crops.errors.notFound": "سفارش نئیں ملی۔",
  "app.crops.errors.rateLimited": "بہت زیادہ درخواستیں۔ تھوڑا انتظار کرو۔",
  "app.crops.reason.suitability": "{crop} تہاڑی {soil} مٹی دے لئی بہترین اے۔",
  "app.crops.reason.weather_fit": "{crop} تہاڑے علاقے دے {season} موسم سے ملتی اے۔",
  "app.crops.reason.profit": "{crop} تہاڑے بجٹ وچ سب سے زیادہ منافع دیندی اے۔",
  "app.crops.reason.rotation_fit": "{crop} تہاڑی پچھلی بوائی توں بعد مٹی بحال کردا اے۔",
  "app.crops.reason.low_risk": "{crop} اس سیزن وچ کم خطرہ اے۔",
  "app.crops.reason.generic": "{crop} اس سیزن دے لئی اچھا انتخاب اے۔",
  "app.crops.rotation.wheat_then_mung": "گیہوں توں بعد مونگ نائٹروجن بحال کردا اے۔",
  "app.crops.rotation.wheat_then_chickpea": "گیہوں توں بعد چنے مٹی بہتر کردا اں۔",
  "app.crops.rotation.wheat_then_cotton": "پنجاب وچ گیہوں توں بعد کپاس عام اے۔",
  "app.crops.rotation.cotton_then_wheat": "کپاس توں بعد گیہوں زمین بحال کردا اے۔",
  "app.crops.rotation.cotton_then_maize": "اچھی زمین پر کپاس توں بعد مکئی۔",
  "app.crops.rotation.rice_then_wheat": "دھان توں بعد گیہوں کلاسیکی ترتیب اے۔",
  "app.crops.rotation.rice_then_maize": "دھان توں بعد مکئی بچی ہوئی نمی استعمال کردا اے۔",
  "app.crops.rotation.maize_then_potato": "دوآبی زمین پر مکئی توں بعد آلو۔",
  "app.crops.rotation.maize_then_wheat": "مکئی توں بعد گیہوں فائدہ مند اے۔",
  "app.crops.rotation.potato_then_maize": "آلو توں بعد مکئی۔",
  "app.crops.rotation.sugarcane_then_maize": "گنے توں بعد مکئی۔",
  "app.crops.rotation.mung_then_wheat": "پلس توں بعد گیہوں زرخیزی بحال کردا اے۔",
  "app.crops.rotation.chickpea_then_cotton": "پلس توں بعد کپاس نائٹروجن فائدہ دیندا اے۔",
  "app.crops.rotation.mustard_then_cotton": "سرسوں توں بعد کپاس۔",
  "app.crops.rotation.soybean_then_wheat": "سویابین توں بعد گیہوں۔",
  "app.crops.rotation.onion_then_maize": "پیاز توں بعد زرخیز زمین پر مکئی۔",
  "app.crops.rotation.tomato_then_wheat": "ٹماٹر توں بعد گیہوں۔",
  "app.crops.catalogue.barley": "جَو",
  "app.crops.catalogue.bajra": "بajra",
  "app.crops.catalogue.jowar": "جَوار",
  "app.crops.catalogue.tobacco": "تمباکو",
  "app.crops.catalogue.sunflower": "سورج مکھی",
  "app.crops.catalogue.canola": "سرسوں",
  "app.crops.catalogue.sesame": "تل",
  "app.crops.catalogue.lentil": "مسور",
  "app.crops.catalogue.pigeon_pea": "دوسرا",
  "app.crops.catalogue.black_gram": "کالی دال",
  "app.crops.catalogue.pea": "مٹر",
  "app.crops.catalogue.cowpea": "لوبیا",
  "app.crops.catalogue.cauliflower": "پھول گوبھی",
  "app.crops.catalogue.cabbage": "بند گوبھی",
  "app.crops.catalogue.brinjal": "بینگن",
  "app.crops.catalogue.okra": "بامی",
  "app.crops.catalogue.chili": "مرچ",
  "app.crops.catalogue.garlic": "لہسن",
  "app.crops.catalogue.ginger": "ادرک",
  "app.crops.catalogue.cucumber": "کھیرا",
  "app.crops.catalogue.watermelon": "تربوز",
  "app.crops.catalogue.pumpkin": "کدو",
  "app.crops.catalogue.carrot": "گاجر",
  "app.crops.catalogue.spinach": "پالک",
  "app.crops.catalogue.fenugreek": "شنبلیله",
  "app.crops.catalogue.mango": "آم",
  "app.crops.catalogue.citrus": "مالٹا",
  "app.crops.catalogue.guava": "امرود",
  "app.crops.catalogue.apple": "سیب",
  "app.crops.rotation.barley_then_chickpea": "جو توں بعد چنا - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.bajra_then_cowpea": "بجرا توں بعد لوبیا - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.sunflower_then_wheat": "سورج مکھی توں بعد گندم - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.canola_then_wheat": "سرسوں توں بعد گندم - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.lentil_then_cotton": "مسور توں بعد کپاس - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.pea_then_maize": "مٹر توں بعد مکئی - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.cauliflower_then_pea": "پھول گوبھی توں بعد مٹر - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.okra_then_cowpea": "بامی توں بعد لوبیا - فصلوں دا چکر منافع بخش",
  "app.crops.rotation.garlic_then_wheat": "لہسن توں بعد گندم - فصلوں دا چکر منافع بخش",
  "app.shell.nav.satellite": "سیٹلائٹ",
  "app.satellite.nav": "سیٹلائٹ",
  "app.satellite.pageTitle": "Field monitoring — Agropioo",
  "app.satellite.eyebrow": "سیٹلائٹ مانیٹرنگ",
  "app.satellite.title": "اپنے کھیت فضاسے ویکھو",
  "app.satellite.description": "نقشے تے کھیت دی حدونہ بناؤ۔ اساں گزشتہ دو ہفتیاں وچچ کوئی صاف سیٹلائٹ تصویر چیک کریں گے تے NDVI صحت ہیٹ میپ دکھائیں گے۔",
  "app.satellite.farmSelectorLabel": "کھیت",
  "app.satellite.selectFarmPrompt": "کھیت دی صحت ویکھو۔",
  "app.satellite.noFarms": "ابھی تائیں کوئی کھیت رجسٹرڈ نہیں۔",
  "app.satellite.drawBoundaryBtn": "کھیت دی حدونہ بناؤ",
  "app.satellite.saveBoundaryBtn": "حدونہ محفوظ کرو",
  "app.satellite.cancelDrawBtn": "بنانا منسوخ کرو",
  "app.satellite.clearBoundaryBtn": "حدونہ صاف کرو",
  "app.satellite.drawInstructions": "اپنے کھیت دے گرد چھکویرا بناؤ۔ شکل مکمل کرو۔",
  "app.satellite.drawing": "Drawing boundary…",
  "app.satellite.savingBoundary": "Saving boundary…",
  "app.satellite.processingTitle": "Processing satellite imagery…",
  "app.satellite.processingBody": "اساں تھاڑے کھیت دیں تازہ سیٹلائٹ ڈیٹا دی جانچ کر رہے۔",
  "app.satellite.processingSub": "گزشتہ دو ہفتیاں وچچ کوئی صاف سیٹلائٹ تصویر چیک کر رہے۔",
  "app.satellite.noBoundaryTitle": "کھیت دی حدونہ نہیں",
  "app.satellite.noBoundaryBody": "کھیت دی سیٹلائٹ تصویریں ویکھن لئی حدونہ بناؤ۔",
  "app.satellite.noSnapshots": "ابھی تائیں کوئی صحت تصویر نہیں۔",
  "app.satellite.noSnapshotsBody": "جیہوں ہی تھاڑی پہلی سیٹلائٹ جانچ مکمل ہوئے گی، ایہاں اتھے دکھائی دیسی۔",
  "app.satellite.cloudCover": "بادل دی چھان",
  "app.satellite.cloudCoverYes": "بادلین",
  "app.satellite.cloudCoverNo": "صاف",
  "app.satellite.weekEnding": "{date} دی ہفتہ",
  "app.satellite.weekStartShort": "{date} توں ہفتہ",
  "app.satellite.meanNdvi": "اوسط NDVI",
  "app.satellite.health": "صحت",
  "app.satellite.dateCol": "تاریخ",
  "app.satellite.legendTitle": "NDVI پیمانہ",
  "app.satellite.legend.waterShadow": "پانی / پھینہ",
  "app.satellite.legend.stressed": "دبیا ہوئیا",
  "app.satellite.legend.moderate": "درمیانی",
  "app.satellite.legend.healthy": "صحت مند",
  "app.satellite.legendNodata": "ڈیٹا نہیں",
  "app.satellite.jobPending": "انتظار وچ",
  "app.satellite.jobProcessing": "جھٹیا ویچھا جا رہا",
  "app.satellite.jobCompleted": "تیار",
  "app.satellite.jobFailed": "ناکام",
  "app.satellite.jobFailedBody": "تازہ سیٹلائٹ جانچ مکمل نہ ہوئی۔ حدونہ ویکھو یا دوبارہ کوشش کرو۔",
  "app.satellite.retry": "دوبارہ کوشش کرو",
  "app.satellite.refreshStatus": "ھکی تازہ کرو",
  "app.satellite.refreshing": "Refreshing…",
  "app.satellite.historyHeading": "۱۲ ہفتیاں دی تاریخ",
  "app.satellite.historyEmpty": "ابھی تائیں کوئی عکس نہیں۔",
  "app.satellite.healthGood": "واہیا",
  "app.satellite.healthWatch": "ویکھو",
  "app.satellite.healthStressed": "دبیا ہوئیا",
  "app.satellite.loading": "Loading…",
  "app.satellite.noImagery": "گزشتہ دو ہفتیاں وچچ ایں کھیت لئی کوئی صاف سیٹلائٹ تصویر نہیں ملی۔",
  "app.satellite.error.generic": "کجھ غلط ہویا۔ دوبارہ کوشش کرو۔",
  "app.satellite.error.serviceUnavailable": "سیٹلائٹ تصویر عارضی طور تے دستیاب نہیں۔",
  "app.satellite.error.noFarm": "سیٹلائٹ مانیٹرنگ ویکھن لئی کھیت چنو۔",
  "app.satellite.mapLegend": "رنگ پیمانہ",
  "app.satellite.zoomToFarm": "اپنا کھیت زوم کرو",
  "app.satellite.boundarySaved": "Boundary saved. Checking for satellite imagery…",
  "app.satellite.boundaryError": "حدونہ محفوظ نہ ہوئی۔ شکل ویکھو یا دوبارہ کوشش کرو۔",
  "app.satellite.areaTooLarge": "The drawn area is too large — please draw around a single field.",
  "app.satellite.areaOutsidePk": "کوآرڈینیٹس پاکستان د پیړو دننه لري۔ خپلے کھیت دی ټھیک ټھیک جگہ ویکھو۔",
  "app.satellite.invalidBoundary": "Invalid field boundary — please redraw.",
};
