import type { CatalogKey } from "./en.ts";

/** سرائیکی — AI-drafted, founder-reviewed copy (plan D4). */
export const skr: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "ایہ کیویں کم کردا اے",
  "nav.vision": "ساڈا وژن",
  "nav.signIn": "سائن اِن کرو",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کرو",
  "nav.openMenu": "مینیو کھولو",
  "nav.closeMenu": "مینیو بند کرو",
  "common.languageSwitcherLabel": "بولی بدلو",
  "notFound.title": "ورقہ موجود کائنا",
  "notFound.body": "تساں جیہدا ورقہ لبھدا پئے او موجود کائنا یا بدل گیا ہے۔",
  "notFound.backHome": "اگروپیو دے گھر واپس ونجو",
  "common.builtForPakistan": "پاکستان لئی بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ دی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت تے مبنی فارم ذہانت دا پلیٹ فارم",
  "home.hero.titleLead": "ہوشیار وہائی لئی",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "اک پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی دیاں قیمتیں تے تہاڈے فارم دے ریکارڈ اک تھاں کٹھے کردا اے — ڈیٹا کوں صاف فیصلیاں وچ بدلدا اے، تہاڈی اپنی بولی وچ۔",
  "home.hero.ctaSecondary": "ݙیکھو ایہ کیویں کم کردا اے",
  "home.hero.imageAlt": "وہائی کران وچ ٹیبلٹ تے اگروپیو ورتیندے ہوئے",
  "home.hero.readingCrop": "فصل دی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی دی نمی",
  "home.hero.noteExcellent": "چنگا",
  "home.hero.noteClearSky": "صاف اسمان",
  "home.hero.noteOptimal": "ٹھیک",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم دیاں صلاحیتاں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتاں دی جانکاری",
  "home.ticker.weatherAdvisories": "موسم موجب صلاحاں",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 بولیاں وچ صلاح",
  "home.ticker.pestAlerts": "سُکڑیاں دے خطرے دی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسلہ",
  "home.problem.title": "وہائی دے فیصلے اندازے دا کھیل نہیں ہونے چاہیدے",
  "home.problem.subtitle": "سارے پاکستان وچ وہائی ریایت، مقامی صلاحاں تے کھنڈریاں معلومات نال وڈے رسک والے فیصلے کرندے نیں۔ نقصان کتائی تے چکندا اے۔",
  "home.problem.item1Title": "غیر یقینی ویلھا",
  "home.problem.item1Body": "پانی، کھاد، دوائی، بوائی، کتائی — اہم لمحے اجے وی اندازے نال طے تھیندے نیں، جس نال پیداوار گھٹدی تے خرچ ضائع تھیندی اے۔",
  "home.problem.item2Title": "گواچیا فارم ریکارڈ",
  "home.problem.item2Body": "سیزاں دا علم یاداشت یا کھنڈریاں کاپیاں وچ رہندا اے۔ پچھلے سال جیہڑا کم آیا، اوں توں ایں سال سکھنا اوکھا اے۔",
  "home.problem.item3Title": "کھنڈریاں صلاحاں",
  "home.problem.item3Body": "گوآں ڈے، دکان دار تے ویڈیوز سب جواب ڈیندے نیں — پر تھوڑے جیہے وہائی دی فصل، مٹی، موسم یا علاقے نال ملدے نیں۔",
  "home.problem.kicker": "اندازے دی قیمت کتائی تے چکندی اے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "تہاڈے فارم دی ذہانت،",
  "home.solution.titleB": "اک تھاں تے",
  "home.solution.subtitle": "سارے سیزن لئی اک ذہانت دا پلیٹ فارم — صلاح، ریکارڈ، موسم تے منڈی تہاڈی زمین دے ڈیٹا نال کم کرندے نیں، عام صلاحاں نال نہیں۔",
  "home.solution.card1Title": "کی کرنا اے",
  "home.solution.card1Body": "پانی، کھاد، سُکڑیاں مار تے کتائی دے ویلے لئی ذاتی صلاحاں — تہاڈی فصل تے حالات موجب۔",
  "home.solution.card1Answer": "ایں کھیت، ایں ہفتے لئی صاف صلاح۔",
  "home.solution.card2Title": "کڈوں کرنا اے",
  "home.solution.card2Body": "موسمی رہنمائی ڈسدی اے کم کڈوں کرنا اے، تاں جو غلط ویلھا تے اچانک حالات تہاڈی فصل نہ کھاون۔",
  "home.solution.card2Answer": "سچے موسم تے فصل دی نشوونما موجب ویلھا۔",
  "home.solution.card3Title": "کی کیتا گیا اے",
  "home.solution.card3Body": "ہر کم — پانی، ان پٹ، بیماری، خرچ، کتائی — ترتیب والے ریکارڈ وچ محفوظ جیہڑا ہر سیزن کوں ودھ سمجھدار بناندا اے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ موجود۔",
};
