import type { CatalogKey } from "./en.ts";

/** اردو — AI-drafted, founder-reviewed copy (plan D4). */
export const ur: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "یہ کیسے کام کرتا ہے",
  "nav.vision": "ہمارا وژن",
  "nav.signIn": "سائن اِن کریں",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کریں",
  "nav.openMenu": "مینیو کھولیں",
  "nav.closeMenu": "مینیو بند کریں",
  "common.languageSwitcherLabel": "زبان تبدیل کریں",
  "notFound.title": "صفہ موجود نہیں",
  "notFound.body": "جو صفہ آپ تلاش کر رہے ہیں وہ موجود نہیں یا منتقل ہو چکا ہو گا۔",
  "notFound.backHome": "اگروپیو کے ہوم پر واپس جائیں",
  "common.builtForPakistan": "پاکستان کے لیے بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ کی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت پر مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "اسمارٹ کاشتکاری کے لیے",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "ایک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی کی قیمتیں اور آپ کے فارم کے ریکارڈ ایک جگہ جمع کرتا ہے — ڈیٹا کو واضح فیصلوں میں بدلتا ہے، آپ کی اپنی زبان میں۔",
  "home.hero.ctaSecondary": "دیکھیں یہ کیسے کام کرتا ہے",
  "home.hero.imageAlt": "کاشتکار کھیت میں ٹیبلٹ پر اگروپیو استعمال کرتے ہوئے",
  "home.hero.readingCrop": "فصل کی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی کی نمی",
  "home.hero.noteExcellent": "بہترین",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم کی صلاحیتیں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتوں کی جانکاری",
  "home.ticker.weatherAdvisories": "موسم کے مطابق مشورے",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 زبانوں میں مشورہ",
  "home.ticker.pestAlerts": "کیڑے مکوڑے کے خطرے کی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسئلہ",
  "home.problem.title": "کاشتکاری کے فیصلے اندازے کا کھیل نہیں ہونے چائییں",
  "home.problem.subtitle": "پورے پاکستان میں کاشتکار روایت، مقامی مشورے اور بکھری ہوئی معلومات کے ساتھ بڑے رسک والے فیصلے کرتے ہیں۔ نقصان کٹائی کے وقت چکنا پڑتا ہے۔",
  "home.problem.item1Title": "غیر یقینی وقت",
  "home.problem.item1Body": "سینچائی، کھاد، دوا، بوائی، کٹائی — اہم لمحے اب بھی اندازے سے طے ہوتے ہیں، جس سے پیداوار کم اور خرچ ضائع ہوتی ہے۔",
  "home.problem.item2Title": "کھویا ہوا فارم ریکارڈ",
  "home.problem.item2Body": "سیزنوں کا علم یادداشت یا بکھری نوٹ بکوں میں رہتا ہے۔ پچھلے سال جو کام آیا، اس سے اس سال سیکھنا ناممکن ہے۔",
  "home.problem.item3Title": "بکھرا ہوا مشورہ",
  "home.problem.item3Body": "پڑوسی، دکاندار اور ویڈیوز سب جواب دیتے ہیں — لیکن چند ہی کاشتکار کی فصل، مٹی، موسم یا علاقے سے ملتے ہیں۔",
  "home.problem.kicker": "اندازے کی قیمت کٹائی پر چکتی ہے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "آپ کے فارم کی ذہانت،",
  "home.solution.titleB": "ایک جگہ",
  "home.solution.subtitle": "پورے سیزن کے لیے ایک انٹیلیجنس پلیٹ فارم — مشورہ، ریکارڈ، موسم اور بازار آپ کی زمین کے ڈیٹا سے کام کرتے ہیں، عمومی مشوروں سے نہیں۔",
  "home.solution.card1Title": "کیا کرنا ہے",
  "home.solution.card1Body": "سینچائی، کھاد، کیڑے مار اور کٹائی کے وقت کے لیے ذاتی مشورے — آپ کی فصل اور حالات کے مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے کے لیے واضح مشورہ۔",
  "home.solution.card2Title": "کب کرنا ہے",
  "home.solution.card2Body": "موسمی رہنمائی بتاتی ہے کہ کام کب کریں، تاکہ غلط وقت اور اچانک حالات آپ کی پیداوار نہ کھائیں۔",
  "home.solution.card2Answer": "حقیقی موسم اور فصل کی نشوونما کے مطابق وقت۔",
  "home.solution.card3Title": "کیا کیا جا چکا ہے",
  "home.solution.card3Body": "ہر سرگرمی — سینچائی، ان پٹ، بیماری، اخراجات، کٹائی — منظم ریکارڈ میں محفوظ جو ہر سیزن کو زیادہ سمجھدار بناتا ہے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ دستیاب۔",
  "home.features.eyebrow": "پلیٹ فارم کے اندر",
  "home.features.titleA": "متعدد انجن،",
  "home.features.titleB": "ایک ذہین پلیٹ فارم",
  "home.features.subtitle": "آپ کے اپنے الفاظ میں پہلے سوال سے لے کر پورے سیزن کے ریکارڈ تک — ہر صلاحیت اگلی کو تقویت دیتی ہے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی زرعی مشیر",
  "home.features.advisorTopics": "سینچائی · کھاد · کیڑے اور بیماری · کٹائی",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "پیلی پتوں والی گندم پر اگروپیو مشیر سے نمونہ گفتگو",
  "home.features.advisorUserMsg": "میری گندم کے پتے پیلے ہو رہے ہیں — کیا کروں؟",
  "home.features.advisorReplyTitle": "پیلے پتے — دو عام وجوہات:",
  "home.features.advisorReplyCause1": "پانی کی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے اوقات میں، صبح 9 بجے سے پہلے پانی دیں۔",
  "home.features.advisorReplyCause2": "نائٹروجن کی کمي",
  "home.features.advisorReplyCause2Rest": "— سب سے پرانے پتے پہلے چیک کریں؛ ضرورت ہو تو یوریا ڈالیں۔",
  "home.features.advisorReplyFooter": "اگر پتوں کے نیچے پیلی دھاریاں نظر آئیں، تصویر بھیجیں — میں بیماری کی تشخیص کر دوں گا۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھیں یا بولیں…",
  "home.features.advisorFooter": "اپنی فصل کے بارے میں کچھ بھی پوچھیں — روزمرہ سوالات خوش آمدید ہیں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر سرگرمی منظم اور درج — تاکہ مشورہ آپ کی اپنی زمین سے سیکھے۔",
  "home.features.record1Activity": "سینچائی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتوں کا اسکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "گندم · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · زبان",
  "home.features.languageTitle": "آپ کی زبان، آپ کے الفاظ",
  "home.features.languageDesc": "جو سوچتے ہیں وہی بول کر یا لکھ کر کہیں — تکنیکی انگریزی کی ضرورت نہیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم سے آگاہ رہنمائی",
  "home.features.weatherDesc": "مشورہ آپ تک پہنچنے سے پہلے حقیقی حالات چیک کرتا ہے — بارش سے پہلے سپرے کر بیٹھے تو سارا زرخیز مال بہہ جائے گا۔",
  "home.features.weatherMockAria": "پانچ دن کی پیشن گوئی جس میں جمعرات کو اسپرے نہ کرنے کا مشورہ نمایاں ہے",
  "home.features.dayMon": "پیر",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "اسپرے روکیں",
  "home.features.weatherLegend": "مقامی موسم کی پیشن گوئی سے مشورہ والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم مسلسل بڑھ رہا ہے — مکمل صلاحیتوں کا مجموعہ دیکھیں",
  "home.journey.eyebrow": "یہ کیسے کام کرتا ہے",
  "home.journey.title": "ایک سوال سیزن کا آغاز کرتا ہے",
  "home.journey.subtitle": "آپ کے پہلے سوال سے مکمل، ذہین فارم تاریخ تک ایک سادہ راستہ۔",
  "home.journey.step1Title": "اپنا فارم شامل کریں",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بنانے کے لیے مقام، فصل اور بنیادی تفصیلات درج کریں۔",
  "home.journey.step2Title": "اے آئی سے پوچھیں",
  "home.journey.step2Body": "اپنا سوال اسی زبان میں لکھیں یا بولیں جس سے آپ سب سے زیادہ آرام دہ ہوں۔",
  "home.journey.step3Title": "رہنمائی حاصل کریں",
  "home.journey.step3Body": "اپنی فصل، موسم، مقام اور فارم تاریخ پر مبنی مشورہ حاصل کریں۔",
  "home.journey.step4Title": "سرگرمی درج کریں",
  "home.journey.step4Body": "چند ٹیپوں میں سینچائی، کھاد، دوا یا بیماری درج کریں۔",
  "home.journey.step5Title": "تاریخ بنائیں",
  "home.journey.step5Body": "ہر ریکارڈ مستقبل کے مشوروں کو زیادہ سمجھدار اور موزوں بناتا ہے۔",
  "home.journey.step6Title": "نگهانی جاری رکھیں",
  "home.journey.step6Body": "پورے سیزن میں ریکارڈ دیکھیں اور پیش رفت پر نظر رکھیں۔",
  "home.matrix.eyebrow": "مکمل صلاحیتوں کا مجموعہ",
  "home.matrix.title": "ضروری سے حیران کن تک",
  "home.matrix.subtitle": "ہر خصوصیت فصل بچاتی ہے، خرچ کم کرتی ہے یا آمدنی بڑھاتی ہے。 اسے پنچانگ کی طرح پڑھیں — ہر درجہ پچھلے پر تعمیر ہوتا ہے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتیں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی سطح",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری کی شناخت",
  "home.matrix.t1f1Body": "متاثرہ پتے کی تصویر اپ لوڈ کریں اور فوری تشخیص، شدت اور علاج کی سفارشات حاصل کریں۔",
  "home.matrix.t1f2Title": "سیٹلائٹ فیلڈ مانیٹرنگ",
  "home.matrix.t1f2Body": "اپنے کھیت کی حد متعین کریں اور مفت سینٹینل-2 تصویروں سے این ڈی وی آئی پر مبنی فصل کی صحت دیکھیں۔",
  "home.matrix.t1f3Title": "سمارٹ موسمی مشورہ",
  "home.matrix.t1f3Body": "مقامی موسم کی پیشن گوئی آپ کی فصل اور نشوونما کے مرحلے سے مل کر روزانہ قابلِ عمل مشورہ بنتی ہے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر اور پیشن گوئی",
  "home.matrix.t1f4Body": "قریبی منڈی کی قیمتیں اے آئی رجحانات کے ساتھ دیکھیں، تاکہ صحیح وقت پر بیچیں۔",
  "home.matrix.tier2Name": "امتیازی خصوصیات",
  "home.matrix.tier2Badge": "نمایاں",
  "home.matrix.t2f1Title": "علاقائی زبانوں میں وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولیں یا لکھیں — جواب اسی زبان میں سنیں جو آپ بہتر سمجھتے ہیں۔",
  "home.matrix.t2f2Title": "سرکاری اسکیم میچر",
  "home.matrix.t2f2Body": "اپنی معلومات درج کریں اور ہر اہل اسکیم دریافت کریں — دستاویزات اور درخواست کے لنکس سمیت۔",
  "home.matrix.t2f3Title": "فصل کی سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن میں آپ کی مٹی، موسم، منڈی کی مانگ اور بجٹ کے مطابق سب سے منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع اور حقیقی اخراجات، پیداوار، آمدنی اور نفع — بریک ایون اور آر او آئی کے ساتھ۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم اور ماہر رابطہ",
  "home.matrix.t2f5Body": "سوالات پوسٹ کریں، تصاویر شیئر کریں، ہم منصف کاشتکاروں اور تصدیق شدہ ماہرین سے جواب لیں۔",
  "home.matrix.tier3Name": "حیرت انگیز",
  "home.matrix.tier3Badge": "سب سے آگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی کا مشاہدہ",
  "home.matrix.t3f1Body": "سلائیڈر کے ساتھ وقت کے ساتھ سیٹلائٹ تصاویر موازنہ کریں — نشوونما، نقصان یا قبضہ ٹریک کریں۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیشن گوئی",
  "home.matrix.t3f2Body": "موسم، فصل کے مرحلے اور تاریخ کی بنیاد پر ممکنہ کیڑے حملے سے پہلے ابتدائی انتباہ۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر پر کال کریں، سوال بولیں، اپنی زبان میں مشورہ سنیں — اسمارٹ فون ضروری نہیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ تخمینہ",
  "home.matrix.t3f4Body": "پائیدار طریقے درج کریں اور رضاکارانہ مارکیٹوں سے کاربن کریڈٹ کا تخمینہ لیں۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت میں آف لائن کام کرے، کنکشن پر سنک ہو، کمزور نیٹ پر ایس ایم ایس اطلاع دے۔",
  "home.vision.eyebrow": "تصور",
  "home.vision.titleA": "پاکستان کے لیے بنایا گیا۔",
  "home.vision.titleB": "دنیا کے لیے تیار۔",
  "home.vision.pkTitle": "پاکستان کو ترجیح دینے والا طریقہ",
  "home.vision.pkBody": "پہلا ورژن پاکستان کے کھیتوں کے لیے ڈیزائن کیا گیا ہے: مقامی فصلیں، علاقائی زبانیں، حقیقی کاشتکاری کے طریقے اور حقیقی میدانی حالات۔",
  "home.vision.pkPoint1": "مقامی فصل اور موسم کا علم",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "حقیقی کاشتکاروں کی رائے سے بہتر بنایا گیا",
  "home.vision.worldTitle": "عالمی توسیع کا تصور",
  "home.vision.worldBody": "موافقت کے لیے بنایا گیا۔ جیسے جیسے پلیٹ فارم بالغ ہوگا، یہ نئے ممالک، زبانوں، فصلوں اور موسموں تک پھیلے گا — شروع سے دوبارہ بنائے بغیر۔",
  "home.vision.worldPoint1": "ملک کے مطابق زرعی علم",
  "home.vision.worldPoint2": "اضافی زبانیں اور مقامی فصلیں",
  "home.vision.worldPoint3": "گہرے ڈیٹا انٹیگریشنز اور تجزیے",
  "home.users.title1": "انفرادی کاشتکار",
  "home.users.desc1": "چھوٹے اور درمیانے فارم جنہیں عملی رہنمائی اور ہر سرگرمی کا منظم ریکارڈ درکار ہے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہیں منظم معلومات، فیصلہ سازی میں مدد اور ٹیم بھر کے ریکارڈ درکار ہیں۔",
  "home.users.title3": "ایکو سسٹم پارٹنرز",
  "home.users.desc3": "ان پٹ سپلائرز، کوآپریٹو، انشورنس کمپنیاں اور ایکسٹینشن سروسز جو وقت کے ساتھ پلیٹ فارم سے جڑیں گے۔",
  "home.users.tagline": "سب سے پہلے کاشتکاروں کے لیے ڈیزائن کردہ — ایکو سسٹم کے ساتھ بڑھتا ہوا",
  "home.cta.eyebrow": "ابتدائی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم پر لائیں",
  "home.cta.subtitle": "اگروپیو کے ساتھ بہتر فیصلے کرنے والے کاشتکاروں میں شامل ہوں — پاکستان سے آغاز، دنیا بھر میں توسیع۔",
  "home.cta.success": "آپ فہرست میں شامل ہیں۔ جب آپ کا علاقہ کھلے گا تو ہم آپ سے رابطہ کریں گے۔",
  "home.cta.emailLabel": "ای میل کا پتہ",
  "home.cta.fineprint": "کوئی اسپام نہیں۔ کبھی بھی ان سبسکرائب کریں۔",
  "home.footer.tagline": "اے آئی سے چلنے والا فارم انٹیلیجنس پلیٹ فارم۔ مشاورت، سیٹلائٹ مانیٹرنگ، منڈی کی قیمتیں اور ریکارڈ — مٹی اور سگنل، ساتھ ساتھ۔",
  "home.footer.pagesHeading": "صفحات",
  "home.footer.pagesNavLabel": "فوٹر صفحات",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس کی شرائط",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کریں",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔ جملہ حقوق محفوظ ہیں۔",
  "home.footer.motto": "پاکستان کے لیے بنایا · دنیا کے لیے تیار",
  "hiw.meta.title": "یہ کیسے کام کرتا ہے — اگروپیو",
  "hiw.meta.description":
    "ایک منٹ کے فارم پروفائل سے لے کر مسلسل بہتر ہونے والے موسمی چکر تک: دیکھیں کہ اگروپیو سوالات، سرگرمیوں اور ریکارڈ کو ذاتی زرعی رہنمائی میں کیسے بدلتا ہے۔",
  "hiw.hero.eyebrow": "یہ کیسے کام کرتا ہے",
  "hiw.hero.titleA": "چھ چھوٹے مرحلے۔",
  "hiw.hero.titleLead": "ایک",
  "hiw.hero.titleAccent": "زیادہ سمجھدار موسم۔",
  "hiw.hero.subtitle":
    "اگروپیو ویسے ہی کام کرتا ہے جیسے کاشتکاری پہلے سے چلتی ہے — آپ بوائی کرتے ہیں، پوچھتے ہیں، کام کرتے ہیں اور ریکارڈ کرتے ہیں۔ فرق صرف یہ ہے کہ اب ہر مرحلہ اگلے کو بہتر بناتا ہے۔",
  "hiw.hero.browseFeatures": "خصوصیات دیکھیں",
  "hiw.route.navLabel": "اگروپیو کے موسمی چکر کے چھ مراحل",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بنائیں",
  "hiw.route.stop2": "پوچھیں",
  "hiw.route.stop3": "رہنمائی",
  "hiw.route.stop4": "کام کریں",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "ایک بار سیٹ اپ کریں",
  "hiw.setup.title": "آپ کا فارم ایک زندہ پروفائل بن جاتا ہے",
  "hiw.setup.body":
    "چار خانے، ایک منٹ سے کم — ضلع، فصل، بوائی کی تاریخ اور زمین کا رقبہ۔ یہی پورا فارم ہے۔ اس کے بعد ہر جواب جانتا ہے کہ یہ کہاں اور کن حالات میں اگ رہا ہے۔",
  "hiw.setup.point1": "فصل تبدیل کریں یا کسی بھی وقت نئے فارم شامل کریں",
  "hiw.setup.point2": "ٹھیکیداروں اور ڈیلرز کے لیے متعدد فارمز",
  "hiw.setup.point3": "کچھ تکنیکی نہیں پوچھا جاتا — مٹی کی رپورٹ کی ضرورت نہیں",
  "hiw.setup.mockHeading": "نیا فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بنائیں",
  "hiw.setup.mockFootnote": "ایک منٹ سے کم لگتا ہے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جس میں ضلع، فصل، بوائی کی تاریخ اور زمین کا رقبہ درج ہے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربیع",
  "hiw.setup.rowSowing": "بوائی کی تاریخ",
  "hiw.setup.valSowing": "20 نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "12 ایکڑ",
  "hiw.ask.eyebrow": "جو دل چاہے پوچھیں",
  "hiw.ask.titleA": "ایک سوال جائے۔",
  "hiw.ask.titleB": "آپ کا سارا فارم جواب دیتا ہے۔",
  "hiw.ask.body":
    "ایک ہی سوال مختلف فارموں پر مختلف مطلب رکھتا ہے۔ اس لیے جواب دینے سے پہلے اگروپیو اس سوال کو آپ کے فارم کے بارے میں معلوم ہر چیز سے ملا کر دیکھتا ہے۔",
  "hiw.ask.pipelineLabel":
    "کاشتکار کا سوال فصل، ضلع، موسم اور تاریخ کے تناظر کے ساتھ ملا کر ذاتی جواب بنایا جاتا ہے",
  "hiw.ask.question": "اب پانی دینا چاہیے یا تھوڑا انتظار؟",
  "hiw.ask.checkedAgainst": "ان چیزوں سے ملا کر",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · گٹھیاں نکلنے کا وقت",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26° · خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخچہ",
  "hiw.ask.chipValHistory": "یوریا 9 دن پہلے",
  "hiw.ask.answer":
    "دو دن رکیں — بارش کا امکان ہے، اور یوریا کے بعد زمین ابھی گیلی ہے۔ جمعے تک دیکھ لینا کافی ہے۔",
  "hiw.ask.answerMeta": "ذاتی جواب · گندم، یوریا کے 9 دن بعد",
  "hiw.ask.footnote": "لکھیں، بولیں یا کال کریں — جواب ہر صورت آپ کے فارم کا اپنا ہوتا ہے",
  "hiw.engine.eyebrow": "جواب کے پیچھے",
  "hiw.engine.title": "چار جانچیں اس سے پہلے کہ آپ ایک سطر دیکھیں",
  "hiw.engine.body":
    "رہنمائی کوئی سرچ نتیجہ نہیں۔ یہ چار دروازوں سے گزرتی ہے تاکہ جو آپ تک پہنچے وہ اسی کھیت کے لیے، اسی ہفتے کے لیے محفوظ ہو۔",
  "hiw.engine.check1Title": "معلومات جمع کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم اور فصل کا مرحلہ بھیجنے کے لمحے ساتھ ساتھ جمع کیا جاتا ہے۔",
  "hiw.engine.check2Title": "مطابقت کی جانچ",
  "hiw.engine.check2Desc":
    "مشورے کو موسم کی پیش گوئی سے پرکھا جاتا ہے — بارش میں بے کار ہونے والا سپرے انجن سے نکلتا ہی نہیں۔",
  "hiw.engine.check3Title": "ذاتی بنانا",
  "hiw.engine.check3Desc":
    "آپ کے کھیت کی تاریخ جواب کو بدل دیتی ہے — وہی فصل، الگ مٹی، الگ مشورہ۔",
  "hiw.engine.check4Title": "پہنچانا",
  "hiw.engine.check4Desc":
    "پھر وہ آپ کی زبان میں صاف اقدامات بن کر آتا ہے — اسکرین پر، آواز میں یا فون کال پر۔",
  "hiw.engine.safetyStrong": "اگر کچھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تو اگروپیو انتظار کا کہتا ہے — دیر سے ملنے والا جواب بے کار ہوا سپرے یا تباہ فصل سے بہتر ہے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کریں",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی دینا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل کاٹنا",
  "hiw.record.row1Time": "آج · صبح 6:40",
  "hiw.record.row1Label": "پانی دینا درج ہوا",
  "hiw.record.row1Detail": "نہر کا موڑ · 40 منٹ · پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج ہوئی",
  "hiw.record.row2Detail": "DAP 20 کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف دو ٹیپ — آف لائن بھی چلتا ہے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جس میں فوری ایکشن چپس اور حال ہی میں درج شدہ اندراجات ہیں",
  "hiw.record.eyebrow": "جیسے جیسے کام کریں، ریکارڈ کرتے جائیں",
  "hiw.record.titleA": "ابھی دو ٹیپ،",
  "hiw.record.titleB": "پورے موسم بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت کے لیے بنائی گئی ہے — بڑے بٹن، کم خانے، ٹائپنگ کی ضرورت نہیں۔ ہر اندراج فارم کی یادداشت کا حصہ بنتا ہے، تو مشورہ بھی فصل کے ساتھ ساتھ تیز ہوتا جاتا ہے۔",
  "hiw.record.point1": "پانی، کھادیں، بیماری، خرچ، فصل — سب ایک ٹائم لائن پر",
  "hiw.record.point2": "مکمل آف لائن چلتا ہے؛ سگنل آنے پر خود سنک ہو جاتا ہے",
  "hiw.record.point3": "بینک، خریدار یا انشورنس کے لیے موسمی خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "یہ فصل کاٹنے پر ختم نہیں ہوتا۔",
  "hiw.loop.titleB": "وہاں سے شروع ہوتا ہے۔",
  "hiw.loop.body":
    "پوچھیں، کام کریں، ریکارڈ کریں — دہرائیں۔ چکر کی هر گرد اگروپیو کو آپ کی زمین کے بارے میں نیا کچھ سکھاتی ہے، تاکہ اگلا موسم پچھلے سے آگے شروع ہو۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماتا ہے",
  "hiw.loop.benefit1Desc":
    "پچھلے موسم کی بیماریاں، خوراکیں اور تاریخیں اس موسم کا پہلا جواب بناتی ہیں۔",
  "hiw.loop.benefit2Title": "کچھ دہرانا نہیں پڑتا",
  "hiw.loop.benefit2Desc":
    "مشاورت جانتی ہے کہ کیا پہلے سپرے یا کھاد ہو چکی ہے — دوہری خوراک کا خطرہ نہیں۔",
  "hiw.loop.benefit3Title": "ہر موسم دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرضے، خریدار، انشورنس یا اگلی فصل کے فیصلے کے لیے تیار رہتی ہے۔",
    "hiw.loop.stepLearn": "سیکھیں",
  "hiw.loop.stepImprove": "بہتر بنائیں",
"hiw.loop.diagramLabel": "گول چکر خاکہ: پوچھیں، کام کریں، ریکارڈ کریں، سیکھیں، بہتر بنائیں",
  "hiw.loop.centerSeason": "موسم",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر موسم، پچھلے سے بہتر",
};
