import type { CatalogKey } from "./en.ts";

/** اردو — AI-drafted, founder-reviewed copy (plan D4). */
export const ur: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "یہ کیسے کام کرتا ہے",
  "nav.vision": "ہمارا وژن",
  "nav.signIn": "سائن اِن کریں",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کریں",
  "nav.openMenu": "مینیو کھولیں",
  "nav.closeMenu": "مینیو بند کریں",
  "common.languageSwitcherLabel": "زبان تبدیل کریں",
  "notFound.title": "صفہ موجود نہیں",
  "notFound.body": "جو صفہ آپ تلاش کر رہے ہیں وہ موجود نہیں یا منتقل ہو چکا ہو گا۔",
  "notFound.backHome": "اگروپیو کے ہوم پر واپس جائیں",
  "common.builtForPakistan": "پاکستان کے لیے بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ کی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت پر مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "اسمارٹ کاشتکاری کے لیے",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "ایک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی کی قیمتیں اور آپ کے فارم کے ریکارڈ ایک جگہ جمع کرتا ہے — ڈیٹا کو واضح فیصلوں میں بدلتا ہے، آپ کی اپنی زبان میں۔",
  "home.hero.ctaSecondary": "دیکھیں یہ کیسے کام کرتا ہے",
  "home.hero.imageAlt": "کاشتکار کھیت میں ٹیبلٹ پر اگروپیو استعمال کرتے ہوئے",
  "home.hero.readingCrop": "فصل کی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی کی نمی",
  "home.hero.noteExcellent": "بہترین",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم کی صلاحیتیں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتوں کی جانکاری",
  "home.ticker.weatherAdvisories": "موسم کے مطابق مشورے",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 زبانوں میں مشورہ",
  "home.ticker.pestAlerts": "کیڑے مکوڑے کے خطرے کی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسئلہ",
  "home.problem.title": "کاشتکاری کے فیصلے اندازے کا کھیل نہیں ہونے چائییں",
  "home.problem.subtitle": "پورے پاکستان میں کاشتکار روایت، مقامی مشورے اور بکھری ہوئی معلومات کے ساتھ بڑے رسک والے فیصلے کرتے ہیں۔ نقصان کٹائی کے وقت چکنا پڑتا ہے۔",
  "home.problem.item1Title": "غیر یقینی وقت",
  "home.problem.item1Body": "سینچائی، کھاد، دوا، بوائی، کٹائی — اہم لمحے اب بھی اندازے سے طے ہوتے ہیں، جس سے پیداوار کم اور خرچ ضائع ہوتی ہے۔",
  "home.problem.item2Title": "کھویا ہوا فارم ریکارڈ",
  "home.problem.item2Body": "سیزنوں کا علم یادداشت یا بکھری نوٹ بکوں میں رہتا ہے۔ پچھلے سال جو کام آیا، اس سے اس سال سیکھنا ناممکن ہے۔",
  "home.problem.item3Title": "بکھرا ہوا مشورہ",
  "home.problem.item3Body": "پڑوسی، دکاندار اور ویڈیوز سب جواب دیتے ہیں — لیکن چند ہی کاشتکار کی فصل، مٹی، موسم یا علاقے سے ملتے ہیں۔",
  "home.problem.kicker": "اندازے کی قیمت کٹائی پر چکتی ہے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "آپ کے فارم کی ذہانت،",
  "home.solution.titleB": "ایک جگہ",
  "home.solution.subtitle": "پورے سیزن کے لیے ایک انٹیلیجنس پلیٹ فارم — مشورہ، ریکارڈ، موسم اور بازار آپ کی زمین کے ڈیٹا سے کام کرتے ہیں، عمومی مشوروں سے نہیں۔",
  "home.solution.card1Title": "کیا کرنا ہے",
  "home.solution.card1Body": "سینچائی، کھاد، کیڑے مار اور کٹائی کے وقت کے لیے ذاتی مشورے — آپ کی فصل اور حالات کے مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے کے لیے واضح مشورہ۔",
  "home.solution.card2Title": "کب کرنا ہے",
  "home.solution.card2Body": "موسمی رہنمائی بتاتی ہے کہ کام کب کریں، تاکہ غلط وقت اور اچانک حالات آپ کی پیداوار نہ کھائیں۔",
  "home.solution.card2Answer": "حقیقی موسم اور فصل کی نشوونما کے مطابق وقت۔",
  "home.solution.card3Title": "کیا کیا جا چکا ہے",
  "home.solution.card3Body": "ہر سرگرمی — سینچائی، ان پٹ، بیماری، اخراجات، کٹائی — منظم ریکارڈ میں محفوظ جو ہر سیزن کو زیادہ سمجھدار بناتا ہے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ دستیاب۔",
};
