import type { CatalogKey } from "./en.ts";

/** اردو — AI-drafted, founder-reviewed copy (plan D4). */
export const ur: Partial<Record<CatalogKey, string>> = {
  "nav.whyAgropioo": "اگروپیو کیوں؟",
  "nav.features": "خصوصیات",
  "nav.howItWorks": "یہ کیسے کام کرتا ہے",
  "nav.vision": "ہمارا وژن",
  "nav.signIn": "سائن اِن کریں",
  "nav.getEarlyAccess": "ابتدائی رسائی حاصل کریں",
  "nav.openMenu": "مینیو کھولیں",
  "nav.closeMenu": "مینیو بند کریں",
  "common.languageSwitcherLabel": "زبان تبدیل کریں",
  "notFound.title": "صفہ موجود نہیں",
  "notFound.body": "جو صفہ آپ تلاش کر رہے ہیں وہ موجود نہیں یا منتقل ہو چکا ہو گا۔",
  "notFound.backHome": "اگروپیو کے ہوم پر واپس جائیں",
  "common.builtForPakistan": "پاکستان کے لیے بنایا گیا",
  "common.productOfAplinode": "اپلینوڈ کی پروڈکٹ",
  "home.hero.eyebrow": "مصنوعی ذہانت پر مبنی فارم انٹیلیجنس پلیٹ فارم",
  "home.hero.titleLead": "اسمارٹ کاشتکاری کے لیے",
  "home.hero.titleAccent": "ذہانت",
  "home.hero.subtitle": "ایک ہی پلیٹ فارم جو اے آئی مشیر، سیٹلائٹ مانیٹرنگ، منڈی کی قیمتیں اور آپ کے فارم کے ریکارڈ ایک جگہ جمع کرتا ہے — ڈیٹا کو واضح فیصلوں میں بدلتا ہے، آپ کی اپنی زبان میں۔",
  "home.hero.ctaSecondary": "دیکھیں یہ کیسے کام کرتا ہے",
  "home.hero.imageAlt": "کاشتکار کھیت میں ٹیبلٹ پر اگروپیو استعمال کرتے ہوئے",
  "home.hero.readingCrop": "فصل کی صحت",
  "home.hero.readingWeather": "موسم",
  "home.hero.readingSoil": "مٹی کی نمی",
  "home.hero.noteExcellent": "بہترین",
  "home.hero.noteClearSky": "صاف آسمان",
  "home.hero.noteOptimal": "مناسب",
  "home.ticker.ariaLabel": "اگروپیو پلیٹ فارم کی صلاحیتیں",
  "home.ticker.cropDoctor": "اے آئی فصل ڈاکٹر",
  "home.ticker.satelliteNdvi": "سیٹلائٹ این ڈی وی آئی مانیٹرنگ",
  "home.ticker.mandiPrices": "منڈی قیمتوں کی جانکاری",
  "home.ticker.weatherAdvisories": "موسم کے مطابق مشورے",
  "home.ticker.farmRecords": "ڈیجیٹل فارم ریکارڈ",
  "home.ticker.advisoryLanguages": "7 زبانوں میں مشورہ",
  "home.ticker.pestAlerts": "کیڑے مکوڑے کے خطرے کی اطلاع",
  "home.ticker.offlineSms": "آف لائن سہولت + ایس ایم ایس",
  "home.problem.eyebrow": "مسئلہ",
  "home.problem.title": "کاشتکاری کے فیصلے اندازے کا کھیل نہیں ہونے چائییں",
  "home.problem.subtitle": "پورے پاکستان میں کاشتکار روایت، مقامی مشورے اور بکھری ہوئی معلومات کے ساتھ بڑے رسک والے فیصلے کرتے ہیں۔ نقصان کٹائی کے وقت چکنا پڑتا ہے۔",
  "home.problem.item1Title": "غیر یقینی وقت",
  "home.problem.item1Body": "سینچائی، کھاد، دوا، بوائی، کٹائی — اہم لمحے اب بھی اندازے سے طے ہوتے ہیں، جس سے پیداوار کم اور خرچ ضائع ہوتی ہے۔",
  "home.problem.item2Title": "کھویا ہوا فارم ریکارڈ",
  "home.problem.item2Body": "سیزنوں کا علم یادداشت یا بکھری نوٹ بکوں میں رہتا ہے۔ پچھلے سال جو کام آیا، اس سے اس سال سیکھنا ناممکن ہے۔",
  "home.problem.item3Title": "بکھرا ہوا مشورہ",
  "home.problem.item3Body": "پڑوسی، دکاندار اور ویڈیوز سب جواب دیتے ہیں — لیکن چند ہی کاشتکار کی فصل، مٹی، موسم یا علاقے سے ملتے ہیں۔",
  "home.problem.kicker": "اندازے کی قیمت کٹائی پر چکتی ہے",
  "home.solution.eyebrow": "حل",
  "home.solution.titleA": "آپ کے فارم کی ذہانت،",
  "home.solution.titleB": "ایک جگہ",
  "home.solution.subtitle": "پورے سیزن کے لیے ایک انٹیلیجنس پلیٹ فارم — مشورہ، ریکارڈ، موسم اور بازار آپ کی زمین کے ڈیٹا سے کام کرتے ہیں، عمومی مشوروں سے نہیں۔",
  "home.solution.card1Title": "کیا کرنا ہے",
  "home.solution.card1Body": "سینچائی، کھاد، کیڑے مار اور کٹائی کے وقت کے لیے ذاتی مشورے — آپ کی فصل اور حالات کے مطابق۔",
  "home.solution.card1Answer": "اس کھیت، اس ہفتے کے لیے واضح مشورہ۔",
  "home.solution.card2Title": "کب کرنا ہے",
  "home.solution.card2Body": "موسمی رہنمائی بتاتی ہے کہ کام کب کریں، تاکہ غلط وقت اور اچانک حالات آپ کی پیداوار نہ کھائیں۔",
  "home.solution.card2Answer": "حقیقی موسم اور فصل کی نشوونما کے مطابق وقت۔",
  "home.solution.card3Title": "کیا کیا جا چکا ہے",
  "home.solution.card3Body": "ہر سرگرمی — سینچائی، ان پٹ، بیماری، اخراجات، کٹائی — منظم ریکارڈ میں محفوظ جو ہر سیزن کو زیادہ سمجھدار بناتا ہے۔",
  "home.solution.card3Answer": "مکمل تاریخ، ہمیشہ دستیاب۔",
  "home.features.eyebrow": "پلیٹ فارم کے اندر",
  "home.features.titleA": "متعدد انجن،",
  "home.features.titleB": "ایک ذہین پلیٹ فارم",
  "home.features.subtitle": "آپ کے اپنے الفاظ میں پہلے سوال سے لے کر پورے سیزن کے ریکارڈ تک — ہر صلاحیت اگلی کو تقویت دیتی ہے۔",
  "home.features.advisorModule": "ماڈیول 01 · مشیر",
  "home.features.advisorTitle": "اے آئی زرعی مشیر",
  "home.features.advisorTopics": "سینچائی · کھاد · کیڑے اور بیماری · کٹائی",
  "home.features.advisorBadge": "رومن اردو",
  "home.features.advisorMockAria": "پیلی پتوں والی گندم پر اگروپیو مشیر سے نمونہ گفتگو",
  "home.features.advisorUserMsg": "میری گندم کے پتے پیلے ہو رہے ہیں — کیا کروں؟",
  "home.features.advisorReplyTitle": "پیلے پتے — دو عام وجوہات:",
  "home.features.advisorReplyCause1": "پانی کی کمی",
  "home.features.advisorReplyCause1Rest": "— ٹھنڈے اوقات میں، صبح 9 بجے سے پہلے پانی دیں۔",
  "home.features.advisorReplyCause2": "نائٹروجن کی کمي",
  "home.features.advisorReplyCause2Rest": "— سب سے پرانے پتے پہلے چیک کریں؛ ضرورت ہو تو یوریا ڈالیں۔",
  "home.features.advisorReplyFooter": "اگر پتوں کے نیچے پیلی دھاریاں نظر آئیں، تصویر بھیجیں — میں بیماری کی تشخیص کر دوں گا۔",
  "home.features.advisorInputPlaceholder": "اپنا سوال لکھیں یا بولیں…",
  "home.features.advisorFooter": "اپنی فصل کے بارے میں کچھ بھی پوچھیں — روزمرہ سوالات خوش آمدید ہیں۔",
  "home.features.recordsModule": "ماڈیول 02 · ریکارڈ",
  "home.features.recordsTitle": "ڈیجیٹل فارم ریکارڈ",
  "home.features.recordsDesc": "ہر سرگرمی منظم اور درج — تاکہ مشورہ آپ کی اپنی زمین سے سیکھے۔",
  "home.features.record1Activity": "سینچائی",
  "home.features.record1Detail": "نہر · 40 منٹ",
  "home.features.record2Activity": "یوریا 46% N",
  "home.features.record2Detail": "25 کلو / ایکڑ",
  "home.features.record3Activity": "پتوں کا اسکین",
  "home.features.record3Detail": "کوئی بیماری نہیں",
  "home.features.recordsCropTag": "گندم · ربیع سیزن",
  "home.features.languageModule": "ماڈیول 03 · زبان",
  "home.features.languageTitle": "آپ کی زبان، آپ کے الفاظ",
  "home.features.languageDesc": "جو سوچتے ہیں وہی بول کر یا لکھ کر کہیں — تکنیکی انگریزی کی ضرورت نہیں۔",
  "home.features.weatherModule": "ماڈیول 04 · موسم",
  "home.features.weatherTitle": "موسم سے آگاہ رہنمائی",
  "home.features.weatherDesc": "مشورہ آپ تک پہنچنے سے پہلے حقیقی حالات چیک کرتا ہے — بارش سے پہلے سپرے کر بیٹھے تو سارا زرخیز مال بہہ جائے گا۔",
  "home.features.weatherMockAria": "پانچ دن کی پیشن گوئی جس میں جمعرات کو اسپرے نہ کرنے کا مشورہ نمایاں ہے",
  "home.features.dayMon": "پیر",
  "home.features.dayTue": "منگل",
  "home.features.dayWed": "بدھ",
  "home.features.dayThu": "جمعرات",
  "home.features.dayFri": "جمعہ",
  "home.features.holdSpray": "اسپرے روکیں",
  "home.features.weatherLegend": "مقامی موسم کی پیشن گوئی سے مشورہ والا دن نمایاں",
  "home.features.moreLink": "پلیٹ فارم مسلسل بڑھ رہا ہے — مکمل صلاحیتوں کا مجموعہ دیکھیں",
  "home.journey.eyebrow": "یہ کیسے کام کرتا ہے",
  "home.journey.title": "ایک سوال سیزن کا آغاز کرتا ہے",
  "home.journey.subtitle": "آپ کے پہلے سوال سے مکمل، ذہین فارم تاریخ تک ایک سادہ راستہ۔",
  "home.journey.step1Title": "اپنا فارم شامل کریں",
  "home.journey.step1Body": "ڈیجیٹل فارم پروفائل بنانے کے لیے مقام، فصل اور بنیادی تفصیلات درج کریں۔",
  "home.journey.step2Title": "اے آئی سے پوچھیں",
  "home.journey.step2Body": "اپنا سوال اسی زبان میں لکھیں یا بولیں جس سے آپ سب سے زیادہ آرام دہ ہوں۔",
  "home.journey.step3Title": "رہنمائی حاصل کریں",
  "home.journey.step3Body": "اپنی فصل، موسم، مقام اور فارم تاریخ پر مبنی مشورہ حاصل کریں۔",
  "home.journey.step4Title": "سرگرمی درج کریں",
  "home.journey.step4Body": "چند ٹیپوں میں سینچائی، کھاد، دوا یا بیماری درج کریں۔",
  "home.journey.step5Title": "تاریخ بنائیں",
  "home.journey.step5Body": "ہر ریکارڈ مستقبل کے مشوروں کو زیادہ سمجھدار اور موزوں بناتا ہے۔",
  "home.journey.step6Title": "نگهانی جاری رکھیں",
  "home.journey.step6Body": "پورے سیزن میں ریکارڈ دیکھیں اور پیش رفت پر نظر رکھیں۔",
  "home.matrix.eyebrow": "مکمل صلاحیتوں کا مجموعہ",
  "home.matrix.title": "ضروری سے حیران کن تک",
  "home.matrix.subtitle": "ہر خصوصیت فصل بچاتی ہے، خرچ کم کرتی ہے یا آمدنی بڑھاتی ہے。 اسے پنچانگ کی طرح پڑھیں — ہر درجہ پچھلے پر تعمیر ہوتا ہے۔",
  "home.matrix.capabilitiesLabel": "صلاحیتیں",
  "home.matrix.tier1Name": "بنیادی",
  "home.matrix.tier1Badge": "بنیادی سطح",
  "home.matrix.t1f1Title": "اے آئی فصل بیماری کی شناخت",
  "home.matrix.t1f1Body": "متاثرہ پتے کی تصویر اپ لوڈ کریں اور فوری تشخیص، شدت اور علاج کی سفارشات حاصل کریں۔",
  "home.matrix.t1f2Title": "سیٹلائٹ فیلڈ مانیٹرنگ",
  "home.matrix.t1f2Body": "اپنے کھیت کی حد متعین کریں اور مفت سینٹینل-2 تصویروں سے این ڈی وی آئی پر مبنی فصل کی صحت دیکھیں۔",
  "home.matrix.t1f3Title": "سمارٹ موسمی مشورہ",
  "home.matrix.t1f3Body": "مقامی موسم کی پیشن گوئی آپ کی فصل اور نشوونما کے مرحلے سے مل کر روزانہ قابلِ عمل مشورہ بنتی ہے۔",
  "home.matrix.t1f4Title": "منڈی قیمت ٹریکر اور پیشن گوئی",
  "home.matrix.t1f4Body": "قریبی منڈی کی قیمتیں اے آئی رجحانات کے ساتھ دیکھیں، تاکہ صحیح وقت پر بیچیں۔",
  "home.matrix.tier2Name": "امتیازی خصوصیات",
  "home.matrix.tier2Badge": "نمایاں",
  "home.matrix.t2f1Title": "علاقائی زبانوں میں وائس چیٹ بوٹ",
  "home.matrix.t2f1Body": "اردو، پنجابی، سرائیکی سمیت بولیں یا لکھیں — جواب اسی زبان میں سنیں جو آپ بہتر سمجھتے ہیں۔",
  "home.matrix.t2f2Title": "سرکاری اسکیم میچر",
  "home.matrix.t2f2Body": "اپنی معلومات درج کریں اور ہر اہل اسکیم دریافت کریں — دستاویزات اور درخواست کے لنکس سمیت۔",
  "home.matrix.t2f3Title": "فصل کی سفارش انجن",
  "home.matrix.t2f3Body": "اس سیزن میں آپ کی مٹی، موسم، منڈی کی مانگ اور بجٹ کے مطابق سب سے منافع بخش فصل۔",
  "home.matrix.t2f4Title": "فارم نفع/نقصان کیلکولیٹر",
  "home.matrix.t2f4Body": "متوقع اور حقیقی اخراجات، پیداوار، آمدنی اور نفع — بریک ایون اور آر او آئی کے ساتھ۔",
  "home.matrix.t2f5Title": "کمیونٹی فورم اور ماہر رابطہ",
  "home.matrix.t2f5Body": "سوالات پوسٹ کریں، تصاویر شیئر کریں، ہم منصف کاشتکاروں اور تصدیق شدہ ماہرین سے جواب لیں۔",
  "home.matrix.tier3Name": "حیرت انگیز",
  "home.matrix.tier3Badge": "سب سے آگے",
  "home.matrix.t3f1Title": "سیٹلائٹ تبدیلی کا مشاہدہ",
  "home.matrix.t3f1Body": "سلائیڈر کے ساتھ وقت کے ساتھ سیٹلائٹ تصاویر موازنہ کریں — نشوونما، نقصان یا قبضہ ٹریک کریں۔",
  "home.matrix.t3f2Title": "اے آئی کیڑا خطرہ پیشن گوئی",
  "home.matrix.t3f2Body": "موسم، فصل کے مرحلے اور تاریخ کی بنیاد پر ممکنہ کیڑے حملے سے پہلے ابتدائی انتباہ۔",
  "home.matrix.t3f3Title": "وائس فون کال موڈ",
  "home.matrix.t3f3Body": "ٹول فری نمبر پر کال کریں، سوال بولیں، اپنی زبان میں مشورہ سنیں — اسمارٹ فون ضروری نہیں۔",
  "home.matrix.t3f4Title": "کاربن کریڈٹ تخمینہ",
  "home.matrix.t3f4Body": "پائیدار طریقے درج کریں اور رضاکارانہ مارکیٹوں سے کاربن کریڈٹ کا تخمینہ لیں۔",
  "home.matrix.t3f5Title": "آف لائن فرسٹ پی ڈبلیو اے + ایس ایم ایس",
  "home.matrix.t3f5Body": "کھیت میں آف لائن کام کرے، کنکشن پر سنک ہو، کمزور نیٹ پر ایس ایم ایس اطلاع دے۔",
  "home.vision.eyebrow": "تصور",
  "home.vision.titleA": "پاکستان کے لیے بنایا گیا۔",
  "home.vision.titleB": "دنیا کے لیے تیار۔",
  "home.vision.pkTitle": "پاکستان کو ترجیح دینے والا طریقہ",
  "home.vision.pkBody": "پہلا ورژن پاکستان کے کھیتوں کے لیے ڈیزائن کیا گیا ہے: مقامی فصلیں، علاقائی زبانیں، حقیقی کاشتکاری کے طریقے اور حقیقی میدانی حالات۔",
  "home.vision.pkPoint1": "مقامی فصل اور موسم کا علم",
  "home.vision.pkPoint2": "اردو، پنجابی، پشتو، سندھی، سرائیکی، بلوچی، ہندکو",
  "home.vision.pkPoint3": "حقیقی کاشتکاروں کی رائے سے بہتر بنایا گیا",
  "home.vision.worldTitle": "عالمی توسیع کا تصور",
  "home.vision.worldBody": "موافقت کے لیے بنایا گیا۔ جیسے جیسے پلیٹ فارم بالغ ہوگا، یہ نئے ممالک، زبانوں، فصلوں اور موسموں تک پھیلے گا — شروع سے دوبارہ بنائے بغیر۔",
  "home.vision.worldPoint1": "ملک کے مطابق زرعی علم",
  "home.vision.worldPoint2": "اضافی زبانیں اور مقامی فصلیں",
  "home.vision.worldPoint3": "گہرے ڈیٹا انٹیگریشنز اور تجزیے",
  "home.users.title1": "انفرادی کاشتکار",
  "home.users.desc1": "چھوٹے اور درمیانے فارم جنہیں عملی رہنمائی اور ہر سرگرمی کا منظم ریکارڈ درکار ہے۔",
  "home.users.title2": "تجارتی فارم",
  "home.users.desc2": "زرعی کاروبار جنہیں منظم معلومات، فیصلہ سازی میں مدد اور ٹیم بھر کے ریکارڈ درکار ہیں۔",
  "home.users.title3": "ایکو سسٹم پارٹنرز",
  "home.users.desc3": "ان پٹ سپلائرز، کوآپریٹو، انشورنس کمپنیاں اور ایکسٹینشن سروسز جو وقت کے ساتھ پلیٹ فارم سے جڑیں گے۔",
  "home.users.tagline": "سب سے پہلے کاشتکاروں کے لیے ڈیزائن کردہ — ایکو سسٹم کے ساتھ بڑھتا ہوا",
  "home.cta.eyebrow": "ابتدائی رسائی",
  "home.cta.title": "اپنا فارم پلیٹ فارم پر لائیں",
  "home.cta.subtitle": "اگروپیو کے ساتھ بہتر فیصلے کرنے والے کاشتکاروں میں شامل ہوں — پاکستان سے آغاز، دنیا بھر میں توسیع۔",
  "home.cta.success": "آپ فہرست میں شامل ہیں۔ جب آپ کا علاقہ کھلے گا تو ہم آپ سے رابطہ کریں گے۔",
  "home.cta.emailLabel": "ای میل کا پتہ",
  "home.cta.fineprint": "کوئی اسپام نہیں۔ کبھی بھی ان سبسکرائب کریں۔",
  "home.footer.tagline": "اے آئی سے چلنے والا فارم انٹیلیجنس پلیٹ فارم۔ مشاورت، سیٹلائٹ مانیٹرنگ، منڈی کی قیمتیں اور ریکارڈ — مٹی اور سگنل، ساتھ ساتھ۔",
  "home.footer.pagesHeading": "صفحات",
  "home.footer.pagesNavLabel": "فوٹر صفحات",
  "home.footer.legalHeading": "قانونی",
  "home.footer.legalNavLabel": "قانونی",
  "home.footer.privacy": "پرائیویسی پالیسی",
  "home.footer.terms": "سروس کی شرائط",
  "home.footer.cookies": "کوکی پالیسی",
  "home.footer.disclaimer": "ڈس کلیمر",
  "home.footer.contactHeading": "رابطہ کریں",
  "home.footer.country": "پاکستان",
  "home.footer.copyright": "© {year} اگروپیو۔ جملہ حقوق محفوظ ہیں۔",
  "home.footer.motto": "پاکستان کے لیے بنایا · دنیا کے لیے تیار",
  "hiw.meta.title": "یہ کیسے کام کرتا ہے — اگروپیو",
  "hiw.meta.description":
    "ایک منٹ کے فارم پروفائل سے لے کر مسلسل بہتر ہونے والے موسمی چکر تک: دیکھیں کہ اگروپیو سوالات، سرگرمیوں اور ریکارڈ کو ذاتی زرعی رہنمائی میں کیسے بدلتا ہے۔",
  "hiw.hero.eyebrow": "یہ کیسے کام کرتا ہے",
  "hiw.hero.titleA": "چھ چھوٹے مرحلے۔",
  "hiw.hero.titleLead": "ایک",
  "hiw.hero.titleAccent": "زیادہ سمجھدار موسم۔",
  "hiw.hero.subtitle":
    "اگروپیو ویسے ہی کام کرتا ہے جیسے کاشتکاری پہلے سے چلتی ہے — آپ بوائی کرتے ہیں، پوچھتے ہیں، کام کرتے ہیں اور ریکارڈ کرتے ہیں۔ فرق صرف یہ ہے کہ اب ہر مرحلہ اگلے کو بہتر بناتا ہے۔",
  "hiw.hero.browseFeatures": "خصوصیات دیکھیں",
  "hiw.route.navLabel": "اگروپیو کے موسمی چکر کے چھ مراحل",
  "hiw.route.stepLabel": "مرحلہ {n}: {stop}",
  "hiw.route.stop1": "فارم بنائیں",
  "hiw.route.stop2": "پوچھیں",
  "hiw.route.stop3": "رہنمائی",
  "hiw.route.stop4": "کام کریں",
  "hiw.route.stop5": "ریکارڈ",
  "hiw.route.stop6": "بہتر مشورہ",
  "hiw.setup.eyebrow": "ایک بار سیٹ اپ کریں",
  "hiw.setup.title": "آپ کا فارم ایک زندہ پروفائل بن جاتا ہے",
  "hiw.setup.body":
    "چار خانے، ایک منٹ سے کم — ضلع، فصل، بوائی کی تاریخ اور زمین کا رقبہ۔ یہی پورا فارم ہے۔ اس کے بعد ہر جواب جانتا ہے کہ یہ کہاں اور کن حالات میں اگ رہا ہے۔",
  "hiw.setup.point1": "فصل تبدیل کریں یا کسی بھی وقت نئے فارم شامل کریں",
  "hiw.setup.point2": "ٹھیکیداروں اور ڈیلرز کے لیے متعدد فارمز",
  "hiw.setup.point3": "کچھ تکنیکی نہیں پوچھا جاتا — مٹی کی رپورٹ کی ضرورت نہیں",
  "hiw.setup.mockHeading": "نیا فارم پروفائل",
  "hiw.setup.mockButton": "فارم پروفائل بنائیں",
  "hiw.setup.mockFootnote": "ایک منٹ سے کم لگتا ہے",
  "hiw.setup.mockLabel":
    "فارم پروفائل فارم جس میں ضلع، فصل، بوائی کی تاریخ اور زمین کا رقبہ درج ہے",
  "hiw.setup.rowDistrict": "ضلع",
  "hiw.setup.valDistrict": "ملتان",
  "hiw.setup.rowCrop": "فصل",
  "hiw.setup.valCrop": "گندم · ربیع",
  "hiw.setup.rowSowing": "بوائی کی تاریخ",
  "hiw.setup.valSowing": "20 نومبر",
  "hiw.setup.rowLand": "زمین",
  "hiw.setup.valLand": "12 ایکڑ",
  "hiw.ask.eyebrow": "جو دل چاہے پوچھیں",
  "hiw.ask.titleA": "ایک سوال جائے۔",
  "hiw.ask.titleB": "آپ کا سارا فارم جواب دیتا ہے۔",
  "hiw.ask.body":
    "ایک ہی سوال مختلف فارموں پر مختلف مطلب رکھتا ہے۔ اس لیے جواب دینے سے پہلے اگروپیو اس سوال کو آپ کے فارم کے بارے میں معلوم ہر چیز سے ملا کر دیکھتا ہے۔",
  "hiw.ask.pipelineLabel":
    "کاشتکار کا سوال فصل، ضلع، موسم اور تاریخ کے تناظر کے ساتھ ملا کر ذاتی جواب بنایا جاتا ہے",
  "hiw.ask.question": "اب پانی دینا چاہیے یا تھوڑا انتظار؟",
  "hiw.ask.checkedAgainst": "ان چیزوں سے ملا کر",
  "hiw.ask.chipCrop": "فصل",
  "hiw.ask.chipValCrop": "گندم · گٹھیاں نکلنے کا وقت",
  "hiw.ask.chipDistrict": "ضلع",
  "hiw.ask.chipValDistrict": "ملتان",
  "hiw.ask.chipWeather": "موسم",
  "hiw.ask.chipValWeather": "26° · خشک ہفتہ",
  "hiw.ask.chipHistory": "تاریخچہ",
  "hiw.ask.chipValHistory": "یوریا 9 دن پہلے",
  "hiw.ask.answer":
    "دو دن رکیں — بارش کا امکان ہے، اور یوریا کے بعد زمین ابھی گیلی ہے۔ جمعے تک دیکھ لینا کافی ہے۔",
  "hiw.ask.answerMeta": "ذاتی جواب · گندم، یوریا کے 9 دن بعد",
  "hiw.ask.footnote": "لکھیں، بولیں یا کال کریں — جواب ہر صورت آپ کے فارم کا اپنا ہوتا ہے",
  "hiw.engine.eyebrow": "جواب کے پیچھے",
  "hiw.engine.title": "چار جانچیں اس سے پہلے کہ آپ ایک سطر دیکھیں",
  "hiw.engine.body":
    "رہنمائی کوئی سرچ نتیجہ نہیں۔ یہ چار دروازوں سے گزرتی ہے تاکہ جو آپ تک پہنچے وہ اسی کھیت کے لیے، اسی ہفتے کے لیے محفوظ ہو۔",
  "hiw.engine.check1Title": "معلومات جمع کرنا",
  "hiw.engine.check1Desc":
    "فارم پروفائل، موجودہ موسم اور فصل کا مرحلہ بھیجنے کے لمحے ساتھ ساتھ جمع کیا جاتا ہے۔",
  "hiw.engine.check2Title": "مطابقت کی جانچ",
  "hiw.engine.check2Desc":
    "مشورے کو موسم کی پیش گوئی سے پرکھا جاتا ہے — بارش میں بے کار ہونے والا سپرے انجن سے نکلتا ہی نہیں۔",
  "hiw.engine.check3Title": "ذاتی بنانا",
  "hiw.engine.check3Desc":
    "آپ کے کھیت کی تاریخ جواب کو بدل دیتی ہے — وہی فصل، الگ مٹی، الگ مشورہ۔",
  "hiw.engine.check4Title": "پہنچانا",
  "hiw.engine.check4Desc":
    "پھر وہ آپ کی زبان میں صاف اقدامات بن کر آتا ہے — اسکرین پر، آواز میں یا فون کال پر۔",
  "hiw.engine.safetyStrong": "اگر کچھ غیر محفوظ لگے،",
  "hiw.engine.safetyRest":
    "تو اگروپیو انتظار کا کہتا ہے — دیر سے ملنے والا جواب بے کار ہوا سپرے یا تباہ فصل سے بہتر ہے۔",
  "hiw.record.recorderHeading": "سرگرمی درج کریں",
  "hiw.record.syncBadge": "خودکار سنک آن",
  "hiw.record.actionIrrigation": "پانی دینا",
  "hiw.record.actionFertiliser": "کھاد",
  "hiw.record.actionPesticide": "کیڑے مار",
  "hiw.record.actionDisease": "بیماری",
  "hiw.record.actionExpense": "خرچ",
  "hiw.record.actionHarvest": "فصل کاٹنا",
  "hiw.record.row1Time": "آج · صبح 6:40",
  "hiw.record.row1Label": "پانی دینا درج ہوا",
  "hiw.record.row1Detail": "نہر کا موڑ · 40 منٹ · پلاٹ B",
  "hiw.record.row2Time": "کل",
  "hiw.record.row2Label": "کھاد درج ہوئی",
  "hiw.record.row2Detail": "DAP 20 کلو / ایکڑ",
  "hiw.record.offlineNote": "→ ہر اندراج صرف دو ٹیپ — آف لائن بھی چلتا ہے",
  "hiw.record.mockLabel":
    "سرگرمی ریکارڈر جس میں فوری ایکشن چپس اور حال ہی میں درج شدہ اندراجات ہیں",
  "hiw.record.eyebrow": "جیسے جیسے کام کریں، ریکارڈ کرتے جائیں",
  "hiw.record.titleA": "ابھی دو ٹیپ،",
  "hiw.record.titleB": "پورے موسم بہتر جواب",
  "hiw.record.body":
    "ریکارڈنگ کھیت کے لیے بنائی گئی ہے — بڑے بٹن، کم خانے، ٹائپنگ کی ضرورت نہیں۔ ہر اندراج فارم کی یادداشت کا حصہ بنتا ہے، تو مشورہ بھی فصل کے ساتھ ساتھ تیز ہوتا جاتا ہے۔",
  "hiw.record.point1": "پانی، کھادیں، بیماری، خرچ، فصل — سب ایک ٹائم لائن پر",
  "hiw.record.point2": "مکمل آف لائن چلتا ہے؛ سگنل آنے پر خود سنک ہو جاتا ہے",
  "hiw.record.point3": "بینک، خریدار یا انشورنس کے لیے موسمی خلاصہ تیار",
  "hiw.loop.eyebrow": "موسمی چکر",
  "hiw.loop.titleA": "یہ فصل کاٹنے پر ختم نہیں ہوتا۔",
  "hiw.loop.titleB": "وہاں سے شروع ہوتا ہے۔",
  "hiw.loop.body":
    "پوچھیں، کام کریں، ریکارڈ کریں — دہرائیں۔ چکر کی هر گرد اگروپیو کو آپ کی زمین کے بارے میں نیا کچھ سکھاتی ہے، تاکہ اگلا موسم پچھلے سے آگے شروع ہو۔",
  "hiw.loop.benefit1Title": "مشورہ سودا کماتا ہے",
  "hiw.loop.benefit1Desc":
    "پچھلے موسم کی بیماریاں، خوراکیں اور تاریخیں اس موسم کا پہلا جواب بناتی ہیں۔",
  "hiw.loop.benefit2Title": "کچھ دہرانا نہیں پڑتا",
  "hiw.loop.benefit2Desc":
    "مشاورت جانتی ہے کہ کیا پہلے سپرے یا کھاد ہو چکی ہے — دوہری خوراک کا خطرہ نہیں۔",
  "hiw.loop.benefit3Title": "ہر موسم دستاویزی",
  "hiw.loop.benefit3Desc":
    "صاف تاریخ قرضے، خریدار، انشورنس یا اگلی فصل کے فیصلے کے لیے تیار رہتی ہے۔",
    "hiw.loop.stepLearn": "سیکھیں",
  "hiw.loop.stepImprove": "بہتر بنائیں",
  "hiw.loop.diagramLabel": "گول چکر خاکہ: پوچھیں، کام کریں، ریکارڈ کریں، سیکھیں، بہتر بنائیں",
  "hiw.loop.centerSeason": "موسم",
  "hiw.loop.centerLoop": "چکر",
  "hiw.loop.caption": "ہر موسم، پچھلے سے بہتر",
  "feat.meta.title": "خصوصیات — اگروپیو",
  "feat.meta.description": "اگروپیو کی ہر خصوصیت دیکھیں: اے آئی فصل ڈاکٹر، سیٹلائٹ NDVI نگرانی، منڈی قیمت کی پیش گوئی، مقامی زبانوں میں آوازی مشاورت، آف لائن رسائی اور ایس ایم ایس الرٹس، اور بہت کچھ۔",
  "feat.hero.eyebrow": "خصوصیات",
  "feat.hero.titleLead": "آپ کے موسم کی ہر",
  "feat.hero.titleAccent": "ضرورت پوری",
  "feat.hero.subtitle": "چودہ خصوصیات ایک ساتھ کام کرتی ہیں — پتے اسکین کرتی ہیں، خلا سے کھیت دیکھتی ہیں، منڈی پڑھتی ہیں اور آپ کی زبان بولتی ہیں۔ دیکھیں ہر ایک آپ کے فارم کے لیے کیا کرتی ہے۔",
  "feat.hero.ctaPrimary": "ابتدائی رسائی حاصل کریں",
  "feat.hero.ctaSecondary": "دیکھیں یہ کیسے کام کرتا ہے",
  "feat.hero.builtFor": "پاکستان کے لیے بنایا گیا",
  "feat.hero.productOf": "Aplinode کی پیداوار",
  "feat.hero.tile1Label": "پتہ اسکین",
  "feat.hero.tile1Value": "94% ٹھیک",
  "feat.hero.tile2Label": "منڈی گندم",
  "feat.hero.tile2Value": "+12%",
  "feat.hero.tile3Label": "NDVI کھیت",
  "feat.hero.tile3Value": "0.82",
  "feat.hero.tile4Label": "کیڑے کا خطرہ",
  "feat.hero.tile4Value": "کم · 7 دن",
  "feat.hero.voiceReady": "آوازی مشاورت تیار",
  "feat.hero.voiceLangs": "اردو · پنجابی · سرائیکی",
  "feat.hero.liveBadge": "لائیو",
  "feat.hero.smsLabel": "ایس ایم ایس الرٹ · آف لائن موڈ",
  "feat.hero.smsMsg": "بارش 3 شام — سپرے روکیں",
  "feat.intel.eyebrow": "فصل کی ذہانت",
  "feat.intel.heading": "مسائل نقصان سے پہلے دیکھیں",
  "feat.intel.sub": "بیماری، کیڑے، موسم اور فصل کا انتخاب — چار فیصلے جو فصل طے کرتے ہیں، ہر ایک اپنے انجن کے ساتھ۔",
  "feat.intel.included": "شامل ہے",
  "feat.intel.doctorCode": "F·01 · وژن",
  "feat.intel.doctorTitle": "اے آئی فصل ڈاکٹر",
  "feat.intel.doctorDesc": "متاثرہ پتے کی تصویر لینیں اور سیکنڈوں میں بیماری کا نام، شدت اور علاج کا منصوبہ پائیں۔",
  "feat.intel.doctorMock": "پتہ اسکین نتیجہ جس میں پیلے زنگ کی زیادہ یقین کے ساتھ تشخیص",
  "feat.intel.diseaseName": "پیلا زنگ",
  "feat.intel.matchScore": "94% مماثلت",
  "feat.intel.severityLabel": "شدت",
  "feat.intel.severityValue": "درمیانہ",
  "feat.intel.pestCode": "F·02 · پیش گوئی",
  "feat.intel.pestTitle": "کیڑوں کے حملے کی الرٹس",
  "feat.intel.pestDesc": "موسم اور فصل کا مرحلہ خطرے کے ماڈل کو کھلاتا ہے جو حملے سے دن پہلے خبردار کر دیتا ہے۔",
  "feat.intel.pestMock": "سات دن کے کیڑے خطرے کے بار جو چھٹے دن بلندی پر جاتے ہیں",
  "feat.intel.pestAlert": "ہفتہ · ٹڈی دل کا خطرہ 74% — نئی گندم کو محفوظ بنائیں",
  "feat.intel.weatherCode": "F·03 · موسم",
  "feat.intel.weatherTitle": "موسم کے مطابق مشورے",
  "feat.intel.weatherDesc": "مقامی پیش گوئیاں آپ کی فصل اور نشونما کے مرحلے سے ملیتی ہیں — مشورہ صاف ہدایت بن کر آتا ہے، خام ڈیٹا نہیں۔",
  "feat.intel.weatherMock": "مثالی موسمی مشورہ جو بارش سے پہلے آبپاشی میں تاخیر کا کہتا ہے",
  "feat.intel.delayIrrigation": "آج پانی دینے میں تاخیر کریں",
  "feat.intel.rainNote": "شام 3 بجے بارش کا امکان — پہلے آسمان کو کھیت سیراب کرنے دیں۔",
  "feat.intel.waterSaved": "پانی کی بچت",
  "feat.intel.cropCode": "F·04 · منصوبہ بندی",
  "feat.intel.cropTitle": "فصل کی سفارش",
  "feat.intel.cropDesc": "مٹی، موسم، مانگ اور آپ کا بجٹ ایک ساتھ جانچے جاتے ہیں — وہ بوئیں جو اس موسم منافع دے۔",
  "feat.intel.cropMock": "درجہ بند فصل سفارشات جن میں گندم اوپر",
  "feat.intel.crop1": "گندم",
  "feat.intel.crop2": "سرسوں",
  "feat.intel.crop3": "چنا",
  "feat.field.eyebrow": "کھیت اور منڈی کی ذہانت",
  "feat.field.headingA": "آپ کی زمین خلا سے ناپی جاتی ہے۔",
  "feat.field.headingB": "آپ کی فصل ڈیٹا سے پرکی جاتی ہے۔",
  "feat.field.sub": "ہر ایکڑ پر سیٹلائٹ کی نظریں اور قریبی ہر منڈی کا جائزہ — تاکہ نشونما اور فروخت دونوں صحیح وقت پر ہوں۔",
  "feat.field.ndviCode": "F·05 · سیٹلائٹ",
  "feat.field.ndviTitle": "NDVI کھیت نگرانی",
  "feat.field.ndviDesc": "اپنی حد ایک بار نشان زد کریں؛ ہر صاف سیٹلائٹ پاس پر صحت کے زون اپ ڈیٹ ہوتے ہیں — کمزور حصے آنکھ سے پہلے سامنے آتے ہیں۔",
  "feat.field.ndviMock": "کھیت صحت گرڈ جس میں گہرا سبز مضبوط فصل نشونما ظاہر کرتا ہے",
  "feat.field.weakZone": "کمزور زون · قطار 2",
  "feat.field.priceCode": "F·06 · منڈی",
  "feat.field.priceTitle": "منڈی قیمت پیش گوئی",
  "feat.field.priceDesc": "قریبی منڈیوں کی موجودہ ریٹس اور رجحان کی پیش گوئی — اس وقت بیچیں جب گراف کہے، خریدار جب کہے نہیں۔",
  "feat.field.priceMock": "گندم قیمت رجحان آٹھ ہفتوں میں بلندی کی طرف، رکے رہنے کی سفارش کے ساتھ",
  "feat.field.wheatTrend": "گندم · 8 ہفتے",
  "feat.field.holdStock": "↑ 12% — مال رکھیں",
  "feat.field.financeCode": "F·07 · مالیات",
  "feat.field.financeTitle": "نفع و نقصان ٹریک",
  "feat.field.financeDesc": "ہر روپیہ آنے اور جانے کا، پورے موسم — منڈی یا بینک جانے سے پہلے بریک ایون اور آر او آئی تیار۔",
  "feat.field.ledgerMock": "موسمی خرچ کھاتہ جس میں ان پٹ، مزدوری، آبپاشی اور آمدنی",
  "feat.field.rowInputs": "ان پٹس",
  "feat.field.rowLabour": "مزدوری",
  "feat.field.rowIrrigation": "آبپاشی",
  "feat.field.rowRevenue": "آمدنی (تخمینی)",
  "feat.field.netMargin": "خالص مارجن",
  "feat.voice.eyebrow": "سب کے لیے رسائی",
  "feat.voice.headingA": "اسمارٹ فون نہیں؟",
  "feat.voice.headingB": "انگریزی نہیں؟ پھر بھی شامل۔",
  "feat.voice.sub": "بہترین مشورہ بے کار ہے اگر وہ کاشتکار تک پہنچے ہی نہیں۔ ہر خصوصیت فون کال جواب دیتی ہے، آواز سنتی ہے اور سگنل ختم علاقے میں بھی چلتی ہے۔",
  "feat.voice.speakCode": "F·08 · آواز",
  "feat.voice.speakTitle": "اپنا سوال بولیں",
  "feat.voice.speakMock": "رومن اردو میں مشاورت سے آوازی گفتگو",
  "feat.voice.chatUser": "میری فصل کے پتوں پر دھبے ہیں",
  "feat.voice.chatAdvisor": "دھبوں کی تصویر بھیجیں — میں ابھی تشخیص کرتا ہوں۔",
  "feat.voice.inputPlaceholder": "بول کر پوچھیں…",
  "feat.voice.callCode": "F·09 · کال",
  "feat.voice.callTitle": "ٹول فری نمبر ڈائل کریں",
  "feat.voice.callMock": "اگروپیو وائس اسسٹنٹ کے ساتھ ٹول فری کال کی نقل",
  "feat.voice.greetingLine": "اگروپیو میں آپ کا خوش آمدید ہے",
  "feat.voice.heardLine": "آواز سمجھ لی — جواب تیار ہے",
  "feat.voice.callEnded": "کال ختم · خلاصہ محفوظ",
  "feat.voice.anyPhone": "کسی بھی فون پر · انٹرنیٹ نہیں چاہیے",
  "feat.voice.offlineCode": "F·10 · آف لائن + ایس ایم ایس",
  "feat.voice.offlineTitle": "سگنل ختم علاقے بھی نہیں روکتے",
  "feat.voice.offlineDesc": "مشورے، ریکارڈ اور کیلکولیٹر بغیر سگنل کام کرتے رہتے ہیں؛ نیٹ ورک واپسی پر سب سنک ہو جاتا ہے اور اہم الرٹس ایس ایم ایس سے آتے ہیں۔",
  "feat.voice.networkStatus": "نیٹ ورک حالت",
  "feat.voice.offlineQueued": "آف لائن · 3 ریکارڈ قطار میں",
  "feat.voice.smsStamp": "ایس ایم ایس · 07:42",
  "feat.voice.smsMsg": "موسم الرٹ: بارش شام 3 بجے — سپرے کا وقت بدل لیں۔",
  "feat.manage.eyebrow": "نبھائیں اور بڑھائیں",
  "feat.manage.headingA": "مشورہ ابتدا ہے۔",
  "feat.manage.headingB": "باقی سب ریکارڈ پر چلتا ہے۔",
  "feat.manage.sub": "تاریخچہ، سبسڈی، پائیداری اور کاشتکاروں کی کمیونٹی — خاموش خصوصیات جو ہر موسم جمع ہوتی ہیں۔",
  "feat.manage.diaryCode": "F·11 · ریکارڈز",
  "feat.manage.diaryTitle": "ڈیجیٹل فارم ڈائری",
  "feat.manage.diaryDesc": "آبپاشی سے کٹائی تک، سب ایک ٹائم لائن پر جسے مشاورت جواب سے پہلے پڑھتی ہے۔",
  "feat.manage.timelineMock": "اگست کی فارم سرگرمی ٹائم لائن",
  "feat.manage.tl1Date": "12 اگست",
  "feat.manage.tl1Label": "آبپاشی",
  "feat.manage.tl1Detail": "نہر کی باری · 40 منٹ",
  "feat.manage.tl2Date": "09 اگست",
  "feat.manage.tl2Label": "یوریا دیا گیا",
  "feat.manage.tl2Detail": "25 کلو / ایکڑ",
  "feat.manage.tl3Date": "02 اگست",
  "feat.manage.tl3Label": "پتہ اسکین",
  "feat.manage.tl3Detail": "صاف · کوئی بیماری نہیں",
  "feat.manage.schemeCode": "F·12 · اسکیمز",
  "feat.manage.schemeTitle": "سبسڈی اور اسکیم تلاش",
  "feat.manage.schemeDesc": "سرکاری رقم جس کے آپ پہلے سے اہل ہیں — ملائی، سمجھائی اور ایک ٹیپ درخواست کے لیے جوڑی جاتی ہے۔",
  "feat.manage.checklistMock": "اہلیت چیک لسٹ جس میں چار میں سے تین شرطیں مکمل",
  "feat.manage.check1": "زمین کی تصدیق ہوئی",
  "feat.manage.check2": "فصل کا موسم مطابقت رکھتا ہے",
  "feat.manage.check3": "شناختی کارڈ رجسٹرڈ",
  "feat.manage.check4": "بینک اکاؤنٹ جڑا",
  "feat.manage.programName": "Kisaan Support Program",
  "feat.manage.readyBadge": "75% تیار",
  "feat.manage.carbonCode": "F·13 · پائیداری",
  "feat.manage.carbonTitle": "سبز طریقوں کے انعامات",
  "feat.manage.carbonDesc": "نامیاتی اور کم ہل کے طریقے درج کریں؛ سیٹلائٹ سبز احاطہ تصدیق کرتا ہے اور کاربن کریڈٹ کی قدر کا تخمینہ لگتا ہے۔",
  "feat.manage.carbonMock": "کاربن خلاصہ جس میں قبضہ شدہ ٹن اور سالانہ تخمینی قدر",
  "feat.manage.co2Label": "CO₂ جذب",
  "feat.manage.creditLabel": "کریڈٹ قدر / سال",
  "feat.manage.forumCode": "F·14 · کمیونٹی",
  "feat.manage.forumTitle": "کاشتکار فورم + ماہرین",
  "feat.manage.forumDesc": "مسئلہ پوسٹ کریں، ان کاشتکاروں سے جواب پائیں جنہوں نے خود سامنا کیا — تصدیق شدہ ماہرین درست حل نشان زد کرتے ہیں۔",
  "feat.manage.threadMock": "کمیونٹی بحث جس میں ماہر کی تصدیق شدہ جواب",
  "feat.manage.threadQuestion": "کپاس میں سفید مکھی کا بہترین علاج؟",
  "feat.manage.threadMeta": "ملتان · 12 جوابات · 34 ووٹ",
  "feat.manage.expertBadge": "ماہر کی تصدیق شدہ جواب",
  "feat.manage.threadAnswer": "نیم کے تیل کا سپرے، شام کو — دو بار، 5 دن کے وقفے پر۔",
  "vp.meta.title": "ویژن — اگروپیو",
  "vp.meta.description": "اگروپیو کا وژن: ہر کسان کی جیب میں ذہین زرعی رہنمائی — پاکستان سے آغاز، پانچ عقائد، تین افق اور وعدے جن سے کوئی سمجھوتہ نہیں۔",
  "vp.hero.eyebrow": "ہمارا وژن",
  "vp.hero.titleLead": "ایک قابل اعتماد مشیر",
  "vp.hero.titleAccent": "ہر کسان کی جیب میں۔",
  "vp.hero.sub": "ذہین رہنمائی کا انحصار دولت، خواندگی یا زبان پر نہیں ہونا چاہیے۔ اگروپیو اس لیے موجود ہے تاکہ ہر کسان — کسی بھی فون پر، کسی بھی گاؤں میں — اسی اعتماد سے کھیتی کرے جیسے کوئی ماہر ساتھ کھڑا ہو۔",
  "vp.hero.tagStart": "ضرورت سب سے پہلے",
  "vp.hero.tagThen": "پھر پوری دنیا",
  "vp.hero.ctaLink": "دیکھیں ہم نے کیا بنایا",
  "vp.beliefs.eyebrow": "ہمارے عقائد",
  "vp.beliefs.heading": "پانچ عقائد ہر فیصلے کی شکل دیتے ہیں",
  "vp.beliefs.b1Title": "ترقی",
  "vp.beliefs.b1Desc": "زندہ فصلیں، صحتمند زمین، خوشحال کسان۔",
  "vp.beliefs.b2Title": "ذہانت",
  "vp.beliefs.b2Desc": "مقامی موسم، تاریخ اور فصل سائنس پر مبنی اے آئی۔",
  "vp.beliefs.b3Title": "رسائی",
  "vp.beliefs.b3Desc": "ہر کسان کی اپنی زبان اور اپنے ماحول میں رہنمائی۔",
  "vp.beliefs.b4Title": "اعتماد",
  "vp.beliefs.b4Desc": "عملی، بروقت مشورہ جو روزگار کا تحفظ کرے۔",
  "vp.beliefs.b5Title": "مستقبل",
  "vp.beliefs.b5Desc": "روایت کا احترام کرنے والی توسیع پذیر ٹیکنالوجی۔",
  "vp.horizons.eyebrow": "آنے والا راستہ",
  "vp.horizons.heading": "تین افق، ایک سمت",
  "vp.horizons.h1Tag": "افق 01",
  "vp.horizons.h1Phase": "ابھی",
  "vp.horizons.h1Status": "کھیتوں میں",
  "vp.horizons.h1Body": "سب سے پہلے پاکستان۔ مرکزی مشیر، ڈیجیٹل فارم ریکارڈ، موسم سے آگاہ رہنمائی اور چھ علاقائی زبانیں — کسی اور چیز سے پہلے حقیقی کسانوں کی رائے سے مکمل۔",
  "vp.horizons.h1P1": "مرکزی مشیر + ریکارڈ",
  "vp.horizons.h1P2": "چھ زبانیں",
  "vp.horizons.h1P3": "حقیقی کسانوں سے بہتری",
  "vp.horizons.h2Tag": "افق 02",
  "vp.horizons.h2Phase": "اگلا مرحلہ",
  "vp.horizons.h2Status": "پھیلاؤ",
  "vp.horizons.h2Body": "گھر میں گہرائی اور وسعت — پاکستان بھر میں مزید فصلیں اور علاقے، زرعی ڈیٹا ذرائع سے مضبوط تعلق، اور وہ تجزیات جو ہر سفارش کو مزید ذاتی بناتی ہیں۔",
  "vp.horizons.h2P1": "مزید فصلیں اور علاقے",
  "vp.horizons.h2P2": "ڈیٹا انٹیگریشنز",
  "vp.horizons.h2P3": "جدید تجزیات",
  "vp.horizons.h3Tag": "افق 03",
  "vp.horizons.h3Phase": "بعد میں",
  "vp.horizons.h3Status": "عالمگیر",
  "vp.horizons.h3Body": "پلیٹ فارم نئے ملکوں، موسموں، فصلوں، زبانوں اور طریقوں کے مطابق ڈھل جاتا ہے — عالمی سطح پر ڈھلنے والی زرعی ذہانت، بغیر صفر سے شروع کیے۔",
  "vp.horizons.h3P1": "نئے ملک",
  "vp.horizons.h3P2": "نئی زبانیں اور موسم",
  "vp.horizons.h3P3": "عالمی پلیٹ فارم",
  "vp.outcomes.eyebrow": "کامیابی کی شکل",
  "vp.outcomes.heading": "چار نتائج جن پر ہم خود کو تولتے ہیں",
  "vp.outcomes.sub": "وژن ایپ نہیں — فارم پر بدلنے والی حالت ہے۔ ہر چیز ان چار نتائج کے مقابل جاری ہوتی ہے۔",
  "vp.outcomes.o1Title": "بہترین فیصلے",
  "vp.outcomes.o1Desc": "ہر انتخاب — پانی، ان پٹ، وقت — عادات کے بجائے ڈیٹا پر مبنی۔",
  "vp.outcomes.o2Title": "زیادہ پیداوار",
  "vp.outcomes.o2Desc": "صحتمند فصلیں، وقت پر ان پٹ، اور عروج پر کٹی فصل۔",
  "vp.outcomes.o3Title": "کم بچائے جا سکنے والے نقصانات",
  "vp.outcomes.o3Desc": "بیماری، کیڑے اور موسم بروقت پکڑے گئے — فصل کھونے سے پہلے۔",
  "vp.outcomes.o4Title": "فارم کاروبار کی طرح",
  "vp.outcomes.o4Desc": "منظم ریکارڈ اور موسمی ذہانت جسے بینک اور خریدار تسلیم کریں۔",
  "vp.principles.eyebrow": "سمجھوتہ نہیں",
  "vp.principles.heading": "وہ وعدے جن پر ہم بناتے ہیں",
  "vp.principles.sub": "وژن تفصیلات میں ناکام ہوتا ہے۔ یہ عہد ہر خاصیت، ہر صفحہ، ہر ریلیز پر لاگو ہیں — آج سے۔",
  "vp.principles.c1Title": "کسان کا فائدہ اول",
  "vp.principles.c1Desc": "ہر خاصیت کھیت کی ضرورت سے شروع ہوتی ہے — ٹیکنالوجی سے کبھی نہیں۔",
  "vp.principles.c2Title": "زبان پہلے",
  "vp.principles.c2Desc": "ہر اسکرین اور ہر جواب کسان کی اپنی زبان میں پہنچتا ہے۔",
  "vp.principles.c3Title": "دھوپ میں پڑھنے کے قابل",
  "vp.principles.c3Desc": "تیز کنٹراسٹ دوپہر کی دھوپ کے لیے، صرف دفتر کے لیے نہیں۔",
  "vp.principles.c4Title": "سادہ الفاظ",
  "vp.principles.c4Desc": "اتنی سادہ کہ ایک پڑوسی دوسرے کو سمجھا سکے۔",
  "vp.principles.c5Title": "پہلے فون",
  "vp.principles.c5Desc": "موبائل فرسٹ، بڑے ٹچ ٹارگٹ — اب کھیتی فون پر ہی چلتی ہے۔",
  "vp.principles.c6Title": "طرز میں قدرتی",
  "vp.principles.c6Desc": "حرکت اور خاکہ جو فطری محسوس ہو — نشوونما، مشینری کبھی نہیں۔",
  "vp.principles.motto": "مٹی اور سگنل — ساتھ ساتھ",
  "wy.meta.title": "اگروپیو کیوں — اے آئی سے لیس فارم ذہانت",
  "wy.meta.description": "کھیتی باڑی کے فیصلے اندازے پر نہیں چھوڑے جا سکتے۔ دیکھیں اگروپیو کیسے اے آئی مشیر، فارم ریکارڈ، موسم سے آگاہ رہنمائی اور مقامی زبانیں ایک پاکستان اول پلیٹ فارم پر جمع کرتا ہے۔",
  "wy.hero.eyebrow": "اگروپیو کیوں",
  "wy.hero.titleLead": "جہاں مٹی ملتی ہے",
  "wy.hero.titleAccent": "سگنل سے",
  "wy.hero.sub": "کھیتی باڑی کے فیصلے اندازوں پر نہیں چھوڑے جا سکتے۔ اگروپیو ایک ہی پلیٹ فارم میں اے آئی مشیر، آپ کے فارم کا ریکارڈ، موسم سے آگاہ رہنمائی اور آپ کی اپنی زبان فراہم کرتا ہے — تاکہ ہر فیصلہ آپ کی زمین کی حقیقت پر مبنی ہو۔",
  "wy.hero.ctaPrimary": "جلد رسائی حاصل کریں",
  "wy.hero.ctaSecondary": "پلیٹ فارم دیکھیں",
  "wy.hero.tagStart": "پاکستان کے لیے بنایا گیا",
  "wy.hero.tagThen": "Aplinode کا پروڈکٹ",
  "wy.hero.svgLabel": "کھیت پر لہراتی ہوئی خم دار بیل بوٹی لکیریں",
  "wy.origin.eyebrow": "ہم نے یہ کیوں بنایا",
  "wy.origin.heading": "اہم فیصلے محض اندازے پر نہیں ٹکے ہونے چاہئیں",
  "wy.origin.sub": "اگروپیو کی شروعات ایک سادہ مشاہدے سے ہوئی: کسان کا موسم چند فیصلوں سے طے ہوتا ہے، اور ہر فیصلہ اصل ذہانت کا حقدار ہے۔",
  "wy.origin.g1Title": "وقت کا اندازہ",
  "wy.origin.g1Desc": "سینچائی، کھاد، بوائی، کٹائی — موسم کا فیصلہ کرنے والے لمحات اب بھی عادت اور امید سے چنے جاتے ہیں۔",
  "wy.origin.g2Title": "تاریخ مٹ جاتی ہے",
  "wy.origin.g2Desc": "کب سپرے ہوا، کب کھیت سیراب ہوا، پچھلے سال کون سی بیماری لگی — کچھ بھی لکھا نہیں جاتا، اس لیے اس سے کچھ سیکھا نہیں جا سکتا۔",
  "wy.origin.g3Title": "مشورے بکھرے ہوئے ہیں",
  "wy.origin.g3Desc": "پڑوسی، دکاندار اور ویڈیوز ہر ایک جواب دیتا ہے — مگر کسی کے پاس آپ کی فصل، آپ کی مٹی یا اس ہفتے کی فضا کا اصل علم نہیں ہوتا۔",
  "wy.origin.banner": "اندازے کی قیمت کٹائی کے دن چکانی پڑتی ہے",
  "wy.diff.eyebrow": "اسے مختلف کیا بناتا ہے",
  "wy.diff.heading1": "صرف ایک اور مشورے والی ایپ نہیں۔",
  "wy.diff.heading2": "ایک فارم ذہانت کا پلیٹ فارم۔",
  "wy.diff.sub": "زیادہ تر ٹولز صرف سوالوں کے جواب دیتے ہیں۔ اگروپیو آپ کے فارم کو سیکھتا ہے — اور آپ کے درج کردہ ہر کام کے ساتھ مزید کارآمد ہوتا جاتا ہے۔",
  "wy.diff.personalTitle": "ذاتی نوعیت کا، عام نہیں",
  "wy.diff.personalDesc": "تجاویز آپ کی فصل، آپ کے مقام، موجودہ موسم اور آپ کے فارم کی اپنی تاریخ سے بنتی ہیں — کبھی سب کے لیے ایک ہی نسخہ نہیں۔",
  "wy.diff.chip1": "آپ کی فصل",
  "wy.diff.chip2": "آپ کا ضلع",
  "wy.diff.chip3": "اس ہفتے کا موسم",
  "wy.diff.chip4": "آپ کا پچھلا موسم",
  "wy.diff.langTitle": "آپ کی زبان بولتا ہے",
  "wy.diff.langDesc": "جیسے آپ واقعی بولتے ہیں اسی طرح پوچھیں اور سمجھیں — کوئی مشکل انگریزی ضروری نہیں۔",
  "wy.diff.memoryTitle": "ہر فارم کی یادداشت",
  "wy.diff.memoryDesc": "سینچائی، ان پٹ، بیماری، خرچ، کٹائی — ہر کام منظم ریکارڈ میں محفوظ، تاکہ ہر موسم پچھلے سے بہتر آغاز کرے۔",
  "wy.diff.weatherTitle": "بنیادی طور پر موسم سے آگاہ",
  "wy.diff.weatherDesc": "رہنمائی آپ تک پہنچنے سے پہلے اصل حالات دیکھتی ہے — تاکہ بارش سے گھنٹوں پہلے سپرے کا مشورہ نہ دیا جائے۔",
  "wy.diff.platformTitle": "ایک پلیٹ فارم، پورا موسم",
  "wy.diff.platformDesc": "مشیر، ریکارڈ، موسم کی رہنمائی اور مشاورت مل کر کام کرتے ہیں — الگ ایپس اور کاپیوں میں بکھرے نہیں رہتے۔",
  "wy.diff.pakTitle": "پاکستان اول",
  "wy.diff.pakDesc": "مقامی فصلیں، علاقائی طریقے اور حقیقی کھیت کے حالات پہلے دن سے ڈیزائن میں شامل ہیں — بعد میں جوڑے گئے سوچ کے طور پر نہیں۔",
  "wy.diff.pakBadge": "یہیں سے شروعات",
  "wy.life.eyebrow": "مشیر کس کس میں رہنمائی کرتا ہے",
  "wy.life.heading": "فصل کے چکر کے ہر فیصلے کے لیے رہنمائی",
  "wy.life.sub": "ایک مشیر پورے فصلی دور میں آپ کے ساتھ رہتا ہے — موسم کی منصوبہ بندی سے لے کر فصل گھر پہنچانے تک۔",
  "wy.life.s1Title": "سینچائی کا وقت",
  "wy.life.s1Desc": "جانیں کب پانی دینا ہے — اور کب انتظار کرنا ہے۔",
  "wy.life.s2Title": "فصل کی منصوبہ بندی",
  "wy.life.s2Desc": "اپنی زمین کے موافق فصلیں اور بوائی کی کھڑکیاں منتخب کریں۔",
  "wy.life.s3Title": "کھاد اور کیڑے مار دواؤں کی رہنمائی",
  "wy.life.s3Desc": "صحیح ان پٹ، صحیح مقدار میں، صحیح وقت پر۔",
  "wy.life.s4Title": "کیڑے اور بیماری میں مدد",
  "wy.life.s4Desc": "مسائل جلد پکڑیں اور پھیلنے سے پہلے عمل کریں۔",
  "wy.life.s5Title": "کٹائی کا وقت",
  "wy.life.s5Desc": "اس لمحے کاٹیں جو پیداوار اور معیار کی حفاظت کرے۔",
  "wy.life.s6Title": "موسم سے آگاہ تجاویز",
  "wy.life.s6Desc": "ہر مشورہ پہلے آج کے حالات دیکھتا ہے۔",
  "wy.life.s7Title": "روزمرہ سوالات",
  "wy.life.s7Desc": "اپنی فصل کے بارے میں کچھ بھی پوچھیں، موسم کے کسی بھی دن۔",
  "wy.value.eyebrow": "وعدہ",
  "wy.value.heading1": "کیا کرنا ہے۔ کب کرنا ہے۔",
  "wy.value.heading2": "اور کیا ہو چکا ہے۔",
  "wy.value.sub": "اگروپیو کی ہر سہولت ان تین جوابات میں سے ایک کی خدمت کرتی ہے — اسی طرح فیصلوں کا موسم اعتماد کا موسم بن جاتا ہے۔",
  "wy.value.p1Heading": "کیا کرنا ہے",
  "wy.value.p1Desc": "آپ کی فصل اور حالات کے مطابق واضح، مخصوص تجاویز — عام نکات نہیں۔",
  "wy.value.p2Heading": "کب کرنا ہے",
  "wy.value.p2Desc": "اصل موسم اور نشوونما کے مرحلے کے مطابق وقت، تاکہ صحیح اقدام صحیح لمحے پر ہو۔",
  "wy.value.p3Heading": "کیا ہو چکا ہے",
  "wy.value.p3Desc": "ہر کام کی منظم تاریخ — ہمیشہ دستیاب، ہمیشہ بہتر مشورے کی بنیاد۔",
  "wy.who.eyebrow": "کن کے لیے ہے",
  "wy.who.heading": "کسان سے شروع ہو کر آگے",
  "wy.who.a1Title": "انفرادی کسان",
  "wy.who.a1Desc": "ہر فیصلے میں عملی، ذاتی رہنمائی — اور جو کچھ ہو چکا ہے اس کا منظم ریکارڈ۔",
  "wy.who.a2Title": "تجارتی فارم اور زرعی کاروبار",
  "wy.who.a2Desc": "ٹیموں، کھیتوں اور موسموں میں منظم فارم معلومات اور قابلِ بھروسہ فیصلہ سازی کی مدد۔",
  "wy.who.a3Title": "ایکو سسٹم کے شراکت دار",
  "wy.who.a3Desc": "ان پٹ فراہم کرنے والے، کوآپریٹو، بیمہ کمپنیاں اور زرعی توسیعی خدمات — جیسے جیسے پلیٹ فارم بڑھتا ہے۔",
  "wy.who.strip": "فارم کے گرد ماحول کے ساتھ بڑھتے ہوئے",

  "auth.backHome": "واپس ہوم پر",
  "auth.emailLabel": "ای میل کا پتہ",
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordLabel": "پاس ورڈ",
  "auth.showPassword": "پاس ورڈ دکھائیں",
  "auth.hidePassword": "پاس ورڈ چھپائیں",
  "auth.err.emailRequired": "اپنا ای میل کا پتہ لکھیں۔",
  "auth.err.emailInvalid": "درست ای میل کا پتہ لکھیں۔",
  "auth.err.passwordRequired": "پاس ورڈ بنائیں۔",
  "auth.err.passwordMin": "کم از کم ۸ حروف استعمال کریں۔",
  "auth.err.passwordMax": "زیادہ سے زیادہ ۶۴ حروف استعمال کریں۔",
  "auth.err.nameRequired": "اپنا پورا نام لکھیں۔",
  "auth.err.phoneInvalid": "درست فون نمبر لکھیں۔",
  "auth.err.confirmRequired": "اپنا پاس ورڈ دوبارہ لکھیں۔",
  "auth.err.termsRequired": "آگے بڑھنے کے لیے شرائط قبول کریں۔",
  "auth.err.passwordMismatch": "پاس ورڈ ایک جیسے نہیں ہیں۔",
  "auth.err.loginPasswordRequired": "اپنا پاس ورڈ لکھیں۔",
  "auth.err.tooManyAttempts": "بہت زیادہ کوششیں — براہ کرم تھوڑی دیر بعد دوبارہ کوشش کریں۔",
  "auth.err.serverError": "ہماری طرف سے خرابی پیش آئی۔ براہ کرم دوبارہ کوشش کریں۔",
  "auth.err.invalidCredentials": "ای میل یا پاس ورڈ غلط ہے۔",

  "li.meta.title": "سائن اِن — اگروپیو",
  "li.meta.description":
    "اگروپیو، اے آئی سے لیس فارم ذہانت کے پلیٹ فارم میں سائن اِن کریں۔ آپ کا مشیر، ریکارڈ اور رہنمائیاں — وہیں موجود جہاں آپ نے چھوڑی تھیں۔",
  "li.brand.headingA": "آپ کے فارم کی ذہانت،",
  "li.brand.headingB": "وہیں منتظر جہاں آپ نے چھوڑی۔",
  "li.demo.aria": "اگروپیو مشیر سے گفتگو کی جھلک",
  "li.demo.user": "میری گندم کے پتے پیلے ہو رہے ہیں — کیا کروں؟",
  "li.demo.advisorLabel": "دو وجوہات:",
  "li.demo.advisorBody": "پانی کی کمی یا نائٹروجن کی کمی۔ پہلے صبح ٹھنڈے وقت میں پانی دیں۔",
  "li.point1": "آپ کی اپنی زبان میں اے آئی مشیر",
  "li.point2": "سیٹیلائٹ سے فصل کی صحت کی نگرانی",
  "li.point3": "ہر موسم کا ڈیجیٹل ریکارڈ",
  "li.eyebrow": "سائن اِن",
  "li.heading": "آپ کے فارم پر دوبارہ خوش آمدید",
  "li.sub": "سائن اِن کریں تاکہ اپنے فارم کے مشیر، ریکارڈ اور رہنمائیوں تک پہنچ سکیں۔",
  "li.passwordPlaceholder": "آپ کا پاس ورڈ",
  "li.forgot": "پاس ورڈ بھول گئے؟",
  "li.submitting": "سائن اِن ہو رہا ہے…",
  "li.noAccount": "ابھی اکاؤنٹ نہیں؟ ابتدائی رسائی خطہ در خطہ کھلی جا رہی ہے —",
  "li.noAccountEnd": "۔",
  "li.createAccount": "اپنا اکاؤنٹ بنائیں",

  "su.meta.title": "اکاؤنٹ بنائیں — اگروپیو",
  "su.meta.description":
    "اپنا اگروپیو اکاؤنٹ بنائیں: ذاتی نوعیت کا اے آئی مشیر، موسم سے آگاہ رہنمائی، اور فارم ریکارڈ جو ہر موسم کو بہتر بناتے ہیں۔ پاکستان کے لیے بنایا گیا۔",
  "su.brand.headingA": "اپنا موسم شروع کریں",
  "su.brand.headingB": "ذہانت کے ساتھ۔",
  "su.profile.aria": "سائن اپ کے بعد بننے والے فارم پروفائل کی جھلک",
  "su.profile.badge": "فارم پروفائل · ایک منٹ میں تیار",
  "su.profile.district": "ضلع",
  "su.profile.crop": "فصل",
  "su.profile.language": "مشورے کی زبان",
  "su.profile.districtValue": "ملتان",
  "su.profile.cropValue": "گندم · ربیع",
  "su.profile.langValue": "رومن اردو",
  "su.included1": "پہلے دن سے ذاتی نوعیت کا مشیر",
  "su.included2": "آپ کے ضلع کے لیے موسم سے آگاہ رہنمائی",
  "su.included3": "فارم ریکارڈ جو ہر موسم کو بہتر بناتے ہیں",
  "su.eyebrow": "اکاؤنٹ بنائیں",
  "su.heading": "اپنا فارم اگروپیو لائیں",
  "su.sub": "ایک اکاؤنٹ — آپ کے مشیر، ریکارڈ اور اس موسم کی ہر رہنمائی کے لیے۔",
  "su.registered.title": "یہ ای میل پہلے سے رجسٹرڈ ہے۔",
  "su.registered.body":
    "سائن اِن کریں، یا اگر پاس ورڈ بھول گئے ہیں تو ری سیٹ کریں — آپ کا فارم وہیں منتظر ہے جہاں آپ نے چھوڑا تھا۔",
  "su.registered.reset": "پاس ورڈ ری سیٹ کریں",
  "su.name.label": "پورا نام",
  "su.name.placeholder": "مثلاً محمد احمد",
  "su.phone.label": "فون نمبر",
  "su.phone.optional": "(اختیاری)",
  "su.phone.placeholder": "+92 3XX XXXXXXX",
  "su.phone.note": "آف لائن ہونے پر ایس ایم ایس الرٹس کے لیے۔",
  "su.password.placeholder": "کم از کم ۸ حروف",
  "su.confirm.label": "پاس ورڈ کی تصدیق کریں",
  "su.confirm.placeholder": "اپنا پاس ورڈ دوبارہ لکھیں",
  "su.strength0": "بہت مختصر",
  "su.strength1": "ٹھیک ہے",
  "su.strength2": "اچھا",
  "su.strength3": "مضبوط",
  "su.terms.prefix": "میں",
  "su.terms.tos": "شرائط خدمت",
  "su.terms.and": "اور",
  "su.terms.privacy": "پرائیویسی پالیسی",
  "su.terms.end": "قبول کرتا ہوں۔",
  "su.submit": "میرا اکاؤنٹ بنائیں",
  "su.submitting": "اکاؤنٹ بن رہا ہے…",
  "su.haveAccount": "پہلے سے اکاؤنٹ ہے؟",
  "app.shell.metadataTitle": "اگروپیو — مصنوعی ذہانت پر مبنی فارم انٹیلیجنس پلیٹ فارم",
  "app.shell.metadataDescription":
    "آج کی رہنمائی، موسم، الرٹس اور اگروپیو کا ہر آلہ — پاکستان کے لیے۔ اپلینوڈ کی پروڈکٹ۔",

  /* ── شیل نیویگیشن ─────────────────────────────────── */
  "app.shell.nav.dashboard": "ڈیش بورڈ",
  "app.shell.nav.farms": "کھیت",
  "app.shell.nav.advisor": "مشیر",
  "app.shell.nav.detect": "تشخیص",
  "app.shell.nav.prices": "قیمتیں",
  "app.shell.nav.weather": "موسم",
  "app.shell.nav.notifications": "اطلاعات",
  "app.shell.nav.settings": "ترتیبات",
  "app.shell.nav.more": "مزید",
  "app.shell.signOut": "لاگ آؤٹ",
  "app.shell.aria.farmerTools": "کسان کے اوزار",
  "app.shell.aria.currentPage": "موجودہ صفحہ",

  /* ── ڈیش بورڈ UI ──────────────────────────────────── */
  "app.dashboard.greeting": "ہیلو، {name}",
  "app.dashboard.aria.profileMenu": "پروفائل مینو",
  "app.dashboard.welcomeEyebrow": "اگروپیو میں خوش آمدید",
  "app.dashboard.welcomeTitle": "اپنا پہلا کھیت شروع کریں۔",
  "app.dashboard.welcomeBody":
    "آپ کی فصل، آپ کی زمین، آپ کا موسم — جب آپ کا کھیت ہوگا تو ہر رہنمائی اس کے مطابق ہوگی۔",
  "app.dashboard.addFirstFarm": "اپنا پہلا کھیت شامل کریں",
  "app.dashboard.badge.today": "آج",
  "app.dashboard.aria.advisoryTitle": "آج کی رہنمائی",
  "app.dashboard.carryToField": "اسے کھیت میں لے جائیں",
  "app.dashboard.askAdvisor": "مشیر سے پوچھیں",
  "app.dashboard.aria.weatherTitle": "موسم \u00b7 {location}",
  "app.dashboard.aria.degreesCelsius": "{n} ڈگری سیلسیس",
  "app.dashboard.fullForecast": "مکمل پیشگوئی",
  "app.dashboard.weatherUnavailable":
    "موسم اس وقت لوڈ نہیں ہو رہا۔ کچھ دیر بعد دوبارہ چیک کریں — آپ کی رہنمائیاں جاری ہیں۔",
  "app.dashboard.seasonTipBadge": "موسمی تجاویز",
  "app.dashboard.alertsHeading": "الرٹس",
  "app.dashboard.newCount": "{n} نئی",
  "app.dashboard.viewAllAlerts": "تمام الرٹس دیکھیں",
  "app.dashboard.noAlerts": "آج کوئی الرٹ نہیں — آپ کی فصلیں سکون میں ہیں۔",
  "app.dashboard.aria.alert": "الرٹ",
  "app.dashboard.severity.critical": "سنگین",
  "app.dashboard.severity.watch": "خبردار",
  "app.dashboard.severity.info": "معلومات",
  "app.dashboard.languageLabel": "زبان",
  "app.dashboard.quickActionsHeading": "فوری اعمال",
  "app.dashboard.cropDoctor": "فصل کا ڈاکٹر",
  "app.dashboard.detectTitle": "بیماری پھیلنے سے پہلے پہچانیں",
  "app.dashboard.detectBody":
    "متاثرے پتے کی تصیر اپلوڈ کریں — فوری تشخیص اور اگلا قدم آپ کے فون پر۔",
  "app.dashboard.myFarms": "میرے کھیت",
  "app.dashboard.addFarm": "کھیت شامل کریں",
  "app.dashboard.health.good": "اچھا",
  "app.dashboard.health.watch": "خبردار",
  "app.dashboard.setupChecklist": "اپنا کھیت ترتیب دیں",
  "app.dashboard.checklistProgress": "{done} میں سے {total} مکمل",
  "app.dashboard.aria.dismissChecklist": "سیٹ اپ چیک لسٹ بند کریں",
  "app.dashboard.aria.setupProgress": "سیٹ اپ کی پیشرفت",
  "app.dashboard.demoFooter": "ڈیمو بلڈ \u00b7 صرف نمونہ ڈیٹا",

  /* ── ڈیش بورڈ ڈیمو ڈیٹا ──────────────────────────── */
  "app.dashboard.demo.todayLabel": "اتوار، 23 اگست",
  "app.dashboard.demo.location": "ملتان، پنجاب",
  "app.dashboard.demo.advisoryCrop": "گندم",
  "app.dashboard.demo.advisoryStage": "سبزی کا مرحلہ",
  "app.dashboard.demo.advisoryAction": "آج آبپاشی میں تاخیر کریں",
  "app.dashboard.demo.advisoryWhy":
    "آج دوپہر کے بعد بارش کا امکان ہے — آپ کا کھیت قدرتی طور پر پانی پائے گا۔",
  "app.dashboard.demo.seasonAction": "بارش آنے سے پہلے اپنے کھیتوں میں چلیں",
  "app.dashboard.demo.seasonWhy":
    "خشک دنوں کے بعد آہستہ چلنا دکھاتا ہے کہ کون سے حصے خراب نکاسی کرتے ہیں — بونے سے پہلے نوٹ کریں۔",
  "app.dashboard.demo.weatherLocation": "ملتان",
  "app.dashboard.demo.weatherCondition": "ابرآلود",
  "app.dashboard.demo.rainNote": "دوپہر 2 بجے کے بعد بارش کا امکان \u00b7 80% امکان",
  "app.dashboard.demo.alertWhitefly":
    "ملتان ضلع میں اس ہفتے کپاس پر سفید مکھی کا خطرہ زیادہ ہے۔",
  "app.dashboard.demo.alertRain":
    "آج دوپہر 2 بجے کے بعد بارش متوقع ہے — چھڑی چھڑکنے کا منصوبہ ملتوی کریں۔",
  "app.dashboard.demo.alertPrice":
    "ملتان مڑی پر گندم کی قیمتیں گزشتہ ہفتے کے مقابلے میں 4% زیادہ ہیں۔",
  "app.dashboard.demo.farm1Name": "خلیل پور کھیت",
  "app.dashboard.demo.farm1Location": "خلیل پور، ملتان",
  "app.dashboard.demo.farm1Crops": "گندم",
  "app.dashboard.demo.farm1Stage": "سبزی کا مرحلہ",
  "app.dashboard.demo.farm2Name": "سہیوال پلاٹ",
  "app.dashboard.demo.farm2Location": "دیپالپور روڈ، سہیوال",
  "app.dashboard.demo.farm2Crops": "کپاس",
  "app.dashboard.demo.farm2Stage": "پھول آنا",
  "app.dashboard.demo.farm3Name": "چک 62 جی بی",
  "app.dashboard.demo.farm3Location": "چک 62 جی بی، فیصل آباد",
  "app.dashboard.demo.farm3Crops": "گنا",
  "app.dashboard.demo.farm3Stage": "پَرچی کا مرحلہ",
  "app.dashboard.demo.checklistAdvisor": "ایک بار مشیر سے پوچھیں",
  "app.dashboard.demo.checklistDetect": "اپنی پہلی تشخیص چلائیں",
  "app.dashboard.demo.actionAdvisor": "مشیر سے پوچھیں",
  "app.dashboard.demo.actionScan": "فصل اسکین کریں",
  "app.dashboard.demo.actionPrices": "قیمتیں چیک کریں",
  "app.dashboard.demo.actionRecord": "ریکارڈ شامل کریں",

  /* ── کھیت عام ──────────────────────────────────────── */
  "app.farms.eyebrow": "کھیت",
  "app.farms.health.good": "اچھا",
  "app.farms.health.watch": "خبردار",
  "app.farms.units.acres": "ایکڑ",
  "app.farms.stages.sowing": "بوائی",
  "app.farms.stages.tillering": "شاخیں نکلنا",
  "app.farms.stages.vegetative": "نباتاتی",
  "app.farms.stages.grainFilling": "دانہ بھرنا",
  "app.farms.stages.ready": "تیار",
  "app.farms.stages.squaring": "فال بندی",
  "app.farms.stages.flowering": "پھول آنا",
  "app.farms.stages.bollFilling": "تہائی بھرنا",
  "app.farms.stages.grandGrowth": "عریض نشوونما",
  "app.farms.stages.ripening": "پکنا",
  "app.farms.stages.harvest": "کٹائی",
  "app.farms.stages.panicleInitiation": "پہنچائپن",

  /* ── ضلع اور فصلیں ─────────────────────────────────── */
  "app.farms.districts.multan": "ملتان",
  "app.farms.districts.sahiwal": "سہیوال",
  "app.farms.districts.faisalabad": "فیصل آباد",
  "app.farms.districts.vehari": "وہاڑی",
  "app.farms.districts.bahawalpur": "بہاولپور",
  "app.farms.districts.lodhran": "لودھراں",
  "app.farms.crops.wheat": "گندم",
  "app.farms.crops.cotton": "کپاس",
  "app.farms.crops.sugarcane": "گنا",
  "app.farms.crops.maize": "مکئی",
  "app.farms.crops.rice": "چاول",

  /* ── کھیتوں کی فہرست ───────────────────────────────── */
  "app.farms.list.pageTitle": "کھیت — اگروپیو",
  "app.farms.list.heading": "آپ کے سارے کھیت، ایک فہرست",
  "app.farms.list.description":
    "ہر کھیت اپنی فصلوں، نشوونما کے مرحلے اور صحت کے ساتھ — ایک نظر میں۔ کھیت کی مکمل کہانی کے لیے ٹیپ کریں۔",
  "app.farms.list.addLink": "شامل کریں",
  "app.farms.list.openFarm": "کھیت کھولیں",
  "app.farms.list.addNewFarm": "نیا کھیت شامل کریں",
  "app.farms.list.emptyHeading": "ابھی تک کوئی کھیت نہیں",

  /* ── نیا کھیت ───────────────────────────────────────── */
  "app.farms.new.pageTitle": "کھیت شامل کریں — اگروپیو",
  "app.farms.new.heading": "کھیت شامل کریں",
  "app.farms.new.description":
    "اگروپیو کو اپنی زمین کے بارے میں بتائیں — مقام، فصل اور رقبہ — تاکہ ہر رہنمائی اس کے مطابق ہو۔",
  "app.farms.new.fields.name": "کھیت کا نام",
  "app.farms.new.placeholders.name": "مثلاً خلیل پور کھیت",
  "app.farms.new.fields.district": "ضلع",
  "app.farms.new.placeholders.district": "ضلع منتخب کریں",
  "app.farms.new.fields.crop": "بنیادی فصل",
  "app.farms.new.placeholders.crop": "فصل منتخب کریں",
  "app.farms.new.fields.acres": "رقبہ (ایکڑ)",
  "app.farms.new.placeholders.acres": "مثلاً ۱۲.۵",
  "app.farms.new.buttons.saving": "محفوظ ہو رہا ہے…",
  "app.farms.new.buttons.save": "کھیت محفوظ کریں",
  "app.farms.new.demoNotice": "ڈیمو — محفوظ کرنا ابھی ڈیٹابیس سے نہیں جڑا",
  "app.farms.new.success.heading": "کھیت ڈیمو میں محفوظ ہو گیا",
  "app.farms.new.success.description":
    "مکمل بلڈ میں یہ کھیت آپ کے ڈیش بورڈ پر دکھائے گا اور رہنمائیاں شکل لینا شروع کریں گی۔",
  "app.farms.new.success.goToFarms": "میرے کھیتوں پر جائیں",
  "app.farms.new.success.backToDashboard": "واپس ڈیش بورڈ پر",
  "app.farms.new.errors.nameRequired": "کھیت کو نام دیں۔",
  "app.farms.new.errors.districtRequired": "ضلع منتخب کریں۔",
  "app.farms.new.errors.cropRequired": "بنیادی فصل منتخب کریں۔",
  "app.farms.new.errors.acresRequired": "رقبہ ایکڑ میں درج کریں۔",

  /* ── کھیت کی تفصیلات ────────────────────────────────── */
  "app.farms.detail.pageTitle": "کھیت کی تفصیلات — اگروپیو",
  "app.farms.detail.heroEyebrow": "کھیت کی تفصیلات",
  "app.farms.detail.goodHealth": "اچھی صحت",
  "app.farms.detail.needsWatching": "توجہ درکار",
  "app.farms.detail.sownLabel": "بوائی",
  "app.farms.detail.seasonHeading": "فصل کہاں ہے",
  "app.farms.detail.activityHeading": "کھیت کی سرگرمی",
  "app.farms.detail.viewAllRecords": "تمام ریکارڈ دیکھیں",
  "app.farms.detail.logFieldEvent": "کھیت کا واقعہ درج کریں",
  "app.farms.detail.scanCrop": "فصل اسکین کریں",

  /* ── ریکارڈ عام ─────────────────────────────────────── */
  "app.records.eyebrow": "کھیت کے ریکارڈ",
  "app.records.types.irrigation": "آبپاشی",
  "app.records.types.fertilizer": "کھاد",
  "app.records.types.pesticide": "کیڑے مار",
  "app.records.types.disease": "بیماری",
  "app.records.types.harvest": "کٹائی",

  /* ── ریکارڈ کی فہرست ───────────────────────────────── */
  "app.records.farmRecords.pageTitle": "کھیت کے ریکارڈ — اگروپیو",
  "app.records.farmRecords.heading": "کھیت کی یادداشت",
  "app.records.farmRecords.description":
    "ہر آبپاشی، اسپرے اور علاج لکھا ہوا — تاکہ اگلے ہفتے کے فیصلے یادداشت پر منحصر نہ ہوں۔",
  "app.records.farmRecords.demoNotice":
    "ڈیمو — صرف نمونہ اندراجات — نئے محفوظ کرنا ابھی نہیں جڑا",

  /* ── نیا ریکارڈ ─────────────────────────────────────── */
  "app.records.new.pageTitle": "نیا ریکارڈ — اگروپیو",
  "app.records.new.heading": "کھیت میں جو ہوا وہ درج کریں",
  "app.records.new.description":
    "آبپاشی، کھاد، کیڑے مار، بیماری اور کٹائی کے اندراجات — آپ کے کھیت کی یادداشت، ایک ایک لائن۔",
  "app.records.new.fields.type": "کیا ہوا؟",
  "app.records.new.fields.farm": "کھیت",
  "app.records.new.placeholders.farm": "کھیت منتخب کریں",
  "app.records.new.fields.date": "تاریخ",
  "app.records.new.fields.title": "مختصر عنوان",
  "app.records.new.fields.optional": "(اختیاری)",
  "app.records.new.placeholders.titleIrrigation": "مثلاً نہری پانی — مکمل کھیت",
  "app.records.new.placeholders.titleOther": "دوسرا چھڑکاؤ پتواروں پر",
  "app.records.new.fields.details": "تفصیلات",
  "app.records.new.placeholders.details":
    "اگلے ہفتے کے لیے جو بھی یاد رکھنا ضروری ہو — مقدار، موسم، کھیت کی صورتحال۔",
  "app.records.new.buttons.saving": "محفوظ ہو رہا ہے…",
  "app.records.new.buttons.save": "ریکارڈ محفوظ کریں",
  "app.records.new.demoNotice": "ڈیمو — محفوظ کرنا ابھی ڈیٹابیس سے نہیں جڑا",
  "app.records.new.success.heading": "ریکارڈ ڈیمو میں محفوظ ہو گیا",
  "app.records.new.success.description":
    "مکمل بلڈ میں یہ اندراج آپ کے کھیت کے ریکارڈ میں شامل ہوگا اور مستقبل کی رہنمائیاں تیز ہوں گی۔",
  "app.records.new.success.backToDashboard": "واپس ڈیش بورڈ پر",
  "app.records.new.success.viewFarms": "میرے کھیت دیکھیں",
  "app.records.new.errors.farmRequired": "منتخب کریں یہ کس کھیت پر ہوا۔",
  "app.records.new.errors.dateRequired": "تاریخ منتخب کریں۔",

  "app.advisor.pageTitle": "مشیر",
  "app.advisor.sidebar.title": "گفتگو",
  "app.advisor.sidebar.newConversation": "نئی گفتگو",
  "app.advisor.sidebar.noConversations": "ابھی کوئی گفتگو نہیں۔ نئی شروع کریں!",
  "app.advisor.sidebar.rename": "نام تبدیل کریں",
  "app.advisor.sidebar.delete": "حذف کریں",
  "app.advisor.sidebar.deleteConfirm": "یہ گفتگو حذف کریں؟ یہ واپس نہیں ہو سکتا۔",
  "app.advisor.sidebar.closeSidebar": "سائڈبار بند کریں",
  "app.advisor.chat.placeholder": "فصل، موسم، قیمتوں کے بارے میں پوچھیں…",
  "app.advisor.chat.send": "بھیجیں",
  "app.advisor.chat.thinking": "سوچ رہا ہوں…",
  "app.advisor.chat.openingGreeting": "السلام علیکم! میں آپ کا اگروپیو زرعی مشیر ہوں۔ فصل، موسم، منڈی کی قیمت، یا سرکاری سکیموں کے بارے میں کچھ بھی پوچھیں۔",
  "app.advisor.chat.photoRedirect": "تصویر سے بیماری کی پہچان ڈیٹیکٹ پیج پر ہے — فصل اسکین کریں پر جائیں۔",
  "app.advisor.chat.nonFarmingRedirect": "میں زراعت کے سوالات میں مدد کے لیے ہوں۔ آپ کی فصل یا کھیت کے بارے میں کیا مدد کر سکتا ہوں؟",
  "app.advisor.chat.tryAsking": "یہ پوچھ کر دیکھیں",
  "app.advisor.chat.suggested1": "میری گندم پر کون سی بیماری لگی ہے؟",
  "app.advisor.chat.suggested2": "کیا آج ملتان میں بارش ہوگی؟",
  "app.advisor.chat.suggested3": "آج منڈی کے نرخ کیا ہیں؟",
  "app.advisor.chat.suggested4": "کسان کارڈ سکیم کے بارے میں بتائیں",
  "app.advisor.errors.serviceUnavailable": "مشیر کی سروس عارضی طور پر دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  "app.advisor.errors.rateLimited": "بہت زیادہ درخواستیں۔ ایک لمحہ رکیں اور دوبارہ کوشش کریں۔",
  "app.advisor.errors.network": "نیٹ ورک کی خرابی۔ اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
  "app.advisor.errors.generic": "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔",
  "app.advisor.aria.openSidebar": "گفتگو کھولیں",
  "app.advisor.aria.sendMessage": "پیغام بھیجیں",
  "app.advisor.aria.chatMessages": "چیٹ پیغامات",
};
