/**
 * Typed translation bundle for the dashboard UI chrome and demo data.
 * Built server-side and passed as props to the client DashboardView.
 */

export type DashboardBundle = {
  greeting: string;
  profileMenu: string;
  welcomeEyebrow: string;
  welcomeTitle: string;
  welcomeBody: string;
  addFirstFarm: string;
  today: string;
  advisoryTitle: string;
  carryToField: string;
  askAdvisor: string;
  weatherTitle: string;
  degreesCelsius: string;
  fullForecast: string;
  weatherUnavailable: string;
  seasonTipBadge: string;
  alertsHeading: string;
  newCount: string;
  viewAllAlerts: string;
  noAlerts: string;
  alertAria: string;
  severityCritical: string;
  severityWatch: string;
  severityInfo: string;
  quickActionsHeading: string;
  cropDoctor: string;
  detectTitle: string;
  detectBody: string;
  recommendCrops: string;
  recommendCropsBody: string;
  myFarms: string;
  addFarm: string;
  viewAllFarms: string;
  healthGood: string;
  healthWatch: string;
  setupChecklist: string;
  checklistProgress: string;
  dismissChecklist: string;
  setupProgress: string;
  languageLabel: string;
  signOut: string;
  pricesWidgetTitle: string;
  pricesWidgetView: string;
  pricesWidgetPerMaund: string;
  pricesWidgetNoTracked: string;
  demo: {
    todayLabel: string;
    location: string;
    advisoryCrop: string;
    advisoryStage: string;
    advisoryAction: string;
    advisoryWhy: string;
    seasonAction: string;
    seasonWhy: string;
    weatherLocation: string;
    weatherCondition: string;
    rainNote: string;
    alertWhitefly: string;
    alertRain: string;
    alertPrice: string;
    farm1Name: string;
    farm1Location: string;
    farm1Crops: string;
    farm1Stage: string;
    farm2Name: string;
    farm2Location: string;
    farm2Crops: string;
    farm2Stage: string;
    farm3Name: string;
    farm3Location: string;
    farm3Crops: string;
    farm3Stage: string;
    checklistAdvisor: string;
    checklistDetect: string;
    actionAdvisor: string;
    actionScan: string;
    actionPrices: string;
    actionRecord: string;
    actionRecommend: string;
  };
};
