const fs = require('fs');
let sd = fs.readFileSync('catalog/sd.ts', 'utf8');

const translations = [
  // Home page
  ['"home.hero.ctaSecondary": "See how it works"', '"home.hero.ctaSecondary": "ڪيئن ڪم ڪري ٿو ڏيکاريو"'],
  ['"home.hero.imageAlt": "Farmer using Agropioo on a tablet in the field"', '"home.hero.imageAlt": "فيڊڊ ۾ ٽيبلٽ تي Agropioo استعمال ڪندو ڪسان"'],
  ['"home.hero.readingCrop": "Crop health"', '"home.hero.readingCrop": "ٻج جي صحت"'],
  ['"home.hero.readingWeather": "Weather"', '"home.hero.readingWeather": "موسم"'],
  ['"home.hero.readingSoil": "Soil moisture"', '"home.hero.readingSoil": "مٹي جي نم"'],
  ['"home.hero.noteExcellent": "Excellent"', '"home.hero.noteExcellent": "xyzcellent"'],
  ['"home.hero.noteClearSky": "Clear sky"', '"home.hero.noteClearSky": "صاف آسمان"'],
  ['"home.hero.noteOptimal": "Optimal"', '"home.hero.noteOptimal": "مناسب"'],
  ['"home.ticker.ariaLabel": "Agropioo platform capabilities"', '"home.ticker.ariaLabel": "Agropioo پليٽ فرم جا صلاحيت"'],
  ['"home.ticker.cropDoctor": "AI crop doctor"', '"home.ticker.cropDoctor": "AI ٻج جو ڊاڪٽر"'],
  ['"home.ticker.satelliteNdvi": "Satellite NDVI monitoring"', '"home.ticker.satelliteNdvi": "سیلیٽ NDVI نگراني"'],
  ['"home.ticker.mandiPrices": "Mandi price intelligence"', '"home.ticker.mandiPrices": "منڊي قيمت انٽيليجنس"'],
  ['"home.ticker.weatherAdvisories": "Weather-aware advisories"', '"home.ticker.weatherAdvisories": "موسم ڄاڻي تي مشورا"'],
  ['"home.ticker.farmRecords": "Digital farm records"', '"home.ticker.farmRecords": "ڊجٽل فارم رڪارڊ"'],
  ['"home.ticker.advisoryLanguages": "Advisory in 7 languages"', '"home.ticker.advisoryLanguages": "7 ڀاڱن ۾ مشورا"'],
  ['"home.ticker.pestAlerts": "Pest outbreak alerts"', '"home.ticker.pestAlerts": "آفات جا اطلاعات"'],
  ['"home.problem.eyebrow": "The problem"', '"home.problem.eyebrow": "مسئلو"'],
  ['"home.problem.title": "Farming decisions shouldn\'t be a guessing game"', '"home.problem.title": "ڪسان جا فيصلا انuman جي کڍ نه ٿي وڃن"'],
  ['"home.problem.kicker": "The cost of guessing is paid at harvest"', '"home.problem.kicker": "انuman جو خرچ ڦڙي ۾ ادا ٿي ٿو"'],
  ['"home.solution.eyebrow": "The solution"', '"home.solution.eyebrow": "حل"'],
  ['"home.solution.titleB": "in one place"', '"home.solution.titleB": "ھڪ ۾"'],
  ['"home.solution.card1Title": "What to do"', '"home.solution.card1Title": "ڪهڙو ڪم ڪريو"'],
  ['"home.solution.card1Answer": "Clear, specific advice for this field, this week."', '"home.solution.card1Answer": "صاف، مخصوص مشورو ھن فيلڊ، ھن هفتي لاءِ."'],
  ['"home.solution.card2Title": "When to do it"', '"home.solution.card2Title": "ڪڏهن ڪم ڪريو"'],
  ['"home.solution.card2Answer": "Timing tuned to real weather and growth stage."', '"home.solution.card2Answer": " REAL موسم ۽ وڌ جي مرحلو تي مبني وقت."'],
  ['"home.solution.card3Title": "What has been done"', '"home.solution.card3Title": "ڪهڙو ڪم ٿيو"'],
  ['"home.solution.card3Answer": "A complete history, always within reach."', '"home.solution.card3Answer": "پوري تاريخ، هميشه پهونچ ۾."'],
  ['"home.features.eyebrow": "Inside the platform"', '"home.features.eyebrow": "پليٽ فرم ۾"'],
  ['"home.features.titleB": "one intelligence platform"', '"home.features.titleB": "هڪ انٽيليجنس پليٽ فرم"'],
  ['"home.features.advisorModule": "Module 01 · Advisor"', '"home.features.advisorModule": "موديول 01 · مشاور"'],
  ['"home.features.advisorTitle": "AI agriculture advisor"', '"home.features.advisorTitle": "AI زراعتي مشاور"'],
  ['"home.features.advisorBadge": "Roman Urdu"', '"home.features.advisorBadge": "رومن اردو"'],
  ['"home.features.advisorFooter": "Ask anything about your crop — everyday questions welcome."', '"home.features.advisorFooter": "ٻج جي باري ۾ ڪجهه پڇو — روزانه سوالون جي استقبال."'],
  ['"home.features.recordsModule": "Module 02 · Records"', '"home.features.recordsModule": "موديول 02 · رڪارڊ"'],
  ['"home.features.recordsTitle": "Digital farm record"', '"home.features.recordsTitle": "ڊجٽل فارم رڪارڊ"'],
  ['"home.features.languageModule": "Module 03 · Language"', '"home.features.languageModule": "موديول 03 · ڀاڱو"'],
  ['"home.features.languageTitle": "Your language, your words"', '"home.features.languageTitle": "توھان جو ڀاڱو، توھان جا لفظ"'],
  ['"home.features.weatherModule": "Module 04 · Weather"', '"home.features.weatherModule": "موديول 04 · موسم"'],
  ['"home.features.weatherTitle": "Weather-aware guidance"', '"home.features.weatherTitle": "موسم ڄاڻي تي راهائتي"'],
  ['"home.features.holdSpray": "Hold spray"', '"home.features.holdSpray": "پري روکو"'],
  ['"home.features.moreLink": "The platform keeps growing — see the full capability stack"', '"home.features.moreLink": "پليٽ فرم وڌي رھي آهي — پوري صلاحيت ڏيکاريو"'],
  ['"home.journey.eyebrow": "How it works"', '"home.journey.eyebrow": "ڪيئن ڪم ڪري ٿو"'],
  ['"home.journey.title": "One question starts the season"', '"home.journey.title": "هڪ سوال موسم شروع ڪري ٿو"'],
  ['"home.journey.step1Title": "Add your farm"', '"home.journey.step1Title": "فارم شامل ڪريو"'],
  ['"home.journey.step2Title": "Ask the AI"', '"home.journey.step2Title": "AI کي پڇو"'],
  ['"home.journey.step3Title": "Get guidance"', '"home.journey.step3Title": "راهائتي حاصل ڪريو"'],
  ['"home.journey.step4Title": "Record activity"', '"home.journey.step4Title": "سرگرمي رڪارڊ ڪريو"'],
  ['"home.journey.step5Title": "Build history"', '"home.journey.step5Title": "تاريخ بڻائيو"'],
  ['"home.journey.step6Title": "Keep monitoring"', '"home.journey.step6Title": "نگراني جاري رکو"'],
  ['"home.matrix.eyebrow": "Full capability stack"', '"home.matrix.eyebrow": "پوري صلاحيت"'],
  ['"home.matrix.capabilitiesLabel": "capabilities"', '"home.matrix.capabilitiesLabel": "صلاحيت"'],
  ['"home.matrix.tier1Name": "Must-Have"', '"home.matrix.tier1Name": "ضروري"'],
  ['"home.matrix.tier1Badge": "Baseline"', '"home.matrix.tier1Badge": "بنياد"'],
  ['"home.matrix.tier2Name": "Differentiators"', '"home.matrix.tier2Name": "فرق"'],
  ['"home.matrix.tier2Badge": "Stand out"', '"home.matrix.tier2Badge": "مolan"'],
  ['"home.matrix.tier3Name": "Wow Factor"', '"home.matrix.tier3Name": "حيرت انگيز"'],
  ['"home.matrix.tier3Badge": "Ahead of the field"', '"home.matrix.tier3Badge": "فيلڊ کان اڳي"'],
  ['"home.vision.eyebrow": "The vision"', '"home.vision.eyebrow": "ڏيڪ"'],
  ['"home.vision.titleB": "Ready for the world."', '"home.vision.titleB": "سڃي لاءِ تيار."'],
  ['"home.vision.pkTitle": "Pakistan-first approach"', '"home.vision.pkTitle": "پاکستان پہرو طريقو"'],
  ['"home.vision.worldTitle": "Global expansion vision"', '"home.vision.worldTitle": "عالمي وڌاڻ ڏيڪ"'],
  ['"home.users.title1": "Individual farmers"', '"home.users.title1": "انفرادي ڪسان"'],
  ['"home.users.title2": "Commercial farms"', '"home.users.title2": "ڪاروباري فارم"'],
  ['"home.users.title3": "Ecosystem partners"', '"home.users.title3": "eco-system partners"'],
  ['"home.users.tagline": "Designed for farmers first — growing with the ecosystem"', '"home.users.tagline": "پہلي ڪسان لاءِ ٺھائي — eco-system سان وڌي"'],
  ['"home.cta.eyebrow": "Early access"', '"home.cta.eyebrow": " EARLY access"'],
  ['"home.cta.title": "Bring your farm onto the platform"', '"home.cta.title": "فارم پليٽ فرم تي آڻيو"'],
  ['"home.cta.emailLabel": "Email address"', '"home.cta.emailLabel": "اي ميل پتو"'],
  ['"home.cta.fineprint": "No spam. Unsubscribe anytime."', '"home.cta.fineprint": "spam نه. ڪنھن وقت unsubscribe ڪريو."'],
  ['"home.footer.privacy": "Privacy Policy"', '"home.footer.privacy": "رازداري پاليسئ"'],
  ['"home.footer.terms": "Terms of Service"', '"home.footer.terms": "سروس جا شرائطو"'],
  ['"home.footer.cookies": "Cookie Policy"', '"home.footer.cookies": "ڪوڪي پاليسئ"'],
  ['"home.footer.disclaimer": "Disclaimer"', '"home.footer.disclaimer": "Disclaaimer"'],
  ['"home.footer.contactHeading": "Get in touch"', '"home.footer.contactHeading": "راairobi ۾ اچو"'],
  ['"home.footer.country": "Pakistan"', '"home.footer.country": "پاکستان"'],
  ['"home.footer.motto": "Built for Pakistan · Ready for the world"', '"home.footer.motto": "پاکستان لاءِ ٺھائي · سڃي لاءِ تيار"'],
  // Hiw page
  ['"hiw.hero.eyebrow": "How it works"', '"hiw.hero.eyebrow": "ڪيئن ڪم ڪري ٿو"'],
  ['"hiw.hero.titleB": "smarter season."', '"hiw.hero.titleB": "سمارٽ موسم."'],
  ['"hiw.hero.browseFeatures": "Browse features"', '"hiw.hero.browseFeatures": "خصوصيت ڏيکاريو"'],
  ['"hiw.route.navLabel": "The six steps of the Agropioo season loop"', '"hiw.route.navLabel": "Agropioo موسم لوپ جا چھ قدم"'],
  ['"hiw.route.stop1": "Add farm"', '"hiw.route.stop1": "فارم شامل"'],
  ['"hiw.route.stop3": "Guidance"', '"hiw.route.stop3": "راهائتي"'],
  ['"hiw.route.stop5": "Record"', '"hiw.route.stop5": "رڪارڊ"'],
  ['"hiw.route.stop6": "Better advice"', '"hiw.route.stop6": "بهترين مشورو"'],
  ['"hiw.setup.eyebrow": "Set up once"', '"hiw.setup.eyebrow": "ھڪ ڀيِّ سيٽ ڪريو"'],
  ['"hiw.setup.title": "Your farm becomes a living profile"', '"hiw.setup.title": "فارم هڪ زندہ پروفائل بڻي ٿو"'],
  ['"hiw.setup.mockHeading": "New farm profile"', '"hiw.setup.mockHeading": "نئون فارم پروفائل"'],
  ['"hiw.setup.mockButton": "Create farm profile"', '"hiw.setup.mockButton": "فارم پروفائل ٺھائيو"'],
  ['"hiw.setup.mockFootnote": "Takes less than a minute"', '"hiw.setup.mockFootnote": "ھڪ منشن کان کم وڳي ٿو"'],
  ['"hiw.setup.rowDistrict": "District"', '"hiw.setup.rowDistrict": "ضلع"'],
  ['"hiw.setup.valDistrict": "Multan"', '"hiw.setup.valDistrict": "ملتان"'],
  ['"hiw.setup.valSowing": "20 Nov"', '"hiw.setup.valSowing": "20 نومبر"'],
  ['"hiw.setup.valLand": "12 acres"', '"hiw.setup.valLand": "12 اڪر"'],
  ['"hiw.ask.eyebrow": "Ask anything"', '"hiw.ask.eyebrow": "ڪجهه پڇو"'],
  ['"hiw.ask.titleB": "Your whole farm answers."', '"hiw.ask.titleB": "توھان جو ڪل فارم جواب ڏي ٿو."'],
  ['"hiw.ask.checkedAgainst": "Checked against"', '"hiw.ask.checkedAgainst": "ت motz ڪري"'],
  ['"hiw.ask.chipValCrop": "Wheat · tillering"', '"hiw.ask.chipValCrop": "گندم · ٽيلرنگ"'],
  ['"hiw.ask.chipDistrict": "District"', '"hiw.ask.chipDistrict": "ضلع"'],
  ['"hiw.ask.chipValDistrict": "Multan"', '"hiw.ask.chipValDistrict": "ملتان"'],
  ['"hiw.ask.chipWeather": "Weather"', '"hiw.ask.chipWeather": "موسم"'],
  ['"hiw.ask.chipHistory": "History"', '"hiw.ask.chipHistory": "تاريخ"'],
  ['"hiw.ask.chipValHistory": "Urea 9 days ago"', '"hiw.ask.chipValHistory": "يوريا 9 ڏينهن پاڻ"'],
  ['"hiw.ask.footnote": "Type it, speak it, or call it in — the answer stays personal"', '"hiw.ask.footnote": "ٽائپ ڪريو، بوليو، يا ڪال ڪريو — جواب شخصي رھي ٿو"'],
  ['"hiw.engine.eyebrow": "Behind the answer"', '"hiw.engine.eyebrow": "جواب کان پاڻ"'],
  ['"hiw.engine.title": "Four checks before you see one line"', '"hiw.engine.title": "هڪ ليڪ ڏيکارڻ کان پاڻ چار چيڪ"'],
  ['"hiw.engine.check1Title": "Gather"', '"hiw.engine.check1Title": "ايکٽو ڪريو"'],
  ['"hiw.engine.check2Title": "Cross-check"', '"hiw.engine.check2Title": "ڪراس چيڪ"'],
  ['"hiw.engine.check3Title": "Personalise"', '"hiw.engine.check3Title": "شخصي ڪريو"'],
  ['"hiw.engine.check4Title": "Deliver"', '"hiw.engine.check4Title": "پهونچائيو"'],
  ['"hiw.engine.safetyStrong": "If something looks unsafe,"', '"hiw.engine.safetyStrong": "ڪجهه خطرناڪ نظر اچي،"'],
  ['"hiw.record.recorderHeading": "Log an activity"', '"hiw.record.recorderHeading": "سرگرمي رڪارڊ ڪريو"'],
  ['"hiw.record.syncBadge": "Auto-sync on"', '"hiw.record.syncBadge": "آٹو سنڪ ON"'],
  ['"hiw.record.actionIrrigation": "Irrigation"', '"hiw.record.actionIrrigation": "آبياري"'],
  ['"hiw.record.actionFertiliser": "Fertiliser"', '"hiw.record.actionFertiliser": "کيڪ"'],
  ['"hiw.record.actionPesticide": "Pesticide"', '"hiw.record.actionPesticide": "ڪمائي دوا"'],
  ['"hiw.record.actionDisease": "Disease"', '"hiw.record.actionDisease": "بيماري"'],
  ['"hiw.record.actionExpense": "Expense"', '"hiw.record.actionExpense": "خرچ"'],
  ['"hiw.record.actionHarvest": "Harvest"', '"hiw.record.actionHarvest": "ڦڙي"'],
  ['"hiw.record.row1Time": "Today · 6:40 AM"', '"hiw.record.row1Time": "اڄ · 6:40 صبح"'],
  ['"hiw.record.row1Label": "Irrigation logged"', '"hiw.record.row1Label": "آبياري رڪارڊ"'],
  ['"hiw.record.row1Detail": "Canal turn · 40 min · plot B"', '"hiw.record.row1Detail": "نيهر · 40 منٽ · plot B"'],
  ['"hiw.record.row2Time": "Yesterday"', '"hiw.record.row2Time": "ڪل"'],
  ['"hiw.record.row2Label": "Fertiliser logged"', '"hiw.record.row2Label": "کيڪ رڪارڊ"'],
  ['"hiw.record.row2Detail": "DAP 20 kg / acre"', '"hiw.record.row2Detail": "DAP 20 kg / اڪر"'],
  ['"hiw.record.eyebrow": "Record as you go"', '"hiw.record.eyebrow": "جئن وڃو رڪارڊ ڪريو"'],
  ['"hiw.record.titleB": "smarter answers all season"', '"hiw.record.titleB": "سمارٽ جواب ڪل موسم"'],
  ['"hiw.record.point1": "Irrigation, inputs, disease, expenses, harvest — one timeline"', '"hiw.record.point1": "آبياري، ڍ⛓، بيماري، خرچ، ڦڙي — هڪ ٽايم لائن"'],
  ['"hiw.record.point2": "Works fully offline; syncs when signal returns"', '"hiw.record.point2": "مکمل آف لائن ڪم ڪري ٿو؛ سنڪ واپس اچي تInSection سنڪ ڪري ٿو"'],
  ['"hiw.record.point3": "Season summary ready for banks, buyers, or insurance"', '"hiw.record.point3": "موسم جا خلاصه بينڪ، خريدار، يا بيمه لاءِ تيار"'],
  ['"hiw.loop.eyebrow": "The season loop"', '"hiw.loop.eyebrow": "موسم لوپ"'],
  ['"hiw.loop.titleB": "It starts there."', '"hiw.loop.titleB": "هتي شروع ٿي ٿو."'],
  ['"hiw.loop.benefit1Title": "Advice compounds"', '"hiw.loop.benefit1Title": "مشاوري جمع ٿي"'],
  ['"hiw.loop.benefit2Title": "Nothing gets repeated"', '"hiw.loop.benefit2Title": "ڪجهه دوباره نه ٿي"'],
  ['"hiw.loop.benefit3Title": "Every season documented"', '"hiw.loop.benefit3Title": "هر موسم دستاويز"'],
  ['"hiw.loop.stepImprove": "Improve"', '"hiw.loop.stepImprove": "بہتري"'],
  ['"hiw.loop.diagramLabel": "Circular loop diagram: ask, act, record, learn, improve"', '"hiw.loop.diagramLabel": "گول لوپ ڊائڳرام: پڇو، عمل ڪريو، رڪارڊ، ڏienes، بہتري"'],
  ['"hiw.loop.centerSeason": "SEASON"', '"hiw.loop.centerSeason": "موسم"'],
];

let ok = 0, fail = 0;
for (const [from, to] of translations) {
  if (sd.includes(from)) {
    sd = sd.replace(from, to);
    ok++;
  } else {
    console.log('NOT FOUND:', from.substring(0, 65));
    fail++;
  }
}

fs.writeFileSync('catalog/sd.ts', sd);
console.log(`Landing: ${ok} replaced, ${fail} not found.`);
