const fs = require('fs');
let sd = fs.readFileSync('catalog/sd.ts', 'utf8');

const translations = [
  // Vision page
  ['"vp.hero.eyebrow": "Our vision"', '"vp.hero.eyebrow": "индн ڏيڪ"'],
  ['"vp.hero.titleLead": "A trusted advisor in"', '"vp.hero.titleLead": "قابلِ اعتماد مشاور"'],
  ['"vp.hero.titleAccent": "every farmer\'s pocket."', '"vp.hero.titleAccent": "هر ڪسان جي جيب ۾."'],
  ['"vp.hero.tagStart": "Start where the need is greatest"', '"vp.hero.tagStart": "هتي شروع ڪريو جتي ضرورت سڀ کان وڌيڪ آهي"'],
  ['"vp.hero.tagThen": "Then earn the world"', '"vp.hero.tagThen": "پڏين سڃ حاصل ڪريو"'],
  ['"vp.hero.ctaLink": "See what we built"', '"vp.hero.ctaLink": "indhne ڪهڙو ٺھائي سو ڏيکاريو"'],
  ['"vp.beliefs.eyebrow": "What we believe"', '"vp.beliefs.eyebrow": "indhne ڪهڙو يقين ڪري ٿا"'],
  ['"vp.beliefs.b1Title": "Growth"', '"vp.beliefs.b1Title": "وڌاڻ"'],
  ['"vp.beliefs.b1Desc": "Living crops, healthy land, prosperous farmers."', '"vp.beliefs.b1Desc": "زندہ ٻج، صحت مند زمين، خوشحال ڪسان."'],
  ['"vp.beliefs.b2Title": "Intelligence"', '"vp.beliefs.b2Title": "انٽيليجنس"'],
  ['"vp.beliefs.b2Desc": "AI grounded in local weather, history, and crop science."', '"vp.beliefs.b2Desc": "AI مقامي موسم، تاريخ، ۽ ٻج سائنس تي مبني."'],
  ['"vp.beliefs.b3Title": "Accessibility"', '"vp.beliefs.b3Title": "رسائي"'],
  ['"vp.beliefs.b3Desc": "Guidance in the farmer\'s own language and context."', '"vp.beliefs.b3Desc": "ڪسان جي پنھن جي ڀاڱي ۽ سياق ۾ راهائتي."'],
  ['"vp.beliefs.b4Desc": "Practical, timely advice that protects livelihoods."', '"vp.beliefs.b4Desc": "عملي، بيهنگو مشورو جي ڪسان جي رزقي بچائي ٿو."'],
  ['"vp.beliefs.b5Title": "Future"', '"vp.beliefs.b5Title": "مستقبل"'],
  ['"vp.beliefs.b5Desc": "Scalable technology that respects tradition."', '"vp.beliefs.b5Desc": " Tecchnology جي وڌيڪ ۽ روايت جي عزت."'],
  ['"vp.horizons.eyebrow": "The road ahead"', '"vp.horizons.eyebrow": "اڳي جو راستو"'],
  ['"vp.horizons.h1Tag": "Horizon 01"', '"vp.horizons.h1Tag": "افق 01"'],
  ['"vp.horizons.h1Status": "In the fields"', '"vp.horizons.h1Status": "فيلڊن ۾"'],
  ['"vp.horizons.h1P2": "Six languages"', '"vp.horizons.h1P2": "چھ ڀاڱا"'],
  ['"vp.horizons.h1P3": "Real-farmer refinement"', '"vp.horizons.h1P3": "ڪسان جي تجربن تي بہتري"'],
  ['"vp.horizons.h2Tag": "Horizon 02"', '"vp.horizons.h2Tag": "افق 02"'],
  ['"vp.horizons.h2Status": "Broadening"', '"vp.horizons.h2Status": "وڌيڪ وڃي رھا آهي"'],
  ['"vp.horizons.h2P2": "Data integrations"', '"vp.horizons.h2P2": "ڊيٽا ڊائڻ"'],
  ['"vp.horizons.h2P3": "Advanced analytics"', '"vp.horizons.h2P3": "لاڳو analytics"'],
  ['"vp.horizons.h3Tag": "Horizon 03"', '"vp.horizons.h3Tag": "افق 03"'],
  ['"vp.horizons.h3Status": "Global"', '"vp.horizons.h3Status": "عالمي"'],
  ['"vp.horizons.h3P1": "New countries"', '"vp.horizons.h3P1": "نئنا ملڪ"'],
  ['"vp.horizons.h3P3": "Global platform"', '"vp.horizons.h3P3": "عالمي پليٽ فرم"'],
  ['"vp.outcomes.eyebrow": "What success looks like"', '"vp.outcomes.eyebrow": "ڪامپrhahi ڪيئن نظر اچي ٿي"'],
  ['"vp.outcomes.o1Title": "Better decisions"', '"vp.outcomes.o1Title": "بهترين فيصلا"'],
  ['"vp.outcomes.o1Desc": "Every choice — water, input, timing — backed by data instead of habit."', '"vp.outcomes.o1Desc": "هر اختيار — پانهَن، ڍ⛓، وقت — ڊيٽا تي مبني عادت کان بدلاءِ."'],
  ['"vp.outcomes.o2Title": "Higher productivity"', '"vp.outcomes.o2Title": "وڌيڪ پيداوار"'],
  ['"vp.outcomes.o2Desc": "Healthy crops, well-timed inputs, and harvests picked at their peak."', '"vp.outcomes.o2Desc": "صحت مند ٻج، ڍ⛓، ۽ ڦڙي اوجھ تي."'],
  ['"vp.outcomes.o3Title": "Fewer avoidable losses"', '"vp.outcomes.o3Title": "کم نقصان"'],
  ['"vp.outcomes.o3Desc": "Disease, pests, and weather caught early — before they take the yield."', '"vp.outcomes.o3Desc": "بيماري، آفات، ۽ موسم پهري کان پڏي — پيداوار کان پاڻ."'],
  ['"vp.outcomes.o4Title": "Farms run like businesses"', '"vp.outcomes.o4Title": "ڪاروبار جئن فارم"'],
  ['"vp.outcomes.o4Desc": "Structured records and season intelligence that banks and buyers respect."', '"vp.outcomes.o4Desc": "ساختي رڪارڊ ۽ موسم انٽيليجنس جن کي بينڪ ۽ خريدار عزت ڏي ٿا."'],
  ['"vp.principles.eyebrow": "Non-negotiables"', '"vp.principles.eyebrow": "غير قابلِ مذاکره"'],
  ['"vp.principles.c1Title": "Farmer benefit leads"', '"vp.principles.c1Title": "ڪسان جو فائدو پهري"'],
  ['"vp.principles.c1Desc": "Every feature starts from the field\'s need — never from the technology."', '"vp.principles.c1Desc": "هر خصوصيت فيلڊ جي ضرورت کان شروع — ڪبھي ٽيڪنالاجي کان نه."'],
  ['"vp.principles.c2Title": "Language first"', '"vp.principles.c2Title": "ڀاڱو پهري"'],
  ['"vp.principles.c2Desc": "Every screen and every answer arrives in the farmer\'s own language."', '"vp.principles.c2Desc": "هر اسڪرين ۽ هر جواب ڪسان جي پنھن جي ڀاڱي ۾ اڃي ٿو."'],
  ['"vp.principles.c3Title": "Sunlight readable"', '"vp.principles.c3Title": "سوري جي روشني ۾ قابلِ پڑھڻ"'],
  ['"vp.principles.c3Desc": "High contrast designed for the midday sun, not just the office."', '"vp.principles.c3Desc": "وڌيڪ contrast دوپاھر جي سوري لاءِ، ڪفيش ڪل تي نه."'],
  ['"vp.principles.c4Title": "Plain words"', '"vp.principles.c4Title": "سادي لفظ"'],
  ['"vp.principles.c4Desc": "Simple enough that one neighbour can explain it to another."', '"vp.principles.c4Desc": "itto سادو ته هڪ ٻيا ٻيان کي سمجھائي سکي."'],
  ['"vp.principles.c5Title": "Phones before everything"', '"vp.principles.c5Title": " telefon ڀالڙي سڀ"'],
  ['"vp.principles.c5Desc": "Mobile-first, big touch targets — farming lives on phones now."', '"vp.principles.c5Desc": "موبائل پهري، وڏا ٽچ ٽارگيٽ — ڪسان ھاڻي ٿائيفون تي آهن."'],
  ['"vp.principles.c6Title": "Natural by design"', '"vp.principles.c6Title": "قَدري ٺڻي"'],
  ['"vp.principles.c6Desc": "Motion and layout that feel organic — growth, never machinery."', '"vp.principles.c6Desc": "حرڪت ۽ ليآؤٽ جي قَدري احساس — وڌاڻ، ڪبھي مشينري نه."'],
  ['"vp.principles.motto": "Soil and signal — growing together"', '"vp.principles.motto": "مٹي ۽ نشان — ھڪٿي وڌي"'],
  // Why page
  ['"wy.hero.eyebrow": "Why Agropioo"', '"wy.hero.eyebrow": "Agropioo ڇو"'],
  ['"wy.hero.titleLead": "Where soil meets"', '"wy.hero.titleLead": "مٹي ملائي"'],
  ['"wy.hero.titleAccent": "signal"', '"wy.hero.titleAccent": "نشان"'],
  ['"wy.hero.ctaPrimary": "Get early access"', '"wy.hero.ctaPrimary": "EARLY access حاصل ڪريو"'],
  ['"wy.hero.ctaSecondary": "Explore the platform"', '"wy.hero.ctaSecondary": "پليٽ فرم جائڻ ڪريو"'],
  ['"wy.hero.tagStart": "Built for Pakistan"', '"wy.hero.tagStart": "پاکستان لاءِ ٺھائي"'],
  ['"wy.hero.tagThen": "A product of Aplinode"', '"wy.hero.tagThen": "Aplinode جو product"'],
  ['"wy.hero.svgLabel": "Stylised furrow curves rolling across a field"', '"wy.hero.svgLabel": "فيڊڊ ۾ گھمڻي حروف"'],
  ['"wy.origin.eyebrow": "Why we built this"', '"wy.origin.eyebrow": "indhne ڇو ٺھائي"'],
  ['"wy.origin.banner": "The cost of guessing is paid at harvest"', '"wy.origin.banner": "انuman جو خرچ ڦڙي ۾ ادا ٿي ٿو"'],
  ['"wy.diff.eyebrow": "What makes it different"', '"wy.diff.eyebrow": "ڇو فرق آهي"'],
  ['"wy.diff.chip1": "Your crop"', '"wy.diff.chip1": "توھان جو ٻج"'],
  ['"wy.diff.chip2": "Your district"', '"wy.diff.chip2": "توھان جو ضلع"'],
  ['"wy.diff.chip3": "This week\'s weather"', '"wy.diff.chip3": "ھن هفتي جو موسم"'],
  ['"wy.diff.chip4": "Your last season"', '"wy.diff.chip4": "توھان جو پڏيل موسم"'],
  ['"wy.diff.pakTitle": "Pakistan-first"', '"wy.diff.pakTitle": "پاکستان پهري"'],
  ['"wy.diff.pakBadge": "Built here first"', '"wy.diff.pakBadge": "هتي پهري ٺھائي"'],
  ['"wy.life.eyebrow": "What the advisor covers"', '"wy.life.eyebrow": "مشاور ڪهڙن شيءن جي حڪومت ڪري ٿو"'],
  ['"wy.life.s1Title": "Irrigation timing"', '"wy.life.s1Title": "آبياري جو وقت"'],
  ['"wy.life.s1Desc": "Know when to water — and when to wait."', '"wy.life.s1Desc": "پانهَن ڇڏڻ جو وقت ڄاڻو — ۽ انتظار جو وقت."'],
  ['"wy.life.s2Title": "Crop planning"', '"wy.life.s2Title": "ٻج منصوبن بنياد"'],
  ['"wy.life.s2Desc": "Choose crops and sowing windows suited to your land."', '"wy.life.s2Desc": "ٻج ۽ ڦڙين جا وينڊو چونڊيو زمين لاءِ مناسب."'],
  ['"wy.life.s3Desc": "The right input, at the right dose, at the right moment."', '"wy.life.s3Desc": "درست ڍ⛓، درست ڊوز، درست لمحي."'],
  ['"wy.life.s4Desc": "Spot problems early and act before they spread."', '"wy.life.s4Desc": "مسئلن پهري پڇو ۽ ۽يٽ کان پاڻ عمل ڪريو."'],
  ['"wy.life.s5Title": "Harvest timing"', '"wy.life.s5Title": "ڦڙي جو وقت"'],
  ['"wy.life.s5Desc": "Pick at the moment that protects yield and quality."', '"wy.life.s5Desc": "پيداوار ۽ معنيت بچائڻ جي لمحي ڏيڏي."'],
  ['"wy.life.s6Title": "Weather-aware recommendations"', '"wy.life.s6Title": "موسم ڄاڻي تي سفارش"'],
  ['"wy.life.s6Desc": "Every advisory reads today\'s conditions first."', '"wy.life.s6Desc": "هر مشورو پهري اڄ جي حالت پڇي ٿو."'],
  ['"wy.life.s7Title": "Everyday questions"', '"wy.life.s7Title": "روزانه سوال"'],
  ['"wy.life.s7Desc": "Ask anything about your crop, any day of the season."', '"wy.life.s7Desc": "ٻج جي باري ۾ ڪجهه پڇو، موسم جي ڪنھن ڏينهن."'],
  ['"wy.value.eyebrow": "The promise"', '"wy.value.eyebrow": "واعده"'],
  ['"wy.value.p1Heading": "What to do"', '"wy.value.p1Heading": "ڪهڙو ڪم ڪريو"'],
  ['"wy.value.p1Desc": "Clear, specific recommendations for your crop and conditions — not generic tips."', '"wy.value.p1Desc": "صاف، مخصوص سفارش ٻج ۽ حالت لاءِ — عام ٽپس نه."'],
  ['"wy.value.p2Heading": "When to do it"', '"wy.value.p2Heading": "ڪڏهن ڪم ڪريو"'],
  ['"wy.value.p2Desc": "Timing tuned to real weather and growth stage, so the right action lands at the"', '"wy.value.p2Desc": "REAL موسم ۽ وڌ جي مرحلو تي مبني وقت، درست عمل هتي وڃي."'],
  ['"wy.value.p3Heading": "What has been done"', '"wy.value.p3Heading": "ڪهڙو ڪم ٿيو"'],
  ['"wy.value.p3Desc": "A structured history of every activity — always within reach, always feeding bet"', '"wy.value.p3Desc": "هر سرگرمي جي ساختي تاريخ — هميشه پهونچ ۾، هميشه بهتري لاءِ."'],
  ['"wy.who.eyebrow": "Who it serves"', '"wy.who.eyebrow": "ڪن لاءِ آهي"'],
  ['"wy.who.a1Title": "Individual farmers"', '"wy.who.a1Title": "انفرادي ڪسان"'],
  ['"wy.who.a3Title": "Ecosystem partners"', '"wy.who.a3Title": "eco-system partners"'],
  ['"wy.who.strip": "Growing with the ecosystem around the farm"', '"wy.who.strip": "فارم جي گرد eco-system سان وڌي"'],
];

let ok = 0, fail = 0;
for (const [from, to] of translations) {
  if (sd.includes(from)) {
    sd = sd.replace(from, to);
    ok++;
  } else {
    console.log('NOT FOUND:', from.substring(0, 65));
    fail++;
  }
}

fs.writeFileSync('catalog/sd.ts', sd);
console.log(`VP/WY: ${ok} replaced, ${fail} not found.`);
