const fs = require('fs');
let sd = fs.readFileSync('catalog/sd.ts', 'utf8');

const translations = [
  ['"app.crops.eyebrow": "Crop recommendation"', '"app.crops.eyebrow": "ٻج جي سفارش"'],
  ['"app.crops.title": "What should I plant this season?"', '"app.crops.title": "ھن موسم ڇڙي ڇڙي؟"'],
  ['"app.crops.form.seasonLabel": "Target season"', '"app.crops.form.seasonLabel": "موسم چونڊيو"'],
  ['"app.crops.form.yearLabel": "Target year"', '"app.crops.form.yearLabel": "سال چونڊيو"'],
  ['"app.crops.form.soilLabel": "Soil type"', '"app.crops.form.soilLabel": "مٹي جو قسم"'],
  ['"app.crops.form.irrigationLabel": "Irrigation"', '"app.crops.form.irrigationLabel": "آبياري"'],
  ['"app.crops.form.budgetLabel": "Budget bracket"', '"app.crops.form.budgetLabel": "بجٽ ڊڍن"'],
  ['"app.crops.form.soilOther": "Not sure / Other"', '"app.crops.form.soilOther": "ڳاڙهو نه / ٻيو"'],
  ['"app.crops.form.submit": "Get recommendations"', '"app.crops.form.submit": "سفارش حاصل ڪريو"'],
  ['"app.crops.form.noFarm": "Add a farm first to get recommendations."', '"app.crops.form.noFarm": "سفارش حاصل ڪرڻ لاءِ پهلي فارم شامل ڪريو."'],
  ['"app.crops.form.geoError": "Recommendations are only available for farms in Pakistan."', '"app.crops.form.geoError": "سفارش پاکستان ۾ فارم لاءِ ڪل دستياب آهي."'],
  ['"app.crops.seasons.summer": "Summer"', '"app.crops.seasons.summer": "گرمي"'],
  ['"app.crops.seasons.winter": "Winter"', '"app.crops.seasons.winter": "ڇيُني"'],
  ['"app.crops.seasons.autumn": "Autumn"', '"app.crops.seasons.autumn": "خORIZ"'],
  ['"app.crops.seasons.spring": "Spring"', '"app.crops.seasons.spring": "بهاڙ"'],
  ['"app.crops.soil.sandy_loam": "Sandy loam"', '"app.crops.soil.sandy_loam": "ريتلي لوم"'],
  ['"app.crops.soil.clay_loam": "Clay loam"', '"app.crops.soil.clay_loam": "ميتي لوم"'],
  ['"app.crops.soil.saline": "Saline"', '"app.crops.soil.saline": "نوٻري"'],
  ['"app.crops.soil.other": "Not sure / Other"', '"app.crops.soil.other": "ڳاڙهو نه / ٻيو"'],
  ['"app.crops.budget.low": "Low (up to Rs 25,000/acre)"', '"app.crops.budget.low": "گهٽ (Rs 25,000/اڪر ۾)"'],
  ['"app.crops.budget.very_high": "Very high (over Rs 120,000/acre)"', '"app.crops.budget.very_high": "بہت وڌيڪ (Rs 120,000/اڪر کان وڌيڪ)"'],
  ['"app.crops.irrigation.rainfed": "Rainfed"', '"app.crops.irrigation.rainfed": "پانهَن تي منحصر"'],
  ['"app.crops.irrigation.tubewell": "Tubewell"', '"app.crops.irrigation.tubewell": "ٽيوب ويل"'],
  ['"app.crops.results.title": "Your top 3 crops"', '"app.crops.results.title": "توھان جا 3 بهترين ٻج"'],
  ['"app.crops.results.revenue": "Est. revenue/acre"', '"app.crops.results.revenue": "اَنuman آمدن/اڪر"'],
  ['"app.crops.results.reason": "Why this crop"', '"app.crops.results.reason": "ھي ٻج ڇو"'],
  ['"app.crops.results.risks": "Key risks"', '"app.crops.results.risks": "مکيٽا خطر"'],
  ['"app.crops.results.saveToPlan": "Save to farm plan"', '"app.crops.results.saveToPlan": "فارم منصوبن تي بچائيو"'],
  ['"app.crops.results.saved": "Saved to plan"', '"app.crops.results.saved": "منصوبن تي بچائي وئو"'],
  ['"app.crops.results.compare": "Compare crops"', '"app.crops.results.compare": "ٻج جي ترقي ڪريو"'],
  ['"app.crops.results.sourceWeather": "weather"', '"app.crops.results.sourceWeather": "موسم"'],
  ['"app.crops.results.sourceMarket": "market"', '"app.crops.results.sourceMarket": "بازار"'],
  ['"app.crops.results.regenerate": "Regenerate"', '"app.crops.results.regenerate": "نئون بڻائيو"'],
  ['"app.crops.results.alreadyExists": "You already have a recommendation for this farm, season, and year."', '"app.crops.results.alreadyExists": "توھان کي اڳhed ھن فارم، موسم، ۽ سال لاءِ سفارش آهي."'],
  ['"app.crops.results.viewExisting": "View existing"', '"app.crops.results.viewExisting": "موجودہ ڏيکاريو"'],
  ['"app.crops.results.noCandidates": "No crop matches your season and budget. Try a higher budget bracket."', '"app.crops.results.noCandidates": "بجٽ ڊڍن وڌيڪ وڃو."'],
  ['"app.crops.results.replacedPlan": "Replaced your previous plan for this season."', '"app.crops.results.replacedPlan": "ھن موسم لاءِ توھان جي پڏيل منصوبو بدلائي وئو."'],
  ['"app.crops.detail.title": "Recommendation detail"', '"app.crops.detail.title": "سفارش تفصيل"'],
  ['"app.crops.detail.back": "Back to recommendations"', '"app.crops.detail.back": "سفارشن تي واپس"'],
  ['"app.crops.detail.confidence": "Confidence"', '"app.crops.detail.confidence": "إيثار"'],
  ['"app.crops.detail.scoreBreakdown": "Score breakdown"', '"app.crops.detail.scoreBreakdown": "نمبر جي تفصيل"'],
  ['"app.crops.detail.suitability": "Suitability"', '"app.crops.detail.suitability": "مناسب بند"'],
  ['"app.crops.detail.weatherFit": "Weather fit"', '"app.crops.detail.weatherFit": "موسم ميل"'],
  ['"app.crops.detail.profitability": "Profitability"', '"app.crops.detail.profitability": "نافع بخش"'],
  ['"app.crops.detail.risk": "Risk (lower is better)"', '"app.crops.detail.risk": "خطر (کم بھتر)"'],
  ['"app.crops.detail.sustainability": "Sustainability"', '"app.crops.detail.sustainability": "پائيداري"'],
  ['"app.crops.detail.final": "Final score"', '"app.crops.detail.final": "آخري نمبر"'],
  ['"app.crops.detail.soilImpact": "Soil impact"', '"app.crops.detail.soilImpact": "مٹي تي اثر"'],
  ['"app.crops.water.medium": "Medium"', '"app.crops.water.medium": "درميانا"'],
  ['"app.crops.confidence.medium": "Medium"', '"app.crops.confidence.medium": "درميانا"'],
  ['"app.crops.confidence.unreliable": "Unreliable"', '"app.crops.confidence.unreliable": "قابلِ اعتماد نه"'],
  ['"app.crops.risk.price_volatility": "Price volatility"', '"app.crops.risk.price_volatility": "قيمت جي اُڏهييال"'],
  ['"app.crops.risk.pest_pressure": "Pest pressure"', '"app.crops.risk.pest_pressure": "آفات جا خطر"'],
  ['"app.crops.risk.weather": "Weather risk"', '"app.crops.risk.weather": "موسم جو خطر"'],
  ['"app.crops.risk.water_stress": "Water stress"', '"app.crops.risk.water_stress": "پانهَن جي تناؤ"'],
  ['"app.crops.risk.input_cost": "Input cost"', '"app.crops.risk.input_cost": "ڍ⛓ خرچ"'],
  ['"app.crops.soilImpact.improves": "Improves soil"', '"app.crops.soilImpact.improves": "مٹي ۾ بہتري"'],
  ['"app.crops.soilImpact.neutral": "Neutral"', '"app.crops.soilImpact.neutral": "bilambit"'],
  ['"app.crops.soilImpact.depletes": "Depletes soil"', '"app.crops.soilImpact.depletes": "مٹي خراب ڪري"'],
  ['"app.crops.compare.title": "Compare your top crops"', '"app.crops.compare.title": "بهترين ٻج جي ترقي ڪريو"'],
  ['"app.crops.compare.close": "Close comparison"', '"app.crops.compare.close": "بند ڪريو"'],
  ['"app.crops.compare.revenue": "Est. revenue/acre"', '"app.crops.compare.revenue": "اَنuman آمدن/اڪر"'],
  ['"app.crops.compare.duration": "Growing days"', '"app.crops.compare.duration": "وڌڻ جا ڏينهن"'],
  ['"app.crops.compare.water": "Water need"', '"app.crops.compare.water": "پانهَن جي ضرورت"'],
  ['"app.crops.compare.marketRisk": "Market risk"', '"app.crops.compare.marketRisk": "بازار جو خطر"'],
  ['"app.crops.compare.soilImpact": "Soil impact"', '"app.crops.compare.soilImpact": "مٹي تي اثر"'],
  ['"app.crops.compare.labour": "Labour cost"', '"app.crops.compare.labour": "مzenia خرچ"'],
  ['"app.crops.compare.chartUnavailable": "Chart unavailable — showing the table instead."', '"app.crops.compare.chartUnavailable": "چارٽ دستياب نه — ۽ي جڳھ ڏيکاريو."'],
  ['"app.crops.compare.selectToSave": "Select a crop to save"', '"app.crops.compare.selectToSave": "بچائڻ لاءِ ٻج چونڊيو"'],
  ['"app.crops.compare.saveSelected": "Save selected"', '"app.crops.compare.saveSelected": "چونڊيل بچائيو"'],
  ['"app.crops.rotation.title": "Crop rotation plan"', '"app.crops.rotation.title": "ٻج مودي منصوبو"'],
  ['"app.crops.rotation.subtitle": "What to plant next to keep your soil healthy."', '"app.crops.rotation.subtitle": "مٹي صحت مند رکڻ لاءِ ڇڙي ڇڙي."'],
  ['"app.crops.rotation.generic": "Generic advice — based on common practice, not your field history."', '"app.crops.rotation.generic": "عام مشورو — عام عمل تي مبني، فيلڊ تاريخ تي نه."'],
  ['"app.crops.catalogue.empty": "No crops match this filter."', '"app.crops.catalogue.empty": "ھن فلٽر سان ڪوئي ٻج ميل نه کڻي."'],
  ['"app.crops.errors.serviceUnavailable": "Recommendation service is temporarily unavailable. Please retry."', '"app.crops.errors.serviceUnavailable": "سفارش سروس عارضي طور تي دستياب نه آهي. ٻڌي ڪوشش ڪريو."'],
  ['"app.crops.errors.generic": "Something went wrong. Please try again."', '"app.crops.errors.generic": "ڪجهه خراب ٿيو. ٻڌي ڪوشش ڪريو."'],
  ['"app.crops.errors.notFound": "Recommendation not found."', '"app.crops.errors.notFound": "سفارش نه ملي."'],
  ['"app.crops.errors.rateLimited": "Too many requests. Please wait a moment."', '"app.crops.errors.rateLimited": "بہت گهرن. ٻڌي ڪنھن کان پاڻ ٿڌي ڪوشش ڪريو."'],
  ['"app.crops.rotation.wheat_then_mung": "Mung bean fixes nitrogen after wheat."', '"app.crops.rotation.wheat_then_mung": "مونگ ڳنم کان پاڻ نائogenein بند ڪري."'],
  ['"app.crops.rotation.wheat_then_chickpea": "Chickpea builds soil after wheat."', '"app.crops.rotation.wheat_then_chickpea": "چنا ڳنم کان پاڻ مٹي بڻائي ٿو."'],
  ['"app.crops.rotation.wheat_then_cotton": "Cotton is a common follow-on after wheat in Punjab."', '"app.crops.rotation.wheat_then_cotton": "ڪپاس پنجاب ۾ ڳنم کان پاڻ عام آهي."'],
  ['"app.crops.rotation.cotton_then_wheat": "Wheat restores the field after cotton."', '"app.crops.rotation.cotton_then_wheat": "گندم ڪپاس کان پاڻ فيلڊ واپس آڻي ٿو."'],
  ['"app.crops.rotation.cotton_then_maize": "Maize follows cotton on good land."', '"app.crops.rotation.cotton_then_maize": "مڪئي ڪپاس کان پاڻ اچي ٿو."'],
  ['"app.crops.rotation.rice_then_wheat": "Classic kharif-to-rabi rice then wheat sequence."', '"app.crops.rotation.rice_then_wheat": "کاريف-تو-ربي چاول ۽ ڳم جو ترتيب."'],
  ['"app.crops.rotation.rice_then_maize": "Maize after paddy uses residual moisture."', '"app.crops.rotation.rice_then_maize": "مڪئي چاول کان پاڻ باقي پانهَن وڃي."'],
  ['"app.crops.rotation.maize_then_potato": "Potato follows maize on loamy soils."', '"app.crops.rotation.maize_then_potato": "آلو مڪئي کان پاڻ لومي مٹي تي."'],
  ['"app.crops.rotation.maize_then_wheat": "Wheat after maize keeps the rotation productive."', '"app.crops.rotation.maize_then_wheat": "گندم مڪئي کان پاڻ مودي وڌائي رکي ٿو."'],
  ['"app.crops.rotation.potato_then_maize": "Maize follows potato."', '"app.crops.rotation.potato_then_maize": "مڪئي آلو کان پاڻ اچي ٿو."'],
  ['"app.crops.rotation.sugarcane_then_maize": "Maize after ratoon sugarcane."', '"app.crops.rotation.sugarcane_then_maize": "مڪئي茎inha کان پاڻ."'],
  ['"app.crops.rotation.mung_then_wheat": "Wheat after a pulse restores fertility."', '"app.crops.rotation.mung_then_wheat": "گندم مونگ کان پاڻ زرخيزي واپس آڻي ٿو."'],
  ['"app.crops.rotation.chickpea_then_cotton": "Cotton after a legume benefits from fixed nitrogen."', '"app.crops.rotation.chickpea_then_cotton": "ڪپاس چنا کان پاڻ نائogenein benefit وڃي."'],
  ['"app.crops.rotation.mustard_then_cotton": "Cotton after mustard oilseed."', '"app.crops.rotation.mustard_then_cotton": "ڪپاس رائي کان پاڻ."'],
  ['"app.crops.rotation.soybean_then_wheat": "Wheat after soybean."', '"app.crops.rotation.soybean_then_wheat": "گندم سويابين کان پاڻ."'],
  ['"app.crops.rotation.onion_then_maize": "Maize after onion on a fertile bed."', '"app.crops.rotation.onion_then_maize": "مڪئي پياز کان پاڻ زرخيز بستي تي."'],
  ['"app.crops.rotation.tomato_then_wheat": "Wheat after tomato."', '"app.crops.rotation.tomato_then_wheat": "گندم ٽماٽو کان پاڻ."'],
];

let ok = 0, fail = 0;
for (const [from, to] of translations) {
  if (sd.includes(from)) {
    sd = sd.replace(from, to);
    ok++;
  } else {
    console.log('NOT FOUND:', from.substring(0, 65));
    fail++;
  }
}

fs.writeFileSync('catalog/sd.ts', sd);
console.log(`Crops: ${ok} replaced, ${fail} not found.`);
