const fs = require('fs');
let sd = fs.readFileSync('catalog/sd.ts', 'utf8');

const translations = [
  ['"app.detect.eyebrow": "Crop doctor"', '"app.detect.eyebrow": "ٻج جو ڊاڪٽر"'],
  ['"app.detect.title": "Spot disease before it spreads"', '"app.detect.title": "۽يٽ کان پاڻ بيماري پڇو"'],
  ['"app.detect.uploadPrompt": "Photograph the sick leaf"', '"app.detect.uploadPrompt": "بيمار پتي جو فوٹو"'],
  ['"app.detect.takePhoto": "Take or choose a photo"', '"app.detect.takePhoto": "فوٹو وڃو يا چونڊيو"'],
  ['"app.detect.sampleScan": "No photo handy? Run a sample scan"', '"app.detect.sampleScan": "فوٹو نه آهي؟ نمونا اسڪين چالو ڪريو"'],
  ['"app.detect.readingLeaf": "Reading the leaf…"', '"app.detect.readingLeaf": "پتي لوڊ ڪري..."'],
  ['"app.detect.analyzing": "Analyzing…"', '"app.detect.analyzing": "ٻڌايو ڪري..."'],
  ['"app.detect.scanAnother": "Scan another leaf"', '"app.detect.scanAnother": "ٻيو پتو اسڪين ڪريو"'],
  ['"app.detect.discussAdvisor": "Discuss with advisor"', '"app.detect.discussAdvisor": "مشاور سان ڳالهابين"'],
  ['"app.detect.saveToFarm": "Save to farm"', '"app.detect.saveToFarm": "فارم تي بچائيو"'],
  ['"app.detect.savedToFarm": "Saved to {farm}"', '"app.detect.savedToFarm": "{farm} تي بچائي وئو"'],
  ['"app.detect.notSaved": "Not saved"', '"app.detect.notSaved": "بچائي نه وئو"'],
  ['"app.detect.confidence": "Confidence {pct}%"', '"app.detect.confidence": "إيثار {pct}%"'],
  ['"app.detect.whatToDo": "What to do now"', '"app.detect.whatToDo": "ھاڻي ڪهڙو ڪم ڪريو"'],
  ['"app.detect.caution": "Always confirm treatment with your local agriculture office before spraying."', '"app.detect.caution": "هميشه پري ڪرڻ کان پاڻ علاج کي مقامي زراعت دفتر سان تائيد ڪريو."'],
  ['"app.detect.noFarmsTitle": "Register a farm first"', '"app.detect.noFarmsTitle": "پهلي فارم رجسٽر ڪريو"'],
  ['"app.detect.noFarmsBody": "Link your scans to a farm to build a full disease history."', '"app.detect.noFarmsBody": "بوري بيماري جي تاريخ بڻڻ لاءِ اسڪينن کي فارم سان جوڑيو."'],
  ['"app.detect.addFarm": "Add farm"', '"app.detect.addFarm": "فارم شامل ڪريو"'],
  ['"app.detect.dismiss": "I\'ll do this later"', '"app.detect.dismiss": "مون ھو پاڻ ڪندس"'],
  ['"app.detect.pastScans": "Past scans"', '"app.detect.pastScans": "پڏيل اسڪين"'],
  ['"app.detect.loadMore": "Load more"', '"app.detect.loadMore": "وڌيڪ لوڊ ڪريو"'],
  ['"app.detect.invalidFile": "Please upload an image file."', '"app.detect.invalidFile": "مھرباني ڪري تصوير فائل اپلوڊ ڪريو."'],
  ['"app.detect.serviceUnavailable": "Service temporarily unavailable. Please try again."', '"app.detect.serviceUnavailable": "سروس عارضي طور تي دستياب نه آهي. ٻڌي ڪوشش ڪريو."'],
  ['"app.detect.noDiagnosis": "Could not identify the disease — try a clearer photo of the affected area."', '"app.detect.noDiagnosis": "بيماري پڌران نه سکي — متاثر علاقو جو صاف تر فوٹو وڃو."'],
  ['"app.detect.retry": "Retry"', '"app.detect.retry": "دوباره ڪريو"'],
  ['"app.detect.savedStatus": "Saved to {farm}"', '"app.detect.savedStatus": "{farm} تي بچائي وئو"'],
  ['"app.detect.unsavedStatus": "Not saved"', '"app.detect.unsavedStatus": "بچائي نه وئو"'],
  ['"app.detect.dragDropPrompt": "Drag an image here or click to browse"', '"app.detect.dragDropPrompt": "تصوير هتي ڇڏيو يا ڳڻي لاءِ ڪليڪ ڪريو"'],
  ['"app.detect.dragDropPromptLine1": "Drag an image here"', '"app.detect.dragDropPromptLine1": "تصوير هتي ڇڏيو"'],
  ['"app.detect.dragDropPromptLine2": "or click to browse"', '"app.detect.dragDropPromptLine2": "يا ڳڻي لاءِ ڪليڪ ڪريو"'],
  ['"app.detect.historyEmpty": "No scans yet. Take a photo to begin."', '"app.detect.historyEmpty": "اڃا اسڪين نه آهن. شروع لاءِ فوٹو وڃو."'],
  ['"app.detect.linkToFarm": "Link to a farm"', '"app.detect.linkToFarm": "فارم سان جوڑيو"'],
  ['"app.detect.severity.watch": "Watch"', '"app.detect.severity.watch": "ڇاڻو"'],
  ['"app.detect.severity.treatNow": "Treat Now"', '"app.detect.severity.treatNow": "ھاڻي علاج ڪريو"'],
  ['"app.detect.severity.clear": "Clear"', '"app.detect.severity.clear": "صاف"'],
  ['"app.detect.chat.newScan": "New scan"', '"app.detect.chat.newScan": "نئون اسڪين"'],
  ['"app.detect.chat.placeholder": "Ask about this detection..."', '"app.detect.chat.placeholder": "ھن پڇن جي باري ۾ پڇو..."'],
  ['"app.detect.chat.send": "Send"', '"app.detect.chat.send": "ڇڏيو"'],
  ['"app.detect.chat.thinking": "Thinking..."', '"app.detect.chat.thinking": "سوچ ڪري..."'],
  ['"app.detect.chat.imagePreview": "View full image"', '"app.detect.chat.imagePreview": "پوري تصوير ڏيکاريو"'],
  ['"app.detect.chat.closePreview": "Close preview"', '"app.detect.chat.closePreview": "بند ڪريو"'],
  ['"app.detect.chat.emptyState": "Ask a follow-up question about this detection."', '"app.detect.chat.emptyState": "ھن پڇن جي باري ۾ دريتي سوال پڇو."'],
  ['"app.detect.chat.sessionsTitle": "Detection chats"', '"app.detect.chat.sessionsTitle": "پڇو ڳالهابين"'],
  ['"app.detect.chat.noSessions": "No detection chats yet."', '"app.detect.chat.noSessions": "اڃا ڳالهابين نه آهن."'],
  ['"app.detect.chat.deleteSession": "Delete session"', '"app.detect.chat.deleteSession": "سسشن ڊليٽ ڪريو"'],
  ['"app.detect.chat.deleteConfirm": "Are you sure you want to delete this chat?"', '"app.detect.chat.deleteConfirm": "توھان کي ڳاڙهو آهي ته ھي ڳالهابين ڊليٽ ڪرڻو آهي؟"'],
  ['"app.detect.chat.cancel": "Cancel"', '"app.detect.chat.cancel": "منسوخ"'],
  ['"app.detect.sidebar.title": "History"', '"app.detect.sidebar.title": "تاريخ"'],
  ['"app.detect.sidebar.newScan": "New scan"', '"app.detect.sidebar.newScan": "نئون اسڪين"'],
  ['"app.detect.sidebar.closeSidebar": "Close sidebar"', '"app.detect.sidebar.closeSidebar": "بند ڪريو"'],
  ['"app.detect.sidebar.noHistory": "No scans or chats yet."', '"app.detect.sidebar.noHistory": "اڃا اسڪين يا ڳالهابين نه آهن."'],
  ['"app.detect.sidebar.scansTitle": "Past scans"', '"app.detect.sidebar.scansTitle": "پڏيل اسڪين"'],
  ['"app.detect.sidebar.chatsTitle": "Chat sessions"', '"app.detect.sidebar.chatsTitle": "ڳالهابين سسشن"'],
  ['"app.detect.crop.apple": "Apple"', '"app.detect.crop.apple": "aiser"'],
  ['"app.detect.crop.blueberry": "Blueberry"', '"app.detect.crop.blueberry": "بليو بيري"'],
  ['"app.detect.crop.cherry": "Cherry"', '"app.detect.crop.cherry": "چيري"'],
  ['"app.detect.crop.corn": "Corn"', '"app.detect.crop.corn": "مڪئي"'],
  ['"app.detect.crop.grape": "Grape"', '"app.detect.crop.grape": "ڏاڍ"'],
  ['"app.detect.crop.orange": "Orange"', '"app.detect.crop.orange": "مالټا"'],
  ['"app.detect.crop.peach": "Peach"', '"app.detect.crop.peach": "آڑو"'],
  ['"app.detect.crop.pepper": "Pepper"', '"app.detect.crop.pepper": "مرچ"'],
  ['"app.detect.crop.potato": "Potato"', '"app.detect.crop.potato": "آلو"'],
  ['"app.detect.crop.raspberry": "Raspberry"', '"app.detect.crop.raspberry": "ریزبری"'],
  ['"app.detect.crop.soybean": "Soybean"', '"app.detect.crop.soybean": "سويابين"'],
  ['"app.detect.crop.squash": "Squash"', '"app.detect.crop.squash": "کدو"'],
  ['"app.detect.crop.strawberry": "Strawberry"', '"app.detect.crop.strawberry": "اسٽرابيري"'],
  ['"app.detect.crop.tomato": "Tomato"', '"app.detect.crop.tomato": "ٽماٽو"'],
  ['"app.detect.rescan.7": "Scan again in 7 days"', '"app.detect.rescan.7": "7 ڏينهن کان پاڻ نئون اسڪين ڪريو"'],
  ['"app.detect.rescan.14": "Scan again in 14 days"', '"app.detect.rescan.14": "14 ڏينهن کان پاڻ نئون اسڪين ڪريو"'],
  ['"app.detect.rescan.21": "Scan again in 21 days"', '"app.detect.rescan.21": "21 ڏينهن کان پاڻ نئون اسڪين ڪريو"'],
  ['"app.detect.healthy.name": "Healthy"', '"app.detect.healthy.name": "صحت مند"'],
  ['"app.detect.healthy.causes": "No disease symptoms were detected on this leaf."', '"app.detect.healthy.causes": "ھن پتي تي ڪوئي بيماري علامت نه هو."'],
  ['"app.detect.healthy.steps.0": "No treatment needed. Resume normal care and scouting."', '"app.detect.healthy.steps.0": "علاج جي ضرورت نه. عامcare ۽ ڳولا جاري رکو."'],
  ['"app.detect.disease.apple_scab.name": "Apple scab"', '"app.detect.disease.apple_scab.name": "aiser soh"'],
  ['"app.detect.disease.apple_black_rot.name": "Apple black rot"', '"app.detect.disease.apple_black_rot.name": "aiser ڪريهو ڳنڍ"'],
  ['"app.detect.disease.apple_cedar_rust.name": "Cedar-apple rust"', '"app.detect.disease.apple_cedar_rust.name": "سيڊر-aiser زنگ"'],
  ['"app.detect.disease.cherry_powdery_mildew.name": "Cherry powdery mildew"', '"app.detect.disease.cherry_powdery_mildew.name": "چيري پائڻeri mildew"'],
  ['"app.detect.disease.corn_gray_leaf_spot.name": "Gray leaf spot"', '"app.detect.disease.corn_gray_leaf_spot.name": "مڪئي پتي جي ڪاله ڦوڙي"'],
  ['"app.detect.disease.corn_common_rust.name": "Corn common rust"', '"app.detect.disease.corn_common_rust.name": "مڪئي عام زنگ"'],
  ['"app.detect.disease.corn_northern_leaf_blight.name": "Northern leaf blight"', '"app.detect.disease.corn_northern_leaf_blight.name": "اتر پتي جي ٻلهار"'],
  ['"app.detect.disease.grape_black_rot.name": "Grape black rot"', '"app.detect.disease.grape_black_rot.name": "ڏاڍ ڪريهو ڳنڍ"'],
  ['"app.detect.disease.grape_esca.name": "Grape esca (black measles)"', '"app.detect.disease.grape_esca.name": "ڏاڍ esca (ڪريهو ڳنڍ)"'],
  ['"app.detect.disease.grape_leaf_blight.name": "Grape leaf blight (Isariopsis)"', '"app.detect.disease.grape_leaf_blight.name": "ڏاڍ پتي جي ٻلهار (Isariopsis)"'],
  ['"app.detect.disease.orange_huanglongbing.name": "Citrus greening (Huanglongbing)"', '"app.detect.disease.orange_huanglongbing.name": "سائٽس وريーンنگ (Huanglongbing)"'],
  ['"app.detect.disease.peach_bacterial_spot.name": "Peach bacterial spot"', '"app.detect.disease.peach_bacterial_spot.name": "آڑو بايڪٽريائي ڦوڙي"'],
  ['"app.detect.disease.pepper_bacterial_spot.name": "Pepper bacterial spot"', '"app.detect.disease.pepper_bacterial_spot.name": "مرچ بايڪٽريائي ڦوڙي"'],
  ['"app.detect.disease.potato_early_blight.name": "Potato early blight"', '"app.detect.disease.potato_early_blight.name": "آلو早期 ٻلهار"'],
  ['"app.detect.disease.potato_late_blight.name": "Potato late blight"', '"app.detect.disease.potato_late_blight.name": "آلو وڏي ٻلهار"'],
  ['"app.detect.disease.squash_powdery_mildew.name": "Squash powdery mildew"', '"app.detect.disease.squash_powdery_mildew.name": "کدو پائڻeri mildew"'],
  ['"app.detect.disease.strawberry_leaf_scorch.name": "Strawberry leaf scorch"', '"app.detect.disease.strawberry_leaf_scorch.name": "اسٽرابيري پتي جي سوھ"'],
  ['"app.detect.disease.tomato_bacterial_spot.name": "Tomato bacterial spot"', '"app.detect.disease.tomato_bacterial_spot.name": "ٽماٽو بايڪٽريائي ڦوڙي"'],
  ['"app.detect.disease.tomato_early_blight.name": "Tomato early blight"', '"app.detect.disease.tomato_early_blight.name": "ٽماٽو早期 ٻلهار"'],
  ['"app.detect.disease.tomato_late_blight.name": "Tomato late blight"', '"app.detect.disease.tomato_late_blight.name": "ٽماٽو وڏي ٻلهار"'],
  ['"app.detect.disease.tomato_leaf_mold.name": "Tomato leaf mold"', '"app.detect.disease.tomato_leaf_mold.name": "ٽماٽو پتي جي ٻلهار"'],
  ['"app.detect.disease.tomato_septoria.name": "Tomato septoria leaf spot"', '"app.detect.disease.tomato_septoria.name": "ٽماٽو septoria پتي جي ڦوڙي"'],
  ['"app.detect.disease.tomato_spider_mites.name": "Tomato spider mites"', '"app.detect.disease.tomato_spider_mites.name": "ٽماٽو مڪڙي"'],
  ['"app.detect.disease.tomato_target_spot.name": "Tomato target spot"', '"app.detect.disease.tomato_target_spot.name": "ٽماٽو هدف ڦوڙي"'],
  ['"app.detect.disease.tomato_ylcv.name": "Tomato yellow leaf curl virus"', '"app.detect.disease.tomato_ylcv.name": "ٽماٽو پيتو پتي وائرس"'],
  ['"app.detect.disease.tomato_mosaic_virus.name": "Tomato mosaic virus"', '"app.detect.disease.tomato_mosaic_virus.name": "ٽماٽو موزيڪ وائرس"'],
];

let ok = 0, fail = 0;
for (const [from, to] of translations) {
  if (sd.includes(from)) {
    sd = sd.replace(from, to);
    ok++;
  } else {
    console.log('NOT FOUND:', from.substring(0, 65));
    fail++;
  }
}

fs.writeFileSync('catalog/sd.ts', sd);
console.log(`Detect: ${ok} replaced, ${fail} not found.`);
