/**
 * Types for the offline write queue (specs/offline-pwa/spec.md §3-5).
 * Queued writes are stored in IndexedDB and replayed by lib/offline/drain.ts
 * when connectivity returns. Each entry carries a client-side UUID so the
 * server can deduplicate via ON CONFLICT (client_uuid) DO NOTHING.
 */

/** HTTP method for the queued request. */
export type QueuedMethod = "POST" | "PATCH" | "PUT" | "DELETE";

/**
 * Client-side connectivity status.
 * `online` is true when the browser is connected.
 * `canConnect` is true when a DNS check succeeds, catching captive portals.
 */
export interface OfflineStatus {
  online: boolean;
  canConnect: boolean;
}

/** A single write action stored in the offline queue. */
export interface QueuedWrite {
  /** Auto-generated UUID v4 on enqueue; primary key in the `writes` store. */
  uuid: string;
  /** Logical endpoint (e.g. "/api/records"); stored so the URL can be rebuilt. */
  url: string;
  method: QueuedMethod;
  /** The request payload — JSON-serialized body, FormData entries, or null. */
  body: string | null;
  /** When the write was queued (ms since epoch). */
  queuedAt: number;
  /**
   * UUID generated by the client and forwarded to the server as `client_uuid`.
   * On replay, the server uses ON CONFLICT (client_uuid) DO NOTHING to skip
   * already-persisted writes (idempotency).
   */
  clientUuid: string;
  /** Optional dependency: this write only sends after `dependsOn` succeeds. */
  dependsOn: string | null;
  /** Monotonic attempt count for exponential backoff (FR-12). */
  attempts: number;
  /** Timestamp of the next scheduled retry (ms since epoch). */
  retryAt: number;
  /** Server response code from the last attempt, or null if never tried. */
  lastStatus: number | null;
  /** Error message from the last attempt, or null if never tried. */
  lastError: string | null;
}

/** Internal record persisted to IndexedDB in the `writes` object store. */
export interface WriteRecord {
  uuid: string;
  url: string;
  method: QueuedMethod;
  body: string | null;
  queuedAt: number;
  clientUuid: string;
  dependsOn: string | null;
  attempts: number;
  retryAt: number;
  lastStatus: number | null;
  lastError: string | null;
}

/** Result of draining the queue for one page load. */
export interface DrainResult {
  /** UUIDs of writes that were successfully sent (or deduped by the server). */
  succeeded: string[];
  /** UUIDs of writes that failed and remain in the queue for the next drain. */
  failed: string[];
  /** UUIDs of writes that were skipped because a dependency failed. */
  skipped: string[];
}

/** Cap on how many writes can sit in the pending queue at once. */
export const MAX_PENDING_WRITES = 200;

/** Hard ceiling for a single drain session (FR-12: 60s). */
export const DRAIN_TIMEOUT_MS = 60_000;

/** Base delay for exponential backoff (ms). */
export const BACKOFF_BASE_MS = 1_000;
